### ISSUE TITLE
samtools view -hr option retains all @HD records

### ISSUE THREAD

**Issue by web80863** [samtools/samtools#1002]
While using samtools view -hr <rg> multiple_rg.bam (version 1.9) to select a single read group from a multiple read group bam file, the output file contains the header information including the proper @HD record for the selected <rg>, but it also adds @HD records for all the other <rg>s in the file.  The additional @HD records cause errors when trying to use the resulting single <rg> bam file.

**Comment by daviesrob** [comment]
There should only ever be one `@HD` line, if present at all.  Do you mean `@RG`, and if so what errors do they cause?

PS. Please put `@RG` etc. in backquotes, otherwise github treats it as a username and sends unwanted notifications.

**Comment by valeriuo** [comment]
If still the case, reopen with the requested information.
