### ISSUE TITLE
killed:9 when mpileup

### ISSUE THREAD

**Issue by valery-shap** [samtools/samtools#1004]
Hello,

I have 111.111 reads from Nanopore, genome size 5,6 Mbp. Reads were aligned by minimap2 => sam file.
Then sam to bam: ./samtools view -b -o file.bam file.sam
sort bam file and index, also reference is indexed.
Then I wanted to use mpileup for variant calling and used this command:
./samtools mpileup -f file.fasta -o test.vcf -v file-sorted.bam
That's what I see:
[warning] samtools mpileup option `v` is functional, but deprecated. Please switch to using bcftools mpileup in future.

[mpileup] 1 samples in 1 input files

Killed: 9

What could be the reason of this? Is something wrong with command or maybe problems with laptop ram and threads?

my version is 1.9-49-gb321ed1 (using htslib 1.9-70-gf0b8337).

**Comment by daviesrob** [comment]
Something external to samtools killed it (signal 9 is the KILL signal which terminates a process unconditionally).

If you were running on a laptop, the most likely explanation is that you ran out of memory and the out-of-memory killer terminated samtools.  This will usually leave a trace in the system logs, try running `dmesg`, or look in `/var/log/syslog`.

It's likely that the BAQ alignment used a lot of memory on one of your long Nanopore reads.  You could try using the `-B` option to disable it.  I'm afraid that if you do want BAQ, the only other quick fix would be to find a machine with more available memory.

**Comment by valery-shap** [comment]
Thank you very much for the answer.
Today I tried to do the same using the computer with 24 threads and a lot of RAM. And I had the same killed9.
Then found this issue: https://github.com/lh3/minimap2/issues/6
I aligned by minimap2 again but now with -L flag to work with >65535 CIGAR operations. Suppose that w/o this flag I had wrong BAM file (when samtools sam to bam). But i view it in igv and everything looks ok.
Then i tried to mpileup again with this new file and again killed.
So i decided to try htsbox: pileup -q10 -vcf ref.fa sorted.bam > var.vcf as in issue#6. As the result i had a huge file with about all my 5,6Mbp as variants. Smth wrong. Is htsbox used only for asm-to-asm alignment?
All this is for variant calling of whole genome.

**Comment by daviesrob** [comment]
I can't comment on htsbox.  Did you try using the `-B` option with Samtools?

Without this option, it can use a lot of memory if you have a long read that has a large number of inserted or deleted bases compared to the reference used.

**Comment by valery-shap** [comment]
A night of waiting and there is neither killed9 nor result with vcf file...

**Comment by valery-shap** [comment]
Thank you for the help.
It was long but worked!
