### ISSUE TITLE
plot-bamstats error on gnu-plot

### ISSUE THREAD

**Issue by callumparr** [samtools/samtools#1006]
#### Are you using the latest version of [samtools](https://github.com/samtools/samtools/releases/latest) and [HTSlib](https://github.com/samtools/htslib/releases/latest)? If not, please specify.
(run `samtools --version`)
Current version 1.9 installed via conda install samtools
Updated 2/2/19 using conda install samtools

 #### Please describe your environment.
- OS (run `uname -sr` on Linux/Mac OS or ` wmic os get Caption, Version` on Windows)
Darwin 18.2.0 
- machine architecture (run `uname -m` on Linux/Mac OS or ` wmic os get OSArchitecture` on Windows)
x86_64
- compiler (run `gcc --version` or `clang --version`)
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/usr/include/c++/4.2.1
Apple LLVM version 10.0.0 (clang-1000.11.45.5)
Target: x86_64-apple-darwin18.2.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin

#### Please specify the steps taken to generate the issue, the command you are running and the relevant output.

long cDNA reads in fastq taken through porechop to trim adapters to generate none.fastq 
mapped against hg38.mmi index using minimap2 to give none_minimap2.sam

samtools stats -d -@ 4 none_minimap2 > none_minimap2.sam.stats

CMD 

`plot-bamstats -p ~/Sync_later/plot_bamstats/ ~/Sync_later/none_minimap2.sam.stats`

Output 

`set terminal png size 600,400 truecolor
             ^
"/Users/callum/Sync_later/plot_bamstats/acgt-cycles.gp", line 2: unknown or ambiguous terminal type; type just 'set terminal' for a list

The command exited with non-zero status 256:
	gnuplot /Users/callum/Sync_later/plot_bamstats/acgt-cycles.gp

 at /Users/callum/miniconda3/bin/plot-bamstats line 51.
	main::error("The command exited with non-zero status 256:\x{a}\x{9}gnuplot /Users/"...) called at /Users/callum/miniconda3/bin/plot-bamstats line 317
	main::plot("/Users/callum/Sync_later/plot_bamstats/acgt-cycles.gp") called at /Users/callum/miniconda3/bin/plot-bamstats line 855
	main::plot_acgt_cycles(HASH(0x100864308)) called at /Users/callum/miniconda3/bin/plot-bamstats line 34`

**Comment by daviesrob** [comment]
What version of `gnuplot` do you have, and what does it say if you type `set terminal`?

I'm surprised that it doesn't like `png`.

**Comment by callumparr** [comment]
ah I see, set terminal outputs nothing and then rerunning my command it gives same error. set terminal should give a list if I understand correctly but actually it didn't return anything. 

I think there is some issue in installation with gnulpot, so I will remove and reinstall and see what happens.
