### ISSUE TITLE
Bam indexing error-the samtools index command for just 1 chromosome is also not working in this case, the following error is showing [E::hts_idx_push] Region 536871288..536871299 cannot be stored in a bai index. Try using a csi index with min_shift = 14, n_lvls >= 6 samtools index: failed to create index for P2R1R2_aln_sorted.bam": Numerical result out of range.

### ISSUE THREAD

**Issue by Humiras** [samtools/samtools#1011]
#### Are you using the latest version of [samtools](https://github.com/samtools/samtools/releases/latest) and [HTSlib](https://github.com/samtools/htslib/releases/latest)? If not, please specify.
(run `samtools --version`)

 #### Please describe your environment.
- OS (run `uname -sr` on Linux/Mac OS or ` wmic os get Caption, Version` on Windows)
- machine architecture (run `uname -m` on Linux/Mac OS or ` wmic os get OSArchitecture` on Windows)
- compiler (run `gcc --version` or `clang --version`)

**Comment by jkbonfield** [comment]
This is a fundamental limit of the BAI index format.  It cannot cope with chromosomes longer than 512Mb as it was designed with assumptions around human genomes.

Try `samtools index -c` to request a CSI instead instead.  This has the BAI limitations removed.

**Comment by Humiras** [comment]
We have used -C CSI option but the file cannot be used in IGV.

**Comment by jkbonfield** [comment]
Ah,  that's going to be a problem then.  I suggest you make a request to IGV as what you want is basically impossible right now short of artificially splitting up the chromosomes to smaller pieces.

**Comment by valeriuo** [comment]
IGV should have support for [CSI indexes](https://github.com/igvteam/igv/commit/7a7353e498f2f73b785143a51a5a41053754a2ac), starting version [2.4.17](https://github.com/igvteam/igv/releases/tag/v2.4.17).

**Comment by Humiras** [comment]
I have good SAM file but after calling SNPs I have only N`s in alternate allele. Please suggest me what can be the problem. I wanted to check in IGV but it is not showing any reads

**Comment by valeriuo** [comment]
> I have good SAM file but after calling SNPs I have only N`s in alternate allele.

This is a different issue from the one you initially stated. Please fill in the issue template, which you left blank in your first comment, and also change the title to something shorter and indicative of your problem.

**Comment by sheepyuanyang** [comment]
samtools old version v0.1.13 could sovle this problem.
Nevertheless, I am still doubt why the lastest version of samtools couldn't support long chromosome (>512Mb).
