### ISSUE TITLE
bam_header_t members non-existent in latest version of samtools.

### ISSUE THREAD

**Issue by Matthew-Mosior** [samtools/samtools#1012]
Referring to release [0.2.0-rc1](https://github.com/samtools/samtools/commit/6435bcca2171d7cf90c2aa31b9e9c8f512e06b44#diff-bc03f15168f54d6184f891ea63ac8490), libbam API function calls were replaced with their htslib equivalents.  In doing so, large swaths of code were removed.<br/><br/>
This includes:<br/>
`typedef struct {`
`	int32_t n_targets;`
`	char **target_name;`
`	uint32_t *target_len;`
`	void *dict, *hash, *rg2lib;`
`	uint32_t l_text, n_text;`
`	char *text;`
`} bam_header_t;`<br/>
The code above is referring to lines 91-98 of release [0.2.0-rc1](https://github.com/samtools/samtools/commit/6435bcca2171d7cf90c2aa31b9e9c8f512e06b44#diff-bc03f15168f54d6184f891ea63ac8490).<br/>
What are the htslib equivalents for void *dict and void *hash for the [current](https://github.com/samtools/samtools/releases/tag/1.9) version of samtools?<br/><br/>
Thanks!<br/>
@Matthew-Mosior @zlskidmore

**Comment by daviesrob** [comment]
Look in https://github.com/samtools/htslib/blob/develop/htslib/hts.h

Function `bam_name2id(bam_hdr_t *h, const char *ref)` will convert a reference name to the corresponding id (or -1 if it isn't in the list).  Conversion the other way is currently a lookup in `target_name`.
