### ISSUE TITLE
SAMTools 1.9 fastq - paired reads out of order

### ISSUE THREAD

**Issue by RichardCorbett** [samtools/samtools#1014]
Hi all,

I'm trying SAMTools for converting BAM to fastq, which I've been doing slowly with Picard for the past few years so was excited to see a multithreaded solution.

Version: SAMTools 1.9
OS: CentOS 7
machine: Linux gphost13.bcgsc.ca 3.10.0-693.5.2.el7.x86_64 #1 SMP Fri Oct 20 20:32:50 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

Command:
`samtools fastq -1 reads.fq1 -2 reads.fq2 -@ 32 myBam.bam`

The output fastq files don't have the reads in the same order.   For example:
```
head -n 100000 GM24385_DNA_2.bam.fq1  | tail -4
@HISEQ104_146:3:1215:22820:55368
TTGACTAAAATGTCAAATAATGATATAGACAATGAAATCCAAGCTGAGATGGTCTCAGATGGAGATGAGGAACTCAATGGGAACTGGAGTAAAGGTGTCTCTTGCTATCGAGAGAGACTGGCAGCATTTTGTCCCTGCCCTAGAGATTTG
+
<AFFFJJJJJJJJJJJJJJJJJJJJJJJJJJJJJFJJJJJJJJJJJFJFJJJJJJJJJFJJJJJFJJJJJJJJJJJJJJJJJJJJJJJJAFFJJJJJJJJJJJJJJJJJFJJJJFJFFJJJJAJJAFJJJJJJJFJAJ<JF<FAF-FJFJ

head -n 100000 GM24385_DNA_2.bam.fq2  | tail -4
@HISEQ104_146:3:2108:27438:8200
TGATTTTACAGGTTTATATGTGGAAGAGACTTGCCCTGTCTCAGGTGAGACTTTGGACTGCCAACTTTTGAGTTAATGCTGAAGTGAGTTAAGACTGTTGGGGACTATTGGGAAGGCATGATTGGTTTTGAAATGTGAGGACATGAGAGT
+
AAAFFJJJJJJJJJJJJJJJJJJFJJJJJJJJJJJJJ<J7AAJFJJJAFJFFJJJFJFJJFJFJJJFAJJ<FJJJJJFJFJFJJJJJJFJFJJJJJ-FFFJJJAFFJJ<<<FA<FFFFFA-FFFJFJJJFJJFFJAJ7AJAF-AA7F<-7

```

**Comment by RichardCorbett** [comment]
I see now. I missed the doc message about supplementary reads being included.   I'll filter those out and re-run

**Comment by RichardCorbett** [comment]
Hmm.
Using this command:
`/gsc/software/linux-x86_64-centos6/samtools-1.9/bin/samtools fastq -F 0x900 -1 $1.fq1 -2 $1.fq2  $1`
Read1 and Read2 line up in the two output files, but when I introduce the multi-thread option the read order is different in the two output files.

**Comment by RichardCorbett** [comment]
Actually I think reads are also out of order with one thread.

**Comment by valeriuo** [comment]
> The output fastq files don't have the reads in the same order

@RichardCorbett, did you sort your BAM file by query name before trying to convert to FASTQ, as the [documentation](http://www.htslib.org/doc/samtools.html) instructs?
> The input to this program must be collated by name. Use samtools collate or samtools sort -n to ensure this.

The multi-threadness only deals with the compression of the output files, which in your case is not activated. The compression is, by default, implied from the extension of the output files. Quoting from the documentation:
> The files will be automatically compressed if the file names have a .gz or .bgzf extension.

Your FASTQ files have the extensions `fq1` and `fq2`, which defaults to uncompressed text and no multi-threading.

**Comment by RichardCorbett** [comment]
Thanks @valeriuo ,

I had missed that documentation.   I am relatively new to using the new samtools and had been relying on the command line help messages.  I hadn't realized there was so much information on the documentation page.

**Comment by jmarshall** [comment]
The documentation should emphasise the wisdom of using `-s`, as not using it is what allows the `-1` and `-2` files to become out of sync. A warning if you don't use it would be just about warranted.

Leaving the input file sorted by coordinate is a common user error, and `samtools fast[aq]` should be able to detect it and exit with an error.

* If the header contains `SO:coordinate`, that's at least a strong hint (⇒ warning) that the input is unsuitable.

* If after emitting 10,000 reads, more than a trivial percentage of them (1%? 5%? 20%?) have gone to the singleton file, that's a very strong hint that the input has not been collated by queryname. It should be possible to find a suitable threshold (by measuring some typical BAM files sorted by qname and by coordinate) such that samtools could reasonably fail with an error (unless you used `--force` or so to tell it to really emit so many singletons).

**Comment by ttrolle** [comment]
I agree, it would be extremely helpful if samtools fastq could raise an error if the bam file is not sorted correctly. It's very easy to forget to namesort the bam file first.
