### ISSUE TITLE
Segfault in markdups with -S option

### ISSUE THREAD

**Issue by ryanrichholt** [samtools/samtools#1021]
#### Are you using the latest version of [samtools](https://github.com/samtools/samtools/releases/latest) and [HTSlib](https://github.com/samtools/htslib/releases/latest)? If not, please specify.
(run `samtools --version`)

```
samtools 1.9
Using htslib 1.9
Copyright (C) 2018 Genome Research Ltd.
```

 #### Please describe your environment.
- OS (run `uname -sr` on Linux/Mac OS or ` wmic os get Caption, Version` on Windows)
- machine architecture (run `uname -m` on Linux/Mac OS or ` wmic os get OSArchitecture` on Windows)
- compiler (run `gcc --version` or `clang --version`)

```
$ uname -sr
Linux 3.10.0-957.5.1.el7.x86_64
$ uname -m
x86_64
$ gcc --version
gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-11)
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

#### Please specify the steps taken to generate the issue, the command you are running and the relevant output.

# Segfault in markdups with -S option

Bam in question: https://drive.google.com/open?id=1VG8uPmtm-g3xjnrbLz87qFrC9u5yxRe3

`failing.bam` consistently segfaults when running markdup with the `-S` option

1) I am able to use: `view`, `index`, `stats`, and `flagstat` on the bam
with no problems
2) This also happens with version 1.7
3) The commands below show an absent EOF warning. This example data is taken
from a much larger bam. I figured out that I could subset the bam at the 
site of the error by catting the bam data into tee, then mirroring the output
to a file and a samtools process. Once the samtools process segfaults, the
pipe breaks, and voila, the file contains all the data samtools received right
up until it crashed. 
Like this: `cat full.bam | tee failing.bam | samtools markdup -S - full.md.bam`
So, yes, it's technically trucated, but that's not the cause of the problem.

# Command Examples

Segfault when using `-S`
```
$ samtools markdup -S failing.bam out.bam
[W::bam_hdr_read] EOF marker is absent. The input is probably truncated
Segmentation fault (core dumped)
```

No problem without that option
```
$ samtools markdup failing.bam out.bam
[W::bam_hdr_read] EOF marker is absent. The input is probably truncated
```

## Strangely, samtools view seems to resolve the problem

```
$ samtools markdup -S <(samtools view -h failing.bam) out.bam
[W::bam_hdr_read] EOF marker is absent. The input is probably truncated
```

**Comment by whitwham** [comment]
Thanks for the bug report and especially for being able to include the failing bam file.  That should make it much easier to track down what it going wrong.

**Comment by whitwham** [comment]
I think this is the same error as in #909 which was fixed in #911.  Unfortunately we have not had a release since then.

**Comment by PedalheadPHX** [comment]
The current github code does resolve the issue that exists in v1.9.  Is there any plan for a release on the horizon?

**Comment by whitwham** [comment]
The next release is being worked on but I don't have a definite date for it yet.
