### ISSUE TITLE
My session with samtools is being killed 

### ISSUE THREAD

**Issue by beginner984** [samtools/samtools#1022]
(py3venv) [fi1d18@cyan01 fi1d18]$  samtools mpileup -q 1 -f /hs37d5.fa 1.bam 2.bam > 1.pileup
[mpileup] 2 samples in 2 input files
<mpileup> Set max per-file depth to 4000
Killed
(py3venv) [fi1d18@cyan01 fi1d18]$ which samtools
/local/software/samtools/1.3.2/bin/samtools

Sorry I don't know whatever I am trying to use this command for preparing input for varscan, after a while running being killed, any suggestion please?
Thanks a lot for any help

**Comment by valeriuo** [comment]
What is the configuration of the system (including available memory) you are running the command on?
What is the kernel reporting? Use `dmesg`.

Anyway, you should update your samtools instance to the [latest version](https://github.com/samtools/samtools/releases/tag/1.9), as there have been some changes in the mpileup area.

**Comment by beginner984** [comment]
(py3venv) [fi1d18@cyan01 fi1d18]$ dmesg
timed out
nfs: server fsresearch.soton.ac.uk not responding, timed out
nfs: server fsresearch.soton.ac.uk not responding, timed out
nfs: server fsresearch.soton.ac.uk not responding, timed out
nfs: server fsresearch.soton.ac.uk not responding, timed out
nfs: server fsresearch.soton.ac.uk not responding, timed out
nfs: server fsresearch.soton.ac.uk not responding, timed out
nfs: server fsresearch.soton.ac.uk not responding, timed out
nfs: server fsresearch.soton.ac.uk not responding, timed out
nfs: server fsresearch.soton.ac.uk not responding, timed out
nfs: server fsresearch.soton.ac.uk not responding, timed out
nfs: server fsresearch.soton.ac.uk not responding, timed out
nfs: server fsresearch.soton.ac.uk not responding, timed out
nfs: server fsresearch.soton.ac.uk not responding, timed out
nfs: server fsresearch.soton.ac.uk not responding, timed out
nfs: server fsresearch.soton.ac.uk not responding, timed out
nfs: server fsresearch.soton.ac.uk not responding, timed out
nfs: server fsresearch.soton.ac.uk not responding, timed out
nfs: server fsresearch.soton.ac.uk not responding, timed out
nfs: server fsresearch.soton.ac.uk not responding, timed out
nfs: server fsresearch.soton.ac.uk not responding, timed out
nfs: server fsresearch.soton.ac.uk not responding, timed out

**Comment by valeriuo** [comment]
The kernel logs a lot of stuff. We need the log message just after the samtools command gets killed.

**Comment by daviesrob** [comment]
I suspect you ran out of memory.  Please feel free to reopen this if you get more information.
