### ISSUE TITLE
Improved Documenation for idxstats flagstats and stats

### ISSUE THREAD

**Issue by DarioS** [samtools/samtools#1024]
The documentation has vague statements such as "samtools stats collects statistics from BAM files and outputs in a text format." Outputs what information exactly? There's a lack of detail in the documentation in these three tools which makes it unclear what each of their purpose is and what statistics they calculate. It could be made easier for the user to pick a tool if they knew more about the statistics calculated by each one of them. Or, if the three commands were merged into one command that calculated all of the metrics to remove the three separate commands with quite similar names.

**Comment by jkbonfield** [comment]
Are you looking at the official release or the latest develop branch?

There is an improved man page for stats since https://github.com/samtools/samtools/pull/927, but it hasn't yet appeared in a proper release.

**Comment by DarioS** [comment]
I wasn't aware of the latest additions. They explain the statistics a lot better. Indeed, it's frustrating when Broad Institute employees release a half-finished software and don't work on it after it's published. I'm glad that the bioinformatics community adopted the orphan software.
