### ISSUE TITLE
samtools stats - percentage of target genome covered is greater than 100

### ISSUE THREAD

**Issue by miguelpmachado** [samtools/samtools#1025]
Dear Samtools team,
I recently run `samtools stats` with `--target-regions` and noticed that the "_percentage of target genome with coverage > 0 (%)_" is greater than 100 (_103.04_).
This sounds odd to me, but I couldn't find any extra information that would clarify me why is this happening.
I attached the `samtools stats` [report](https://github.com/samtools/samtools/files/2970851/general.bamstat.zip)
If you could help me, I would appreciate.
Thank you in advance.
Best regards,
Miguel

I'm using the v1.9 with a [Docker image](https://cloud.docker.com/repository/docker/miguelpmachado/samtools) (`miguelpmachado/samtools:1.9`)

**Comment by valeriuo** [comment]
I am struggling to reproduce this issue. Can we have an anonymized subset of your data which triggers this behaviour?

**Comment by miguelpmachado** [comment]
Hi @valeriuo ,
Thank you for being checking this.
I downsampled the original files and produced a similar result. It's not _103.04%,_ but it is grater than 100% (_100.36%_).
I uploaded the files to WeTransfer. You can find them here: https://we.tl/t-J46ZTUSiKc
There you can find the bam, the target regions file and the `samtools stats` report that I obtained.
I hope you can help me trying to understand what is going on.
Thank you once more.
Best regards,
Miguel

**Comment by valeriuo** [comment]
Thank you for the data! I've managed to identify the problem. A fix will follow shortly.
