### ISSUE TITLE
Sum of idxstats Third Column Greater Than Reads In Input FASTQ File

### ISSUE THREAD

**Issue by DarioS** [samtools/samtools#1026]
The documentation of idxstats states "The output is TAB-delimited with each line consisting of reference sequence name, sequence length, # mapped **reads** and # unmapped **reads**." Should it be something like "number of alignments" instead? The sum Is about one percent bigger than the reads in the input file.

**Comment by valeriuo** [comment]
Is your issue about the documentation or the **idxstats** figures? Please fill in the issue template.

**Comment by DarioS** [comment]
More so the figures. I don't see the benefit of counting multi-mapping reads multiple times.  But, I suppose the person who created it had a reason for doing it that way, so perhaps it's best to clarify the documentation instead.

**Comment by jkbonfield** [comment]
I've updated the manual page.  We cannot change the figures themselves as these are part of the official SAM specification.  I used the same terminology listed in that document: "read-segments".
