### ISSUE TITLE
Have samtools specify exact byte ranges when making HTTP requests

### ISSUE THREAD

**Issue by anderspitman** [samtools/samtools#1028]
#### Is your feature request related to a problem? Please specify.

From what I can tell, when using an index to read a specific range of a bam/cram file, samtools uses libcurl to make an HTTP range request starting at the proper location, but open ended (ie "`Range: bytes=<start>-`"). I'm assuming it reads until it has everything it needs and then terminates the connection.

I'm working on a system where my HTTP server is a special type of proxy which actually receives the data from another server, over a custom protocol. The problem I'm having is that when making open-ended requests as samtools does, the connection between my proxy and the next hop can become saturated, since the next hop is unaware that samtools intends to only use a small amount of the data. This is especially a problem when the proxy receives many samtools requests as once, which is common in my system.

#### Describe the solution you would like.

Is it/would it be possible to have samtools use the information in the index/region to only request the exact (or at least approximate) byte range, so the entire pipeline only sends the actual required data?

I spent a couple hours looking through the HTSlib code, and it looks like it might be too heavily abstracted for this to be easily done, but I figured I'd at least ask and maybe get alternative suggestions.

**Comment by lh3** [comment]
It is theoretically possible but will require massive code changes. I don't see this happening.

**Comment by anderspitman** [comment]
I figured that would be the case but just wanted to check. Thanks!
