### ISSUE TITLE
fixmate not recognizing name sorted inputs

### ISSUE THREAD

**Issue by nrcombs** [samtools/samtools#1034]
I'm running samtools v1.9 on a linux environment, and am using the program in a workflow to convert sam formatted files to bam, sort by name, and remove secondary/unmapped reads.  I have used this workflow multiple times on various datasets and not had a problem (all quite straightforward commands), but today am having issues with samtools fixmate. Have there been any program changes or bugs that I should be aware of?

To provide more information, here are the options I'm using broken down for each step:

samtools view -b infile.sam >outfile.bam
samtools sort -n infile.bam >outfile.sort.bam
samtools fixmate -r infile.sort.bam >outfile.rem.bam

samtools fixmate immediately returns the help documentation for this module and does not proceed. As I mentioned above, these same options have previously worked on a few different datasets (also in the same environment) but fails for my new dataset. To troubleshoot I've gone back to my previous datasets and now those inputs also fail with samtools fixmate (but still work fine with samtools view and sort). I've also tested in a different environment and using an earlier program version and still get the fixmate help documentation.

Any advice will be appreciated, thanks!

**Comment by whitwham** [comment]
The arguments for fixmate are:
> samtools  fixmate infile outfile

While you are trying to redirect stdout:
> samtools fixmate infile > outfile

If you want fixmate to write to stdout you have to use - as the output file:

> samtools fixmate infile - > outfile
