### ISSUE TITLE
samtools sort  fails if there are existing tmp files

### ISSUE THREAD

**Issue by raivivek** [samtools/samtools#1035]
Hi,

It appears that `samtools sort` fails if there existing `tmp.*` files in the directory (from a previous failed run, for example) with the following message:

```
samtools sort: failed to create temporary file "/lab/.../bwa/347.4______347.4_RG1.bam.tmp.0000.bam": File exists
```

Is there a way to specify force overwrite existing tmp files?

#### Are you using the latest version of [samtools](https://github.com/samtools/samtools/releases/latest) and [HTSlib](https://github.com/samtools/htslib/releases/latest)? If not, please specify.
```
samtools 1.9
Using htslib 1.9
Copyright (C) 2018 Genome Research Ltd.
```

**Comment by daviesrob** [comment]
Unfortunately not at the moment.  Sort's handling of temporary files has never been that good, and is one of its main outstanding annoyances.  At some point it will be reworked to manage them in a more sensible way; until then I'm afraid you'll have to clean up after any failures yourself.  One way to do this would be something like:

```
SORT_TMP=`mktemp -d`
samtools sort -T "$SORT_TMP" [...other options...]
result=$?
rm -rf "$SORT_TMP"
if [ $result -eq 0 ] ; then echo "sort worked"; else echo "sort failed"; fi
```

You can use the `--tmpdir` option of `mktemp` if you want more control over where to put the temporary files.

**Comment by raivivek** [comment]
Thanks for your input. It's good to know that it's a recognized pain point and that it'll probably be addressed sometime in future.

**Comment by millerh1** [comment]
+1 for this -- it poses challenges for pipeline tools like snakemake which do not know to clean up the tmp files from samtools if there's a failure during a sort operation.

**Comment by jmarshall** [comment]
If you're using Snakemake, then I would expect you could insulate yourself from this clean up by using a [shadow rule](https://snakemake.readthedocs.io/en/stable/snakefiles/rules.html#shadow-rules). Alternatively if you use `-T output_file_directory` (or any suitable already existing directory) sort will use temporary file names that almost certainly won't collide with a previous failure.

But what I don't understand is why people are so keen to automatically paste over the cracks in their job failures. What is the reason for your previous sort jobs failing? If it were my pipeline, I would want to analyse what had gone wrong, and cleaning up the temporary files at the end of that manual process is no real additional burden.

**Comment by raivivek** [comment]
> But what I don't understand is why people are so keen to automatically paste over the cracks in their job failures. What is the reason for your previous sort jobs failing?

One instance where this crack might show up is a job is cancelled by the resource manager or some other sort of failure, where the pipeline is fine but you just need to restart it to get going. I agree that cleaning up after the failure is not a problem, and I'm sure that's what I and everyone else is doing at the moment. However, after using samtools for quite a while, I was surprised to find this behavior one day.

**Comment by millerh1** [comment]
@jmarshall the main reason I need the cleanup is usually because a different in a different job and I need to restart as @raivivek mentions. 

I haven't tried using shadow rules before, but I can give that a shot! Thanks for the suggestion!
