### ISSUE TITLE
Problem calling a single nucleotic deletion with mpileup

### ISSUE THREAD

**Issue by PabloCabaleiro** [samtools/samtools#1037]
Hello, 

I am using the 1.9 version of samtools and I have found a issue that I am not able to explain. I have two cases of the same biological sample that should present the same variants, but I have a deletion that is present in only one of them.

#### Case 1: Deletion found
Executing pileup:

`samtools mpileup --reference ref.fasta case1.bam `
```
REF   4167    C       142     .$,$.,-1a,,-1a,,..-1A..-1A.,..,-1a,-1a.,-1a,,-1a,,-1a,.-1A...,..-1A.-1A..-1A...,-1a.,..,,-1a.,.-1A.-1A.-1A,-1a.-1A.-1A,..,.-1A..,-1a,,....-1A.-1A....-1A,-1a.-1A..,.,-1a,-1a,....-1A..,-1a,..,-1a.-1A..-1A,.-1A.-1A.,-1a,-1a,...-1A...-1A,-1a.,-1a.-1A.-1A.,-1a,-1a.-1A....-1A.-1A.,-1a,...-1A.-1A,,.-1A..-1A.,.-1A..,.^~, mDjCBDHHpIpqIGlIIIGHIHEIHoppEHjoGIqIfIIpIpIFGpIIpHDFIHpIGqIIIIIInIlfbIHIHIFEIGHIIIIH?IFIHGHIHHiEcIFIHHIIIIII@HIIIIEIIIHI1III@IIII?HIHIHI@DDHDD
REF   4168    A       140     *,*,,.*.*.,..**.*,*,*,*...,.**.*...*.,..,*.,*******,..,*..*,,...**...***..,.**,...*..*,..**.*,**.**,..*..**.***.***...**.,*,..**,,*.*.,*..,^~.  D?DHHpIppG?pIIHIIHIIIHopqEIopCHpIlIHqHpIIIpIHpD@HFIHqIHqHGHIIHpIHmiIIIIDHEI@IIIIIICIHIIIEIIFiHkIHIFGkkGIEIE?IHIIHIIHHIECIIIGIGIIIIIHIIIDHCID
```
The deletion seems to be present and when I report the result to bcf type with the option -g the deletion is reported as a indel 4167:CA>C:
```
REF   4167    .       CA      C       0       .       INDEL;IDV=66;IMF=0.390533;DP=169;I16=56,36,35,29,3660,151268,2238,80252,1840,36800,1280,25600,1701,36883,1174,24984;QS=0.58921,0.41079;VDB=0.865006;SGB=-0.693147;MQSB=1;MQ0F=0    PL      108,0,130
REF   4168    .       A       <*>     0       .       DP=104;I16=57,26,0,0,3789,192325,0,0,1660,33200,0,0,1572,34376,0,0;QS=1,0;MQSB=1;MQ0F=0 PL      0,250,194
```

#### Case 2:  Deletion not found
Executing pileup:

`samtools mpileup --reference ref.fasta case2.bam `
```
REF   4167    C       255     ...$.$,,$,......,,,.-1A.-1A.......-1A..-1A.-1A...-1A.-1A.,,-1a..,-1a,-1a,-1a,.,,.-1A..-1A,,-1a,.-1A.-1A.-1A..-1A.-1A.,-1a.-1A,..,-1a..,,-1a.-1A.-1A..-1A.-1A..-1A.-1A.-1A,-1a,..-1A.-1A,,-1a,,-1a,..-1A,.-1A,,..-1A,-1a,..-1A...-1A..-1A..-1A,-1a,....-1A.-1A.-1A.,-1a,-1a,,-1a,-1a..-1A..-1A..-1A.-1A..-1A...-1A.-1A.-1A,-1a.-1A.-1A.-1A,-1a,,-1a.-1A.-1A.,-1a....-1A,,-1a....-1A...-1A..-1A.-1A..-1A.-1A,,-1a..,-1a..-1A.,,-1a,....-1A..-1A.-1A..-1A,..-1A..,-1a,..-1A,-1a.,-1a.-1A...,-1a,-1a,,-1a,.-1A..,-1a.-1A..-1A.-1A.-1A,-1a...,-1a.-1A.,-1a...-1A...-1A,-1a..-1A.-1A.,,.....-1A..-1A...-1A,,-1a.,..,,.^~.^~.   `8imDDCmmDmGqDD<IoHpIpmGpFlcIqIIHIIIIIIIHII?kIqHIHqIpIpTqIqHFFIIIHIEeIqIIpHqIHGHIIIHHIIpHkIIoIIIoVIIIIIpCIIHHIH1GIHHHIIIHVHqFIHFkHGXT0qIIIH<?HHIIoqIIIIIHHqF@pIIHoIEIHHIqIIHHHIHGG?HIIIGIqHIIHHIIHHIHCIIIIHGIIHIGIIHIIIHHIIIIIHII@IIIHIIIHIIHHGIIIIGIGCIDDIHDDD
REF   4168    A       253     ,$,$..,,,**......*.**..**.,*..***,.,,*.*,*,***.**.**,..*..,***.**.****,.**,*,*,.*,*,,.**,.*..*.*.**,...***.**,**.*.*.**.*..********,***.*...*,*...*..*.**.**,*..*.*.,*,...*.***.*,.*..*,.**.**...**,*,*..**.*****...***.*..*..**.**.,*,....*.*..*,*,,.,.,...^~.^~.^~.      DDHqDD<IkHoGpiHpGgjHqIIEIIIIHHIGIIIiGqIIIqIpIplqIoIE@HIIIHHlIqIIIHpIEHHIIIIHI?pIoHIpIIIpWIIIIIlCIIIIIICIIHHHIIIIUIpEIHDoHHje<qIIHI@EIHHIqqIIHIIIDqGCqIIHoIGIHHIqIIIIIGHIICIIIIHIGqHCIH?IIIIIHGHIHIHIIIHICIIDIIIHIGGHIHIIHIHGIIIHHIIIIIIHHDIIIIHIEHHIIDFDBDDBD
```
The deletion seems also to be present, but when I report the information in bcf format with the option -g the indel is not present:
```
REF   4167    .       C       <*>     0       .       DP=302;I16=179,76,0,0,11471,570855,0,0,5100,102000,0,0,4849,108889,0,0;QS=1,0;MQSB=1;MQ0F=0     PL      0,255,255
REF   4168    .       A       <*>     0       .       DP=164;I16=98,39,0,0,5934,280658,0,0,2740,54800,0,0,2459,54319,0,0;QS=1,0;MQSB=1;MQ0F=0 PL      0,255,210
```
The dp is better in the sample without indel and the qualities seem to be similar for both cases. Also, I didn't find significant differences between the quality of the reads that present the deletion and the ones that do not.

I have replicated the results using directly the mpileup from bcftools and since the -g option seems to be deprecated obtaining the same results. 

I would appreciate any help the understand this issue.
Thank you for the help!

**Comment by pd3** [comment]
Any chance you could provide a small BAM for testing? It's hard to tell without seeing the alignments.

**Comment by PabloCabaleiro** [comment]
Thanks for the reply and sorry for my delayed answer, but I needed to replicate this issue on a sample that I could provide to you. 

[cases_samtools.zip](https://github.com/samtools/samtools/files/3395852/cases_samtools.zip)

The folder contains the bams from both samples, the reference, the files generated in the example and the commands used. Both cases are from the same sample NA12878 in case you want to check it. The missed variant is M33388:g.4168delA that corresponds with NC_000022.10:g.42524244delT and seems to be correct.

**Comment by daviesrob** [comment]
Thanks for the data.  It looks like you're hitting the `max_indel_depth` limit on you second case.  This can be set using the mpileup `-L` option:

```
          -L, --max-idepth INT
               Skip INDEL calling if the average per-sample depth is above INT [250]
```

Trying this on your data set does fix the problem:

```
samtools mpileup -d 900000 -L 600 --reference ref.fasta -g case_2.bam | bcftools call -P 0 -Amv - | grep $'\t'4167$'\t'
M33388.1	4167	.	CA	C	117	.	INDEL;IDV=235;IMF=0.436803;DP=538;VDB=0.496939;SGB=-0.693147;MQSB=1;MQ0F=0;ICB=1;HOB=0.5;AC=1;AN=2;DP4=151,120,133,99;MQ=20	GT:PL	0/1:120,0,148
```

`DP` shows the actual depth here is 538.

I should add that the `samtools mpileup -g` option is now deprecated as it's better to use `bcftools mpileup` instead.  The equivalent command is:
```
bcftools mpileup -d 900000 -L 600 -f ref.fasta case_2.bam | bcftools call -P 0 -Amv - | grep $'\t'4167$'\t'
M33388.1	4167	.	CA	C	102	.	INDEL;IDV=235;IMF=0.436803;DP=538;VDB=0.626777;SGB=-0.693147;MQSB=1;MQ0F=0;ICB=1;HOB=0.5;AC=1;AN=2;DP4=154,152,133,99;MQ=20	GT:PL	0/1:105,0,129
```

I'm afraid others (probably @pd3) will need to comment on the implications of increasing `-L` from the default.

**Comment by PabloCabaleiro** [comment]
Increasing the -L value solves the problem for me and I didn't find any mayor implications in the calling or even in the performance.

Thank you for your help.
