### ISSUE TITLE
Samtools fasta extract fasta sequences from bam get illegal characters（i.e. [M::bam2fq_mainloop] discarded 0 singletons）

### ISSUE THREAD

**Issue by DengHAU** [samtools/samtools#1039]
#### Are you using the latest version of [samtools]
samtools 1.9
Using htslib 1.9
Copyright (C) 2018 Genome Research Ltd.

 #### Please describe your environment.
Linux 3.10.0-693.el7.x86_64

#### Please specify the steps taken to generate the issue, the command you are running and the relevant output.

Using “samtools fasta -F 0x900 in.bam > all_reads.fa” to extract fasta sequences from an bamfile from PacBio subreads.bam, I get illegal characters(i.e.[M::bam2fq_mainloop] discarded 0 singletons) in many fasta sequences.
>m54059_190401_061634/74908106
TGATACGGCGACCACCGAGATCTACACTGGCTAGGACACTCTTTCCCTACAGACGCTCTTCCGATCTTATCTTTTTCATTTAGAGCATCAATTCATTCATTAATTTTCTCTACTTTGGCTCTATCTAAACTTTAAATAAACTAGAGCAATCTACTTCATCATCAGAGGATTCTTCATCACTAGATGAAGTGTACTTGGGTGTGTCCGATCACGTACCTTTTCTCCTTGGCCATAAGGCATGTATGGTGTTTGTTGGGGAAGAGTGAGGATTTGTTGAAGGCTGAGGTAGCAAGTCCTTCGTCGTCAGAGTCGGAAGAGGAGCAATCCGAGTCCCGTTCCTTTCCAAGGTGCGCCCCGCCCTTTGCCTTCCTGTAGTTCTTCTTTTTCTCCTTCTTCCGTTCTTTCTTGTCCTGGTCACTACCATTATCGGGACAATTTGTAATAAAGTGACCAGTCTTACCACATTTAAAACAGGAGCGCTTTCCCTTGTTTTGTTCTTGTTGGGTACTCCTTGCGTCCTTTGAGTGCGGTCTTGAAGCGCTTGATGATAAGCGCCGTCTCATTCTCGTTGAGGCCAGCGGCCTCCACTTGTGCCACCTTGCTTGAGAGTGCCTCCTGCTACTGGTTGCCTTGAGAGCAACAGGTTGAGGCTCATAGACGGGTAGTGGACCATTTAGAGCATCGTCCACGTATCGAGCTTCCTTCACCATCATGCGCCCATTCACAAATTTTCCAAGAATCTCCTCGAGCGTCATCTTGGTGTACCTGGGATTCTCACGAATAAGATTGACAAGATGGGGTCAATTACAGTAAATGACCTTAGCATGAGTCGGACGACATCATGATCCGTCCATCTTGTGTTTCCATAGCTTCGGATCTGTTGACCAGGGTCTTGAGCCTGTTGTAAGTCTGAGTTGGCTCCTCTCCCCTGATCATCGCGAATCTCCCCAGCTCGCCTTCCACCAGCTCCATTTTGGTGATCATGGTGGCGTGTTTCCCTCATGAGATATCATGAGGGTGTCCCAGATTTGCTTGGCGTTGTCCAAGCCGCTCACCTTATTATTTATCCCTGCAAAGTGAAGCTAGCAAGACAGTAGTAGCTTGTGCATTTTATGATTTGCTCATTATGGAAACGGGATTATCAGTACTATCAAAATGCATTCCGTTTTCAACAATCTCCTAGATACTAGGATGGAGAGAAAATAATGACTATGCATTTTATGACTCCAGAAAGAGTAGTCTTCTCCATCAAAGTGTGGAGGTTTCCCAAGTTGAATTGATAGAAATGAGCATTTGAATTAGATGGAATACAGGAGTAATCAAATGATAGTTTTTATTAACCGTTTTCTTCTTTGAAGAGTCATCGTTGTCGTCGTGTGGTGAAGAAGACGAGGCATCGCTGTCGTAAGATGATCTTCTTGATGCGCATCTTCTTCTTCCTCTCTCTTCTTTTGACTCGAGCCTGAGTCAGTAGACTTGTCGTCTCTTGGCTCGTTGAAGACGGACTCCTTTTCCTTGTCGTTGACCACCATCCCCTTTCCCTTAGGATCCATCTCTTCGGGCGGTTAGTCCCTTAGATGAAGAGTACGACTCTGATACAATTGAGAGCACCTAGAGGGGGGTGAATAGGTGATCCTGTAAAATTCAACACTAAATTCTAACAAGCTTGATTAAAGAGATATTAGCGCAAGTTAATCAGTCTATGAGGCGAGCTCTTGCGAACACAAATATCACAGAGAGGAGCAACACAAGAGACAACACGATTTTTATCTCGTGGTTCGGCCAAGTAACACTTGCCTACTTCCACGTTGTGGCGTCCCAATGGACGAGTGTTGCACTCAACCCCTTTCAAGTGATCCAATGATCAACTTGATACCATGTCTTTCTACTTATAGTCT[M::bam2fq_mainloop] discarded 0 singletons
[M::bam2fq_mainloop] processed 512807 reads
TTCTCTCGTTTGCGGGAATCTCCACAAGTTGGAGCCTCTCTCCCTTACATAAAGATCACAAAGAAGGCACAAGAGTAAGGCTAGGAGAGCAACACACACAACACACCAAATCCACAGCACACACACGCACACAAGCCAAGACTTGAGCTCGAAACGTAGCACAGAGAGTTCACAACTCGAACGGAGCTCAATCACTAACACAATCGATCAAATGCGTGGCAGAGTGTGAGAGTCTTAGAATGCTTAGTGAATGCTGGCTTACTCCTCCATGCGCCTAGGGGTCCTTTTATAGCCCAAGGCAGCTAGGAGCCGTTGGAGATCGACATGGAAGGCTATCTTGCCTTCTGTCGAATGGCGCACCGGACAGTCCGGTGCGCAATCTCCTTCCAAATTTGGCATATCCGAACGTTGCTCCTCTGGGCTGATTGGCGCACCGGACACTGTCCGATGCACAACGACAGTCCGGTGCACACCGGACAGTCTGGTGCCCGGCTGACCGTTGGAGCATTCCACGTGTCGCACGAAGATTGTGTCGCCGACCGTTGCTCAGGCGACCGTTTGCTCACCGAACAGTCCGGTGCACCACTGGACAGTCCGGATTTTAGTCGTACGCCGCTGATCCTTTTCCCGGAGAAGCTATTTCACCAGAGACCAGCCTAGCGCACCGGACACTATCCGTGCACCATCGGACAGTCCGTGTGCCAGGCCAAACTGGAATATGGCTGCATGAAGGGAAATAGGCTTACACCTTTTCCTAATTGTTTTGGTGGTTGAATTGCCCAACACAAATAATTGGACTAACTAGTTTGCTCTAGATCATACATTCTACAGGTGCCAAAGTTCAACACCAACCAATCAAAAGAACAAGTTAGGCTTCAAAAGAAAGGAGCAAAAAGGAAACCGAAGTGTGCCCTGGTCTGGCGCACCGGACTGTCCGGTGTGCCACCGGACAGTGTCGGTGCACCAGGGTGAATCAGCTCAAACTCCTCACCTTCGGTTTCCAGGCGCAGCTCCGCTATAATTCACCGGACTGTCCGGTGTGCCACCGGACTATCTGGTGCACCAGCGGAGCAACGACTATCTGTGCGCAACGGTCGACTCTGCAAAGTGAACAGTGCAATTCAGATGTCAGAGCAGAAGGTCAGAGAGGCACCGGACTGACCAGTGTGCCACCGGACTGCCTGGTGCCACATGAGACAAAGCCTCCAATGGTCGACCAGCTCCATGGCCTAACGAAGATGATGTGGCGGCGCACCAGACTGTCCGGTGCGCCCATCGCCAGCAGCCTTCTCCAACGGCTACAATTTGGTTGGTGGCTATAAATACCACCCCAACCGTCCACTTCAAGGTGTGGGAGCCCAAGCACATTCCAAGTCATATAGTTGACATATCCAAGCCCTCCAACCACCTCTATTCATTGATTCATCCTATACACAAGATTTAGACCACTACACCCCCACACAAGTGCCACAAAAGTGAGAGCAAGCAAAAGAAAGCTTCTCGTGTGAGTTTAGCTCTAGTGCCTTGTGAGATTCATTGAGAGAAAGTGTGTGCTACATCTTGCGTTCATTTGTGCGTGGAGTTTTGACCCCATTGAACTTCCTCCAAAGTGTTGGAGGCTTGTAAAGCTAGCAAGAGACACCTAAGTGTGTGGTGATCCTTGCGGGTCTTAAGTGATCCTTGAGAAGAAGAAGAGCTCGTCGATCTTGGGATCGATTGAGAGAGGGAAAGGGAGAGCCCCGTCCTTAGTGGACTCCTCAACGTGGACTAGGCCTTCGATGGCCGAACCTCGGTAAAACAAACTCCCGTGTCTCGTGTGTTTATTGCTTGTGATTTGTTTGTTCTCTCTTTCTAAGTTCTCTTGTTCTACTCTTTGCTAACATTATTTTGTGTTGCTTCAAGTTAAATTCTCATTTAGAGAAGCAACTCCTCGCAAGAAAGAACTTGTGTTTATCTTCTTCTTATCTAAAGCCCTCTTGCATTATTCTCCACTAACCTTTCTAATAGTATTGTTTAAATTCCGCACTCTTTGAAAACAATACTCATTGCAGATCGGAAGAGCACACGTCTGAACTCCAGTCACGCGCCAAATCTCGTATGCCGTCTTCTGCTTG

Using "samtools view in.bam | less" , this read has no this kind of "[M::bam2fq_mainloop] discarded 0 singletons
[M::bam2fq_mainloop] processed 512807 reads" character in read.

m54059_190401_061634/74908106       4       *       0       255     *       *       0       0       TGATACGGCGACCACCGAGATCTACACTGGCTAGGACACTCTTTCCCTACAGACGCTCTTCCGATCTTATCTTTTTCATTTAGAGCATCAATTCATTCATTAATTTTCTCTACTTTGGCTCTATCTAAACTTTAAATAAACTAGAGCAATCTACTTCATCATCAGAGGATTCTTCATCACTAGATGAAGTGTACTTGGGTGTGTCCGATCACGTACCTTTTCTCCTTGGCCATAAGGCATGTATGGTGTTTGTTGGGGAAGAGTGAGGATTTGTTGAAGGCTGAGGTAGCAAGTCCTTCGTCGTCAGAGTCGGAAGAGGAGCAATCCGAGTCCCGTTCCTTTCCAAGGTGCGCCCCGCCCTTTGCCTTCCTGTAGTTCTTCTTTTTCTCCTTCTTCCGTTCTTTCTTGTCCTGGTCACTACCATTATCGGGACAATTTGTAATAAAGTGACCAGTCTTACCACATTTAAAACAGGAGCGCTTTCCCTTGTTTTGTTCTTGTTGGGTACTCCTTGCGTCCTTTGAGTGCGGTCTTGAAGCGCTTGATGATAAGCGCCGTCTCATTCTCGTTGAGGCCAGCGGCCTCCACTTGTGCCACCTTGCTTGAGAGTGCCTCCTGCTACTGGTTGCCTTGAGAGCAACAGGTTGAGGCTCATAGACGGGTAGTGGACCATTTAGAGCATCGTCCACGTATCGAGCTTCCTTCACCATCATGCGCCCATTCACAAATTTTCCAAGAATCTCCTCGAGCGTCATCTTGGTGTACCTGGGATTCTCACGAATAAGATTGACAAGATGGGGTCAATTACAGTAAATGACCTTAGCATGAGTCGGACGACATCATGATCCGTCCATCTTGTGTTTCCATAGCTTCGGATCTGTTGACCAGGGTCTTGAGCCTGTTGTAAGTCTGAGTTGGCTCCTCTCCCCTGATCATCGCGAATCTCCCCAGCTCGCCTTCCACCAGCTCCATTTTGGTGATCATGGTGGCGTGTTTCCCTCATGAGATATCATGAGGGTGTCCCAGATTTGCTTGGCGTTGTCCAAGCCGCTCACCTTATTATTTATCCCTGCAAAGTGAAGCTAGCAAGACAGTAGTAGCTTGTGCATTTTATGATTTGCTCATTATGGAAACGGGATTATCAGTACTATCAAAATGCATTCCGTTTTCAACAATCTCCTAGATACTAGGATGGAGAGAAAATAATGACTATGCATTTTATGACTCCAGAAAGAGTAGTCTTCTCCATCAAAGTGTGGAGGTTTCCCAAGTTGAATTGATAGAAATGAGCATTTGAATTAGATGGAATACAGGAGTAATCAAATGATAGTTTTTATTAACCGTTTTCTTCTTTGAAGAGTCATCGTTGTCGTCGTGTGGTGAAGAAGACGAGGCATCGCTGTCGTAAGATGATCTTCTTGATGCGCATCTTCTTCTTCCTCTCTCTTCTTTTGACTCGAGCCTGAGTCAGTAGACTTGTCGTCTCTTGGCTCGTTGAAGACGGACTCCTTTTCCTTGTCGTTGACCACCATCCCCTTTCCCTTAGGATCCATCTCTTCGGGCGGTTAGTCCCTTAGATGAAGAGTACGACTCTGATACAATTGAGAGCACCTAGAGGGGGGTGAATAGGTGATCCTGTAAAATTCAACACTAAATTCTAACAAGCTTGATTAAAGAGATATTAGCGCAAGTTAATCAGTCTATGAGGCGAGCTCTTGCGAACACAAATATCACAGAGAGGAGCAACACAAGAGACAACACGATTTTTATCTCGTGGTTCGGCCAAGTAACACTTGCCTACTTCCACGTTGTGGCGTCCCAATGGACGAGTGTTGCACTCAACCCCTTTCAAGTGATCCAATGATCAACTTGATACCATGTCTTTCTACTTATAGTCTTTCTCTCGTTTGCGGGAATCTCCACAAGTTGGAGCCTCTCTCCCTTACATAAAGATCACAAAGAAGGCACAAGAGTAAGGCTAGGAGAGCAACACACACAACACACCAAATCCACAGCACACACACGCACACAAGCCAAGACTTGAGCTCGAAACGTAGCACAGAGAGTTCACAACTCGAACGGAGCTCAATCACTAACACAATCGATCAAATGCGTGGCAGAGTGTGAGAGTCTTAGAATGCTTAGTGAATGCTGGCTTACTCCTCCATGCGCCTAGGGGTCCTTTTATAGCCCAAGGCAGCTAGGAGCCGTTGGAGATCGACATGGAAGGCTATCTTGCCTTCTGTCGAATGGCGCACCGGACAGTCCGGTGCGCAATCTCCTTCCAAATTTGGCATATCCGAACGTTGCTCCTCTGGGCTGATTGGCGCACCGGACACTGTCCGATGCACAACGACAGTCCGGTGCACACCGGACAGTCTGGTGCCCGGCTGACCGTTGGAGCATTCCACGTGTCGCACGAAGATTGTGTCGCCGACCGTTGCTCAGGCGACCGTTTGCTCACCGAACAGTCCGGTGCACCACTGGACAGTCCGGATTTTAGTCGTACGCCGCTGATCCTTTTCCCGGAGAAGCTATTTCACCAGAGACCAGCCTAGCGCACCGGACACTATCCGTGCACCATCGGACAGTCCGTGTGCCAGGCCAAACTGGAATATGGCTGCATGAAGGGAAATAGGCTTACACCTTTTCCTAATTGTTTTGGTGGTTGAATTGCCCAACACAAATAATTGGACTAACTAGTTTGCTCTAGATCATACATTCTACAGGTGCCAAAGTTCAACACCAACCAATCAAAAGAACAAGTTAGGCTTCAAAAGAAAGGAGCAAAAAGGAAACCGAAGTGTGCCCTGGTCTGGCGCACCGGACTGTCCGGTGTGCCACCGGACAGTGTCGGTGCACCAGGGTGAATCAGCTCAAACTCCTCACCTTCGGTTTCCAGGCGCAGCTCCGCTATAATTCACCGGACTGTCCGGTGTGCCACCGGACTATCTGGTGCACCAGCGGAGCAACGACTATCTGTGCGCAACGGTCGACTCTGCAAAGTGAACAGTGCAATTCAGATGTCAGAGCAGAAGGTCAGAGAGGCACCGGACTGACCAGTGTGCCACCGGACTGCCTGGTGCCACATGAGACAAAGCCTCCAATGGTCGACCAGCTCCATGGCCTAACGAAGATGATGTGGCGGCGCACCAGACTGTCCGGTGCGCCCATCGCCAGCAGCCTTCTCCAACGGCTACAATTTGGTTGGTGGCTATAAATACCACCCCAACCGTCCACTTCAAGGTGTGGGAGCCCAAGCACATTCCAAGTCATATAGTTGACATATCCAAGCCCTCCAACCACCTCTATTCATTGATTCATCCTATACACAAGATTTAGACCACTACACCCCCACACAAGTGCCACAAAAGTGAGAGCAAGCAAAAGAAAGCTTCTCGTGTGAGTTTAGCTCTAGTGCCTTGTGAGATTCATTGAGAGAAAGTGTGTGCTACATCTTGCGTTCATTTGTGCGTGGAGTTTTGACCCCATTGAACTTCCTCCAAAGTGTTGGAGGCTTGTAAAGCTAGCAAGAGACACCTAAGTGTGTGGTGATCCTTGCGGGTCTTAAGTGATCCTTGAGAAGAAGAAGAGCTCGTCGATCTTGGGATCGATTGAGAGAGGGAAAGGGAGAGCCCCGTCCTTAGTGGACTCCTCAACGTGGACTAGGCCTTCGATGGCCGAACCTCGGTAAAACAAACTCCCGTGTCTCGTGTGTTTATTGCTTGTGATTTGTTTGTTCTCTCTTTCTAAGTTCTCTTGTTCTACTCTTTGCTAACATTATTTTGTGTTGCTTCAAGTTAAATTCTCATTTAGAGAAGCAACTCCTCGCAAGAAAGAACTTGTGTTTATCTTCTTCTTATCTAAAGCCCTCTTGCATTATTCTCCACTAACCTTTCTAATAGTATTGTTTAAATTCCGCACTCTTTGAAAACAATACTCATTGCAGATCGGAAGAGCACACGTCTGAACTCCAGTCACGCGCCAAATCTCGTATGCCGTCTTCTGCTTG      5555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555   RG:Z:b12db176   np:i:7  rq:f:0  rs:B:i,9,0,0,0,0,0      sn:B:f,4.15455,7.84199,5.47593,9.53097     za:f:0  zm:i:74908106   zs:B:f,0

**Comment by jkbonfield** [comment]
That text should be sent to stderr (standard error) and will not appear in output unless you are binding stderr to stdout with e.g. "2>&1".

For example, this works:

```
samtools fasta -F 0x900 in.bam > out.fasta
```

but this does not:

```
samtools fasta -F 0x900 in.bam > out.fasta 2>&1
```

Note that's a UNIX shell thing and nothing to do with Samtools.  Can you please give us the *complete* command line you used?

**Comment by DengHAU** [comment]
Thanks for your reply

I used this command line：
`samtools fasta -F 0x900 m54059_190401_061634.subreads.bam > all_subreads.fa &` 
OR
`nohup samtools fasta -F 0x900 m54059_190401_061634.subreads.bam > all_subreads.fa &>fasta.log &`
 but I'm sure I never use "2>&1".

I'll try:
 `samtools fasta -F 0x900 m54059_190401_061634.subreads.bam > all_subreads.fa` 
again and see if this will happen again.

> That text should be sent to stderr (standard error) and will not appear in output unless you are binding stderr to stdout with e.g. "2>&1".
> 
> For example, this works:
> 
> ```
> samtools fasta -F 0x900 in.bam > out.fasta
> ```
> but this does not:
> 
> ```
> samtools fasta -F 0x900 in.bam > out.fasta 2>&1
> ```
> Note that's a UNIX shell thing and nothing to do with Samtools. Can you please give us the _complete_ command line you used?

**Comment by jkbonfield** [comment]
It's the nohup.  The man page states:

> If  standard error is a terminal, redirect it to standard output.

Remove this and samtools will work properly again.

**Comment by valeriuo** [comment]
Or you can specify different files for output and error:

`nohup samtools fasta -F 0x900 m54059_190401_061634.subreads.bam 1>all_subreads.fa 2>fasta.log`

**Comment by jmarshall** [comment]
More motivation for a `-o` option here (as per #874), which would help neophytes avoid stderr vagaries.

**Comment by jkbonfield** [comment]
That works in some simple cases, but not for all uses so it still needs the complex mechanism too (-1, -2, -s, etc).

Generally it's one of those "I wouldn't start from here" scenarios.  Anyway it's irrelevant to this ticket which is a unix usage error rather than a samtools issue.  Virtually all samtools tools will give wrong output if you use single "> file" semantics combined with nohup.

**Comment by jmarshall** [comment]
Of course it needs the -1, -s, etc options; the point, if you care to read #874, is it would benefit from additionally having the -o option discussed, as that's the remaining missing native `samtools fasta/q` redirection that necessitates falling back to shell redirection in the `fasta/q` command.

The relevance to this issue is that if samtools provided sufficient redirection options itself, users would not need to use Unix redirections at all, especially in combination with nohup. It is clear (by the number of issues filed by neophytes, if nothing else) that `nohup` + `> file` is harder to use than individual tools' built-in redirection options.

**Comment by jkbonfield** [comment]
I did care to read it...

**Comment by DengHAU** [comment]
Hi, all, I'm the neophytes..., i am really sorry for open this thoughtless issue. I often use `nohup` command,because I need to use VPN daily and it broken down sometimes. Great thanks to all developers for your hard work to make samtools a usr-friendly and useful toolkit.
