### ISSUE TITLE
Samtools mpileup (-A) option 

### ISSUE THREAD

**Issue by nmfad** [samtools/samtools#1040]
Hello, 

Am using samtools to generate mpileups and I am looking for an accurate count of each 
allele for positions provided by a bed file. On using the (-A) option , I see my allelic counts 
change by a huge margin from not using the (-A) option. 

My questions are :
1) What does mpileup consider anomalous read pairs ??
2) How does mpileup extract these anomalous read pairs from an RNA paired end bam that is aligned using Tophat 
3) If I am looking to calculate simple allelic counts for RNA data , is it recommended to 
use the (-A) option ??

**Comment by tseemann** [comment]
https://github.com/samtools/samtools/blob/651bf1469d1abd86a78b5e57c29b24a93598b0c3/bam_plcmd.c#L285

```
else if ((ma->conf->flag&MPLP_NO_ORPHAN) && (b->core.flag&BAM_FPAIRED) && !(b->core.flag&BAM_FPROPER_PAIR)) skip = 1;
```
It appears "anomalous" means it is paired in sequencing, but the "proper pair" flag in the flags 
column of the SAM file is not set.

```
samtools flags
        0x1     PAIRED        .. paired-end (or multiple-segment) sequencing technology
        0x2     PROPER_PAIR   .. each segment properly aligned according to the aligner
```

These flags are set by your aligner, not chosen by `samtools`.   For example, `bowtie2` has `-X 500` default, so if the read pairs are more than 500bp apart _and_ are not oriented R1=Fwd,R2=Rev then it will be anomalous.
