### ISSUE TITLE
Clarify that samtools fastq can compress output files in docs

### ISSUE THREAD

**Issue by tseemann** [samtools/samtools#1044]
#### Is your feature request related to a problem? Please specify.

From #874 I learnt that `samtools fastq` will compress the output files of the `-{1,2,s,o}` options of the destination filename is name appropriately.

From `samtools fastq` I see
`-c                   compression level [0..9] to use when creating gz or bgzf fastq files`
so I assume `.gz` or `.bgzf` are the supported extensions?

#### Describe the solution you would like.

The help currently says this:

```
samtools fastq |& grep FILE
  -0 FILE              write reads designated READ_OTHER to FILE
  -1 FILE              write reads designated READ1 to FILE
  -2 FILE              write reads designated READ2 to FILE
  -s FILE              write singleton reads designated READ1 or READ2 to FILE
  --i1 FILE            write first index reads to FILE
  --i2 FILE            write second index reads to FILE
```

Perhaps replace `FILE` with `FILE[.gz]` or similar?
Or put a line mentioning the compression output option.

ALSO - How would one get it to compress *and* write to `stdout` ?

**Comment by tseemann** [comment]
It seems this is already in master:

https://github.com/samtools/samtools/blob/1b72f1a3a7db53159451fb25afd3537b92931a3c/sam_view.c#L967

I am using:
```
samtools --version
samtools 1.9
Using htslib 1.9
```
I will close, sorry!

**Comment by jkbonfield** [comment]
Compression and writing to stdout is still an unsolved issue, but with the new `-o` option (#1042) this at least be partially solved.  The assumption is previously most requests to compress stdout have been because they wanted to produce an interleaved gzipped fastq.

I guess if stdout is actually what you wanted, you can pipe into gzip or bgzip so it's not a major issue anyway.

**Comment by plijnzaad** [comment]
minor remark: the -o option only works as advertised if there is indeed a read1 or read2. If the bam contains only unmapped reads (just flag 4, nothing else; this is the default from the Nanopore Dorado mapper) there is no read1 or read2 and everthing  goes to stdout regardless.

**Comment by jkbonfield** [comment]
According to the usage statement

```
  -0 FILE      write reads designated READ_OTHER to FILE
  -1 FILE      write reads designated READ1 to FILE
  -2 FILE      write reads designated READ2 to FILE
  -o FILE      write reads designated READ1 or READ2 to FILE
```

So if a read has flag 4, meaning no READ1 or READ2 flag, then it is correct that it doesn't appear in any of -1, -2 or -o files.  I think it's probably -0 for "other" categories.

**Comment by claczny** [comment]
Related to the comment by @jkbonfield, while I agree that piping is a possible solution, the documentation remains unclear IMO.
http://www.htslib.org/doc/samtools-fasta.html from 12 Sep. 2024 says:
> The files will be automatically compressed if the file names have a .gz, .bgz, or .bgzf extension. 

right at the top. There is no information there that this is supposed to be used with a special command-line option (`-0/1/2/o`).
The documentation thus could be improved.

In fact, I ran into this recently when running `dorado` for the first time and going from POD5 --- basecalling ---> unmapped BAM --- demux ---> unmapped BAM-per-barcode --- samtools fastq ---> FQ.GZ, but the FQ.GZ actually being FQ only, i.e. not being compressed when using stdout redirection to a file (`samtools fastq -T "*" barcodeXX.bam > barcodeXX.fq.gz`)

**Comment by jkbonfield** [comment]
The misunderstanding here is that samtools fastq is the bit processing the "> barcodeXX.fq.gz".  That's nothing to do with samtools and is handle by the login shell.  Consequentially the "_if the filenames have a .gz, .bgz or .bgzf extension_" bit doesn't apply as there is no filename involved as far as samtools goes.

Appreciated though that this requires knowledge of command lines and shells, so the documentation could be more explicit in stdout, or maybe we need an explicit gzip command line option to force bgzf to stdout too.

**Comment by claczny** [comment]
Fair point and thank you for the reminder.
