### ISSUE TITLE
samtools stats - insert size average difference

### ISSUE THREAD

**Issue by HopedWall** [samtools/samtools#1046]
#### Are you using the latest version of [samtools](https://github.com/samtools/samtools/releases/latest) and [HTSlib](https://github.com/samtools/htslib/releases/latest)? If not, please specify.
I'm using samtools 1.7 (htslib 1.7-2)

 #### Please describe your environment.
Linux 4.4.0-17134-Microsoft (Linux Subsystem for Windows) on x86_64. I don't think this is a platform-specific issue.

#### Please specify the steps taken to generate the issue, the command you are running and the relevant output.
Hi, I'm working with paired-end reads where the average insert size is not provided. I used BBMap in order to align my reads to a genome, and then samtools stats (`samtools stats output.sam | grep "insert size average"`) to obtain the average insert size. The problem is that the average insert size displayed by BBMap is different from the one obtained by samtools. I'm not sure if this is an error on my end (eg. wrong samtools command), a problem in my data (I'm using simulated reads generated from the same genome), or something else entirely. Thanks!

**Comment by valeriuo** [comment]
First of all, you should use the [1.9 release](https://github.com/samtools/samtools/releases/tag/1.9) of samtools, if possible. There have been a lot of improvements added to stats, including to the [insert size](https://github.com/samtools/samtools/commit/618d6244b62125b44c828284eee441780d193349) code.
Second, the command you used looks good, but you should narrow down the discrepancy to a small data subset (a few reads), that you can attach to the issue.

**Comment by valeriuo** [comment]
Please reopen with relevant data, if still present.

**Comment by shouldsee** [comment]
How is samtools insert size calculated??
