### ISSUE TITLE
mpileup output option to report flags of reads

### ISSUE THREAD

**Issue by tedtoal** [samtools/samtools#1052]
I would like to use duplicate reads to call variants, but I want to be able to filter to require at least N non-duplicate supporting alt-allele reads.  To implement this filtering I was attempting to use mpileup to determine how many alt-allele reads were non-duplicates, but to do that I need the DUP flag for each read, which is not available in the mpileup output.

I'd like an option in the samtools mpileup command to report the FLAGS for each read.

**Comment by daviesrob** [comment]
Could you add a small example of the output you're after, please?

**Comment by tedtoal** [comment]
Like this:

```
> samtools mpileup --output-FLAG -r chr1:1758616-1758616  3-CG-214T1.normvdup.recal.bam
chr1    1758616 N       49      C$C$C$C$c$CCCcC$C$ccCcCCCAAAccccccCCcCcccccccccccccccccc        qqllLppjIFkE@jAkkeijiFEEEFFkkFkEFFFFFFFF<F?FF>G8F       1123,99,1123,1123,147,1123,99,1123,147,1024,99,147,83,1171,147,1171,16,1171,147,1171,1171,99,147,163,1187,163,1187,163,163,147,83,1107,83,147,147,147,83,1107,163,1187,1107,83,83,147,99,147,1171,147,83,83,1107,83,1107,83,1040,147,147,1171,1171,147,147,147,1171,147,83,1171,83
```
