### ISSUE TITLE
Feature request: In mpileup output, differentiating between deletions on forward and reverse strands

### ISSUE THREAD

**Issue by jkmatila** [samtools/samtools#1054]
In the `samtools mpileup` output, deletions which stretch out over multiple bases are marked with asterisks (`*`), regardless of whether they are on forward or reverse strand.

**Problem:** This makes it hard to count the strand-specific read depth (including deletions) from the mpileup output. (Especially when the `-l` and/or `-r` command line option is specified and the output may start in the middle of a deletion so that the first line of the deletion which would contain the deleted bases is not included in the output.)

Example output from command `samtools mpileup -l somefile.bed`:

```
chr1	10440	N	10	**c$***AcCa	HFBBBDDIA:
```
Here the line contains five asterisks, with no distinction whether they are on forward or reverse strand.

**Proposed solution:** It would be useful if there would be a way to see whether the deletion is on forward or reverse strand, for example by outputting different character depending on whether it is on forward or reverse strand. (Since this affects the output, perhaps there should be a separate command line option to enable this behavior.)

Hypothetical output from `samtools mpileup -l somefile.bed --enable-proposed-feature`:

```
chr1	10440	N	10	##c$***AcCa	HFBBBDDIA:
```
Here the deletions on the reverse strand were marked with hypothetical `#` and deletions from the forward strand with the usual `*`.

**Comment by daviesrob** [comment]
This seems reasonable, given that all the other possible outputs in that column are capable of showing the strand.

We'll look into this along with all the other recent requests for enhanced mpileup output.
