### ISSUE TITLE
Depth is off-by-one wrt BED file

### ISSUE THREAD

**Issue by ningyuansg** [samtools/samtools#1063]
#### Are you using the latest version of [samtools](https://github.com/samtools/samtools/releases/latest) and [HTSlib](https://github.com/samtools/htslib/releases/latest)? If not, please specify.
(run `samtools --version`)

```$ samtools --version
samtools 1.9
Using htslib 1.9
Copyright (C) 2018 Genome Research Ltd.
```

 #### Please describe your environment.
- OS (run `uname -sr` on Linux/Mac OS or ` wmic os get Caption, Version` on Windows)
``` 
$ uname -sr
Linux 4.15.0-47-generic
```
- machine architecture (run `uname -m` on Linux/Mac OS or ` wmic os get OSArchitecture` on Windows)
```
$ uname -m
x86_64
```
- compiler (run `gcc --version` or `clang --version`)
```
$ gcc --version ; clang --version
gcc (Ubuntu 7.3.0-27ubuntu1~18.04) 7.3.0
Copyright (C) 2017 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.


Command 'clang' not found, but can be installed with:
```

#### Please specify the steps taken to generate the issue, the command you are running and the relevant output.

I am running samtools depth with a BED file. The BED file I provide is:
```
$ cat test.bed 
chr3    10066666        10066667
chr3    10066668        10066669
chr3    10066670        10066671
chr3    10066672        10066673
chr3    10066674        10066675
```

The output I obtain from samtols is 
```
$ cat out.depth 
chr3    10066667        5
chr3    10066669        5
chr3    10066671        5
chr3    10066673        5
chr3    10066675        5
```

The output I expect from samtools is
```
$ cat out.depth 
chr3    10066666        5
chr3    10066668        5
chr3    10066670        5
chr3    10066672        5
chr3    10066674        5
```

BED file entries are 0-based, starting from and including chromStart, up to and excluding chromEnd ([source from UCSC Genome Browser](https://genome.ucsc.edu/FAQ/FAQformat.html#format1)). So, for an entry of 10066666-10066667, I should get the depth for the 1nt positioned at 10066666, not the one at 10066667.

This should be replicable with any sorted and indexed BAM file, with any BED file specifying regions of said BAM files with non-zero coverage. The command to run is
```
samtools depth -b test.bed aligned.sorted.bam
```
where there exists an index file aligned.sorted.bam.bai in the same directory.

**Comment by valeriuo** [comment]
Samtools output is based on the [SAM format](https://github.com/samtools/hts-specs/blob/master/SAMv1.pdf) (section 1.4), which specifies the leftmost position to be 1-based. So a BED entry of  `chr3    10066666        10066667` covers the 1-based position `10066667`. We'll try to make that clearer in the command documentation.

**Comment by ningyuansg** [comment]
I'd like to suggest that (1) this breaks the abstraction that a BED file is meant to provide, and (2) furthermore, this 'SAM format' indexing is inconsistent with samtools view anyways.

### BED file abstraction

When a user obtains a BED file, they do not think of it as a collection of indices, but a collection of regions. So, when they use a BED file, what they mean is 'show me the information associated with this region', and *not* 'the information associated with these indices'. One should not have to be concerned with *how* the data is represented and stored, in order to use it properly. To illustrate: I do not know how an mp4 stores its information, but I can use it anyway, anywhere, with any application. That is supposed to be, in my opinion, the role of data storing file formats.

On the other hand, it is the role of the applications handling the data file to interpret its data representations correctly. There is little reason why, I think, samtools should see the BED file as a collection of indices, rather than of regions—this would be counterintuitive.

### Inconsistency with samtools view

The command in question, depth with BED file argument, uses 1-based indexing, including the first index but *excluding the last*. samtools view, when specified with a region, also uses 1-based indexing, including *both* the first and last indices.

Either way, I would recommend this command be changed to be consistency with the BED file *or* with samtools view. Preferably the former.

**Comment by ningyuansg** [comment]
@valeriuo Any change you'd reconsider?

**Comment by lh3** [comment]
> Any chance you'd reconsider?

No way. Samtools depth follows samtools pileup which has existed more than 10 years. Changing their behavior now will break many tools and pipelines out there.

**Comment by ningyuansg** [comment]
@lh3 I can see where you're coming from. Perhaps the indexing quirk can be mentioned in the man pages somewhere, then? I think most people wouldn't even think about the index, since most people don't generate the BED files themselves. They'd pass their BED files through this depth subcommand assuming what's returned is exactly what the BED files covered—when in fact it's being shifted slightly by 1nt.

**Comment by jmarshall** [comment]
Depth output is not itself SAM, but like other samtools **textual** output its coordinates are 1-based.

So the location you asked for with BED `chr3  10066666  10066667` is being correctly output as `10066667`, which is (in the textual output 1-based notation) exactly what the BED line covers. There is no inconsistency with either BED or samtools view — you might mislead yourself less if your BED regions contained more than one position apiece. For example, BED `chr3  10066666  10066668` would request a two-base region that samtools depth would output in 1-based coordinates as

```
chr3    10066667        5
chr3    10066668        5
```

The individual subcommand documentation for **samtools depth** is not explicit about this, which @valeriuo already agreed was worthy of clarification.

**Comment by jkbonfield** [comment]
The documentation could definitely do with improvement.  Right now the various samtools-_cmd_.1 man pages are just excerpts from the original monolithic man page, but separating them out revealed just how weak the original one was too.  There is nothing at all on the format.

How do people feel about this as a replacement for DESCRIPTION:

> Computes the depth at each position or region.
>
> The output format is chromosome name, 1-based position and the number of aligned bases from all sequences (depth) at that location. 
> Note this means a record aligned over a location but containing a deletion at a specific site will not count towards the depth for that site.

**Comment by jmarshall** [comment]
@jkbonfield: Good, with two quibbles: there are `2+n` columns, where `n` is the number of input BAM files; clarify that “deletion” encompasses both CIGAR `D` and `N` (or so glancing at the code suggests, I haven't exercised it and observed the results).

Oh, and the documentation has a slight preference for spelling `TAB-separated` thus (and often uses `TAB-delimited` instead, though I think that's probably a more obscure term for samtools users).

**Comment by jkbonfield** [comment]
Thanks.

Yes D and N are treated equally.  I want that in the description because it's been a confusion and cause of incorrect bug reports in the past.  There's a whole host of problems surrounding maximum depth, but that's a can of worms I hope to avoid ;-)

Maybe this then?

> Computes the depth at each position or region.
> 
> The output format is one line per genomic location, with TAB-separated columns for chromosome 
> name and 1-based position followed by the number of aligned bases from all sequences (depth) at
> that location for each input file.
>
> Note this means a record aligned over a location but containing a deletion or reference-skip at a
> specific site will not count towards the depth for that site, nor will bases below the **-q** quality
> threshold.

**Comment by ningyuansg** [comment]
> Depth output is not itself SAM, but like other samtools **textual** output its coordinates are 1-based.

Ah, I see where my misunderstanding is now. Thanks!
