### ISSUE TITLE
Samtools to output RX tags for Unique Molecular Indexes (UMI)

### ISSUE THREAD

**Issue by apallav** [samtools/samtools#1064]
Hi,

I would like to know if there is a way in samtools algo to recognize and output UMI / uniq molecular index tags from bam files. ex:RX:Z tags. 

Could this be added as feature request if none is available currently?

Thanks,

Aparna

**Comment by valeriuo** [comment]
By default, `samtools view` outputs all tags attached to a read, starting from column 12.

There is a merged but unreleased pull request (#1001) that filters the reads based on tags, including **RX**. However, the filter only works with a supplied tag value, e.g. 
`samtools view -d RX:AGTCGATA alignment.bam`

But it's not very clear that this feature is what you are after. If you just want to list all the values of a tag present in a file, you can go with a grep filter: 
`samtools view alignment.bam | grep -oE "RX:Z:[acgtnACGTN-]+ | sort -u"`

**Comment by apallav** [comment]
> By default, `samtools view` outputs all tags attached to a read, starting from column 12.
> 
> There is a merged but unreleased pull request (#1001) that filters the reads based on tags, including **RX**. However, the filter only works with a supplied tag value, e.g.
> `samtools view -d RX:AGTCGATA alignment.bam`
> 
> But it's not very clear that this feature is what you are after. If you just want to list all the values of a tag present in a file, you can go with a grep filter:
> `samtools view alignment.bam | grep -oE "RX:Z:[acgtnACGTN-]+ | sort -u"`

I am sorry for not being clear. I would like to see if it is possible for samtools mpileup to give out tag information  just like it gives out Fastq header tags. 

I could use samtools view alignment.bam | grep -oE "RX:Z:[acgtnACGTN-]+ | sort -u" to pipe in to samtools mpileup but that info is lost in the mpile up non vcf or vcf output formats. 

I specifically work with non-vcf formats from samtools / mpileup.

Thanks for your help,

-A

**Comment by valeriuo** [comment]
Closed by https://github.com/samtools/samtools/pull/1073
