### ISSUE TITLE
samtools fixmate output generated without sorting

### ISSUE THREAD

**Issue by CuypersBart** [samtools/samtools#1075]
Works without postion sorted  bam file
`samtools fixmate -m in.bam out.bam `
Throws error
`samtools fixmate -m in.bam -o out.bam`
'file must be grouped by read name '

My question: can the output of the first command be trusted? It generates a file that can be used for
'markduplicates -r'

But I wonder if it is correct, as 
`samtools fixmate -m in.bam -o bam`
says the original input should be sorted

**Comment by whitwham** [comment]
Which version of samtools are you using?  The current version, v1.9, does not take a -o option and the error message for non sorted files is different.

**Comment by whitwham** [comment]
Are you still having a problem?  If not, I am going to close this issue.
