### ISSUE TITLE
Unix command-line Samtools fastq does not say that the input BAM file should be name-sorted

### ISSUE THREAD

**Issue by jackieroger** [samtools/samtools#1078]
When using command-line Samtools fastq (version 1.9), it is not clear that the input BAM file should be name-sorted. The online manual (http://www.htslib.org/doc/samtools.html) includes this information: “The input to this program must be collated by name. Use samtools collate or samtools sort -n to ensure this.” It could be helpful for users of command-line Samtools fastq if that is included in the usage information. Thanks!

**Comment by tseemann** [comment]
Technically it is not compulsory to be name sorted, as it is only paired-end reads where this matters?

**Comment by valeriuo** [comment]
The [note](https://github.com/samtools/samtools/blob/cb6b3b5891ef5d059a3e42283add654ddb42d6eb/bam_fastq.c#L98) is included in the latest `samtools fastq` help message, on the **develop** branch (#1042), and it will be available with the next release.
