### ISSUE TITLE
Using pileup instead of mpileup.

### ISSUE THREAD

**Issue by orijitghosh** [samtools/samtools#1080]
Hi, sorry for a naive question. I am trying to get a pileup file from my BAM file as some old tools I need to use for downstream analysis only supports pileup, not mpileup. It will be great if someone can let me know how I can use an older version of samtools to get a pileup file, when I already have the latest version installed.

**Comment by daviesrob** [comment]
You would need to go back to [release 0.1.16](https://github.com/samtools/samtools/releases/tag/0.1.16).

It's pretty ancient but you should be able to build it.

Out of interest, what difference is there in the output that means `mpileup` can't be used?

**Comment by orijitghosh** [comment]
Hi, I was confused by seeing the way chromosomes were named in PILEUP files vs MPILEUP files, but MPILEUP actually worked fine for me, previously I was committing some other mistake in downstream analysis.

**Comment by tseemann** [comment]
@orijitghosh good news that use solved your problem. can you close this issue now please?

**Comment by orijitghosh** [comment]
yes, thank you @daviesrob @tseemann
