### ISSUE TITLE
query name too long

### ISSUE THREAD

**Issue by FadelBerakdar** [samtools/samtools#1081]
Hi, 

I am trying to convert a SAM file to BAM, the SAM file is generated by novoSplice using simulated reads generated by SimCT. Each simulated read contains alignment info in its name/ identifier, thus reads names are longer than usual.  In this particular case, read name is 256 characters. 

> [E::sam_parse1] query name too long
[W::sam_read1] Parse error at line 148116670
[main_samview] truncated file.

```
$ awk 'NR==148116670' alignment.sam 
50486975:23,35459525,+,9M2584N17M5106N11M936N13M582N14M1319N10M1664N11M1539N13M137N10M4099N7M1759N5M249N9M2230N11M575N10M;23,35467245,-,7M936N13M582N14M1319N10M1664N11M1539N13M137N10M4099N7M1759N5M249N9M2230N11M575N14M14N6M5642N3M7050N7M3085N10M:AAAAAAAAA	99	23	35459528	60	2S7=2584N17=5106N11=936N13=582N14=1319N10=1664N11=1539N13=137N10=4099N7=1759N5=249N9=2230N11=575N7=3S	=	35467246	38748	CTATTTAAGATTCCCAAACCAGATAGGAAATGGTCAGATGGATTTAGCTGTTTTGCCCTTGTATATGCAAACATTAATCATTTATGAATTTACCCATGGATTCGACAAGATAAATTTGAAGCAAGTTAGGCCGACCTTAGAATACATaTa	@BBBCFFFFFFFDHHHHHHHHJJJJJJIGIIJIJIHGEFIIGIEEFHJIIIJJJJJJJJJJJJHGIJGACGB99B9FFGIIJJJJIGIGIIIICAGIJJIJJI@:FFFDDDDDEDE<AEDBB5:<<?CCCBAAABB>B>A@CCDACC###	AS:i:3353	id:Z:ENSDARG00000116857	bt:Z:protein_coding	tm:i:1849
```

Is there any parameter which I can tune to increase query name buffers' size?

**Comment by FadelBerakdar** [comment]
I found in SAM specification, maximum length of read name is 254 

> Length of read name below (= length(QNAME) + 1) uint8 t

**Comment by dpellow** [comment]
@FadelBerakdar how did you solve this issue with your data?

**Comment by Hohnny** [comment]
> 

did you find the reason? my data's query_name length is same, still reporting this error.

**Comment by whitwham** [comment]
From the SAM [specification](https://samtools.github.io/hts-specs/SAMv1.pdf):
`1 QNAME String [!-?A-~]{1,254} Query template NAME`

The read names are limited in length.
