### ISSUE TITLE
samtools mpileup giving incomplete output

### ISSUE THREAD

**Issue by biowizz** [samtools/samtools#1082]
Hello, I am having troubles with running mpile on a merged bam file. I have a two merged bam each of them having 4 bam files each. They are both sorted and running `samtools quickcheck` results in no errors on them.
I am trying to run mpile on these two merged bam files using the below command
`samtools mpileup -l AmpliSeqExome.hg38.bed --no-BAQ -f "$bwa_ref".fa Normal_merged.sorted.bam Tumor_merged.sorted.bam`
The command executes without any error message but generates an incomplete pileup file. There are no entries in the output after chr7. 
Steps tried so far:

- Verified bed file for all the chromosome entries
- Resorted the bam files based on cordinates
- Used another machine to run mpileup (truncated output)

How do I troubleshoot this?
Thanks

**Comment by tseemann** [comment]
Were the BAM files sorted by read name or position?

**Comment by biowizz** [comment]
> Were the BAM files sorted by read name or position?
>
The bam files were sorted by position.

> I have a feeling `quickcheck` only checks the SAM headers.
> What does `samtools view -H file.bam` say?

```
> @HD	VN:1.6	SO:coordinate
> @SQ	SN:chr1	LN:248956422
> @SQ	SN:chr10	LN:133797422
> @SQ	SN:chr11	LN:135086622
> @SQ	SN:chr12	LN:133275309
> @SQ	SN:chr13	LN:114364328
> @SQ	SN:chr14	LN:107043718
> @SQ	SN:chr15	LN:101991189
> @SQ	SN:chr16	LN:90338345
> @SQ	SN:chr17	LN:83257441
> @SQ	SN:chr18	LN:80373285
> @SQ	SN:chr19	LN:58617616
> @SQ	SN:chr2	LN:242193529
> @SQ	SN:chr20	LN:64444167
> @SQ	SN:chr21	LN:46709983
> @SQ	SN:chr22	LN:50818468
> @SQ	SN:chr3	LN:198295559
> @SQ	SN:chr4	LN:190214555
> @SQ	SN:chr5	LN:181538259
> @SQ	SN:chr6	LN:170805979
> @SQ	SN:chr7	LN:159345973
> .
> .

```
This is very frustrating as I feel I have hit a dead end.
I also have [posted on biostars](https://www.biostars.org/p/391439/#392198) from where it all began.

**Comment by jkbonfield** [comment]
Are you running this as part of a longer command line, as in your biostars post, or purely in isolation (writing to a local file).

Please try the latter and report and warning / error messages you see and check the return value (probably in `$?`).  Is samtools exiting silently?

Also, I see your header does indeed *end* with chr7, so that's absolutely normal you'll have chr7 as the final thing reported as it's alphabetically sorted and not numerically.  Are you *SURE* you're missing the data for the other chromosomes?

**Comment by daviesrob** [comment]
If you index your input files, you can also use the `-r` option to rapidly generate pileups over given regions (it can be combined with `-l` which acts as a filter).  If part of your input file is crashing samtools, you may be able to skip over it in this way.

Try to see if you can get output for regions in your bed file that come after where your output apparently stops.  If that works, you can try other regions to see if you can find which part of the input triggers the problem.

**Comment by biowizz** [comment]
> Are you running this as part of a longer command line, as in your biostars post, or purely in isolation (writing to a local file).

I running it as a part of longer command line but now I am running it totally in isolation to troubleshoot.

There are no errors that pop up and samtools exits silently. 

> Are you SURE you're missing the data for the other chromosomes?

Absolutely. 
```
cut -f 1 sample_merged.sorted.mpileup | uniq
chr1
chr2
chr3
chr4
chr5
chr6
chr7
```

**Comment by biowizz** [comment]
> If you index your input files, you can also use the `-r` option to rapidly generate pileups over given regions (it can be combined with `-l` which acts as a filter). If part of your input file is crashing samtools, you may be able to skip over it in this way.
> 
> Try to see if you can get output for regions in your bed file that come after where your output apparently stops. If that works, you can try other regions to see if you can find which part of the input triggers the problem.

I will try to follow the suggestion and revert. Thanks.

**Comment by biowizz** [comment]
> to see if you can get output for regions in your bed file that come after where your output apparently stops. If that works, you can try other regions to see if you can find which part of the input trigge

I think I figured out the problem. I went back to bed file to inspect it near the region samtools exits. There seems to be a blank line separating two entries.

```
chr7    100893945   100894175   ACHE_80133.3.2392   0   +   .   GENE_ID=ACHE;Pool=10;TRIM_LEFT=0;TRIM_RIGHT=0
chr7    100894084   100894305   ACHE_80133.3.7298   0   +   .   GENE_ID=ACHE;Pool=11;TRIM_LEFT=0;TRIM_RIGHT=48

chr7    100990480   100990689   MUC12_80135.1.27552 0   +   .   GENE_ID=MUC12;Pool=1;TRIM_LEFT=1001;TRIM_RIGHT=0
chr7    100990677   100990894   MUC12_80135.1.26417 0   +   .   GENE_ID=MUC12;Pool=2;TRIM_LEFT=1001;TRIM_RIGHT=0
chr7    100990882   100991081   MUC12_80135.1.5617  0   +   .   GENE_ID=MUC12;Pool=3;TRIM_LEFT=1001;TRIM_RIGHT=0
```
I also found three more blank lines in the bed file.

**Comment by jkbonfield** [comment]
I can confirm samtools is silently stopping parsing the bed on the first blank line.  This is probably a bug as it at least should complain (I note blank lines don't appear to be explicitly permitted in BED but I don't see a harm in coping with them).

**Comment by jkbonfield** [comment]
Fixed.  It now just skips blank lines.  I'm unsure if that's permitted in bed, but it's less work than actually raising an error. :-)

**Comment by jmarshall** [comment]
:+1: FWIW bedtools also skips blank lines (but errors on other forms of too-few-columns). So that's _de facto_ permitted!
