### ISSUE TITLE
How the flag '512' to know this read fails platform/vendor quality checks

### ISSUE THREAD

**Issue by lidd77** [samtools/samtools#1096]
HI,

As we know ,  we get a bam file through mapping the fastq file to reference genome  with using some mapping tools , but  actually  as I know ,  the fastq file won't record any information about  whether this read has passed the quality checks ,  so  how the flag '512' is to mark this read ?? and why ? 

or '512' is just the mapping quality check  , to indicate whether this read is in a good mapping quality ?

**Comment by dpryan79** [comment]
Fastq files generally do contain information about whether they have pass or failed vendor quality checks. On data produced by Illumina machines, this is commonly encoded by on the first (sequence identifier line). An entry like the following would indicate that the read failed quality checks (and is therefore eligible to have bit 512 in the BAM/CRAM/SAM flag set):

    @machine:run123:and:so:on 1:Y:0:ACTGACTG

The `Y` indicates that the read failed quality control. Note that (A) you will typically not receive such reads and (B) how Illumina has indicated this has changed over time.

**Comment by jkbonfield** [comment]
If your mapping tools accept BAM (SAM, etc) as input in addition to Fastq then you could use this format.  Storing unmaped data in BAM offers the ability to add arbitrary auxiliary tags, set flags, etc.  It's my preferred route as Fastq was simply never designed to be a feature rich format.

**Comment by lidd77** [comment]
> Fastq files generally do contain information about whether they have pass or failed vendor quality checks. On data produced by Illumina machines, this is commonly encoded by on the first (sequence identifier line). An entry like the following would indicate that the read failed quality checks (and is therefore eligible to have bit 512 in the BAM/CRAM/SAM flag set):
> 
> ```
> @machine:run123:and:so:on 1:Y:0:ACTGACTG
> ```
> 
> The `Y` indicates that the read failed quality control. Note that (A) you will typically not receive such reads and (B) how Illumina has indicated this has changed over time.

Much Thanks ! 
Yes ,  I also  think  not all Illumina fastqs   mark  'Y' or 'N'  in the first line .  
Illumina has changed this so many times , so  perhaps we should delete this  '512'flag from SAM format definition  .

**Comment by jmarshall** [comment]
Illumina has changed their representation in FASTQ, but not the concept.

Moreover the SAM flag is used to represent _filtered-out_ in general, whether as a result of propagating vendor QC or arbitrary user-defined filtering. See samtools/hts-specs#85.
