### ISSUE TITLE
a question about "samtools quickcheck" for CRAM file

### ISSUE THREAD

**Issue by FrankFeng** [samtools/samtools#1098]
Hi,

According to the documantation, `samtools quickcheck` checks "that an end-of-file (EOF) is present and intact (**BAM only**)." Does it mean this EOF checking is not applicable to CRAM files? Thanks!

Regards,

Frank

**Comment by jkbonfield** [comment]
It's a documentation error.  I have a test file with no EOF block in CRAM and it does indeed spot this.  It cannot in SAM as there is no EOF marker present.

I'll update the man page.  Thanks.
