### ISSUE TITLE
Samtools writes / passes through incorrect sort order in @HD SO header, even when sorting file

### ISSUE THREAD

**Issue by leecbaker** [samtools/samtools#110]
When samtools writes a file, it never changes the sort order listed in the header. This can lead to situations where the indicated sort order does not reflect the sort order of the file, causing some operations with other tools to fail.

There has been some discussion about this here (http://seqanswers.com/forums/showthread.php?t=7783), where it is claimed that the spec doesn't require that the sort order be included in the header, so samtools is compliant with the spec; however, when samtools processes a file generated by other tools, it leaves the sort order intact. It would be better to remove it, but ideally the sort order should be updated to be correct.

How to reproduce:
- Use a file that is coordinate sorted, with the header line reflecting this (eg "@HD VN:1.4 SO:coordinate")
- Sort this file by query name using samtools ("samtools sort -n in.bam out")
- Observe that the file header incorrectly indicates that the file is coordinate sorted, when it is actually sorted by query name ("samtools view -H")

Ideal behavior:
- Samtools sort updates the sort order to "coordinate" or "queryname" in the sort command
- Other samtools commands mark the sort order correctly when a bam is generated

**Comment by kirkmcclure** [comment]
This appears to have been fixed.
````
head -1 test/dat/view.001.sam
@HD	VN:1.4	SO:coordinate
./samtools view -b -o /tmp/view.001.bam -f test/dat/view.001.fa test/dat/view.001.sam
./samtools index /tmp/view.001.bam
./samtools sort -n /tmp/view.001.bam /tmp/view.001.sorted
./samtools view -H /tmp/view.001.sorted.bam | head -1
@HD	VN:1.4	SO:queryname

/samtools sort -n -o /tmp/view.001.sorted.sam -O sam -T /tmp/view.001.sorted /tmp/view.001.bam
diff /tmp/view.001.sorted.sam test/dat/view.001.sam | grep "@HD"
< @HD	VN:1.4	SO:queryname
> @HD	VN:1.4	SO:coordinate
diff /tmp/view.001.sorted.sam test/dat/view.001.sam | tail -6
59d56
< ref12_grp2_p001	97	ref1	46	50	10M	ref2	120CAAGCTTGAG	AAAAAAAAAA	RG:Z:grp2	NM:i:0	MD:Z:10
60a58,60
> ref2_grp3_p002	147	ref2	16	99	15M	=	4645CTAAATAGCTTGGCG	}}}}}}}}}}}}}}}	RG:Z:grp3	NM:i:0	MD:Z:15
> ref2_grp3_p001	163	ref2	31	99	15M	=	1-45CTGTTTCCTGTGTGA	|||||||||||||||	RG:Z:grp3	NM:i:13	MD:Z:0T0A0A1C0A0T0G0G0T0C0A1A0G0
> ref2_grp3_p002	99	ref2	46	99	15M	=	16-45CTGTTTCCTGTGTGA	{{{{{{{{{{{{{{{	RG:Z:grp3	NM:i:0	MD:Z:15
````

**Comment by SamStudio8** [comment]
#481

**Comment by valeriuo** [comment]
Fixed by https://github.com/samtools/samtools/commit/3ecdcc4760ae76bbdedaa40ae0d4c0bff26a5b20 (version 1.7+).
