### ISSUE TITLE
A question in install, thanks a lot

### ISSUE THREAD

**Issue by Flingspider** [samtools/samtools#1102]
checking for lzma.h... yes
checking for lzma_easy_buffer_encode in -llzma... no
configure: error: liblzma development files not found

The CRAM format may use LZMA2 compression, which is implemented in HTSlib
by using compression routines from liblzma <http://tukaani.org/xz/>.

Building HTSlib requires liblzma development files to be installed on the
build machine; you may need to ensure a package such as liblzma-dev (on Debian
or Ubuntu Linux), xz-devel (on RPM-based Linux distributions or Cygwin), or
xz (via Homebrew on macOS) is installed; or build XZ Utils from source.

Either configure with --disable-lzma (which will make some CRAM files
produced elsewhere unreadable) or resolve this error to build HTSlib.
configure: error: ./configure failed for htslib-1.9
[zhangxq@localhost samtools-1.9]$

**Comment by daviesrob** [comment]
The [INSTALL](https://github.com/samtools/samtools/blob/74718c2/INSTALL#L197) file has instructions for installing samtools' dependencies on various Linux distributions.  Follow the instructions there and you should be able to run `configure` successfully.
