### ISSUE TITLE
Samtools ignores specific zlib error codes in bgzf.c

### ISSUE THREAD

**Issue by ChristopherWilks** [samtools/samtools#111]
Hi Folks,

First, thanks for continuing to maintain and improve samtools through htslib.  This is a great resource and has saved me (and many others) a lot of time when working with BAM files.  

This is a specific case of the general issues mentioned by jmarshall in 
https://github.com/samtools/samtools/issues/51

using samtools 0.1.19-44428cd:

samread->bam_read1->bgzf_read->bgzf_read_block->inflate_block

when zlib's inflateInit2 doesn't return a Z_OK, inflate_block in bgzf.c ORs fp->errcode with the general BGZF_ERR_ZLIB and then returns a -1 no matter what the specific error is coming from zlib.

My specific issue was that zlib will fail due to a Z_MEM_ERROR usually correlated with virtual memory limits on certain larger BAM files in the context of a job scheduler, but samtools ultimately "raises" this as a -4 ignoring the specific zlib error.

I've also seen a memory limit error be misrepresented as a truncated BAM problem during BAM indexing.

The core problem still appears to be an issue within Samtools using htsllib, as a quick reading of the inflate_block function in bgzf.c in htslib still ignores the returned error code from zlib:

```
 if (inflateInit2(&zs, -15) != Z_OK) {
                fp->errcode |= BGZF_ERR_ZLIB;
                return -1;
        }
```

This isn't a "show stopper" bug but it is incorrect (and annoying) that the real error is not being surfaced by Samtools.  I had to trace the calls via GDB to confirm that the issue was really memory limits rather than BAM format or something else. 

thanks,
Chris

**Comment by jmarshall** [comment]
Fixed by PR samtools/htslib#271.
