### ISSUE TITLE
Incorrect BAM?

### ISSUE THREAD

**Issue by qin218** [samtools/samtools#1111]
Hi there,
I used NCBI sratoolkit.2.9.6.1-mac64 to generate the SAM from NCBI SRA:
./sam-dump SRR8097370 > SRR8097370.sam

Then samtools-1.9
samtools view -S -b SRR8097370.sam > SRR8097370.bam
samtools index SRR8097370.bam

"samtools view -H SRR8097370.bam" - no error message, nothing printed
"samtools view SRR8097370.bam | head" -see below:

1 77 * 0 0 * * 0 0 TGGAANAAAACTTACTAAAACCTAGGTAACTCTAGATTAGGCCAGTTCAGGTGTATTTTGTATCTTAGTAATGG AAAAA#EEEEEEEEEEEEEEEEEEEEEEEEEEEAEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEAEEAEEEE RG:Z:GGCTAC

1 141 * 0 0 * * 0 0 NNNAAATACATGACCTTTCCCTCAACAGAACAGCATAATCAATATATCTTCCCAACTTATCTCTATTTTTACGAT ###AAAEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE6EEEEEEEEAEEEEEEEEEEAEEE RG:Z:GGCTAC

2 77 * 0 0 * * 0 0 TGCGACCTCTTCATTCCCATGCAGTTTGGGATCATCCAGAAGCATCTGAAGACCATGGATCACAACCGGAACCGC AAAAAEEEEEEEEEEAEEEEE/EEEEEEAEAEEEE/AAEEAE/EE/EEE/EAE<6EEE/EEE/E/A<EEAAE6E6 RG:Z:GGCTAC

2 141 * 0 0 * * 0 0 NNNGAGCCTGCGGTTCCGGTTGTGATCCATGGTCTTCAGATGCTTCTGGATGATCCCAAACTGCATGGGAATGA ###AAEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE/EEEEEEEEEEEEEEEEEEEEAEEEEEAEEEEE/AEE RG:Z:GGCTAC

3 77 * 0 0 * * 0 0 AGGAAGTCAGGCCGCCATAGGAAGAATGATCCACTTTGGACGAGAGCTGCAAGCAATGAGTGAACAGCTAAGG AAAAAEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE RG:Z:GGCTAC

3 141 * 0 0 * * 0 0 NNNTCTCTCCTTAGCTGTTCACTCATTGCTTGCAGCTCTCGTCCAAAGTGGATCATTCTTCCTATGGCGGCCTG ###AAEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE RG:Z:GGCTAC

4 77 * 0 0 * * 0 0 TTTGGAGAGTAGCAAATCTAGCTTTTTTGTACAGACTTAGAAATTATCTAAAGATTTCATCTTTTTACCTCATAT AAAAA/EEEEEEAE/EE/E/E/EEEEEEEE//AEA/EE/EE/EEEAEE//A/EEEEE/EE6EEEEE///E<6E<E RG:Z:GGCTAC

4 141 * 0 0 * * 0 0 NNNATACATGTTGATTGAGCCAAAAGACATAGGAAAAAAAGACAACATATAACCATTAAATTCCTAAGAAATATG ###/A//EEEEEEEEEEEEE/AAE/EAEEE/EE//</EE/EEEAAEEE/EEEA6EEEEAAEEA/E//AA//E/EE RG:Z:GGCTAC

5 77 * 0 0 * * 0 0 AATTTACTGAAATAACAAAAACGTGGACTTTGGGATTTCCTCTAACTGCTGCAAATTATAAC AAAAAEEEEEEEEEEEEEEEEEEEEE<EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE RG:Z:GGCTAC

5 141 * 0 0 * * 0 0 NNNATAATTTGCAGCAGTTAGAGGAAATCCCAAAGTCCACGTTTTTGTTATTTCAGTAAATTGATCGTCGGACTG ###AAEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEAEEEEEEEE RG:Z:GGCTAC

I also can't see any reads in the IGV.
And I also tried NCBI genome workbench, and it says "Loading BAM file: no items created".

Could anyone here know what is possibly going wrong? Thanks!

**Comment by jkbonfield** [comment]
It's an unaligned BAM, as such it doesn't need anything in the header (no `@SQ` lines required).  Personally I think it's good practice to at least put in an `@HD` record, but the above is legal.

Hence `samtools -H` returns nothing because the header is blank.

**Comment by qin218** [comment]
Thanks for the information.
