### ISSUE TITLE
Testing mpileup.reg regressions error

### ISSUE THREAD

**Issue by MiguelMque** [samtools/samtools#1114]
Lastest version of samtools and htslib, please help, while I do make check it throws me this:

=== Testing mpileup.reg regressions ===

EXPECTED FAIL: Task failed, but expected to fail;
when running $samtools mpileup -Q0 -x -f c1.fa c1#pad1.bam

EXPECTED FAIL: Task failed, but expected to fail;
when running $samtools mpileup -Q0 -x -f c1.fa c1#pad2.bam

UNEXPECTED FAIL: Output mismatch for $samtools mpileup -x -v -f mpileup.ref.fa mpileup.1.bam | $filter
See FAIL-49.out.1 vs expected/49.out

UNEXPECTED FAIL: Output mismatch for $samtools mpileup -x -v -f mpileup.ref.fa mpileup.1.cram | $filter
See FAIL-49.out.2 vs expected/49.out

EXPECTED FAIL: Task failed, but expected to fail;
when running $samtools mpileup -ABQ0 -a -l xx.bed3 xx#depth3.bam

Expected   passes:   153
Unexpected passes:   0
Expected   failures: 3
Unexpected failures: 2
=> FAIL
make: *** [check] Error 1

What can I do to solve the problem?

Thanks in advanced

**Comment by valeriuo** [comment]
> Lastest version of samtools and htslib

Latest from develop or master? What does `samtools --version` say?

Try 
```
cd <samtools folder>/test/mpileup
diff FAIL-49.out.1 expected/49.out
```
and
```
cmp FAIL-49.out.1 expected/49.out`
```
and paste the output of these commands here.

**Comment by MiguelMque** [comment]
Thanks for your response valeriou, it is latest from master and samtools --version says the following:

samtools 1.9-172-ga0b6c71
Using htslib 1.9-390-g7fc833d-dirty
Copyright (C) 2019 Genome Research Ltd.

1. diff FAIL-49.out.1 expected/49.out: 
3496c3496
< 17	3493	.	CAAAAAAAAAAAAA	CAAAAAAAAAAAA,CAAAAAAAAAAAAAA	0	.INDEL;I16=5,5,5,5,5,5,5,5,5,5,89,4441,147,3143,30,650;QS=0.833333,0.0833333,0.0833333	PL	0,22,42,22,44,42
---
> 17	3493	.	CAAAAAAAAAAAAA	CAAAAAAAAAAAA,CAAAAAAAAAAAAAA	0	.INDEL;I16=5,5,0,2,255,6523,47,1129,600,36000,89,4441,147,3143,30,650;QS=0.833333,0.0833333,0.0833333	PL	0,22,42,22,44,42

2. cmp FAIL-49.out.1 expected/49.out:

FAIL-49.out.1 expected/49.out differ: byte 326196, line 3496

**Comment by valeriuo** [comment]
> samtools 1.9-172-ga0b6c71
> Using htslib 1.9-390-g7fc833d-dirty

This is not the latest from master. And it looks like the htslib code has been modified (dirty).
Go to your htslib folder and run `git status`. It will tell you how your code stands with respect to the upstream branch. If there are any modified files, check what those changes are.
  
You can also run `git describe`. It should match `1.9-390-g7fc833d-dirty`, which means you have a modified htslib baked into your samtools executable. You should then either fix your changes or reset to `develop HEAD`.

**Comment by valeriuo** [comment]
Please reopen if issue persists.
