### ISSUE TITLE
Find all the reads changes in the bam file

### ISSUE THREAD

**Issue by Yichel518** [samtools/samtools#1116]
Hello, I using samtools mpileup to find snp or indel according BAM file,and I need to find all the reads changes in the bam file, but the tool seems to filter them out automatically.
What can I do for it?
Thanks!

**Comment by tseemann** [comment]
What do you mean by "fnd all the reads changes in the bam file" ?

**Comment by Yichel518** [comment]
Thanks @tseemann 
According to the sixth column information of Sam file, such as "169H41M1I25M15H"（I = insert M=match）,I figured out about 30,000, However, according to the "+[0-9]+[ACGT (ACGT) Nacgtn]+" or "-[0-9]+[ACGT (ACGT) Nacgtn]+" in the mpileup file, only half of the quantity is calculated. I don't know why?

**Comment by Yichel518** [comment]
Thanks @tseemann
According to the sixth column information of Sam file, such as "169H41M1I25M15H"（I = insert M=match）,I figured out about 30,000, However, according to the "+[0-9]+[ACGT (acgt) Nacgtn]+" or "-[0-9]+[ACGT (acgt) Nacgtn]+" in the mpileup file, only half of the quantity is calculated. I don't know why?

**Comment by Yichel518** [comment]
and my CMD is "samtools mpileup -f  /home/yxtu/gRNA/new_test/fasta/chr1.fa -d 487845 /home/yxtu/gRNA/new_test/ankrd37.bam > /home/yxtu/gRNA/new_test/mpileup/ankrd37.bam.mpileup

**Comment by tseemann** [comment]
```
  -q, --min-MQ INT        skip alignments with mapQ smaller than INT [0]
  -Q, --min-BQ INT        skip bases with baseQ/BAQ smaller than INT [13]
```

Try `-Q 0` ?

**Comment by Yichel518** [comment]
Thank you so much ! the number of indel is increased!!!
