### ISSUE TITLE
samtools index: failed to create index: Numerical result out of range

### ISSUE THREAD

**Issue by jhcaddisfly** [samtools/samtools#1118]
#### Are you using the latest version of [samtools](https://github.com/samtools/samtools/releases/latest) and [HTSlib](https://github.com/samtools/htslib/releases/latest)? If not, please specify.
(run `samtools --version`)

Yes:
samtools 1.9
Using htslib 1.9
Copyright (C) 2018 Genome Research Ltd.

 #### Please describe your environment.
- OS (run `uname -sr` on Linux/Mac OS or ` wmic os get Caption, Version` on Windows)
- machine architecture (run `uname -m` on Linux/Mac OS or ` wmic os get OSArchitecture` on Windows)
- compiler (run `gcc --version` or `clang --version`)

Linux 3.10.0-957.21.3.el7.x86_64
x86_64
gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-36)

#### Please specify the steps taken to generate the issue, the command you are running and the relevant output.
Hello,
I really need help!

I mapped short reads to a fasta file using ngm and piped the output to samtools.
I used samtools sort to generate a sorted bamfile which I want to index with samtools index.

This is the command I used:
`ngm -r HK1_racon1_nanopolished_genome.fa -1 cHK1_1.fq -2 cHK1_2.fq -t64 --max-read-length 150 --affine | samtools sort -l 9 -@ 10 -O BAM -o HK1.paired.sort.bam && samtools index HK1.paired.sort.bam`

I got the following error message:
[bam_sort_core] merging from 310 files and 10 in-memory blocks...
[E::hts_idx_push] Region 589897413..589897563 cannot be stored in a bai index. Try using a csi index with min_shift = 14, n_lvls >= 6
samtools index: failed to create index for "HK1.paired.sort.bam": Numerical result out of range

I laso tried `samtools index -c HK1.paired.sort.bam` but got the same error message.

Thanks,

Jacqueline

**Comment by valeriuo** [comment]
Can you show the output of this command?

`samtools view -H HK1.paired.sort.bam | grep "^@SQ"`

The **LN** field on each line is the one of interest.

**Comment by jhcaddisfly** [comment]
(samtools) -bash-4.2$ samtools view -H HK1.paired.sort.bam | grep "^@SQ"
@SQ     SN:ctg1 LN:11755914
@SQ     SN:ctg2 LN:26178236
@SQ     SN:ctg3 LN:35803611
@SQ     SN:ctg4 LN:9399180
@SQ     SN:ctg5 LN:12170952
@SQ     SN:ctg6 LN:21468360
@SQ     SN:ctg7 LN:7885224
@SQ     SN:ctg8 LN:7403663
@SQ     SN:ctg9 LN:6666907
@SQ     SN:ctg10        LN:23660883
@SQ     SN:ctg11        LN:8190672
@SQ     SN:ctg12        LN:9534817
@SQ     SN:ctg13        LN:6498356
@SQ     SN:ctg14        LN:17126868
@SQ     SN:ctg15        LN:6314243
@SQ     SN:ctg16        LN:10981139
@SQ     SN:ctg17        LN:7600640
@SQ     SN:ctg18        LN:5885822
@SQ     SN:ctg19        LN:6877687
@SQ     SN:ctg20        LN:5935540
@SQ     SN:ctg21        LN:5444747
@SQ     SN:ctg22        LN:20679261
@SQ     SN:ctg23        LN:5314221
@SQ     SN:ctg24        LN:5319325
@SQ     SN:ctg25        LN:4864666
@SQ     SN:ctg26        LN:15078917
@SQ     SN:ctg27        LN:7868991
@SQ     SN:ctg28        LN:6741688
@SQ     SN:ctg29        LN:13939969
@SQ     SN:ctg30        LN:4693152
@SQ     SN:ctg31        LN:4942951
@SQ     SN:ctg32        LN:7207698
@SQ     SN:ctg33        LN:4468356
@SQ     SN:ctg34        LN:6580662
@SQ     SN:ctg35        LN:5833138
@SQ     SN:ctg36        LN:15096158
@SQ     SN:ctg37        LN:11678086
@SQ     SN:ctg38        LN:13094951
@SQ     SN:ctg39        LN:4006062
@SQ     SN:ctg40        LN:3948841
@SQ     SN:ctg41        LN:5760126
@SQ     SN:ctg42        LN:3765447
@SQ     SN:ctg43        LN:3569980
@SQ     SN:ctg44        LN:3503126
@SQ     SN:ctg45        LN:4853755
@SQ     SN:ctg46        LN:5631963
@SQ     SN:ctg47        LN:3343275
@SQ     SN:ctg48        LN:3285234
@SQ     SN:ctg49        LN:3265483
@SQ     SN:ctg50        LN:3113155
@SQ     SN:ctg51        LN:2934593
@SQ     SN:ctg52        LN:2925688
@SQ     SN:ctg53        LN:5157989
@SQ     SN:ctg54        LN:3723405
@SQ     SN:ctg55        LN:2814256
@SQ     SN:ctg56        LN:2818470
@SQ     SN:ctg57        LN:2749893
@SQ     SN:ctg58        LN:2758347
@SQ     SN:ctg59        LN:2610250
@SQ     SN:ctg60        LN:3089399
@SQ     SN:ctg61        LN:3315081
@SQ     SN:ctg62        LN:2414671
@SQ     SN:ctg63        LN:2333364
@SQ     SN:ctg64        LN:2308158
@SQ     SN:ctg65        LN:2969206
@SQ     SN:ctg66        LN:2198089
@SQ     SN:ctg67        LN:2187207
@SQ     SN:ctg68        LN:4922620
@SQ     SN:ctg69        LN:2440951
@SQ     SN:ctg70        LN:2117424
@SQ     SN:ctg71        LN:2473835
@SQ     SN:ctg72        LN:2465646
@SQ     SN:ctg73        LN:2001362
@SQ     SN:ctg74        LN:1987882
@SQ     SN:ctg75        LN:1893481
@SQ     SN:ctg76        LN:1890519
@SQ     SN:ctg77        LN:1881752
@SQ     SN:ctg78        LN:1840413
@SQ     SN:ctg79        LN:1807844
@SQ     SN:ctg80        LN:1810640
@SQ     SN:ctg81        LN:1692521
@SQ     SN:ctg82        LN:1591273
@SQ     SN:ctg83        LN:1575444
@SQ     SN:ctg84        LN:1611158
@SQ     SN:ctg85        LN:1503837
@SQ     SN:ctg86        LN:1495692
@SQ     SN:ctg87        LN:1368752
@SQ     SN:ctg88        LN:1368362
@SQ     SN:ctg89        LN:1314363
@SQ     SN:ctg90        LN:1278301
@SQ     SN:ctg91        LN:2467309
@SQ     SN:ctg92        LN:2161917
@SQ     SN:ctg93        LN:1216048
@SQ     SN:ctg94        LN:1145568
@SQ     SN:ctg95        LN:1862028
@SQ     SN:ctg96        LN:1129194
@SQ     SN:ctg97        LN:1083296
@SQ     SN:ctg98        LN:1074244
@SQ     SN:ctg99        LN:1043780
@SQ     SN:ctg100       LN:1735319
@SQ     SN:ctg101       LN:1020145
@SQ     SN:ctg102       LN:996459
@SQ     SN:ctg103       LN:968663
@SQ     SN:ctg104       LN:2521451
@SQ     SN:ctg105       LN:906606
@SQ     SN:ctg106       LN:878426
@SQ     SN:ctg107       LN:792782
@SQ     SN:ctg108       LN:757930
@SQ     SN:ctg109       LN:758806
@SQ     SN:ctg110       LN:753436
@SQ     SN:ctg111       LN:877136
@SQ     SN:ctg112       LN:735798
@SQ     SN:ctg113       LN:789512
@SQ     SN:ctg114       LN:717443
@SQ     SN:ctg115       LN:677913
@SQ     SN:ctg116       LN:686847
@SQ     SN:ctg117       LN:639698
@SQ     SN:ctg118       LN:612860
@SQ     SN:ctg119       LN:575044
@SQ     SN:ctg120       LN:459950
@SQ     SN:ctg121       LN:441725
@SQ     SN:ctg122       LN:605762
@SQ     SN:ctg123       LN:345375
@SQ     SN:ctg124       LN:383545
@SQ     SN:ctg125       LN:313129
@SQ     SN:ctg126       LN:292037
@SQ     SN:ctg127       LN:277171
@SQ     SN:ctg128       LN:274094
@SQ     SN:ctg129       LN:261731
@SQ     SN:ctg130       LN:255305
@SQ     SN:ctg131       LN:294148
@SQ     SN:ctg132       LN:246901
@SQ     SN:ctg133       LN:321833
@SQ     SN:ctg134       LN:216286
@SQ     SN:ctg135       LN:184384
@SQ     SN:ctg136       LN:181841
@SQ     SN:ctg137       LN:239324
@SQ     SN:ctg138       LN:126534
@SQ     SN:ctg139       LN:247583
@SQ     SN:ctg140       LN:108047
@SQ     SN:ctg141       LN:109994
@SQ     SN:ctg142       LN:108829
@SQ     SN:ctg143       LN:105644
@SQ     SN:ctg144       LN:99620
@SQ     SN:ctg145       LN:220947
@SQ     SN:ctg146       LN:127477
@SQ     SN:ctg147       LN:87029
@SQ     SN:ctg148       LN:83984
@SQ     SN:ctg149       LN:81094
@SQ     SN:ctg150       LN:75358
@SQ     SN:ctg151       LN:135154
@SQ     SN:ctg152       LN:72213
@SQ     SN:ctg153       LN:62063
@SQ     SN:ctg154       LN:88573
@SQ     SN:ctg155       LN:61404
@SQ     SN:ctg156       LN:57361
@SQ     SN:ctg157       LN:69513
@SQ     SN:ctg158       LN:53680
@SQ     SN:ctg159       LN:54146
@SQ     SN:ctg160       LN:51579
@SQ     SN:ctg161       LN:53260
@SQ     SN:ctg162       LN:52847
@SQ     SN:ctg163       LN:62066
@SQ     SN:ctg164       LN:51148
@SQ     SN:ctg165       LN:52344
@SQ     SN:ctg166       LN:46455
@SQ     SN:ctg167       LN:49378
@SQ     SN:ctg168       LN:47842
@SQ     SN:ctg169       LN:131244
@SQ     SN:ctg170       LN:57056
@SQ     SN:ctg171       LN:39620
@SQ     SN:ctg172       LN:64614
@SQ     SN:ctg173       LN:36663
@SQ     SN:ctg174       LN:32892
@SQ     SN:ctg175       LN:32196
@SQ     SN:ctg176       LN:32139
@SQ     SN:ctg177       LN:39839
@SQ     SN:ctg178       LN:30645
@SQ     SN:ctg179       LN:29433
@SQ     SN:ctg180       LN:29683
@SQ     SN:ctg181       LN:99229
@SQ     SN:ctg182       LN:25959
@SQ     SN:ctg183       LN:54339
@SQ     SN:ctg184       LN:26348
@SQ     SN:ctg185       LN:24764
@SQ     SN:ctg186       LN:25210
@SQ     SN:ctg187       LN:25497
@SQ     SN:ctg188       LN:45711
@SQ     SN:ctg189       LN:24007
@SQ     SN:ctg190       LN:23600
@SQ     SN:ctg191       LN:23788
@SQ     SN:ctg192       LN:23058
@SQ     SN:ctg193       LN:23893
@SQ     SN:ctg194       LN:22122
@SQ     SN:ctg195       LN:16696
@SQ     SN:ctg196       LN:21066
@SQ     SN:ctg197       LN:44254
@SQ     SN:ctg198       LN:21294
@SQ     SN:ctg199       LN:23157
@SQ     SN:ctg200       LN:21485
@SQ     SN:ctg201       LN:20903
@SQ     SN:ctg202       LN:20954
@SQ     SN:ctg203       LN:20860
@SQ     SN:ctg204       LN:20246
@SQ     SN:ctg205       LN:20208
@SQ     SN:ctg206       LN:35450
@SQ     SN:ctg207       LN:20166
@SQ     SN:ctg208       LN:19488
@SQ     SN:ctg209       LN:19281
@SQ     SN:ctg210       LN:40247
@SQ     SN:ctg211       LN:33092
@SQ     SN:ctg212       LN:19265
@SQ     SN:ctg213       LN:18743
@SQ     SN:ctg214       LN:76292
@SQ     SN:ctg215       LN:18859
@SQ     SN:ctg216       LN:18101
@SQ     SN:ctg217       LN:18670
@SQ     SN:ctg218       LN:17842
@SQ     SN:ctg219       LN:15437
@SQ     SN:ctg220       LN:17380
@SQ     SN:ctg221       LN:23832
@SQ     SN:ctg222       LN:17539
@SQ     SN:ctg223       LN:17210
@SQ     SN:ctg224       LN:17227
@SQ     SN:ctg225       LN:17825
@SQ     SN:ctg226       LN:18031
@SQ     SN:ctg227       LN:16711
@SQ     SN:ctg228       LN:16701
@SQ     SN:ctg229       LN:16450
@SQ     SN:ctg230       LN:14591
@SQ     SN:ctg231       LN:16301
@SQ     SN:ctg232       LN:16489
@SQ     SN:ctg233       LN:16562
@SQ     SN:ctg234       LN:16248
@SQ     SN:ctg235       LN:11634
@SQ     SN:ctg236       LN:15044
@SQ     SN:ctg237       LN:15905
@SQ     SN:ctg238       LN:14909
@SQ     SN:ctg239       LN:15567
@SQ     SN:ctg240       LN:15078
@SQ     SN:ctg241       LN:15162
@SQ     SN:ctg242       LN:13607
@SQ     SN:ctg243       LN:15439
@SQ     SN:ctg244       LN:14885
@SQ     SN:ctg245       LN:14604
@SQ     SN:ctg246       LN:14072
@SQ     SN:ctg247       LN:14305
@SQ     SN:ctg248       LN:14076
@SQ     SN:ctg249       LN:13981
@SQ     SN:ctg250       LN:14604
@SQ     SN:ctg251       LN:13416
@SQ     SN:ctg252       LN:10647
@SQ     SN:ctg253       LN:13706
@SQ     SN:ctg254       LN:13891
@SQ     SN:ctg255       LN:13342
@SQ     SN:ctg256       LN:13928
@SQ     SN:ctg257       LN:13338
@SQ     SN:ctg258       LN:12923
@SQ     SN:ctg259       LN:13528
@SQ     SN:ctg260       LN:13131
@SQ     SN:ctg261       LN:12877
@SQ     SN:ctg262       LN:13479
@SQ     SN:ctg263       LN:25201
@SQ     SN:ctg264       LN:13898
@SQ     SN:ctg265       LN:12967
@SQ     SN:ctg266       LN:12995
@SQ     SN:ctg267       LN:12848
@SQ     SN:ctg268       LN:12445
@SQ     SN:ctg269       LN:16650
@SQ     SN:ctg270       LN:11939
@SQ     SN:ctg271       LN:12481
@SQ     SN:ctg272       LN:11835
@SQ     SN:ctg273       LN:12536
@SQ     SN:ctg274       LN:11992
@SQ     SN:ctg275       LN:12423
@SQ     SN:ctg276       LN:12437
@SQ     SN:ctg277       LN:12483
@SQ     SN:ctg278       LN:12330
@SQ     SN:ctg279       LN:12438
@SQ     SN:ctg280       LN:12408
@SQ     SN:ctg281       LN:12311
@SQ     SN:ctg282       LN:12269
@SQ     SN:ctg283       LN:12183
@SQ     SN:ctg284       LN:12011
@SQ     SN:ctg285       LN:12024
@SQ     SN:ctg286       LN:11220
@SQ     SN:ctg287       LN:12322
@SQ     SN:ctg288       LN:11790
@SQ     SN:ctg289       LN:11849
@SQ     SN:ctg290       LN:12132
@SQ     SN:ctg291       LN:11025
@SQ     SN:ctg292       LN:10991
@SQ     SN:ctg293       LN:17199
@SQ     SN:ctg294       LN:12092
@SQ     SN:ctg295       LN:11178
@SQ     SN:ctg296       LN:12755
@SQ     SN:ctg297       LN:11017
@SQ     SN:ctg298       LN:11005
@SQ     SN:ctg299       LN:11226
@SQ     SN:ctg300       LN:10797
@SQ     SN:ctg301       LN:10659
@SQ     SN:ctg302       LN:10815
@SQ     SN:ctg303       LN:11019
@SQ     SN:ctg304       LN:10628
@SQ     SN:ctg305       LN:18883
@SQ     SN:ctg306       LN:10880
@SQ     SN:ctg307       LN:17814
@SQ     SN:ctg308       LN:10380
@SQ     SN:ctg309       LN:11726
@SQ     SN:ctg310       LN:10287
@SQ     SN:ctg311       LN:10241
@SQ     SN:ctg312       LN:10005
@SQ     SN:ctg313       LN:10331
@SQ     SN:ctg314       LN:9545
@SQ     SN:ctg315       LN:9931
@SQ     SN:ctg316       LN:10144
@SQ     SN:ctg317       LN:10247
@SQ     SN:ctg318       LN:10099
@SQ     SN:ctg319       LN:10407
@SQ     SN:ctg320       LN:10081
@SQ     SN:ctg321       LN:10145
@SQ     SN:ctg322       LN:10150
@SQ     SN:ctg323       LN:10160
@SQ     SN:ctg324       LN:9830
@SQ     SN:ctg325       LN:9976
@SQ     SN:ctg326       LN:10008
@SQ     SN:ctg327       LN:10366
@SQ     SN:ctg328       LN:9849
@SQ     SN:ctg329       LN:10008
@SQ     SN:ctg330       LN:21725
@SQ     SN:ctg331       LN:15134
@SQ     SN:ctg332       LN:9962
@SQ     SN:ctg333       LN:15556
@SQ     SN:ctg334       LN:10244
@SQ     SN:ctg335       LN:9811
@SQ     SN:ctg336       LN:10104
@SQ     SN:ctg337       LN:9786
@SQ     SN:ctg338       LN:5033
@SQ     SN:ctg340       LN:19783
@SQ     SN:ctg341       LN:9336
@SQ     SN:ctg342       LN:9844
@SQ     SN:ctg343       LN:8630
@SQ     SN:ctg344       LN:8888
@SQ     SN:ctg345       LN:9089
@SQ     SN:ctg346       LN:9145
@SQ     SN:ctg347       LN:9146
@SQ     SN:ctg348       LN:8828
@SQ     SN:ctg349       LN:9184
@SQ     SN:ctg350       LN:9193
@SQ     SN:ctg351       LN:9326
@SQ     SN:ctg352       LN:8390
@SQ     SN:ctg353       LN:9037
@SQ     SN:ctg354       LN:9279
@SQ     SN:ctg355       LN:9072
@SQ     SN:ctg356       LN:8606
@SQ     SN:ctg357       LN:9056
@SQ     SN:ctg358       LN:8658
@SQ     SN:ctg359       LN:8827
@SQ     SN:ctg360       LN:10928
@SQ     SN:ctg361       LN:9388
@SQ     SN:ctg362       LN:10057
@SQ     SN:ctg363       LN:9358
@SQ     SN:ctg364       LN:8767
@SQ     SN:ctg365       LN:8809
@SQ     SN:ctg367       LN:8222
@SQ     SN:ctg368       LN:8855
@SQ     SN:ctg369       LN:8399
@SQ     SN:ctg370       LN:8380
@SQ     SN:ctg371       LN:18064
@SQ     SN:ctg372       LN:8125
@SQ     SN:ctg373       LN:16843
@SQ     SN:ctg374       LN:7756
@SQ     SN:ctg375       LN:8290
@SQ     SN:ctg376       LN:8024
@SQ     SN:ctg377       LN:8167
@SQ     SN:ctg378       LN:8502
@SQ     SN:ctg379       LN:8339
@SQ     SN:ctg380       LN:8222
@SQ     SN:ctg381       LN:8832
@SQ     SN:ctg382       LN:8040
@SQ     SN:ctg383       LN:8273
@SQ     SN:ctg384       LN:8228
@SQ     SN:ctg385       LN:8192
@SQ     SN:ctg386       LN:8352
@SQ     SN:ctg387       LN:8062
@SQ     SN:ctg388       LN:8257
@SQ     SN:ctg389       LN:8259
@SQ     SN:ctg390       LN:8189
@SQ     SN:ctg391       LN:16816
@SQ     SN:ctg392       LN:7710
@SQ     SN:ctg393       LN:16699
@SQ     SN:ctg394       LN:7956
@SQ     SN:ctg395       LN:7804
@SQ     SN:ctg396       LN:7967
@SQ     SN:ctg397       LN:8448
@SQ     SN:ctg398       LN:7919
@SQ     SN:ctg399       LN:7834
@SQ     SN:ctg400       LN:7885
@SQ     SN:ctg401       LN:6657
@SQ     SN:ctg402       LN:7536
@SQ     SN:ctg403       LN:18467
@SQ     SN:ctg404       LN:7940
@SQ     SN:ctg405       LN:7955
@SQ     SN:ctg406       LN:7844
@SQ     SN:ctg407       LN:7957
@SQ     SN:ctg408       LN:7367
@SQ     SN:ctg409       LN:7185
@SQ     SN:ctg410       LN:7508
@SQ     SN:ctg411       LN:7739
@SQ     SN:ctg413       LN:6750
@SQ     SN:ctg414       LN:7012
@SQ     SN:ctg415       LN:7157
@SQ     SN:ctg416       LN:7236
@SQ     SN:ctg417       LN:7238
@SQ     SN:ctg418       LN:6973
@SQ     SN:ctg419       LN:9382
@SQ     SN:ctg420       LN:7086
@SQ     SN:ctg421       LN:7484
@SQ     SN:ctg422       LN:7297
@SQ     SN:ctg423       LN:7183
@SQ     SN:ctg424       LN:7058
@SQ     SN:ctg425       LN:6865
@SQ     SN:ctg426       LN:7122
@SQ     SN:ctg427       LN:7142
@SQ     SN:ctg428       LN:25054
@SQ     SN:ctg429       LN:6261
@SQ     SN:ctg430       LN:7110
@SQ     SN:ctg431       LN:7091
@SQ     SN:ctg432       LN:7162
@SQ     SN:ctg433       LN:7686
@SQ     SN:ctg434       LN:6989
@SQ     SN:ctg435       LN:6553
@SQ     SN:ctg436       LN:6826
@SQ     SN:ctg437       LN:6903
@SQ     SN:ctg438       LN:6970
@SQ     SN:ctg439       LN:7241
@SQ     SN:ctg440       LN:7231
@SQ     SN:ctg441       LN:6726
@SQ     SN:ctg442       LN:6774
@SQ     SN:ctg443       LN:7344
@SQ     SN:ctg444       LN:6726
@SQ     SN:ctg445       LN:6593
@SQ     SN:ctg446       LN:7567
@SQ     SN:ctg447       LN:7019
@SQ     SN:ctg448       LN:27070
@SQ     SN:ctg449       LN:6303
@SQ     SN:ctg450       LN:6738
@SQ     SN:ctg451       LN:6714
@SQ     SN:ctg452       LN:6765
@SQ     SN:ctg453       LN:6942
@SQ     SN:ctg454       LN:6645
@SQ     SN:ctg455       LN:6435
@SQ     SN:ctg456       LN:5616
@SQ     SN:ctg457       LN:6524
@SQ     SN:ctg458       LN:6798
@SQ     SN:ctg459       LN:6577
@SQ     SN:ctg460       LN:6243
@SQ     SN:ctg461       LN:7002
@SQ     SN:ctg462       LN:11092
@SQ     SN:ctg463       LN:6515
@SQ     SN:ctg464       LN:6296
@SQ     SN:ctg465       LN:5998
@SQ     SN:ctg466       LN:5858
@SQ     SN:ctg467       LN:5860
@SQ     SN:ctg468       LN:6257
@SQ     SN:ctg469       LN:6027
@SQ     SN:ctg470       LN:5937
@SQ     SN:ctg471       LN:5591
@SQ     SN:ctg472       LN:6068
@SQ     SN:ctg473       LN:5955
@SQ     SN:ctg474       LN:5857
@SQ     SN:ctg475       LN:6222
@SQ     SN:ctg476       LN:6122
@SQ     SN:ctg477       LN:6037
@SQ     SN:ctg478       LN:6095
@SQ     SN:ctg479       LN:6181
@SQ     SN:ctg480       LN:6128
@SQ     SN:ctg481       LN:10630
@SQ     SN:ctg482       LN:6157
@SQ     SN:ctg483       LN:5744
@SQ     SN:ctg484       LN:6129
@SQ     SN:ctg485       LN:6133
@SQ     SN:ctg486       LN:6123
@SQ     SN:ctg487       LN:6017
@SQ     SN:ctg488       LN:5933
@SQ     SN:ctg489       LN:6191
@SQ     SN:ctg490       LN:6267
@SQ     SN:ctg491       LN:5993
@SQ     SN:ctg492       LN:6324
@SQ     SN:ctg493       LN:6343
@SQ     SN:ctg494       LN:5297
@SQ     SN:ctg495       LN:6525
@SQ     SN:ctg496       LN:6315
@SQ     SN:ctg497       LN:6021
@SQ     SN:ctg498       LN:6423
@SQ     SN:ctg499       LN:6109
@SQ     SN:ctg500       LN:5545
@SQ     SN:ctg501       LN:5970
@SQ     SN:ctg502       LN:5652
@SQ     SN:ctg503       LN:5790
@SQ     SN:ctg504       LN:5869
@SQ     SN:ctg505       LN:5342
@SQ     SN:ctg506       LN:17940
@SQ     SN:ctg507       LN:6301
@SQ     SN:ctg508       LN:5876
@SQ     SN:ctg509       LN:5813
@SQ     SN:ctg510       LN:6147
@SQ     SN:ctg511       LN:5354
@SQ     SN:ctg512       LN:5907
@SQ     SN:ctg513       LN:5766
@SQ     SN:ctg514       LN:4997
@SQ     SN:ctg515       LN:6630
@SQ     SN:ctg517       LN:5477
@SQ     SN:ctg518       LN:6571
@SQ     SN:ctg519       LN:5767
@SQ     SN:ctg520       LN:5233
@SQ     SN:ctg521       LN:5563
@SQ     SN:ctg522       LN:5405
@SQ     SN:ctg523       LN:5156
@SQ     SN:ctg524       LN:5175
@SQ     SN:ctg525       LN:5284
@SQ     SN:ctg526       LN:5351
@SQ     SN:ctg527       LN:5151
@SQ     SN:ctg528       LN:4894
@SQ     SN:ctg529       LN:15085
@SQ     SN:ctg531       LN:5176
@SQ     SN:ctg532       LN:4993
@SQ     SN:ctg533       LN:5118
@SQ     SN:ctg534       LN:5211
@SQ     SN:ctg535       LN:5153
@SQ     SN:ctg536       LN:5139
@SQ     SN:ctg537       LN:5085
@SQ     SN:ctg538       LN:5055
@SQ     SN:ctg539       LN:15905
@SQ     SN:ctg540       LN:5122
@SQ     SN:ctg541       LN:4785
@SQ     SN:ctg542       LN:4746
@SQ     SN:ctg543       LN:5056
@SQ     SN:ctg544       LN:5085
@SQ     SN:ctg545       LN:4945
@SQ     SN:ctg546       LN:4914
@SQ     SN:ctg547       LN:4665
@SQ     SN:ctg548       LN:5025
@SQ     SN:ctg549       LN:5035
@SQ     SN:ctg550       LN:5145
@SQ     SN:ctg551       LN:5138
@SQ     SN:ctg552       LN:4860
@SQ     SN:ctg553       LN:10685
@SQ     SN:ctg554       LN:4962
@SQ     SN:ctg556       LN:4785
@SQ     SN:ctg557       LN:5063
@SQ     SN:ctg558       LN:4833
@SQ     SN:ctg559       LN:5100
@SQ     SN:ctg560       LN:4974
@SQ     SN:ctg561       LN:5034
@SQ     SN:ctg562       LN:4903
@SQ     SN:ctg563       LN:5137
@SQ     SN:ctg564       LN:5130
@SQ     SN:ctg565       LN:5002
@SQ     SN:ctg566       LN:5151
@SQ     SN:ctg567       LN:4753
@SQ     SN:ctg568       LN:4973
@SQ     SN:ctg569       LN:4867
@SQ     SN:ctg570       LN:4831
@SQ     SN:ctg571       LN:4814
@SQ     SN:ctg572       LN:5034
@SQ     SN:ctg573       LN:4922
@SQ     SN:ctg574       LN:19104
@SQ     SN:ctg575       LN:7985
@SQ     SN:ctg576       LN:14067
@SQ     SN:ctg577       LN:10686
@SQ     SN:ctg578       LN:8737
@SQ     SN:ctg579       LN:8545
@SQ     SN:ctg580       LN:18742
@SQ     SN:ctg581       LN:8833
@SQ     SN:ctg582       LN:8484
@SQ     SN:ctg583       LN:14973
@SQ     SN:ctg584       LN:5320
@SQ     SN:ctg585       LN:11416
@SQ     SN:ctg586       LN:7732

**Comment by valeriuo** [comment]
If these are all the `@SQ` lines, it seems that one or more of the reads fall outside of the header reference. The maximum length of any reference sequence (as taken from the previous message) is **35803611**, while the read that triggered the error starts at **589897413**.

Thus it might be more of a problem with [ngm](https://github.com/Cibiv/NextGenMap), the tool that generated the alignment. On our side, we can try to make the error message slightly more verbose, to understand more about reads that cause such issues.

There are a few more steps you could perform, so that we get a clearer picture of what is happening.

Get the minimum and maximum starting coordinate of the reads with the command:
`samtools view HK1.paired.sort.bam | awk 'NR==1 {min=$4; max=$4} {max = max < $4 ? $4 : max; min = min > $4 ? $4 : min } END {print min, max}'`

Get the maximum LN value with the command:
`samtools view HK1.paired.sort.bam -H | grep "^@SQ" | awk 'BEGIN {max=0} {split($3,ln,":"); max = max < ln[2] ? ln[2] : max} END {print max}`

**Comment by jhcaddisfly** [comment]
Thank you for your answer. 
The minimum and the starting coordinates of the reads are: 
0 589897414

The maximum LN value is:
35803611

**Comment by jkbonfield** [comment]
Am I reading this correct?  It sounds like the longest chromosome in the SQ headers is ~36Mb while the alignments are out to ~590Mb.  This would appear to indicate the header does not match the data, in which case the indexing will not work (nor will much else for that matter).  Has there been some header manipulation on this file already?  I'd find it surprising if an aligner output data in this form.

Could we see the actual SAM line that corresponds to 589897414 and the corresponding SQ line from the header for the reference is matches against.

**Comment by jhcaddisfly** [comment]
Thanks, I opened an issue at github for ngm.

**Comment by jhcaddisfly** [comment]
Hi,
again many thanks for your help and suggestions. I guess the problem was caused by ngm. I used bwa mem to map the reads and all the follwing samtool steps worked nicely. For this reason I will close the issue.

**Comment by valeriuo** [comment]
Good to know. Anyway, we added a few more details to error reports of this kind, to spare the user from doing the debugging. From the next release, the error message will look something like:
```
[E::hts_idx_check_range] Region 589897414..589897564 cannot be stored in a bai index. Try using a csi index with min_shift = 14, n_lvls >= 6
[E::sam_index] Read 'A00551:69:HGV7VDSXX:2:2568:6262:1094' with ref_name='ctg1', ref_length=11755914, flags=161, pos=589897414 cannot be indexed
samtools index: failed to create index for "HK1.paired.sort.bam": Result too large
```

**Comment by jhcaddisfly** [comment]
This is really great!
