### ISSUE TITLE
Samtools view -s error: Incorrect sampling argument

### ISSUE THREAD

**Issue by HasseB-MAN** [samtools/samtools#1123]
Hi, 
I am tring to subsample a series of BAM files using samtools 1.9. 
I'm using `samtools view -s ${PROPORTION} -b ${BAMFILE} > out.bam`.

However, this gives me the error "Incorrect sampling argument". The arguments I'm using are all of the format 0.333054077. I've looked in the samtools manual to see if there is something wrong with this argument format, but that did not specify any restrictions. I've tried to shorten the argument to three decimal places, but that did not help.

I would greatly appreciate any input on this.

**Comment by HasseB-MAN** [comment]
This has now been resolved. It turned out the problem was that samtools view -s requires a floating point number, but these are not supported by bash. Therefore, whatever was actually being passed to samtools was not a floating point number.

**Comment by tseemann** [comment]
@HasseB-MAN a portable way to do floating point maths in shell scripts is to use `bc` which comes with most Unix.

```
#!/usr/bin/env bash
PI=$(bc -l <<<"22/7")
echo $PI
3.14285714285714285714
```
or to choose decimal points:
```
echo $(bc -l <<<"scale=3;22/7")
3.142
```
