### ISSUE TITLE
Remove misc/varfilter.py?

### ISSUE THREAD

**Issue by jmarshall** [samtools/samtools#1125]
_misc/varfilter.py_ is written in Python 2, which will soon be a problem (cf [RH #1738176](https://bugzilla.redhat.com/show_bug.cgi?id=1738176)). It's probably trivial to convert it to Python 3 (e.g., there is only one `print` statement to add parentheses to), but there are other problems.

It appears that this script takes `pileup -c` (consensus) output as input, which was removed in samtools 0.1.17 in 2011. The semi-equivalent `bcftools/misc/vcftools.pl varfilter` appears to (now) take a VCF file instead.

Presumably people haven't been using _varfilter.py_ much since the pileup command disappeared! So it could be removed from the samtools distribution, or at least deprecated: add an always-printed message for a release or two:

> varfilter.py will be removed soon -- post to samtools-help if you wish for a reprieve

**Comment by jkbonfield** [comment]
Gets my vote.  Thanks for the suggestion.

**Comment by jkbonfield** [comment]
Also, I really dislike how distributions add rubbish dependencies like this.  It's a miscellaneous script which is not required for general usage.  I guess technically one component requires it, but they need a middle group of "recommended".  The core program functionality does not have this dependency.

It explains how we often get the kitchen-sink-syndrome of dependencies when installing innocuous packages.  As a user I'd like the choice between "required" and "works best with".  Grrr.

**Comment by jmarshall** [comment]
Yup. Dpkg has recommends (and I see Debian's [samtools](https://packages.debian.org/buster/samtools) uses it) but rpm sadly does not (or didn't back when I was packaging stuff in earnest).

Also CC @aylwyn in the unlikely event he's updated this script over the years.

**Comment by aylwyn** [comment]
Fine by me; afraid I have not updated. It was essentially a conversion of Heng's .pl script, adding the (essential) option of outputting nonvariant sites passing filters, and also being easier to work with since not in cryptic perl :)
