### ISSUE TITLE
Massive difference between mpileup and depth

### ISSUE THREAD

**Issue by migrau** [samtools/samtools#1129]
Hi, 
If I run `samtools depth bam`, the depth is ~8000x but if I try with `samtools mpileup -f ref bam`, it's ~1000x. However with `samtools mpileup -A -f ref bam`, it's 8000x again. I understand then that the difference of ~7000 reads in each position is exclusively because the orphan reads? or it's something more like duplicates/secondary etc? A small difference would be normal but that's huge...

These are paired illumina reads 150bp.
Thanks!

**Comment by tseemann** [comment]
Those commands use different default filter options:

depth
```
   -d/-m <int>         maximum coverage depth [8000]. If 0, depth is set to the maximum
                       integer value, effectively removing any depth limit.
   -q <int>            base quality threshold [0]
   -Q <int>            mapping quality threshold [0]
```

mpileup
```
  -A, --count-orphans     do not discard anomalous read pairs
  -d, --max-depth INT     max per-file depth; avoids excessive memory usage [8000]
  -E, --redo-BAQ          recalculate BAQ on the fly, ignore existing BQs
  -f, --fasta-ref FILE    faidx indexed reference sequence file
  -G, --exclude-RG FILE   exclude read groups listed in FILE
  -q, --min-MQ INT        skip alignments with mapQ smaller than INT [0]
  -Q, --min-BQ INT        skip bases with baseQ/BAQ smaller than INT [13]
  --rf, --incl-flags STR|INT  required flags: skip reads with mask bits unset []
  --ff, --excl-flags STR|INT  filter flags: skip reads with mask bits set
                                            [UNMAP,SECONDARY,QCFAIL,DUP]
  -x, --ignore-overlaps   disable read-pair overlap detection
```

**Comment by migrau** [comment]
Thanks, Torsten. 
With `samtools view -f 0x0002 -b bam | samtools depth -d 0 -q 13 - > view.cov`
The output is pretty similar to `samtools mpileup -f ref bam`, ~1000x

With `samtools depth -d 0 -q 13 bam` or `samtools mpileup -d 0 -A -f fa bam`, depth is ~20k.

I can identify some reads with `-f 0x0008` (unmapped mate) but the difference is still really big. I have checked the not primary/quality/duplicate and that's not the problem. I'm wondering what `0x0002` (mapped in a proper pair) means exactly. The pair overlaps?

**Comment by tseemann** [comment]
Proper pair is up to the aligner tool.

BWA MEM and Bowtie2 will require the pairs to be orientated correctly and be within a certain distance from each other. The default for BWA is fine, but bowtie2 is too low in my experience.

**Comment by migrau** [comment]
bam is from bwa, (`bwa mem ref R1.fq R2.fq`). 
Should I discard them (`samtools mpileup` without `-A`) if I call variants with bcftools (`bcftools mpileup -Ou ... | bcftools call -mv -Oz ...`)? 
Could it happen because some sequencing or library prep aspect?

**Comment by Cynthy21** [comment]
hello,migrau
I have found a similar problem to you, that  'samtools mpileup without -A' will make many reads lost even these reads have no primary/quality/duplicate problems. And, I used data that I made up,  to test the tool, It showed the same results that some reads lost. I think 'samtools mpileup' may treat these reads as anomalous reads，though I don't know the exact algorithm.

**Comment by dpryan79** [comment]
FYI, `samtools depth` and `samtools mpileup` literally use the same code, the only difference is the default in what's filtered (and maybe how overlapping reads are handled, I don't recall what `depth` does with them).

**Comment by daviesrob** [comment]
The default behaviour in mpileup is to reject reads where the `PAIRED` flag is set and the `PROPER_PAIR` flag is not set (done [here](https://github.com/samtools/samtools/blob/a6a160bb/bam_plcmd.c#L369)).  The `-A` flag disables this filter.  There is no equivalent code in the `depth` command so in this respect it always behaves like `samtools mpileup -A`.

Setting `PAIRED` and `PROPER_PAIR` is up to the aligner; `mpileup` just uses the results.  You need to check what your aligner is doing to find out why so many reads are not being marked as a `PROPER_PAIR`.

Note that the default options for `samtools mpileup` were more aimed at variant calling (functionality now moved to `bcftools mpileup`) than generating pileup output.  Unfortunately we're somewhat stuck with them for backwards-compatibility reasons.  When generating pileup, consider using `-A`, `-Q 0`, `-x` and possibly `-B`.
