### ISSUE TITLE
samtools merge S3 cram files requires -X flag

### ISSUE THREAD

**Issue by uitde007** [samtools/samtools#1132]
#### Is your feature request related to a problem? Please specify.

`samtools merge -R $region - s3://bucket/sample1.bam s3://bucket/sample2.bam` # ok

`samtools merge -R $region - s3://bucket/sample1.cram s3://bucket/sample2.cram --reference ref.fa` # Failed to load index.

#978 gives an option -X flag workaround:

`samtools merge -R $region - -X s3://bucket/sample1.cram s3://bucket/sample2.cram sample1.cram.crai sample2.cram.crai --reference ref.fa` # ok

#### Describe the solution you would like.
I would prefer a solution without this -X flag, similar to the syntax for BAM files.

**Comment by uitde007** [comment]
What syntax should I use for samtools merge -b cramfile.list -X to work?

**Comment by valeriuo** [comment]
What version of samtools/htslib are you using?
Does your htslib include https://github.com/samtools/htslib/pull/870?
What are the error messages in your output?

Please fill in the issue template.

**Comment by uitde007** [comment]
samtools 1.9-180-gf9e1caf
Using htslib 1.9-401-gd59c364-dirty

> [bam_merge_core2] failed to load index for s3://bucket/sample1.cram.  Random alignment retrieval only works for indexed BAM or CRAM files.

Where can I find the issue template?

**Comment by uitde007** [comment]
samtools/htslib#870 Does'nt check for .crai index?

**Comment by valeriuo** [comment]
You can try the fix, until it is merged, by running the following commands in your HTSlib folder:
```
git checkout -b valeriuo-crai_index develop
git pull https://github.com/valeriuo/htslib.git crai_index
make clean; make && make install
```
Then rebuild your samtools binary with this version of HTSlib.
