### ISSUE TITLE
 samtools mepielup extact the reads which pass one point

### ISSUE THREAD

**Issue by LiQingsolab** [samtools/samtools#1139]
#### Are you using the latest version of [samtools](https://github.com/samtools/samtools/releases/latest) and [HTSlib](https://github.com/samtools/htslib/releases/latest)? If not, please specify.
(run `samtools --version`)

 #### Please describe your environment.
- OS (run `uname -sr` on Linux/Mac OS or ` wmic os get Caption, Version` on Windows)
- machine architecture (run `uname -m` on Linux/Mac OS or ` wmic os get OSArchitecture` on Windows)
- compiler (run `gcc --version` or `clang --version`)

**Comment by LiQingsolab** [comment]
Hi!
I used samtools mepielup extact the reads which pass one point, but i found lost of reads which are in the point were not  be printed, the cmdline i used was:

/biocluster/data/bioexec/software/samtools-1.6/samtools mpileup -O --output-QNAME -d 1000000 -f $REF -q 0 -Q 0 -r 1:115258744-115258744  test_header.bam -o 2R14_115258744.mpileup -A -x

Looking forward to receipt any answer ~

**Comment by jkbonfield** [comment]
It looks like you have the correct options to keep as much as possible: base quality (-Q), mapping quality (-q), anomalous pairs (-A), depth (-d).  I think -B (no BAQ) isn't likely to make much difference once you've applied -q 0 and -Q 0, but it's worth a shot.  I cannot think why else data would be lost.

Presumably you know which reads have been lost.  (If not a `samtools view  test_header.bam 1:115258744-115258744` would report all the overlapping ones.)  How are you calculating that they have been lost?  If it is checking read names, then note these can be duplicated so the unique set of names will probably be fewer than the actual coverage.

Also note that when doing mpileup on a region you won't see all the '^<mapping_qual>' chars in the sequence column as this is only shown for reads that start at that coordinate, and not the ones that started before the region queried.

**Comment by LiQingsolab** [comment]
Hi~

Thanks for your answer!

I printed the lost reads we thought should be extract in our aim region. This reads started before our aim region, so, though this reads passed the aim region, these won’t be extracted!

**Comment by jkbonfield** [comment]
A read starting before the target region of 1:115258744-115258744 should still be included in the mpileup provided it doesn't also finish prior to that region although they won't be visible with the `^<qual><base>` syntax.  Obviously data that is entirely before the region will not be present.

Is that would you are seeing?

**Comment by LiQingsolab** [comment]
hi，
This sentence: “Also note that when doing mpileup on a region you won't see all the '^<mapping_qual>' chars in the sequence column as this is only shown for reads that start at that coordinate, and not the ones that started before the region queried.” Is that means that The mpileup result only show the reads that started before the aim region?

**Comment by LiQingsolab** [comment]
hi，
This sentence: “Also note that when doing mpileup on a region you won't see all the '^<mapping_qual>' chars in the sequence column as this is only shown for reads that start at that coordinate, and not the ones that started before the region queried.” Is that means that the mpileup result only show the reads that started after the aim region? If one read which started at 1:115258743 but passed  115258744, does this read can be extracted ?

**Comment by LiQingsolab** [comment]
For example, this is a lost  read which  can be extracted by using  1:115258743-115258744, but can't be extracted by 1:115258744-115258744. In fact, this read passed this region: 115258744.
### A00601:160:HTCHVDSXX:1:1564:18096:23970#GGTTTCGTMC220F|1|115258777|46#r2#115258710#115258755#46 147     1       115258732       60      46M     =       115258732       -46     CTTTTCCCAACACCACCTGCTCCAACCACCACCAGTTTGTACTCAG ..........

**Comment by LiQingsolab** [comment]
For example, this is a lost read which can be extracted by using 1:115258743-115258744, but can't be extracted by 1:115258744-115258744. In fact, this read passed this region: 115258744.

A00601:160:HTCHVDSXX:1:1564:19569:9862#GCAGCCACMC217F|1|115258777|46#r2#115258710#115258755#46  147     1       115258732       60      46M     =       115258732       -46     CTTTTCCCAACACCACCTGCTCCAACCACCACCAG.........

**Comment by jkbonfield** [comment]
That read starts at  115258732 and ends at 115258777 (due to 46M match length).  Thus it does overlap the query region and it should be reported by mpileup.

How are you determining that this read was not included in the mpileup output?  Is the name missing in the qnames column?

**Comment by LiQingsolab** [comment]
Hi, 

I think I know  why I couldn't find these lost reads, because these reads are duplicates!
Thanks very much for your answer !

**Comment by LiQingsolab** [comment]
And on more question, if i want to use samtools to extract half/85% data from original bam file, does one line which contains read1 and read2 will be extracted all ?  Or sometime, samtools will just extracts read1 or read2?

**Comment by jkbonfield** [comment]
If you do a sub-region query it'll extract reads overlapping that sub-region.  This means sometimes you get one end of a read pair without the other end.

However if you're using `samtools view -s0.5` to subsample to 50% depth then you'll either get all reads on that template (usually 2) or no reads on that  template.  It won't give partial template data.

**Comment by LiQingsolab** [comment]
Ok！Thanks very much for your reply and clear answer!
