### ISSUE TITLE
cram to bam conversion

### ISSUE THREAD

**Issue by Irfanwustl** [samtools/samtools#1141]
I am trying to convert from cram file to bam file and getting this error: 

> [E::cram_get_ref] Failed to populate reference for id 556

> [E::cram_get_ref] Failed to populate reference for id 571

> [E::cram_get_ref] Failed to populate reference for id 575

> ..............................................................................................

My command is: 

> samtools view -b -T ref_sequence.fa -o $sample.bam -@8 $sample.cram

A similar problem is reported [here](https://github.com/samtools/htslib/issues/662). But I am reporting again because
it seems like a multithreading issue. When I have removed -@8 from the command, 
it is solved.
Samtools version:  1.7
Linux 4.15.0-66-generic
gcc : 7.4.0

**Comment by daviesrob** [comment]
Quite a few CRAM multithreading bugs have been fixed since version 1.7.  Could you try building samtools and htslib from their `develop` branches and see if they work correctly, please?

**Comment by tseemann** [comment]
Would 1.9 have the fixes?

**Comment by daviesrob** [comment]
I think it should have.

**Comment by valeriuo** [comment]
samtools [1.10](https://github.com/samtools/samtools/releases/tag/1.10) has been released recently, with the accompanying HTSlib [1.10.2](https://github.com/samtools/htslib/releases/tag/1.10.2). 

Give them a try with your command please, and reopen the issue if persistent.
