### ISSUE TITLE
Library level stats from Markdup

### ISSUE THREAD

**Issue by PedalheadPHX** [samtools/samtools#1143]
#### Is your feature request related to a problem? Please specify.

Not a problem but a limitation of the current stats summary when a given BAM file contains multiple libraries.

#### Describe the solution you would like.

Assuming duplicates are marked by library (RG-LB) within a given BAM, and optical duplicates are marked by the platform unit (RG-PU) then having at least the duplicate stats for each library defined in the BAM versus the sample or even multi-sample BAM would improve quality control processes.

Requested solution: `samtools markdup -f markdup.stats in.bam out.bam` produces a file with one column or row for each library within "in.bam".  I acknowledge the optical duplicate stats are then left in a similar issue where the numbers might differ by RG-PU but unlike different libraries that might have very different duplicate levels I'd expect the same library sequenced on multiple RG-PU will have very similar optical duplicate numbers so averaging the level observed by library seems reasonable.

In a perfect world the stats would be output in JSON with levels for the total BAM, each RG-SM (might be multiple samples in a BAM), and each RG-LB (might be multiple libraries).

**Comment by whitwham** [comment]
It would take some reworking of the stats but that might not be a bad thing.

As for JSON, how about posting an example of the kind of output you would like to see?
