### ISSUE TITLE
Different read count and base quality between samtools version (mpileup)

### ISSUE THREAD

**Issue by rkendar** [samtools/samtools#1146]
Hi Samtools Team,

Currently I am comparing different version of `samtools mpileup` (0.1.19 vs 1.8). I noticed that they give different result in read count and base quality in some regions, as follow:

Same command for both version:
`samtools mpileup -q 1 -f genome.fasta -r 1  in.bam | gzip > out.mpileup.gz`
```
samtools 0.1.19
1       10017   C       1       ^@,     3
1       10018   C       1       ,       3
1       10019   T       1       ,       3
1       10020   A       3       ,.^$.   345
1       10021   A       3       ,..     3>=
1       10022   C       3       ,..     3A@
1       10023   C       3       ,..     3A@
1       10024   C       3       ,..     3BA
1       10025   T       3       ,.G     3D>
1       10026   A       3       ,C.     3DB
```
```
samtools 1.8 
1       10017   C       1       ^@,     3
1       10018   C       1       ,       3
1       10019   T       1       ,       /
1       10020   A       2       ,^$.    F5
1       10021   A       2       ,.      P=
1       10022   C       2       ,.      S@
1       10023   C       2       ,.      S@
1       10024   C       2       ,.      TA
1       10025   T       2       ,G      V>
1       10026   A       2       C.      =B
```
I have tried another command (below), but the result is the same without the `--ff` flag. 
`samtools mpileup -q 1 -f genome.fasta -r 1 --ff UNMAP,SECONDARY,QCFAIL,DUP in.bam | gzip > out.mpileup.gz 
`

So my questions are:
1. Why they have different read count and base quality?
2. For example `1       10020   A       3       ,.^$.   345` , it has 5 reads ( ,.^$.) supporting this position but why it only give 3 base quality (345)? Please correct me if I misinterpreted this example.
3. Will this different affect in more downstream analysis (exp. variant calling)?

Best regards,
Raden

**Comment by tseemann** [comment]
1. not sure. the code has changed a lot over the 7 years (?) since 0.1.19. maybe you need to also add
`  -B, --no-BAQ            disable BAQ (per-Base Alignment Quality)` for 1.8

2. `^` and `$` are not bases. they have special meaning - "a read starts (ends) here"

3. only if you use the mpileup result for calling variants with samtools itself. most other variant callers use the BAM directly. I believe `bcftools mpileup` is the recommended way to do it now

Notes:
* 1.8 is not the current version, best to compare to 1.9 or upcoming 1.10
* calling your output file `out.bam`is confusing - do you mean `out.mpileup.gz`?

**Comment by rkendar** [comment]
Hi Torsten,

Thank you so much for your reply and suggestion! I have edited the typo` out.mpileup.gz`  :) 
1. Does it mean the samtools 1.8 is automatically enabled BAQ? I saw in samtools 0.1.19 manual http://www.htslib.org/doc/samtools-0.1.19.html it has the same option, so I assume both samtools will do BAQ if i didn't specified `-B`
2. Thank you for pointing this out!
3. I see, thank you.

But, I still don't really understand why different version can give me different read count. I check this region in IGV:

![image](https://user-images.githubusercontent.com/38774176/69862160-cc68ac00-12d4-11ea-946a-af2700c61a73.png)

I exclude all MAPQ 0 using `-q 1`, so I expect to get 3 read counts. But the result is different between samtools version:
```
samtools 0.1.19 (has depth of 3)
1       10020   A       3       ,.^$.   345

samtools 1.8 (has depth of 2)
1       10020   A       2       ,^$.    F5
```
Looks like samtools 1.8 have other automatic filtering factor that more stringent than the older one. Is that true? If yes, do you know what factor is that?

**Comment by valeriuo** [comment]
**samtools 1.8** discards overlaps by default. Meaning that from two paired reads that cover a position, it will select only one, by [increasing](https://github.com/samtools/htslib/blob/3f140ad0bd64beeed2884b818e7b7a08ef06721d/sam.c#L4321-L4323) the base quality of the selected read and setting the other quality value to **0**.

In you case, most likely, the first two reads are paired, and that particular base has quality "3" (18 phred encoded to 51) on the first read, and quality "4" (19 phred encoded to 52). The algorithm selects one read and it boosts the base quality to "F" (18+19 phred encoded to 70).

You can disable this behaviour by using `-x` option in your mpileup command.

**Comment by tseemann** [comment]
Thanks @valeriuo - i keep forgetting about the `-x` !

**Comment by rkendar** [comment]
Thanks @valeriuo now I understand! 

So can I safely say if I specify the `-x` option, the result between two version will be the same? I briefly inspect some lines and it is the same, but the md5sum is different. I did notice some `blank` space in samtools 1.8 are annotated `*` in 0.1.19. Is that all the difference?

**Comment by valeriuo** [comment]
> So can I safely say if I specify the -x option, the result between two version will be the same?

Most likely. Usually, consideration is given to preserving the compatibility of output, and when that is not possible, orthogonal command options are added to allow the user to switch between variants, such as `-x`.

Anyway, why are you comparing the output of these two versions? 1.8 isn't even the last samtools [release](https://github.com/samtools/samtools/releases/tag/1.9), and the currently recommended way of doing mpileup/variant calling is using [bcftools](https://samtools.github.io/bcftools/howtos/variant-calling.html).

> Samtools mpileup can still produce VCF and BCF output, but this feature is deprecated and will be removed in a future release. Please use bcftools mpileup for this instead.

**Comment by rkendar** [comment]
Well noted about the `-x` option @valeriuo !

> Anyway, why are you comparing the output of these two versions?

The reason is I am doing CNV calling using [sequenza](https://sequenza-utils.readthedocs.io/en/latest/api.html) and comparing the v2.1.2 and v3.0.0. This tool requires `samtools  mpileup` as dependency to obtain the read counts/depth to calculate the zygosity. 

In our previous pipeline we used `samtools 0.1.19 + sequenza v2.1.2`, now we want to updated to `sequenza v3.0.0`. But, the newer sequenza required newer version of samtools (I am using v1.8 because it is the one that available in my cluster).

Since the different samtools version give different read counts, it affects the result of CNV calling. Thus, I want to understand why the read count is different.

It maybe a very basic question, but what is the difference between `samtools mpileup` and `bcftools mpileup` (instead of the deprecated option for VCF and BCL)? Will the `bcftools mpileup` give a better result? I cannot find any documentation/forum talk about this.
