### ISSUE TITLE
unmapped read from bam files

### ISSUE THREAD

**Issue by yogeshgupt** [samtools/samtools#1153]
Hi,

I need to extract unmapped read from pair end bam files. could you help me to understand  what is the difference between f4 and f12 flag.

samtools view -b -f 4 216_5W_Ca1.bam > unmap_216_5W_Ca1.bam

samtools view -b -f 12 216_5W_Ca1.bam > unmap_216_5W_Ca1.bam

thanks

**Comment by jkbonfield** [comment]
See the useful `samtools flags` command which gives you a summary of the values and what they mean:

```
About: Convert between textual and numeric flag representation
Usage: samtools flags INT|STR[,...]

Flags:
	0x1	PAIRED        .. paired-end (or multiple-segment) sequencing technology
	0x2	PROPER_PAIR   .. each segment properly aligned according to the aligner
	0x4	UNMAP         .. segment unmapped
	0x8	MUNMAP        .. next segment in the template unmapped
	0x10	REVERSE       .. SEQ is reverse complemented
	0x20	MREVERSE      .. SEQ of the next segment in the template is reversed
	0x40	READ1         .. the first segment in the template
	0x80	READ2         .. the last segment in the template
	0x100	SECONDARY     .. secondary alignment
	0x200	QCFAIL        .. not passing quality controls
	0x400	DUP           .. PCR or optical duplicate
	0x800	SUPPLEMENTARY .. supplementary alignment
```

More information on the meaning of these fields can be found in the SAM format specification:  http://samtools.github.io/hts-specs/

**Comment by yogeshgupt** [comment]
Hi James,

I can't able to find anything f4 and f12 in the samtools flags. 

there is only two related to unmapped how these are related with f4 and f12?

       0x4	UNMAP         .. segment unmapped
	0x8	MUNMAP        .. next segment in the template unmapped

could you please help me to understand this?

**Comment by jkbonfield** [comment]
They are bit flags, so 12 is just 4+8.

As the -f option is "-f INT   only include reads with all  of the FLAGs in INT present [0]" that means you need both 4 and 8 to be present.

**Comment by valeriuo** [comment]
You can also find more details in the official [SAM specs](https://github.com/samtools/hts-specs/blob/master/SAMv1.pdf), section 1.4.
