### ISSUE TITLE
Test "test_large_positions" fails when compiled without ncurses support

### ISSUE THREAD

**Issue by cljacobs** [samtools/samtools#1162]
When samtools is configured with the `--without-ncurses` (and similar) flags, it fails a text alignment viewer test; specifically the "test_large_positions" test. I'm not sure this test is even necessary in this configuration, given that the help docs for `samtools tview` explicitly spell out that it is based on the ncurses library.

#### Are you using the latest version of [samtools](https://github.com/samtools/samtools/releases/latest) and [HTSlib](https://github.com/samtools/htslib/releases/latest)? If not, please specify.
Yes. The error occurs during `make check` for the latest version.

 #### Please describe your environment.
- OS: Linux 3.10.0-1062.7.1.el7.x86_64
- machine architecture: x86_64
- compiler: gcc (GCC) 7.2.0

#### Please specify the steps taken to generate the issue, the command you are running and the relevant output.
Here are the steps I used to compile. You'll have to set the variable `INSTALL_BASE` to the desired install base directory (e.g. `/usr/local`) if you want to rerun as is. I already had an installation of htslib-1.10.2 in the desired location, so I used that instead of the bundled version.

```
./configure --build='x86_64-redhat-linux-gnu' --without-curses --without-ncurses --without-ncursesw --with-htslib="${INSTALL_BASE}/samtools-1.10.0" --prefix="${INSTALL_BASE}/samtools-1.10.0" CPPFLAGS="-I${INSTALL_BASE}/samtools-1.10.0/include" LDFLAGS="-Wl,-rpath,${INSTALL_BASE}/samtools-1.10.0/lib -L${INSTALL_BASE}/samtools-1.10.0/lib"
make 2>&1 | tee make.log
PATH="${INSTALL_BASE}/samtools-1.10.0/bin${PATH:+:${PATH}}" make --keep-going check 2>&1 | tee check.log
```

The error can be seen here (snippet from check.log, attached):
```
test_large_positions:
         /broad/rosenlab_archive/Software/tmp/samtools-1.10/samtools tview -d T -p CHROMOSOME_I:10000000000 /broad/hptmp/bpFK0_Re_K/longref.sam.gz
 
         The outputs stdout differ:
                 /broad/rosenlab_archive/Software/tmp/samtools-1.10/test/large_pos/tview.expected.out
                 /broad/rosenlab_archive/Software/tmp/samtools-1.10/test/large_pos/tview.expected.out.new
 .. failed ...
```

The full `make check` log:
[check.log](https://github.com/samtools/samtools/files/4027237/check.log)

The files that differ can be seen here:
[tview.expected.out.txt](https://github.com/samtools/samtools/files/4027233/tview.expected.out.txt)
[tview.expected.out.new.txt](https://github.com/samtools/samtools/files/4027234/tview.expected.out.new.txt)

**Comment by daviesrob** [comment]
Thanks for the very comprehensive bug report.

I suspect this isn't due to disabling curses, but instead due tview producing a wider output than the test expected.  Does `COLUMNS=80 make test` work correctly?

**Comment by cljacobs** [comment]
Oh, yes that works. Thanks. You can tell how much I use the tview command, since I just assumed that the extra characters in the test-generated version were a mistake in the interpretation of the command inputs rather than an output viewing-window-size thing.

Still seems odd that this test succeeds in previous versions without the need to the columns variable to be set explicitly (I went back and tested on the same machine with the same configure and build commands), but I'm happy enough just to have at least learned what tview is actually used for.
