### ISSUE TITLE
depth still reports zero coverage positions

### ISSUE THREAD

**Issue by Asutu** [samtools/samtools#1166]
#### Are you using the latest version of [samtools](https://github.com/samtools/samtools/releases/latest) and [HTSlib](https://github.com/samtools/htslib/releases/latest)? If not, please specify.

samtools 1.9
Using htslib 1.9
Copyright (C) 2018 Genome Research Ltd.

 #### Please describe your environment.

Both in `Darwin 18.7.0 x86_64` and `Linux 3.10.0-693.11.6.el7.x86_64`

#### Please specify the steps taken to generate the issue, the command you are running and the relevant output.

```
$ samtools depth toy.bam | awk '$3 == 0'
c6268220_99999_s6268220	16455	0
c6268220_99999_s6268220	16456	0
```

There's a large region between 50-6000 bp without mapped reads that is, correctly, not reported. However I wouldn't expect to see the two cases above. For the toy example showed this is negligible, but  in a working BAM file I do have thousands of zero coverage bases in the output.

My understanding was that without the `-a` or `-aa` flags, zero coverage bases were not reported in the output.

Thanks,
Pedro

PS: tried to attach the example BAM file but GitHub said it doesn't support that file type.

**Comment by daviesrob** [comment]
Thanks for the report.  You should be able to attach your bam file either by putting it in a zip file, or possibly by renaming it to `.bam.gz`.

**Comment by Asutu** [comment]
Thanks @daviesrob.

Here's the toy example attached.
[toy.bam.zip](https://github.com/samtools/samtools/files/4046766/toy.bam.zip)

**Comment by daviesrob** [comment]
What's happening here is that your reads all have a deletion at this position:

```
 16441     16451     16461     16471              
NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN
AGTGAAATTSGAGGTKKTATTGTGTAAAGCTATAAGCTATAAGATAAATT
agtgaaattgGAGGT**TATTGTGTAAAGCTATAAGCTATAAGATAAATT
AGTGAAATTGGAGGT**TATTGTGtaaagctataagctataagataaatt
AGTGAAATTGGAGGT**TATTGTGTA        AGCTATAAGATAAATT
agtgaaattggaggt**tattgcgtaaa                TAAATT
agtgaaattggaggt**tattgtgtaaagc              taaatt
AGTGAAATTGGAGGT**TATTGTGTAAAGCTATAAG              
AGTGAAATTCGAGGT**TATTGTGTAAAGCTATAAG              
agtgaaattcgaggt**tattgtgtaaagctataagcta           
AGTGAAATTGGAGGT**TATTGTGTAAAGCTATAAGCTATAAGATAAATT
AGTGAAATTGGAGGT**TATTGTGTATAGCTATAAGCTATAGGATAAATT
agtgaaattggaggt**tattgtgtaaagctataagctataagataaatt
                    TGTGTAAAGCTATAAGCTATAAGATAAATT
```

`depth` is reporting at this location because it has found some reads to process, but as it doesn't include the deleted bases in the final count it ends up printing a result of zero here.

This is sort-of related to #1163, which adds an option to count the deleted bases.  When the option in that pull request is enabled, the reported depth is 11 at that position instead of zero:

```
./samtools depth -J toy.bam | egrep -A 1 'c6268220_99999_s6268220.*16455'
c6268220_99999_s6268220	16455	11
c6268220_99999_s6268220	16456	11
```

**Comment by Asutu** [comment]
Thanks for quickly following this up and for the very useful information.
