### ISSUE TITLE
CRAM compression not documented properly

### ISSUE THREAD

**Issue by gevro** [samtools/samtools#1167]
Hi, There is no documentation regarding how samtools view -C (BAM to CRAM compression) preserves or handles quality scores. There is also no way to control the type of quality score preservation (lossless) or compression.

Please advise.

Thanks.

**Comment by jkbonfield** [comment]
The CRAM encoding is lossless by default and the only choice of data loss if for read-name encoding.  There are no options to do lossy compression of quality scores, although third party tools do exist which link with htslib (including my own [crumble](https://github.com/jkbonfield/crumble) tool).

Options for controlling other aspects of CRAM, such as which codecs may be used and random access granularity, can be found in the samtools man page under the "GLOBAL COMMAND OPTIONS" section.
