### ISSUE TITLE
samtools collate should respect TMPDIR in generate_prefix()

### ISSUE THREAD

**Issue by mp15** [samtools/samtools#1172]
#### Are you using the latest version of [samtools]
samtools 1.10

 #### Please describe your environment.
linux

#### Please specify the steps taken to generate the issue, the command you are running and the relevant output.
run samtools collate with TMPDIR set
expected result: temporary files end up in $TMPDIR if set
actual result: generate_prefix() is hardcoded to use /tmp

**Comment by valeriuo** [comment]
@mp15 
Having made a PR for this issue, a debate has started about the (lack of) use of **TMPDIR** inside samtools. Is there any particular reason which requires the support of TMPDIR, when one can already specify the temporary folder prefix as a free CLI argument at the end of the command string?

`samtools collate [options] in.sam|in.bam|in.cram [<prefix>] `

**Comment by mp15** [comment]
Because it is not correct to assume /tmp, for example on my Mac (and every Mac).

`declare -x TMPDIR="/var/folders/03/3h2pdngd2k3d9_h3cb_mv554000dhq/T/"`

See also POSIX: https://pubs.opengroup.org/onlinepubs/9699919799/basedefs/V1_chap08.html

To be honest we should probably use mkdtemp and have done with it. That bit of code will create a unique non-colliding temporary DIR correct for the platform it is run on.

**Comment by jmarshall** [comment]
Bcftools uses `mkdtemp()` but has to substitute something else on Windows.

Doesn't this use about the same amount of temp space as `samtools sort`, therefore should perhaps similarly default to the same “put the temp files alongside the output file as that's a big disk” technique as that uses?

(Actually I came here to say “time to abstract out some temp dir handling into _sam_utils.c_ or similar” but there turns out to be less of it in samtools than I expected…)

**Comment by robmaz** [comment]
Any assumptions about which disks are large will be wrong for someone somewhere. It is just as likely that people want the temp stuff on a scratch disk and not on their precious data disk (where an automated backup may start to backup the temp files ...)

**Comment by dpryan79** [comment]
TMPDIR is so widely supported that it would really be nice to not have to manually specify the temporary location in samtools commands (I have users forgetting to do this frequently, since most python and other programs respect it and it's set on our cluster nodes).

**Comment by jmarshall** [comment]
@robmaz: Well, yes, that's why it needs a sensible default (same place as the output; $TMPDIR or _/tmp_ if unset; hardcoded _/tmp_ not so much) along with a way to override the default — which this command already has in its `[<prefix>]` command line argument.

**Comment by jmarshall** [comment]
BTW also I'd like to see the prefix override also specifiable as an option: `-T PREFIX`, the same as `samtools sort`. The current last-filename-is-a-tmp-prefix arrangement interferes with the usual Unix filter conventions. (The ship may have sailed on making it have real multi-input-file syntax, but at least you could write `samtools collate -T /tmp/wherever foo.bam` in a more explicit familiar way.)

**Comment by robmaz** [comment]
Seeing that collate is just a kind of sort producing "SO: unsorted GO:query", which is basically a less-processed supertype of "SO:queryname", one might wonder why this would even be a separate tool, let alone have a different interface. Maybe it could at some point become a new sort option -c, with the old collate becoming just a legacy interface for that. Then it would also automatically use the sort semantics for temp files.

**Comment by jkbonfield** [comment]
The algorithms are completely different.  Sort sorts.  Collate collates.  The two don't have to be remotely similar in operation.  As an example, collate can use binning via hashes of names (to ensure the same name ends up in the same bin), but there is no sort order between different names.  Or it can buffer up until it sees the second name (or more if XA/SA imply more are forthcoming) and emit the group collated at that stage.  This can make `samtools collate` much faster than simply sorting, hence it makes sense to think of it as a separate tool in its own right.

Regarding the TMPDIR environment variable the `mktemp` and `tempnam` functions use it, but both are documented with "Never use this function"!.    So I suspect most tools have been rewritten to use `tmpfile` or `mkstemp` and hence no longer honour TMPDIR.

We could support for it ourselves of course (and it certainly wouldn't harm), but there's no longer the wide spread expectation of it working in the unix culture.

**Comment by robmaz** [comment]
I hadn't given the algorithm much thought, but from a user perspective, any operation that changes he sort order as stated in @HD (and in my view, that includes the GO: tag) is arguably a sorting operation ... but fair enough, I don't really want to argue for making it one tool.

**Comment by jkbonfield** [comment]
For what it's worth, collates original name was "bamshuf" - the complete and utter opposite of sort. :-)
It was devised to randomise the order of data, but keep pairs together, so we could regenerate fastqs and realign without affecting aligner assessment of insert sizes (which can become very skewed if the data is presented in chr/pos ordering). 

Anyway, it's a digression.  Agreed that TMPDIR perhaps could be honoured properly within htslib & samtools.

@jmarshall wrote:
> (Actually I came here to say “time to abstract out some temp dir handling into sam_utils.c or similar” but there turns out to be less of it in samtools than I expected…)

Still a good longer-term solution that this single fix to `samtools collate`.

**Comment by adamnovak** [comment]
With this bug, and without  it's not possible to use `samtools collate` on Terra or in other environments where `/tmp` is not able to hold BAM-sized files, and the user is expected to use storage disks provided elsewhere for anything of appreciable size.

My current workaround is to **patch the samtools binary with Perl**, because [no butterflies were available](https://xkcd.com/378/).

```
cp `which samtools` ./modified_samtools
perl -pi -e 's/\/tmp\/collate/.\/tmpcollate/g' ./modified_samtools
# Now ./modified_samtools collate will keep scratch files in the *current* directory
```

**Comment by jmarshall** [comment]
@adamnovak: While I agree that this subcommand should respect TMPDIR, you also have the option of using the `<prefix>` argument to override the temporary file location. (But see also https://github.com/samtools/samtools/issues/1172#issuecomment-583358328)

**Comment by jkbonfield** [comment]
I don't understand why #1178 was never looked at as a solution to this.  I'll take a look myself.

We are now better at stopping things fall through the crack, but this PR landed in an era of no meeting minutes and things sometimes just fell off the radar. :/  We really need to make the time to go through all our outstanding old PRs and tidy them up - either close as outdated / won't fix, or allocate them for review.

**Comment by jkbonfield** [comment]
I agree with the sentiment that while TMPDIR isn't strictly necessary given an explicit command line parameter to specify the directory, and that TMPDIR isn't even that robust on Unix given patchy support by the more modern (and recommended) temp functions, it's also unlikely to cause any problems, trivial to do, and importantly already solved by Valeriuo.

So I did some minimal tidying to #1178 and made a new PR (#1782).
