### ISSUE TITLE
samtools stats & CRAM indexing problem

### ISSUE THREAD

**Issue by pd3** [samtools/samtools#1173]
I get a nonsense result when requesting stats on a single chromosome
````
$ samtools view -h test.cram 1 | samtools stats | grep 'raw total sequences'
SN	raw total sequences:	11641406

$ samtools stats test.cram 1 | grep 'raw total sequences'
SN	raw total sequences:	9990
````

This issue may be related to https://github.com/samtools/htslib/issues/977
I'll provide a test CRAM offline.

**Comment by jkbonfield** [comment]
It looks like this isn't the only problem.  Eg a 31-bit int limit:

```
SN      bases inside the target:        2147483647
```

That's perhaps a different bug though.  This one appears to be an index region parsing or querying thing.  I'm not sure how stats and view can interpret the region differently, but this gives the correct answer:

```
$  samtools stats test.cram 1:1-249250621 | grep 'raw total sequences'
SN	raw total sequences:	11641406
```

Why wasn't "1" considered to be all of chr 1?  It needs more investigation.
