### ISSUE TITLE
Empty depth.txt file for hybrid assembled contigs

### ISSUE THREAD

**Issue by cmaggior** [samtools/samtools#1179]
Using ```samtools depth *.sorted.bam > depth.txt``` is returning an empty txt file for hybrid MinION/HiSeq data. The .sorted.bam files were indexed, as well. The command works as expected when used with just HiSeq contigs. Any tips/advice? I didn't have an error file but am happy to run the command again to generate one.

**Comment by jkbonfield** [comment]
Do you have a small snippet of example data that we could look at that produces this problem?

**Comment by cmaggior** [comment]
Problem was fixed by re-running mapping program (bbmap) with different parameters. Sorry for the trouble!
