### ISSUE TITLE
samtools partially marks reverse reads as duplicates

### ISSUE THREAD

**Issue by gamabunta313** [samtools/samtools#1180]
I am working on cfDNA project and I am using the samtools v1.9 mpileup function to analyze normal vs tumor samples for further steps (samtools mpileup -ABQ0 -d 10000000000). What happened is that I lost part of the reverse reads only since marked as duplicates. I've edited an older version o samtools (v 1.18) to avoid duplicate removal and it seems to correct such behavior. I am wandering if someone encountered a similar problem and how he/she managed to fix it. Moreover, I would like clarification regarding the good practices when using samtools mpileup.

**Comment by whitwham** [comment]
I am not sure I understand the question.

By default mpileup will exclude duplicate reads.  This is not new behaviour and should not have changed between v1.8 and v1.9.

You can control which flags are excluded by using the -ff option.  For example, the following should keep the normal filters but allow duplicates through.
`-ff UNMAP,SECONDARY,QCFAIL`

Is the way you are marking duplicates changed?

**Comment by gamabunta313** [comment]
Thanks for the fast reply ! as soon as I can I'll check your solution.
Bests

**Comment by whitwham** [comment]
I am closing this issue since it has been quiet for over a fortnight.
