### ISSUE TITLE
mpileup how to get corresponding basequality from base

### ISSUE THREAD

**Issue by MartenHoogeveen** [samtools/samtools#1186]
How can I get the correct quality score for each base in the mpileup output. The length of base column is longer then the quality column. I am aware of things like insertion, deletions, start of the read info. But I cannot filter the base (5th) column so it matches the quality score. Is this even possible?

One of my filter steps in python is:
```
re.sub(r'\^[^actgnNACTG\.\,]', '', bases)
bases = bases.replace("^", "")
```

But if the bases are something like:
`.^.^A^,^,^,^,g^,^,^,^,^W,`

How do I know if the character after the "^" is a ASCII score or a mismatch?

**Comment by jkbonfield** [comment]
The [samtools mpileup](http://www.htslib.org/doc/samtools-mpileup.html#Pileup_Format) man page describes this format.

The caret is a marker for a new sequence starting at this location with the following character being the alignment mapping score.  Similarly dollar indicates the last base in a sequence.  You'll also find + and - to indicate insertions.

If you just do a global substitution for `\^.|\$` then you'll only have sequence bases left (including indels).  If you want to remove the indels too it's a bit trickier with pure regexp as POSIX regular expressions cannot count.  It's doable in perl re though using the `(??{ code })"` syntax on a capture group.   I don't know if a similar feature is in the python regexp engine.

Eg this would remove the indels and start/end markers and then validates the sequence and quality lengths match - so produces no output:

```
samtools mpileup in.bam | perl -lane '$F[4]=~s/\^.|\$//g;$F[4]=~s/[+-](\d+)(??{".{$1}"})//gi;print "@F" if (length($F[4]) != length($F[5]))'
```

**Comment by MartenHoogeveen** [comment]
Thanks, if I use your command I don't have any output. I will try to write it myself in python and follow up if it works.
