### ISSUE TITLE
Improve documentation of bedcov input files

### ISSUE THREAD

**Issue by mcarmack** [samtools/samtools#1188]
I have run into issues trying to use bed files of form:
```
chrom    chromstart    chromend
chr1    20915535    20915536
```
And received the error:
`Errors in BED line 'chr1    20915535    20915536'` 

My problem was that bedcov does not accept the "chr" in the input bed file.

It would be very helpful to have this documented in the bedcov manual:
http://www.htslib.org/doc/samtools-bedcov.html

**Comment by valeriuo** [comment]
But `bedcov` does accept any string reference name from the BED file, as long as that name is known (present in the header `@SQ` lines). What it usually complains about with errors of this kind is the presence of blank spaces as column separators in the BED file, instead of single tabs only.
