### ISSUE TITLE
Build according to INSTALL cannot work

### ISSUE THREAD

**Issue by adamnovak** [samtools/samtools#119]
Hello,

I am trying to build samtools. The INSTALL file says to just run Make. Doing that produces this:

```
[anovak@podk samtools]$ make
Makefile:53: ../htslib/htslib.mk: No such file or directory
make: *** No rule to make target `../htslib/htslib.mk'.  Stop.
```

So the INSTALL file is incorrect; it looks like it is necessary to check out samtools adjacent to some other project (htslib), or manually set HTSDIR in the Makefile, in order for it to build. Please update INSTALL (and, presumably, README) to reflect this somewhat idiosyncratic dependency.

**Comment by agarwal** [comment]
In addition, the INSTALL file specifically says "This samtools release contains a copy of HTSlib", but at least version 1.1 doesn't.

**Comment by mp15** [comment]
Are you talking about the git repo or the release tarball?

**Comment by agarwal** [comment]
The tarballs from the GitHub releases page, so the repo and tarball would be the same since there are no [binary assets](https://github.com/blog/1547-release-your-software) attached to the releases. Am I going to the wrong place?

**Comment by jmarshall** [comment]
As noted in release announcements and http://www.htslib.org/, releases are made available at [SourceForge](http://sourceforge.net/projects/samtools/files/samtools/1.1/).

At some point we will likely make release tarballs available at GitHub too (cf [motivation](https://twitter.com/najeebashraf/status/550236060899213312)), but at present those there are GitHub-generated unaugmented tarballs corresponding to commits, which are not samtools _releases_.

**Comment by agarwal** [comment]
Got it. Thanks for the clarification.

**Comment by jmarshall** [comment]
The INSTALL instructions were updated in the lead-up to the 1.0 release in ad732cd9634310541ce42bb8f47c9742f49aeb0a.  (In the upcoming release or the next, samtools will be acquiring a configure script, and the instructions will be updated again and simplified accordingly.)

FYI since 1.2, we are also making release tarballs as GitHub release binary assets.
