### ISSUE TITLE
addreplacerg command level flag

### ISSUE THREAD

**Issue by mikelatiolais** [samtools/samtools#1190]
#### Are you using the latest version of [samtools](https://github.com/samtools/samtools/releases/latest) and [HTSlib](https://github.com/samtools/htslib/releases/latest)? If not, please specify.
(run `samtools --version`)
Version: 1.10 (using htslib 1.10)

 #### Please describe your environment.
- OS (run `uname -sr` on Linux/Mac OS or ` wmic os get Caption, Version` on Windows)
Linux 3.10.0-957.5.1.el7.x86_64
- machine architecture (run `uname -m` on Linux/Mac OS or ` wmic os get OSArchitecture` on Windows)
x86_64
- compiler (run `gcc --version` or `clang --version`)
gcc 5.4.0

#### Please specify the steps taken to generate the issue, the command you are running and the relevant output.
I compiled samtools for a researcher, and they are asking about an apparent difference in the documentation online and the documentation shown with --help. 
Online, the command lists [-l level] as an option in the synopsis:
samtools addreplacerg [-r rg-line | -R rg-ID] [-m mode] [-l level] [-o out.bam] in.bam

When they run "samtools addreplacerg --help" it is missing:
Usage: samtools addreplacerg [options] [-r <@RG line> | -R <existing id>] [-o <output.bam>] <input.bam>

Was this removed at some point? Is there something I missed when compiling?

**Comment by valeriuo** [comment]
It appears to have been removed in https://github.com/samtools/samtools/commit/9a8f2f6d8a02c2052319b7a5c9c920ba14e5fffb, without proper update to the documentation or to the option string. We'll fix. Thanks for the report!
