### ISSUE TITLE
Download pages wrong version

### ISSUE THREAD

**Issue by Ikayanjoh** [samtools/samtools#1198]
Good Morning,

 I was trying to install Samtools, bcftools and htslib and went to this website https://github.com/samtools/samtools/releases downloaded version 1.9 and run the installation 

cd samtools-1.x    # and similarly for bcftools and htslib
./configure --prefix=/where/to/install
make
make install

Everything went find but wen i did check the version its showing version 1.7
do you have the version 1.9 and how can i get and upgrade my samtools?

#### Are you using the latest version of [samtools](https://github.com/samtools/samtools/releases/latest) and [HTSlib](https://github.com/samtools/htslib/releases/latest)? If not, please specify.
(run `samtools --version`)

 #### Please describe your environment.
- OS (run `uname -sr` on Linux/Mac OS or ` wmic os get Caption, Version` on Windows)
- machine architecture (run `uname -m` on Linux/Mac OS or ` wmic os get OSArchitecture` on Windows)
- compiler (run `gcc --version` or `clang --version`)

**Comment by whitwham** [comment]
When you did the version check are you sure you are running the 1.9 version you just installed?  Is there an older version on your system that you could be picking up instead?

**Comment by valeriuo** [comment]
If `which samtools` command returns a path other than `/where/to/install/samtools`, it means you have another version of samtools installed in a different folder that takes precedence over `/where/to/install/` in the `$PATH` order.

**Comment by Ikayanjoh** [comment]
@whitwham and @valeriuo  , Thank you for your feedback but No there is no other samtools installed that i know off.
i apologize but i'm a newby in this how could i double check if there is other version of samtools installed? if ever can how can i upgrade it using the download file (version 1.9).

**Comment by daviesrob** [comment]
Try to `cd` to the directory where you built samtools, and run `./samtools --version`.  That will tell you the version of the samtools that you just built.  You can also try `grep ^VERSION version.sh`.  That should confirm that you really have got version 1.9.

You could also try the following commands to locate possible samtools installations on your system:

`which -a samtools`

`locate '*/samtools'`

**Comment by tseemann** [comment]
This command will print your $PATH out nicely so you can see the order of folders that your computer is looking for the samtools command:
```
echo $PATH | tr ":" "\n" | nl
```
Another option to avoid manually compiling samtools is to use a packaging system like bioconda (linux) or brew (mac).

**Comment by valeriuo** [comment]
Not a samtools dev issue.
