### ISSUE TITLE
bam_fetch cannot successfully search for 0-length intervals

### ISSUE THREAD

**Issue by kortschak** [samtools/samtools#12]
Hello,

This may sound like a strange thing to report, but SVs are 0-length, so there is merit in being able to query for 0-length regions. Currently bam_fetch cannot take a target query where beg==end and return the alignments that overlap that query. This is because bam_iter_query does not create bins when the interval length equals zero.

There is a work around where a non-zero-length query is constructed that encompasses the real query and then the results are further filtered. This is a nasty kludge.

It is not clear to me whether it is possible to sanely achieve 0-length feature searches while retaining compatibility with the current API - fully closed (i.e. element based) range indexing is implicit in is_overlap's overlap test (which requires at least one base of overlap) and this indexing cannot describe the position between bases.

Actually, it appears that there is some contradiction between is_overlap's definition of an overlap and the fact that bam_iter_query does not return a bin for a query where beg==end. It seems that bam_iter_query is using half closed ranges while is_overlap isn't.

thank you

**Comment by kirkmcclure** [comment]
Can a deprecation warning be added to bam_fetch() and the issue closed?

The bam_fetch() function remains in the codebase, but its only use is by samfetch() which is unused.
The issue originator was informed that "bam_fetch() is considered to be deprecated. It will still be there for backward compatibility, but using the iterator interface is recommended." (in 2012, at the transition to htslib).
http://ehc.ac/p/samtools/mailman/samtools-devel/thread/1346470050.4817.12.camel%40sueno/#msg29750975

And, the replacement does not appear to have the limitation:
````
samtools view <tmp_dir>/large_chrom.bam ref2:536880911-536880911
ref2_grp3_p001	163	ref2	536880911	99	15M	=	1-45CTGTTTCCTGTGTGA	|||||||||||||||	RG:Z:grp3	NM:i:13	MD:Z:0T0A0A1C0A0T0G0G0T0C0A1A0G0
````
