### ISSUE TITLE
Samtools 'coverage' reporting inconsistent values in column 4 relative to input BAM

### ISSUE THREAD

**Issue by calliza** [samtools/samtools#1203]
#### Are you using the latest version of [samtools]
samtools 1.10
Using htslib 1.10

 #### Please describe your environment.
x86_64

#### Please specify the steps taken to generate the issue, the command you are running and the relevant output.

1) Aligned reads to reference (BWA version 0.7.17):
```
bwa mem \
        -M -t $NCPUS $ref \
        -R "@RG\tID:${flowcell}.${lane}_${sampleID}_${lib}\tPL:${platform}\tPU:${flowcell}.${lane}\tSM:${sampleID}\tLB:${sampleID}_${lib}\tCN:${centre}" \
        $raw_reads_1 $raw_reads_2 \
        | samtools sort -@ $NCPUS \
       --write-index -o ${out_raw}##idx##${out_raw}.bai
```

2) Run samtools 'coverage':
`samtools coverage --reference $ref T1121B.rawReads.sort.bam -o T1121B.rawReads.cov`

3) Run samtools idxstats:
`samtools idxstats T1121B.rawReads.sort.bam >  T1121B.rawReads.idxstats`

4) Compare 'coverage', 'idxstats' and 'view' output for first 10 reference contigs:
$ head -11 T1121B.rawReads.cov 
#rname  startpos        endpos  numreads        covbases        coverage        meandepth       meanbaseq       meanmapq
k141_24689      1       321     8       321     100     2.33645 35.8    39
k141_49373      1       331     84      79      23.8671 0.477341        36.8    10.9
k141_0  1       362     108     362     100     23.779  26.3    23
k141_85277      1       369     14      329     89.1599 5.72087 34.8    49.9
k141_20201      1       390     17      388     99.4872 5.55128 35.9    60
k141_6735       1       327     8       327     100     3.12232 35.4    51.1
k141_92009      1       320     26      320     100     12.9812 36.1    43.2
k141_33665      1       351     9       351     100     2.50712 36.7    60
k141_53861      1       368     10      368     100     3.40489 36.2    46.5
k141_62837      1       376     39      376     100     16.1968 36      33.8
$ head T1121B.rawReads.idxstats 
k141_24689      321     6       1
k141_49373      331     2       0
k141_0  362     445     2
k141_85277      369     14      0
k141_20201      390     15      0
k141_6735       327     8       0
k141_92009      320     28      0
k141_33665      351     8       0
k141_53861      368     9       1
k141_62837      376     41      0
$ samtools view T1121B.rawReads.sort.bam k141_24689 | wc -l
7
$ samtools view T1121B.rawReads.sort.bam k141_49373 | wc -l
2
$ samtools view T1121B.rawReads.sort.bam k141_0 | wc -l
447
$ samtools view T1121B.rawReads.sort.bam k141_85277 | wc -l
14
$ samtools view T1121B.rawReads.sort.bam k141_20201 | wc -l
15
$ samtools view T1121B.rawReads.sort.bam k141_6735 | wc -l
8
$ samtools view T1121B.rawReads.sort.bam k141_92009 | wc -l
28
$ samtools view T1121B.rawReads.sort.bam k141_33665 | wc -l
8
$ samtools view T1121B.rawReads.sort.bam k141_53861 | wc -l
10
$ samtools view T1121B.rawReads.sort.bam k141_62837 | wc -l
41

I understand that both 'idxstats' and 'coverage' may have default quality filtering, so I would expect that for some reference contigs, the number reported in 'idxstats' or 'coverage'  would be less than the number present in the BAM file as reported by 'view'. However, I do not understand how 'coverage' can report a greater number of reads in column 4 than is present in the BAM file for that reference contig. This is most extreme for contig k141_49373, where 84 reads are reported by 'coverage' yet there are only 2 reads reported in the BAM for that contig. The problem is also evident for contigs k141_24689, k141_20201 and k141_33665, though to a much lesser extreme. 

Thank you for your time,
Cali

**Comment by valeriuo** [comment]
Can you try indexing the sorted BAM file separately (without `--write-index`) and use that index file instead? Or running the latest HTSlib develop [HEAD](9979fac560319507cefe5d5682617304d609b589)? There was recently a bug fix (https://github.com/samtools/htslib/pull/1028), pertaining to a multi-threaded `--write-index` issue.

**Comment by calliza** [comment]
I tried indexing the sorted BAM separately, re-ran 'coverage', and the resulting coverage file was identical to that generated with the --write-index BAI file.

**Comment by valeriuo** [comment]
Ok, there might be an issue in the way **coverage** uses the **mpileup** methods and data. We'll work on a fix.

**Comment by valeriuo** [comment]
@calliza 
PR #1205 is a potential for this issue. Can you give it a try before it is merged?
