### ISSUE TITLE
Samtools Sort Failure: Repeating Samtools Sort without Re-Running BWA Mem?

### ISSUE THREAD

**Issue by darethehair** [samtools/samtools#1206]
My environment:

```
samtools 1.10
Using htslib 1.10.2
Copyright (C) 2019 Genome Research Ltd.

Linux 4.18.0-0.bpo.1-amd64
gcc (Debian 6.3.0-18+deb9u1) 6.3.0 20170516
```

Ran the following commands, which appear to have resulted in successful execution of 'bwa mem' command, but failure when piped into a 'samtools sort' command:

```
$ time bwa mem -t 4 GCA_000001405.15_GRCh38_no_alt_analysis_set.fna.gz xxx_SA_L001_R1_001.fastq.gz xxx_SA_L001_R2_001.fastq.gz | samtools sort -@4 -o xxx_grch38.bam
...
[main] Version: 0.7.17-r1188
[main] CMD: bwa mem -t 4 GCA_000001405.15_GRCh38_no_alt_analysis_set.fna.gz xxx_SA_L001_R1_001.fastq.gz xxx_SA_L001_R2_001.fastq.gz
[main] Real time: 160817.542 sec; CPU: 626876.847 sec
[bam_sort_core] merging from 352 files and 4 in-memory blocks...
[E::bam_write1] Segmentation fault
```

Since it takes 48 hours to get to this point, and not knowing why the process died (a previous run using different alignment file worked OK), I am wondering what syntax I would have to use to re-run the 'samtools sort' command with the 352 work files I already have generated from the 'bwa mem' run?  Of course any insight as to why I got a segmentation fault would also be useful (I hope that re-running the 'samtools sort' will not fail again).

**Comment by daviesrob** [comment]
Unfortunately, while you can use `samtools merge` to merge all of the temporary files that sort wrote, you won't get all of the data back as a small amount will still have been in the memory of the `samtools sort` process that died. 

You could attempt to get that back by finding the last read stored in the last temporary file, then running `bwa mem | samtools sort` on all of the reads after that one in the original fastq files and finally merging the output from that with the temporary files from the original sort.  Note that as the input to `bwa` will be slightly different to what it originally saw, the results from this process would not be exactly the same as running it on all of the data - for example, its insert size calculations may come out slightly different.

Unfortunately it looks like you didn't get a core dump, which would have been very useful for finding out why `samtools sort` crashed.  However, it looks like the segmentation fault occurred while trying to print an error message in `bam_write1()`.  There aren't actually many places where it tries to print errors, and I'm at a bit of a loss as to how one of them could go wrong at that exact point.  Some possibilities might be a failure to allocate `bam->data` which somehow went unnoticed; a run-away string from `bam_get_qname(b)`; some unrelated error in another thread that happened to interrupt printing the error message; or something very odd happened to your `samtools` binary while it was in use.

**Comment by darethehair** [comment]
Hmmm...daviesrob, I guess I will just to need to re-run and hope for the best.  I'll post back what happens when I try it again...

**Comment by jkbonfield** [comment]
Not doing it as a pipe may help diagnose, or at least with a tee.

Right now you have "bwa | samtools", but "bwa [args] > aln.sam; samtools sort [args] < aln.sam" or equivalent can break things up a bit so you can retry if it fails, and may also get a better understanding of the failure.  Alternatively "bwa | tee aln.sam | samtools" type of usage would run as before, but keep a local cached copy of the input to samtools sort (NB - may be large!), which again permits a more efficient retry and debugging.

**Comment by tseemann** [comment]
May i ask how many CPU cores and RAM and Disk space you have on that machine?
I notice you choose `-t 4` (four).
The samtool sort uses 768MB per thread, and you asked for 5 threads (-@ is _extra_ threads).

**Comment by darethehair** [comment]
Update: It looks like my last run worked OK :)
```
$ time bwa mem -t 4 GCA_000001405.15_GRCh38_no_alt_analysis_set.fna.gz xxx_SA_L001_R1_001.fastq.gz xxx_SA_L001_R2_001.fastq.gz | samtools sort -@4 -o xxx_darren_enns_grch38.bam
[M::bwa_idx_load_from_disk] read 0 ALT contigs
[M::process] read 269524 sequences (40000207 bp)...
[M::process] read 269774 sequences (40000170 bp)...
[M::mem_pestat] # candidate unique pairs for (FF, FR, RF, RR): (0, 96692, 26, 0)
...
[M::mem_pestat] skip orientation RF as there are not enough pairs
[M::mem_pestat] skip orientation RR as there are not enough pairs
[M::mem_process_seqs] Processed 53562 reads in 45.447 CPU sec, 11.499 real sec
[main] Version: 0.7.17-r1188
[main] CMD: bwa mem -t 4 GCA_000001405.15_GRCh38_no_alt_analysis_set.fna.gz xxx_SA_L001_R1_001.fastq.gz xxx_SA_L001_R2_001.fastq.gz
[main] Real time: 155219.438 sec; CPU: 612418.881 sec
[bam_sort_core] merging from 352 files and 4 in-memory blocks...

real	2665m56.510s
user	10531m0.533s
sys	22m22.980s
```

This time, I had run my Linux session entirely in 'console' mode, and the process itself as 'root', to eliminate some variables.  Do I have any explanation as to why it worked this time?  Not really, but I know that it had worked in the past (with different input files) so I knew that I had a chance.  Had upgrading my memory from 8gb to 16gb (for this process) introduced some flakiness?  Perhaps.

I thank you all for your help and suggestions!  It is very good to know that I had the necessary hardware and software to run interesting code like this on my own -- but I am amazed at the resources (disk space and CPU time) it takes to actually do it!  

jkbonfield: If I ever get into lots of trouble again, I will consider using your alternate syntax in order to give myself a chance to just re-run the 'samtools' portion, which should be much quicker (though noting, as you did, the extra space that might be required).

tseemann: Your point is interesting.  Every example I had seen so far of 'samtools sort' uses an *even* number of cores -- is this is mistake by the users?  In my case, I think that I have 2 cores and 4 threads:

```
$ lscpu
Architecture:          x86_64
CPU op-mode(s):        32-bit, 64-bit
Byte Order:            Little Endian
CPU(s):                4
On-line CPU(s) list:   0-3
Thread(s) per core:    2
Core(s) per socket:    2
Socket(s):             1
NUMA node(s):          1
Vendor ID:             GenuineIntel
CPU family:            6
Model:                 69
Model name:            Intel(R) Core(TM) i7-4600U CPU @ 2.10GHz
Stepping:              1
CPU MHz:               1716.232
CPU max MHz:           3300.0000
CPU min MHz:           800.0000
BogoMIPS:              4189.93
Virtualization:        VT-x
L1d cache:             32K
L1i cache:             32K
L2 cache:              256K
L3 cache:              4096K
NUMA node0 CPU(s):     0-3
```

Since my original 8gb was insufficient for 'bwa mem', I had purchased/installed 16gb (as it turns out, it looks like 11gb would have been good enough).  By the end of my successful run, I still had 220gb of space free on the device I ran this:

`/dev/sdb6       1.2T  871G  220G  80% /data`

**Comment by darethehair** [comment]
Opps!  Did I speak too soon?  I proceeded to my next step (i.e. indexing my new BAM file) and got an error, even though I thought my BAM file creation was successful:

```
$ time samtools index xxx_darren_enns_grch38.bam 60820188477620_darren_enns_grch38.bam.bai
[E::bgzf_uncompress] Inflate operation failed: invalid distance too far back
[E::bgzf_read] Read block operation failed with error 1 after 0 of 4 bytes
samtools index: failed to create index for "xxx_darren_enns_grch38.bam": No such file or directory

real	2m34.593s
user	2m22.277s
sys	0m2.416s

```

**Comment by jkbonfield** [comment]
Regarding number of threads, samtools does spawn an additional N threads, but when doing so it's typically offloading the heavy lifting to those threads (compression, sorting) and the additional main / original thread usually doesn't run close to 100% CPU utilisation.   Also asking for a few more threads than you have isn't usually a big bottleneck.

As for the samtools index error, the read of 4 bytes is typically the first 4 bytes of a BAM record (size), so this likely implies it failed with broken or truncated data.  Does `samtools quickcheck xxx_darren_enns_grch38.bam` fail?  That basically checks the very start and very end of the file to look for EOF marker.

It may also be informative to know whether `zcat xxx_darren_enns_grch38.bam > /dev/null` fails or not.  If it doesn't then this implies the data isn't corrupted per-se, but for some reason sort wrote inappropriate BAM data.  If zcat fails, then I'd be suspicious of a filesystem corruption.  What is the filesystem you are writing this file to?

**Comment by darethehair** [comment]
jkbonfield: Thanks for your input!

1) samtools quickcheck is OK:

```
$ samtools quickcheck xxx_darren_enns_grch38.bam
(no messages)
```

2) zcat has troubles:

```
$ zcat xxx_darren_enns_grch38.bam > /dev/null

gzip: xxx_darren_enns_grch38.bam: invalid compressed data--crc error

gzip: xxx_darren_enns_grch38.bam: invalid compressed data--length error
```

3) My 'ext4' file system seems to be fine:

```
$ sudo e2fsck /dev/sdb6
e2fsck 1.43.4 (31-Jan-2017)
DATA: clean, 266566/75956224 files, 233319956/303803136 blocks
```
So my BAM file was assembled/compressed improperly?

**Comment by jkbonfield** [comment]
So thinking about the observations:

- Samtools read the SAM from bwa and wrote all the intermediate files during sort.

- Samtools decoded all those intermediates fine, merged them and thinks it wrote the output fine.

- Neither samtools nor zcat can read the compressed BAM file, due to a data error which implies the file on disk is incorrect.

The compression of the data is just a call to zlib, which isn't something likely to be buggy.  While it's possible there is an error in samtools, it is smelling like a data corruption outside of samtools itself, either a filesystem glitch or a silent memory corruption.

Have there been any system logs reporting errors, eg from `dmesg` or in the various /var/log files?

To check system memory there are tools like [memtest86](https://www.memtest86.com/) or possibly it's even already available in your GRUB boot menu when you reboot the machine.

**Comment by darethehair** [comment]
jkbonfield:  I guess I am in a dilemma -- not knowing exactly what I should do at this point (after many days of effort) :( I do not recall seeing any evidence of errors in my Linux logs for either disk corruption nor memory problems.  The only stranger-than-normal behavior since my upgrade to 16gb was (initially) some crashes by Firefox browser for strange reasons.  Memtest86 doesn't run properly on my Chromebox -- possibly due to its unusual SeaBIOS firmware.  As an alternative, ChromeOS has 'memtester' as a built-in option.  Not as thorough, perhaps, as memtest86, but it reports good memory (I think testing 12gb out of the 16gb installed?):

```
crosh> memory_test
memtester version 4.2.2 (64-bit)
Copyright (C) 2010 Charles Cazabon.
Licensed under the GNU General Public License version 2 (only).

pagesize is 4096
pagesizemask is 0xfffffffffffff000
want 12506MB (13113491456 bytes)
got  12506MB (13113491456 bytes), trying mlock ...locked.
Loop 1/1:
  Stuck Address       : ok        
  Random Value        : ok
  Compare XOR         : ok
  Compare SUB         : ok
  Compare MUL         : ok
  Compare DIV         : ok
  Compare OR          : ok
  Compare AND         : ok
  Sequential Increment: ok
  Solid Bits          : ok        
  Block Sequential    : ok        
  Checkerboard        : ok        
  Bit Spread          : ok        
  Bit Flip            : ok        
  Walking Ones        : ok        
  Walking Zeroes      : ok        

Done.
```
What is odd as well is that my very first run of 'bwa mem/samtools sort' (with different input files) worked just fine -- but if this is some intermittent problem, then maybe this is possible.  Maybe what I should do (annoying as it might be) is to re-run *again* but on a different disk/partition.  If disk corruption is involved, this might avoid that.  For memory, I don't have strong evidence that anything is actually wrong.

Should I try the alternate syntax as you suggested?  Something like:

`time bwa mem -t 4 GCA_000001405.15_GRCh38_no_alt_analysis_set.fna.gz xxx_SA_L001_R1_001.fastq.gz xxx_SA_L001_R2_001.fastq.gz | tee aln.sam | samtools sort -@4 -o xxx_darren_enns_grch38.bam`

If you, what would be the syntax to just re-run the 'samtools' part if I need to do so?

**Comment by tseemann** [comment]
I notice your BWA reference is .gz compressed. What command did you use to index it?

**Comment by jkbonfield** [comment]
I have no idea how robust that memory check is, although it seems a bit suspicious that it only found about 3/4trs of your memory.

As for running things again, the above command you quoted would be reasonable comparable to your original pipeline but with the additional step of saving a copy of the BWA output for subsequent sort trials if needed.  Note the SAM file may well be 8x larger than the gzipped BAM, so be sure you estimate before hand if it'll fit on disk.

Judging by the total run time of the entire pipeline vs the time quoted by bwa, it looks like around 97% of your time is spent in the BWA part.  That means you can do dozens or sort trials in the time it takes to just rerun the entire thing once.  So saving the output should be a win for diagnosing things.

Sadly I don't really have a good feel for what's causing this other than the possibility of system glitches.

**Comment by darethehair** [comment]
> I notice your BWA reference is .gz compressed. What command did you use to index it?

Thanks for your question!

```
$ time bwa index GCA_000001405.15_GRCh38_no_alt_analysis_set.fna.gz
[bwa_index] Pack FASTA... 33.32 sec
[bwa_index] Construct BWT for the packed sequence...
[BWTIncCreate] textLength=6199845082, availableWord=448243540
...
[BWTIncConstructFromPacked] 680 iterations done. 6184133946 characters processed.
[bwt_gen] Finished constructing BWT in 688 iterations.
[bwa_index] 2523.54 seconds elapse.
[bwa_index] Update BWT... 14.97 sec
[bwa_index] Pack forward-only FASTA... 26.39 sec
[bwa_index] Construct SA from BWT and Occ... 1037.42 sec
[main] Version: 0.7.17-r1188
[main] CMD: bwa index GCA_000001405.15_GRCh38_no_alt_analysis_set.fna.gz
[main] Real time: 3711.325 sec; CPU: 3635.644 sec

real	61m51.327s
user	60m25.262s
sys	0m10.383s

```
Does this seem OK to you?

**Comment by darethehair** [comment]
OK, ran this again with the altered style:

```
$ time bwa mem -t 4 GCA_000001405.15_GRCh38_no_alt_analysis_set.fna.gz 60820188477620_SA_L001_R1_001.fastq.gz 60820188477620_SA_L001_R2_001.fastq.gz | tee aln.sam | samtools sort -@4 -o xxx_darren_enns_grch38_test2.bam
[M::bwa_idx_load_from_disk] read 0 ALT contigs
[M::process] read 269524 sequences (40000207 bp)...
[M::process] read 269774 sequences (40000170 bp)...
[M::mem_pestat] # candidate unique pairs for (FF, FR, RF, RR): (0, 96692, 26, 0)
[M::mem_pestat] skip orientation FF as there are not enough pairs
[M::mem_pestat] analyzing insert size distribution for orientation FR...
[M::mem_pestat] (25, 50, 75) percentile: (252, 325, 415)
[M::mem_pestat] low and high boundaries for computing mean and std.dev: (1, 741)
[M::mem_pestat] mean and std.dev: (337.68, 124.98)
[M::mem_pestat] low and high boundaries for proper pairs: (1, 904)
[M::mem_pestat] analyzing insert size distribution for orientation RF...
[M::mem_pestat] (25, 50, 75) percentile: (32, 76, 132)
[M::mem_pestat] low and high boundaries for computing mean and std.dev: (1, 332)
[M::mem_pestat] mean and std.dev: (73.50, 51.23)
[M::mem_pestat] low and high boundaries for proper pairs: (1, 432)
[M::mem_pestat] skip orientation RR as there are not enough pairs
[M::mem_pestat] skip orientation RF
[M::mem_process_seqs] Processed 269524 reads in 227.167 CPU sec, 56.899 real sec
...
[M::mem_process_seqs] Processed 269288 reads in 219.940 CPU sec, 55.205 real sec
[gzread] <fd:4>: incorrect data check
[bam_sort_core] merging from 200 files and 4 in-memory blocks...

real	1527m55.801s
user	5992m4.480s
sys	14m6.581s
```

The message 'incorrect data check' looks worrying.  Two files were created:

```
-rw-r--r-- 1 darren darren 179397103569 Mar 13 12:14 aln.sam
-rw-r--r-- 1 darren darren  25024693062 Mar 13 13:09 xxx_darren_enns_grch38_test2.bam
```

Can anyone advise to my next steps to validate the files and/or create a final BAM file (as if I had used the original shortcut method to begin with)?

P.S. No errors were reported in 'dmesg'.  Also interesting that this method took considerably less time (25 hrs vs 44 hrs).

**Comment by jkbonfield** [comment]
If you tail aln.sam you'll see what was passed into samtools sort.  It's unlikely it's corrupted, but it may be.  Even if so it _shouldn't_ cause a crash.  If it does then that is a bug, but I'm doubting as it seems to read all of the data and crash during the merge step (which is very I/O heavy).

My money however is still on either a filesystem corruption (broken disk) or memory corruption.  You didn't see this incorrect data check error before?  If not then it's highly likely this is something that has broken since your original tests, which again points at it not being downloading a corrupted file but rather gradual system failure (sorry!).  As memory is looking clean, try one of the disk trashing tools to see what happens there maybe.

Keep a close eye on system logs too, as maybe something has been reported there.

Either way, this is looking less and less like a samtools issue to me.

**Comment by jmarshall** [comment]
`[gzread] <fd:4>: incorrect data check` is a message from **bwa**, telling you the same thing about the input FASTQ files as that gzip command. You didn't see this before, suggesting that this is either intermittent or gradually degrading — neither of which is a good sign — and my money is in the same place as @jkbonfield's…

**Comment by darethehair** [comment]
FYI: Update to those who have generously been helping me through my efforts to use bwa/samtools to convert my Dante Labs FASTQ files from 'bg19' to 'GRCh38' -- I believe that I now (finally) have had success!

```
$ time bwa mem -t 4 GCA_000001405.15_GRCh38_no_alt_analysis_set.fna.gz xxx_SA_L001_R1_001.fastq.gz xxx_SA_L001_R2_001.fastq.gz | samtools sort -@4 -o xxx_darren_enns_grch38.bam

[M::bwa_idx_load_from_disk] read 0 ALT contigs
[M::process] read 269556 sequences (40000012 bp)...
[M::process] read 269810 sequences (40000038 bp)...
[M::mem_pestat] # candidate unique pairs for (FF, FR, RF, RR): (0, 0, 0, 0)
[M::mem_pestat] skip orientation FF as there are not enough pairs
[M::mem_pestat] skip orientation FR as there are not enough pairs
[M::mem_pestat] skip orientation RF as there are not enough pairs
[M::mem_pestat] skip orientation RR as there are not enough pairs
[M::mem_process_seqs] Processed 269556 reads in 167.144 CPU sec, 41.907 real sec
...
[M::mem_pestat] # candidate unique pairs for (FF, FR, RF, RR): (0, 0, 0, 0)
[M::mem_pestat] skip orientation FF as there are not enough pairs
[M::mem_pestat] skip orientation FR as there are not enough pairs
[M::mem_pestat] skip orientation RF as there are not enough pairs
[M::mem_pestat] skip orientation RR as there are not enough pairs
[M::mem_process_seqs] Processed 246530 reads in 161.221 CPU sec, 40.460 real sec
[main] Version: 0.7.17-r1188
[main] CMD: bwa mem -t 4 GCA_000001405.15_GRCh38_no_alt_analysis_set.fna.gz xxx_SA_L001_R1_001.fastq.gz xxx_SA_L001_R2_001.fastq.gz
[main] Real time: 113629.660 sec; CPU: 448658.147 sec
[bam_sort_core] merging from 352 files and 4 in-memory blocks...

real	1966m29.925s
user	7708m9.538s
sys	12m19.457s

$ time samtools quickcheck xxx_darren_enns_grch38.bam

real	0m0.476s
user	0m0.005s
sys	0m0.000s

$ time zcat xxx_darren_enns_grch38.bam > /dev/null

real	20m38.380s
user	18m49.310s
sys	0m15.023s

$ time samtools index xxx_darren_enns_grch38.bam xxx_darren_enns_grch38.bam.bai

real	14m27.191s
user	12m38.902s
sys	0m14.695s

$ ls -ltr xxx_darren_enns_grch38.bam*
-rw-r--r-- 1 darren darren 28169047131 Mar 29 23:50 xxx_darren_enns_grch38.bam
-rw-r--r-- 1 darren darren     8795176 Mar 30 08:46 xxx_darren_enns_grch38.bam.bai
```
To what I do attribute my success this time?

1) Despite the fact that none of my computer memory tests always came out clean, I reduced my installed memory from 16gb down to 12gb.  This still gave me sufficient resources to run these utilities, which took around 10.5gb to run.  Another 'hint' that this had a positive effect was that my Firefox browser stopped having crashed tabs.

2) My problem with badly-compressed FASTQ files from Dante Labs was only resolved when I asked for -- and they sent -- a third attempt, just a few days ago.  This then allowed me to re-run the utilities with confidence, after I verified that the compression was OK.

Thanks to all of you that helped!
