### ISSUE TITLE
Cram conversion error: [main_samview] failed to write the SAM header

### ISSUE THREAD

**Issue by EmadHassanin** [samtools/samtools#1207]
Hi,

I'm doing some experiments with cram files, I'm working with  .bam file from
`ftp://ftp-trace.ncbi.nlm.nih.gov/ReferenceSamples/giab/data/NA12878/NIST_NA12878_HG001_HiSeq_300x/RMNISTHS_30xdownsample.bam`
I try to convert it to cram format, the commands I run are:

`samtools view -@ 3 -C -T /references/hs37d5.fa /home/Archive/Data/RMNISTHS_30xdownsample.bam > /home/Archive/Compression/output/RMNISTHS_30xdownsample.4.cram`

And I get the next error:

`[E::cram_get_ref] Failed to populate reference for id 84
[main_samview] failed to write the SAM header`

I'll really appreciate your help!
Thanks,

Emad

**Comment by jkbonfield** [comment]
Ref 84 is the 85th SQ line (it starts counting from 0).  Lines 83-86 are:

```
     83 @SQ     SN:GL000225.1   LN:211173
     84 @SQ     SN:GL000192.1   LN:547496
     85 @SQ     SN:ERCC-00002   LN:1061
     86 @SQ     SN:ERCC-00003   LN:1023
```

I've not seen any human reference with these chromosomes in before, and they're certainly not in hs37d5.  Google suggests they're part of the External RNA Controls Consortium.  There is some information about them at the Encode website (https://www.encodeproject.org/data-standards/rna-seq/long-rnas/) but all I get is a bunch of broken links when I try to download.

Regardless, this isn't a samtools issue but one of poor data provenance (no M5 tags in the BAM header, no URL for fasta listed, and poorly filled out PG records) and usage error in specifying an incorrect reference file, so I'm closing this issue.   Please contact the people who generated this data and ask them for their reference.
