### ISSUE TITLE
Unable to load bcftools (dyld: library not loaded)

### ISSUE THREAD

**Issue by LorenzoLF** [samtools/samtools#1210]
Hello everyone,

Whenever I call bcftools (installed with conda, running in MacOS 10.15.3), I get the following error:

(base) lorenzolf@x86_64-apple-darwin13 ~ % bcftools
dyld: Library not loaded: @rpath/libquadmath.0.dylib
  Referenced from: /Users/lorenzolf/miniconda3/lib/libopenblasp-r0.3.9.dylib
  Reason: image not found
zsh: abort      bcftools

I know there are similar topics and I have been trying the different solutions that have been posted, but none of them have worked for me.

Could anybody give me a hand here?

Thank you very much.

**Comment by dpryan79** [comment]
Please open this on the bioconda repository.

**Comment by LorenzoLF** [comment]
Thanks for the reply.
What do you mean exactly?

**Comment by dpryan79** [comment]
Since the issue is with the bioconda package rather than samtools itself then this issue should be [on the bioconda project](https://github.com/bioconda/bioconda-recipes). We probably just need to change how the pinning is done in the recipe.
