### ISSUE TITLE
samtools calmd--input SAM does not have header. Abort!

### ISSUE THREAD

**Issue by JieLiBio** [samtools/samtools#1215]
Here is my environment
samtools 1.8
Using htslib 1.8
Copyright (C) 2018 Genome Research Ltd.

gcc (GCC) 4.4.7 20120313 (Red Hat 4.4.7-23)
Copyright (C) 2010 Free Software Foundation, Inc

Hi,
I used STAR 2-pass to produce genomic alignment and transcriptomic alignement BAM file. However, I have found there is no NM tag in transcriptomic BAM, So I would like to used samtools calmd to get NM tag so that I can input the transcriptomic BAM file to MMSEQ.

Here is my STAR code:
STAR --genomeDir <genomeDir> --readFilesIn <fastq1.gz> fastq2.gz> --limitSjdbInsertNsj <number_of_SJs>  --sjdbFileChrStartEnd <SJs_file> --outFileNamePrefix <output_prefix> --runMode alignReads --readFilesCommand zcat --runThreadN <number_of_threads> --outSAMprimaryFlag AllBestScore --outFilterMismatchNoverLmax 0.05 --outSAMattributes All --outSAMstrandField intronMotif --outFilterIntronMotifs RemoveNoncanonical --outFilterMultimapNmax 10 --seedSearchStartLmax 10 --outSJfilterOverhangMin 30 8 8 8 --outFilterScoreMin 0 --outFilterScoreMinOverLread 0.25 --outFilterMatchNmin 0 --outFilterMatchNminOverLread 0.25 --quantMode TranscriptomeSAM GeneCounts --quantTranscriptomeBan Singleend --outSAMtype BAM Unsorted SortedByCoordinate

After that ,I got three bam file, <output_prefix>.Aligned.out.bam, <output_prefix>.Aligned.sortedByCoord.out.bam and <output_prefix>.Aligned.toTranscriptome.out.bam. 

Then, I run 
samtools calmd -b ref_transcript.fa <output_prefix>.Aligned.toTranscriptome.out.bam > <output_prefix>.calmd.bam
where the ref_transcript.fa is the transcript sequence. 
However, an error occured:
[bam_fillmd] input SAM does not have header. Abort!

I have checked the header lines of  <output_prefix>.Aligned.toTranscriptome.out.bam 
samtools view -H <output_prefix>.Aligned.toTranscriptome.out.bam  
The results looks like this:

```
@SQ	SN:ENSMFAT00000000550	LN:4034
@SQ	SN:ENSMFAT00000045289	LN:103
@SQ	SN:ENSMFAT00000027236	LN:1965
@SQ	SN:ENSMFAT00000027246	LN:243
@SQ	SN:ENSMFAT00000027241	LN:1548
@SQ	SN:ENSMFAT00000027244	LN:1425
@SQ	SN:ENSMFAT00000064373	LN:1359
@SQ	SN:ENSMFAT00000012179	LN:3847
@SQ	SN:ENSMFAT00000038755	LN:67
@SQ	SN:ENSMFAT00000012195	LN:1161
.....
@SQ	SN:ENSMFAT00000070988	LN:1378
@SQ	SN:ENSMFAT00000000019	LN:69
@SQ	SN:ENSMFAT00000000020	LN:59
@SQ	SN:ENSMFAT00000000021	LN:71
@SQ	SN:ENSMFAT00000070989	LN:1812
@SQ	SN:ENSMFAT00000070990	LN:528
@SQ	SN:ENSMFAT00000000022	LN:69
@SQ	SN:ENSMFAT00000070991	LN:1141
@SQ	SN:ENSMFAT00000000023	LN:64
@SQ	SN:ENSMFAT00000000024	LN:69
```
(The head and tail )

How to solve this error? Any suggestions would be appreciated.

**Comment by jkbonfield** [comment]
> samtools calmd -b ref_transcript.fa <output_prefix>.Aligned.toTranscriptome.out.bam > <output_prefix>.calmd.bam
> where the ref_transcript.fa is the transcript sequence.
> However, an error occured:
> [bam_fillmd] input SAM does not have header. Abort!


The usage statement for calmd is:

```
Usage: samtools calmd [-eubrAESQ] <aln.bam> <ref.fasta>
```

You appear to be putting the ref.fasta before aln.bam, so the error about invalid header is because it is attempting to read ref.fasta as the sequence alignment file.
