### ISSUE TITLE
problems in samtools

### ISSUE THREAD

**Issue by zhanglm07** [samtools/samtools#1217]
when i try to tranform the .sam type to .bam type, it failed.
the command is:
**$ samtools view -bS aln-pe.sam > aln-pe.bam**
......
Then it shows that:
**[E::sam_hrecs_update_hashes] Duplicate entry ":516332_sim4" in sam header
samtools view: failed to add PG line to the header**

what should i do in this situation?

**Comment by valeriuo** [comment]
You have two `@SQ` lines with the same `SN` value (**:516332_sim4**). Try to understand why and correct/remove one of them.

**Comment by daviesrob** [comment]
Something like this should print out your duplicate header entries:
```
awk '/^@/ && /:516332_sim4/ { print } /^[^@]/ { exit }' aln-pe.sam
```

If you think the duplication is harmless, you can try getting rid of the extra one with:
```
awk 'BEGIN { i = 0; } /^@/ { if (/:516332_sim4/) { if (i++ < 1) { print; } } else { print } } /^[^@]/ { print }' aln-pe.sam > aln-pe-fixed.sam
```

Depending on exactly what made the duplicate entry, you may get lucky and end up with a usable SAM file.

**Comment by zhanglm07** [comment]
> Something like this should print out your duplicate header entries:
> 
> ```
> awk '/^@/ && /:516332_sim4/ { print } /^[^@]/ { exit }' aln-pe.sam
> ```
> 
> If you think the duplication is harmless, you can try getting rid of the extra one with:
> 
> ```
> awk 'BEGIN { i = 0; } /^@/ { if (/:516332_sim4/) { if (i++ < 1) { print; } } else { print } } /^[^@]/ { print }' aln-pe.sam > aln-pe-fixed.sam
> ```
> 
> Depending on exactly what made the duplicate entry, you may get lucky and end up with a usable SAM file.

thanks for your reply!
I had removed the duplication and tried it again, but another duplication was reported like before. And I found that there are many duplications in it. Maybe there is an error in the previous step(bwa)?

**[E::sam_hrecs_update_hashes] Duplicate entry ":xxxxxx_sim4" in sam header
samtools view: failed to add PG line to the header**

**Comment by zhanglm07** [comment]
> You have two `@SQ` lines with the same `SN` value (**:516332_sim4**). Try to understand why and correct/remove one of them.

thank you for your reply~ The problem has already been solved!

**Comment by zhanglm07** [comment]
> Something like this should print out your duplicate header entries:
> 
> ```
> awk '/^@/ && /:516332_sim4/ { print } /^[^@]/ { exit }' aln-pe.sam
> ```
> 
> If you think the duplication is harmless, you can try getting rid of the extra one with:
> 
> ```
> awk 'BEGIN { i = 0; } /^@/ { if (/:516332_sim4/) { if (i++ < 1) { print; } } else { print } } /^[^@]/ { print }' aln-pe.sam > aln-pe-fixed.sam
> ```
> 
> Depending on exactly what made the duplicate entry, you may get lucky and end up with a usable SAM file.

thank you for your reply~ The problem has already been solved!

**Comment by xiaozhenliu88** [comment]
> when i try to tranform the .sam type to .bam type, it failed.
> the command is:
> **$ samtools view -bS aln-pe.sam > aln-pe.bam**
> ......
> Then it shows that:
> **[E::sam_hrecs_update_hashes] Duplicate entry ":516332_sim4" in sam header samtools view: failed to add PG line to the header**
> 
> what should i do in this situation?

I have this problem, too. what should i do in this situation? Thank you very much.

**Comment by jkbonfield** [comment]
The error message explains what the problem is, so the solution is to fix it (the duplicate data in the header).  It's text so can be edited by various scripting tools or, if it's *small*, by a text editor.  You may be able to use samtools reheader too, unless it triggers the error before managing to reheader.

Better though would be to fix whatever is producing your broken headers so you don't have to patch up the file afterwards.

**Comment by nduan1** [comment]
I have the same problem, is that because I use the pair end data to mapping the references?

**Comment by valeriuo** [comment]
@nduan1 What application generated your file?

**Comment by Caiyulu-818** [comment]
> when i try to tranform the .sam type to .bam type, it failed. the command is: **$ samtools view -bS aln-pe.sam > aln-pe.bam** ...... Then it shows that: **[E::sam_hrecs_update_hashes] Duplicate entry ":516332_sim4" in sam header samtools view: failed to add PG line to the header**
> 
> what should i do in this situation?

I have this problem, too. what should i do in this situation? Thank you very much

**Comment by Caiyulu-818** [comment]
> > when i try to tranform the .sam type to .bam type, it failed. the command is: **$ samtools view -bS aln-pe.sam > aln-pe.bam** ...... Then it shows that: **[E::sam_hrecs_update_hashes] Duplicate entry ":516332_sim4" in sam header samtools view: failed to add PG line to the header**
> > what should i do in this situation?
> 
> I have this problem, too. what should i do in this situation? Thank you very much

 and I use bowtie to index my reference index file.

**Comment by whitwham** [comment]
Have you tried all the previous solutions mentioned in this issue?

**Comment by sunnyEV** [comment]
I tried both the AWK cmd's, able to remove one entry at a time.

I had more duplicates, how do I automate the process ?

I tried with samtools and picard to remove the duplicates, not successful.

Suggestions please!

**Comment by ouyang-lang** [comment]
> 
Hello, I also encountered the same problem, there are multiple duplicates, I would like to ask you, delete multiple duplicates in batches, have you solved it? Can you tell me your order? thanks

**Comment by sunnyEV** [comment]
Well, I able to solve using https://github.com/statgen/bamUtil, 
https://www.biostars.org/p/9523926/#9524238, check my post.

**Comment by ouyang-lang** [comment]
> Well, I able to solve using https://github.com/statgen/bamUtil, https://www.biostars.org/p/9523926/#9524238, check my post.
> 
> In case if you know alternative ways of solving the duplicates, please let me know.

Sorry, I didn't understand, did you use this command to solve it?
samtools view -F 1024 in.bam

**Comment by sunnyEV** [comment]
No, use bamUtil.

**Comment by ouyang-lang** [comment]
> No, use bamUtil.

Is bamUtil java? Linux can't use it, right?

**Comment by sunnyEV** [comment]
Well, 
Incase, if you have a lot of duplicates in the sam files, it is not possible to convert them to sorted bam using samtools.
Samtools can't handle the more duplicated sam, but using bamutil is able to convert to bam file and remove the duplicates. 

1) Install the bamutil in linux, 
2) bam convert - convert sam to bam file
3) Using samtools sort - convert a bam to sorted bam file.
3)  bam dedup --in <InputBamFile> --out <OutputBamFile> 
4)  Output is a sorted bam file without duplicates

**Comment by ouyang-lang** [comment]
> Well, Incase, if you have a lot of duplicates in the sam files, it is not possible to convert them to sorted bam using samtools. Samtools can't handle the more duplicated sam, but using bamutil is able to convert to bam file and remove the duplicates.
> 
> 1. Install the bamutil in linux,
> 2. bam convert - convert sam to bam file
> 3. Using samtools sort - convert a bam to sorted bam file.
> 4. bam dedup --in  --out
> 5. Output is a sorted bam file without duplicates

Thank you very much for your reply, I will try it

**Comment by jkbonfield** [comment]
Note converting SAM to BAM before running samtools is an unfortunately meme that won't die.  Samtools sort has been able to natively read and write SAM (along with BAM and CRAM) for a long time, so this step is not needed.  (Even if it was, it's likely that samtools view would be faster as it's heavily optimised and supports multi-threaded SAM decoding and encoding.)

Also samtools has it's own markdup command too which is mostly compatible with picard.

I don't know enough about bamutils to know how it's subcommands differ, but please don't propagate tropes based on the legacy samtools 0.1.19 era releases.  It's moved on a lot since then.

**Comment by ouyang-lang** [comment]
> Note converting SAM to BAM before running samtools is an unfortunate meme that won't die. Samtools sort has been able to natively read and write SAM (along with BAM and CRAM) for a long time, so this step is not needed. (Even if it was, it's likely that samtools view would be faster as it's heavily optimised and supports multi-threaded SAM decoding and encoding.)
> 
> Also samtools has it's own markdup command too which is mostly compatible with picard.
> 
> I don't know enough about bamutils to know how it's subcommands differ, but please don't propagate tropes based on the legacy samtools 0.1.19 era releases. It's moved on a lot since then.

Ok, thank you very much, I have solved my problem with bamutil according to the information you gave, but I would like to ask, can the bam files generated by bam dedup and bamutil convert be used directly?

**Comment by sunnyEV** [comment]
@lang 
The bam files generated from bamutil can be used further downstream processing analysis.
