### ISSUE TITLE
samtools depth: difference between -r and -b parameter

### ISSUE THREAD

**Issue by billzt** [samtools/samtools#1218]
I run the following two commands:
(1)
```
samtools depth -Q 20 A.bam B.bam C.bam -r chr2:171434627-171434627
```
It runs very fast (<0.1s), and output correct results:
```
chr2    171434627       52      35      18
```

(2) I put the region chr2:171434627-171434627 into a bed file (`test.bed`) like this:
```
chr2    171434626       171434627
```
and run:
```
samtools depth -Q 20 -b test.bed A.bam B.bam C.bam
```
It runs very slow (6mins) and output no results.

What's the difference?

**Comment by valeriuo** [comment]
What version of samtools are you using? 
`samtools --version`

**Comment by billzt** [comment]
@valeriuo v1.10

**Comment by valeriuo** [comment]
The latter form is know to be much slower. Does it display any result when you are running on individual files?

Can you show the output of the following two commands? It should be identical. The read names are scrambled.

`samtools view A.bam chr2:171434627-171434627 | awk 'BEGIN { seq=0; OFS="\t"; } { name=$1; $1=""; if (!reads[name]) {reads[name]="r" ++seq;} print reads[name], $0; }' | cut -f1-9`

`samtools view -L <(echo $'chr2\t171434626\t171434627') A.bam | awk 'BEGIN { seq=0; OFS="\t"; } { name=$1; $1=""; if (!reads[name]) {reads[name]="r" ++seq;} print reads[name], $0; }' | cut -f1-9`

**Comment by billzt** [comment]
@valeriuo Yes, they output identical results. The latter is much slower.

What should I do if I want to get repth in multiple samples in multiple positions? Since  the `-r` option only accepts a single position, currently I can only write a loop to run repeatly through multiple positions

**Comment by valeriuo** [comment]
You can try `samtools bedcov -j -Q 20 test.bed A.bam B.bam C.bam`. But you should fetch the latest develop [HEAD](189b5543d66b50e98e81173fc75c1d3a33febf3d), as it has a fix for exactly this scenario. 

I am still curious though why `samtools depth -Q 20 -b test.bed A.bam B.bam C.bam` doesn't output anything. It should work even if it's slower.

**Comment by billzt** [comment]
I'm sorry, after repeating my commands, it also produces the same results.
