### ISSUE TITLE
Checking the headers and starting positions of 22 files & CRC32 checksum mismatch

### ISSUE THREAD

**Issue by lovelymaoqin** [samtools/samtools#1220]
When I use bcftools combine all the genotype files, it give me an error.

bcftools concat -Oz -o merge.vcf.gz ALL.*.phase3_shapeit2_mvncall_integ
rated_v5a.20130502.genotypes.vcf.gz

Checking the headers and starting positions of 22 files
[E::bgzf_uncompress] CRC32 checksum mismatch
[E::bgzf_read] Read block operation failed with error 33 after 14 of 16 bytes
Concatenating ALL.chr1.phase3_shapeit2_mvncall_integrated_v5a.20130502.genotypes.vcf.gz[E::bgzf_uncompress] CRC32 c
hecksum mismatch
[E::bgzf_read] Read block operation failed with error 33 after 14 of 16 bytes

**Comment by lovelymaoqin** [comment]
Is anyway to check which file? Thanks.

________________________________

**Comment by mp15** [comment]
Bgzip files are valid gzip files so you can use `gzip -vt <file.vcf.gz>` to check each file.

**Comment by lovelymaoqin** [comment]
OK, thanks so much.
________________________________
