### ISSUE TITLE
A issue with bcftools concatenating .vcf.gz files from the same set of samples

### ISSUE THREAD

**Issue by lovelymaoqin** [samtools/samtools#1221]
I want to concatenate multiple .vcf.gz files from the same set of samples. I check all the .vcf.gz file and .vcf.gz.tbi files. However, it does not work.  Any suggestion will be appreciated. I also attached the .vcf.gz file headers. 

The command is as below
bcftools concat -Oz -o merge.vcf.gz ALL.chr{1..22}.phase3_shapeit2_mvncall_integrated_v5a.20130502.genotypes.vcf.gz

Checking the headers and starting positions of 22 files
ConcatenatingALL.chr1.phase3_shapeit2_mvncall_integrated_v5a.20130502.genotypes.vcf.gz
[E::bgzf_uncompress] Inflate operation failed: progress temporarily not possible,
 or in() / out() returned an error
[E::bgzf_read_block] Invalid BGZF header at offset 31618616
        25.019043 seconds
Concatenating ALL.chr2.phase3_shapeit2_mvncall_integrated_v5a.20130502.genotypes.vcf.gz

**Comment by pd3** [comment]
This looks like a problem with the data (corrupted file), not with the tools. To verify, try if this works
```
gunzip -c file.vcf.gz >/dev/null
```

**Comment by jkbonfield** [comment]
" [E::bgzf_uncompress] Inflate operation failed: progress temporarily not possible," implies you have a corrupted file.

Can you try `zcat ALL.chr{1..22}.phase3_shapeit2_mvncall_integrated_v5a.20130502.genotypes.vcf.gz > /dev/null`?  If that fails, the problem is the data and not bcftools.  (Also you added this issue to the wrong project.)

**Comment by lovelymaoqin** [comment]
Thanks so much it works.

________________________________

**Comment by lovelymaoqin** [comment]
Thanks so much.  It works.

________________________________

**Comment by nikotzoumas** [comment]
Hello, I'm having the same issue with indexing files on bcftools - was the only fix to re-download the data?

**Comment by jkbonfield** [comment]
If bcftools is unable to index your data, then it's highly likely either your data isn't the format you think it is (`zless file.gz` may give some clues) or it's been corrupted.  If the other end provides checksums (sha1, md5, etc) then you could verify that before downloading again.
