### ISSUE TITLE
samtools sort: [E::bgzf_read] Read block operation failed with error 2 after 0 of 4 bytes

### ISSUE THREAD

**Issue by billzt** [samtools/samtools#1225]
#### Are you using the latest version of [samtools](https://github.com/samtools/samtools/releases/latest) and [HTSlib](https://github.com/samtools/htslib/releases/latest)? If not, please specify.
(run `samtools --version`)
samtools 1.9 Using htslib 1.9

 #### Please describe your environment.
- OS (run `uname -sr` on Linux/Mac OS or ` wmic os get Caption, Version` on Windows)
Linux 2.6.32-696.13.2.el6.centos.plus.x86_64
- machine architecture (run `uname -m` on Linux/Mac OS or ` wmic os get OSArchitecture` on Windows)
x86_64
- compiler (run `gcc --version` or `clang --version`)
gcc (GCC) 4.4.7

#### Please specify the steps taken to generate the issue, the command you are running and the relevant output.
`samtools sort -@ 10 -o sample.sort.bam sample.bam`, where `sample.bam` is ~100G in size. My server's memory is 128G.

After running for about 30-60mins, it exits with the following error, leaving hundreds of `*.tmp.bam` files.
```
[E::bgzf_read] Read block operation failed with error 2 after 0 of 4 bytes
samtools sort: truncated file. Aborting
```

I tried to check `sample.bam` using `samtools quickcheck`, but there is no error.

**Comment by daviesrob** [comment]
If you try the `develop` htslib branch, you should find it prints a more useful error message that tells you where in the file the problem occurred.

`samtools quickcheck` just checks for a valid header and EOF block.  It doesn't do a full check on the file, as that takes quite a while.  `bgzip -t sample.bam` will do a more thorough check.

You can also use the `-m` option to tell sort to use more memory, which will make it much faster and reduce the number of temporary files that it makes.  Note that the setting is, for historical reasons, per thread, so with ten threads, '-m 10G' will make it use a 100Gbyte sort buffer (total memory used will be a little bit higher).

**Comment by tseemann** [comment]
@billzt i would also recommend upgrading to samtools 1.10

_Small speed up to samtools coordinate sort, by converting it to use radix sort. (#835, thanks to Zhuravleva Aleksandra)_

**Comment by billzt** [comment]
After re-run bwa and using samtools 1.10, it has been resolved.
