### ISSUE TITLE
ampliconclip ideas and todo list

### ISSUE THREAD

**Issue by whitwham** [samtools/samtools#1226]
Since ampliconclip is new and under development for the virus tracking project this is a place to put ideas and a reminder of things to do.

Initial list (in no real order)

- man page
- tests
- both ends clipping
- calmd fix for clipped reads

**Comment by whitwham** [comment]
Options:
Add OA tags to keep the original alignment data.
Remove MD and NM tags when they become invalid.

**Comment by whitwham** [comment]
The calmd fix is not done and not going to be done.  It is probably best left to calmd itself.  The rest have all been done.

**Comment by nathanhaigh** [comment]
I've just come to this tool and have a few suggestions which might help others trying to figure out how to run the tool.

I think the word "amplicon" is being somewhat misused in the help: according to the Sequence Ontology (http://www.sequenceontology.org/browser/current_release/term/SO:0000006) amplicon is the PCR product which will include the bit covered by primers. 

- It's unclear from the help what should actually be in the BED file. It says "bedfile of amplicons to be removed" but to me, it's the amplicon primers
- It's unclear what `--both-ends` and `--strand` achieve. I kind of assume the former requires both the 5' and 3' end of a read to match the boundary of one of the primers defined in the BED file

**Comment by whitwham** [comment]
> I think the word "amplicon" is being somewhat misused in the help: according to the Sequence Ontology (http://www.sequenceontology.org/browser/current_release/term/SO:0000006) amplicon is the PCR product which will include the bit covered by primers.

We know, the list of potential names is [here](https://github.com/samtools/samtools/pull/1219#issuecomment-609649307).  It was all to do with the amplicon based sequencing of Sars-Cov-2 and we were in a hurry.  We are probably not going to change it now.
 
>     * It's unclear from the help what should actually be in the BED file. It says "bedfile of amplicons to be removed" but to me, it's the amplicon primers

That is a good point.  I should include what entries are being used and why.
 
>     * It's unclear what `--both-ends` and `--strand` achieve. I kind of assume the former requires both the 5' and 3' end of a read to match the boundary of one of the primers defined in the BED file

I didn't think `--both-ends` was unclear.  Maybe the man page should read "Clip from the 5' and the 3' ends"?

`--strand` could do with more explanation, probably in conjunction with what we use from the BED file .
 
>     * It would be useful to state how much "slop" there is in matching the boundary coordinates of the read alignment with a primer region. Looking at the code, it looks like this is `tol = 5`

Yes, you are right and you are right.  It should also be an option you can set.

**Comment by nathanhaigh** [comment]
Thanks for the prompt response @whitwham!

**Comment by whitwham** [comment]
I see what you mean, I was thinking of the man page rather than the help (both could do with some work).  Thanks for the offer but I will update the documentation (probably easier), though I will ask you to review it.

Instead of  "soft clip amplicons from reads" would you want "soft clip amplicon primers from reads"?

**Comment by nathanhaigh** [comment]
No problems at all and happy to review.
I think that wording is more accurate and understandable.

I'd also like to suggest the following as a short, general purpose description of the tool.

> Clips the ends of read alignments if they intersect with regions defined in a BED file. While this is particularly useful for clipping read alignments positions which correspond to amplicon primers locations (hence its name) it can also be used in other contexts.

I've also noticed a couple of unexpected results so I'm putting together some mock data to use as tests to see if there are some bugs. I'll file these issues separately if I have something to report.

**Comment by whitwham** [comment]
All done, closing now.
