### ISSUE TITLE
calmd halts in an input record has SEQ=*, with incomprehensible error messages

### ISSUE THREAD

**Issue by rsharris** [samtools/samtools#1229]
####
samtools 1.10

####
- OS: Linux 4.4.0-141-generic
- machine architecture: x86_64
- compiler: gcc (Ubuntu 5.4.0-6ubuntu1~16.04.12) 5.4.0 20160609

####
Small example is available at https://psu.app.box.com/s/kzewixahnr8p9b290u8zy83mt05xbg18/file/656631838103

Run this command:
```
samtools calmd -e \
      --output-fmt SAM \
      reads_vs_assembly.bam \
      temp/${assembly}.fa \
  > reads_vs_assembly.calmd.sam \
  2> reads_vs_assembly.calmd.log
```

Get this failure:
```
[bam_fillmd1] different NM for read 'm74581_185104_510317/7374047/5_37840': 86 -> 697
[E::bam_aux_get] Corrupted aux data for read m74581_185104_510317/7374047/5_37840
[E::sam_format1_append] Corrupted aux data for read m74581_185104_510317/7374047/5_37840
samtools calmd: failed to write to output file: Invalid argument
```

I had originally reported this as issue lh3/minimap2#599 for minimap2 (since the bam file was created by minimap2). @jmarshall figured out the problem is that the BAM file contains records with SEQ=*. Removing these records from the BAM file sidesteps the problem.

Probably not relevant, but the BAM file was created by minimap2, like this:
```
minimap2 -t 3 -x map-pb -a --cs \
    ${assemblyPath}/${assembly}.idx \
    reads.fastq.gz \
  | tee reads_vs_assembly.sam \
  | samtools view -b -o reads_vs_assembly.bam
```

**Comment by jmarshall** [comment]
See the minimap2 issue for further background. I was unable to reproduce any “Corrupted aux data” errors with @rsharris's _reads_vs_assembly.bam_ file as downloaded yesterday.

**Comment by rsharris** [comment]
I now realize that my example bundle is missing temp/${assembly}.fa .

Gzipped version of that can be downloaded from https://vgp.github.io/genomeark-curated-assembly/Lynx_canadensis .  It is mLynCan4.pri.cur.20190110.fasta.gz , and there's a link to it under "Individual 4 Primary Assembly" about half way down the page.

**Comment by jmarshall** [comment]
“Corrupted aux data” is reproducible using this :cat2: assembly, with both _reads_vs_assembly.sam_ and _reads_vs_assembly.bam_. Great, now the maintainers are in business! :smile:

**Comment by daviesrob** [comment]
Yes, this is a bit tragic.  `bam_fillmd1_core()` goes [sailing on ahead](https://github.com/samtools/samtools/blob/3389c09/bam_md.c#L60) ignoring the fact that it's beyond the end of the stored sequence, and occasionally tries to [set a base](https://github.com/samtools/samtools/blob/3389c09/bam_md.c#L68) to `=` thereby corrupting the aux data.  Frankly I'm amazed it got as far as it did without crashing.
It "works" if you don't use the `-e` option, although the `NM` and `MD` calculated are complete fiction.
 I guess the best solution would be to politely refuse to recalculate NM and MD when there's no sequence stored as the information needed to do this is not easily available.

**Comment by rsharris** [comment]
Thanks!

That explains some of what I saw when I added debug prints to see what was happening. I didn't get deep enough to see it sailing ahead. But I added prints to tell me why it thought the aux data was corrupt (bcuz I assumed my input really was corrupt), and it was hitting tags that were not in my input.

The solution you suggest seems sensible to me. Maybe the man page for calmd could briefly mention that too?

**Comment by daviesrob** [comment]
Please have a try with PR #1230.  It should behave much better where records with `SEQ=*` are present.

**Comment by rsharris** [comment]
I'm attempting to try that, but I've run into problems building it because (I presume) I normally build samtools from a release tarball at http://www.htslib.org/download, and there are things in the release tarball that aren't the pull request.

Specifically, configure and config.h.in aren't there, and the htslib-X.XX subdirectory isn't there. I copied configure and config.h.in from the samtools-1.10 tarball, but when I attempted to 'make', it looks like it built an incompatible version of htslib (-1.9, which I must have built years ago for an earlier samtools) and this created complier errors.

I could probably get past that, e.g. by starting over, copying htslib from the samtools-1.10 tarball, hen doing config and make. I worry that this would raise questions about the validity of my test.

**Comment by rsharris** [comment]
I tried what I mentioned above (copying configure stuff and htslib-1.10 from the samtools-1.10 tarball) but make halts with compilation errors.

Specifically, in bam_md.c, in bam_fillmd1_core() it doesn't know what errno, ENOMEM, and EINVAL are.

So there must be some difference in your setup vs mine. Is it worth it for me to pursue this?

**Comment by jmarshall** [comment]
That one's probably a small deficiency in Rob's fixes. Add `#include <errno.h>` at the top of _bam_md.c_ and try compiling it all again.

**Comment by rsharris** [comment]
This time my build fails during link, since fai_path and bam_set_seqi are missing.  Referenced from sam_view.c, bam_sort.c, and padding.c. I can't find where there are defined.

**Comment by jkbonfield** [comment]
You'll probably need a more modern htslib too.  You can do a git clone of that either along side the samtools directory or if you prefer as a subdirectory of the samtools clone.  Ideally you'd also do a "autoreconf -i" to create the configure script in there, but it may also work without needing configure (depending on your system).

**Comment by daviesrob** [comment]
I've added the missing `#include`, although I think it was being picked up via `kstring` anyway.

The best way to test would be to go somewhere not contaminated by old versions of samtools and htslib, then:
```
git clone https://github.com/samtools/htslib.git
git clone https://github.com/samtools/samtools.git
cd htslib
autoconf && autoheader && ./configure && make
cd ../samtools
git fetch origin pull/1230/head:pr1230
git checkout pr1230
autoconf && autoheader && ./configure && make
```

**Comment by rsharris** [comment]
Thanks, rob.  I'm not up adept with using git repos, beyond the very basics; nor with autoconf. So those instructions were very helpful.

Anyway, having built it that way, the PR version did run correctly.  It reported 15 records for which there was no sequence in alignment record.  And for version it reports samtools 1.10-48-g013d182 using htslib 1.10.2-58-g2e36fa6.

Thanks!

**Comment by daviesrob** [comment]
Excellent, good to hear that it worked.
