### ISSUE TITLE
ampliconstats suggestions

### ISSUE THREAD

**Issue by mcshane** [samtools/samtools#1234]
1. Add the command line and version used generate the ampliconstats file to the header so users can, for instance, check what BED file was used to generate the file. Alternatively or in addition to the command line, could duplicate the BED file within the ampliconstats file which could then be used for additional plots within plot-ampliconstats (or custom plots from the stats file)

2. Increase MAX_AMP_LEN or add option to configure this - we are testing 1kb amplicons and had to adjust this.

3. Related to above would be good to add some detail about the coordinates being checked to the error messages when checking bounds on the BED file. We had some custom BED files that had mistakes and adding to the error messages helped track that down.

**Comment by jkbonfield** [comment]
Thank you Shane.  All good points so I'll work some more on it.
