### ISSUE TITLE
add --no-PP option

### ISSUE THREAD

**Issue by mcshane** [samtools/samtools#1235]
Similar to the `--no-PG` option, `--no-PP` would append a `@PG` line, but without the Previous Program `PP` tag. A number of tools in the wild will add `@PG` lines, but don't include `PP`. Thus when a samtools command gets run now, each of those multiple initial PP-less `@PG` lines will be considered a starting point for the command chain and you get and explosion of duplicated samtools commands in the header. Having a `--no-PP` option would allow some level of provenance tracking, even if not the ideal.

**Comment by daviesrob** [comment]
Rather than an option, would it be better to make this automatic?  E.g. only extend from correctly-made chains with `PP` tags and ignore any without - unless there's only one `@PG` line in which case the one to use is obvious.

**Comment by mcshane** [comment]
Yes. This would be better.

**Comment by mcshane** [comment]
Thanks. Working for my use case.
