### ISSUE TITLE
Error in the manual page for samtools depth

### ISSUE THREAD

**Issue by FrankFeng** [samtools/samtools#1243]
Just let you know the description for options -q and -Q is incorrect as at http://www.htslib.org/doc/samtools-depth.html

For -q, it should be "Only count reads with base quality greater than **_or equal to_** INT".
For -Q, it should be "Only count reads with mapping quality greater than **_or equal to_** INT".

**Comment by jkbonfield** [comment]
Thanks for the error report.  Now fixed.
