### ISSUE TITLE
Undefined symbols for architecture x86_64

### ISSUE THREAD

**Issue by emmannaemeka** [samtools/samtools#1251]
#### Describe the solution you would like.

Hi,
I am trying to compile samtools on Unix plateform.

I keep getting this error and cant solve it

gcc  -L./lz4  -o samtools bam_index.o bam_plcmd.o sam_view.o bam_fastq.o bam_cat.o bam_md.o bam_reheader.o bam_sort.o bam_rmdup.o bam_rmdupse.o bam_mate.o bam_stat.o bam_color.o bamtk.o bam2bcf.o bam2bcf_indel.o sample.o cut_target.o phase.o bam2depth.o coverage.o padding.o bedcov.o bamshuf.o faidx.o dict.o stats.o stats_isize.o bam_flags.o bam_split.o bam_tview.o bam_tview_curses.o bam_tview_html.o bam_lpileup.o bam_quickcheck.o bam_addrprg.o bam_markdup.o tmp_file.o bam_ampliconclip.o amplicon_stats.o ./lz4/lz4.o libbam.a libst.a -lhts -lncurses -lm -lz  -lpthread
Undefined symbols for architecture x86_64:
  "_bam_set_seqi", referenced from:
      _worker in bam_sort.o
  "_fai_path", referenced from:
      _main_samview in sam_view.o
      _main_pad2unpad in padding.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [samtools] Error 1

Can you help?

**Comment by jkbonfield** [comment]
`bam_set_seqi` was defined recently in htslib.  Are you building samtools from a git clone of the develop branch?  If so you will need to git clone htslib too in a sibling directory and build both together.

**Comment by valeriuo** [comment]
Detailed installation instructions can be found [here](https://github.com/samtools/samtools/blob/develop/INSTALL).

**Comment by StefanBruens** [comment]
> Detailed installation instructions can be found [here](https://github.com/samtools/samtools/blob/develop/INSTALL).

This does not mention any minimum required version of HTSLib for a specific samtools version.

See also https://github.com/samtools/samtools/issues/702
