### ISSUE TITLE
Enhanced markdup

### ISSUE THREAD

**Issue by keiranmraine** [samtools/samtools#1253]
@dkj asked we share any issues we've seen (a while ago)

#### Is your feature request related to a problem? Please specify.

We have encountered on the newer sequencing technologies read-pairs that appear to be duplicates slipping through due to minor differences in coordinates (a limitation of the current implementation).

There are 2 classes of these (read end can be swapped in either example):

1. r1 is well mapped and consistent, r2 has minor clipping on the *inner* edge due to mismatches (likely poor qual read of base).

e.g.

```
|||||||>         <|||||||
|||||||>          <||||||
|||||||>           <|||||
```

or

```
|||||||>         <|||||||
||||||>          <|||||||
|||||>           <|||||||
```

2. r1 is well mapped, r2 has differences due to poly tract slippage (see image).

![SV-duplicate_problem](https://user-images.githubusercontent.com/3740323/82565339-29ea0100-9b72-11ea-9baf-83cfbd831669.png)

In both cases 3 coordinates are generally stable.  The 2 positions that are the leading end of sequencing for each, and at least 1 of the trailing ends.

#### Describe the solution you would like.

An optional mode (expecting to be slower) in markdup that is able to handle this issue.

#### Reason

Reduce downstream processing to correct VAF and false calls due to over representation of these fragments.

**Comment by whitwham** [comment]
I think running in s mode should already handle this, though I would have to look at actual data to be sure.

Do you have any example data?

**Comment by tseemann** [comment]
```
  -m --mode TYPE   Duplicate decision method for paired reads.
                   TYPE = t measure positions based on template start/end (default).
                          s measure positions based on sequence start.
```

**Comment by keiranmraine** [comment]
Ah, a 1.10 feature.  Thanks
