### ISSUE TITLE
fetched proper_pair mapped reads id is not in same order

### ISSUE THREAD

**Issue by jlli6t** [samtools/samtools#1255]
#### Are you using the latest version of [samtools]
I am using samtools 1.10 & htslib 1.10

 #### Please describe your environment.
- OS : Linux 3.10.0-693.5.2.el7.x86_64
- machine architecture: x86_64
- compiler gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-16)

#### Please specify the steps taken to generate the issue, the command you are running and the relevant output.
'samtools view' to fetch mapped read and then using 'samtools fastq -1 1.fq -2 2.fq -0 other.fq to dump fetched sequences into fastq format, found that sequnces (ids) of 1.fq and 2.fq are not in same order.

**Comment by valeriuo** [comment]
The manual page of [fasta/fastq](http://www.htslib.org/doc/samtools-fasta.html) says:

> If the input contains read-pairs which are to be interleaved or written to separate files in the same order, then the input should be first collated by name. Use samtools collate or samtools sort -n to ensure this. 

Did you perform this step?

**Comment by jlli6t** [comment]
I sorted bam files with samtools sort, but without -n, therefore the sorted bam files is in coordinates order, then I guess this is why the output seems like in mess order?

Thank u so much!
