### ISSUE TITLE
Understanding Samtools depth command

### ISSUE THREAD

**Issue by namiller2015** [samtools/samtools#1256]
Hi All,

Apologies if this is explained elsewhere. My google searching didn't get me anywhere. 
I am trying to understand what exactly the samtools depth command is doing.

Specifically I am confused why increasing the input region size leads to drastically different depths reported

I am working off a BAM produced by Ion Torrent. Running
samtools depth -r chr17:41197711-41197712 INPUT_BAM 
results in
chr17	41197711	7847
chr17	41197712	7848

But Running
samtools depth -r chr17:41197700-41197712 INPUT_BAM
results in 
chr17	41197700	8057
chr17	41197701	8056
chr17	41197702	8057
chr17	41197703	8003
chr17	41197704	8055
chr17	41197705	8054
chr17	41197706	8035
chr17	41197707	8027
chr17	41197708	8028
chr17	41197709	7947
chr17	41197710	7959
chr17	41197711	14
chr17	41197712	15

So positions 41197711 and 41197712 have dropped significantly. Loading the BAM into IGV is showing 41197711 at 7847.

My use case here is I use a BED file to limit the samtools depth command to regions of interest but the reported depth for some positions is drastically different than the depth reported by IGV. I am trying to understand what exactly is going on here.

Thanks!

**Comment by jkbonfield** [comment]
Those numbers are suspiciously close to the default depth limit of 8000.

You'll want to increase it or do a subsample (eg `samtools view -s 0.1`) first.   We haven't got a good way yet to stop this cliff-edge effect when depth hits the limit.

**Comment by namiller2015** [comment]
Removing the depth limit did not have an impact. 
I will try a subsample next.

Is there somewhere I can read more about this cliff-edge effect? That appears to be what I am seeing happen.

I am on version 1.3.1.  I am working on getting access to the latest version but that is not easily done for institutional reasons.

**Comment by namiller2015** [comment]
subsampling seems to resolve this.

After running samtools view -s 0.1 input_bam -b > samtools_subsample.bam
I ran 
samtools depth -r chr17:41197700-41197712 samtools_subsample.bam 
chr17	41197700	1240
chr17	41197701	1240
chr17	41197702	1240
chr17	41197703	1227
chr17	41197704	1240
chr17	41197705	1240
chr17	41197706	2071
chr17	41197707	2071
chr17	41197708	2071
chr17	41197709	2021
chr17	41197710	2068
chr17	41197711	839
chr17	41197712	839

Positions 41197711 and 41197712 have no longer fallen off the cliff. I will need to do more work and investigation to determine what fraction of subsampling is appropriate but this seems to be a valid method.

Thanks for all your help!

I would still be interested in reading more about the inner workings of the depth command and this cliff-edge effect if there is a good write up on it.

**Comment by jkbonfield** [comment]
Removing the depth limit would have worked too, but the syntax of -d0 meaning unlimited didn't exist way back in 1.3.  (I'd recommend upgrading.)  For that version you'd need something big like -d 999999
