### ISSUE TITLE
what is 'samtools view -X' ?

### ISSUE THREAD

**Issue by dadadawei** [samtools/samtools#1257]
I found samtools view -X in manual page, but the 'samtools view -h' can't find the parameter. I am using BSMAP to deal with the DNA methylation data, it needs samtools view -X.

**Comment by dpryan79** [comment]
That option hasn't existed in years, it produced a symbolic representation of the FLAG field.

**Comment by tseemann** [comment]
Actually seems like a useful flag for masochists like myself who still do `samtools view | less -S`

**Comment by dadadawei** [comment]
> That option hasn't existed in years, it produced a symbolic representation of the FLAG field.
thank you! so it doesn't need that option now？or there are any substitute options ？

**Comment by valeriuo** [comment]
What version of samtools are you using?

From the official manual [page](http://www.htslib.org/doc/samtools-view.html) of `samtools view`


> -X        Include customized index file as a part of arguments. See EXAMPLES section for sample of usage.

Also, `-h` is

> -h           Include the header in the output.
