### ISSUE TITLE
mpileup -d DEPTH is out by 1

### ISSUE THREAD

**Issue by jkbonfield** [samtools/samtools#126]
On a 9000 deep sample, doing samtools mpileup -d 8500 yields a depth of 8499. The documentation claims it is the maximum depth, so it should be 8500.

It also has in usage:
       -d INT          max per-BAM depth to avoid excessive memory usage [250]

However any value less than 8000 is increased to 8000 so the default of 250 is highly misleading.

**Comment by joelmartin** [comment]
i'm failing make test on what looks like this on branch develop.
cd test/mpileup && ./regression.sh mpileup.reg

=== Testing mpileup.reg regressions ===

UNEXPECTED FAIL: Output mismatch for $samtools mpileup -x -d 8500 -B -f mpileup.ref.fa deep.sam|awk '{print $4}'
See FAIL-47.out.1 vs expected/47.out

Expected   passes:   123
Unexpected passes:   0
Expected   failures: 0
Unexpected failures: 1
=> FAIL
make: *** [test] Error 1

diff ./test/mpileup/FAIL-47.out.1 ./test/mpileup/expected/47.out
1c1
< 8499
---
> 8500

**Comment by jmarshall** [comment]
@joelmartin This is most likely because your **htslib** is not up-to-date on its **develop** branch, and does not contain samtools/htslib@df4a80e9c387bb1d84cdb47c02e44e77b0f57770.
