### ISSUE TITLE
samtools view -Q to return reads < INT

### ISSUE THREAD

**Issue by JohnUrban** [samtools/samtools#1263]
Hi all. SAMtools is phenomenal. So before anything else, thanks a million.

#### Is your feature request related to a problem? Please specify.

- The problem is simply (potentially) a lack of a feature I need.
- samtools view allows filtering for MAPQ, but only in one direction: -q INT   only include reads with mapping quality >= INT [0]
- I need to extract reads with mapping quality < INT.
- My use case is to specifically target these low quality mapping reads for higher quality mapping.
- For now I am just using AWK on SAMs, but would love a SAMtools solution.

#### Describe the solution you would like.

It would be great if samtools view had a -Q (somewhat like -f vs -F).

-q INT   only include reads with mapping quality >= INT [0]
-Q INT   only include reads with mapping quality < INT [100]

Personally, I only need to extract reads with MAPQ < INT, but perhaps -q and -Q could also be used to slice out reads with MAPQ >= q and < Q. Of course that would also be possible with just unix piping given a -Q option.

Many thanks for considering my request, or thanks in advance for potentially alerting me to an already available solution.

**Comment by valeriuo** [comment]
We'll look into this. Also, you can always come up with a PR for this feature.

**Comment by jmarshall** [comment]
There is always `samtools view -q 20 -U lowquality.bam …`.

**Comment by valeriuo** [comment]
@JohnUrban `-U` option seems to be doing what you needed and can be applied to other conditions.

**Comment by JohnUrban** [comment]
Hi all - thanks for drawing my attention to `-U`.
