### ISSUE TITLE
"samtools view -D" don't work with "CR:Z" tag

### ISSUE THREAD

**Issue by mimi3421** [samtools/samtools#1267]
#### Are you using the latest version of [samtools](https://github.com/samtools/samtools/releases/latest) and [HTSlib](https://github.com/samtools/htslib/releases/latest)? If not, please specify.
(run `samtools --version`)

samtools 1.10
Using htslib 1.10
Copyright (C) 2019 Genome Research Ltd.

 #### Please describe your environment.
- OS (run `uname -sr` on Linux/Mac OS or ` wmic os get Caption, Version` on Windows)
- machine architecture (run `uname -m` on Linux/Mac OS or ` wmic os get OSArchitecture` on Windows)
- compiler (run `gcc --version` or `clang --version`)

windows 10 wsl , Linux 4.4.0-17763-Microsoft

gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
Copyright (C) 2017 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

#### Please specify the steps taken to generate the issue, the command you are running and the relevant output.

```
samtools view Hnor.bam -D CR:Z:UMI.txt | head
[output] samtools view: failed to open "Z:UMI.txt" for reading: No such file or directory
```

The bam file is generate from cellranger process, where UMIs are stored in tag CR:Z

Hnor.bam

```
A00174:24:HFTL2DSXX:4:1111:21169:28604  256     3       150615693       0       86M898272N65M   *       0       0      TAAAAGAGGATACAAACAAATGGAAGAACATTCCATGCTCATGGGTAGGAAGAATAAATATCGTGAAAATGGCCATACTGCCCAAGGTAATTTATAGATTCAATGCCATCCCCATCAAGCTACCAATGACTTTCTTCACAGAATTGGAAAA  FFFFFFFF:FFF:FFFFFFF:F:FFFFFFFF:FFFFFF:FFFF::FFFFFFFFFF,FF,F,:F:FFFFFF,:FFFFFFF:F:FF:FFFFFFFFFFF:F:FFFFF,F,F,F,FFFFFFF,FFF::FF::FF:FFF:FFFFFFFFF,,,FFFF NH:i:6  HI:i:2  AS:i:146        nM:i:0  RE:A:I  BC:Z:CCTCATTC   QT:Z::FFFF,FF   CR:Z:ACGGCCACAATCCAAC   CY:Z:FFFFFFFFF,FF:FFF   CB:Z:ACGGCCACAATCCAAC-1 UR:Z:GTACGTCGCG UY:Z:FF:FFFFFFF UB:Z:GTACGTCGCG RG:Z:xxx:MissingLibrary:1:HFTL2DSXX:4
```

UMI.txt

```
AAGCCGCTCAACGAAA
CAACCAAAGATAGTCA
CAGTCCTTCGTCACGG
CATCGGGAGTACACCT
CATTCGCAGCGCTCCA
CCATTCGGTAAGAGAG
CCGTACTGTATTAGCC
CTACGTCTCTTAGAGC
CTGGTCTGTGGCCCTA
GCAGTTATCTTCTGGC
GGACAAGAGTTCGCGC
```

**Comment by valeriuo** [comment]
The file argument should only contain the tag key (`CR`), excluding the value type (`Z`).
So `CR:Z:UMI.txt` should be `CR:UMI.txt`.
