### ISSUE TITLE
out-of-memory for samtools sort

### ISSUE THREAD

**Issue by xunchen85** [samtools/samtools#1271]
I am using samtools 1.10-31-g6e6d5f9, and i got the following error message. However i still get the sorted bam file. it looks like it is successfully sorted. And the sorted BAM file also can be indexed by using samtools index function.

BTW, my bam file is around 300 Gb, I use allocate the 128 Gb ram with 20 cores. So by default, we should have more than 6Gb per core which is significantly bigger than the default value.

I am wondering if the sorted BAM file is complete that i can carry out other analyses by using the sorted BAM.

#######
slurmstepd: error: Detected 1 oom-kill event(s) in step 36910599.batch cgroup. Some of your processes may have been killed by the cgroup out-of-memory handler
#######

#### Are you using the latest version of [samtools](https://github.com/samtools/samtools/releases/latest) and [HTSlib](https://github.com/samtools/htslib/releases/latest)? If not, please specify.
(run `samtools --version`)

 #### Please describe your environment.
- OS (run `uname -sr` on Linux/Mac OS or ` wmic os get Caption, Version` on Windows)
- machine architecture (run `uname -m` on Linux/Mac OS or ` wmic os get OSArchitecture` on Windows)
- compiler (run `gcc --version` or `clang --version`)

**Comment by jkbonfield** [comment]
You don't list the command line you are running.  Please provide this.

Note that most common memory error people encounter with sort is that the amount of memory specified with the `-m` parameter is *per thread*, so if you are using the `-@` parameter you'll have to work this sum out.

**Comment by xunchen85** [comment]
Thanks for your help.

It may be true, I can try it later on. I saw the default ram per thread is 768Mb. that is why I thought 128Gb ram with 24 threads is good enough. 

My question now is really if the generated sorted.bam is full or not, especially it still can be indexed without errors. 

This is the command line:
samtools sort -@ 24 input.bam -o input.sort.bam.
samtools index -@ 24 input.sort.bam

This is the full log:
[bam_sort_core] merging from 456 files and 24 in-memory blocks...
slurmstepd: error: Detected 1 oom-kill event(s) in step 36910599.batch cgroup. Some of your processes may have been killed by the cgroup out-of-memory handler.

**Comment by daviesrob** [comment]
`samtools quickcheck` may tell you if your bam file is complete.  If it reports a missing EOF block, it probably isn't.

For a better, but slower, check you could also run `samtools flagstat` on the input and output files.  Sort only changes the order of the reads, the counts should be the same. 

Are any of your reads very long?  When merging it needs to store one from each temporary file in addition to the sort blocks allocated at the start.  So it will grow, but not by that much for short reads.

**Comment by jkbonfield** [comment]
Ok so you're not changing the memory, so yes it ought to use no more than 20ish GB.

However, it's possible your system is set up to have a soft or hard mem limit per process, especially as it commented on cgroups.  `ulimit -a` will tell you the current memory limits.

Is this process being launched by a batch submission system?  If so make sure you submit the ulimit command so you can see whether the memory limits of batch jobs differs to your login shell.  (That's how our own local farm is set up.)

**Comment by xunchen85** [comment]
Thanks for your help.

I have check the ulimit -a, and it is unlimit for the memory;

I also run the samtools quickcheck, it do not have any output.

I deleted the BAM before sorting, but I may run the samtools flagstat for new samples. If I got the same read counts, it will indicate that the sorted.BAM is complete, right? Especially if can normally use samtools view, index... with the sorted.BAM file.

Thanks,

**Comment by xunchen85** [comment]
Hi,

with the error, I got identical number of reads by using samtools flagstat.

I just want to confirm if the sort.bam is correct.

Thanks,

**Comment by xunchen85** [comment]
BTW, after i add the parameter -m with 2G, the error message was gone.

Xun

**Comment by jkbonfield** [comment]
None of this is making much sense.  The default is -m 768M, less than 2G, so it ought to always use less memory.  The only difference is a lower -m will lead to more temporary files during merge, which in turn means less possible I/O cache.

I've had linux cgroups kill a cp command before because the I/O buffer cached used by the operating system was filling up with my large files and cgroups included it!  That was a rather broken system config.  It's possible, albeit unlikely, that a similar scenario is happening here.

This doesn't sound like a samtools issue per-se, but something you need to speak to your systems administrators about.  Given your mention of "36910599.batch cgroup" this is clearly some batch scheduling system with per-process conditions applied (cgroup), so that'll be under their control and they can inform you of the optimum amount of memory to request (not samtools may use a bit more, so maybe back it off by 30% of so to be safe), or how to adjust memory requests during job submission.

**Comment by jkbonfield** [comment]
Closing this as I'm certain it's not a samtools issue, but something in the system config.  Please reply if you get evidence otherwise.
