### ISSUE TITLE
samtools coverage meanings

### ISSUE THREAD

**Issue by a40129a** [samtools/samtools#1272]
Hello, when I use samtools coverage -m function, I can see a histogram. I want to ask how the y axis values (percentage) come from and what is the meaning of those values? 
                                                               Thank you

**Comment by tseemann** [comment]
Just an aside, `samtools coverage` is not in the `man samtools` page?

**Comment by a40129a** [comment]
I already read the document 
of samtools coverage ( http://www.htslib.org/doc/samtools-coverage.html), but I still a little confused about the y asxis meaning (in this website is from 0% to 24.19%).  Thanks

**Comment by valeriuo** [comment]
It's the percentage of covered positions from a particular bin.
The target region is divided into bins and the coverage for each position is computed. The y axis is the number of covered position in a bin divided by the bin width x 100.

**Comment by 0xaf1f** [comment]
I had this question too and didn't find the answer in the documentation and had to search open/closed issues until I finally found the answer here. @valeriuo it'd be really helpful if you could just add what you wrote here to the man page. 🙏 🙏 🙏

**Comment by jtoy7** [comment]
I have a similar question with regards to the -D option (--plot-depth). For some reason, the y-axis labels are all "0.0". My data has very low coverage and a lot of missing data, but from the plotted histograms it can be seen that the depth is clearly not zero. An example of my output is below. I assumed the y-axis is supposed to represent either the averaged or summed depth of all sites within the bin. Can you confirm which it is, or if it's something else entirely? Thanks!

`
>     0.0 |.   .                   :                         | Number of reads: 2065
>     0.0 |:.  :             :   :.:                         |
>     0.0 |::.::  .  ::  ..  :   :::     .     :             | Covered bases:   236.0Kbp
>     0.0 |:::::. : :::. ::  :   :::.:.. :     :           . | Percent covered: 0.9868%
>     0.0 |:::::: : :::: :: .:   ::::::: ::    :      .    : | Mean coverage:   0.00996x
>     0.0 |::::::::::::: ::::::.::::::::::::   :      :    : | Mean baseQ:      36.3
>     0.0 |:::::::::::::.::::::::::::::::::: ..: .  . :    : | Mean mapQ:       38
>     0.0 |:::::::::::::::::::::::::::::::::.:::::  : ::   : |
>     0.0 |::::::::::::::::::::::::::::::::::::::: :: :::..: | Histo bin width: 478.4Kbp
>     0.0 |::::::::::::::::::::::::::::::::::::::: ::::::::::| Histo max cov:   0.017849
          1       4.78M     9.57M     14.35M    19.14M     23.92
`
