### ISSUE TITLE
samtools 1.10 cat SIGSEGV 

### ISSUE THREAD

**Issue by EdHarry** [samtools/samtools#1276]
#### Are you using the latest version of [samtools](https://github.com/samtools/samtools/releases/latest) and [HTSlib](https://github.com/samtools/htslib/releases/latest)? If not, please specify.
(run `samtools --version`)

samtools 1.10
htslib 1.10.2
(from bioconda)

 #### Please describe your environment.
- OS (run `uname -sr` on Linux/Mac OS or ` wmic os get Caption, Version` on Windows)
- machine architecture (run `uname -m` on Linux/Mac OS or ` wmic os get OSArchitecture` on Windows)
- compiler (run `gcc --version` or `clang --version`)

Linux 4.15.0-99-generic
x86_64

clang version 10.0.0 (https://github.com/llvm/llvm-project.git 24ec80425acc140e919d6718b303ca13b32b8e36)
Target: x86_64-unknown-linux-gnu
Thread model: posix

#### Please specify the steps taken to generate the issue, the command you are running and the relevant output.

samtools cat (version 1.10) seg faults when operating on two cram files.
```fish
> samtools cat -o tmp.cram test_1.cram test_2.cram
fish: 'samtools cat -o tmp.cram test_1…' terminated by signal SIGSEGV (Address boundary error)

> samtools --version
samtools 1.10
Using htslib 1.10.2
Copyright (C) 2019 Genome Research Ltd.
```

The same command on the same files runs fine using samtools version 1.9

```fish
> samtools cat -o tmp.cram test_1.cram test_2.cram

> samtools --version
samtools 1.9
Using htslib 1.9
Copyright (C) 2018 Genome Research Ltd.
```

The two cram files can be found on the Sanger nfs server at
```fish
/nfs/team117_rnd/eh15/Samtools_1.10_cat_crash/
```
(the files are samples of unaligned reads from the ToL project, and I'm not 100% sure of the data sharing policy in place so I won't share the data publicly until I know otherwise)

**Comment by jkbonfield** [comment]
Confirmed.  It works with 1.9 so this is a new bug.  Thanks for the report.

**Comment by valeriuo** [comment]
Looks like `cram_block_compression_hdr::codecs[DS_CF]` is not properly initialized.

**Comment by valeriuo** [comment]
@EdHarry Thanks for the report and the data!

**Comment by EdHarry** [comment]
> @EdHarry Thanks for the report and the data!

No problem
