### ISSUE TITLE
Confusing long options and defaults for quality filtering in samtools-coverage

### ISSUE THREAD

**Issue by kaspernie** [samtools/samtools#1278]
#### Is your feature request related to a problem? Please specify.

A user could risk filtering on the unintended quality measure as long options and descriptions indicate something different in the help menu. The man page has agreement but is wrong compared to program behaviour.

**From help menu:**

```
  -q, --min-MQ INT        base quality threshold [0]
  -Q, --min-BQ INT        mapping quality threshold [0]

```
**From man samtools-coverage:**

```
       -q, --min-MQ INT
               Minimum mapping quality for an alignment to be used [0]

       -Q, --min-BQ INT
               Minimum base quality for a base to be considered [13]
```
Actual behaviour seems to agree with the help menu, even if it confusing that "--min-MQ" is used for base quality threshold.

#### Describe the solution you would like.

- "--min-MQ" should be used for mapping quality and "--min-BQ" should be used for base quality.
- The base quality default indicated in the man page should be 0 and the options should agree with program behaviour (and help menu) .
 
(I acknowledge that it is not easy to pick good short options among "-q" and "-Q",  as they are already inconsistent between existing samtools subcommands.)

**Comment by valeriuo** [comment]
Thanks for the report!
