### ISSUE TITLE
Samtools mpileup information

### ISSUE THREAD

**Issue by Clement-BIRBES** [samtools/samtools#1282]
#### Are you using the latest version of [samtools](https://github.com/samtools/samtools/releases/latest) and [HTSlib](https://github.com/samtools/htslib/releases/latest)? If not, please specify.
Latest version, 1.10

 #### Please describe your environment.
- OS: Linux 3.10.0-514.26.2.el7.x86_64
- machine architecture : x86_64
- compiler : gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-11)

#### Please specify the steps taken to generate the issue, the command you are running and the relevant output.
Using samtools mpileup to get indel information in specific area of my genome with the following command : 

`samtools mpileup -a -f assembly.racon1.fa map.polisher.sorted.bam > mpileup_output.tsv`

And tit seems that there is a problem with the number of reads in column 4. I tried to find exactly how mpilup count the number of reads, and seen some other closed issues talking about numerotation problem.

A concrate case of the problem :
From position 25269 to position 25292 of my genome, i know i have much more deletion. I want to count this deletion to delete a part of this region.
When i'm watching an IGV representation, i find 50 deletion area containing 352 base over 52 reads (Image bellow).

![IssueMpileup](https://user-images.githubusercontent.com/39647753/86933887-59ad9200-c13b-11ea-943a-2ee0abba3cea.png)

When i'm watching the same area with samtools mpileup i get the following information :

> ctg1	25268	C	32	,-8aaaaaaaa,-4aaaa,..-16AAAAAAAAAAAAAAAA,..-7AAAAAAA.-10AAAAAAAAAA.-4AAAA,-6aaaaaa,-6aaaaaa,-3aaa.-2AA,,-6aaaaaa.,..,-1a,.-6AAAAAA,-4aaaa,-10aaaaaaaaaa,-6aaaaaa..-3AAA.-2AA,-7aaaaaaa,-6aaaaaa,	519>.9</4636.=6:@7==83868;:9:;9<
> ctg1	25269	A	8	,,.,...,	//>..0/.
> ctg1	25270	A	1	.	@
> ctg1	25271	A	1	.	C
> ctg1	25272	A	1	.	@
> ctg1	25273	A	1	.	@
> ctg1	25274	A	1	.	<
> ctg1	25275	A	1	.	<
> ctg1	25276	A	1	.	;
> ctg1	25277	A	1	.	;
> ctg1	25278	A	1	.	8
> ctg1	25279	A	1	.	9
> ctg1	25280	A	1	.	6
> ctg1	25281	A	1	.	7
> ctg1	25282	A	1	.	6
> ctg1	25283	A	1	.	9
> ctg1	25284	A	1	.	7
> ctg1	25285	A	1	.	8
> ctg1	25286	A	1	.	6
> ctg1	25287	A	1	.	8
> ctg1	25288	A	2	..	.6
> ctg1	25289	A	3	.,.	0.6
> ctg1	25290	A	3	.,.	1/6
> ctg1	25291	A	6	....,.	4.</..
> ctg1	25292	C	20	,,..,.,..,.,.,,...,,	289692..764673;7?.:=
> ctg1	25293	C	21	..,.,-1t..,.,.,,,...,.,,	/83:..1363:./56.>/136

which indicate (if i'm right), only 117 deletion. There are several things I don't understand:
First, why there is only 32 reads identified in position 25268; 8 position 25269 and 1 unique reads after that.
then why the number of reads decreases so much? isn't this number supposed to be the number of reads per position?

Sorry if the issues already exist or if i missed something.

**Comment by Clement-BIRBES** [comment]
After reading mpileup parameter once again, i found 
-Q, --min-BQ INT    Minimum base quality for a base to be considered [13] 

I changed Q to 0 and i think my problem is solved, i have the 52 reads found in this region.

Nevertheless, sometimes there is not a perfect matching between what IGV shows and the result given by mpileup, I suppose it comes from a different way of reading BAM?

For example on position 25269 there are 33 reads with a deletion with IGV, for 34 with mpileup:

> ctg1	25269	A	52	.***C,.**,.**********t,*.,.**.*,*.****.**.*****.***,	!!!!+/-!!--!!!!!!(!!!$/!>..!$0!-!,#!!!!!!/!!!!!!!!!.

**Comment by valeriuo** [comment]
Yes, unexpected results often come down to default values, and for mpileup the base quality threshold would be the first to fiddle with. 
On the other hand, I can see the read (no. 31) where mpileup differs from IGV for position 25269. Can we have a look at your data to speed up the investigation?

**Comment by Clement-BIRBES** [comment]
How can i share you the bam file / mpileup file ?

**Comment by valeriuo** [comment]
I only need the BAM file. If you don't want to share it with GitHub, you can email me the link at vo2@sanger.ac.uk.
Otherwise, you can just drag the file into the text box.

**Comment by valeriuo** [comment]
The extra deletion in the **mpileup** output comes from the 31st read (**read_4505605**), after comparing the visual output of both applications:

```
read_6744515    0       ctg1    1001    60
read_6850302    16      ctg1    1042    60
read_9494343    16      ctg1    7434    60
read_4186569    16      ctg1    7784    60
read_9494343    2048    ctg1    7999    60
read_9709241    16      ctg1    8555    60
read_6533289    0       ctg1    10215   60
read_2344328    0       ctg1    10669   60
read_435690     0       ctg1    10778   60
read_9950556    16      ctg1    10985   60
read_5416030    0       ctg1    11743   60
read_1722853    0       ctg1    11893   60
read_10304908   0       ctg1    12287   60
read_2659037    0       ctg1    12974   60
read_12269143   16      ctg1    12995   60
read_1959307    16      ctg1    13459   60
read_10651602   16      ctg1    13815   60
read_1748353    0       ctg1    14633   60
read_1749344    16      ctg1    14633   60
read_10144113   0       ctg1    15555   60
read_4122909    0       ctg1    15810   60
read_4855384    16      ctg1    15995   60
read_7438289    16      ctg1    16212   60
read_12008543   16      ctg1    17820   60
read_7245982    0       ctg1    18544   60
read_6596041    16      ctg1    18628   60
read_12551166   0       ctg1    18787   60
read_2672349    16      ctg1    18815   60
read_6895535    0       ctg1    18954   60
read_4526264    0       ctg1    19276   60
read_4505605    16      ctg1    20018   60 <-
read_4452119    16      ctg1    20216   60
read_10408978   0       ctg1    20247   60
read_8939488    0       ctg1    20478   60
read_2288611    16      ctg1    21002   60
read_10319876   16      ctg1    21057   60
read_8950858    16      ctg1    21542   60
read_1298350    16      ctg1    21952   60
read_4324445    0       ctg1    22207   60
read_4324445    2064    ctg1    22207   60
read_13432700   16      ctg1    22779   60
read_7480673    0       ctg1    22784   60
read_12578045   0       ctg1    23007   60
read_12951451   0       ctg1    23539   60
read_7339213    0       ctg1    23699   60
read_5952925    16      ctg1    24166   60
read_4011117    16      ctg1    24576   51
read_13377232   0       ctg1    24995   60
read_1781528    0       ctg1    25009   60
read_4627187    16      ctg1    25211   60
read_5611410    16      ctg1    25226   60
read_6787780    16      ctg1    25251   60
```

After examining the CIGAR string of this read, the deletion is clearly visible at the reference position 25269:

![CIGAR_25269](https://user-images.githubusercontent.com/6553979/89173519-4f38b980-d57c-11ea-9b9d-a561cd0d652a.png)

`samtools tview` is also in agreement with mpileup. So there appears to be a problem with the IGV output.

![tview_25269](https://user-images.githubusercontent.com/6553979/89173856-ca9a6b00-d57c-11ea-8bb8-ef1c167d47c5.png)
