### ISSUE TITLE
SAMtools [E::hts_open_format] Failed to open file

### ISSUE THREAD

**Issue by zoeluo15** [samtools/samtools#1289]
#### Are you using the latest version of [samtools](https://github.com/samtools/samtools/releases/latest) and [HTSlib](https://github.com/samtools/htslib/releases/latest)? **SAMtools/1.10-GCC-9.2.0**
(run `samtools --version`)

 #### Please describe your environment.
- OS (run `uname -sr` on Linux/Mac OS or ` wmic os get Caption, Version` on Windows) **Linux 3.10.0-693.2.2.el7.x86_64**
- machine architecture (run `uname -m` on Linux/Mac OS or ` wmic os get OSArchitecture` on Windows) **x86_64**
- compiler (run `gcc --version` or `clang --version`) **gcc (GCC) 9.2.0**

#### Please specify the steps taken to generate the issue, the command you are running and the relevant output.
I am trying to randomly sample 22% reads from the cram file (seed being 1). Here is the command I tried:

`samtools view -b -s 1.22 -T /mypath/reference.fasta /mypath/MappedReads/sample01.cram > /mypath/2xCoverageReads/sample01_2fold.bam`

and I got the following error

```
[E::hts_open_format] Failed to open file "/mypath/MappedReads/sample01.cram" : No such file or directory
samtools view: failed to open "/mypath/MappedReads/sample01.cram" for reading: No such file or directory
```

There is no spelling mistake and the file does exist in the directory, I am not sure what is causing the problem.

Any help would be greatly appreciated!

Zoe

**Comment by valeriuo** [comment]
The error comes from the OS call. Is `/mypath` on a mounted drive? If yes, can you try creating a symbolic link to your file in your local filesystem and use the link in your samtools command?

**Comment by zoeluo15** [comment]
Hi Valeriu, `/mypath` is on a cluster file system, and my cram files are symlinks. Cheers, Zoe

**Comment by jkbonfield** [comment]
Samtools sometimes is poor at giving the wrong error message.  It may be that it opens the CRAM but then fails to open something else and that's the cause of the "no such file or directory".  You can try using strace to see what system calls are happening.  For example:

```
$ strace samtools view /tmp/p30.cram 2>&1 | egrep -A10 '\.cram'
openat(AT_FDCWD, "/tmp/p30.cram", O_RDONLY) = 3
fstat(3, {st_mode=S_IFREG|0644, st_size=6072460, ...}) = 0
brk(NULL)                               = 0x15d6000
brk(0x15f7000)                          = 0x15f7000
read(3, "CRAM\3\0/tmp/p30.cram\0\0\0\0\0\0\0\223#\0\0\0\0"..., 4096) = 4096
read(3, "\nU\314\34D\n\255\252.\221\220}w#\262e\243\271\365\375\360\2575\253\331\207r}O\205\222J"..., 4096) = 4096
read(3, "\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0"..., 4096) = 4096
brk(0x1618000)                          = 0x1618000
brk(0x1639000)                          = 0x1639000
fstat(1, {st_mode=S_IFIFO|0600, st_size=0, ...}) = 0
brk(0x1665000)                          = 0x1665000
read(3, "\377\206\230\376N5L\232\223\22\234\362\345,\7E\320%\212V\261\345\315.\242O\"\324\4\204\3514"..., 50272) = 50272
read(3, "\221\334\r9\4\4\f\307.\321\317B@\1\310.\7\0@B\17\0\0\7\200\272\31\200\272\32\1\200"..., 4096) = 4096
mmap(NULL, 471040, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7ffba151b000
read(3, "\352\35\30Q5\353\36JM\277\264|i \243@\346x4\341\36\326\16\331\232\3330a&\317\302u"..., 466654) = 466654
```

That shows the CRAM file being opened, returning file descriptor 3 (it'd be -1 if it errored).

You could also try using `egrep ENOENT` instead.  You'll likely see lots of harmless things while the program and libraries speculatively look for things, but in there somewhere should be the smoking gun.  The example output is something like this (harmless in this case):

```
access("/etc/ld.so.nohwcap", F_OK)      = -1 ENOENT (No such file or directory)
```

**Comment by daviesrob** [comment]
If the cram files are symlinks, the first thing to try would be `ls -lL /mypath/MappedReads/sample01.cram` to check that the link is pointing to something that exists.  Also `head -c 4 /mypath/MappedReads/sample01.cram` should print `CRAM`.

**Comment by zoeluo15** [comment]
> If the cram files are symlinks, the first thing to try would be `ls -lL /mypath/MappedReads/sample01.cram` to check that the link is pointing to something that exists. Also `head -c 4 /mypath/MappedReads/sample01.cram` should print `CRAM`.

Thank you! Just checked using `ls -lL` and found that the target files were removed. I have created new symlinks and it has no problem now :)
