### ISSUE TITLE
samtools index on a sam file core dumps

### ISSUE THREAD

**Issue by jkbonfield** [samtools/samtools#129]
I know it wasn't on my test list, but I just discovered this:

```
jkb@seq3a[work/samtools...] ./samtools index mpileup.1.sam
Segmentation fault (core dumped)
```

**Comment by jmarshall** [comment]
Fixed by 9bbc79ec8d793705007e2141c8f9483b39a4b397, though the error message is not ideal for this one:

    $ samtools index test/mpileup/mpileup.1.sam
    [bam_index] corrupted or unsorted input file
