### ISSUE TITLE
Is it safe for multiple samtools processes to download to a shared hts-ref cache?

### ISSUE THREAD

**Issue by outpaddling** [samtools/samtools#1290]
I've been looking for info on the automatic reference download process.  All I've found is the "REFERENCE SEQUENCES" section in the samtools man page, which describes the env variables involved.

[http://www.htslib.org/doc/1.9/samtools.html](http://www.htslib.org/doc/1.9/samtools.html)

I'm about to run a large parallel job processing SRA CRAM files, and I've been unable to find information on whether it's safe for multiple samtools processes to download to a shared hts-ref cache.  I.e. does it use file locking to prevent two processes from writing the same reference file simultaneously?

This might be a good thing to mention in the docs, as many people run samtools on HPC clusters or multicore workstations.

If it is safe, a quick statement in the docs saying so would be nice.  If not, is there a workaround besides using a difference reference cache dir for each process, which would result in duplicate downloads?

Thanks,

    JB

**Comment by valeriuo** [comment]
Yes, each process downloads the reference into a temporary file that has its name made up of the pid, thread id and current time stamp. It then tries to rename the temporary file to the intended cache path.
We will add a note in the documentation about this aspect.

**Comment by jkbonfield** [comment]
Note this could still mean multiple processes downloading the same reference as it wasn't cached when they all started.  However only one will win.  The optimal strategy is probably to populate the ref cache first off, assuming you know the reference used upfront.

**Comment by daviesrob** [comment]
Note that in a cluster of machines, the combination of `PID` and time might not be unique.  To work around this, the temporary file is opened in exclusive mode so it should be OK as long as your shared filesystem does `O_EXCL` open correctly.  As @jkbonfield says above, the safest (and kindest to the EBI servers) solution is to pre-populate the cache before starting your batch job.

You could also try something like https://github.com/daviesrob/ref-cache-nginx, which is an [nginx](https://nginx.org/) configuration file designed to make it work as a caching proxy to the EBI server.  If you put the cache on a shared filesystem you can set `REF_PATH` to point to the cache directory first, then the nginx proxy server and (possibly) then the EBI as a back-stop.  That way you have a single process (nginx) responsible for writing to the cache directory which is likely to be safer.  Note that the configuration is likely to need manual changes to make it work at your site, and it may not prevent a thundering-herd problem to the EBI if lots of jobs start at the same time and all try to get a non-cached file.

**Comment by outpaddling** [comment]
Great ideas, thanks.

Processing 22 SRA CRAMs after moving the old cache dir out of sight seemed to indicate that there are only 24 references needed, all of which were downloaded while processing the first CRAM.  I'm guessing this means one per chromosome.  So it should be possible to prepopulate.  However, my old hts-ref cache contains 3332 files, even though I've only run samtools on these same 22 CRAM files on this machine.  Maybe EBI revises them frequently, resulting in new hash values for the same reference?

Regarding download collisions, have you considered using uuid() instead of PID/time to generate temporary filenames?

**Comment by jmarshall** [comment]
> have you considered using uuid() instead of PID/time to generate temporary filenames?

Is that in the C standard library? No? :smile: Rest assured that how to get entropy into the temporary filenames has been carefully considered.

**Comment by jkbonfield** [comment]
It's a storm in a tea cup frankly.  The chance of a whole series of collisions is minuscule.  Even if you have a snapshotted VM and all start up at the same time and all generate the same PIDs because of the nature of the snapshot, the elapsed time is simply *variable*.  That coupled with the test and retry cycle means it'll break ties very quick.

Try this program if you don't believe just how variable it is:

```
#include <time.h>
#include <stdio.h>
#include <sys/types.h>
#include <unistd.h>

int main(int argc, char **argv) {
    unsigned int t, t0 = 0;
    int i;
    for (i = 0; i < 10; i++) {
	t = clock();
	printf("%d %u\t%d\n", getpid(), t, t-t0);
	t0 = t;
    }
    return 0;
}
```

I know from benchmarking experiments just how hard it is to get even remotely the same timings out on modern processors, let alone something accurate to the microsecond!

**Comment by jkbonfield** [comment]
> Processing 22 SRA CRAMs after moving the old cache dir out of sight seemed to indicate that there are only 24 references needed, all of which were downloaded while processing the first CRAM. I'm guessing this means one per chromosome. So it should be possible to prepopulate. However, my old hts-ref cache contains 3332 files, even though I've only run samtools on these same 22 CRAM files on this machine. Maybe EBI revises them frequently, resulting in new hash values for the same reference?

There are 24 main chromosomes but 1000s of small unplaced contigs in the GRCh38 reference.  It's likely that's where these came from.  Try `samtools view -H | grep -c '^@SQ'` to count the number of SQ lines in the header.

The MD5 values don't get revised at all.   Once used they're the same forever.

**Comment by outpaddling** [comment]
> > have you considered using uuid() instead of PID/time to generate temporary filenames?
> 
> Is that in the C standard library? No? smile Rest assured that how to get entropy into the temporary filenames has been carefully considered.

Libuuid is highly portable and using it would be simpler and probably more robust than a home-grown solution, though the odds of a collision using PID and a high-resolution clock are miniscule.  I'm not concerned, it was just a suggestion.

**Comment by outpaddling** [comment]
> > Processing 22 SRA CRAMs after moving the old cache dir out of sight seemed to indicate that there are only 24 references needed, all of which were downloaded while processing the first CRAM. I'm guessing this means one per chromosome. So it should be possible to prepopulate. However, my old hts-ref cache contains 3332 files, even though I've only run samtools on these same 22 CRAM files on this machine. Maybe EBI revises them frequently, resulting in new hash values for the same reference?
> 
> There are 24 main chromosomes but 1000s of small unplaced contigs in the GRCh38 reference. It's likely that's where these came from. Try `samtools view -H | grep -c '^@SQ'` to count the number of SQ lines in the header.
> 
> The MD5 values don't get revised at all. Once used they're the same forever.

Thanks for that info, looks about right:
```
samtools view -H SRR6990379/NWD106206.b38.irc.v1.cram | grep -c '^@SQ'
3366
```
I'm at a loss as to why the contig refs ever got downloaded on my system, though.  I always run the same simple samtools view command and it always seems to download the same 24 refs.  The only thing that changes is the required_fields mask (0x208 or 0x608, depending whether I want to process PHRED scores:
```
samtools view -@ 2 --input-fmt-option required_fields=0x608 SRR6990379/NWD102903.b38.irc.v1.cram
```
Even running with no mask, I still get the same 24 files.

I might have run an mpileup and/or depth on this system a long time ago.  Do you know offhand what kinds of commands would download contig references?

Thanks much...

**Comment by jkbonfield** [comment]
It's anything that decodes sequence aligned against that chromosome.  Thus if you set a region to only contain one chromosome (or similarly several regions / a bed file) you'll only pull over those references.

It's likely they'll be in a big flurry at the end of the files, as they come after the primary chromosomes but are each individually quite small, so you wouldn't see them when debugging unless you let a program run to completion (and it doesn't have regions set to exclude them).

**Comment by outpaddling** [comment]
Thanks for the info.  What you said about regions makes sense.  I'll assume the other refs on my workstation came from playing with mpileup long ago.  I don't need them for my current analysis, so pre-populating my cloud instances will speed things up a bit.
