### ISSUE TITLE
setting up samtools to access s3 private bucket

### ISSUE THREAD

**Issue by slb10** [samtools/samtools#1291]
Hello,
I am very new to AWS services. I am trying to find a step-by-step guide for how to access bam files in a private s3 bucket. My current understanding is that I need to perform a configuration step so samtools can access the private bucket (?). Any help is greatly appreciated!

Thank you,
slb

**Comment by whitwham** [comment]
The most basic way to access AWS files from samtools is to add s3 to the front of the URL e.g.

`samtools view s3://mybucket/path/to/file`

This does assume you have a valid **~/.aws/credentials** (or equivalent) already set up.

Some details of the format are [here](http://www.htslib.org/doc/htslib-s3-plugin.html).

**Comment by slb10** [comment]
Thank you so much for your reply! How do I set up the ~/.aws/credentials (or equivalent). 

And for the format in the link your provided do i include the ":" in [ID[:SECRET[:TOKEN]]@]BUCKET/PATH ? I assume yes.

**Comment by whitwham** [comment]
> Thank you so much for your reply! How do I set up the ~/.aws/credentials (or equivalent).

This is not really a samtools thing, details on AWS credential files are [here](https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-files.html).

To briefly cover the basics; to access a private AWS bucket you need an aws_access_key_id (or just ID) and an aws_secret_access_key (or SECRET).  Usually you would put these in a credentials file looking something like this:

**[default]
aws_access_key_id=AKIAIOSFODNN7EXAMPLE
aws_secret_access_key=wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY**

> And for the format in the link your provided do i include the ":" in [ID[:SECRET[:TOKEN]]@]BUCKET/PATH ? I assume yes.

That is the full URL format and not often used.  Anything inside the square brackets is optional depending on what information you have to give.  If you have a credentials file then all you need do is the URL I gave you in my first example.  If you really wanted to type in your ID and secret code in every time it would look something like this:

`samtools view s3://AKIAIOSFODNN7EXAMPLE:wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY@/mybucket/path/to/file`

Do you have any other ways of looking at your files in AWS?  If so, then your credentials files should have already been set up.

**Comment by james-guevara** [comment]
Hi, I'm trying this command to access a private S3 bucket:

```
htsfile s3://<aws_access_key_id>:<aws_secret_access_key>@/an_s3_private_bucket_name/path/to/file
```

and it doesn't work. Am I missing anything?

**Comment by whitwham** [comment]
There should not be a **/** after the **@**.

`htsfile s3://<aws_access_key_id>:<aws_secret_access_key>@an_s3_private_bucket_name/path/to/file`

Yes, I know my example has one but it shouldn't.

Also, this issue was closed two years ago.  It would be better if you had created a new one.

**Comment by james-guevara** [comment]
Thanks for the response. I believed I tried that variant as well, but I will try again soon and create a new issue if I continue to have problems.
