### ISSUE TITLE
CRAM to fastq with provided reference fails 

### ISSUE THREAD

**Issue by kmavrommatis** [samtools/samtools#1292]
Using samtools 1.10 and trying to extract fastq files from CRAM

```
samtools fastq -s WGS.cram_singles.fastq.gz -0 WGS.cram_ambiguous.fastq.gz -1 WGS.cram_R1.fastq.gz -2 WGS.cram_R2.fastq.gz -@ 2 --reference /WholeGenome/genome.fa WGS.name.cram
```

I get the following error.

```

[W::cram_populate_ref] Creating reference cache directory /tmp/51243149-cbeb-46b9-ae03-628563e90f37/root/samtools_extract_fastq/.cache/hts-ref This may become large; see the samtools(1) manual page REF_CACHE discussion 
Failed to open reference "https://www.ebi.ac.uk/ena/cram/md5/f98db672eb0993dcfdabafe2a882905c": Input/output error 
[E::cram_decode_slice] Unable to fetch reference #1 10009..10173  
[E::cram_next_slice] Slice decode failure 
[bam2fq_mainloop] Failed to read bam record. 
[bam2fq_mainloop] Error writing to FASTx files.: Resource temporarily unavailable 
[M::bam2fq_mainloop] discarded 0 singletons 
[M::bam2fq_mainloop] processed 257603562 reads 
[W::find_file_url] Failed to open reference "https://www.ebi.ac.uk/ena/cram/md5/f98db672eb0993dcfdabafe2a882905c": Input/output error 
[E::fai_build3_core] Failed to open the file f98db672eb0993dcfdabafe2a882905c 


```

It appears that the tool is looking for the refence genome in the URL and is not using the provided reference genome, despite having the --reference argument.
Is this the expected behaviour? How can I override it and force to read the local genome sequence (and fail if there is a problem with it)?
The genome used in this case is custom, and the node running these commands does not have internet access.
Thanks in advance for your help

**Comment by valeriuo** [comment]
Can you verify that all the references contained in the CRAM file (`@SQ` lines) are also in the reference FASTA?

**Comment by kmavrommatis** [comment]
Yes, the reference genome has all the chromosomes referenced in the CRAM header and I confirmed that the md5 hashes match.
I found that I can process with the custom genome if I set REF_CACHE and REF_PATH to a local directory, and samtools don't try to access the ebi resource.

I am still testing this solution in a number of samples and will report back.

**Comment by SHuang-Broad** [comment]
I'd also add that the option `-T`, which is used for providing reference files with `samtools view`, is used for a different purpose with `samtools fastq`.
So I'd propose clarifying this in the [doc](http://www.htslib.org/doc/samtools-fasta.html) of `samtools fast`.

**Comment by arpanda** [comment]
I am also seeing the same type issue. Here is the command that I used.

```
samtools collate -@ 8 -u -O sample1.cram |  \
samtools fastq -@ 8 --reference hg38.fa -F 0x900 -1 sample1_R1.fq.gz -2 sample1_R2.fq.gz -0 /dev/null -s /dev/null -n -
```

For the above command, I am getting the below errors.

``` 
 [W::find_file_url] Failed to open reference "https://www.ebi.ac.uk/ena/cram/md5/2648ae1bacce4ec4b6cf337dcae37816": Network is unreachable
  [W::bgzf_read_block] EOF marker is absent. The input is probably truncated
  [M::bam2fq_mainloop] discarded 0 singletons
  [M::bam2fq_mainloop] processed 0 reads

```

I am not sure why it's looking for an external reference genome and other errors. Any suggestion to solve this issue?

**Comment by jkbonfield** [comment]
You are seeing another issue.  Please see the message carefully: "Network is unreachable"

This is likely true.  You could test it by doing

```
wget https://www.ebi.ac.uk/ena/cram/md5/2648ae1bacce4ec4b6cf337dcae37816
```
(or "curl" if wget isn't installed)

If this fails, then your problem is unrelated to samtools and needs fixing elsewhere.  If it is samtools specific, then please open a new ticket instead.  This one should probably have been closed some time ago as it's rather stale.
