### ISSUE TITLE
Longread mappings not fetched by coordinates

### ISSUE THREAD

**Issue by ViriatoII** [samtools/samtools#1294]
Hi,

I'm using samtools v1.10 and I think I detected a bug. When I try to view reads that map to an interest position like this:

`samtools view  mappings.bam   NC_024468.2:135440237-135440237`

I get 0 results. However, if I change the position from 135440237 to 135440000, I get 24 reads,  mapped to starting positions:
>135437441
>135437455
>135437456

all of the reads are larger than 4000 bps (pacbio reads), so they definitely cross over the position I am interested in. Why are they not fetched by my view command?

Cheers,
Ricardo

**Comment by jkbonfield** [comment]
Would you mind also quoting the CIGAR string for these reads also?  The sequence isn't necessary, but it is the combination of position + cigar which determines the read end and whether it overlaps the target region.

Thanks.

**Comment by ViriatoII** [comment]
Interesting, @jkbonfield , I wasn't aware of that.  These are different genotypes being mapped to a reference, so there will be structural variation, but that's exactly what I'm interested in studying. Is it possible to ignore the CIGAR string when fetching reads?

Here are the CIGAR strings:

> 4278H67M1I1595M4I150M2I10M1I12M1I34M4D12M3D10M1D106M60D13M1I256M5I35M5D11M1D38M1D119M1I40M1D172M567H
> 4278H67M1I1595M4I150M2I10M1I45M2D14M4D117M60D13M1I256M5I35M5D11M1D158M1I40M1D172M567H
> 1123S67M1I1595M4I150M2I10M1I10M1I35M2D14M4D117M60D13M1I256M5I35M5D11M1D158M1I40M1D172M823S
> 1875S67M1I1515M1D79M4I150M2I10M1I12M1D32M2D14M4D117M60D13M1I256M5I35M5D11M1D158M1I35M2S
> 931S67M1I1595M4I150M2I10M1I12M1I33M2D14M4D117M60D13M2I266M5I25M5D11M1D158M1I40M1D172M574S
> 1499S67M1I1595M4I150M2I10M1I12M1I33M2D14M4D117M60D13M1I256M5I35M5D11M1D158M1I40M1D172M317S
> 1498S67M1I797M1D797M4I150M2I10M1I45M2D14M4D117M60D13M1I195M1D60M5I35M5D11M1D158M1I40M1D172M317S
> 1435S67M1I1595M4I150M2I10M1I12M1I33M2D14M4D117M60D13M1I256M5I35M5D11M1D158M1I40M1D172M493S
> 5382H67M1I788M1I807M4I150M2I55M2D14M4D117M60D13M1I256M5I35M5D11M1D158M1I40M1D15M1I157M344H
> 1436S67M1I1595M4I150M2I10M1I45M2D14M4D117M60D13M1I256M5I35M5D11M1D158M1I40M1D172M493S
> 1498S67M1I1595M4I150M2I10M1I12M2I33M2D14M4D117M60D13M1I256M5I35M5D11M1D158M1I40M1D75M1I97M317S
> 4275H67M1I598M1D290M1D62M1I643M4I150M1I10M1I12M1I34M4D12M3D117M60D13M1I256M5I35M5D11M1D158M1I40M1D112M1D59M565H
> 2438S67M1I83M1I55M1I1303M1I154M4I150M2I22M1I33M2D14M4D117M60D13M1I256M5I35M5D11M1D158M1I40M1D75M1D96M1907S
> 1611S67M1I889M1I552M1I51M2I103M4I150M2I10M1I45M2D15M3D117M60D13M1I256M5I35M5D11M1D158M1I40M1D172M489S
> 1499S67M1I1073M1D11M1I510M4I150M2I10M1I45M2D14M4D117M60D13M1I256M5I35M5D11M1D158M1I40M1D172M317S
> 1499S67M1I1595M4I53M1D96M2I10M1I12M1I33M2D13M5D117M60D13M1I256M5I35M5D11M1D158M1I40M1D172M317S
> 1609S67M1I1595M4I150M2I10M1I45M2D14M4D117M60D13M1I256M5I35M5D11M1D158M1I40M1D172M489S
> 4601H67M1I1595M4I150M2I10M1I12M1I33M2D14M4D117M60D13M1I17M1D238M5I35M5D11M1D158M1I40M1D172M346H
> 3959H67M1I261M1D1048M1D284M4I150M2I10M1I12M1I33M2D14M4D117M60D13M1I256M5I35M5D11M1D158M1I40M1D172M292H
> 1907S67M1I224M1D1137M1D232M4I150M2I10M1I12M1I33M2D14M4D117M60D13M1I256M5I35M5D11M1D158M1I40M1D172M284S
> 2592S53M1I201M1D860M1I453M1I80M4I150M2I10M1I12M1I33M2D14M4D109M1D7M60D13M1I256M5I35M5D11M1D158M1I40M1D172M149S
> 445S45M1D7M1I839M1D233M1D521M4I94M1D53M3I12M1I12M1I33M2D14M4D117M60D13M1I192M1I64M5I35M5D11M1D110M1I48M1I40M1D172M828S
> 2531S52M1I766M1D293M1D166M1D367M4I29M1I121M2I22M1I33M2D14M4D117M60D13M1I256M5I35M5D11M1D158M1I40M1D172M296S
> 1557S52M1I729M1I209M1D656M4I18M1D131M2I10M1I12M1I33M2D14M4D117M60D13M1I266M5I25M5D11M1D158M1I40M1D172M273S

**Comment by jkbonfield** [comment]
The length of the reference is the M and D operations, with I (insertion) and S (soft-clip) being in the sequence but consuming no reference bases.  H can be ignored (hard clip).  Hence something like this will tell you the reference length:

```
perl -e 'while (<>) {s/(\d+)[SHIP]//g;$len=0;foreach(m/\d+/g) {$len+=$_};print "$len\n"}'
```

For your data, that gives lengths of 2756 mainly, meaning these sequence don't actually overlap the region you queried and samtools is working correctly.

There is no way to get it to "ignore" the cigar string as to do so is illogical.  Range queries are done by checking which bases overlap a region after it has been aligned to the reference sequence.  To ignore the cigar string is to ignore the alignment process, which makes no sense.  If you think the alignment is wrong, then you should change the cigar string, but that is highly unlikely.

**Comment by jkbonfield** [comment]
Note if you want to visualise what this means, try "samtools tview" or IGV if you prefer to see the sequences.  You will find the same thing there, as these tools operate in the same manner (POS + CIGAR).

**Comment by ViriatoII** [comment]
Ok, thank you for the explanation.   I understand better what is happening now. Part of the reads is unmapped due to a large difference with the reference (possibly an unconserved area), as visible in IGV:

![IGV](https://user-images.githubusercontent.com/25958099/88927284-7c812100-d277-11ea-85af-212112a3c434.png)


However, I went looking into the reads themselves and they continue into my position of interest, it's just completely different sequence:

Interest position --------------------------------------------------------------------------------------------------v
REF:  CAAAATAAAACGAAGATGATGTTGCAGCgtatagggatgaaaacggtcggtaaacactaaaactattaccgttt
Read:CAAAATAAAACGAAGATGAAGTTGCGACGGATATCAGGCAGCGGTTGGACACGCAGATCCGCCGTGCA
stops mapping here: ------------------------------------^_________________________________^ ------- interest position in read


I'm working with ccs PacBio reads, so I'm quite sure the read corresponds to reality, and I'm certain the read mapping is good.  So, if I am interested in this area of my mapped reads (which doesn't map to the reference) I have no way of easily accessing it with samtools?  

I know I'm complicating a bit, sorry, but I have dozens of interest positions and am creating an automated pipeline.

**Comment by jkbonfield** [comment]
If you're certain it's genuine sequence, then it's presumably either a large insertion not in the reference, or a structural rearrangement.  An alternative aligner may help, but not if it's a novel insertion - that'd need some denovo assembly.

There's no way to get this data back unless you enlarge the range query to pull out a wider range of data.

**Comment by ViriatoII** [comment]
Great, thanks for the help!
