### ISSUE TITLE
Samtools version of faidx returns multiple matches as it is not searching for exact matches. (1.7)

### ISSUE THREAD

**Issue by osowiecki** [samtools/samtools#1295]
Samtools Version: 1.7 (using htslib 1.7)

Samtools version of faidx returns multiple matches as it is not searching for exact matches.

Original faidx works fine.

faidx clust_K0_MERGED "1971"
```
>1971
CCCCTTCCCTCCCTCTACTGGGGCCCAGTCCACCGCCCACCCACCAGTTTCAACACATCACCATCACCACCAGCAACAGCAACAGCAGCAGCAGCAGCAGCAGCAGCAGCAGCAGCAGCAGCAGCAGCAGCAGCAGCAGCAGCAGCAGCAGCAGCAGCAGCAGCAGCAGCAGCAGCAGCAGCAGCAGCAGCAGCAGCAGCAGCAGCAGCAGCAGCAGCAGCAGCAGCATCACGGAAACTCTGGGCCCCCTCC
```

Samtools faids will mark 1971, 197122, 1971345 etc.

samtools faidx clust_K0_MERGED "1971"
```
>1971
CCCCTTCCCTCCCTCTACTGGGGCCCAGTCCACCGCCCACCCACCAGTTTCAACACATCA
CCATCACCACCAGCAACAGCAACAGCAGCAGCAGCAGCAGCAGCAGCAGCAGCAGCAGCA
GCAGCAGCAGCAGCAGCAGCAGCAGCAGCAGCAGCAGCAGCAGCAGCAGCAGCAGCAGCA
GCAGCAGCAGCAGCAGCAGCAGCAGCAGCAGCAGCAGCAGCAGCAGCATCACGGAAACTC
TGGGCCCCCTCC
```

Was this fixed in the latest release?

**Comment by valeriuo** [comment]
It's the same content in both snippets, just that in the second is wrapped in 60 character lines. You can increase this limit with the `-n` option and get the same result. This is the behaviour of the latest released version - [1.10](https://github.com/samtools/samtools/releases/tag/1.10), and it returns the exact match.

`samtools faidx -n 1000 clust_K0_MERGED 1971`
