### ISSUE TITLE
Failed to retrieve block whe using mpileup

### ISSUE THREAD

**Issue by mbhall88** [samtools/samtools#1297]
#### Are you using the latest version of [samtools](https://github.com/samtools/samtools/releases/latest) and [HTSlib](https://github.com/samtools/htslib/releases/latest)? If not, please specify.

Using samtools from latest biocontainers build `quay.io/biocontainers/samtools:1.10--h9402c20_2` i.e. v1.10

 #### Please describe your environment.
- singularity

#### Please specify the steps taken to generate the issue, the command you are running and the relevant output.

```
$ samtools mpileup -aa -o out.pileup --fasta-ref ref.fa in.bam
[mpileup] 1 samples in 1 input files
[E::fai_retrieve] Failed to retrieve block: unexpected end of file
[E::fai_retrieve] Failed to retrieve block: unexpected end of file
```
The last line continues forever and I have to kill the job.

I have tried running both the BAM and fasta through various samtools (and other tools) commands and there doesn't seem to be a problem with their formatting...

PS the BAM is indexed with `samtools index`  
PPS the same thing happens when I run it locally

**Comment by daviesrob** [comment]
It looks like samtools is trying to read beyond the end of your `ref.fa` file (or at least thinks that it is).  You could try renaming your current `ref.fa.fai` file, then reindex with `samtools faidx ref.fa` and compare the new `ref.fa.fai` file with the old one to see if they're the same.

Presumably `out.pileup` contains data up to the point where `samtools mpileup` stopped working.  Can you use `samtools faidx` to successfully get regions of `ref.fa` around that area?

**Comment by mbhall88** [comment]
Ah. of course, silly me. The log clearly stats fai_retrieve. I was focused on the wrong index. Indeed, the faidx for the fasta was old and needed updating. After reindexing it all worked. Thanks @daviesrob !!
