### ISSUE TITLE
mpileup -l and -r have differing requirements

### ISSUE THREAD

**Issue by jkbonfield** [samtools/samtools#130]
I can run mpileup -l region-list on BAM, SAM and CRAM; even on raw SAM with no tabix index (does such a thing exist btw?).

However mpileup -r region only works on BAM.  Can we not encode one in terms of the other?  Obviously this is a defect as -r should work on CRAM at least.

**Comment by jmarshall** [comment]
@jkbonfield to add documentation now that he knows the details.

**Comment by jkbonfield** [comment]
Fixed by 03a6bc5
