### ISSUE TITLE
mpileup on multiple regions

### ISSUE THREAD

**Issue by Clement-BIRBES** [samtools/samtools#1304]
#### Describe the solution you would like.

Hello, 
I am trying to implement mpileup in a pipeline and would like to know if it is possible to specify multiple chromosomes with the -r option.

Currently I am splitting my analysis into chromosomes but I would like to be able to split by chromosome group.

Is there a way to specify this for mpileup / a technique to do this?

**Comment by valeriuo** [comment]
You can put multiple regions in a BED file and pass it to the mpileup command with the `-l, --positions FILE` option.
The option `-r` only accepts a single region (interval).
More [here](http://www.htslib.org/doc/samtools-mpileup.html).

**Comment by Clement-BIRBES** [comment]
can a simple file with

```
ctg23    1
ctg24    1
```

run mpileup only on the contigs 23 and 24 of my assembly ?
I tried it but mpileup hang

**Comment by valeriuo** [comment]
The [BED format](http://www.genome.ucsc.edu/FAQ/FAQformat.html#format1) expects at least three columns per row, the reference name, the 0-based start coordinate and the end coordinate. For whole chromosomes, use a large end coordinate (1000000000). So that would be:

```
ctg23    0    1000000000
ctg24    0    1000000000
```

**Comment by Clement-BIRBES** [comment]
I tried your solution on my test data using the follow command :

`samtools mpileup -a -Q 0 -l ctg.bed -o test.tsv map.polisher.sorted.bam`

and ctg.bed :
ctg17   0       1000000000
ctg18   0       1000000000

columns are tab-separated.

after 30 minut the output is still empty.
Is there something i'm doing wrong ?

**Comment by Clement-BIRBES** [comment]
Thanks, it worked perfectly !

**Comment by jkbonfield** [comment]
Unfortunately using `-l in.bed` doesn't use an index as that's not how it was intended.  The expectation was -r for gross region query, with random access (ie index) and then -l for streaming and on-the-fly filtering by bed region, which doesn't use the index.

We still need to rationalise our index usage here.
