### ISSUE TITLE
samtools fastq produces incorrect CASAVA entry for paired end reads

### ISSUE THREAD

**Issue by mattsoup** [samtools/samtools#1307]
#### Are you using the latest version of [samtools](https://github.com/samtools/samtools/releases/latest) and [HTSlib](https://github.com/samtools/htslib/releases/latest)? If not, please specify.
(run `samtools --version`)
samtools 1.10
Using htslib 1.10.2

 #### Please describe your environment.
- OS: Linux 4.15.0-101-generic
- machine architecture: x86_64
- compiler: gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0

#### Please specify the steps taken to generate the issue, the command you are running and the relevant output.
I have two bams, one with paired end reads and one with single end reads. In converting the bams to fastq, the CASAVA string is not generated correctly. The following command:

`samtools fastq -i -n --index-format i*i* paired_end.bam`

produces the following fastq headers:

```
@000000000-J6TR3:1:1114:10046:5478 1:N:0:CAGGTAAG+CTCGAAAT+CAGGTAAG+CTCGAAAT
@000000000-J6TR3:1:1114:10046:5478 2:N:0:CAGGTAAG+CTCGAAAT+CAGGTAAG+CTCGAAAT

```
in which the barcode pairs are repeated twice. The BC:Z tag for these reads is:

`BC:Z:CAGGTAAG-CTCGAAAT`

The same command for a single ended bam produces the expected output:

`@000000000-J6TR3:1:1114:10046:5478 1:N:0:CAGGTAAG+CTCGAAAT`

The expected output is also generated for singletons if I remove their corresponding pair in the paired end bam. I believe this can be fixed by changing line 455 of bam_fastq.c from:

`if (action=='i' && *sub_tag) {`

to

`if (action=='i' && *sub_tag && rec->core.flag & BAM_FREAD1) {`

so that the CASAVA string is only appended to on the read 1 pass, rather on both read 1 and read 2.

**Comment by daviesrob** [comment]
#1309 should have fixed this, and works if the `BC:Z:` tag is on only read1, only read2, or both of them.
