### ISSUE TITLE
samtools sorted

### ISSUE THREAD

**Issue by Mewgia** [samtools/samtools#1310]
Dear colleagues,
could you please help me a little? I try to do this:

bowtie2-build \
/media/bobii/ADATA_HD680/135_3_transcriptome/matrix/135_chr_pl_all_without.fasta \
/media/bobii/ADATA_HD680/135_3_transcriptome/bowtie/135_chr_pl_all_without

bowtie2 -p 8 \
-x /media/bobii/ADATA_HD680/135_3_transcriptome/bowtie/135_chr_pl_all_without \
-1 /media/bobii/ADATA_HD680/135_3_transcriptome/24_S23_L001_R1_001.fastq.gz \
-2 /media/bobii/ADATA_HD680/135_3_transcriptome/24_S23_L001_R2_001.fastq.gz \
-S /media/bobii/ADATA_HD680/135_3_transcriptome/bowtie/135_chr_pl_all_without.sam

samtools view -bS -@ 8 \
/media/bobii/ADATA_HD680/135_3_transcriptome/bowtie/135_chr_pl_all_without.sam > \
/media/bobii/ADATA_HD680/135_3_transcriptome/bowtie/135_chr_pl_all_without.bam

samtools sort -@ 8 \
/media/bobii/ADATA_HD680/135_3_transcriptome/bowtie/135_chr_pl_all_without.bam \
-o /media/bobii/ADATA_HD680/135_3_transcriptome/bowtie/135_chr_pl_all_without_s.bam

And the last operation breaks with an error. Instead the result I see that (pic). What I do wrong?
![pic](https://user-images.githubusercontent.com/52279695/92490317-8b091380-f1f9-11ea-9f2d-f8717009391f.png)

Thank you.

**Comment by valeriuo** [comment]
> And the last operation breaks with an error.

What is the error?

**Comment by daviesrob** [comment]
It looks like you tried to print out a bam file.  Are you using a very old version of samtools?  Before version 1.0 it had a different meaning for the `-o` option which would give the result you got.

I would recommend that you install the latest release of samtools as it will be faster and more reliable than the old version you seem to have.  It will also be able to read the sam file directly when sorting, so you can skip the "samtools view" step.
