### ISSUE TITLE
samtools view doesn't use /%2s/%2s/%s convention when looking for references in a local cache

### ISSUE THREAD

**Issue by yfarjoun** [samtools/samtools#1312]
```
$ samtools --version                                                                                                                                     
samtools 1.10
Using htslib 1.10.2

$ uname -a
Darwin wmc0a-d30 19.6.0 Darwin Kernel Version 19.6.0: Sun Jul  5 00:43:10 PDT 2020; root:xnu-6153.141.1~9/RELEASE_X86_64 x86_64

$ gcc --version
Configured with: --prefix=/Library/Developer/CommandLineTools/usr --with-gxx-include-dir=/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/4.2.1
Apple clang version 11.0.3 (clang-1103.0.32.62)
Target: x86_64-apple-darwin19.6.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
```

I ran seq_cache_populate.pl which generated a "tree" of references:

```
$  ls -1 -R | tail -n 20
./ff/55:
b1b730eb936e0ffca09b8fff9a89

./ff/5f:
2aa407bb1f0573a4d815fb69f917

./ff/65:
2624b7319ee60f8946d8f751cf16

./ff/a1:
cdc44c405e284e6f51859e1c2b36

./ff/c2:
9d2524335853c556eac4b936ac47

./ff/cd:
631ed0bf56e54cd72ed51c70fa3c

./ff/df:
636f8835c8e1937d8ea6f631688c
```

but when running `samtools view` it ignored the directory structure and added files to the same cache in a different format:

```
$ ls -1 f7f0* f7/f0
f7f05fb7ceea78cbc32ce652c540ff2d

f7/f0:
5fb7ceea78cbc32ce652c540ff2d
```

I was expecting that samtools would use the results of the perl script....

**Comment by yfarjoun** [comment]
@jmarshall

**Comment by jmarshall** [comment]
Are there any `REF_PATH` and `REF_CACHE` environment variables set, and if so what are their values? If you crank up the verbosity with `samtools view --verbosity 4` or more, it will say a little more about what cache files it is reading/writing.

But it's not clear from your report who's writing what and when. When did the different _f7…40ff2d_ files appear?

As for people knowledgeable about these areas: @daviesrob for _seq_cache_populate.pl_ and @jkbonfield for CRAM reference loading.

**Comment by yfarjoun** [comment]
I was inside the `cache` directory when I issues the `ls` commands.
REF_CACHE=cache
REF_PATH was either '/' to force samtools to use the cache or unset to allow it to access refget.

the pl script made the tree-structure and samtools looks for the md5s in a flat structure.

Sorry about the inaccurate @mentioning.

**Comment by jmarshall** [comment]
Any md5 digits unused after `%` expansions are appended at the end of the expanded cache filename, so I suspect that REF_CACHE setting is equivalent to `cache/%s` thus flat.

Probably `REF_CACHE=cache/%2s/%2s/%s` or so will better reflect the structure made by _seq_cache_populate.pl_, as discussed in the documentation at the end of the script.

**Comment by yfarjoun** [comment]
aha! I didn't understand that special format...thanks.

**Comment by jkbonfield** [comment]
Indeed @jmarshall is correct it in automatically appending any remaining md5 chars to the end of the path if not explicitly covered already in the percent rules.  I do wonder if we could go the extra mile and make it auto-detect, albeit less efficiently.  Eg if the stat fails, but the common idiom of %2s/%2s/%s works, then use it (given the default for `misc/seq_cache_populate.pl` is subdirs=2).

Alternatively `misc/seq_cache_populate.pl` should explicitly print up the required REF_CACHE setting to utilise its output.  That would go a long way to explaining the nuances of the caching system.

**Comment by jmarshall** [comment]
This has basically been a documentation failing: this is all more or less documented, but @yfarjoun hasn't found that information. Possibly the _seq_cache_populate.pl_ documentation could be moved to a manual page or at least pointed to more from the existing REF_CACHE etc manual page section. I see there is already a [REF_PATH/REF_CACHE](https://www.htslib.org/workflow/#the-ref_path-and-ref_cache) section on the web site, which could be reviewed or pointed to from the manual pages.

The _seq_cache_populate.pl_ script already prints out some log messages, so having it also print out a suitable corresponding `REF_CACHE` setting is an excellent idea. And perhaps it could also print out the URL of the web page discussion.

**Comment by jkbonfield** [comment]
Hopefully addressed by https://github.com/samtools/samtools/pull/1313

I haven't changed the htslib code at all, so this is just documentation / diagnostics.
