### ISSUE TITLE
can not get the bam files using pipeline bwa mem | samtools view -Sb

### ISSUE THREAD

**Issue by Zhenwen-camellia** [samtools/samtools#1327]
#### Are you using the latest version of [samtools](https://github.com/samtools/samtools/releases/latest) and [HTSlib](https://github.com/samtools/htslib/releases/latest)? If not, please specify.
(run `samtools --version`)
I am using the 1.7v
 #### Please describe your environment.
- OS (run `uname -sr` on Linux/Mac OS or ` wmic os get Caption, Version` on Windows)
- machine architecture (run `uname -m` on Linux/Mac OS or ` wmic os get OSArchitecture` on Windows)
- compiler (run `gcc --version` or `clang --version`)
environment is x86_64 on Linux
##### input command:
bwa mem -M -K 10000000 -t 12 -R "@RG\tID:A_YNJC_2400\tSM:A_YNJC_2400\tPL:Illumina" DASZ_complete_genome.fa A_YNJC_2400_1.fq.gz A_YNJC_2400_2.fq.gz | samtools sort -@ 12 -m 4G -o ./out/A_YNJC_2400.bam - 
#### or
bwa mem -M -K 10000000 -t 12 -R "@RG\tID:A_YNJC_2400\tSM:A_YNJC_2400\tPL:Illumina" DASZ_complete_genome.fa A_YNJC_2400_1.fq.gz A_YNJC_2400_2.fq.gz | samtools view -Sb -o ./out/A_YNJC_2400.bam -

###### output 
[M::bwa_idx_load_from_disk] read 0 ALT contigs
[M::process] read 71586 sequences (10000137 bp)...
[M::process] read 71586 sequences (10000277 bp)...
##### if I do not use the above pipeline, I can get the sam file successfully. 
bwa mem -M -K 10000000 -t 12 -R "@RG\tID:A_YNJC_2400\tSM:A_YNJC_2400\tPL:Illumina" DASZ_complete_genome.fa A_YNJC_2400_1.fq.gz A_YNJC_2400_2.fq.gz > A_YNJC2400.sam

**Comment by jkbonfield** [comment]
Note that the memory for `samtools sort` is *per thread*.  So `-@12 -m 4G` is asking for 48G - more like 50-60 with overheads.  That may or may not be a problem for you.  Also the `-S` option is an affectation which hasn't been needed for years, although it's harmless.

So if your bwa mem works in isolation and you get a SAM file out, then can your samtools view run on that SAM file to produce a BAM?  I'd expect so, but just checking.  That would imply the only difference here is "cmd1 > file; cmd2 < file" vs "cmd1 | cmd2".  Is that true?  If so my suspicions would be on the compute environment; eg a limit on CPU usage per job or memory limits.

Do you get any exit code?  Also how fast is this to fail?

Is there any output bam at all, even zero length?

**Comment by Zhenwen-camellia** [comment]
### if  I set the number of the thread in bwa mem less than 3 (1 or 2), the pipeline commands can run.  But, if I run the bwa mem only, t=12 is ok.  I don't know why, may be my big input file size.

**Comment by jkbonfield** [comment]
Can you add a "ulimit -a;" on to the front of your command line please so we can see what OS settings you have.  I see no reason why the command wouldn't work, unless it is some compute environment imposed limitation.

Also are you running these commands directly from an ssh login, or is it via some batch system?  If so, what are the settings used for the batch environment?  It may simply be you're using too many cores (for example).  We can't really help more without knowing more information.

**Comment by Zhenwen-camellia** [comment]
## I indeed run these commands directly by ssh login!
`ulimit -a`
[![20201022172236](https://user-images.githubusercontent.com/73217364/96852953-5a6cf880-148c-11eb-8bc6-a22475175d07.png)
](url)

### multiple samples 

```
#!/bin/bash
#BSUB -q Q64C1T_X4
#BSUB -J map*
#BSUB -o %map.out
#BSUB -e %map.err
#BSUB -n 12

find *1.fq.gz | sed s/_1.fq.gz//g | parallel --verbose --xapply bwa mem -M -K 10000000 -t 12 -R "'@RG\tID:{}\tSM:{}\tLB:WGS\tPL:Illumina'" DASZ_complete_genome.fa {}_1.fq.gz {}_2.fq.gz | samtools sort -@ 12 -m 4G -o ./out/{}.bam -
echo job end time is `date` 
```

### single sample
```
#!/bin/bash
#BSUB -q Q64C1T_X4
#BSUB -J map*
#BSUB -o %map.out
#BSUB -e %map.err
#BSUB -n 12

bwa mem -M -K 10000000 -t 12 -R "@rg\tID:A_YNJC_2400\tSM:A_YNJC_2400\tPL:Illumina" DASZ_complete_genome.fa A_YNJC_2400_1.fq.gz A_YNJC_2400_2.fq.gz | samtools sort -@ 12 -m 4G -o ./out/A_YNJC_2400.bam -
echo job end time is `date` 
```
*Whether for single or several samples, I meet the same issues*

**Comment by jkbonfield** [comment]
A parallel sample I could easily see you running out of memory on, as bwa will be using a considerable amount and the samtools sort would be around 50G too - per sample.

Why it dies on a single one I don't know.  The ulimits look all unlimited where it matters.   How much memory does your system have?  If you removed the `-m 4G` part of the sort command does the  pipeline still work?

Also you haven't answered some of the other questions.
- Do you get absolutely no output message from samtools?  Not even "merging N files" type messages?
- Do you get any output files created?  If so what are their sizes?  If non-zero, is it close to what you expect (based on the command that works, when not doing it via a pipe).
- How quickly is it failing?  Eg very fast, or after sufficient time that you think it's probably nearly ran to completion?

Right now I'm just baffled.  It works for others so it's likely something about the system setup or parameters used IMO.

**Comment by Zhenwen-camellia** [comment]
The following two commands were running in the terminal not submitted to queue, as I can check what happened in time. 
### set -t 12. running time 15 seconds, nothing I got. 
```
bwa mem -M -K 10000000 -t 12 -R "@RG\tID:A_YNJC_2400\tSM:A_YNJC_2400\tPL:Illumina" DASZ_complete_genome.fa A_YNJC_2400_1.fq.gz A_YNJC_2400_2.fq.gz | samtools sort -o ./out/A_YNJC_2400.bam -
```
[M::bwa_idx_load_from_disk] read 0 ALT contigs
[M::process] read 71586 sequences (10000137 bp)...
[M::process] read 71586 sequences (10000277 bp)...
samtools sort: failed to read header from "-"


### set -t 2. running time about 2 hours, and get a temporary file with 206M
```
bwa mem -M -K 10000000 -t 2 -R "@RG\tID:A_YNJC_2400\tSM:A_YNJC_2400\tPL:Illumina" DASZ_complete_genome.fa A_YNJC_2400_1.fq.gz A_YNJC_2400_2.fq.gz | samtools sort -o ./out/A_YNJC_2400.bam -
```
[M::bwa_idx_load_from_disk] read 0 ALT contigs
[M::process] read 71586 sequences (10000137 bp)...
[M::process] read 71586 sequences (10000277 bp)...
[M::mem_pestat] # candidate unique pairs for (FF, FR, RF, RR): (1, 7495, 7, 0)
[M::mem_pestat] skip orientation FF as there are not enough pairs
[M::mem_pestat] analyzing insert size distribution for orientation FR...
[M::mem_pestat] (25, 50, 75) percentile: (280, 330, 383)
[M::mem_pestat] low and high boundaries for computing mean and std.dev: (74, 589                                                                             )
[M::mem_pestat] mean and std.dev: (330.36, 78.62)
[M::mem_pestat] low and high boundaries for proper pairs: (1, 692)
[M::mem_pestat] skip orientation RF as there are not enough pairs
[M::mem_pestat] skip orientation RR as there are not enough pairs
[M::mem_process_seqs] Processed 71586 reads in 127.890 CPU sec, 63.873 real sec
[M::process] read 71592 sequences (10000245 bp)...
[M::mem_pestat] # candidate unique pairs for (FF, FR, RF, RR): (1, 7769, 1, 2)
[M::mem_pestat] skip orientation FF as there are not enough pairs
[M::mem_pestat] analyzing insert size distribution for orientation FR...
[M::mem_pestat] (25, 50, 75) percentile: (280, 329, 382)
[M::mem_pestat] low and high boundaries for computing mean and std.dev: (76, 586                                                                             )
................................. (omitting)

[M::mem_pestat] mean and std.dev: (329.62, 75.76)
[M::mem_pestat] low and high boundaries for proper pairs: (1, 671)
[M::mem_pestat] skip orientation RF as there are not enough pairs
[M::mem_pestat] skip orientation RR as there are not enough pairs
[M::mem_process_seqs] Processed 71584 reads in 129.455 CPU sec, 64.620 real sec
[M::process] read 71572 sequences (10000150 bp)...
[W::sam_read1] Parse error at line 2718053
samtools sort: truncated file. Aborting

**Comment by jkbonfield** [comment]
>  samtools sort: failed to read header from "-"

> [W::sam_read1] Parse error at line 2718053
> samtools sort: truncated file. Aborting

It would have been *really* useful if you'd included these error messages in your original issue!

You can maybe try capturing the input to samtools while still doing the pipe with something like:

```
bwa mem -M -K 10000000 -t 2 -R "@RG\tID:A_YNJC_2400\tSM:A_YNJC_2400\tPL:Illumina" DASZ_complete_genome.fa A_YNJC_2400_1.fq.gz A_YNJC_2400_2.fq.gz | tee out.sam | samtools sort -o ./out/A_YNJC_2400.bam -
```

Note the "tee" command.  Start with the `-t 12` as that's quick and see what's being passed into samtools.  The -t2 case is more intriguing.  How does it get so far before failing?  It sounds like there is some error or diagnostic message being injected into the output stream, but that's just guesswork.

Either way, the tee should help hugely in figuring out what samtools is "seeing".  You can then simulate samtools reading from a pipe with `cat out.sam | samtools sort -o ./out/A_YNJC_2400.bam -`.

**Comment by jkbonfield** [comment]
We should probably have closed this issue.  The original requester never came back, but I suspect the problem was an error in upstream software or shell usage (such as mixing stderr and stdout via nohup).  This wasn't exactly aided by not revealing useful error messages initially. :/

If in doubt, always break the pipeline into constituent parts to identify which bit is failing.

**Comment by daviesrob** [comment]
So the clue here is `Killed bwa-mem2`.  Killing bwa-mem2 would likely result in the truncated output and broken pipe that you saw.  It's not entirely obvious why it got killed, but I'd strongly suspect that you ran out of memory and either your nextflow runner or the Linux out-of-memory killer chose to terminate `bwa-mem2` to fix the problem.

Note that the memory limit you set in `samtools sort` is **per thread**, so `samtools sort -@ 20 -m 4G` will use 80G in total (and in fact a bit more as the `-m` limit is somewhat approximate).  To this you will need to add the memory needed by `bwa-mem2`.  If you don't have enough, you need to either reduce the `-m` setting or the number of sort threads so that both processes fit in the available memory.  Hopefully doing that will allow the pipeline to finish successfully.
