### ISSUE TITLE
samtools stats -t: bug or feature?

### ISSUE THREAD

**Issue by pd3** [samtools/samtools#1331]
Not sure if this is intended behavior or not: when restricting alignments to regions via `-t`, the number of filtered reads does not reflect the region subset https://github.com/samtools/samtools/blob/develop/stats.c#L1157. With `-t` one would expect to see only stats from reads overlapping the regions. One can work around this by streaming through `samtools view -L` but, unexpectedly, `view -L` and `stats -t ` can give different number of raw alignments.

**Comment by valeriuo** [comment]
Do you use the same file for `view -L` and `stats -t`?
The intervals for `stats -t` are 1-based closed [ ], while `view -L`, uses the BED format, which is 0-based half-open [ ). So some discrepancies between the output of the two commands might arise from this fact.

**Comment by pd3** [comment]
Yes, I can confirm that the difference is caused by bed vs tab format.
