### ISSUE TITLE
samtools addreplacerg does not output to BAM

### ISSUE THREAD

**Issue by andemexoax** [samtools/samtools#1338]
#### Using samtools 1.7; Linux 4.15.0-118-generic; x86_64; gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
When I run samtools addreplacerg it does not output to BAM despite saying that it should in the manual 
"samtools addreplacerg [-r rg-line | -R rg-ID] [-m mode] [-l level] [-o out.bam] in.bam  " https://www.htslib.org/doc/samtools-addreplacerg.html

This is my code

```
for myfile in /vol_c/folder/4_SamtosortedBam/*.bam
do 
	echo "taking file $myfile for adding read tags"
	base=$(basename ${myfile} .aln.bam)
	printf "base name is %s ...\n" $base
		
	samtools addreplacerg --threads 16 -r ID:$base -r SM:$base -r LB:L1 \
	-o /vol_c/folder/4_SamtosortedBam/w-readTags/${base}_wrt.bam ${myfile} 

done
```

and then running `htsfile file1_wrt.bam` the output is SAM version 1.5 sequence text... not BAM as it should

**Comment by daviesrob** [comment]
The manual page is for the latest version of samtools (1.11).  In samtools 1.7, addreplacerg wasn't able to detect the output format from the file extension.  The earliest version where it can is samtools 1.8.

I'd recommend upgrading to the latest release of samtools, but if you have to use 1.7 for some reason you should be able to  get it to output bam by adding `--output-fmt bam` to your command line.
