### ISSUE TITLE
samtools view error

### ISSUE THREAD

**Issue by sph17** [samtools/samtools#1340]
#### Are you using the latest version of [samtools](https://github.com/samtools/samtools/releases/latest) and [HTSlib](https://github.com/samtools/htslib/releases/latest)? If not, please specify.
(run `samtools --version`)
samtools --version
samtools 1.11
Using htslib 1.11
Copyright (C) 2020 Genome Research Ltd.

 #### Please describe your environment.
- OS (run `uname -sr` on Linux/Mac OS or ` wmic os get Caption, Version` on Windows)
- machine architecture (run `uname -m` on Linux/Mac OS or ` wmic os get OSArchitecture` on Windows)
- compiler (run `gcc --version` or `clang --version`)

Linux 5.4.39-linuxkit
x86_64
gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
Copyright (C) 2017 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

#### Please specify the steps taken to generate the issue, the command you are running and the relevant output.

I installed via conda samtools version 1.11 and tried to run 
samtools view -b -o HG00405.final.bam HG00405.final.cram

But I am getting this error:

[E::easy_errno] Libcurl reported error 52 (Server returned nothing (no headers, no data))
[W::find_file_url] Failed to open reference "https://www.ebi.ac.uk/ena/cram/md5/6aef897c3d6ff0c78aff06ac189178dd": Input/output error
[E::fai_build3_core] Failed to open the file /gpfs/internal/sweng/production/Resources/GRCh38_1000genomes/GRCh38_full_analysis_set_plus_decoy_hla.fa
[E::refs_load_fai] Failed to open reference file '/gpfs/internal/sweng/production/Resources/GRCh38_1000genomes/GRCh38_full_analysis_set_plus_decoy_hla.fa'
[E::cram_get_ref] Failed to populate reference for id 0
[E::cram_decode_slice] Unable to fetch reference #0:9996-34437

[E::cram_next_slice] Failure to decode slice
samtools view: error reading file "HG00405.final.cram": No such file or directory

**Comment by valeriuo** [comment]
Is the issue still occurring? I remember seeing some similar error messages from the EBI reference server during the previous week.

**Comment by valeriuo** [comment]
Please reopen, if the issue is persistent.
