### ISSUE TITLE
Convert BAM file to fast file - Error

### ISSUE THREAD

**Issue by bioramg** [samtools/samtools#1344]
Hi,
I would like to convert bam file into fastq file using the following command, but getting an error:

samtools fastq -F4 -1 forward_1.fastq -2 reverse_2.fastq -s unmapped.fastq mapped_reads.bam

Thank you.

**Comment by whitwham** [comment]
What error are you getting?  Which version of samtools are you using?  What platform are you running on?

**Comment by bioramg** [comment]
I am using Ubuntu 18.0. and getting an error with this command:

[main] unrecognized command 'fastq'

**Comment by whitwham** [comment]
Which version of samtools are you using?

Use `samtools --version` to find out.

**Comment by bioramg** [comment]
I tried to find out the version but getting an error "unrecognized command '--version'"

I installed through Anaconda "conda install -c bioconda samtools"

But, I used samtools to convert sam into bam file "samtools view -b mapped_read.sam > mapped_read.bam"

**Comment by bioramg** [comment]
I used "samtools" command and could able to see this.
samtools

Program: samtools (Tools for alignments in the SAM format)
Version: 0.1.20

Usage:   samtools <command> [options]

Command: view        SAM<->BAM conversion
         sort        sort alignment file
         mpileup     multi-way pileup
         depth       compute the depth
         faidx       index/extract FASTA
         index       index alignment
         idxstats    BAM index stats (r595 or later)
         fixmate     fix mate information
         flagstat    simple stats
         calmd       recalculate MD/NM tags and '=' bases
         merge       merge sorted alignments
         rmdup       remove PCR duplicates
         reheader    replace BAM header
         cat         concatenate BAMs
         bedcov      read depth per BED region
         targetcut   cut fosmid regions (for fosmid pool only)
         phase       phase heterozygotes
         bamshuf     shuffle and group alignments by name

**Comment by whitwham** [comment]
That is a very, very old version of samtools and will not support what you want to do.  This a conda/Anaconda problem where it does not install the newest version of samtools by default.

This has come up before, I am trying to find out what the correct conda commands are.

**Comment by bioramg** [comment]
Could you please update the latest commands to install samtools?

**Comment by whitwham** [comment]
You could try `conda install -c bioconda samtools=1.11`

We do not create the bioconda recipes and I suggest you open an issue with them.

**Comment by daviesrob** [comment]
It might be a good idea to run `which samtools` to check that you're running the copy of samtools that you expect.

Even without specifying the version, conda ought to install something much newer than 0.1.20.  If it really did do that, you probably need to update your conda installation.

**Comment by bioramg** [comment]
Its failed to installed with the above suggested command: install -c bioconda samtools=1.11

I would like to convert bam format into fastq format.

**Comment by whitwham** [comment]
> Its failed to installed with the above suggested command: install -c bioconda samtools=1.11
 
How did fail?  What did it do?  Please @bioramg, if you want our help you need to work with us.  Just saying "its failed" gives us no idea what has happened and no clues to work with. 

> I would like to convert bam format into fastq format.

Then I suggest you install the latest version of samtools which is 1.11, your initial command will work in that version.

**Comment by bioramg** [comment]
The error message:

conda install -c bioconda samtools=1.11
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: /
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
failed

UnsatisfiableError: The following specifications were found to be incompatible with each other:

Output in format: Requested package -> Available versions

Package libgcc-ng conflicts for:
samtools=1.11 -> ncurses[version='>=6.2,<6.3.0a0'] -> libgcc-ng[version='>=7.2.0|>=7.3.0']
samtools=1.11 -> libgcc-ng[version='>=7.5.0']

Package _libgcc_mutex conflicts for:
samtools=1.11 -> libgcc-ng[version='>=7.5.0'] -> _libgcc_mutex=[build=main]
python=3.7 -> libgcc-ng[version='>=7.3.0'] -> _libgcc_mutex=[build=main]

**Comment by jkbonfield** [comment]
See https://github.com/conda/conda/issues/9905 for a long list of packages which are suffering from broken dependency management.  It's worth trying mamba instead (https://github.com/mamba-org/mamba) instead of conda for doing conda installs as it has a less buggy dependency resolver and is **much** faster too.

I'm not sure it resolves the ncurses problems though.  That may be a bioconda recipe issue.  I was about to suggest you also file a bug against bioconda as their packaging has wrong dependencies.  However I see you've just done this. :-).

It may be a duplicate though.  Eg I also see:

https://github.com/bioconda/bioconda-recipes/issues/24199
https://github.com/bioconda/bioconda-recipes/issues/22824

Sadly this is a long standing issue.

However please do also do "which samtools" as we think the version you are picking up also isn't likely to be the one that conda installed.

**Comment by bioramg** [comment]
Thank you for your suggestion.
$which samtools
/home/raman/anaconda3/bin/samtools

But if I use command "conda remove samtools" I can able to see the latest version of samtools 
conda remove samtools
Collecting package metadata (repodata.json): done
Solving environment: done

## Package Plan ##

  environment location: /home/raman/anaconda3

  removed specs:
    - samtools


The following packages will be REMOVED:

  miniasm-0.3_r179-hed695b0_1
  pilon-1.23-2
  racon-1.4.13-he513fc3_0
  samtools-1.7-1
  unicycler-0.4.8-py37h8b12597_0


Proceed ([y]/n)?

**Comment by daviesrob** [comment]
If you run `/home/raman/anaconda3/bin/samtools` does it still claim to be 0.1.20?

**Comment by bioramg** [comment]
Yes

**Comment by daviesrob** [comment]
Give it the full path - i.e. run `/home/raman/anaconda3/bin/samtools` not just `samtools`.

**Comment by bioramg** [comment]
Are you asking to give full path for the conversion of bam to fastq comnand?

**Comment by daviesrob** [comment]
No, just `/home/raman/anaconda3/bin/samtools` so it prints the version number out.

**Comment by bioramg** [comment]
I am getting the same result

 raman@alsvr:~/anaconda3$ /home/raman/anaconda3/bin/samtools

Program: samtools (Tools for alignments in the SAM format)
Version: 0.1.20

Usage:   samtools <command> [options]

Command: view        SAM<->BAM conversion
         sort        sort alignment file
         mpileup     multi-way pileup
         depth       compute the depth
         faidx       index/extract FASTA
         index       index alignment
         idxstats    BAM index stats (r595 or later)
         fixmate     fix mate information
         flagstat    simple stats
         calmd       recalculate MD/NM tags and '=' bases
         merge       merge sorted alignments
         rmdup       remove PCR duplicates
         reheader    replace BAM header
         cat         concatenate BAMs
         bedcov      read depth per BED region
         targetcut   cut fosmid regions (for fosmid pool only)
         phase       phase heterozygotes
         bamshuf     shuffle and group alignments by name

**Comment by daviesrob** [comment]
Hmm, so it looks like the samtools in your conda environment is much older than the one it thinks should be there.

You could try:

```
conda install -c bioconda -c conda-forge -c defaults samtools=1.11
```

to see if adding the conda-forge channel fixes the ncurses dependency problem and gets you the latest version.

Failing that you could try setting up a fresh conda environment and see if that works better.

**Comment by bioramg** [comment]
I could not execute with same issues. So, I am going to setting up a fresh Conda environment. 

Thank you for your kind support.

**Comment by bioramg** [comment]
I reinstalled Anaconda and samtools is working fine. Thank you.
