### ISSUE TITLE
filter reads in BAM having a tag 

### ISSUE THREAD

**Issue by alexbarrera** [samtools/samtools#1348]
#### Is your feature request related to a problem? Please specify.
ArchR is having trouble dealing with fragment reads not having a barcode tag (CB) defined by cellranger (10x Genomics pipeline), which assigns NA as cellular barcodes.
#### Describe the solution you would like.
In addition to `-d TAG:VALUE` which filters reads having a specific value, add an option to filter reads simply *having a TAG*. Ideally, there is no need to create an extra argument, just using `-d TAG` should do it.

Thanks!

**Comment by valeriuo** [comment]
It was implemented as #1339 and will be available in the next release. You can use the feature now, by pulling the develop HEAD.

**Comment by alexbarrera** [comment]
Excellent! Thanks a bunch
