### ISSUE TITLE
support int tags with samtools view options -d and -D

### ISSUE THREAD

**Issue by dariomel** [samtools/samtools#1357]
the -d and -D options of samtools view currently handle only tags of type string, as evidenced by the following code:

https://github.com/samtools/samtools/blob/d58fc8a16729f25407da6729c440a51140396f4c/sam_view.c#L104-L112

It would be nice if those options could also handle tags of type integer.
For example, the following mods allowed me to use option -D with a file containing 1651 integers:
```C
    if (settings->tvhash && settings->tag) {                                     
        uint8_t *s = bam_aux_get(b, settings->tag);                              
        if (s) {                                                                 
            uint8_t t[24];                                                         
            khint_t k;                                                             
            if (*s=='i') { sprintf((char*)t,"%ld",bam_aux2i(s)); s=t; } else ++s;  
            k = kh_get(tv, settings->tvhash, (char*)s);                          
            if (k == kh_end(settings->tvhash)) return 1;                         
        } else {                                                                 
            return 1;                                                            
        }                                                                        
    }                                                                            
``` 
Otherwise, the [man page](http://www.htslib.org/doc/samtools-view.html) should state that the -d and -D options can only handle tags of type string.

**Comment by jkbonfield** [comment]
Since https://github.com/samtools/samtools/pull/1346 went in, a more general purpose filtering rule has been added.  This is currently "filter-out" only although we could possibly add a "filter-in" if deemed appropriate.

That said, this is obviously more flexible (and much likely faster) as building an expression matching one of 1651 integers wouldn't be pretty!  Can you describe the use case for wanting to match a specific set of integers in a tag, rather than simply ranges (eg >10 && <100)?

**Comment by dariomel** [comment]
while processing single-cell RNA-seq reads, I convert all cell barcodes to their index into the original whitelist, and store that index in a custom tag with integer value. Doing so saves storage space and speeds up certain tasks in downstream analysis. After clustering cells, say I want to isolate all of the aligned reads that contributed to a particular cluster. Then, I generate a list of cell barcode indices corresponding to that cluster and use samtools view -D to obtain a BAM file that contains the desired reads. Using a range of values to select the desired reads would not help, because a cluster of cells may consist of any combination of barcodes.
