### ISSUE TITLE
Clearing previous duplicate settings and tags with samtools markdup shouldn't require that fixmates was run with the mote scoring option.

### ISSUE THREAD

**Issue by ghuls** [samtools/samtools#1358]
#### Is your feature request related to a problem? Please specify.

Clearing previous duplicate settings and tags with samtools markdup shouldn't require that fixmates was run with the mate scoring option.

I just want to remove the duplicate flag so I can run a barcode aware mark duplicate tool.
It would be great if a barcode aware mark duplicate tool would be added to `samtools markdup` 

```bash
java -Dpicard.useLegacyParser=false -jar $EBROOTPICARD/picard.jar MarkDuplicates \
        -I "${input_bam_file}" \
        -O "${output_bam_file}" \
        -M "${output_bam_file%.bam}.mark_duplicates_metrics.txt" \
        -BARCODE_TAG CB \
        -REMOVE_DUPLICATES false \
        -OPTICAL_DUPLICATE_PIXEL_DISTANCE 100
```

https://github.com/broadinstitute/picard/issues/1579

**Comment by whitwham** [comment]
Would you want markdup to do it or an entirely separate program?

**Comment by ghuls** [comment]
Clearing the DUP flag without that the mate scoring options are (necessarily) present would be good if it is supported by `samtools markdup`.

The posibility to clean any flag might make sense too to have in another tool (at the moment I don't know which other flags would make sense to be able to clear/set besides the DUP flag).

barcode aware markdup option would make sense in samtools markdup itself.

**Comment by whitwham** [comment]
Clearing DUP flags and tags when not about to do more duplicate marking is not really a job for **markdup**.  It seems like **view** would be the best place to add that.

Barcode awareness I can add.  I assume that means that if a read looks like a duplicate but has a different barcode then it is not a duplicate?

**Comment by ghuls** [comment]
> Clearing DUP flags and tags when not about to do more duplicate marking is not really a job for **markdup**. It seems like **view** would be the best place to add that.

I wrongly assumed that `-c` would only clear the flags, but not run the rest of the markdup code itself. `view` would indeed be a better place for it (as it supports clearing AUX tags already).

> Barcode awareness I can add. I assume that means that if a read looks like a duplicate but has a different barcode then it is not a duplicate?

Yes. It is also important that the BAM tag which should be used for getting the UMI/BARCODE_TAG can be chosen.

The Picard implementation should be in this dir:
https://github.com/broadinstitute/picard/blob/master/src/main/java/picard/sam/markduplicates/UmiAwareMarkDuplicatesWithMateCigar.java

Another feature that `Picard MarkDuplicates` supports is specifying `READ_NAME_REGEX` to extract the coordinates from the flowcell. Some pipelines we use have the cell barcode added to the read names before the mapping start `CB:original_read`. Currently samtools markdup counts the number of colons to extract the x and y coordinate. It would be great if the "column numbers" for x and y would be possible to be specified.

**Comment by whitwham** [comment]
Added UMI/barcode support in #1630 ready for testing. Please open a new issue if you find something wrong with it.

That should be everything in this issue done.
