### ISSUE TITLE
Samtools stats 'inward oriented pairs' and  'outward oriented pairs' seem to imply more reads than 'raw total sequences'?

### ISSUE THREAD

**Issue by jkmatila** [samtools/samtools#1360]
I got the following values in `samtools stats` output from samtools 1.11, which is the latest release at this time. (The full output is attached as [samtools-stats.txt](https://github.com/samtools/samtools/files/5808585/samtools-stats.txt))

It seems like the numbers for _inward oriented pairs_ and _outward oriented pairs_ would imply more reads than _raw total sequences_.

2 * (_inward oriented pairs_ + _outward oriented pairs_) = 2 * (124586692 + 3055596) = 255284576, which is greater than _raw total sequences_ 244454886. (In fact, just the reads implied by inward oriented pairs is enough to exceed the total number of sequences.)

I wonder if this could be indicative of a bug or is there something that I am overlooking? 

(I tried to look at the code. By a quick glance, it seems like [here](https://github.com/samtools/samtools/blob/1.11/stats.c#L1229-L1244), for each read, one of the counters for other/inward/outward orientation is increased and [here](https://github.com/samtools/samtools/blob/1.11/stats.c#L1461-L1464) the counts are halved. It does not seem clear to me why the number of (inward + outward + other) pairs multiplied by two could exceed the number of reads in the file.)

```
# This file was produced by samtools stats (1.11+htslib-1.11) and can be plotted using plot-bamstats
# This file contains statistics for all reads.
# The command line was:  stats /XXX/XXX/XXX.aligned.duplicates_marked.recalibrated.bam
# CHK, Checksum [2]Read Names   [3]Sequences    [4]Qualities
# CHK, CRC32 of reads which passed filtering followed by addition (32bit overflow)
CHK     d9485ac9        0ae529f3        a1fc277b
# Summary Numbers. Use `grep ^SN | cut -f 2-` to extract this part.
SN      raw total sequences:    244454886
SN      filtered sequences:     0
SN      sequences:      244454886
SN      is sorted:      1
SN      1st fragments:  122227443
SN      last fragments: 122227443
SN      reads mapped:   237282395
SN      reads mapped and paired:        237117316       # paired-end technology bit set + both mates mapped
SN      reads unmapped: 7172491
SN      reads properly paired:  237117316       # proper-pair bit set
SN      reads paired:   244454886       # paired-end technology bit set
SN      reads duplicated:       40960232        # PCR or optical duplicate bit set
SN      reads MQ0:      1095026 # mapped and MQ=0
SN      reads QC failed:        0
SN      non-primary alignments: 0
SN      total length:   23762404584     # ignores clipping
SN      total first fragment length:    11906044837     # ignores clipping
SN      total last fragment length:     11856359747     # ignores clipping
SN      bases mapped:   23092079754     # ignores clipping
SN      bases mapped (cigar):   22945895850     # more accurate
SN      bases trimmed:  0
SN      bases duplicated:       3977651283
SN      mismatches:     0       # from NM fields
SN      error rate:     0.000000e+00    # mismatches / bases mapped (cigar)
SN      average length: 97
SN      average first fragment length:  97
SN      average last fragment length:   97
SN      maximum length: 98
SN      maximum first fragment length:  98
SN      maximum last fragment length:   98
SN      average quality:        34.4
SN      insert size average:    716.6
SN      insert size standard deviation: 1639.9
SN      inward oriented pairs:  124586692
SN      outward oriented pairs: 3055596
SN      pairs with other orientation:   0
SN      pairs on different chromosomes: 0
SN      percentage of properly paired reads (%):        97.0
```

**Comment by valeriuo** [comment]
It's quite an intriguing issue. Do you have anonymised data sample that triggers this behaviour? A few reads (<100) should do.

**Comment by jkmatila** [comment]
I think this is explained by alignments with the "supplementary alignment" (0x800) flag set. They are not included in the "raw total sequences" count (or "reads mapped and paired" or "reads paired") but they are included when counting the inward/outward/other oriented pairs. 

I did not initially realize that the data contained supplementary alignments (as samtools stats does not report the number of supplementary alignments).

**Comment by valeriuo** [comment]
Good catch. I meant to ask you about the number of supplementary alignments, but I was under the impression we were counting them under the **raw total sequences**. We should still improve this stats section, so I will leave the issue open for the moment.
Btw, what does `samtools view -c <your.bam>` show?
