### ISSUE TITLE
Extract the overlapping paired-end reads

### ISSUE THREAD

**Issue by aayushraman** [samtools/samtools#1361]
Hi,

I would like to know if there is a way to extract paired-end reads (and the genomic region) from the bam file where a certain part of R1 and R2 read overlaps the genomic location. For example, if R1 and R2 are the paired-end read then, I am interested in extracting this paired-end read from the bam file and extract the region that is between **.

        R1 ---**----------**>
                <**----------**---- R2 

Thanks,
-Ar

**Comment by valeriuo** [comment]
There is no `samtools` command that would give you the desired result. You could start from the output of

`samtools sort -n <alignment_file> | samtools view -f1 -F12`

which would return all the paired and mapped reads grouped by name (1st column). This output should then be piped into a custom script that would perform the required analysis. The alignment start position is at the 4th column, but the length has to be computed from the CIGAR string (6th column).

**Comment by aayushraman** [comment]
Thanks!
