### ISSUE TITLE
htscodecs submodule need to run make

### ISSUE THREAD

**Issue by shbrainard** [samtools/samtools#1364]
I just cloned samtools and tried to compile it on Mac 10.15, and got this error:

```
Error: htscodecs submodule files not present.
Try running:
    git submodule update --init --recursive
and then re-run make.
```

After running this command (within the samtools directory) and re-running make I get the error:
`make: *** No rule to make target '../htslib/htscodecs/htscodecs/arith_dynamic.c', needed by '../htslib/hts-object-files'.  Stop.`

I have htslib cloned at ../htslib

Suggestions?

**Comment by shbrainard** [comment]
Nevermind, I ran make within htslib and then rebuilt and reran ./configure within samtools and everything is working!

**Comment by jkbonfield** [comment]
Thanks for reporting it though as it indicates something we may wish to spell out in the Samtools INSTALL file too, or to edit the error message to be clearer.
