### ISSUE TITLE
Add option to fail if reference isn't available locally for CRAMs

### ISSUE THREAD

**Issue by anderspitman** [samtools/samtools#1366]
#### Is your feature request related to a problem? Please specify.

Yes. The default behavior of falling back to downloading references files from EBI servers if the reference isn't found locally has bitten iobio multiple times. Just this week I discovered a subtle regression that I introduced 3 months back. These types of issues are particularly prevalent in automated environments where you're more likely to be running in a container or other sandboxed environment that starts fresh with each run.

#### Describe the solution you would like.

It would be awesome if there was a flag for samtools that told it to fail if no local reference is available. That way you know for sure it's not making any network requests as side effects.

**Comment by anderspitman** [comment]
This would be similar in concept to the VEP `--offline` option.

**Comment by jkbonfield** [comment]
This is a good idea, but it's probably a documentation issue more than anything.

For example right now:

```
$ REF_PATH=/ samtools view /var/tmp/novaseq-10m.30.cram
[E::fai_build3_core] Failed to open the file /genomes/Homo_sapiens/NCBI/GRCh38Decoy/Sequence/IsaacIndex5/../WholeGenomeFasta/genome.fa
[E::refs_load_fai] Failed to open reference file '/genomes/Homo_sapiens/NCBI/GRCh38Decoy/Sequence/IsaacIndex5/../WholeGenomeFasta/genome.fa'
[E::cram_get_ref] Failed to populate reference for id 0
[E::cram_decode_slice] Unable to fetch reference #0:9967-24250

[E::cram_next_slice] Failure to decode slice
samtools view: error reading file "/var/tmp/novaseq-10m.30.cram": No such file or directory
```

It didn't attempt to connect to the EBI.

So would adding a `--offline` option be more appropriate than setting REF_PATH explicitly?  If it was --offline, we'd need to be modifying each of samtools view, sort, merge, etc, or to modify the options such as `--input-fmt-option offline`.  I'm not convinced that's any easier than simply ensuring REF_PATH contains something.

I note that `REF_PATH=""` still connects to the EBI.  I think this may be an error.  We should consider the lack of specifying REF_PATH as permission to do so, but explicitly emptying it as a request to not search elsewhere.

**Comment by anderspitman** [comment]
Ahhh I didn't even think of that. This is totally acceptable. As I said, it's mostly for automated/scripting environments, so the ergonomics aren't particularly important.

I do agree unsetting `REF_PATH` to disable searching might be nice, but I'll leave that to you guys to decide.

Thanks!

**Comment by jmarshall** [comment]
IMHO treating unset and set-but-empty the same way for environment variables is a good (and common!) convention — cf the shell's `${FOO:-defaultvalue}` syntax with the colon. Not everybody knows the right way to unset an exported variable and `REF_PATH=` is a likely attempt. Also for temporarily overriding it for a single command, as in `…; REF_PATH=foo samtools view bar.cram; …`, I'm not sure there's a way to unset a variable temporally without invoking a sub shell (`…; (unset REF_PATH; samtools view bar.cram); …` probably does it but is much more tedious).

HTSlib's test suite uses `REF_PATH=:` to prevent any searching; making sure that CRAM doesn't work seems like enough of an uncommon case that it should be fairly explicit and it doesn't really need to be made more ergonomic than that or `REF_PATH=/path/to/emptydir`…

**Comment by anderspitman** [comment]
> IMHO treating unset and set-but-empty the same way for environment variables is a good (and common!) convention

Sorry, I misspoke. I meant setting to empty (as @jkbonfield demonstrated), not unsetting. 

> HTSlib's test suite uses `REF_PATH=:` to prevent any searching; making sure that CRAM doesn't work seems like enough of an uncommon case that it should be fairly explicit and it doesn't really need to be made more ergonomic than that or `REF_PATH=/path/to/emptydir`…

Warning: slight rant ahead. I don't pretend to understand all the tradeoffs you guys have to make. samtools and htslib are fantastic and indispensable tools. Just sharing my experience.

I actually disagree with making CRAMs work transparently, especially by relying on a network connection to do so. Hiding the fact that CRAMs require a reference creates a leaky abstraction, and in my experience this one does leak. It's good that it displays a warning the first time it creates the cache directory, but if the user misses that warning they may forever be wondering why their CRAM operations are so slow, when what they really need to do is download a reference and use -T. I have a hard time believing that the average samtools user understands the intricacies of BAM vs CRAM compression enough to navigate this well. Experienced users I know just use -T every time.

**Comment by jkbonfield** [comment]
I'm sort of with you there, and I think perhaps EBI are now.  Originally it was very much a recommendation from them that all CRAMs should use them as a key reference server and they saw this way of working as validation that everyone is using the same reference.  Data provenance etc.

Once CRAM got popular though, the stress on their server went high and it started getting flakey, at which point they required all CRAM implementations to only use EBI as a last resort and to require local download and caching of references.  (We were already doing that though.)  Maybe now they'd prefer the next step as you suggest.

External references are definitely the achilles heel here.  One plan I have for CRAM4 is to improve the capabilities of embedded references, but I know that was contraversial in the early CRAM days - see the data provenance comments above.  The basic embedding capabilities it has were only accepted when we pointed out that we may add a few million reference sequences to their archives for each of our early high-fragmented denovo assemblies, and each new assembly update with be another vast set of references. :)

I'd also put a warning in about use of -T.  It's better to have an exploded md5 based reference directory as it's in the native format needed by CRAM.  It can just mmap it and directly access the data.  A fasta however requires parsing and removing of all those newlines.  That can be a surprising hit, especially when doing lots of threading.

**Comment by anderspitman** [comment]
> External references are definitely the achilles heel here. One plan I have for CRAM4 is to improve the capabilities of embedded references

I could certainly get behind that. While we're on the topic, is there a reason you can't embed the index in the bam/cram? I feel like the answer is obvious but can't think of anything off the top of my head. Even in the case of access over HTTP, you could make a request to the beginning of the file to figure out how big the index is, then read that many bytes to get the index, then make requests against the rest of the file as usual.

> I'd also put a warning in about use of -T. It's better to have an exploded md5 based reference directory as it's in the native format needed by CRAM. It can just mmap it and directly access the data. A fasta however requires parsing and removing of all those newlines. That can be a surprising hit, especially when doing lots of threading.

It's gotchas like this that really make me wonder whether CRAM is an improvement over BAM for working data. For archival, definitely.

**Comment by jmarshall** [comment]
> is there a reason you can't embed the index in the bam/cram?

The pros and cons and the inertia of the status quo have been discussed several times on _samtools-devel_. You can find that in the mailing list archives.

**Comment by jkbonfield** [comment]
> I could certainly get behind that. While we're on the topic, is there a reason you can't embed the index in the bam/cram? I feel like the answer is obvious but can't think of anything off the top of my head. Even in the case of access over HTTP, you could make a request to the beginning of the file to figure out how big the index is, then read that many bytes to get the index, then make requests against the rest of the file as usual.

Having an index can harm streaming.  It is possible to design a format that threads segments of index throughout the file so an indexable file is also streamable, but these weren't part of the design process it would seem so we have what we have.  Changing it now would be quite a big task.

> > I'd also put a warning in about use of -T. It's better to have an exploded md5 based reference directory as it's in the native format needed by CRAM. It can just mmap it and directly access the data. A fasta however requires parsing and removing of all those newlines. That can be a surprising hit, especially when doing lots of threading.
> 
> It's gotchas like this that really make me wonder whether CRAM is an improvement over BAM for working data. For archival, definitely.

I think it depends on what you're doing.  For many tasks we use uncompressed BAM as our working format, but that's usually streamed directly from one tool to another (via pipes or other forms of inter-process communication).  Also unsorted data is a bit spammy of reference access (if enabled) making CRAM a poor choice there.

There are other things to consider though.  Writing CRAM is often faster than writing BAM (unless you're using level 1 compression), but for working data there's little point in using much more than level 1 anyway.  It's also worth considering using referenceless encoding for such CRAMs, simply to avoid access to a local reference server / directory.  This can be particularly helpful when dealing with name sorted data.

HTSlib and SAMtools though are designed to be format agnostic, so there's nothing wrong at all for using BAM throughout a pipeline and only switching to CRAM for the at-rest final output.
