### ISSUE TITLE
mpileup -e INT does nothing.

### ISSUE THREAD

**Issue by jkbonfield** [samtools/samtools#137]
The usage claims "Phred-scaled gap extension seq error probability [20]". It sets an extQ variable in the code, but I can find no reference to this.  Changing it from 1 to 100 in a loop on mpileup.1.bam test file gives identical results in all cases.

**Comment by kirkmcclure** [comment]
The value is assigned to conf->extQ which,
in mpileup(), is assigned to bca->extQ which
is used in a calculation in est_seqQ().

Usage is specific to BCF; the mpileup -g output option must also be selected.

**Comment by jkbonfield** [comment]
Confirmed.  Plus the usage statement was updated 2014-04-23 so it is now obvious which options only affect vcf/bcf output.
