### ISSUE TITLE
Online documentation out-of-date

### ISSUE THREAD

**Issue by mbhall88** [samtools/samtools#1373]
The [online documentation for samtools](https://www.htslib.org/doc/samtools.html) seems to still be for version 1.10? Am I missing something? This gives conflicting information for usage of certain tools (`faidx` as one example).

**Comment by valeriuo** [comment]
We are planning to fix this aspect with the upcoming release. However, the web documentation is a formatted version of the man pages. So you should be able to find the same information by running `man` on the desired samtools subcommand, e.g. 
`man samtools faidx`. Where would you say is the conflicting information?

**Comment by mbhall88** [comment]
Well, just as a single, simple example. The online docs for samtools [faidx](https://www.htslib.org/doc/samtools-faidx.html) don't have some of the new options such as `--fai-idx` and `--gzi-idx`

**Comment by valeriuo** [comment]
It is a bit of a nuisance, as users expect the latest documentation to correspond to the latest release. However, the top right of the page shows the version of tool which it documents.
Nevertheless, it is something to be fixed and it will most likely happen in a matter of weeks.

**Comment by valeriuo** [comment]
Fixed by the latest release.
