### ISSUE TITLE
Documentation on SAM flags could use some fleshing out

### ISSUE THREAD

**Issue by outpaddling** [samtools/samtools#1376]
FYI, "man samtools-flagstat" says only this about secondary alignments:

```
                         secondary
                                0x100 bit set

```
And "man samtools-flags" says this:

`       0x100   SECONDARY       secondary alignment
`
SAMv1.pdf doesn't really add anything.  Would be good if the PDF and one of the man pages had a clear definition of a secondary alignment as flagged by samtools, as well as features indicated by other flags.  There are definitions to be found online, of course, but someone new to the field can never be sure what to trust.

Cheers,

    Jason

**Comment by jmarshall** [comment]
> SAMv1.pdf doesn't really add anything

Is this conclusion re SAMv1.pdf based on just the listing of flags in §1.4, or does it include the background and explanations in §1.2 (Terminologies and Concepts)?

**Comment by outpaddling** [comment]
Hmm, I think it was based on an outdated copy of the spec found on Google.  Just tried again, and now a search in the PDF for "secondary" is producing a lot more hits.  Thanks for catching that.
So it's just the man pages that I would suggest enhancing.  It could be something as simple as adding
"For more information on the meaning of flags, see the SAM specification" at <link>."
