### ISSUE TITLE
S3 file access fails with long paths

### ISSUE THREAD

**Issue by anderspitman** [samtools/samtools#1377]
#### Are you using the latest version of [samtools](https://github.com/samtools/samtools/releases/latest) and [HTSlib](https://github.com/samtools/htslib/releases/latest)? If not, please specify.
(run `samtools --version`)

`samtools 1.10`

 #### Please describe your environment.
- OS (run `uname -sr` on Linux/Mac OS or ` wmic os get Caption, Version` on Windows)
- machine architecture (run `uname -m` on Linux/Mac OS or ` wmic os get OSArchitecture` on Windows)
- compiler (run `gcc --version` or `clang --version`)

`Linux 3.10.0-957.27.2.el7.x86_64`

#### Please specify the steps taken to generate the issue, the command you are running and the relevant output.

When accessing a file on CEPH storage using the S3 protocol, samtools fails on longer paths. I haven't determined yet whether the root cause is the length of the path string, or the depth of nesting. I figured I would check here if this is a known issue before diving too deep into debugging, as I can solve the problem in the short term by moving the data to a location with shorter paths. I'll need to resolve this eventually though.

**Comment by anderspitman** [comment]
Upon further testing, it appears neither path length nor depth are the problem. I've copied the same file to two different locations on our CEPH server. The paths vary by only the top directory. One works; the other doesn't. I'm at a complete loss. Anyone seen something like this before?

**Comment by jmarshall** [comment]
Crank up the logging with `samtools view --verbosity 9` and you should be able to see what the nature of the failure is.

**Comment by anderspitman** [comment]
Thanks, using that I believe I have identified the problem. If the bucket name has an underscore in it (which apparently is invalid on AWS), samtools builds the request differently. As an example, say I have the same file on 2 buckets:

`bucket1/dir/file.bam`

`bucket_2/dir/file.bam`

In the first case, samtools is making a GET to `bucket1.domain`. In the second case, the request is going to `domain/bucket_2`. For us, case 2 is what is working, because we're not serving TLS certs for subdomains of our S3 endpoint.

Obviously we should probably use AWS-valid bucket names, but is there a way to have samtools use the path instead of subdomain requests?

**Comment by whitwham** [comment]
Short answer, no.

Longer answer.  Amazon are deprecating the path-style URLs in favour of the virtual-hosted style ([here](https://aws.amazon.com/blogs/aws/amazon-s3-path-deprecation-plan-the-rest-of-the-story/) if you didn't already know).  So we changed our S3 handling to use virtual-hosting unless the bucket name is not DNS compliant or there is a "." in the name (which breaks SSL).

Looking at the code, I think the only way to force path-style is to have non compliant DNS bucket name in there.

**Comment by whitwham** [comment]
I had a more careful look at the code and there really is no other way around it.  I could add something to force path-style, an environmental variable maybe.

**Comment by jmarshall** [comment]
I think being able to control this via endpoint-related settings in the S3 configuration file has been discussed in the past… e.g. https://github.com/samtools/htslib/issues/436#issuecomment-293305042 and nearby.

IIRC `host_bucket` and/or `website_endpoint` affect this in _.s3cfg_ so could be reused in HTSlib; and in _.aws/credentials_ there's [`addressing_style = path|virtual|auto`](https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-files.html#cli-configure-files-s3).

**Comment by whitwham** [comment]
Good find.  Before my time working on htslib S3.

**Comment by anderspitman** [comment]
So if I'm reading the various references correctly, there's currently no way to do this?

It seems like the primary motivation for AWS making this switch is for scaling purposes, at the cost of added complexity in managing TLS certificates. Seeing as most non-AWS S3 deployments won't have anywhere near their scale, it seems like it would be useful to support the path method.

**Comment by whitwham** [comment]
Yes, I will put in an optional setting somewhere (probably multiple somewheres).

**Comment by anderspitman** [comment]
Just wanted to note that our ops people were able to add support for virtual hosting S3 URLs, which essentially solves this for us. So apparently CEPH is able to support it which is good news.

I'm still in favor of the proposed feature but wanted to let ya'll know we're not blocked.

Thanks!

**Comment by whitwham** [comment]
Good to know.  I did most of my signature v4 testing against CEPH.

With verbosity set to 9, did you see what error codes CEPH produced with the virtual-style URL?  I want to see if I can automatically handle the error.

**Comment by anderspitman** [comment]
I don't recall the exact errors, only that the message indicated a problem with the TLS certificate. And now that it's fixed in our deployment I don't think I have a way to reproduce it.

**Comment by whitwham** [comment]
Okay, thanks.  I might just have to depend on config settings.
