### ISSUE TITLE
samtools view --write-index writes different index than samtools index

### ISSUE THREAD

**Issue by ghuls** [samtools/samtools#1378]
#### Are you using the latest version of [samtools](https://github.com/samtools/samtools/releases/latest) and [HTSlib](https://github.com/samtools/htslib/releases/latest)? If not, please specify.
(run `samtools --version`)

1.11

 #### Please describe your environment.

- Linux 3.10.0-1127.18.2.el7.x86_64

#### Please specify the steps taken to generate the issue, the command you are running and the relevant output.

I created a BAM index while running some filter commands:

```
    # Filter dedup BAM file:
    #   - Filter out reads with low mapping quality,
    #   - Filter out reads with one of the following flags: UNMAP,MUNMAP,SECONDARY,QCFAIL,DUP
    #   - Only keep chromosomes of interest.
    #   - Create index.
    samtools view \
        -@ 4 \
        -b \
        -q 30 \
        -F 1804 \
        --write-index \
        -o "${output_dir}/${sample}.bowtie2.dedup.q30.bam" \
        "${output_dir}/${sample}.bowtie2.dedup.bam" \
        ${chroms_to_keep}
```

I used this BAM file with `deepTools` (which uses pysam, which used HTSlib 1.7) and noticed that for one of my BAM files, for a certain region it wouldn't extract any reads from the index (works fine for all other regions). `samtools view -r ${region}` (1.11) works fine for the same region.

When I moved the index and recraeted the index with `samtools index -c ${bam}`,
`deepTools` saw reads at that position.

Also SAMtools 1.7 can't see any reads at that position (with the index created with `--write-index`), while it also works fine with the index created with  `samtools index -c ${bam}` (1.11).

The `--write-index` is also slightly smaller than the `samtools index -c ${bam}` one.

Would it be possible to create the same index in both cases? or is the index created with `--write-index` in a slightly different format (e.g. streaming format??) (as now it seems like `--write-index` seems like a very dangerous feature to use)?

For more details, see:
https://github.com/deeptools/deepTools/issues/1039

**Comment by jkbonfield** [comment]
This sounds like a bug.

Can you check if it works without threading enabled?  My guess is yes, as getting the index correct while threading is the most complex challenge of that code.

**Comment by ghuls** [comment]
I can try. I had some other samples where everything seemed OK (or at least deepTools didn't show an obvious problem). Is there a proper way to validate the index? Or does `samtools index` generate a index file deterministically?

**Comment by jkbonfield** [comment]
It should be deterministic, even when threading.

The problems arise due to htslib not wanting to split reads across BGZF blocks if possible.  So it doesn't know a read won't fit until it tries, which IIRC also changes the end-index location of the previous read.  It has code to edit the previous index item.  All extremely ghastly, and a nightmare when threading.  I *thought* we'd fixed it to be robust to threading though.

**Comment by ghuls** [comment]
It took a while to reproduce.

First I made the mistake of writing to a different output file (which changes the BAM header slightly, leading to slightly different filesizes and thus a different index).

In the end It seems like I used SAMtools 1.10. The BAM file produced by SAMtools 1.11 is a few bytes larger (5 bytes) (when using 4 threads), so it is difficult to say if the bug is not in SAMtools 1.11 or that we just didn't have a problematic unhandled case.
Creating the index with `samtools index -c` on the SAMtools 1.10 BAM file with 1.10 and 1.11 produces the same file (slightly bigger than the `--write-index` version from SAMtools 1.10).

When running with 1 thread, the BAM file is different and the index created with `--write-index` and `index -c` is the same for SAMtools 1.10 (SAMtools 1.11 `index -c` generates the same CSI index).

When using 8 threads, the BAM file is also different, but CSI index from SAMtools 1.10 `--write-index` and `index -c` are different again (SAMtools 1.11 `index -c` generates the same CSI index). When generating the BAM file with SAMtools 1.11 using 8 threads (different BAM file than with SAMtools 1.10, slightly bigger), `--write-index` and `index -c` are the same.

**Comment by ghuls** [comment]
I guess I hit this with SAMtools 1.10: https://github.com/samtools/htslib/commit/e9863a0f149ea4d9e4336a061d7437952b6c7c8e

**Comment by daviesrob** [comment]
Adding `--no-PG` to your samtools 1.11 command-line should stop it from changing the headers, which will remove at least one cause of variability.

**Comment by ghuls** [comment]
@daviesrob Thanks for the tip.

It looks like SAMtools 1.10 had the bug when using `--write-index` and threads. With 1 thread it works fine and with SAMtools 1.11 with threading, it creates the correct index file.

I used the SAMtoools 1.10 generated BAM file and ran:
```
for nbr_threads in 1 2 4 8 ; do
    /software/SAMtools/1.10-foss-2018a/bin/samtools view -@ ${nbr_threads} --write-index --no-PG -o test.samtools_1.10.threads${nbr_threads}.bam test.bam
    /software/SAMtools/1.11-foss-2018a/bin/samtools view -@ ${nbr_threads} --write-index --no-PG -o test.samtools_1.11.threads${nbr_threads}.bam test.bam
done
```

```
test.bam        337188735
test.bam.csi    29853
test.samtools_1.10.threads1.bam 337188735
test.samtools_1.10.threads1.bam.csi     29900
test.samtools_1.10.threads2.bam 337188735
test.samtools_1.10.threads2.bam.csi     29853
test.samtools_1.10.threads4.bam 337188735
test.samtools_1.10.threads4.bam.csi     29853
test.samtools_1.10.threads8.bam 337188735
test.samtools_1.10.threads8.bam.csi     29853
test.samtools_1.11.threads1.bam 337188735
test.samtools_1.11.threads1.bam.csi     29900
test.samtools_1.11.threads2.bam 337188735
test.samtools_1.11.threads2.bam.csi     29900
test.samtools_1.11.threads4.bam 337188735
test.samtools_1.11.threads4.bam.csi     29900
test.samtools_1.11.threads8.bam 337188735
test.samtools_1.11.threads8.bam.csi     29900
```

```
❯ md5sum test.*bam
2cf75cc43d27b29c461ef554e603cc1f  test.bam
2cf75cc43d27b29c461ef554e603cc1f  test.samtools_1.10.threads1.bam
2cf75cc43d27b29c461ef554e603cc1f  test.samtools_1.10.threads2.bam
2cf75cc43d27b29c461ef554e603cc1f  test.samtools_1.10.threads4.bam
2cf75cc43d27b29c461ef554e603cc1f  test.samtools_1.10.threads8.bam
2cf75cc43d27b29c461ef554e603cc1f  test.samtools_1.11.threads1.bam
2cf75cc43d27b29c461ef554e603cc1f  test.samtools_1.11.threads2.bam
2cf75cc43d27b29c461ef554e603cc1f  test.samtools_1.11.threads4.bam
2cf75cc43d27b29c461ef554e603cc1f  test.samtools_1.11.threads8.bam

❯ md5sum test.*bam.csi
7abea808a63fb49e284e4839fbcf8267  test.bam.csi
ffc2c57dd075bd3d9fb44811c7549b83  test.samtools_1.10.threads1.bam.csi
7abea808a63fb49e284e4839fbcf8267  test.samtools_1.10.threads2.bam.csi
7abea808a63fb49e284e4839fbcf8267  test.samtools_1.10.threads4.bam.csi
7abea808a63fb49e284e4839fbcf8267  test.samtools_1.10.threads8.bam.csi
ffc2c57dd075bd3d9fb44811c7549b83  test.samtools_1.11.threads1.bam.csi
ffc2c57dd075bd3d9fb44811c7549b83  test.samtools_1.11.threads2.bam.csi
ffc2c57dd075bd3d9fb44811c7549b83  test.samtools_1.11.threads4.bam.csi
ffc2c57dd075bd3d9fb44811c7549b83  test.samtools_1.11.threads8.bam.csi
```

**Comment by valeriuo** [comment]
> With 1 thread it works fine and with SAMtools 1.11 with threading, it creates the correct index file.

Closing then.
