### ISSUE TITLE
samtools-collate takes a nap during work time

### ISSUE THREAD

**Issue by robmaz** [samtools/samtools#1388]
#### Samtools version
samtools 1.9
Using htslib 1.9
Copyright (C) 2018 Genome Research Ltd.

 #### Please describe your environment.
- CentOS-7/Linux 3.10.0-1160.el7.x86_64
- x86_64
- NA (installed from Epel package)

#### Please specify the steps taken to generate the issue, the command you are running and the relevant output.

$ 4mc -dz < small.sam.4mz | samtools collate -@ 1 -O -l 0 - > out.bam

This may occasionally hang after writing a partial output file, using no CPU.

- 4mc just unzips a compressed SAM file.
- out.bam would have ~40 Mb, so we are talking about small files here.
  This normally takes a couple seconds to run.
- 4mc has exited at this point.
- The output file is partially written when this occurs, and appears to end with a 
   well-formed record (both reads of a pair), but of course has no EOF block.
   It is also incomplete, but the number of written records varies substantially.
-  The phenomenon is not reproducible. Redoing it with the same input will 
   usually go through ok. I thus noticed it only when I did many such collates in
   parallel. 
-  Since this means there are some hundreds of these temporary collate*.bam 
   in /tmp, I assumed that the number of temporary files might be the problem. I 
   therefore increased the number of file descriptors for the user from 1024 to 
  10000, but that did not change anything. So that does not seem to be the reason.
- While this happens, other collate processes start, execute and finish ok, 
  so I don't think I'm running out of disk space or memory.

I wrote "nap" but currently it seems to be a forever nap. One hanging process
is going on 2 hours now and it doesn't look like it will ever wake up again.

Has anybody seen this before?

**Comment by daviesrob** [comment]
Does it work better without using the threads (`-@`) option?  You may be hitting some sort of deadlock problem - a few were fixed in release 1.10.  I suspect this is the most likely explanation if the failure appears to be random.

By default collate writes 64 temporary files, so you shouldn't need to change the number of file descriptors.

**Comment by robmaz** [comment]
Thanks, that was probably it. I haven't tried playing around with the options, but I can now confirm that the problem does not occur with 1.11.
