### ISSUE TITLE
Get unmapped reads from sam file

### ISSUE THREAD

**Issue by desmodus1984** [samtools/samtools#1389]
#### Is your feature request related to a problem? Please specify.
Hi,
I have assembled a genome, and I am trying to do a PSMC analysis. I forgot that I have to only use autosome scaffolds, so I am trying to filter autosomes (bat genome) using the scaffolds of chromosome X and Y from mouse- no such assembly from bat genomes so far.

#### Describe the solution you would like.
Thus, I mapped my scaffolds to the chromosomes Y and X, and I would like to get the unmapped reads -which should be only the autosomes.
I used the following code, which I thought was to get the unmapped reads:
samtools fasta -@ 48 -f 4 myse_some.sam > Autosome.fasta
and I got 4 scaffolds, technically, kinda correct, but I expected to have all but 4 scaffolds out of the 92.

Then, I ran:
samtools view -@ 40 -b -F 4 myse_some.sam | samtools fasta -@ 40 > autoZome.fasta
and I got the following report:
[W::bgzf_read_block] EOF marker is absent. The input is probably truncated
[bam2fq_mainloop] Failed to read bam record.
[bam2fq_mainloop] Error writing to FASTx files.: Inappropriate ioctl for device
[M::bam2fq_mainloop] discarded 0 singletons
[M::bam2fq_mainloop] processed 13 reads
I expected 88 scaffolds, but as you can see, I was only able to get 12.

The input sam file is about 18G, and the output was only 1.4 GB, which is sort of expected given that the genome assembly was only 1.9GB. 

Could you please help me what is the best approach to filter the reads/scaffolds mapping to the sex chromosomes?

Thanks;

**Comment by valeriuo** [comment]
This seems to be an issue, not a feature request. So please indicate what version of SAMtools/HTSlib you are using and what platform. Run `samtools --version` and `uname -orm`.

To retrieve the unmapped reads use `samtools -f4 myse_some.sam`.
To filter out the unmapped reads use `samtools -F4 myse_some.sam`

**Comment by desmodus1984** [comment]
Hi,

Thank you for the quick reply. I am running samtools 1.10 and htslib 1.10, and the platform is  Linux 3.10.0-1062.18.1.el7.x86_64 x86_64 GNU.

Best regards;



Juan Pablo Aguilar Cabezas

Ecology and Evolutionary Biology Ph.D. Student

Department of Biological Sciences

Ohio University, Athens OH

________________________________

**Comment by valeriuo** [comment]
> I used the following code, which I thought was to get the unmapped reads:
> samtools fasta -@ 48 -f 4 myse_some.sam > Autosome.fasta
> and I got 4 scaffolds, technically, kinda correct, but I expected to have all but 4 scaffolds out of the 92.

To filter out the unmapped reads use `-F 4` instead of `-f 4` in the `samtools fasta` options.

**Comment by desmodus1984** [comment]
Hi Valerio,
sorry to bother you. I would appreciate if you could help me interpret. As I mentioned I am interested in filtering out X/Y scaffolds from my assembly. I mapped my reads with minimap2, and I extracted the reads in a fasta file.

With the following code
samtools fasta -@ 48 -F 4 musXY.sam > musXY.sam.fasta
my fasta has empty sequences/ just the headers/ but one sequence: scaffold_m19_p_76 with data;
>scaffold_m19_p_1
>scaffold_m19_p_2
>scaffold_m19_p_3
...
>scaffold_m19_p_76
TGATCAGGAATGGGAACACCTGGGGATCCCAGTGCTGGGCTCCTGTCCCAGAGCTGCAGGGTTGGGGCTGGACTGTTTTTTCTTATGAGCAGAGTGGGCCCTATTTGCATGTCCTCCTTCTATATAGGGAGCTCTGGGGTTCAATACCTGCAAGGAGGGCAGTGTCTCCATGCAGTTGAGAGTGTCCTTGGGGAGAATCGTGTTATGTAAATATTTTAATAACTAAATA$
...
...
>scaffold_m19_p_88
>scaffold_m19_p_89
>scaffold_m19_p_91

On the other hand, the job with
samtools fasta -@ 48 -f 4 musXY.sam > musXY.f.sam.fasta
outputs a fasta with four sequences:
>scaffold_m19_p_65
GTTTAGCATTTTAACCATACAATTCAGTAACATTAAATACATTCATATTGTTGTGCAACTTTCTGAACCATTCTCTCCACACCTTTATCTTCAAAACTAAAACTCTGTATCCATTAAATAACTCTCCATTGTCTCCCTGCCACCCAGCCCTGGCAACCATGATTCTACTTTTGTCTCTGTGAGTTTGACTATTCTAGGTATCTCATATAAATGGAATCCTATAAAGTGC$
>scaffold_m19_p_75
GGCAGGAAGGTTGGCTGCAGAAAGCAAAGGGCCCAGCAGGAACCCCAGGATGGTCAGCGGTGGTGGCATTTCACTCTGTCCCTTTGGAGGGATATGATTGCTGCTCCCAAGAGACACAGAAAGGTTCAGTCTGGTCTAAGCAGAGTCTGCTCCTGTCTCTATTGAACTCAACACAAGCAGGAAAATTGCATCATTCAAATGATGAAGGCCAGGTAATCCAGAGTCATGG$
>scaffold_m19_p_90
ACCGGACACCCCACCAACAGGCCCCTTCCCCCGCACACTTGGGACTGAAGATGGAAGGGTGCTGCCCGGCCGGGGGCTACGTGGGTTTAAAACTGTCCCCGTAAAAGTTTCAGATCTGATCTGAGCCAGGGCGGAGTCCTAGGTTTGGGGTGTCATTTCCTGAGCGGGGTGAGCACTGGAAGGCAGCTGATGGCTATTTCCCTGTCAGACCCATGGGAACGGCCTTGGG$
>scaffold_m19_p_92
TGAATTGGGCCTCTAGTTTATAATAATGAAGACCAAAAACAATGTAAATGAAAAAGGAATGATTAAATAAATTATATCATATTCATTTAATGAGAACTATGTGCCATACATACATAGTTATATAGATACATAGGTAGATACAAAGATACATAGACCATAATTTTGTAAAAATAATACAAAGAAAAAAAAGGAAGAAAGAAATGAAGGTAATGCATTCAATAGAAGACCT$

I am trying to interpret these correctly because I do not want to inadvertently and wrongly eliminate autosomal/non-X/Y scaffolds.
With "-f 4" I retrieved the unmapped reads but my fasta had four sequences, while with "-F 4" I filtered out the unmapped reads, and the fasta file had one sequence with the rest empty. Any reasons for the output with "-F 4" had all empty sequences but one?

Thanks for the help.

**Comment by valeriuo** [comment]
With samtools 1.10 you could get empty scaffolds in the FASTA file if the originating reads from the SAM file had a missing sequence (**\***). The current samtools code, which is due to be released in the following weeks, has eliminated this behaviour.
What does the command `samtools view musXY.sam | grep -n "scaffold_m19_p_[1|7]" | cut -f1,10 ` show?

**Comment by desmodus1984** [comment]
It ouputs several  sequences.
{module load samtoolssamtools view musXY.sam | grep -n "scaffold_m19_p_[1|7]" | cut -f1,10}
head slurm-4424686.out
1:scaffold_m19_p_1      ACACACACAGTGTACATAGCACACACAGTGTATATGACACACACCATATACACACCGAACAACACACACCTACACACACCGGTATACACACACAGTGTTACACAACACACAGTGTATATGACACACACACATACGCACACCAACACACACCTACACACACCGGTATACACACACAGTGTACACAACACACACAGTGTATATGACACACACACATATACACACACGAACACACACCTACACACACCGGTATACACACATAGATCCACAACACACCTAGTGTATATGACACACACACATATACACACACGAACACACACCTACACGCACCGGTATACACACACAGTGTACACAGCACACACAGTGTATATGACACACACACACATACACACACAACACACACCTACACACACCGGTATGCACACACGATAACAACACACACAGTGTATATGACACACACCAACACACACCAACACACACCTACACACACCGGTATGCACACACAGTGTACACAGCACACCTAGGTATATGACACACACACATATATAACACACCAACCCACACCTACACACACCGGTATACACAACAGTGTACACAGCACACACAGTGTATATGACACACCACATATACACACAACGAACCCACACCTACACACGCCGGTATACACACACAGTGTACACAACACACACAGTGTATATGACACACACACAGATACACAACACACCAACACACACCTACACACACCGGTATACACACACAGTGTACACAGCACACACAGTGTATATGACACACACACACCTACACACACCGGTATACACACACAGATACACAACACAACACAGTGATATGACACACACACACATACGCACACCACCACACACCTACACACACCTACACACACCGGTATGCACACACAGATACACAACACACACAGTGTATATGACACACACACATATACACACAACACACACACACCTACACACACCGGTATGCACACACAGATACACAACACACACAGTGTATATGACACACACACACATACACACACCAACACACACCTACACACACCGGTATACACACACAGATACACAACACACCTAGTGTATATGACACACACACACATACGTACACCAACACACATCTACACACACACCGGTATACACACACAGATACACAACACCCAGTGTATATGACACACACACATATACACACACGAACACACACCTACACACACACCGGTATACACACACAGATACACAACACACACAGTGTATATGACACACACACACCTACACACACACCGGTATACACACACAGATACACAACACACAGTGTATATGACACACACACACATACGCACACCAACACACATCTACACACACACCGGTATACACACACAGATACACAACACACCTAGTGTATATGACACACACACACATACGCACACCAACACACATCTACACACACACCGGTATACACACACAGATACACAACACACCTAGTGTATATGACACACACACACATACGCACACCAACACACATCTACACACACACCGGTATACACACACAGATACACAACCACAGTGTATATGACACACACACATACACACACGAACACACATCTACACACACACCGGTATACACACAGAGATACACAGCACACCTAGTGTATATGACACACACACATACAAACACGAACACACAACTACACACACCGGTATACACACACAGATACACTACACACACAGTGTATATGACACACACAAACATACGCACACCAACACACACCTACACACACACCGGTATACACACCAGATACACAACACACACAGTGTATATGACACACACACACATACACACACGAACACACACCTACACACACCGGTATACACACACAGATACACAAAACACCTAGTGTATATGACACACACACATATACACACACCAACACACACCTACACACACACCGGTATACACACACAGTGTACACAGCACACCTAGTGTATATGACAACACACATACACACACCAACACACACCTACACACACACCGGTATACACACACAGTGTATATGACACGCACACACATACGAACAACACACACCTACACACACCGGTATACACACACAGTGTATATGACACACACACACATATGCACACCTACACACACCAGTATACACACACAGATACACAGCACACCTAGTGTATATGACACACACACATACACACACCAACACACACCTACACACACCGGTATACACACACAGTGTACACAGCACACACAGTGTATATGACACACACACATATACACACACGAACACACACCTACACACACCGGTATACACACACAGTATACACAACACACACAGTGTATATGACACACACACATATATACACACACCAACACACACCTACACACACCGGTATACACACAGTGTACACAGCACACACAGTGTATATGACACACACACATATACACACACGAACACACACCTACACACACCAGTATACACACACAGTGTACACAGCACACACAGTGTATATGACACACACACACCTACACACACCGGTATACACACACAGATACACAACACACACAGTGTATATGACACACACACACATACACACACGAACACACACCTACACACACACCGGTATACACACACAGTGTACACAGCACACCTAGTGTATATGACACACACACATATATGACACACCAACACACACCTACACACACCGGTATACACACACACACAACACACACAGTGTATATGACACACACACATATACACACACCAACACACACCTACACAGACCGTATGCACACACAGATACACAGCACACCTAGTGTATATGACACACACACATTTATACACACACCAACACACACCTACACACACACCGGTATACACACACAGATACCCAACACACACAGTGTATATGACACACACACACATACACACACCAACACACACCGGTATGCACACACAGATACACAACACACACAGTGTATATGACACACACACACCTACACACACCGGTATACACACACAGATACACAACACACCTAGTGTATATGACACACACACACATACACACACCAACACACACCTACACACACCGGTATGCACACACAGATACACAACACACACAGTGTATATGACACACACACACATACACACACCAACACACACCTACACACACCGGTATACACACACAGTGTACACAGCACACACAGTGTATATGACACACACACACATACACACACCAACACACACCTACACACACCGGTATGCACACACAGATACACAACACACACAGTGTATATGACACACACACACCTACACACACCGGTATACACACACAGATACACAACACACACAGTGTATATGACACACACACACATACACACACCAACACACACCTACACACACCGGTATGCACACACAGTGTACACAGCACACCTAGTGTATATGGCACACACACATATATACACACACCAACACACACCTACACACACCGGTATACACACACACACAACACACACAGTGTATATGACACACACACATATACACACACCAACACACACCTACACACACCGGTATGCACACACAGATACACAACACACCTAGTGTATATGACACACACACATACACACACCAACACACACCTACACACACACCGGTATACACACACAGATACACAACACACACAGTGTATATGACACACACACACATACGCACACCAACACACACCTACACACACACCGGTATACACACACAGATACACAACACACAGTGTATATGACACACACACACATACACACACGAACACACACCTACACACACACCGGTATACACACACACACAACACACACAGTGTATATGACACACACACACATACGCACACCAACACACACCTACACACACCAGTATACACACACAGTGTGTA
...
tail slurm-4424686.out69209:scaffold_m19_p_78 *69210:scaffold_m19_p_78 ATCAGTGGTTCTCAACCTTCTGGCCCTTTAAATAGAGTTCCTCATGTTCTGACCCAACCATAAAATTATTTTCTTGGCTACTTCATAACTGTAATGTTGCTACTGTTATGAATCATAATGTAAATATCTCATATGCAG69211:scaffold_m19_p_79 TCTCTCTCTCCCTCTCTCTCCCTGTCTCTCTCTCTCTCTCTCTCTCTCTCTCTCTCTCTCTCTCTCCCTGTCTCTCTCTCTCTCTCTCTCTCTCTCTCTCTCTCTCTCTCTCTCTCTCTCCATCGTCTCTGTGCGCCCGGCAATCCCACTCTGGGTTTCTACCCCAAAGGACCGAAAGCAGAACCTTGGGTGCCTGCACCCTGTGTGCCAGCAGCAGGTTCACAGCGGCCCAGAGGCGGGGCCAGGCCAGTGTCCACGGGCCGATGGCAGGTGAACAGCGGAGACCCTGCCTCGTGCTGCAGCCTGGAGGGGCCTGGGGGATGTGCTGAGTGAGAGGAGCCAGCCACAGAGGACACGGACTGCGGGTTCCCTGTGCTGAGGCACCTGGAGACATCCAGGTCAGCGAGAGGCAGAGAATGCTGGGAGCCAGGCGTTAGGGTAGGGTTAGGGTTAGGGTTAGTGTTACGGTTAGGGTCAGGGTCGGTGTCAGGGTTAGGGTGAGGGTTAGGGTTAGGGTCAGGGTCGGTATCAGGGTTAGGGTGAGGATTAGGGTTAGGGTCAGGGTCGGTGTCAGGGTTAGGGTGAGGGTTAGGGTTAGGGTTAGGGTTAGGGTGAGGGTGAGGGTTAGGGTTAGGGTGAGGGTGAGGGTGAGGGTTAGGGTTAGGGTTAGGTTTAGGGTTAGGGTTAGGGTGAGGGTTAGGGTTAGGGTGAGGGTTAGGGTTAGGGTCAGGGTTAGGGTCAGCGTCAGGGTCAGTTTAGGTTCAGGGCCTGGGTAAGTGTCAGGGTCAAGGTCAGTTTCAGGGTTTGTGTTAGGTTTATCATCAGGGTCAGTTTAGGGTCAGTGTCAGGGTTAGGGTCAGGGTCATGGTCAGGTTCAGGTTAGGGTTAGGGTCAGGGTTAGGGTTAGGGTTGTTAGGATTAGGGTGAGGGTGAGGGTTATGTTTAGCGTTAGGGTTAGGGTTAGGGTTAGGGTTAGGGGTGATGGTGAGGGTTAGGCTTAGGGTGAGGGTTAGGGTTAGTGTGAGGGTTTGGGTTAGGGTGAGGGTTAGGGTTAGGGTCAGGGTCAGTGTCAGGGTCAGGGTGAGGGTTAGGGTTAGGGTCAGGGTCGGTGTCAGGGTTAGGGTGAGGGTTAGGGTGAGGGTCAGGGTTAAGGTTAGGGTCAGGGTAACAAAACAAAACAAAACATTGTGATTAGAAACACATCTAGTTTTTATATAGTTTGACTAGTTCAAACAGGACAAGCCCTGGCTGGTGTTGCTCAGTGGATAGAGCATCGGCCCATGGCCTGAAGGGTCCCGGGTTCGATTCCTTGATCCCCAGTAGGGGGCGTGCAGGAGGCAGCCGATCCACAATTCTGCCTCCTCATCCTTGTCCCTATCTCTCCCTCTCCCTTCCTTTCTGAATTCAATAAAAATAAAATAATATAAAATGAAAACAGGGCGACCGGTGTCCCTGGGTCCCAGGGGGAGATGCTCGCTCCTGTGCTTTCGGAGAGGCTGGCGCCTGGACCTGCCGCGCTCCCGCCACCAGAGGGCACTGCAGGACCACGGATCCGCGCTGCCCTGGCGGTCCCGCCGCTGGGGCTGCCCACGGGCCTTGCCCTGGAGTTTGGGGCGGCGCCGTGTCCTGGTTCTGCTCCCCAACCTTCGATGCATGAAAATCACCATGGAAACCACCTCCCGCCAGCGCCCCAGAGCTTCCTGTTTGGGGAGCAACTGAGAGGGATCTCTGCTCCGAGGCGCGGAGGCGCACCCGCGTGTGCCCACCCTCACCTCCGGTAGCAGCCCCCGCCCCCCGCCCCCCAAGGGGGACAAGTCAACAAATAGGGAAAAAAACAACAACAATCAAGGGCGAAGAGTCGGTCCCTTTGAGGAAACGGACGCCTGGCATTGAGGATGGCGGAGAGCATCTTAGGGCGCTGGTGACGCCCGGGGTGAGGCCCCCCGTGGGGCTGGGTCTGTGGACGGGGAGGCGAGGGAGCGGGTCTTCACGCTCCTGTTGGGAACCCCCCCCCCCAAGACGAGGCTGCCGGGGGAAGCCAGCTTTCGTGGAAATTTGCGGTGCACGTCACGCCCAGCTTCCTCCCGGGCTTCTATTAAGAGGAAAAAAGAAAAAAAAAAGCCCGGCCCGTGTGGCTCAGGGGCTGAGCGAGGACCTAGGAACCTTCAGGTCACGGTTGGATTCCCGGTCCGGGCTCAGGCCCGGGTTGCAGGCTCCACCCCCACCAGCAGGGGGCGCGCAAGAGGCAGCCGGTCCATGATGCCCTCTCATCATTGATGTTTCTCTCCCTCTCCCTCTTTCTTCTTCTCTGAAGTCAATAAAAATATATCTTTTTTTTTTTTTTAAGAAAGAGGAAAAAAGAGAGTTGTTCTAATCCGGAGGTTTTCCCAGCCAACGCGGACCCCCGGGCCTGCGTGGGTGTCTCCCACCCACACCCTTGACGGGCCGCTGTCTCCCCGGCCGCCCCCCTGTCTTCGCGGCCGGGTGTCCTGCCCACACCTGGCAGCGTCCCTCCCACCGCCGCCCGCTCCCGGGCCGAGCGGGTAATTCTGGAAACGGCCGCTCGGAACATTTGTTTTCTGGAGCGACAACAACCCCAACCGCCTCGTGTAAGAGCCGGCTGCACACAGCACGACCAATTAGCGCTATTTAATTACTGACAGCCCAGCTTCCAAATTGATTCCCGGCCCCGCGGAGGAAACACGGAGGCTGGGAGGGAAGCAGATTCCTGACAATTAATCGGAGAGAAAGGGGGCGGGCGCTGGGCAGGGAGCCGTCCAGGGGCGCGCGATGCGGGTCGAGGGCCTGGCTGGCCTG....
69212:scaffold_m19_p_79 GGGTTAGGGTGAGGGTTAGGGTTAGGGTTAGGGTTAGGGTGAGGGTGAGGGTTAGGGTTAGGGTGAGGGTGAGGGTGAGGGTTAGGGTTAGGGTTAGGTTTAGGGTTAGGGTTAGGGTGAGGGTTAGGGTTAGGGTGAGGGTTAGGGTTAGGGTCAGGGTTAGGGTCAGCGTCAGGGTCAGTTTAGGTTCAGGGCCTGGGTAAGTGTCAGGGTCAAGGTCAGTTTCAGGGTTTGTGTTAGGTTTATCATCAGGGTCAGTTTAGGGTCAGTGTCAGGGTTAGGGTCAGGGTCATGGTCAGGTTCAGGTTAGGGTTAGGGTCAGGGTTAGGGTTAGGGTTGTTAGGATTAGGGTGAGGGTGAGGGTTATGTTTAGCGTTAGGGTTAGGGTTAGGGTTAGGGTTAGGG69213:scaffold_m19_p_79 *69214:scaffold_m19_p_79 *69215:scaffold_m19_p_79 *69216:scaffold_m19_p_79 *69217:scaffold_m19_p_79 CTCACCCTAACCCAAACCCTCACACTAACCCTAACCCTCACCCTAAGCCTAACCCTCACCATCACCCCTAACCCTAACCCTAACCCTAACCCTAACGCTAAACATAACCCTCACCCTCACCCTAATCCTAACAACCCTAACCCTAACC69218:scaffold_m19_p_79 *
Is this output the expected?


Juan Pablo Aguilar Cabezas

Ecology and Evolutionary Biology Ph.D. Candidate

Department of Biological Sciences

Ohio University, Athens OH

________________________________

**Comment by valeriuo** [comment]
There's a new [release](https://github.com/samtools/samtools/releases/tag/1.13) out. Could you please download it (together with [HTSlib](https://github.com/samtools/htslib/releases/tag/1.13)) and run your pipeline again?

**Comment by desmodus1984** [comment]
Hi,
I tried installing it - I am in a cluster, and I got the following error message
gcc -Wall -g -O2 -I. -Ihtslib-1.13 -I./lz4  -c -o test/split/test_expand_format_string.o test/split/test_expand_format_string.cgcc  -L./lz4  -o test/split/test_expand_format_string test/split/test_expand_format_string.o test/test.o libst.a htslib-1.13/libhts.a -lpthread -lz -lm -lbz2 -llzma -lcurl -lcrypto -lz  -lpthreadgcc -Wall -g -O2 -I. -Ihtslib-1.13 -I./lz4  -c -o test/split/test_filter_header_rg.o test/split/test_filter_header_rg.cgcc  -L./lz4  -o test/split/test_filter_header_rg test/split/test_filter_header_rg.o test/test.o libst.a htslib-1.13/libhts.a -lpthread -lz -lm -lbz2 -llzma -lcurl -lcrypto -lz  -lpthreadgcc -Wall -g -O2 -I. -Ihtslib-1.13 -I./lz4  -c -o test/split/test_parse_args.o test/split/test_parse_args.cgcc  -L./lz4  -o test/split/test_parse_args test/split/test_parse_args.o test/test.o libst.a htslib-1.13/libhts.a -lpthread -lz -lm -lbz2 -llzma -lcurl -lcrypto -lz  -lpthreadgcc -Wall -g -O2 -I. -Ihtslib-1.13 -I./lz4  -c -o test/vcf-miniview.o test/vcf-miniview.cgcc  -L./lz4  -o test/vcf-miniview test/vcf-miniview.o htslib-1.13/libhts.a -lpthread -lz -lm -lbz2 -llzma -lcurl -lcrypto -lz  -lpthreadmkdir -p -m 755 /usr/local/bin /usr/local/bin /usr/local/share/man/man1install -p samtools /usr/local/binmake: *** [install] Error 1
I downloaded the .tar.bz2 file, unzipped, and then ./configure make and make install as mentioned in the INSTALL file, but it seems that make failed.
./configure ran without any issues.
$ ./configurechecking for gawk... gawkchecking for gcc... gcc....
checking for libdeflate_deflate_compress in -ldeflate... nochecking for curl/curl.h... yeschecking for curl_easy_pause in -lcurl... yeschecking for CCHmac... nochecking for library containing HMAC... -lcryptochecking for library containing regcomp... none requiredchecking whether PTHREAD_MUTEX_RECURSIVE is declared... yesconfigure: creating ./config.statusconfig.status: creating config.mkconfig.status: creating htslib.pc.tmpconfig.status: creating config.hconfig.status: linking htscodecs_bundled.mk to htscodecs.mk
Thanks;



Juan Pablo Aguilar Cabezas

Ecology and Evolutionary Biology Ph.D. Candidate

Department of Biological Sciences

Ohio University, Athens OH

________________________________

**Comment by whitwham** [comment]
Does running **make** by itself (without the **install**) work?

If it does then try **make install** again.  It looks like there should be an error message before `make: *** [install] Error 1` but I'm not seeing one.

**Comment by desmodus1984** [comment]
The make had error and hence make install didn't run.
I tried make again and got this message:

then tried make install and got this:
make installcd htslib-1.13 && make htslib_static.mkmake[1]: Entering directory `/fs/scratch/PHS0338/appz/samtools-1.13/htslib-1.13'sed -n '/^static_libs=/s/[^=]*=/HTSLIB_static_LIBS = /p;/^static_ldflags=/s/[^=]*=/HTSLIB_static_LDFLAGS = /p' htslib.pc.tmp > htslib_static.mkmake[1]: Leaving directory `/fs/scratch/PHS0338/appz/samtools-1.13/htslib-1.13'mkdir -p -m 755 /usr/local/bin /usr/local/bin /usr/local/share/man/man1install -p samtools /usr/local/binmake: *** [install] Error 1
What should I check for if everything worked ok?

Thanks;


Juan Pablo Aguilar Cabezas

Ecology and Evolutionary Biology Ph.D. Candidate

Department of Biological Sciences

Ohio University, Athens OH

________________________________

**Comment by whitwham** [comment]
> The make had error and hence make install didn't run.
> I tried make again and got this message:
>
> then tried make install and got this:

_The rest snipped for brevity_

There is no error message here.  It is not showing on GitHub or the email that gets forwarded to me.

**Comment by daviesrob** [comment]
`make install` may be failing because you don't have permission to write to `/usr/local`.

Did `make` manage to make a samtools binary?  You should be able to test this by looking for and trying to run `/fs/scratch/PHS0338/appz/samtools-1.13/samtools`.

**Comment by desmodus1984** [comment]
Hi,
I see that make did indeed generate the samtools executable file.
Then I ran the code:
/fs/scratch/PHS0338/appz/samtools-1.13/samtools fasta -@ 48 -f 4 musXY.sam > musXY.f.Sam.fas/fs/scratch/PHS0338/appz/samtools-1.13/samtools fasta -@ 48 -F 4 musXY.sam > musXY.F.Sam.fas
and I only got the output from -f 4. What confuses me is that I am interested in finding the scaffolds of my assembly that match the X or Y chromosome of mouse, my assembly is from a bat, and technically/theoretically -f is used to output alignments with an specific Flag and that is "unmapped reads".

My procedure was:
I created the index of the mouse X-Y fasta with minimap 2
./minimap2 -x map-ont -t 48 -d musXY.mmi musX_Y.fasta
then I mapped my scaffolds
./minimap2 -t 48 -a musXY.mmi SuperExt.scaff.fasta > musXY.sam
Did I miss any step or am I misinterpreting something wrong? or are those 4 scaffolds the ones that match the mouse X/Y chromosomes.

Thanks,



Juan Pablo Aguilar Cabezas

Ecology and Evolutionary Biology Ph.D. Candidate

Department of Biological Sciences

Ohio University, Athens OH

________________________________

**Comment by valeriuo** [comment]
> and I only got the output from -f 4. What confuses me is that I am interested in finding the scaffolds of my assembly that match the X or Y chromosome of mouse, my assembly is from a bat, and technically/theoretically -f is used to output alignments with an specific Flag and that is "unmapped reads".

This means you only have unmapped reads in your **musXY.sam** file.
What does `samtools view -c -F4 musXY.sam` show?

**Comment by daviesrob** [comment]
It might be useful to see the output of `samtools flagstat musXY.sam`.

**Comment by desmodus1984** [comment]
The output of flagstat is
69305 + 0 in total (QC-passed reads + QC-failed reads)92 + 0 primary427 + 0 secondary68786 + 0 supplementary0 + 0 duplicates0 + 0 primary duplicates69301 + 0 mapped (99.99% : N/A)88 + 0 primary mapped (95.65% : N/A)0 + 0 paired in sequencing0 + 0 read10 + 0 read20 + 0 properly paired (N/A : N/A)0 + 0 with itself and mate mapped0 + 0 singletons (N/A : N/A)0 + 0 with mate mapped to a different chr0 + 0 with mate mapped to a different chr (mapQ>=5)
Can you suggest on any configuration to try to map differently the scaffolds to the mouse X-Y "chromosome"?


Juan Pablo Aguilar Cabezas

Ecology and Evolutionary Biology Ph.D. Candidate

Department of Biological Sciences

Ohio University, Athens OH

________________________________

**Comment by desmodus1984** [comment]
What I got from view -c -F4 was 69301
How should I interpret that? I only have 94 scaffolds mapped against two mouse "scaffolds".

Thanks;


Juan Pablo Aguilar Cabezas

Ecology and Evolutionary Biology Ph.D. Candidate

Department of Biological Sciences

Ohio University, Athens OH

________________________________

**Comment by valeriuo** [comment]
> What I got from view -c -F4 was 69301
How should I interpret that? I only have 94 scaffolds mapped against two mouse "scaffolds".

By default, `samtools fasta` filters out the secondary and supplementary reads. So when you run `samtools fasta -F4` you are actually telling the program to output only the primary mapped reads, 88 in total. On the other hand, `samtools view -F4` shows you all the mapped reads, including secondary and supplementary,  69301 in total. To get the same number with `view`, you should issue the command as `samtools view -c -F 0x904 musXY.sam`.

**Comment by valeriuo** [comment]
Hopefully, you managed to sort out your data. Please reopen if any issues are still present.

**Comment by desmodus1984** [comment]
Hi,
Hope you are doing all right.

I contacted a colleague and he suggested me to try mapping using a chromosome X/Y from a reference bat genome assembly since the evolutionary distance might be a problem.

I did the same, I download the bat chr-X, used minimap2 to make a reference from it, and then mapped my scaffolds to it.

The results from fragstat are:
184303 + 0 in total (QC-passed reads + QC-failed reads)
509 + 0 secondary
183702 + 0 supplementary
0 + 0 duplicates
184303 + 0 mapped (100.00% : N/A)
0 + 0 paired in sequencing
0 + 0 read1
0 + 0 read2
0 + 0 properly paired (N/A : N/A)
0 + 0 with itself and mate mapped
0 + 0 singletons (N/A : N/A)
0 + 0 with mate mapped to a different chr
0 + 0 with mate mapped to a different chr (mapQ>=5)

and the results from view -c -F4 is 184303

As mentioned before,  I am interested in finding which of the primary scaffolds - 92, map to the X.

I used the following commands to retrieve the scaffolds as fasta:
/fs/scratch/PHS0338/appz/samtools-1.13/samtools fasta -@ 24 -f 4 phidisX.sam > phidisX.sam.f.fas
/fs/scratch/PHS0338/appz/samtools-1.13/samtools fasta -@ 24 -F 4 phidisX.sam > phidisX.sam.F.fas
and both were empty.

Can you suggest any other way to try to identify which of my scaffolds (pair) correspond to the X?
If I include the Y chromosome together with the X, will that make any difference?

Thanks;

**Comment by jkbonfield** [comment]
I don't understand what you're wanting.

You claim to haver mapped against X, and samtools stats claims 100% of reads have mapped against it.  So surely you already know which scaffolds correspond to X - it's all of them!  However you have a number 92 coming from somewhere.  I don't see that in the stats you quote.  Are you mixing up raw reads (many) and consensus sequences (hopefully few)?  Obviously samtools can only give you information on the type of data that you mapped.  Or is this difference due to a high number of supplementary alignments, eg a few primary sequences that have been broken into many fragments.

If the figure above wasn't 100%, then indexing the BAM and doing "samtools view foo.bam X" would return only the ones that match against X.  Also if you include Y too then you may find some reads align there instead, or possible in addition to X.  It's a safer strategy, and then using the index to only query X will give you a more meaningful result.  You may also wish to turn off secondary alignments (perhaps also supplementary depending on the similarly between the assembly and the reference).

If you want to work out which of the supplementary alignments come from the one single source fragment, then you can extract the query name only (first field) and sort / uniq it with a Unix command line.  Eg:

```
samtools view file | awk '{print $1}' | sort -u
```

Note: None of this is a samtools "issue" per se (github is used for bug reports and feature requests mainly), but a general bioinformatics question.  You'll probably get a faster turnaround time on questions such as this using biostars as it's read by several orders of magnitude more people.

**Comment by desmodus1984** [comment]
Hi James,

Thanks for the information. I have done what you mentioned - using the Biostars forum, and nobody has answered or helped until now; and moreover, someone previously posted a similar question and I was the only one that responded to it.

Hope you don't mind me asking another question. Before indexing the BAM, should I sort it?
Sorry, I am new to this and all the help is highly appreciated.

**Comment by daviesrob** [comment]
Yes, the indexes only work on position sorted files so you do need to sort first.  Or do both at the same time by using `samtools sort --write-index`.
