### ISSUE TITLE
samtools coverage unbounded memory usage (lacks -d/--depth parameter)

### ISSUE THREAD

**Issue by d-cameron** [samtools/samtools#1395]
Version: 1.11-3-g7028dd4 (using htslib 1.10.2-145-g8016127)

Running `samtools coverage` has unbounded memory usage and will crash if there exists a region of very high coverage.

Potential solutions are:
- Added a `-d` parameter similar to `samtools depth`
- Redesign algorithm to only load 1 read at a time.

The former is simpler, the later is much more memory efficient and can correctly report depth for high-coverage samples. The only output that requires look-ahead is the coverage field and that only requires 1 bit per position with the max length of the positional look-ahead bounded by (reference) length of the longest read alignment.

#### Please specify the steps taken to generate the issue, the command you are running and the relevant output.

The following test case causes `samtools coverage` to use of over 10GB memory:
```
#!/bin/bash
two_to_the_n=25
compressable_data=AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
echo "@SQ	SN:$compressable_data	LN:1000" > test_depth_header.sam
echo "$compressable_data	0	$compressable_data	1	60	200M	*	0	0	$compressable_data	$compressable_data" > test_depth_1.sam
for i in $(seq 2 $two_to_the_n) ; do
	last_file=test_depth_$(($i-1)).sam
	cat $last_file $last_file > test_depth_${i}.sam
done
cat test_depth_header.sam test_depth_${two_to_the_n}.sam | samtools -@ $(nproc) view -b - > test_depth_${two_to_the_n}.bam && rm test_depth_*.sam
samtools coverage test_depth_${two_to_the_n}.bam
```

**Comment by valeriuo** [comment]
The default maximum depth has been reset from `INT_MAX` to 8000. Also, the first solution was already half baked into the code, so it was just a matter of tidying things up.

**Comment by quacksawbones** [comment]
With regards to samtools coverage, is there any way to set the "minimum" depth for the purposes of calculating coverage? As opposed to extracting the depths from the bam file, filtering out regions below a specified depth, creating a bed file, then recalculating using this new bed file? (Initially placing here as I am unsure if it's ballpark related to this issue).

**Comment by jkbonfield** [comment]
That sounds more like a post-processing option on samtools depth rather than coverage, which is primarily a plotting tool.
