### ISSUE TITLE
DP and DP4 vary hugely mpileup

### ISSUE THREAD

**Issue by arumds** [samtools/samtools#1405]
#### Command
`samtools mpileup -ABugf ref.fasta -l regions.bed -d 1000000 input.bam | bcftools call -vc -Ov > output.vcf`

```
$ grep "236899904" SAM.vcf 
chr1	236899904	.	CT	C	10.6173	.	INDEL;IDV=1;IMF=0.00401606;DP=249;VDB=0.64;SGB=-0.453602;MQ0F=0;AF1=1;AC1=2;DP4=0,0,0,2;MQ=60;FQ=-40.525GT:PL	1/1:49,6,0
```
Could someone help to understand why raw DP and DP4 differ hugely although no filters were applied in mpileup command?

**Comment by arumds** [comment]
Thank you. Could you let me know what filtering has been applied on DP4?
And “high quality bases” means “high quality reads” supporting the base
pair?

On 30. March 2021 at 16.36.34, Petr Danecek ***@***.***)
wrote:

The command samtools mpileup is deprecated and should not be used, please
use bcftools mpileup instead.
As for the different values, DP is raw read depth whereas DP4 are high
quality bases, after filtering has been applied.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/samtools/samtools/issues/1405#issuecomment-810251582>,
or unsubscribe

**Comment by pd3** [comment]
Check the defaults for `-Q, --min-BQ` and `--ff, --excl-flags`:
```
-Q, --min-BQ INT        skip bases with baseQ/BAQ smaller than INT [13]
 --ff, --excl-flags STR|INT  filter flags: skip reads with mask bits set [UNMAP,SECONDARY,QCFAIL,DUP]
```

**Comment by arumds** [comment]
Dear Peter,

The DP4 has DP4=0,0,0,2 while DP=249.

It might be that there are only 2 reads passing the threshold supporting
the base call. However, why is the read depth zero for the reference allele?

On 30. March 2021 at 16.43.34, Petr Danecek ***@***.***)
wrote:

Check the defaults for -Q, --min-BQ and --ff, --excl-flags:

-Q, --min-BQ INT        skip bases with baseQ/BAQ smaller than INT [13]
 --ff, --excl-flags STR|INT  filter flags: skip reads with mask bits
set [UNMAP,SECONDARY,QCFAIL,DUP]

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/samtools/samtools/issues/1405#issuecomment-810259277>,
or unsubscribe

**Comment by pd3** [comment]
The filtering is applied to all reads and bases, regardless of which is the reference.

**Comment by arumds** [comment]
Dear Petr,

In summary, the remaining 247 reads other having reference allele or
non-reference allele do not meet the default cutoffs by mpileup algorithm?

In order to reduce false positives, we should set the read depth cut-off
 based on DP4 instead of DP?

On 30. March 2021 at 19.49.29, Petr Danecek ***@***.***)
wrote:

The filtering is applied to all reads and bases, regardless of which is the
reference.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/samtools/samtools/issues/1405#issuecomment-810417066>,
or unsubscribe
