### ISSUE TITLE
Samtools fails to produce VCF

### ISSUE THREAD

**Issue by twang15** [samtools/samtools#1406]
### Environment
- samtools version 1.11
- OS: Darwin 19.3.0
- x86_64
- clang version 11.0.0 (clang-1100.0.33.17)

### Desription: 
Go to samtools manual page: http://www.htslib.org/doc/samtools-mpileup.html. It says "**Samtools mpileup can still produce VCF and BCF output (with -g or -u)**", but with either -g or -u, I failed to see vcf output

### Data: 
you can download chr21.fa and test.sort.bam here: https://github.com/twang15/Long-read-RNA

### Steps:
1. samtools mpileup -g -f chr21.fa test.sort.bam, this way I can only get bcf in the terminal

OR

1. samtools mpileup -u -f chr21.fa test.sort.bam, only gives me unreadable output

### Expectation: 
with either of the above command, I should be able to see human-readable VCF output.

**Comment by whitwham** [comment]
The man page also says **"but this feature is deprecated and will be removed in a future release. Please use bcftools mpileup for this instead."** So if you want to see BCF\VCF use bcftools, it is much better.

Also, to answer your question, to see a human readable VCF use the -u -v options (but really, use bcftools instead).
