### ISSUE TITLE
How to see QNAMEs?

### ISSUE THREAD

**Issue by twang15** [samtools/samtools#1407]
In Samtools documentation, it says "--output-QNAME
Output an extra column containing comma-separated read names. Equivalent to --output-extra QNAME". 

Does this still work? 
If so, how can see the QNAME list?

**Comment by whitwham** [comment]
What command are you trying to run?

**Comment by valeriuo** [comment]
Yes, it still works.
`samtools mpileup --output-QNAME <your_alignment_file`
The `QNAME` list will appear as a comma separated string in your mpileup output.
Please read the documentation more carefully and only open issues on GitHub if you encounter errors running the commands.
