### ISSUE TITLE
How to use samtools/bcftools mpileup to get QNAME?

### ISSUE THREAD

**Issue by twang15** [samtools/samtools#1409]
I have asked two separate questions before:
1. https://github.com/samtools/samtools/issues/1407
2. https://github.com/samtools/samtools/issues/1406

but they did not solve my problems which I should state more clearly. 

### My Questions
The objective: given a position in the reference sequence (e.g., chr21	5116347), I should be able to answer the following questions:
1. which sample reads (identified by their QNAMEs) **agree** with the reference position
2. which sample reads (identified by their QNAMEs) **disagree** with the reference position

### What I have tried:
0. with a command like **_samtools view test.sort.bam | head -3_**, I got the following output, and the first column is the sample read QNAME:

       7001028:661:CA5PUANXX:8:1212:14639:10657___1-NPC12_BC108	99	chr21	5116347	255	6S119M	=	5116419	198	TTTTTTGCCAACACACTTTATTTCCCTTCGGACGCATCTGCAAGCTTCTGCCACACCTGAACCCACGGCCTGGCACCAACGCTACCATCACTCCCCAGAGGTCAATCCTGGGGGCTGAGGAGCTG	BBBBBFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFBFFFFFFFFFFFFFFFFFFFFFFFFFFFFBFFFFFFFFFFFFFFF/</BFFFFFFFFFF	NH:i:1	HI:i:1	AS:i:241	nM:i:0
       7001028:661:CA5PUANXX:8:2314:11717:92676___1-NPC12_BC108	73	chr21	5116348	255	125M	*	0	0	CCAACACACTTTATTTCCCTTCGGACGCATCTGCAAGCTTCTGCCACACCTGAACCCACGGCCTGGCACCAACGCTACCATCACTCCCCAGAGGTCAATCCTGGGGGCTGAGGAGCTGCAATTTC	//B/BFFFFFFFBFFBFFFFF/FF/FFFBFFFFBFBFBFFFFFFFFFBFFFFFFFB/FFFFFFFF/BFFFFFFFFBBFF<FFF<7F<F<FFF/FBFBFFFFFFBFFFFFFFFBF<FFFFFBF/FF	NH:i:1	HI:i:1	AS:i:123	nM:i:0
       7001028:661:CA5PUANXX:4:1313:5911:45004___1-NPC12_BC108	99	chr21	5116356	255	125M	=	5116439	152	CTTTATTTCCCTTCGGACGCATCTGCAAGCTTCTGCCGCACCTGAACCCACGGCCTGGCACCAACGCTACCATCACTCCCCAGAGGTCAATCCTGGGGGCTGAGGAGCTGCAATTTCCCTTTCTT	BBBBBFFFFFFFF/FFFFF<BFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF<FFFFFBF<FFFFFFFFBFFFFFFFFFFFFFFFFFFFFFFFF	NH:i:1	HI:i:1	AS:i:180	nM:i:5

1. with a command like **_samtools mpileup --output-QNAME -uv -f chr21.fa test.sort.bam | head -100_**,  I should be able to get comma-separated list of QNAMEs of samples. Instead, what I got is as following (where is the QNAME?):

        #CHROM	POS	ID	REF	ALT	QUAL	FILTER	INFO	FORMAT	test.sort.bam
       chr21	5116347	.	G	<*>	0	.	DP=1;I16=1,0,0,0,32,1024,0,0,20,400,0,0,6,36,0,0;QS=1,0;MQ0F=0	PL	0,3,20
       chr21	5116348	.	C	<*>	0	.	DP=1;I16=1,0,0,0,32,1024,0,0,20,400,0,0,7,49,0,0;QS=1,0;MQ0F=0	PL	0,3,20
       chr21	5116349	.	C	<*>	0	.	DP=1;I16=1,0,0,0,37,1369,0,0,20,400,0,0,8,64,0,0;QS=1,0;MQ0F=0	PL	0,3,20
       chr21	5116350	.	A	<*>	0	.	DP=1;I16=1,0,0,0,37,1369,0,0,20,400,0,0,9,81,0,0;QS=1,0;MQ0F=0	PL	0,3,20
       chr21	5116351	.	A	<*>	0	.	DP=1;I16=1,0,0,0,37,1369,0,0,20,400,0,0,10,100,0,0;QS=1,0;MQ0F=0	PL	0,3,20
       chr21	5116352	.	C	<*>	0	.	DP=1;I16=1,0,0,0,37,1369,0,0,20,400,0,0,11,121,0,0;QS=1,0;MQ0F=0	PL	0,3,20
       chr21	5116353	.	A	<*>	0	.	DP=1;I16=1,0,0,0,37,1369,0,0,20,400,0,0,12,144,0,0;QS=1,0;MQ0F=0	PL	0,3,20
       chr21	5116354	.	C	<*>	0	.	DP=1;I16=1,0,0,0,37,1369,0,0,20,400,0,0,13,169,0,0;QS=1,0;MQ0F=0	PL	0,3,20
       chr21	5116355	.	A	<*>	0	.	DP=1;I16=1,0,0,0,37,1369,0,0,20,400,0,0,14,196,0,0;QS=1,0;MQ0F=0	PL	0,3,20
       chr21	5116356	.	C	<*>	0	.	DP=3;I16=3,0,0,0,103,3547,0,0,60,1200,0,0,15,225,0,0;QS=1,0;MQ0F=0	PL	0,9,49
       chr21	5116357	.	T	<*>	0	.	DP=3;I16=3,0,0,0,103,3547,0,0,60,1200,0,0,18,258,0,0;QS=1,0;MQ0F=0	PL	0,9,49
       chr21	5116358	.	T	<*>	0	.	DP=6;I16=6,0,0,0,188,5958,0,0,120,2400,0,0,21,297,0,0;QS=1,0;MQ0F=0	PL	0,18,74

2. In #1406, I was told that bcftools should be used instead of samtools to run mpileup. So I tried **_bcftools mpileup --output-QNAME -uv -f chr21.fa test.sort.bam | head -100_**, but I got

           bcftools: unrecognized option `--output-QNAME'
           Invalid option: '?'

3. I am also confused by the column "QUAL" above. According to VCF specification v4.3, "**_QUAL — quality: Phred-scaled quality score for the assertion made in ALT_**". But I always got "0" as "QUAL". Maybe I did something wrong. I also digged into bcftools source code with gdb, and found that in bcftools-1.11/bam2bcf.c line 749, it always set "QUAL" to 0, which I expect to be calculated out of all the sample reads that got aligned to a reference position.

``` c
   741         int bcf_call2bcf(bcf_call_t *bc, bcf1_t *rec, bcf_callret1_t *bcr, int fmt_flag, const bcf_callaux_t *bca, const char *ref)                                      
   742         {                                                                                                                                                                
   743             extern double kt_fisher_exact(int n11, int n12, int n21, int n22, double *_left, double *_right, double *two);                                               
   744             int i, j, nals = 1;                                                                                                                                          
   745                                                                                                                                                                          
   746             bcf_hdr_t *hdr = bc->bcf_hdr;                                                                                                                                
   747             rec->rid  = bc->tid;                                                                                                                                         
   748             rec->pos  = bc->pos;                                                                                                                                         
   749             rec->qual = 0;
```

4. Question: is there any documentation for developers in addition to the source codes and VCF specification?

I would like to discuss more about this problem in details with @whitwham @valeriuo, and I can provide more information if needed.

### How to reproduce what I have seen?
Everything you need to reproduce can be found here: https://github.com/samtools/samtools/issues/1406

**Comment by whitwham** [comment]
Okay, now I have a better idea of what you are after.  I don't think VCF can give you the output you want, I'm pretty sure the QNAME option is for pileup only. 

Have you tried this **samtools mpileup --output-QNAME -f chr21.fa test.sort.bam**? That will give you the pileup output that will include what reads cover each reference position and if they match at that position.

**Comment by valeriuo** [comment]
You are mixing a few concepts:

1.  The default output of `samtools mpileup` is in the **pileup** [format](http://samtools.sourceforge.net/pileup.shtml), which is a distinct format from **VCF** or **SAM**. The QNAME column is only visible in this format and you can see it when running the command `samtools mpileup --output-QNAME -f chr21.fa test.sort.bam`. However, if you select the output to be VCF (`-uv`), the QNAME column is no longer visible, because it is not part of the VCF format.
2.  Generating VCF from `samtools mpileup` is deprecated and discouraged and you were instructed to use `bcftools`, because your initial requirement was to generate VCF, but you should be aware that `bcftools` and `samtools` are complementary and not interchangeable, so CLI options will not always match or translate between the two.

For your use case, it is best to use `samtools mpileup --output-QNAME -f chr21.fa test.sort.bam` and parse the output with `awk` or something similar. You can focus your search by indicating the region of interest with `-r` option, i.e.
`samtools mpileup --output-QNAME -r chr21:5000000-6000000 test.sort.bam`

**Comment by twang15** [comment]
I tried **_samtools mpileup --output-QNAME -f chr21.fa test.sort.bam_** and it indeed gives me the following outputs 

       chr21	5116347	G	1	^~.	A	7001028:661:CA5PUANXX:8:1212:14639:10657___1-NPC12_BC108
       chr21	5116348	C	1	.	A	7001028:661:CA5PUANXX:8:1212:14639:10657___1-NPC12_BC108

The pileup format that Valeriu points out is critical to decode this output, which is closer to my ultimate goal listed above. 
Thanks a lot! @whitwham and @valeriuo 

BTW, is there a slack channel for samtools/bcftools users?

**Comment by valeriuo** [comment]
> BTW, is there a slack channel for samtools/bcftools users?

No, but you can find answers to most of the practical questions on https://www.biostars.org/
