### ISSUE TITLE
samtools depth inconsistent at a position with different region size

### ISSUE THREAD

**Issue by z5ouyang** [samtools/samtools#1412]
#### Are you using the latest version of [samtools](https://github.com/samtools/samtools/releases/latest) and [HTSlib](https://github.com/samtools/htslib/releases/latest)?
samtools 1.9
Using htslib 1.9

 #### Please describe your environment.
- OS (Linux 2.6.32-642.el6.x86_64)
- machine architecture (x86_64)
- compiler (gcc (GCC) 4.4.7 20120313 (Red Hat 4.4.7-17))

#### Please specify the steps taken to generate the issue, the command you are running and the relevant output.
After obtain the forward strand of chromosome 1 by:
samtools view -b -q 255 -F 20 ...bam 1 > 1F.bam

the following samtools depth produce different results:
```
[zouyang@camhpcps01 outs_MN]$ samtools depth 1F.bam -r 1:23795435-23795545 | tail
1       23795536        65
1       23795537        62
1       23795538        54
1       23795539        43
1       23795540        9
1       23795541        4
1       23795542        4
1       23795543        4
1       23795544        4
1       23795545        3
[zouyang@camhpcps01 outs_MN]$ samtools depth 1F.bam -r 1:23795535-23795545 | tail
1       23795536        351
1       23795537        309
1       23795538        230
1       23795539        171
1       23795540        20
1       23795541        9
1       23795542        8
1       23795543        8
1       23795544        6
1       23795545        4
```

Thanks in advance, I might miss something important.

**Comment by valeriuo** [comment]
Can you also filter out the supplementary reads and run the `depth` commands again?
`samtools view -b -q 255 -F 2068 ...bam 1 > 1F.bam`

**Comment by z5ouyang** [comment]
Thank you very much for the reply. But it did not change the behavior.
However, I played around it, if I remove '-q 255', it will be consistent at a position by providing different region length. But I need to apply downstream analysis only on unique mapper and ignore the multi-mapper. The original bam is generated by STAR within 10X. 
  
```
[zouyang@camhpcps01 outs_MN]$ samtools view -b -q 255 -F 2068 ...bam 1 > F2068withQ255_1F.bam
[zouyang@camhpcps01 outs_MN]$ samtools index F2068withQ255_1F.bam
[zouyang@camhpcps01 outs_MN]$ samtools depth F2068withQ255_1F.bam -r 1:23795435-23795545 | tail
1       23795536        65
1       23795537        62
1       23795538        54
1       23795539        43
1       23795540        9
1       23795541        4
1       23795542        4
1       23795543        4
1       23795544        4
1       23795545        3
[zouyang@camhpcps01 outs_MN]$ samtools depth F2068withQ255_1F.bam -r 1:23795535-23795545 | tail
1       23795536        351
1       23795537        309
1       23795538        230
1       23795539        171
1       23795540        20
1       23795541        9
1       23795542        8
1       23795543        8
1       23795544        6
1       23795545        4
```

**Comment by z5ouyang** [comment]
After more investigation, I found the '-m, -d INT' played an unexpected role in ```samtools depth```:
```
[zouyang@camhpcps01 outs_MN]$ samtools depth 1F.bam -r 1:23795535-23795545 | tail
1       23795536        351
1       23795537        309
1       23795538        230
1       23795539        171
1       23795540        20
1       23795541        9
1       23795542        8
1       23795543        8
1       23795544        6
1       23795545        4
[zouyang@camhpcps01 outs_MN]$ samtools depth 1F.bam -r 1:23795435-23795545 | tail
1       23795536        65
1       23795537        62
1       23795538        54
1       23795539        43
1       23795540        9
1       23795541        4
1       23795542        4
1       23795543        4
1       23795544        4
1       23795545        3
[zouyang@camhpcps01 outs_MN]$ samtools depth -r 1:23795435-23795545 -m 10000 1F.bam | tail
1       23795536        351
1       23795537        309
1       23795538        230
1       23795539        171
1       23795540        20
1       23795541        9
1       23795542        8
1       23795543        8
1       23795544        6
1       23795545        4
```
Is this a bug for the '-m, -d INT', which is NOT "At a position, read at most INT reads per input file."? Or maybe the wording is misleading. I assume that if there are more reads at a upstream position, some of those reads mapped across a long junction, will not be counted in the downstream positions.

**Comment by jkbonfield** [comment]
There are indeed known issues with the depth limit code causing a yo-yo effect downstream sometimes.

https://github.com/samtools/htslib/pull/1084 was an attempt at improving on this, although it's still far from perfect.

**Comment by z5ouyang** [comment]
Thanks! Definitely related. With the sequence depth increasing now a days, and sc/sn RNAseq, I do believe a warning should be provided when using "samtools depth", because this might cause incorrect interpretation on downstream analysis. Since I don't know the sequence depth of the future bam files, I set up '-m 0' which is slow but at least the results are correct.

Maybe the default should be "-m 0" for samtools depth.
