### ISSUE TITLE
Regarding flag usage

### ISSUE THREAD

**Issue by razz1618** [samtools/samtools#1413]
Hi,
This is not a technical issue/bug. I am kinda confused with samtools flags. I have mapped my assembled contig to the original paired-end reads to get a .SAM file via bowtie2.  My aim is to find the read counts of predicted CDS from the assembly.  For this, the process is to sort and index the sam file and then can count any Particular or all CDS reads from the indexed file. 

For sorting the command says 

samtools view -F 4 -bS samfile > bam

But as I read documentation the flag 4 corresponds to unmapped reads and flag 2 means mapped reads. Will the sorting process discard the flag-4 (unmapped) as we only want the mapped reads for counting (if I am not wrong)? or my command is wrong?

**Comment by valeriuo** [comment]
What `-F 4` does is discard the unmapped reads from your output BAM file. Flag 2 means "properly aligned segment". You can read the description of each flag in [the spec](https://github.com/samtools/hts-specs/blob/master/SAMv1.pdf) (page 7).

Depending on the `samtools` version you are using, you can obtain the desired result (filtering out the unmapped reads into a sorted and indexed BAM file) with two chained commands:

`samtools view -F 4 -h input.sam | samtools sort -o out-sort-index.bam --write-index`

**Comment by razz1618** [comment]
Thanks for the clarification.
