### ISSUE TITLE
Samtools coverage histogram not viewed properly

### ISSUE THREAD

**Issue by deminatanja** [samtools/samtools#1419]
Hi,

I am using samtools 1.10, Linux 3.10.0-1062.45.1.el7.x86_64, gcc (GCC) 9.1.0.

Samtools coverage command used as below gives a histogram file that can't be viewed properly.

samtools coverage -m -A -w 32 /path/x.sorted.bam -o /path/outputfile

Viewed with head command:
NODE_1_length_307510_cov_3.543238 (307.5Kbp)
>  90.00% │████████████████████████████████│ Number of reads: 50206
>  80.00% │████████████████████████████████│     (1068 filtered)
>  70.00% │████████████████████████████████│ Covered bases:   307.5Kbp
>  60.00% │████████████████████████████████│ Percent covered: 100%
>  50.00% │████████████████████████████████│ Mean coverage:   24.5x
>  40.00% │████████████████████████████████│ Mean baseQ:      35.2
>  30.00% │████████████████████████████████│ Mean mapQ:       40.1
>  20.00% │████████████████████████████████│ 
>  10.00% │████████████████████████████████│ Histo bin width: 9.6Kbp

Viewed in nano:
NODE_1_length_307510_cov_3.543238 (307.5Kbp)
>  90.00% ?^?^??^?^??^?^??^?^??^?^??^?^??^?^??^?^??^?^??^?^??^?^??^?^??^?^??^?^$
>  80.00% ?^?^??^?^??^?^??^?^??^?^??^?^??^?^??^?^??^?^??^?^??^?^??^?^??^?^??^?^$
>  70.00% ?^?^??^?^??^?^??^?^??^?^??^?^??^?^??^?^??^?^??^?^??^?^??^?^??^?^??^?^$
>  60.00% ?^?^??^?^??^?^??^?^??^?^??^?^??^?^??^?^??^?^??^?^??^?^??^?^??^?^??^?^$
>  50.00% ?^?^??^?^??^?^??^?^??^?^??^?^??^?^??^?^??^?^??^?^??^?^??^?^??^?^??^?^$
>  40.00% ?^?^??^?^??^?^??^?^??^?^??^?^??^?^??^?^??^?^??^?^??^?^??^?^??^?^??^?^$
>  30.00% ?^?^??^?^??^?^??^?^??^?^??^?^??^?^??^?^??^?^??^?^??^?^??^?^??^?^??^?^$
>  20.00% ?^?^??^?^??^?^??^?^??^?^??^?^??^?^??^?^??^?^??^?^??^?^??^?^??^?^??^?^$
>  10.00% ?^?^??^?^??^?^??^?^??^?^??^?^??^?^??^?^??^?^??^?^??^?^??^?^??^?^??^?^$
>   0.00% ?^?^??^?^??^?^??^?^??^?^??^?^??^?^??^?^??^?^??^?^??^?^??^?^??^?^??^?^$
          1	  96.1K     192.2K	307.5K

What could be the reason? 

Thanks in advance,
Tatiana

**Comment by jkbonfield** [comment]
It uses various ANSI escape codes, so it'll depend on what your terminal and viewer support.  This is doubly true for tools that try to replace non-printable characters with `^char` style escapes.

For example `less file` may not work, but `less -r file`.

**Comment by jkbonfield** [comment]
I'm not sure it ever had `#`, despite it appearing in the man page.  It's trivial to change `BLOCK_CHARS2` and a conditional on `VERTICAL_LINE` though to get this output:

```
>  90.00% | : :::      :.:::  :::::::::::::| Number of reads: 301333
>  80.00% | :::::     .:::::  :::::::::::::|     (55240 filtered)
>  70.00% | :::::  .  ::::::  :::::::::::::| Covered bases:   832.8Kbp
>  60.00% |::::::. :  ::::::  :::::::::::::| Percent covered: 83.28%
>  50.00% |::::::: :. ::::::  :::::::::::::| Mean coverage:   44.2x
>  40.00% |::::::: :: ::::::  :::::::::::::| Mean baseQ:      34.2
>  30.00% |::::::: :: ::::::  :::::::::::::| Mean mapQ:       22.6
>  20.00% |::::::: :: :::::: .:::::::::::::| 
>  10.00% |::::::: :: ::::::.::::::::::::::| Histo bin width: 31.2Kbp
>   0.00% |::::::: :: :::::::::::::::::::::| Histo max bin:   100%
          1       312.5K    625.0K      1.00M  
```

What do people think about the ASCII version?  IMO it should have full UTF8 support or plain old printable ASCII only.  I don't really get the middle ground of partial UTF8 being enabled with `-A`.

**Comment by jmarshall** [comment]
Rereading the original PR #992, there was initially partial-UTF-8 mode by default for the benefit of Putty users (as its fonts supported only some of these characters) and a `-U`/`--full-utf` option enabling full UTF-8 mode.

At some point (463ce1b15cd33f3ed4b7a51f389c5fbc8d920730) the default was changed to full UTF-8 mode and `-U` was replaced by the misnomered `-A`/`--ascii` which in fact enabled partial-UTF-8 mode. And nobody picked up on the bad `--ascii` name for the “just use _some_ UTF-8 characters” option during review.

So I'd support changing `-A` mode to actually use ASCII (and I quite like your dotty characters), keeping the full UTF-8 default, and maybe adding a `--half-utf8` or `--putty` or something option if the poor Putty users with bad fonts are still a significant demographic.
