### ISSUE TITLE
Question about mapping transcriptome fasta file

### ISSUE THREAD

**Issue by manburst** [samtools/samtools#1421]
Hello sir
I have tried to convert sam to bam file from map transcriptome fasta file with option
`minimap2 -a -x map-ont ref/transref.fa my.fastq | samtools view -b - -o my.bam`
However, the message shows that `samtools view: failed to add PG line to the header`. I have tried index my reference file but it not help.
Here a screenshot
my reference transcriptome fasta
![image](https://user-images.githubusercontent.com/68594551/115991408-75aef100-a5f2-11eb-940e-ef31ed2e0d2d.png)
my sam output
![image](https://user-images.githubusercontent.com/68594551/115991479-c7577b80-a5f2-11eb-9412-cee62bc4de5d.png)
The problems seem to occur when the map to reference transcriptome file (reference genome is works well).
More question about find coverage of interested region. Does this command work?
`samtools coverage -r <myinterested region from reference> input.bam`
This is a reason that I need a bam file.

**Comment by valeriuo** [comment]
Please specify the version of samtools you are using (`samtools --version`).
Do you get a valid SAM file from `minimap2`?
What happens if you run the first command in two steps? Do you still get an error?
```
minimap2 -a -x map-ont ref/transref.fa my.fastq > my.sam
samtools view -o my.bam my.sam
```

>More question about find coverage of interested region. Does this command work?
`samtools coverage -r <myinterested region from reference> input.bam`

It should, with an index file for your BAM. Any problems running it?

**Comment by manburst** [comment]
> Please specify the version of samtools you are using (`samtools --version`).
the version I used is 1.12
Yes, I get a valid sam file but somehow it cannot convert to bam file.

**Comment by valeriuo** [comment]
If you got it sorted out, I am closing the issue. If not, please reopen this thread with a the complete error log and a test SAM file (if possible).
