### ISSUE TITLE
Allow for prefix specification when using --write-index

### ISSUE THREAD

**Issue by fgvieira** [samtools/samtools#1426]
#### Is your feature request related to a problem? Please specify.
It was recently implemented an option to generate a BAM/CRAM file index on-the-fly (`--write-index`). However, it is not possible to define the name of the output file.

It would be great if one could specify the index prefix, eg:
```
samtools view -b --write-index sample_1 -o sample_1.bam sample_1.sam
```
and it would create files `sample_1.bam` and `sample_1.csi`.

This would also allow to use the option `--write-index` when writing to `stdout`:
```
samtools view -b --write-index sample_1 sample_1.sam > sample_1.bam
```

**Comment by daviesrob** [comment]
The description of `--write-index` in the [samtools manual page](https://www.htslib.org/doc/samtools.html#GLOBAL_COMMAND_OPTIONS) explains how this can be done, albeit in the context of changing the output format.  The same trick will work to set the index path - you need to specify the output file name, followed immediately by the string `##idx##` and then the path to the index.  For your example it would look something like this:
```
samtools view -b --write-index -o sample_1.bam##idx##sample_1.csi sample_1.sam
```

Unless you're redirecting to a file, indexing `stdout` didn't seem that useful so it's not directly supported.  However, if your system (e.g. Linux) supports `stdout` access through `/dev/stdout` or `/dev/fd/1` you can get it to work like this:
```
samtools view -b --write-index -o /dev/stdout##idx##sample_1.csi sample_1.sam > sample_1.bam
```
