### ISSUE TITLE
Filter flag do not work as expect.

### ISSUE THREAD

**Issue by yech1990** [samtools/samtools#1435]
For example, if I would like to filter R1 of proper pair reads, while the read is in the some orientation of the reference sequence. I can use flag 99 (1+2+32+64) in `samtools view` to subset such reads.
But in `sample mpileup`, the `--rf` argument can not deal with this situation correctly. Because flag `99` contains the `1` flag, any paired reads will be selected by `mpileup`, ignoring other flags (2, 32, 64).

![image](https://user-images.githubusercontent.com/5415510/118784442-994c1b00-b8c2-11eb-9fbb-a6f87cccf9de.png)

- I think this line should be fixed

https://github.com/samtools/samtools/blob/5fcc7a4fa822bb216030b6d6803e846f99b7ad41/bam_plcmd.c#L332

**Comment by valeriuo** [comment]
It is not an error. The filter in `mpileup` is designed to work on an **ANY** rule, as opposed to an **ALL** rule, which is how `view` works.
So you can either filter in the reads with `view`, before piping into `mpileup`, or write a different "filter in ALL" option for `mpileup` (e.g. `--af`), but the behaviour of `--rf` cannot be changed for compatibility reasons.

**Comment by yech1990** [comment]
Hi, @valeriuo, thank you for your explanation.
I know what `ANY` in `mpileup` mean, but this is not `ANY` in the general sense. From the user’s point of view, they might want to filter flag `99` or `147`, which are pairs. If `mpileup` can filter `ANY(99, 147)`,  the `--rf` option will be very useful. However, `--rf` option can no set flag filter in this way. It can only filter `ANY(1, 2, 32, 64)` by flag 99. I don't think there is such case, user would like to reads with flag 1, or with flag 64.

**Comment by jkbonfield** [comment]
All FLAG filter rules are bit based though, so you cannot explicitly do equality, only masking (in or out).  That includes `view` as well as `mpileup`. 

Hence `view -f 99` will reject 97 (not a proper pair), but would accept 611 (QCFAIL).  There's no equality thing going on so it can't be `ANY(99, 147)`.  (That's possible with `view -e`, albeit via a much more complex syntax.)

I'd argue however that you need to decide what it is about 99 and 147 that matters.  Which bits in particular are you trying to filter in or filter out?  Are you wanting only primary reads, ie not secondary or supplementary, and no duplicates / fails?  If so filtering for only 99/147 is the wrong way and you'd be better thinking about it as filtering out 0xf00.  (That's `view -F` or `mpileup --ff`.)  If you also then require paired and proper pair, combine that with `-rf 3`.

I'm not convnced there's a need to add a specific flag equality test.  Can you describe precisely what things you are looking for, other than "99 or 147"?

**Comment by yech1990** [comment]
Thank you @jkbonfield.

For the `ANY(99, 147)` example, I mean both reads contains flag `99` (also `355`, `1123`...) and reads contains flag `147` (also `403`, `1171`...) will be selected, and pipe to downstream analysis.

For purpose, selecting reads based on multiple flags has been an feature request for [a long time](https://www.biostars.org/p/60100/). What I am looking for is mpileup multiple bam files for forward and reverse strand respectively.  Strand specific sequencing is common strategy, and it is necessary to separate `mpileup` output by strand.  And this why I tried to add `ANY(99, 147)` and `ANY(83, 163)` filter for two mpileup command. Meanwhile, because there are multiple input bam files in my analysis. there is no simple solution to pipe a samtools `view` command before `mpileup` command.

I tried to separate each bam file into two stranded bam files by awk comamnd, then run the `mpileup` command. It works, but there will be lots of internal files.
```bash
awk '(and($flag, 1) && and($flag, 2)) && ((and($flag, 32) && and($flag, 64)) || (and($flag, 16) && and($flag, 128)))'
awk '(and($flag, 1) && and($flag, 2)) && ((and($flag, 16) && and($flag, 64)) || (and($flag, 32) && and($flag, 128)))'
```

**Comment by jkbonfield** [comment]
Firstly, the biostars link you point to isn't a feature request here, so hardly helpful.  However I note it is infact already possible with `view -G 12` (although perhaps that postdates the question) so that issue is somewhat irrelevant.

I assume, using your syntax of `AND(99, 147)` you mean `(flag & 99) == 99 || (flag & 147) == 147`?  Ie all bits must be set, but extra bits may optionally also be set?  Your awk statement somewhat obfuscates this btw and could be written much simpler.

If so, you can use the filter syntax on view with `samtools view -e  'flag & 99 == 99 || flag & 147 == 147'` would work.   You can also specify this in mpileup too:

```
samtools mpileup --input-fmt-option 'filter=flag & 99 == 99 || flag & 147 == 147' in.bam
```

However I still don't entirely understand what you're attempting to do and why it cannot be done with a combination of `--ff` and `--rf`.  It does take a certain amount of mental gymnastics to figure out how they combine together though.  It's possible `mpileup` needs the view equivalent of `-G` which  works on all flag bits rather than any flag bits, but the newer filtering syntax is probably the easiest.

**Comment by yech1990** [comment]
Thank you very much @jkbonfield.

> `samtools mpileup --input-fmt-option 'filter=flag & 99 == 99 || flag & 147 == 147' in.bam`

This is exactly what I want. I am very sorry that I do not known the `--input-fmt-option` argument can set flag filter. Could you show me the manual for this argument? I would like to read it carefully.

BTW, I know that `mpleup --reverse-del` can store all the strand information of the reads. For example, `.` mean read map to the forward strand, and `,` means read map to the reverse strand. But for pair end reads (R1 and R2), this notation will be a little confusing. Because for read fragment `1>>>   <<<2`, which is in the same orientation (*forward strand*) of the reference sequence, `mpileup` will report `forward` and `reverse` mapping. I know this is because `mpileup` store the orientation of the reads, instead of the fragments. This is why it tried to separate bam files by fragment orientation. 
Thank you very much for the `--input-fmt-option` solution. I would like it is possible to make `mpileup` report the orientation of the fragments, instead of the reads.

**Comment by yech1990** [comment]
>It is not an error. The filter in mpileup is designed to work on an ANY rule, as opposed to an ALL rule, which is how view works.

Could you please add this description in the `--help` output? I think other user might also confusing with `--rf` in `mpileup` and `-f` in `view`.

**Comment by jkbonfield** [comment]
It's a new feature.  It's documented in the main samtools man page as it's a common option to all subcommands.

http://www.htslib.org/doc/samtools.html#FILTER_EXPRESSIONS

Agreed the help for mpileup isn't particularly clear in the all-set vs any-set semantics of those filtering options, unlike view which is very explicit.

**Comment by jmarshall** [comment]
It's a bit surprising that `mpileup --ff` and `view -F` implement the same check, but `mpileup --rf`, `view -f`, and `view -G` are all different. I have an upcoming `view` PR that clarifies this a bit more (on the `view` side).

**Comment by jkbonfield** [comment]
Thanks John.  Are you planning on improving the documentation for mpileup while you're at it, or shall we clarify that?

Agreed with your comment, but "surprising" is no longer becoming "surprising" with time. ;-)

**Comment by jkbonfield** [comment]
> Because for read fragment `1>>> <<<2`, which is in the same orientation (_forward strand_) of the reference sequence, `mpileup` will report `forward` and `reverse` mapping. I know this is because `mpileup` store the orientation of the reads, instead of the fragments. This is why I tried to separate bam files by fragment orientation.
> Thank you very much for the `--input-fmt-option` solution. I would like it is possible to make `mpileup` report the orientation of the fragments, instead of the reads.

That's a different issue, but I can definitely see where you're coming from.  We'd need a new mpileup option to change the type of strand being reported.

Note you can define template strand as `read_end != read_strand`, with read_end being 0/1 for READ1/READ2 and read_strand being 0/1 for non-REVERSE and REVERSE.  I've used this logic in the past in other tools (Gap5) for separating strands.

In the filter language it'd be something like `(flag.read2 == 0) != (flag.reverse == 0)` for 0/1 template strand (NB: untested!).    I wonder if the filter expression syntax should simplify it with a new variable `template_strand` to simplify matters, which simply does a combination of flag checks (but a bit better though to cope with neither READ1/2 or both READ1/2 set).

**Comment by jmarshall** [comment]
It's been gestating more than long enough without widening it to mpileup too :smile: so probably best for someone to look at that separately.

**Comment by yech1990** [comment]
>  We'd need a new mpileup option to change the type of strand being reported.

I just want to know if this will become a new feature of `mpileup`, or is this example too special and need not be implemented separately?

> Note you can define template strand as read_end != read_strand

Thanks for this clever solution. I will try it now, and read the `--input-fmt-option` carefully.
