### ISSUE TITLE
Typo in samtools coverage help

### ISSUE THREAD

**Issue by ceilinglight** [samtools/samtools#1443]
Hi,

Just found a typo in help text.
The line
```
-l, --min-read-len INT  ignore reads shorter than INT bp [0]
```
should read
```
-L, --min-read-len INT  ignore reads shorter than INT bp [0]
```
https://github.com/samtools/samtools/blob/8e8b07400fd7d148e4243f38e7e0fc3cb9e124e1/coverage.c#L114
https://github.com/samtools/samtools/blob/8e8b07400fd7d148e4243f38e7e0fc3cb9e124e1/coverage.c#L330

**Comment by valeriuo** [comment]
Thanks for reporting it.
