### ISSUE TITLE
`--input-fmt-option` filter not work on unmapped reads

### ISSUE THREAD

**Issue by yech1990** [samtools/samtools#1445]
I tried to use `--input-fmt-option 'filter=cigar=~"S"'` for filtering soft clip reads, but the samtools report `[E::sam_passes_filter] Couldn't process filter expression` error  when the input read is unmapped.

`--input-fmt-option 'filter=!flag.unmap && cigar=~"S"'` also don't work.

**Comment by yech1990** [comment]
Seem that htslib do not support filtering `cigar`. The `rname` works.

**Comment by jkbonfield** [comment]
It works for me on mapped data:

```
$ samtools view -c ~/scratch/data/9827_2#49.1m.bam 
99890
$ samtools view -c -e 'cigar=~"S"' ~/scratch/data/9827_2#49.1m.bam 
3848
$ samtools view --input-fmt-option 'filter=cigar=~"S"' -c ~/scratch/data/9827_2#49.1m.bam 
3848
```

However on umapped data I do indeed get a warning:

```
$ samtools view -e 'cigar=~"S"' -c ../htslib/test/ce#unmap.sam
[E::sam_passes_filter] Couldn't process filter expression
[E::sam_passes_filter] Couldn't process filter expression
[E::sam_passes_filter] Couldn't process filter expression
[E::sam_passes_filter] Couldn't process filter expression
[E::sam_passes_filter] Couldn't process filter expression
[E::sam_passes_filter] Couldn't process filter expression
0
```

It returns success (ie not a failure), and mixing mapped and unmapped together produces the correct count.  This is therefore a bug in the implementation.  It should probably return the empty string as CIGAR for unmapped reads to avoid the warning.

The second attempt of `samtools view -e 'cigar=~"S"'` is reasonable, but the expression parser is still quite brain-dead as it expands the cigar variable up irrespective of whether the first part of that AND statement was true or false, hence it creates the same warning.

I'll fix this, but for now it seems it's just a harmless, if annoying, whinge.

**Comment by jkbonfield** [comment]
Hopefully now fixed in samtools/htslib#1298

**Comment by yech1990** [comment]
Hi @jkbonfield, 

It seem that `--input-fmt-option` also not work for the `samtools fastq` command. Can you test it for me?
Thank you.

**Comment by jkbonfield** [comment]
The fix for this is in htslib, not samtools.  All the samtools commands call the same code for option handling and filtering, so the change will affect every sub-command.

**Comment by yech1990** [comment]
Yes. But seems that any options passed to this argument is not working in
samtools flastq.
