### ISSUE TITLE
Error using samtools with subjunc bam output [samtools sort: truncated file]

### ISSUE THREAD

**Issue by hchetia** [samtools/samtools#1449]
Hi,
I am facing an error generated by samtools when I try running "samtools sort". It generates ~100 tmp files and finally the foll. error message is displayed. 

**Samtools version**- samtools 1.12 Using htslib 1.12 (installed from conda)
**OS**- Redhat 7.5
**Command**- samtools sort -@ 4 -m 2G xyz.bam
**xyz.bam generated using subjunc aligner (subjunc -T 24 -I 200 --rg-id WGS -i hg38 -r xyz_R1.fq.gz -R xyz_R2.fq.gz -o xyz.bam**

Error- 
[E::bam_read1] CIGAR and query sequence lengths differ for A00815:188:H55YWDRXY:1:2246:24478:28260
samtools sort: truncated file. Aborting

Thanks,
Hasna

**Comment by valeriuo** [comment]
You are allocating 2 GB of memory to 4 threads. So the whole process would take 8 GB. Do you have any limits on the per process memory or the number of opened files? What does `ulimit -a` indicate?

**Comment by jkbonfield** [comment]
I'd assume that samtools is correct and the read really does have a malformed CIGAR string.  What does `samtools view xyz.bam | awk '$1 == "A00815:188:H55YWDRXY:1:2246:24478:28260"'` show?  (Or use grep, but that may find the name in other records in SA tags.)

If it's incorrect, then this would be an aligner bug.

**Comment by hchetia** [comment]
> You are allocating 2 GB of memory to 4 threads. So the whole process would take 8 GB. Do you have any limits on the per process memory or the number of opened files? What does `ulimit -a` indicate?

![image](https://user-images.githubusercontent.com/64626735/121945436-c6ed7e00-cd21-11eb-9f36-765d8228fed5.png)

**Comment by hchetia** [comment]
![image](https://user-images.githubusercontent.com/64626735/122055816-031eee00-cdb7-11eb-9f0a-5e899499f0be.png)


> I'd assume that samtools is correct and the read really does have a malformed CIGAR string. What does `samtools view xyz.bam | awk '$1 == "A00815:188:H55YWDRXY:1:2246:24478:28260"'` show? (Or use grep, but that may find the name in other records in SA tags.)
> 
> If it's incorrect, then this would be an aligner bug.



> I'd assume that samtools is correct and the read really does have a malformed CIGAR string. What does `samtools view xyz.bam | awk '$1 == "A00815:188:H55YWDRXY:1:2246:24478:28260"'` show? (Or use grep, but that may find the name in other records in SA tags.)
> 
> If it's incorrect, then this would be an aligner bug.

HI,
I get the error again when using the suggested command.

![image](https://user-images.githubusercontent.com/64626735/122055886-15992780-cdb7-11eb-8a18-8d7a56905348.png)

**Comment by valeriuo** [comment]
What is the length of the sequence? It's a bit hard to count the letters from a picture.

**Comment by jkbonfield** [comment]
The fact that samtools view is complaining shows it's not a sort problem.  Indeed it's quite possible the read shown is the paired copy and not the failing one and the BAM to SAM conversion is throwing the error so we don't even see the affected line.

I think this is very much more likely to be a subjunc bug.   If subjunc initially produces a SAM file then the cast iron proof there is an error in it would be to grep that output.  This should then be filed against subjunc rather than samtools.

**Comment by hchetia** [comment]
> What is the length of the sequence? It's a bit hard to count the letters from a picture.
The length is 250 bp.

**Comment by hchetia** [comment]
I do not see a sam file in the directory, but definitely a bunch of tmp*bam files.
So, perhaps I will add this issue to subjunc for now.
Thanks for the prompt responses guys.



> The fact that samtools view is complaining shows it's not a sort problem. Indeed it's quite possible the read shown is the paired copy and not the failing one and the BAM to SAM conversion is throwing the error so we don't even see the affected line.
> 
> I think this is very much more likely to be a subjunc bug. If subjunc initially produces a SAM file then the cast iron proof there is an error in it would be to grep that output. This should then be filed against subjunc rather than samtools.

**Comment by jkbonfield** [comment]
Closing as we believe it to be a problem with the input data, but if you get more evidence for it being a samtools/htslib problem then please respond here.

Thanks.
