### ISSUE TITLE
samtools v1.12 exclude chromosome chunks when extracting entire chromosomes 

### ISSUE THREAD

**Issue by vinimfava** [samtools/samtools#1451]
- OS Linux 3.10.0-1127.19.1.el7.x86_64
- machine architecture x86_64
- compiler gcc (GCC) 9.3.0

While filtering for entire chromosomes samtools v1.12 excluded large chunks of the chromosome while for v1.11 and v.1.10 that was not the case. I used the same commands in an HPC environment using different samtools versions: 

module load samtools/1.10
samtools view -@ 4 -f 2 -F 1804 -b Sample.bam chr15 | samtools sort -@ 4 -o Sort.marked_dup_v1.10_chr15.bam
samtools index Sort.marked_dup_v1.10_chr15.bam

module load samtools/1.11
samtools view -@ 4 -f 2 -F 1804 -b Sample.bam chr15 | samtools sort -@ 4 -o Sort.marked_dup_v1.11_chr15.bam
samtools index Sort.marked_dup_v1.11_chr15.bam

module load samtools/1.12
samtools view -@ 4 -f 2 -F 1804 -b .Sample.bam chr15 | samtools sort -@ 4 -o Sort.marked_dup_v1.12_chr15.bam
samtools index Sort.marked_dup_v1.12_chr15.bam

![Screen Shot 2021-06-16 at 10 56 45 AM](https://user-images.githubusercontent.com/45293154/122242991-bf4ce700-ce91-11eb-8186-5a76e97d19b3.png)

The chunks were "removed" for 5 independent samples out of the 40 processed with samtools v.1.12. The disappearance of chromosome chunks was restricted to chr15 and chr22 in my dataset.

**Comment by valeriuo** [comment]
Could be related to https://github.com/samtools/htslib/issues/1279. Can you pull the latest develop HEAD of [HTSlib](https://github.com/samtools/htslib), recompile it (and samtools) and see if the issue persists?

**Comment by vinimfava** [comment]
Thanks for the prompt response Valeriuo.

The htslib seems to be likely cause of my problem. All good now.
