### ISSUE TITLE
Write records that failed to pass the filter into file

### ISSUE THREAD

**Issue by yech1990** [samtools/samtools#1453]
`--input-fmt-option "fllter=xxx"` can subset records and pass them into a certain command. How can I save those reads that fail to pass the filter into another file in the same time?

**Comment by jmarshall** [comment]
`--input-fmt-option filter=…` operates at too low a level to do this. However `samtools view -e` uses the same filter expressions, hence

```
samtools view -e … -o pass.bam -U fail.bam in.bam
```
