### ISSUE TITLE
Running samtools view on bam affects the number of variants called by both haplotypecaller and deepvariant 

### ISSUE THREAD

**Issue by ramprasadn** [samtools/samtools#1460]
Hi all,

I have a pipeline to call variants using both haplotypecaller and deepvariant, and I am trying to evaluate its performance by using samples from the genome in a bottle dataset. The issue is that I am observing more false-positive and false-negative variants once I switched to the latest version of samtools (v1.12) and I hope to understand what’s causing this discrepancy with some help from the community.  

The pipeline framework is as follows,
bwa (v0.7.17) -> samtools view -> markduplicates (picard 2.25.0) -> variant caller (gatk v4.2.0.0 and deepvariant v1.1.0)

And I run samtools view like this,
samtools view --output-fmt BAM --write-index -o <output.bam> <input.bam> <chromosome> 

To get at the summary statistics, I have used the eval function in rtg_tools (https://github.com/RealTimeGenomics/rtg-tools) and results are tabulated in the table below 

| Variant-caller | Samtools-version | True-pos variants | False-pos variants | False-neg variants |
|---------------|------------------|----------|------------|-----------|
   deepvariant   |  1.10   |   3516267 |  23757   | 16088   
   deepvariant   |  1.11    |  3516267  | 23757   | 16088    
   deepvariant   |  1.12    |  3488183  | 23576  | 44017   
   haplotypecaller | 1.10  |    3511732 |  39339 |  19949   
   haplotypecaller | 1.11   |   3511732   |39339  | 19949   
   haplotypecaller | 1.12   |   3483688 |  40790 |  47847   

As you can see, when I run view function in samtools v1.12, my results appear to get worse and I don’t know why. Any pointers would be appreciated. 

And this is the environment that I am running my pipeline in
- OS - Linux 3.10.0-1062.4.1.el7.x86_64
- Machine architecture - x86_64
- compiler - (gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-39) 

Let me know if you guys need more details from my side.

Thanks,

**Comment by valeriuo** [comment]
Hi!
We had some issues with the indexing code in 1.12. Can you pull the latest develop HEAD of [HTSlib](https://github.com/samtools/htslib), recompile it (and samtools) and see how the numbers change?
We are due with a release soon, but we want to make sure we've included all the critical fixes. So your test would help us greatly.

**Comment by ramprasadn** [comment]
Thanks for getting back to me Valeriu. 

As you suggested, I used the latest commit from the develop branch in my pipeline, and the results look good. I was able to replicate the numbers from samtools v1.10.2 and v1.11 for both variant callers. 

FYI
```
$ docker run scilifelabram/htslib:dev_proper /opt/samtools/samtools version
samtools 1.12-36-g2f2992a
Using htslib 1.12-55-gf7975f1
Copyright (C) 2021 Genome Research Ltd.

Samtools compilation details:
    Features:       build=configure curses=yes
    CC:             gcc
    CPPFLAGS:
    CFLAGS:         -Wall -g -O2
    LDFLAGS:
    HTSDIR:         /opt/htslib
    LIBS:
    CURSES_LIB:     -lncursesw

HTSlib compilation details:
    Features:       build=configure plugins=no libcurl=yes S3=yes GCS=yes libdeflate=no lzma=yes bzip2=yes htscodecs=1.0-2-gd7e3579
    CC:             gcc
    CPPFLAGS:
    CFLAGS:         -Wall -g -O2 -fvisibility=hidden
    LDFLAGS:        -fvisibility=hidden

HTSlib URL scheme handlers present:
    built-in:	 preload, data, file
    S3 Multipart Upload:	 s3w, s3w+https, s3w+http
    Amazon S3:	 s3+https, s3+http, s3
    Google Cloud Storage:	 gs+http, gs+https, gs
    libcurl:	 imaps, pop3, http, smb, gopher, ftps, imap, smtp, smtps, rtsp, ftp, telnet, rtmp, ldap, https, ldaps, tftp, pop3s, smbs, dict
    crypt4gh-needed:	 crypt4gh
    mem:	 mem
```

**Comment by valeriuo** [comment]
@ramprasadn Good to know and thanks for verifying. We'll try to have the fix released ASAP.
