### ISSUE TITLE
samtools coverage fails to parse the regions

### ISSUE THREAD

**Issue by Lyn16** [samtools/samtools#1461]
Hello, 
I am using samtools to get coverage for each chromosome and some specific region. 
Here is the code:
`samtools coverage -r chr1:1M-12M /Users/lyn/seq_data/WGSdata/tumor_sample_raw_data/Bam/CN9R1_1.final.bam`

and error looks like this:
>samtools coverage: Failed to parse region "chr1:1M-12M": No such file or directory

I wonder if the problem comes from how I write the specific region? Thanks!

**Comment by valeriuo** [comment]
The most probable cause is that **chr1** does not exist as a contig name in the BAM file header. You can inspect all the contig names with the following command:
`samtools view -H /Users/lyn/seq_data/WGSdata/tumor_sample_raw_data/Bam/CN9R1_1.final.bam | grep "^@SQ" | cut -f2`

Maybe the **chr** prefix has been dropped, in which case you should adjust your query to match it:
`samtools coverage -r 1:1M-12M ...`

However, the error message is misleading and this is on us to fix.

**Comment by Lyn16** [comment]
Thanks! I checked the contig names with the code you provided, indeed the 'chr' prefix has been dropped in my bam files.  And the code is working now
