### ISSUE TITLE
phred scores of deletions

### ISSUE THREAD

**Issue by luyoutao** [samtools/samtools#1468]
Maybe already discussed somewhere (https://www.biostars.org/p/61965, https://www.biostars.org/p/302206) but it still seems to be a mystery that how samtools assigns phred scores to deletions. 

Below is an example:
```
$ samtools view test.bam 
1       0       chr1    10      255     2S4M1S  *       0       0       AGTGGTA EDBA@?>
2       0       chr1    50      60      1M2I3M  *       0       0       CGTGCC  IHGFEC
3       0       chr1    90      30      3M2D1M  *       0       0       GACT    DCBA

$ samtools mpileup test.bam 
[mpileup] 1 samples in 1 input files
chr1    10      N       1       ^~T     B
chr1    11      N       1       G       A
chr1    12      N       1       G       @
chr1    13      N       1       T$      ?
chr1    50      N       1       ^]C+2GT I
chr1    51      N       1       G       F
chr1    52      N       1       C       E
chr1    53      N       1       C$      C
chr1    90      N       1       ^?G     D
chr1    91      N       1       A       C
chr1    92      N       1       C-2NN   B
chr1    93      N       1       *       A
chr1    94      N       1       *       A
chr1    95      N       1       T$      A
```

My puzzle is why the two deletions (position 93-94) got score A but not B, if we consider the padded lines as associated with position 92 (the origin of the deletions) according to https://www.biostars.org/p/61965. 

version info: 
* samtools 1.13
* Using htslib 1.13

**Comment by jkbonfield** [comment]
The trouble with the pileup format is that fundamentally it's broken!  It always has exactly 1 quality for 1 base, and it marks the deleted base as `*`.  Therefore there is no way you can avoid assigning it a confidence value.  Similarly it's impossible for it to show the confidence for an inserted base, despite that having a value in the SAM file.

Now logically the deletion confidence should be the probability that the deletion is not a sequencing error, but we don't have that data recorded in SAM.  Instead it's simply the quality value from the neighbouring base.   It appears to be the next base, but it's just convention.  (Note this may flip on a reverse complemented read, but I'd have to double check.)

(I assume in the CIGAR processing it's already skipped to the next base in the sequence, but the reference position hasn't caught up yet.  If I recall this originally had a bug where a read ending on a deletion would give quality scores copied from the first aux tag.)

**Comment by luyoutao** [comment]
Just saw https://github.com/samtools/samtools/issues/1305, good explanation, thanks.
