### ISSUE TITLE
add option to samtools view to unmap aligned reads rather than remove them

### ISSUE THREAD

**Issue by eboyden** [samtools/samtools#1469]
Pretty self-explanatory.  When using -f/F/G or any other filters, I want to keep the reads in the bam, just render them unaligned.  This would be useful for downstream analyses that use "total reads" in the denominator, as well as downsampling bams that have already been "filtered".

**Comment by whitwham** [comment]
Interesting idea.  How complete would you want the unmapping to be?  Just changing the mapped flag or removing the mapping information entirely?

You could do it with a combination or **samtools view** and **samtools merge** though it might not be terribly efficient.

**Comment by eboyden** [comment]
Ideally it would remove the mapping information entirely, since downstream tools may not always rely on the bitflag - the records should look like the aligner failed to align them in the first place.  Is there a way to unmap the reads via view | merge, or would that just reconstitute the original bam file (unless an additional tool was used on the filtered reads before merging them back in)?

**Comment by whitwham** [comment]
You can set/unset flags in the latest version of **view** and remove tags.  I don't think you can delete cigar strings or remove pos values (and other entries).  So it would not wipe all the mapping information.

If we did set up an option to do this, keeping the pair information consistent could be a problem.

**Comment by eboyden** [comment]
Forgive me if I'm wrong, but isn't keeping pair info consistent also a problem when removing reads?  Does samtools modify the bitflag, insert size, etc. of the remaining read when filtering one of a pair of aligned reads?  Or is it just implicit that filtering in this fashion is "at your own risk"?  Couldn't most of the information be fixed by running fixmate?

FWIW, usually I'd be unmapping based on the "concordance" bitflag (0x2), so I'd be unmapping reads as pairs (or unmapping singleton alignments) anyway.

**Comment by whitwham** [comment]
> Forgive me if I'm wrong, but isn't keeping pair info consistent also a problem when removing reads?

True, I'm really just thinking out loud.  Trying to see if there are any drawbacks I haven't seen.
