### ISSUE TITLE
Detail information of samtools depth 

### ISSUE THREAD

**Issue by Ben-unbelieveable** [samtools/samtools#1471]
#### Are you using the latest version of [samtools](https://github.com/samtools/samtools/releases/latest) and [HTSlib](https://github.com/samtools/htslib/releases/latest)? If not, please specify.
(run `samtools --version`)
Version Information: 
          samtools 1.5
          Using htslib 1.5
          Copyright (C) 2017 Genome Research Ltd.

 #### Please describe your environment.
- OS (run `uname -sr` on Linux/Mac OS or ` wmic os get Caption, Version` on Windows)
- machine architecture (run `uname -m` on Linux/Mac OS or ` wmic os get OSArchitecture` on Windows)
- compiler (run `gcc --version` or `clang --version`)

x86_64

#### Please specify the steps taken to generate the issue, the command you are running and the relevant output.

What kind of data will be used for depth calculations. Use view to filter out flag&4, 256, 512, 1024, and deduplicate readsID to get a depth of 20067. But through samtools depth directly calculate the site depth to 8070. What may be the reason for this difference in depth.

**Comment by jkbonfield** [comment]
This will almost certainly be the maximum depth limit (option `-m`).  However I would strongly advise you simply upgrade to samtools 1.13 which has a newer depth command that is considerably faster on such deep data and doesn't need the `-m` option any more.

**Comment by Ben-unbelieveable** [comment]
Yeah，that's very helpful，thanks for your help . and this case show the need for the upgrade the publication.
