### ISSUE TITLE
Erroneous "CRAM CIGAR extends beyond slice reference extents"

### ISSUE THREAD

**Issue by matt-sexton** [samtools/samtools#1475]
samtools 1.13 / Ubuntu 18.04

Attached is a CRAM file that was not generated by samtools.  It consists of a single aligned read and includes embedded reference.  samtools can successfully decode the file in its default mode:

```
$ ~/samtools-1.13/samtools view -c ./samtools-bug.cram 
1
```
When using the `required_fields` option with certain bit fields, samtools generates an error:

```
$ ~/samtools-1.13/samtools view --input-fmt-option required_fields=2 ./samtools-bug.cram 
[E::cram_decode_seq] CRAM CIGAR extends beyond slice reference extents
[E::cram_next_slice] Failure to decode slice
samtools view: error reading file "./samtools-bug.cram"
```
The single read has a CIGAR string of 108M188S and the embedded reference has a span of 108 bases.  My crude debugging of the error suggest that samtools is comparing the length of the entire sequence to the extent of the reference rather than only the mapped portion of the read.

The problem does not show up if the cram file is generated by samtools because samtools makes different encoding decisions.  During the subsequent decoding, samtools decides that it can decode fewer fields and never makes the check that leads to the error.

Please note that I had to add a .txt extension to the CRAM so that I could upload it.

[samtools-bug.cram.txt](https://github.com/samtools/samtools/files/6910019/samtools-bug.cram.txt)

**Comment by jkbonfield** [comment]
Thank you for the bug report and test data.

I can reproduce it and confirm that it is a bug.  I have a fix incoming.
