### ISSUE TITLE
Exclude alignments based on presence of tag (regardless of value)

### ISSUE THREAD

**Issue by williamrowell** [samtools/samtools#1476]
#### Is your feature request related to a problem? Please specify.

I have a haplotagged BAM with tags `HP:i:1` or `HP:i:2` in phased regions, and no tags in unphased regions.  I would like to split the BAM into three groups based on the presence of this tag and the value.  I can use something like `-d HP:1` to get the phased alignments, but I'm having trouble getting the unphased alignments.  I have tried `-e '[HP]!=1 && [HP]!=2'` and `-e ![HP]`, but both of these seem to be allowing tagged alignments to slip through.

#### Describe the solution you would like.

I would like to be able to _exclude_ reads that have a specific tag, with any value.

**Comment by daviesrob** [comment]
I think `-e '![HD]'` should do what you want.  For example, on this simple input:
```
@HD	VN:1.4	SO:coordinate
@SQ	SN:ref1	LN:10
r1	0	ref1	1	60	10M	=	1	0	ACGTACGTAC	aaaaaaaaaa	HD:i:1
r2	0	ref1	1	60	10M	=	1	0	ACGTACGTAC	aaaaaaaaaa	HD:i:2
r3	0	ref1	1	60	10M	=	1	0	ACGTACGTAC	aaaaaaaaaa
```

I get:
```
./samtools view -e '![HD]' /tmp/e.sam 
r3	0	ref1	1	60	10M	=	1	0	ACGTACGTAC	aaaaaaaaaa
```

If this isn't working for you, would it be possible to make us a small example file that demonstrates the problem?  You should be able to zip it and attach it here if it's not too big.

**Comment by williamrowell** [comment]
It appears that the problem is that I was filtering based on a tag and removing the tag in the same step.  I assumed filtering would precede removing the tag, but it doesn't seem to be the case.

I made a small [test case](https://github.com/samtools/samtools/files/6941278/test.bam.gz) with three alignments, one with `HP:i:1`, one with `HP:i:2`, and one without the HP tag.

```bash
$ samtools version
samtools 1.12
Using htslib 1.12
Copyright (C) 2021 Genome Research Ltd.
...
$ samtools view -e '![HP]' -x HP test.bam | wc -l
3
$ samtools view -e '![HP]' test.bam | wc -l
1
```

**Comment by jkbonfield** [comment]
Ah that's an intriguing corner case.  To be honest I'd have assumed the same order too, but it's not documented which way it works.

The easiest workaround for now is simply to do it via a pipe as two separate commands.  In that case `view -u` to output uncompressed BAM in the initial command would be the fastest communication from one step to the next.

**Comment by williamrowell** [comment]
Right, thanks, that will cover the case where I want to get the untagged alignments.

The order of operations seems to be different for `-e <expr> -x <tag>` and `-d <expr> -x <tag>`, which would explain why retrieving reads with specific tag values worked.

```bash
$ samtools view -d HP:1 -x HP test.bam | wc -l
1
$ samtools view -d HP:1 test.bam | wc -l
1
```
