### ISSUE TITLE
CG tag in BAM/CRAM output?

### ISSUE THREAD

**Issue by cmdcolin** [samtools/samtools#1477]
Hi there,
I was looking at a BAM file (and an equivalent CRAM file) from hg002 that has an actual CG tag in the output when decoding with samtools

I imagine this might be a mis-encoded CIGAR string as it is long read data as the CIGAR shows the signature "softclip is the whole length of the sequence"

Can see issue here
```
 samtools view 'https://ftp-trace.ncbi.nlm.nih.gov/giab/ftp/data/AshkenazimTrio/HG002_NA24385_son/Ultralong_OxfordNanopore/combined_2018-08-10/HG002_ONTrel2_16x_RG_HP10xtrioRTG.cram.bam' 1:87,066,445-87,193,601|head -n1|tr '\t' '\n' |less -S

```

BAM output
```
9b0fe1f3-7b3c-4f39-98a2-7d2dcd9e6804
0
1
86697442
60
663204S670990N
*
0
0
TAAATCTGGTGGATAAGTGTTATGTCTCAGGAGGATGAACTGTCATAAACTATAGCTGGAATTTAGAGCAGCTACACCCAGAGCACCAGGTGCTTGAACA>
#$$$$%#'%#&))*+(('&&&#%$%%AB;=>46>48EF:10-1/57<@7134:;)*-8>8;5A((%.%8123.+.)2((--0344;>2/&..*7))+34.>
s1:i:292917
s2:i:884
CG:B:i,372,480,18,208,18,80,18,80,17,176,17,624,34,352,34,320,34,112,33,64,18,64,17,592,18,784,34,62>
RG:Z:HG002_ONT_rel1
AS:i:906162
cm:i:35982
nn:i:0
tp:A:P
ms:i:903524
dv:f:0.0787
```

CRAM output

```
9b0fe1f3-7b3c-4f39-98a2-7d2dcd9e6804
0
1
86697442
60
663204S670990N
*
0
0
TAAATCTGGTGGATAAGTGTTATGTCTCAGGAGGATGAACTGTCATAAACTATAGCTGGAATTTAGAGCAGCTACACCCAGAGCACCAGGTGCTTGAACATACTGCCTGGATAGTTCCATATTCCTGCACTCTTTCACTTGTTCGCTTACATGTATTTATTTTCTCCCTCAGTTGTAGGAATTCTAGAGGGACCAAATATCA>
#$$$$%#'%#&))*+(('&&&#%$%%AB;=>46>48EF:10-1/57<@7134:;)*-8>8;5A((%.%8123.+.)2((--0344;>2/&..*7))+34.--211868EHBD?>F@DA10(.526--1+11.6<+5(,/C2CI@=4@4--,-&/(04:-3=E?67=B>12$),.*$()'5'8,00/0&3:-3:58E@D?B@1>
s1:i:292917
s2:i:884
CG:B:i,372,480,18,208,18,80,18,80,17,176,17,624,34,352,34,320,34,112,33,64,18,64,17,592,18,784,34,624,49,80,18,304,33,1008,17,432,17,1216,34,640,33,320,17,16,34,64,18,752,17,16,34,96,33,64,17,144,34,16,>
AS:i:906162
cm:i:35982
nn:i:0
tp:A:P
ms:i:903524
dv:f:0.0787
MD:Z:0
NM:i:0
RG:Z:HG002_ONT_rel1
```

Would you expect that this would be an issue with an upstream tool or samtools? The data is all there in GIAB if the issue might need reproducing but it is large :)

**Comment by jkbonfield** [comment]
The cause of this is that the tag is `CG:B:i` and not `CG:B:I` as the specification dictates.

Possibly this is being a bit overly precise though.  I'll need to figure out why it ended up lowercase though, and whether it's a CRAM issue or something else that wrote the initial file.

**Comment by jkbonfield** [comment]
Do you know much about the history of this file?  Whoeever created it hasn't been filling out PG headers correctly.

There are two `PG` header records - minimap2 and whatshap, but neither of them have a `PP` (previous program) so the header is disjoint.  Furthermore whatshap implies it wrote to a CRAM file (which wouldn't be using CG as it doesn't need it), but we're viewing a BAM so there has been an unrecorded tool that converted formats.  Presumably that was the tool that wrote the CG tag wrongly.

I wish people actually cared about data provenance. :-(

**Comment by cmdcolin** [comment]
actually the provenence is  weird, and surprised me before  because it was actually a BAM file and BAI file with a CRAM and CRAI extension. I wasn't involved in the data generation but there is a note here



See
https://ftp-trace.ncbi.nlm.nih.gov/giab/ftp/data/AshkenazimTrio/HG002_NA24385_son/Ultralong_OxfordNanopore/combined_2018-08-10/HG002_ONTrel2_16x_RG_HP10xtrioRTG.cram_filename_change_01292020.README

**Comment by cmdcolin** [comment]
perhaps that could even explain some things since only bam would really use special handling for CG...if the particular issue here is quite obscure like that maybe it is a not really a practical issue ! it was just weird to see in the browser

**Comment by jkbonfield** [comment]
Bah, I've found that picard `SamFormatConverter` does this. :(

The spec is quite clear:

> With 16 bits, {\sf n\_cigar\_op} can keep at most 65535 CIGAR
operations in BAM files. For an alignment with more CIGAR operations, BAM
stores the real {\sf CIGAR}, encoded the same way as the {\sf cigar} field in
BAM, in the {\tt CG} optional tag of type `{\tt B,I}', and sets {\sf CIGAR} to
`\textit{k}{\tt S}\textit{m}{\tt N}' as a placeholder, where `\textit{k}' equals {\sf l\_seq}, `\textit{m}'

However I think we're maybe being overly precise and should accept `B,i` (provided it doesn't contain negative values).  It is however a bug in picard, or more likely htsjdk.

**Comment by cmdcolin** [comment]
ah...good catch! hopefully they would add the pg headers too:)
