### ISSUE TITLE
Base positions on reads mapped in reverse strand in the pileup format

### ISSUE THREAD

**Issue by ifantasy** [samtools/samtools#1481]
#### Is your feature request related to a problem? Please specify.
I would like to get base mismatch positions on reads (5'->3'). It can be done easily in the pileup format with the option -O enabled. However, in case of reads mapped to reverse strand, it is difficult because the positions are still numbered in the  forward strand direction, not in 5'->3' direction of the target strand. 
#### Describe the solution you would like.
mpileup supports read length output or calculate the positions on reads in 5'->3' direction.

**Comment by jkbonfield** [comment]
It could be done, but it'd need an additional option in order not to break scripts relying on the existing behaviour.

I'm unsure how it'd work around indels though, or even if it's possible to get consistent behaviour between forward vs reverse reads in that scenario.  It needs some experimentation I think.

What was your intended purpose for this, and how would you expect it to work on an insertion or a deletion?  Eg what end of the insertion does the BP figure refer to?  I'm guessing it's always a reference mapped base so it doesn't matter (*I think*).  What about deletions?  They're not in the sequence at all, so does it repeat the next base or the previous base coordinate?  (Indeed does it even make sense how it works now for deleted bases?)

**Comment by jkbonfield** [comment]
Actually I can answer the question of how it works now:

```
1       759442  N       3       AaA     FGG     86,69,68
1       759443  N       3       AaA     FGG     87,70,69
1       759444  N       3       Aa-4nnnnA-4NNNN GIF     88,71,70
1       759445  N       3       T**     FGF     89,72,71
1       759446  N       3       A**     GGF     90,72,71
1       759447  N       3       T**     GGF     91,72,71
1       759448  N       3       T**     BGF     92,72,71
1       759449  N       3       TtT     GGF     93,72,71
1       759450  N       3       AaA     HFI     94,73,72
```

It would appear a deleted base gets the coordinate of the next base in the sequence.  That makes sense as how it works if it's marching along the sequence, and it's pointing to the next base ready for when it arrives, but we don't have it aligned yet.

When reverse complemented, we'd be changing those values to `length-pos` instead.  It'll still be the case that pos 759449's BP figure matches pos 759450's figure in the above example.   I'm not sure anything is correct for a base which is missing, but we could check if in a deletion and increment by an extra 1 so it always refers to the "next" base in a 5' to 3' direction, or it could point to the "next" base in the pileup order.

Thoughts?

**Comment by ifantasy** [comment]
I would like to observe the distribution of mismatches across the reads, thus I can evaluate if there is any sequencing bias in 5' end, 3' end or other regions of reads, just like m-bias plots in WGBS.

I would not consider indels in this purpose. But I think position numbering for indels in the reverse strand can be done like those in forward strand. See the following examples:

Insertion (`4` and `5` in the forward strand or `8` and `9` in the reverse strand would be gone in the pileup):

```
             I  I
5'  1  2  3  4  5  6  7  8  9  10 11 12 3'
    T  G  A  C  G  A  G  C  A  T  A  C
3' 12 11 10  9  8  7  6  5  4  3  2  1  5'
```

Deletion (deletion refers to the next base(s) of `3` in the forward strand or `7` in the reverse strand):
```
             D  D
5'  1  2  3  4  4  4  5  6  7  8  9  10 3'
    T  G  A  C  G  A  G  C  A  T  A  C
3' 10  9  8  8  8  7  6  5  4  3  2  1  5'
```
