### ISSUE TITLE
NotImplementedError:

### ISSUE THREAD

**Issue by starboyvarun** [samtools/samtools#1488]
!conda install --yes -c bioconda bedtools samtools
I am using the above command. But still this below error.

![3](https://user-images.githubusercontent.com/26819449/131206345-95c8a2b1-dbda-470d-945c-cf9b95c1f3ab.JPG)
 I am running this command in google collab but still getting this error.
 Can you tell me how I can solve this?
@daviesrob @jkbonfield  can you please help me solve this issue.

**Comment by starboyvarun** [comment]
@jkbonfield  can you please help me solve this issue.

**Comment by valeriuo** [comment]
This doesn't appear to be related in any way to samtools.
It looks like a mismatch between your BEDtools and pybedtools instances. You may want to update your pybedtools installation as well.
`conda update -c bioconda pybedtools`

**Comment by starboyvarun** [comment]
@valeriuo 
Thanks, I solved the issue.
using conda update -c bioconda pybedtools
