### ISSUE TITLE
Anonymous s3 bucket access

### ISSUE THREAD

**Issue by ctsa** [samtools/samtools#1491]
#### Is your feature request related to a problem? Please specify.

Can samtools/htslib support anonymous s3 bucket access? For instance:

    samtools view -H s3://1000genomes/1000G_2504_high_coverage/additional_698_related/data/ERR3988761/HG00405.final.cram

I've been able to use `HTS_S3_HOST` and `AWS_DEFAULT_PROFILE` to access local private buckets, but haven't been able to get the public bucket access working as s3 URLs. Is there some kind of no-sign-request option for this case?

**Comment by daviesrob** [comment]
This may have broken when we introduced V4 signatures.  It appears to work if you turn on V2 signature mode:
```
HTS_S3_V2=yes samtools view -H s3://1000genomes/1000G_2504_high_coverage/additional_698_related/data/ERR3988761/HG00405.final.cram | head -n 1
@HD	VN:1.5	GO:none	SO:coordinate
```

You can of course also work around the problem by rewriting the URL yourself, and using `https`:
```
samtools view -H https://1000genomes.s3.amazonaws.com/1000G_2504_high_coverage/additional_698_related/data/ERR3988761/HG00405.final.cram | head -n 1
@HD	VN:1.5	GO:none	SO:coordinate
```

... or include some credentials so you're accessing the bucket as an AWS user.

We'll have a look to see if we can get the V4 signature code to work properly for public buckets when you haven't provided any credentials.

**Comment by ctsa** [comment]
Thanks @daviesrob , those are good workarounds and I confirm they both work for me.

**Comment by whitwham** [comment]
Yep, the V4 signature code had no idea what to do without any credentials (which is basically to do nothing).  I'll do a few more tests then put a PR in.
