### ISSUE TITLE
samtools merge CRAM output

### ISSUE THREAD

**Issue by gevro** [samtools/samtools#1494]
Hi,

Issue:
1) I ran samtools merge -O CRAM --reference ref.fasta output.cram input1.bam input2.bam
2) Then I ran samtools sort output.cram > output.sorted.cram
3) Then I ran samtools index output.sorted.cram,
  but the output of that is output.sorted.cram.bai

This is weird because I'm indexing a CRAM file...

I suspect the issue is that samtools merge did not actually output a CRAM file?
But I don't know how to check the format of each file, whether it is a CRAM or BAM.

Regardless, this suggests a bug somewhere, because I don't see any issue with the commands I wrote.

Samtools version:
samtools 1.12
Using htslib 1.12
Copyright (C) 2021 Genome Research Ltd.

Samtools compilation details:
    Features:       build=configure curses=yes 
    CC:             gcc
    CPPFLAGS:       
    CFLAGS:         -Wall -g -O2
    LDFLAGS:        
    HTSDIR:         htslib-1.12
    LIBS:           
    CURSES_LIB:     -lncursesw

HTSlib compilation details:
    Features:       build=configure plugins=no libcurl=yes S3=yes GCS=yes libdeflate=no lzma=yes bzip2=yes htscodecs=1.0
    CC:             gcc
    CPPFLAGS:       
    CFLAGS:         -Wall -g -O2 -fvisibility=hidden
    LDFLAGS:        -fvisibility=hidden 

HTSlib URL scheme handlers present:
    built-in:	 preload, data, file
    S3 Multipart Upload:	 s3w, s3w+https, s3w+http
    Amazon S3:	 s3+https, s3+http, s3
    Google Cloud Storage:	 gs+http, gs+https, gs
    libcurl:	 imaps, pop3, http, smb, gopher, ftps, imap, smtp, smtps, rtsp, ftp, telnet, smbs, https, tftp, pop3s, dict
    crypt4gh-needed:	 crypt4gh
    mem:	 mem

**Comment by valeriuo** [comment]
How about if you run `samtools sort output.cram -o output.sorted.cram` instead? By default, `sort` outputs BAM data to stdout, even if the input is CRAM. This is specified in the documentation:

> By default, samtools tries to select a format based on the -o filename extension; if output is to standard output or no format can be deduced, bam is selected.
