### ISSUE TITLE
Whether samtools can select a certain number of cells from the BED file

### ISSUE THREAD

**Issue by qimiaonnegliguo** [samtools/samtools#1495]
Hello! I am a beginner in bioinformatics. I want to know whether samtools can select a certain number of cells from the BED file. For example, I now have a BED file containing ATAC information for 1000 cells. I just want to choose 500 of them. I want to know whether this work can be performed by samtools. I am very grateful for your help.

**Comment by valeriuo** [comment]
SAMtools doesn't use the concept of cell. It works with alignments (or reads), regions (contigs, scaffolds, chromosomes) and samples. A BED file has **regions** in its first column and it is used by SAMtools commands as a query filter, i.e. SAMtools will select only the alignments that overlap the regions from the BED file. If you want to specify only a subset of those regions (e.g the first 500 out of 1000), you need to trim the BED file yourself before providing it to SAMtools.
