### ISSUE TITLE
samtools view problem

### ISSUE THREAD

**Issue by putianhuizi** [samtools/samtools#1499]
#### I am using the version 1.10 and  gcc 5.1.0 in centos 
Hi , I got an error when I trasnfered sam to bam file after minimap2 for my nanorpore data. 
`minimap2 -p 28 -ax  map-ont XXX.mmi xx.fasta.gz >xx_male.sam`
then I run `samtools view -bS xx_male.sam  > xx_male.bam`
It exited directly and present " [M::main] Real time: 31.302 sec; CPU: 49.525 sec; Peak RSS: 2.820 GB
[W::sam_hdr_create] Ignored @SQ SN:ori[M::main::5.178*1.00] loaded/built the index for 1897 target sequence(s) : bad or missing LN tag
[E::sam_hrecs_update_hashes] Header includes @SQ line "ori[M::main::5.178*1.00] loaded/built the index for 1897 target sequence(s)" with no LN: tag
samtools view: failed to add PG line to the header ".
The result part looks like for the fisrt 20 lines:
@SQ     SN:chr1 LN:88189632
@SQ     SN:chr2 LN:57441030
@SQ     SN:chr3 LN:55509702
@SQ     SN:chr4 LN:45919539
@SQ     SN:chr5 LN:41202720
@SQ     SN:chr6 LN:37808164
@SQ     SN:chr7 LN:34031354
@SQ     SN:chr8 LN:21030328
@SQ     SN:fragScaff_scaffold_1 LN:57102
@SQ     SN:fragScaff_scaffold_108       LN:69684
@SQ     SN:fragScaff_scaffold_110       LN:80411
@SQ     SN:fragScaff_scaffold_114       LN:84714
@SQ     SN:fragScaff_scaffold_115       LN:106091
@SQ     SN:fragScaff_scaffold_117       LN:47163
@SQ     SN:fragScaff_scaffold_133       LN:57351
@SQ     SN:fragScaff_scaffold_137       LN:133280
@SQ     SN:fragScaff_scaffold_142       LN:38929
@SQ     SN:fragScaff_scaffold_152       LN:104679
I wonder which part goes wrong and how to fix it ?Thank you

**Comment by putianhuizi** [comment]
'SQ" are upcase in file but turned to downcase here.

**Comment by jkbonfield** [comment]
You'll need to surround text with triple-backquote blocks if you wish to avoid the @ name detection in github.

Regarding the error, it sounds like your header has some stderr text mangled in with it too.  "[M::main::5.1781.00] loaded/built the index for 1897 target sequence(s)" is a normal diagnostic message from minimap2.

Don't use tools like nohup in conjunction with piping output or redirection, as it mixes stdout and stderr together.  If this is coming from a batch scheduling system which is mixing up the output streams then it is buggy!  Both of these may be worked around though by explicitly redirecting stderr.  Eg:

```
      minimap2 [args] 2>stderr > output.sam
```

Closing this as it's not a samtools problem.

**Comment by putianhuizi** [comment]
Thank you for answer! It helps a lot.

**Comment by jkbonfield** [comment]
Thanks.  Out of curiosity, was it nohup you used?  We see this a lot, but have never really got to grips with what's causing it.  If there is some standard pipeline or batch scheduler out there which is mixing stderr and stdout up then it'd be good to know.

**Comment by putianhuizi** [comment]
> Thanks. Out of curiosity, was it nohup you used? We see this a lot, but have never really got to grips with what's causing it. If there is some standard pipeline or batch scheduler out there which is mixing stderr and stdout up then it'd be good to know.

Just nohup without other pipelines.
