### ISSUE TITLE
samtools coverage doc

### ISSUE THREAD

**Issue by pmenzel** [samtools/samtools#1504]
The actual output for the field `coverage` seems to be in the range `0..100` and not in `0..1` as written in the doc:
https://github.com/samtools/samtools/blob/a78376c5fe659bd53819fc0a960ec699830a3ecb/doc/samtools-coverage.1#L62

**Comment by daviesrob** [comment]
Yes, the proportion is [multiplied by 100.0](https://github.com/samtools/samtools/blob/0cc1a84482990363363c8fa95acc8b5563256499/coverage.c#L206) when printed out, so it's a percentage.  We'll fix the documentation to match.
