### ISSUE TITLE
How can I get the bining coverage depth using samtools depth?

### ISSUE THREAD

**Issue by omG0-hub** [samtools/samtools#1505]
Hi,

I have a WGS human bam file, and I want to get the average value in 500 bins.
I tried to many methods for obtaining read depth info, but I couldn't get it.

First, I get read depth per base using samtools depth.
`samtools depth -a sorted.bam > coverage.txt` or `samtools depth sorted.bam > coverage.txt`
and then, I have tried bedtools "makewindows" option to get a bed file divided by window size 500.
`bedtools makewindows -w 500 -g reference.txt > bin500.bed`
![image](https://user-images.githubusercontent.com/70621317/134815077-17d0e7b5-bf11-4856-a426-5ae2817d758d.png)

Finally, I executed below command for getting the 500 bin size coverage data.
`samtools depth -b bin500.bed sorted.bam > bin500_coverage.txt`
However, as a result, a file such as coverage.txt was obtained, not a value calculated by the size of 500.

Could you get some advice what to do ?
I would be happy to hear about your feedback on this.

**Comment by daviesrob** [comment]
The `samtools depth -b` option just selects regions, it doesn't average over those regions.  To get what you want, it would be easiest to post-process the `depth` output with a script.  For example, if you want depth averaged over bins of size 500, something a like this would mostly do the job:

```
samtools depth sorted.bam | perl -lane 'BEGIN { $lref = ""; $lpos = 1; $tot = 0; $width = 500; }
  while ($lref ne $F[0] || $F[1] - $lpos >= $width) {
    if ($lref) {
      printf "%s %d %d %g\n", $lref, $lpos,  $lpos + $width - 1, $tot / $width;
      $tot = 0;
    }
    $lpos = $lref eq $F[0] ? $lpos + $width : 1;
    $lref = $F[0];
  }
  $tot += $F[2];
  END {
    if ($lref) {
      printf "%s %d %d %g\n", $lref, $lpos,  $lpos + $width, $tot / $width;
    }
  }' > binned.out
```

Although I would recommend writing something better for production use, especially as the above doesn't take the chromosome lengths into account properly.
