### ISSUE TITLE
samtools tview for protein ncbi-blast blastp output

### ISSUE THREAD

**Issue by avilella** [samtools/samtools#1507]
I've generated a SAM file with ncbi-blast:
```
/data2/ncbi-blast/ncbi-blast-2.2.31+/bin/blastp -query FTtmSfSnO-4-.mscf.faa -db fastaAConstructs.faa -outfmt 15
```
The context is to try to produce a pileup view of peptides from proteomics onto a set of reference sequences.

And managed to show the results with `samtools tview`. But all the aminoacid characters shown are either A,C,G,T or ambiguity codes for nucleotides. This makes me think there is something missing in the alphabet description somewhere or the way tview works.

Has anybody got `samtools tview` working for protein alphabets? Does it need any special flags or tweaks? If so, could this be implemented?

**Comment by daviesrob** [comment]
I'm suprised you managed to get a SAM file out of `blastp`.  This [blog post](https://blastedbio.blogspot.com/2015/07/ncbi-working-on-sam-output-from-blast.html) says it's possible with the version you used, but I expect it was not officially supposed to work.  Certainly later versions only support SAM output in `blastn`, which makes more sense.

`samtools` is designed for DNA alignments, and does not support the protein alphabet.  I think SAM was also designed with only DNA in mind, although the [specification](https://samtools.github.io/hts-specs/SAMv1.pdf) is a bit quiet about exactly how the sequence should be interpreted.  Certainly the related BAM format only supports DNA sequences (with ambiguity codes).

I think for protein work, you would be better off using formats and programs specifically designed for that domain.

**Comment by avilella** [comment]
Could I ask where are the ACGT and ambiguity codes listed in the samtools
codebase? Maybe I could have my own fork that extends to the current
alphabet plus the 20 aminoacids, and switch off the ambiguity code pileup
in tview. Thanks

**Comment by avilella** [comment]
I should add that I've been following the samtools tickets related to
epigenetic modifications, and thinking about it, maybe it is also useful
for Oxford Nanopore data to have a samtools tview that works on an extended
alphabet and doesn't automatically calculate ambiguities during the
column-wise pileup. Good to hear opinions on this.

**Comment by daviesrob** [comment]
[HTSlib](https://github.com/samtools/htslib), the library underlying SAMtools, uses an internal representation that's more like BAM.  In particular, it expects to be able to [store two nucleotide codes in a byte](https://github.com/samtools/htslib/blob/develop/htslib/sam.h#L311-L324), which is possible if you only allow the standard ambiguity codes (see [here](https://github.com/samtools/htslib/blob/develop/hts.c#L226-L247) for conversion tables to/from ASCII).  This is fundamentally baked-in to the code and would not be at all easy to change.

If you would like to expand SAM to support protein alignments, it would be better to discuss on [hts-specs](https://github.com/samtools/hts-specs) than here.

**Comment by avilella** [comment]
If I can store 16 letters, I could collapse down some similar aminoacids
(isoleucine with leucine, etc.) then replace the 16 letter nt dictionary
for my 16 letter aa dictionary. Would that work?

**Comment by avilella** [comment]
See my idea of a 16 letter aa code below.

It still doesn't decode correctly. Is there a special order in which seq_nt16_str characters should be?

```
HTSLIB_EXPORT
const char seq_nt16_str[] = "=ABEFGHKMPQRSTWY";
/* was */
/* const char seq_nt16_str[] = "=ACMGRSVTWYHKDBN"; */

/* collapsed down the 3 below */
/* asparagine or aspartic acid   B   DN                    */
/* glutamine or glutamic acid    Z   EQ                    */
/* V, leucine or isoleucine      J   VIL                   */
/* full list below */
/* any                           X   ADEFGHIKLMNPQRSTVWY   */
```

**Comment by daviesrob** [comment]
I don't think this is a good idea at all.  If you wanted to store protein translations in SAM, it might be better to use an aux tag, where you won't run in to problems with the allowed alphabet.  Although first you should really check out software like [clustal](http://www.clustal.org/) which has been used for protein multiple alignments for years, along with the formats that it supports.

**Comment by avilella** [comment]
Thanks, that's good to consider. I could rehook the 'tview' part on the aux
tag value instead and as you say, it would be much simpler.

The alternative is clustal, as the size of my datasets is in the thousands
of peptides, but mid-term I am thinking about Next Generation Protein
Sequencing (NGPS) of the likes of Quantum-SI and others: having dense
pileups for a concatenated reference sequences of tens of thousands of
proteins, with potentially millions of peptide "reads", then to me it
sounds like a better fit for the samtools/htslib infrastructure overall.
It's the NGS -> NGPS transition which could be coming along soon.

Meanwhile, I am happy to tinker a bit on my own fork now that you've given
me an avenue forward, thanks again for your help.
