### ISSUE TITLE
UMI support in markdup

### ISSUE THREAD

**Issue by Poshi** [samtools/samtools#1514]
#### Is your feature request related to a problem? Please specify.
When working with UMIs the duplicate definition changes: it adds the requirement that different molecules have different UMIs. But the current implementation of `samtools markdup` does not allow the user to specify that the UMI has to be taken into account.

#### Describe the solution you would like.
The solution would be to add a parameter to `samtools markdup` to inform the tag that contains the UMI data. When this tag is given it should be used to further differentiate similar but independent molecules.

**Comment by eboyden** [comment]
+1 for adding this.  It would be extra great if it used a sophisticated algorithm similar to that used by umi-tools (or offered a choice of algorithms) but even a simple method would be appreciated.  Umi-tools is nice but requires indexed bams and so doesn't work on a pipe, plus it only marks read 1 in a pair.  When marking but not removing duplicates, both reads in a pair should be tagged and the bitflags properly set.

**Comment by whitwham** [comment]
Looking at including UMIs in markdup is my next samtools task.

**Comment by whitwham** [comment]
Added UMI/barcode support in #1630 ready for testing.  Please open a new issue if you find something wrong with it.
