### ISSUE TITLE
idxstats showing extemely large values of chr21 and reduced chrM

### ISSUE THREAD

**Issue by gm9756** [samtools/samtools#1518]
I am reaching out because I have seen an interesting dilemma.  My laboratory is currently updating our alignment script which uses Hisat2, samtools, trimmomatic and ngsutils (now ngsutilsj) to use the most up to date versions.  In comparing alignments done using the older version of both programs to the newest versions we are getting a result that we can't explain when using samtools idxstats.  We appear to be getting almost double the amount of reads mapping to chromosome 21, and almost half the reads mapping to chromosome M.  Additionally, the number of total sequences obtained appears to be 2-3 million higher than the originally aligned files.  We can't figure out why this is happening.  Do you know where the problem may be occurring?

**Comment by daviesrob** [comment]
Hopefully you got this to work.  Please re-open if you still have a problem, and can send us some examples to work on.
