### ISSUE TITLE
samtools markdup slow in docker

### ISSUE THREAD

**Issue by EugeneEA** [samtools/samtools#1524]
samtools samtools 1.13 form the container davelabhub/samtools:1.13--h8c37831_0
but I had the same issue in all other containers I tried, including homebuild

 #### Please describe your environment.
- OS (run `uname -sr` on Linux/Mac OS or ` wmic os get Caption, Version` on Windows)
CentOS Linux 7
Linux 3.10.0-1160.el7.x86_64
- machine architecture (run `uname -m` on Linux/Mac OS or ` wmic os get OSArchitecture` on Windows)
x86_64
- compiler (run `gcc --version` or `clang --version`)
4.8.5 20150623
#### Please specify the steps taken to generate the issue, the command you are running and the relevant output.

I'm trying to pipe some data through diferent samtools tools inside the docker container and got stuck with the perfomance issue, which boiled down to the following observation:

the comand 
` docker run --mount type=bind,source=/,target=/home/   davelabhub/samtools:1.13--h8c37831_0 samtools  markdup -d 100  -@ 100 /path-to-my-file/test.bam out.bam` basically newer finishes wheres just running samtools locally `samtools  markdup  -d 100 -@ 100 /path-to-my-file/test.bam out.bam` works perfectly. I tried several docker containers, I build one myself and I reproduce the issue on different servers. I'm not sure is it samtools issue or not but I stuck and would appreciate any advice. 

what I observed in `htop` for the aforementioned commands, is that when run from the docker, markdup always uses 1 core regardless of what I'm passing with the -@ parameter. Where as with system run it ues multiple cores.

also to notice the issue you need a reasonably large bam file. with the toy example of couple mb you wont see a difference. 

Best wishes, Eugene

**Comment by whitwham** [comment]
I couldn't replicate this at the time and, with more experience with docker, I can't replicate it now.  I'm going to close this until I can come up with more evidence.
