### ISSUE TITLE
inconsistent support for ##idx## remote urls between BAM & CRAM

### ISSUE THREAD

**Issue by cariaso** [samtools/samtools#1541]
samtools 1.11
Using htslib 1.11
Copyright (C) 2020 Genome Research Ltd.

Linux 4.14.252-195.483.amzn2.x86_64
gcc (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0

`samtools view -u s3://mybucket/mypath1/my.bam##idx##s3://mybucket/mypath2/my.bam.bai chr6:29886751-29886799`

works

but

`samtools view -u s3://mybucket/mypath3/my.cram##idx##s3://mybucket/mypath4/my.cram.crai chr6:29886751-29886799`

does not.  This does produce some valid output at first, but ends abruptly with

[E::cram_index_load] Could not retrieve index file for 's3://mybucket/mypath3/my.cram##idx##s3://mybucket/mypath4/my.cram.crai'
[main_samview] random alignment retrieval only works for indexed BAM or CRAM files.

So there seems to be some issue with CRAM support in the changes related to
https://github.com/samtools/samtools/pull/1176
https://github.com/samtools/samtools/blob/4fe33221082adceedfdbf525ced54c1a0883998c/NEWS#L63
https://github.com/samtools/samtools/blob/4fe33221082adceedfdbf525ced54c1a0883998c/NEWS#L216

**Comment by jkbonfield** [comment]
It appears this isn't related to s3, but `##idx##` in general.  I believe it'll be fixed once the above PR gets merged.

Thanks for reporting the bug.
