### ISSUE TITLE
Select MAPQ scores from BAM/CRAM file

### ISSUE THREAD

**Issue by sagnikbanerjee15** [samtools/samtools#1547]
Hello,

I was wondering if it would be possible to extract only the MAPQ scores from a BAM or CRAM file without having to convert the file to SAM format.

Thank you.

**Comment by jkbonfield** [comment]
It can be done programmatically, but I can't think of something to do only that on the command line.  However note you can select which columns you're interested in.  This has no impact on BAM, but speeds up CRAM considerably.  Eg:

```
samtools view --input-fmt-option required_fields=0x10 ~/scratch/data/novaseq.10m.cram
```

Search for "required_fields" in the samtools.1 man page for the numbers.  (We really ought to upgrade that to be sensible strings instead.)

On the 10 million read test CRAM file this took 2.5s.    On the same dataset in BAM it took 11s, and without `required_fields` the CRAM took 20s.  So you may find just processing SAM isn't so bad afterall.

**Comment by sagnikbanerjee15** [comment]
Thanks for your reply @jkbonfield. I checked and found processing both SAM and CRAM roughly takes the same time!
