### ISSUE TITLE
Mixup in samtools depth documention

### ISSUE THREAD

**Issue by stephan-hutter** [samtools/samtools#1549]
In the *caveats* section of http://www.htslib.org/doc/samtools-depth.html it states:
- Deletions (CIGAR element "D") are counted by default in "depth". This can be turned off with the -J option. "Mpileup" always ignores these bases, and has no option to count them.

Shouldn't this be exactly the other way around? I am observing in samtools 1.14 that the default is *not* counting CIGAR "D"s and -J turns this behaviour on. Which is also what is written in the options description...

**Comment by jkbonfield** [comment]
You are correct here.  Thanks for reporting this.

Furthermore the sentence about mpileup is also back to front - it always counts deleted bases and has no option to not count them.  I'll make a PR to fix this.
