### ISSUE TITLE
Issue with Ampliconclip resulting in non-ATCG characters at the end or beginning of sequences.

### ISSUE THREAD

**Issue by zhemingfan** [samtools/samtools#1550]
#### Environment
- OS: Linux 3.10.0-957.5.1.el7.x86_64
- machine architecture: x86_64
- compiler: gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-36)

#### Please specify the steps taken to generate the issue, the command you are running and the relevant output.

Ampliconclip sometimes results in characters at the end or beginning of the certain trims (e.g "=", sometimes a letter) present on the sequence line. These are not artifacts of sequencing (and weren't present prior to the trim). 

E.g "=ATCGAT"

**Comment by whitwham** [comment]
Is your problem the same as this #1527?

**Comment by zhemingfan** [comment]
I'm currently using the latest commit on Github - commit `fc03d3f`

**Comment by whitwham** [comment]
Well that is disappointing, I thought that last problem was solved.

Okay.  Let me know what options you were running with.  If you could give me a small example of the data where it goes wrong then that would be very helpful.  Just a line from the BED file and the SAM file would be great.

**Comment by whitwham** [comment]
@zhemingfan Is there any update on this?

**Comment by zhemingfan** [comment]
Hi @whitwham, thanks for the check-in: I can send you a short sequence over email. I couldn't find an email address to send it to?

**Comment by whitwham** [comment]
@zhemingfan andrew dot whitwham at sanger dot ac dot uk.

**Comment by whitwham** [comment]
@zhemingfan I haven't received any emails yet?  Did you manage to get some data together?

**Comment by whitwham** [comment]
Since there is no response from @zhemingfan, I am going to close this.
