### ISSUE TITLE
samtools coverage numreads different to idxstats

### ISSUE THREAD

**Issue by SamH1985** [samtools/samtools#1551]
Hi, I can see in the documentation that samtools coverage gives number of reads after filtering. I wondered what this filtering is, as I get a lot fewer numreads using coverage, compared to mapped read-segments in idxstats. I thought they would be the same. I think I might be misinterpreting this... Many thanks for your help.

**Comment by jkbonfield** [comment]
If you look at the usage help for samtools coverage it states:

```
  --ff <int|str>          filter flags: skip reads with mask bits set 
                                      [UNMAP,SECONDARY,QCFAIL,DUP]
```

I believe this is likely the cause of the difference in stats counts.  The idxstats only breaks data down by mapped / unmapped, and doesn't have any data on other flags.  Hence it should be the same as `samtools coverage --ff UNMAP`.
