### ISSUE TITLE
does samtools sort throw some reads away?

### ISSUE THREAD

**Issue by ymoon06** [samtools/samtools#1555]
#### Are you using the latest version of [samtools](https://github.com/samtools/samtools/releases/latest) and [HTSlib](https://github.com/samtools/htslib/releases/latest)? If not, please specify.
(run `samtools --version`)
->using samtools version 1.14

 #### Please describe your environment.
- OS (run `uname -sr` on Linux/Mac OS or ` wmic os get Caption, Version` on Windows)
- machine architecture (run `uname -m` on Linux/Mac OS or ` wmic os get OSArchitecture` on Windows)
- compiler (run `gcc --version` or `clang --version`)
-> gcc 9.3.0 , ubuntu 20.04 in Windows 10
#### Please specify the steps taken to generate the issue, the command you are running and the relevant output.
->I am not sure if here is where I can post questions about samtools. If not, I will ask somewhere else.
I was selecting representative read closest to the 3' UTR but some of reads seem to be lost after using samtools sort function even if they had CB, UB and GX tag. 

Does the samtools sort remove some of reads by default?
I used  samtools sort output.bam -o output_sorted.bam for sorting 
and samtools index output_sorted.bam for indexing.

I also used UMI tools deduplication  and there, after deduplication, I did sorting and again where some of reads are missing again.

The size of bam file before sorting was 56MB but after sorting it becomes 36MB.
 May I ask if there is a parameter that removes some of reads? if yes, how can we get all reads?
 
 thank you.

**Comment by whitwham** [comment]
No, samtools sort should not lose any reads.  For the simple position sort you are using, samtools sort does not use tags for anything.

Running a bam file through samtools sort can change the size when the output bam file is recompressed.

If you run samtools flagstat on output.bam and output_sorted.bam we can find out the exact number of reads difference.

**Comment by jkbonfield** [comment]
Agreed with everything @whitwham says.

Answering the first query, here is fine for Samtools issues that you think may be either bugs or are feature requests.  Both of these are invaluable to us for improving the software.

More general usage queries are probably best addressed to somewhere like BioStars as the audience (and therefore speed and sometimes accuracy of reply) is considerably larger.  Obviously it is your judgement as to what may be a bug vs general usage queries, but if in doubt we do want to hear of potential problems.

Thanks.

**Comment by netwon123** [comment]
I also found samtool sort would loss some reads, could u solve this question?
