### ISSUE TITLE
given path to lib,but configure erro: curses development files not found.

### ISSUE THREAD

**Issue by chairchild** [samtools/samtools#1556]
when I configured samtools v1.14, this erro reported:
.....
checking for Ncurses library... no
checking for Curses library... no
configure: error: curses development files not found

The 'samtools tview' command uses the curses text user interface library.
Building samtools with tview requires curses/ncurses/etc development files
to be installed on the build machine; you may need to ensure a package such
as libncurses5-dev (on Debian or Ubuntu Linux) or ncurses-devel (on RPM-based
Linux distributions) is installed.

FAILED.  Either configure --without-curses or resolve this error to build
samtools successfully.

-------------------------------------------------------------------------------------------------------------
libncurses.so in conda/lib, and ncurses.h in conda/include was checked and the path was passed to CFLAGS, LDFLAGS , and LD_LIBRARY_PATH.
what should I do?

**Comment by chairchild** [comment]
then I used --without-curses, a similar erro reported:
.......
checking for zlib.h... yes
checking for inflate in -lz... no
configure: error: zlib development files not found

Samtools uses compression routines from the zlib library <http://zlib.net>.
Building samtools requires zlib development files to be installed on the build
machine; you may need to ensure a package such as zlib1g-dev (on Debian or
Ubuntu Linux) or zlib-devel (on RPM-based Linux distributions) is installed.

FAILED.  This error must be resolved in order to build samtools successfully.

**Comment by jkbonfield** [comment]
Please read the INSTALL notes in samtools and htslib for the list of prerequisites.  It includes appropriate package names for a variety of operating systems.

**Comment by chairchild** [comment]
thanks, i had solved this. 
I copied libcurse and zlib from conda to all path that the program might search.  and use CURSE_LIB= -l curses flags.

> Please read the INSTALL notes in samtools and htslib for the list of prerequisites. It includes appropriate package names for a variety of operating systems.
> 
> https://github.com/samtools/samtools/blob/develop/INSTALL https://github.com/samtools/htslib/blob/develop/INSTALL

**Comment by jkbonfield** [comment]
Generally attempting to resolve conda issues by copying files around is a bad idea, but if you managed to get things built then I'll close the issue.

My advice though: if you're using conda, use the conda pre-packaged samtools/htslib too.  This may need a fresh environment or explicitly requesting the version if it's picking something outdated.   Or if you want to build from source, do so without any conda stuff in your PATH, installing and/or compiling the prerequistes yourself outside of Conda.  (In theory you should be able to compile new source from within Conda, but that may also require a conda install of the compilers too so they operate nicely with the rest of conda.  My experience is such complexities are probably just best avoided when a simple alternative is available.)

**Comment by jkbonfield** [comment]
Please don't bump old closed issues.

As for your question, most problems of building from source can be solved by:

1) Use the configure script, not just "make"
2) Carefully read the INSTALL file for the list of prerequisites to install.
