### ISSUE TITLE
mpileup command do not work properly when `--min-BQ` flag is set to 0

### ISSUE THREAD

**Issue by yech1990** [samtools/samtools#1564]
By default, `mpileup` command will only count overlap region of PE reads once, expect the `-x` flag is given. But when run `mpileup` commad with the `-Q/ --min-BQ` flag, and the argument is less than 1 (0 for example), **the mpileup command will count overlap region twice.**

**Comment by jkbonfield** [comment]
I thought we'd documented this, but it appears not.

Fundamentally it can't be fixed without a major redesign.  The way the overlap removal was implemented was to set filtered bases to quality 0 and then rely on the minimum base quality filter to reject them.  I don't think it's possible to set them to quality -1, but that's about the only potential solution I could see.

For now I would not advise setting min-BQ to 0.  (No valid base should ever get quality zero as phred quality zero should be reserved for N only, as the meaning of zero is to assert that the base is incorrect with 100% certainty.)

**Comment by yech1990** [comment]
Thank you @jkbonfield . Yes, this can be easily avoid by setting another min-BQ. But it is undocumented and might cause bug in the downstream application.
