### ISSUE TITLE
[E::hts_idx_push] NO_COOR reads not in a single block at the end 36 -1

### ISSUE THREAD

**Issue by jingydz** [samtools/samtools#1565]
#### Are you using the latest version of [samtools](https://github.com/samtools/samtools/releases/latest) and [HTSlib]
samtools 1.10
Using htslib 1.10.2

 #### Please describe your environment.
Linux 5.4.0-84-generic, x86_64, gcc (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0

#### Please specify the steps taken to generate the issue, the command you are running and the relevant output.
$samtools index -@ 16 xxx_rep1.rmchrM.mm10.bam
[E::hts_idx_push] NO_COOR reads not in a single block at the end 36 -1
[E::sam_index] Read 'E100015604L1C025R0130277562' with ref_name='chrX', ref_length=171031299, flags=163, pos=3050097 cannot be indexed
samtools index: failed to create index for "xxx_rep1.rmchrM.mm10.bam"

**Comment by whitwham** [comment]
Indexing will only work on a sorted BAM file.  See #1559.

**Comment by whitwham** [comment]
In fact, with 1.10 onwards you should be able to index a BAM file while you are sorting it.
`samtools sort --write-index -o outfile.bam infile.bam`
