### ISSUE TITLE
samtools view -H fails with standard input 

### ISSUE THREAD

**Issue by skchronicles** [samtools/samtools#1567]
## Cannot get header from standard input

`samtools view -H`  seems to always fail when given standard input AND the shell has `set -eo pipefail` enabled. The exit code returned is always, **141**, due to a pipe failure. 

**Here is a very basic reproducible example:**
```
#!/bin/bash
set -euo pipefail 

# Works fine 
cat test.sam | grep --color=never '^@..\b'
echo 'grep works!'

# There be dragens here
cat test.sam | samtools view -H
echo 'samtools works!'

echo 'The dragens are a lie!'
```

#### Are you using the latest version of [samtools](https://github.com/samtools/samtools/releases/latest)?
I have tried with multiple versions of samtool including:
- samtools/1.9 
- samtools/1.13

 #### Please describe your environment.
- OS: CentOS7 Linux 3.10.0-862.14.4.el7.x86_64
- machine architecture: x86_6
- compiler: gcc (GCC) 4.8.5
 
#### Please specify the steps taken to generate the issue, the command you are running and the relevant output.

Please see script above for example and screen shots below for more information:
> **Reproducing the error**
![image](https://user-images.githubusercontent.com/18038345/146614805-df4862b3-2d00-4f31-bfcd-44406e7b0c08.png)
![image](https://user-images.githubusercontent.com/18038345/146614600-266919a1-8e7a-4ddb-9e6c-63e620975d99.png)

The example above always returns an exit code of 141. I have tried a few other tools like `sambamba view -S -H` and `picard ViewSam` to just grab the header of a SAM/BAM file from standard input, and they both unexpectedly fail with the same exit code. I ended up just using `grep '^@..\b'` to accomplish the same thing; however, I though it might be worth bringing to your attention. I am not sure if this is a bug in the HTS library (and I am also not sure if all the tools I listed above use it under the hood). 

I have tried running the command with different sam files, all of which result in the same error.

Also, please feel free to let me know if you need anything else. I am more than happy to help in any way!

Thank you for your time,
@skchronicles

**Comment by daviesrob** [comment]
The return value isn't coming from `samtools`, it's from `cat` which is getting a `SIGPIPE` when `samtools` has finished reading the header.  You should be able to see much the same result by using `head` instead of `samtools` in the pipeline - see for example [this StackExchange answer](https://unix.stackexchange.com/questions/580117/debugging-sporadic-141-shell-script-errors).

To avoid this problem, you should either let `samtools view -H` read from the original file instead of a pipe, or write the pipeline in a way that returns zero for the part of the pipe feeding into `samtools` if it stops reading early.

**Comment by skchronicles** [comment]
Hello @daviesrob,

I hope you are having a great day! Thank you for getting back with me so quickly. I just wanted to relay that you are 100% correct. I am not sure how I have never encountered this issue until now but it is due to SIGPIPE signal from the `cat` command.

> To avoid this problem, you should either let samtools view -H read from the original file instead of a pipe, or write the pipeline in a way that returns zero for the part of the pipe feeding into samtools if it stops reading early.

Yes, I agree 100%. I am going to close this issue. Thank you again for your response!
