### ISSUE TITLE
more flexible '--write-index' option for sort

### ISSUE THREAD

**Issue by eboyden** [samtools/samtools#1568]
Samtools `sort` can automatically index an output file (although this isn't currently mentioned in the manual, only in the command help).  However it outputs a `.bam.csi` file, with no option to specify either the file name or index type.  Not all downstream tools will necessarily recognize a `.csi` index.

Although the simplest solution is probably to just use `index` to write a user-specified index, if there were interest it would be nice to provide an option to specify an index name for `sort`, and determine the index type from the file suffix.

**Comment by jkbonfield** [comment]
I'll check in the new year, but it's likely you can use the filename##idx##filename.bai syntax to control the index file type.  (Search for ##idx in the samtools.1 man page)

**Comment by eboyden** [comment]
Looks like you're correct, `sort` (and apparently every tool) already does support this. From the main page under "Global Command Options" (bolding is mine):

> The --write-index option enables automatic index creation while writing out BAM, CRAM or bgzf SAM files. Note to get compressed SAM as the output format you need to manually request a compression level, otherwise all SAM files are uncompressed. By default SAM and BAM will use CSI indices while CRAM will use CRAI indices. **If you need to create BAI indices note that it is possible to specify the name of the index being written to, and hence the format, by using the filename##idx##indexname notation.**

So I apologize for the unnecessary request - I just missed the description of how to do this in the documentation.  Thanks for the assist!
