### ISSUE TITLE
[E::hts_hopen] Failed to open file : Exec format error

### ISSUE THREAD

**Issue by JuanMartinezV** [samtools/samtools#1572]
#### Are you using the latest version of [samtools](https://github.com/samtools/samtools/releases/latest) and [HTSlib](https://github.com/samtools/htslib/releases/latest)? If not, please specify.
(run `samtools --version`)
**Version: 1.14** 
 #### Please describe your environment.
- OS (run `uname -sr` on Linux/Mac OS or ` wmic os get Caption, Version` on Windows)
**Linux 5.11.0-1023-gcp**
- machine architecture (run `uname -m` on Linux/Mac OS or ` wmic os get OSArchitecture` on Windows)
**x86_64**
- compiler (run `gcc --version` or `clang --version`)
**gcc (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0**
#### Please specify the steps taken to generate the issue, the command you are running and the relevant output.

Hi, I'm trying to create a database from a previous assembly following this steps [](https://rpubs.com/ednachiang/MetaG_Pipeline ) section 9D: index and create a BAM File.

I was able to Index the Assembly with `samtools faidx /home/juaan_villalobos15/SRR37_Spades/contigs.fasta` 
but when I try to create the BAM File with `samtools import contigs.fasta.fai SRR37.sam SRR37_Spades/SRR37.bam`  the output give me the following error 

```
[E::hts_hopen] Failed to open file contigs.fasta.fai
[E::hts_open_format] Failed to open file "contigs.fasta.fai" : Exec format error
contigs.fasta.fai: Exec format error
```
The contigs.fasta.fai file looks like this 
```
(base) juaan_villalobos15@meta-1:~/SRR37_Spades$ head contigs.fasta.fai
NODE_1_length_228909_cov_16.528193      228909  36      60      61
NODE_2_length_218024_cov_31.062819      218024  232797  60      61
NODE_3_length_201993_cov_15.880019      201993  454491  60      61
NODE_4_length_198391_cov_15.743621      198391  659887  60      61
NODE_5_length_189518_cov_70.159178      189518  861621  60      61
NODE_6_length_163933_cov_15.619069      163933  1054334 60      61
NODE_7_length_160042_cov_7.891083       160042  1221035 60      61
NODE_8_length_151184_cov_11.981177      151184  1383781 60      61
NODE_9_length_148526_cov_30.887220      148526  1537521 60      61
NODE_10_length_146926_cov_8.000919      146926  1688559 60      61
```
Any advice on how could I resolve this?
Thank you!

**Comment by JuanMartinezV** [comment]
I was able to solved by using Anvio's 
`conda create -y --name anvio-7.1 python=3.6`
`conda activate anvio-7.1`
`conda install -y -c bioconda bowtie2 tbb=2019.8`
`conda install -y -c bioconda samtools=1.9`

**Comment by freixas84** [comment]
I am getting the same error, can you elaborate more why was it fixed with Anvio's?

**Comment by JuanMartinezV** [comment]
Hi Freixa, 
I think it was the programs version, Python (3.6), bowtie2 (2019.8) and samtools (1.9), at that time I was using the latest version of these three, then when I changed it, using what Anvio's already has it worked. 

I wrote the pipeline here on [Notion](https://quirky-ghoul-d8c.notion.site/Pipeline-34447048d9bd4b2fbeb08989405c1754), Search for the step six (It is all in spanish hehe) I hope this can help!
