### ISSUE TITLE
samtools mpileup: parsing of header failed but exit code was zero

### ISSUE THREAD

**Issue by pdagosto** [samtools/samtools#1573]
#### Are you using the latest version of [samtools](https://github.com/samtools/samtools/releases/latest) and [HTSlib](https://github.com/samtools/htslib/releases/latest)? If not, please specify.
(run `samtools --version`)
samtools 1.8
Using htslib 1.8
Copyright (C) 2018 Genome Research Ltd.

Note: we are under GMP restrictions and this is our validated version.

 #### Please describe your environment.
- OS (run `uname -sr` on Linux/Mac OS or ` wmic os get Caption, Version` on Windows)
Linux 3.10.0-1160.45.1.el7.x86_64

- machine architecture (run `uname -m` on Linux/Mac OS or ` wmic os get OSArchitecture` on Windows)
x86_64

- compiler (run `gcc --version` or `clang --version`)
gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-44)

#### Please specify the steps taken to generate the issue, the command you are running and the relevant output.

samtools mpileup -u -d 10000000 -t DP,AD,ADF,ADR,SP -m 20 -q 20 -Q 20 -L 10000000 -f 2373SpikePtnSeq_NC_001623.1.fasta -o raw.mpileup.201223_ag53cw-supe-x1_S1_NB551297_AHGK5TAFX2.vcf alignment.201223_ag53cw-supe-x1_S1_NB551297_AHGK5TAFX2.sorted.bam

The reference file contains two headers:

>2373_spike_protein_sequence
>NC_001623.1_Autographa_californica_nucleopolyhedrovirus,_complete_genome

The second header, which contains two embedded commas produces the following output in stderr:

[E::bcf_hdr_parse_line] Could not parse the header line: "##contig=<ID=NC_001623.1_Autographa_californica_nucleopolyhedrovirus,_complete_genome,length=133894>"

which would seem to indicate an error yet the exit code for the program was 0 which indicated a successful completion.

I have the following questions (note that I am a software guy not a bioinformatician):

1. Does the [E::bcf_hdr_parse_line] notation in the stderr output indicate an error? If so, why does the program exit with a success code? This complicates out pipeline since we should not perform further steps if the samtools mpileup has failed. We detect failure by examining the exit code.

2, I understand that the commas may be a problem. Are both of them problems or only the first one?

Please let me know if additional information is required.

**Comment by daviesrob** [comment]
While `bcf_hdr_parse_line` does consider this an error, unfortunately the code in `samtools 1.8` that called it didn't check the return code, so effectively turned it into a warning.  The result would be that you don't get a `##contig` line for this entry in the header, and undefined behaviour (meaning I can't quite work out what would happen, but it's likely to be bad) when it tries to write the VCF records.  Note that the production of vcf/bcf using `samtools mpileup` has been deprecated for quite a while now, and the feature will be removed entirely on the next release (the replacement is `bcftools mpileup`).
  
Commas are a problem, and should not be used in reference names.  The SAM specification now, rather belatedly,  includes a [section](https://samtools.github.io/hts-specs/SAMv1.pdf#subsubsection.1.2.1) which describes which characters are allowed.  I would strongly recommend only using references that conform to that text.

**Comment by pdagosto** [comment]
Thanks for the explanation - it makes sense. I will inform the bioinformaticians about the situation with samtools mpileup.
