### ISSUE TITLE
How to visualize the depth file

### ISSUE THREAD

**Issue by DooYal** [samtools/samtools#1577]
How to visualize the depth file or change the Y-axis of the coverage histogram into the data of "aligned read count per bin" instead of "aligned read coverage per bin"

**Comment by DooYal** [comment]
How to visualize the depth file or change the Y-axis of the coverage histogram into the data of "aligned read count per bin" instead of "aligned read coverage per bin"

**Comment by DooYal** [comment]
How to visualize the depth file or change the Y-axis of the coverage histogram into the data of "aligned read count per bin" instead of "aligned read coverage per bin"

**Comment by DooYal** [comment]
> 

Thanks for your advice. I think of that maybe some scripts like R can visualize the depth file, but the layout format should be modified.

**Comment by jkbonfield** [comment]
Should be modified to what?

**Comment by DooYal** [comment]
> Should be modified to what?

Sorry, I actually found nothing should be moditified. 
I typed a loop with the core command being "samtools view -c -F 0X04 test.sort.bam $refID:$i-$j >> ${j}.tempcount". (i=0; j=i+bin size; samtools $command; position info added into the file; i=i+bin size), then, I merged these files and also sorted the positions for R to visualize the output.


R script
`library(ggplot2)
df<- read.table("sort.read.pos_count", header=T, sep="\t", fill=T)
figure <- ggplot() + geom_bar(data = df, mapping = aes(x=pos,y=count), stat = 'identity')`

**Comment by DooYal** [comment]
Sorry, I actually found nothing should be moditified. 
I typed a loop with the core command being "samtools view -c -F 0X04 test.sort.bam $refID:$i-$j >> ${j}.tempcount". (i=0; j=i+bin size; samtools $command; position info added into the file; i=i+bin size), then, I merged these files and also sorted the positions for R to visualize the output.

R script
`library(ggplot2)`
`df<- read.table("sort.read.pos_count", header=T, sep="\t", fill=T)`
`figure <- ggplot() + geom_bar(data = df, mapping = aes(x=pos,y=count), stat = 'identity')`

**Comment by jkbonfield** [comment]
Note that should probably be `i+bin_size-1` as the range is inclusive.  Although I doubt it really makes any noticable difference.  Also note it's counting the number of records that _overlap_ rather than _start within_ the bin.  So the summation of bin values will be higher than the total read count in the combined regions.

**Comment by DooYal** [comment]
> Note that should probably be `i+bin_size-1` as the range is inclusive. Although I doubt it really makes any noticable difference. Also note it's counting the number of records that _overlap_ rather than _start within_ the bin. So the summation of bin values will be higher than the total read count in the combined regions. (It would be possible to get _start within_ instead if you use the expression language to further filter the results.)

If the bin size large enough, the bias will not significantly affect the conclusion, and the corresponding figure is just regarded as one of supplementary materials for friendly review, as the original samtools depth file is a long data frame, which is not so friendly for reviewing. 
Actually, I met with such tissue before, however, that former one is counting base pairs of the targets per bin: When the targets are exactly located between 2 bins, the corresponding base pairs are separated into base pairs at former bins and base pairs at latter bins with independently calculation. But differently, if only count the target number, I confess that the bias is inevitable.

不知道码友是不是中国人，我这蹩脚中式英语有没有看懂😓

**Comment by jkbonfield** [comment]
As the bins get larger the number of bases becomes a very good proxy for the number of reads overlapping a bin (multiply by average read length).   The bin size where that becomes true will depend on read length though, so may not be a viable proxy for long read technologies.

So for low-res chromosome level plots, it's unlikely you'll see much visual difference between Nbases/avg_read_len vs Nread being plotted.  That's probably even true for long read technology.

**Comment by DooYal** [comment]
> As the bins get larger the number of bases becomes a very good proxy for the number of reads overlapping a bin (multiply by average read length). The bin size where that becomes true will depend on read length though, so may not be a viable proxy for long read technologies.
> 
> So for low-res chromosome level plots, it's unlikely you'll see much visual difference between Nbases/avg_read_len vs Nread being plotted. That's probably even true for long read technology.

Thanks for the tips. And the read lengths in my samples are equal to 150 bp or 75 bp, so there might be just a little bit bias when the plots were established.

**Comment by jkbonfield** [comment]
OK, that sounds promising then.

Given we don't have plans to produce an alternative version of depth that counts read numbers (either spanning or starting at each position), and we've discussed possible workarounds, I'll consider this issue closed.
