### ISSUE TITLE
Errors when compiling samtools-0.1.17

### ISSUE THREAD

**Issue by zhitian-wu** [samtools/samtools#1586]
I have downloaded bcf file from [ricevarmap](http://ricevarmap2.ncpgr.cn/Download_bcfs/). In order to "view" this old bcf format (probably "bcf1") and convert it to a newer format, it's said on the [help page](http://ricevarmap2.ncpgr.cn/v1/download/) that I have to install samtools-0.1.17, which has a older version bcftools in it.

I downloaded this version from sourceforge but when I **make** source code, it pops out two errors as follows.

```
ar -csru libbcf.a bcf.o vcf.o bcfutils.o prob1.o em.o kfunc.o kmin.o index.o fet.o mut.o bcf2qcall.o
make[1]: ar: No such file or directory
make[1]: *** [Makefile:31: libbcf.a] Error 127
make[1]: Leaving directory '~/rice/samtools/samtools-0.1.17/bcftools'
make: *** [Makefile:17: all-recur] Error 1
```
I am using windows subsystem for Linux, and gcc version is 11.2.0.
How can I install this version?

**Comment by jmarshall** [comment]
[Crossposted to [biostars](https://www.biostars.org/p/9508108/).]

**Comment by zhitian-wu** [comment]
solve this by installing binutils (ar)
