### ISSUE TITLE
samtools rmdup fails on bam with more than one library

### ISSUE THREAD

**Issue by mcshane** [samtools/samtools#159]
samtools rmdup fails when given a bam with more than one library.

samtools rmdup multi_library.bam rmdup.bam
[bam_rmdup_core] processing reference 20...
Samtools-htslib-API: bam_get_library() not yet implemented

Essentially failing for the same reason as #138.

**Comment by bgruening** [comment]
:+1: 
This still exists in:
```
samtools 1.2
Using htslib 1.2.1
```

**Comment by jmarshall** [comment]
This was fixed by the commit above (PR #461, in particular 13de48f8dd6bcd71277128143fadc9ab3aa50576); an `rmdup` command that works as well as it ever did will reappear in the upcoming 1.3 release.

**Comment by bgruening** [comment]
Thanks @jmarshall!
