### ISSUE TITLE
Appetite for a new sort order: TemplateCoordinate

### ISSUE THREAD

**Issue by nh13** [samtools/samtools#1591]
I wanted to gauge the appetite for a pull request for a new sort order, which we have in `fgbio` called [TemplateCoordinate](https://github.com/fulcrumgenomics/fgbio/blob/c26d405c55872b683dfa16ffe8d3c360db5ce898/src/main/scala/com/fulcrumgenomics/bam/api/SamOrder.scala#L167-L198).

This sort order is used by downstream tools that try to identify reads that observe the same source molecule.  This occurs when the original source molecule has one or more UMIs, and so the multiple observations (i.e read pairs) of the source molecule have the same UMI.  The reads observing the same source molecule can be used to create consensus reads.

For example UMI-tools and [`fgbio GroupReadsByUmi`](http://fulcrumgenomics.github.io/fgbio/tools/latest/GroupReadsByUmi.html) have to sort the input into this order, which is slow for large datasets.  

Sorts reads by:

1. the earlier unclipped 5' coordinate of the read pair
2. the higher unclipped 5' coordinate of the read pair
3. library (from read group)
4. the molecular identifier
5. read name
6. if R1 has the lower coordinates of the pair

In the SAM header, the sort order (SO) is `unsorted`, the group order (GO) is `query`, and sub-sort (SS) is `template-coordinate`.

I'd be open to attempting make a PR (command line option `-c`?), but don't want to invest effort unless there's commitment to review and accept a PR.

**Comment by daviesrob** [comment]
I think this looks OK in principle.  I think a long option would be better than a short one, so we don't make the inconsistencies between samtools short options even worse.  It would also need a way of setting the UMI tag name.

I don't really like using the single string `template-coordinate` for the sub-sort order.  The [SAM specification](https://samtools.github.io/hts-specs/SAMv1.pdf#subsection.1.3) suggests that you can use a colon-separated sequence of descriptions, which would allow for a richer description of exactly how the file was sorted.  Unfortunately it doesn't have anything for "the earlier unclipped 5' coordinate of the read pair" though, so you would have to make up a name for that part.  @jkbonfield may want to comment on this aspect.

**Comment by nh13** [comment]
@daviesrob I am not biggest fan of a long colon list as it gets unwieldy to describe.  The sort order is unsorted, the group order is query, and I'm a fan of keeping it `template-coordinate` for the sub-sort versus `unsorted:earlier-five-prime-template-coordinate:later-five-prime-coordinate:library:molecular-id:query-name:r1-is:lower`.

**Comment by nh13** [comment]
@daviesrob I have a working implementation in #1605.  Let me know how else I can help!

**Comment by nh13** [comment]
Done in #1605 thank y-ou @daviesrob !
