### ISSUE TITLE
samtools depth output incomplete

### ISSUE THREAD

**Issue by RNieuwenhuis** [samtools/samtools#1593]
#### Are you using the latest version of [samtools](https://github.com/samtools/samtools/releases/latest) and [HTSlib](https://github.com/samtools/htslib/releases/latest)? If not, please specify.
(run `samtools --version`)
```
samtools 1.14
Using htslib 1.14
```

 #### Please describe your environment.
- OS (run `uname -sr` on Linux/Mac OS or ` wmic os get Caption, Version` on Windows)
- machine architecture (run `uname -m` on Linux/Mac OS or ` wmic os get OSArchitecture` on Windows)
- compiler (run `gcc --version` or `clang --version`)
```
uname -r
3.10.0-1160.2.1.el7.x86_64

uname -m
x86_64
```

#### Please specify the steps taken to generate the issue, the command you are running and the relevant output.

`samtools depth -aa mybam.bam > genomecov.cov`

Returns incomplete and scrambled output

If I do 

`cut -f 1 genomecov.cov | sort - | uniq -c > position_counts.txt`

I see three important things:

1. Some of the smaller reference sequences are missing (they have probably no mappings, but according to -aa that should not matter)
2. For some reference sequences, the number of positions reported is smaller than the length.
3. Some scrambled names occur like "Super-ScaffolSuper-Scaffold_10" or "SupeSuper-Scaffold_10"

Important observation. The scrambled names are also the names of reference sequences for which issue 2 applies.

The file system to which the output was written is a lustre file system.

**Comment by jkbonfield** [comment]
I tried to reproduce this on ftp://ftp.sra.ebi.ac.uk/vol1/run/ERR323/ERR3239334/NA12878.final.cram (albeit a BAM version of it) and the number of rows per chromosome, and their order, precisely matches the SQ header LN fields.

If you have any more hints on how to reproduce the bug then it would be welcomed. Thanks

**Comment by RNieuwenhuis** [comment]
I reran everything overnight and just checked, now it turned out fine. I guess it must have been a hickup in the filesystem. Anyway, sorry for wasting your time. I appreciate your reply very much.
