### ISSUE TITLE
samtools calmd is pretty slow

### ISSUE THREAD

**Issue by lxwgcool** [samtools/samtools#1595]
I am using "samtools calmd" to add MD tag back to BAM file. The size of original BAM is around 50Gb (whole genome sequence by using pacbio HIFI reads). The issue that I encountered is that the speed of "calmd" is incredibly slow! The jobs have already run 12 hours, and only 600MB BAM with MD tag are generated. In this way, 50GB BAM will take 30days to be finished.

Here is the code I used to add MD tag (very normal):
```
rule addMDTag:
    input:
        rules.pbmm2_alignment.output        
    output: 
        strBAMDir + "/pbmm2/v37/{wcReadsType}/Tmp/rawReads{readsIndex}.MD.bam"               
    params:
        ref = strRef
    threads:
        16
    log:
        strBAMDir + "/pbmm2/v37/{wcReadsType}/Log/rawReads{readsIndex}.MD.log"
    benchmark:
        strBAMDir + "/pbmm2/v37/{wcReadsType}/Benchmark/rawReads{readsIndex}.MD.benchmark.txt"
    shell:
        "samtools calmd -@ {threads} {input} {params.ref} -bAr > {output}"
```

The version of samtools I used is v1.10.

Here is my OS info
- OS: Linux Redhat
![image](https://user-images.githubusercontent.com/11053933/153045096-ef9a929b-20bc-4327-9c9c-9955a39a3090.png)

- machine architecture
  x86_64
- compiler
  gcc (GCC) 7.2.0

BTW, I use 16 cores to run calmd, however, it looks like the samtools is still using 1 core to run it:
```
top - 11:44:53 up 47 days, 20:35,  1 user,  load average: 2.00, 2.01, 2.00
Tasks: 1723 total,   3 running, 1720 sleeping,   0 stopped,   0 zombie
Cpu(s):  2.8%us,  0.3%sy,  0.0%ni, 96.8%id,  0.0%wa,  0.0%hi,  0.0%si,  0.0%st
Mem:  529329180k total, 232414724k used, 296914456k free,    84016k buffers
Swap: 12582908k total,    74884k used, 12508024k free, 227912476k cached

   PID USER      PR  NI  VIRT  RES  SHR S %CPU %MEM    TIME+  COMMAND                                                                                                                                       
 93137 lix33     20   0  954m 151m 2180 R 100.2  0.0 659:04.13 samtools 
```

May I know how to make calmd be much faster? Why the multi-threads does not work? Is there any additional way to add MD tag back to BAM more efficiently?

Thanks so much

**Comment by daviesrob** [comment]
That sounds rather slow.  It may be a scaling problem with the length of your HiFi reads.  We'll try running it on some and see if it's possible to reproduce the problem.

**Comment by lxwgcool** [comment]
Thanks so much. I will ask my colleagues to get some statistic metrics about this raw data and send it to you tomorrow. If I remember correctly, I did not encounter this issue when I use illumina PE reads. 

Thanks again for your help

**Comment by daviesrob** [comment]
It looks like the slowness is caused by the `-r` option, which turns on BAQ realignment.  That's slow in general, and very slow on long-read data.  If you just want the `MD` tags, I would recommend removing the `-A` and `-r` options.

**Comment by lxwgcool** [comment]
Hi,
 
I did try only using -b option to run calmd. However, the speed looks like still pretty slow. 

I started my job at 13:50 pm yesterday, and right now is already nearly 23 hours. For original 50GB BAM, I only generated  1.5G BAM so far. Please check the screenshot below:
![image](https://user-images.githubusercontent.com/11053933/153464353-9579efde-4c6c-4bbb-b669-34e602ccea48.png)

I am using 16 cores to run each job. However, it looks like only one core be used:  
![image](https://user-images.githubusercontent.com/11053933/153464697-20dcbc8f-dd6e-49d4-864f-7402ede838e8.png)

Therefore, I think the problem is that samtools only uses single core to run calmd even you set multiple cores by using -@
![image](https://user-images.githubusercontent.com/11053933/153465745-c10d8f7c-3aec-4bc6-a9d4-5fe1e7d867a0.png)

Could you help me solve this issue? 
Thanks so much for your help

**Comment by lxwgcool** [comment]
Thanks so much for your reply. I did not sort bam before using it as the input of calmd. Thank for tips. I will sort BAM first, and then use calmd to add MD tags. I will let you know how things going on. Thanks again.

**Comment by lxwgcool** [comment]
Just want to update this ticket: after sorted BAM before calmd, the speed was improved significantly. Thank again for the tips. 
I think this tickets could be closed. 

BTW, in order to help others avoid this issue, I do recommend adding this notification (make sure the bam has been sorted before running calmd) in the user manual of calmd.

**Comment by daviesrob** [comment]
Glad to hear the position-sorted file worked better.  I'll leave this open as a reminder that we need to make `calmd` work properly on files that have other orderings.  It shouldn't be too difficult to get that to work.
