### ISSUE TITLE
samtools view filtering report

### ISSUE THREAD

**Issue by lucygarner** [samtools/samtools#1597]
#### Describe the solution you would like.
I am using the -f and -F options with `samtools view` to filter my BAM file. Is there an easy way to output a report of the number of reads from each category that have been filtered out?

Thanks for any suggestions.

**Comment by lucygarner** [comment]
Thank you - I was thinking about counts for the number of reads removed by each filter.

**Comment by daviesrob** [comment]
Hopefully the `flagstats` solution worked well enough for you.  I'll close this for now, but may revisit this if we get more requests for view filtering stats.
