### ISSUE TITLE
The -s flag for view  breaks mate paired reads

### ISSUE THREAD

**Issue by Nheyer** [samtools/samtools#1608]
#### Is your feature request related to a problem? Please specify.
Yes, the -s flag for view  breaks mate paired reads 
#### Describe the solution you would like.
I would like to have the mate be guaranteed (perhaps with a flag to turn of the functionality) to get taken with the read taken for the random sub-set.
Related to this unless the reads have been sorted with the -n flag the reads become improperly paired in the outputs and it dose not warn the user, a simple warning should work here.

I have a draft code for sampling that includes grabbing the mates written in c++ and htslib, but it would need to be refactored to work within samtools and possibly changed so it dose a subset insted of a sub-sample of reads like the current functionality of -s.

**Comment by jmarshall** [comment]
Please provide an example data file which exhibits `-s` breaking pairs.

**Comment by Nheyer** [comment]
It is going to take me a bit to get a file I can share, but from looking a bit further it seems like it might only be happening when one of the two reads is not mapped and/or with suplimental reads.

**Comment by Nheyer** [comment]
I have looked into it more and it seems to have just been my issue not knowing how to use BAM_FMUNMAP within htslib, sorry for the inconvienience.
