### ISSUE TITLE
Errors while converting CRAM to paired fastq files

### ISSUE THREAD

**Issue by prasundutta87** [samtools/samtools#1609]
#### Are you using the latest version of [samtools](https://github.com/samtools/samtools/releases/latest) and [HTSlib](https://github.com/samtools/htslib/releases/latest)? If not, please specify.
(run `samtools --version`)

samtools 1.14
Using htslib 1.14

 #### Please describe your environment.
- OS (run `uname -sr` on Linux/Mac OS or ` wmic os get Caption, Version` on Windows) 
Linux 4.18.0-305.10.2.el8_4.x86_64
- machine architecture (run `uname -m` on Linux/Mac OS or ` wmic os get OSArchitecture` on Windows)
x86_64
- compiler (run `gcc --version` or `clang --version`)
gcc (GCC) 8.5.0 20210514 (Red Hat 8.5.0-4)
#### Please specify the steps taken to generate the issue, the command you are running and the relevant output.
I have a set of CRAM files and I am firing an array job in my HPC cluster to convert them to paired-end fastq files as I need to use the actual reads to complement with long reads sequenced from the same sample. The CRAM files are rather big (>100GB) and they consist of WGS paired-end reads with >=30x depth. I am aware that I need to sort my CRAM files by read name and I have been trying to use samtools sort -n to do that which came up with a lot of errors (similar to the ones described below). I then came across samtools collate and learned that it is faster than samtools sort and perfect for CRAM to paired-end fastq conversion. The command I am using is:

`samtools collate --reference hg38.fa -@ 5 $CRAM -O -u $sample_name|samtools fastq -@ 5 -1 "$sample_name"_R1.fastq.gz -2 "$sample_name"_R2.fastq.gz -0 /dev/null -s /dev/null -n -`

There are a variety of errors I am getting (as its an array job with multiple samples). It seems like the errors are samtools specific, but I am also having a chat with my HPC helpline in case there is some hardware issue. I have also checked the integrity of the CRAM files and they are all okay. I would be grateful if I could be helped with the errors. I have replaced actual sample names with <sample_name> as I am working with real patient data.

```
[E::bgzf_read] Read block operation failed with error 6 after 0 of 4 bytes
[E::bam_hdr_read] Invalid BAM binary header
[E::bgzf_read_block] Failed to read BGZF header at offset 2617
[E::bgzf_read] Read block operation failed with error 7 after 0 of 4 bytes
Error reading '<sample_name>.bam'
[W::bgzf_read_block] EOF marker is absent. The input may be truncated
```

`samtools bam2fq: Error writing to FASTx files.: No such file or directory`

```
/var/spool/slurm/job32231/slurm_script: line 36: 1035678 Bus error               (core dumped) samtools collate --reference /mnt/e1000/home/u027/u027/shared/project/data/reference/hg38.fa -@ 5 $CRAM -O -u $sample_name
     1035679                       (core dumped) | samtools fastq -@ 5 -1 "$sample_name"_R1.fastq.gz -2 "$sample_name"_R2.fastq.gz -0 /dev/null -s /dev/null -n -
```

```
[E::hts_hopen] Failed to open file <sample_name>.bam
[E::hts_open_format] Failed to open file "<sample_name>.bam" : Input/output error
samtools collate: Couldn't open "<sample_name>.bam": Input/output error
[M::bam2fq_mainloop] discarded 0 singletons
[M::bam2fq_mainloop] processed 308625918 reads
```
 
```
/var/spool/slurm/job32216/slurm_script: line 36: 809398 Broken pipe             samtools collate --reference /mnt/e1000/home/u027/u027/shared/project/data/reference/hg38.fa -@ 5 $CRAM -O -u $sample_name
     809399 Bus error               (core dumped) | samtools fastq -@ 5 -1 "$sample_name"_R1.fastq.gz -2 "$sample_name"_R2.fastq.gz -0 /dev/null -s /dev/null -n -
```

Regards,
Prasun

**Comment by jkbonfield** [comment]
BGZF isn't used anywhere in CRAM, so this is suspicious.

What does `htsfile` on your CRAM files say?  I assume they really are CRAM, but it's good to double check.

Also it's disappointing to see the program just Bus Error.  We ought to be catching such problems and reporting more sensibly.  Is the "core dumped" message genuine (sadly often not the case now on modern Linux)?  If so, running `gdb samtools core` and `where` should produce a stack trace helping us to diagnose where the crash is occurring.

**Comment by prasundutta87** [comment]
Hi @jkbonfield ,

Thanks for your reply. What exact information are you looking for from htsfile output? On checking a few lines of the outut file (did not run the whole thing as the output file was becoming very big), I can see this line wihch is very CRAM specific (correct me if I am wrong):

@SQ     SN:chr1 LN:248956422    M5:6aef897c3d6ff0c78aff06ac189178dd     UR:/home/u027/project/data/reference/hg38.fa

For the other question, I am not sure how to run them. On replicating what yiou wrote, I got the result "no stack". Do I need to go to some specific samtools related location and then run thr gdb command? Sorry, I have never used the above mentioned commands ever, hence asking.

Regards,
Prasun

**Comment by daviesrob** [comment]
`collate` writes intermediate BAM files and then reads them back in.  I expect the problem occurred when trying to read one of those files.  One slightly odd thing is that in the invocation above, the intermediates would be called something like `<sample_name>.0001.bam`.  Did you accidentally redact the four-digit number along with the sample name part?

Are you using some sort of shared file system?  On x86_64 Linux, bus errors are pretty unusual, but one cause might be that the system failed to read in some virtual memory pages.  If the file system went away from underneath you while the program was running, it's possible that you might have got similar problems to the ones you encountered.

**Comment by prasundutta87** [comment]
Hello @daviesrob ,

I checked and saw that the four-digit number along with the sample name is intact.

I actually ran the script with just one job and it turned out to be fine. The same sample showed an error when present in an array job. (core dumped error)

Regards,
Prasun

**Comment by jkbonfield** [comment]
It's possibly just running out of temporary file storage then.  That's also consistent with one job being OK, but many jobs causing failures.  How big is your /tmp?

There is an additional prefix command line option used for creating temporary files, so you could specify this somewhere large enough (such as the directory where the final output file will be).

**Comment by prasundutta87** [comment]
Thanks, @jkbonfield. The temp files are being created in the folder where fastq files are being created. I knew that filling /tmp may be an issue with many jobs, hence, I put $sample_name as the prefix. Also, in my script, I am changing directory to where fastqs are being created.

**Comment by jkbonfield** [comment]
Sorry I didn't spot that bit; yes I see.  Yes it'll create temporary files named after the prefix you specify, as $prefix.<0000-9999>.bam.

One other possibility is if you are running multiple jobs on the same file then they could be clobbering each others temporary files.  In theory we check for this, but that may have only been on sort and not collate - I'd have to check that.  It's also hard to be fully robust with such things as race conditions are difficult to spot and not every OS supports atomic file creation.

You can avoid it by using something like the PID (`$$`) in your prefix so separate processes won't clobber.  If you're dispatching across several machines, then add hostname in there too.
