### ISSUE TITLE
CIGAR length too long at position 2114 (270349838H)

### ISSUE THREAD

**Issue by yulong1227** [samtools/samtools#1611]
Hi!

I use samtools to convert the sam format of the fasta file to bam format, the command is 

`samtools view -Sb alignments_hap1.sam > alignments_hap1.bam`

But the following error occurred

![image](https://user-images.githubusercontent.com/99491773/158121932-92881914-4453-43b1-9e99-e7ecf8c97fc7.png)

I'd appreciate any advice!
Best
yulong

**Comment by whitwham** [comment]
@yulong1227.  Do you have an update on this problem?  If not, I will close this issue.

**Comment by whitwham** [comment]
Closing due to lack of response.
