### ISSUE TITLE
Filtering by reference span

### ISSUE THREAD

**Issue by Shians** [samtools/samtools#1618]
#### Is your feature request related to a problem? Please specify.

When aligning long reads with minimap2 to specific regions, there tends to be very high mapping rates with the absolute majority of the read clipped and only a small segment aligned (eg. 500bp of a 30kb read). To identify high-quality mapping to the region, I would like to find reads that span at least n bases of the reference sequence.

#### Describe the solution you would like.

I would like samtools view to have some filtering option for span over the ref sequence, I believe this is roughly the sum of all reference consuming CIGAR values? The current `--min-qlen` is very close to this, but I need filter by reference consumed and not query.

**Comment by jkbonfield** [comment]
There is the filter expression language  which includes an rlen parameter.  Eg:

```
samtools view -e 'rlen>30' in.bam
```

See https://www.htslib.org/doc/samtools.html#FILTER_EXPRESSIONS for more details.

**Comment by Shians** [comment]
That is incredibly helpful, thank you!
