### ISSUE TITLE
samtools depth -s gives incorrect values when running on cram

### ISSUE THREAD

**Issue by ConorMesser** [samtools/samtools#1624]
#### Are you using the latest version of [samtools] and [HTSlib]? If not, please specify.
Running samtools and htslib 1.12

 #### Please describe your environment.
- Linux 5.13.0-1015-gcp  
- x86_64
- gcc (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0   

#### Please specify the steps taken to generate the issue, the command you are running and the relevant output.
Running `samtools depth -r CHR:START-END FILE` on a bam and its cram file return the same results. However, when using the `-s` option (to only count the bases of the first read of an overlapping read pair), running on a cram and bam file return different results.

For example:
```bash
samtools depth -r chr1:935800-935801 NA12878.bam
>chr1    935800  140
>chr1    935801  136

samtools depth -r chr1:935800-935801 NA12878.cram
>chr1    935800  140
>chr1    935801  136

samtools depth -s -r chr1:935800-935801 NA12878.bam
>chr1    935800  120
>chr1    935801  117

samtools depth -s -r chr1:935800-935801 NA12878.cram
>chr1    935800  72
>chr1    935801  70
```
I believe the counts using the cram are being undercounted but I have not verified this explicitly.

**Comment by jkbonfield** [comment]
I can replicate this on a local copy of samtools 1.11, but not in the current version (nor 1.13).  I haven't got a local build of 1.12, but I assume it's got the same issue I can observe in 1.11.

Can you please retest using a newer version on your data?

**Comment by jkbonfield** [comment]
Closing this as we believe it to be fixed already.
