### ISSUE TITLE
extract multiple region read

### ISSUE THREAD

**Issue by natchaphon602** [samtools/samtools#1629]
Are there any scripts to extract mapped read count from every region of multiple BAM file? I can only extract from one region  of one BAM file by using
samtools view -c 'input.bam' 'region:start-end'

**Comment by jkbonfield** [comment]
I was thinking maybe `bedcov` would do this, but it's only base count and not read counts.  It feels like it ought to be trivial to extend this with an extra argument so it can add an additional column.

For now, all I can think of is running `samtools view -c` in a loop.  Sorry.  Unless of course for your purposes base count is a sufficient alternative.
