### ISSUE TITLE
Error in qualities with pair-end overlapping data

### ISSUE THREAD

**Issue by svarona** [samtools/samtools#1631]
#### Are you using the latest version of [samtools](https://github.com/samtools/samtools/releases/latest) and [HTSlib]
samtools: '1.14'

 #### Please describe your environment.
- OS: Linux 4.18.0-305.19.1.el8_4.x86_64
- machine architecture: x86_64
- compiler: gcc (GCC) 8.5.0 20210514 (Red Hat 8.5.0-4)

#### Please specify the steps taken to generate the issue, the command you are running and the relevant output.

# Describe the bug

We have observed that when using pair-end reads, if R1 and R2 from same pair overlap in a position, quality assignment in that position for R2 is decreased to minimum quality value in phred33 (`!`), while R1 is increased to maximum quality in phred64 `i`, as you can see in the image below:

![issuempileup_img2](https://user-images.githubusercontent.com/23449453/152827056-db4f6f86-929b-4db5-aaa1-ee5d5d3d0be2.png)
*Image 1. Mpileup file.*

This behaviour is explained by [#1146 Valeriuo comment](https://github.com/samtools/samtools/issues/1146#issuecomment-559756496).

This creates problems in downstream analyses because we are mixing phred33 and phred64 qualities. In our case we are seeing failures when calling for variants with ```ivar variants``` for SARS-CoV-2 genomes analysis, because ivar is not considering phred64 nucleotides, decreasing position's depth.

# To reproduce

```
# Enable read-pair overlap detection
samtools mpileup \\
        -a \\
        --count-orphans \\
        --no-BAQ \\
        --max-depth  \\
        --fasta-ref fasta \\
        --min-BQ $params.min_base_qual \\
        bam | ivar variants -q 0.25 -t 0.75 -m 20 -r fasta features -p sample
```

# Temporal workaround

```
# Disable read-pair overlap detection
samtools mpileup \\
        -a \\
        --count-orphans \\
        --no-BAQ \\
        --ignore-overlaps \\
        --max-depth  \\
        --fasta-ref fasta \\
        --min-BQ $params.min_base_qual \\
        bam | ivar variants -q 0.25 -t 0.75 -m 20 -r fasta features -p sample
```
# Expected behavior

We suggest that mpileup should assign the highest or lowest quality in the same phred encoding.

This issue may be related to [#97](https://github.com/andersen-lab/ivar/issues/97), [#100](https://github.com/andersen-lab/ivar/issues/100), [#104](https://github.com/andersen-lab/ivar/issues/104), [#113](https://github.com/andersen-lab/ivar/issues/113).

**Comment by jkbonfield** [comment]
You're seeing this problem because Phred64 is not supported.  It may appear that way, but it's simply interpreted as an overly confidence Phred33 quality string.

Practically speaking there is no actual way of distinguishing the two other than gathering lots of data and doing statistical analysis on it.  This is one of the reasons why it was a tragically bad invention, and presumably why Illumina rapidly dropped it again.  I would recommend you don't ever use Phred64 and life will become simpler (for more than just Samtools).

**Comment by svarona** [comment]
Ok! you are right! I've just checked and that was the issue (we also have seen this a while ago and we are just reporting), the problem is just as you say when the two overlapping bases match the phred scores are summed.

But the problem is we'll expect that if the sum of the phred scores passes the maximum phred33 score, 40 (I uppercase in asciii), the score should be 40, not more than 40 like in this case which would be 73 in "phred33" (i lowercase in asciii), which gives us a pileup that "seems" to have mixed phred33 and phred64. Generating qualities not in the phred33 score range looks artefactual and could be misleading for downstream tools.

We've seen this because when we used ivar variants without the `--ignore-overlaps` flag in amplicon data (when a lot of overlapping is going on). We see a bunch of variants ignored because all the bases with this weird phred scores are being ignored as they are not being detected as "high quality" phred33 score but as "no quality" or something weird at all.

**Comment by jkbonfield** [comment]
This sounds more like an ivar bug then and should be reported there.  There is no official upper-bound on phred scores, other than to printable ascii (so 93 = `~`).  Indeed PacBio CCS routinely reports values that high.  For much the same reason infact - the data has been independently observed several times.

We don't have an option to limit the maximum quality, but it could be done with a relatively simple script as the quality values all reside in their own column so something like perl's `tr` command would easily be used to set an upper-bound.

**Comment by svarona** [comment]
Okay! Thank you very much for your help and the explanation! We will move this issue to iVar then!
