### ISSUE TITLE
plot-bamstats

### ISSUE THREAD

**Issue by xbx-xbx-1208** [samtools/samtools#1632]
#### Are you using the latest version of [samtools](https://github.com/samtools/samtools/releases/latest) and [HTSlib](https://github.com/samtools/htslib/releases/latest)? If not, please specify.
(run `samtools --version`)
samtools 1.9
Using htslib 1.9

 #### Please describe your environment.
- OS (run `uname -sr` on Linux/Mac OS or ` wmic os get Caption, Version` on Windows)
- machine architecture (run `uname -m` on Linux/Mac OS or ` wmic os get OSArchitecture` on Windows)
- compiler (run `gcc --version` or `clang --version`)
Linux 3.10.0-1160.42.2.el7.x86_64
#### Please specify the steps taken to generate the issue, the command you are running and the relevant output.
plot-bamstats -p ./test sorted.bam.stats 

set terminal png size 600,400 truecolor
             ^
"./test-quals.gp", line 2: unknown or ambiguous terminal type; type just 'set terminal' for a list

The command exited with non-zero status 256:
	gnuplot ./test-quals.gp

 at /home/line/local/app/miniconda3/bin/plot-bamstats line 51.
	main::error("The command exited with non-zero status 256:\x{a}\x{9}gnuplot ./test-"...) called at /home/line/local/app/miniconda3/bin/plot-bamstats line 317
	main::plot("./test-quals.gp") called at /home/line/local/app/miniconda3/bin/plot-bamstats line 653
	main::plot_qualities(HASH(0x561210313648)) called at /home/line/local/app/miniconda3/bin/plot-bamstats line 33

**Comment by whitwham** [comment]
No update from @xbx-xbx-1208 so I am closing the issue.
