### ISSUE TITLE
View Mapping Quality by genomic coordinate

### ISSUE THREAD

**Issue by elcortegano** [samtools/samtools#1634]
I wonder if its possible to query mapping qualities (MQ) as displayed by `samtools view`, but rather than having one value per read and line, having mean MQs sorted by genomic coordinate in the output,

Does samtools provide a utility to perform such a query? or do you have any recommendation to do so? thanks!

**Comment by daviesrob** [comment]
I don't think there's a way to get samtools to do this, but it should be easy enough yourself by extracting [columns 3, 4 and 5](https://samtools.github.io/hts-specs/SAMv1.pdf#subsection.1.4) from the SAM alignment records and working out the average in your favourite scripting language.

If you're reading a CRAM file, you can also speed things up a bit by [telling samtools](https://www.htslib.org/doc/samtools.html#GLOBAL_COMMAND_OPTIONS) that you're only interested in these columns using `samtools view --input-fmt-option=required_fields=0x1c in.cram`.  It currently only works in CRAM files though, for BAM you'll just get the normal output.

**Comment by elcortegano** [comment]
That gives MQ already in a very convenient way, and works actually quite well. Thanks!
