### ISSUE TITLE
samtools: error while loading shared libraries: libcrypto.so.1.0.0: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by adesalegn** [samtools/samtools#1641]
Hi all here,

I just could not able to use samtools for unknow reason. 
Does any one has a solution for the error(indicated in the title) I am having ?
whenever I type the following ,
```
samtools
samtools view --help
```
 It prints, samtools: error while loading shared libraries: libcrypto.so.1.0.0: cannot open shared object file: No such file or directory.

Thanks!!

**Comment by whitwham** [comment]
It would help if you told us which OS you are running on (presumably some form of Linux) and how you installed samtools in the first place.

**Comment by whitwham** [comment]
No update from @adesalegn so I am closing the issue.
