### ISSUE TITLE
Working --read-coords REGEX option to markdup?

### ISSUE THREAD

**Issue by RandyHarr** [samtools/samtools#1642]
Firstly, I stand up and applaud the addition of the --read-coords option to the samtools markdup command.  BGI/MGI/DNB sequencer QNAMES literally "hang" (infinite stall) samtools markdup nearly 50% of the time.  So we have to avoid duplicate marking on those sequencer results; which are the majority of files we process.

I have tried every conceivable form to get the REGEX matching for BGI QNAMEs with no success.  I either get the 
   "[markdup] warning: can not decipher X coordinate in E100003218L1C034R0294035623 ." or 
   "[markdup] warning: cannot decipher read name E100003218L1C034R0294035623 for optical duplicate marking." message. 
(side note: notice two forms of "cannot" and "can not" in the warning messages.)

As you can see in the above, BGI/MGI/DNB sequencer names have much the same content as Illumina but just without colon separators.  I can easily match and manipulate the QNAMEs with the regex processor in Python. And have templates for the many varieties of QNAMES found.  (See http://bit.ly/2TfoAP2 if you really care.)  It does become a little tougher as the length of the numerical fields can vary.  But the placement of the L, C and R are usually enough to figure out the information. 

I drop the template (t) processing from this example for simplicity.  The first warning shown above comes from using command line parameters of: 
  --read-coords '(C[0-9]{3})(R[0-9]{3})' --coords-order xy (and many other variations I have tried).  The second warning from using the BASIC POSIX REGEX form of parameters: 
  --read-coords '(C[0-9]\{3\})(R[0-9]\{3\})' --coords-order xy 
As part of my trying everything, even tried:
  --read-coords '(C034)(R029)' --coords-order xy
which yields X coord warnings (for where it matches exactly as written) and then "cannot decipher read name" warnings where it does not. Cannot get much simpler than that for a REGEX.

Your example uses "\w" which is PERL REGEX and not POSIX.  Otherwise, I would use "\d" instead of [0-9] but that generates the second warning message if used. I tend to abhor [[:digit:]] as it takes me back to the days of Ada.

As your examples do not have backslashes, I presume you are using EXTENDED REGULAR EXPRESSIONS in POSIX as opposed to BASIC. Would be useful to clarify. I tried both ways and think you cannot handle the backslashes of BASIC. Maybe see https://en.wikibooks.org/wiki/Regular_Expressions/POSIX_Basic_Regular_Expressions

Tried digging into the code changes but am not familiar with the libraries you are linking to and could not get very far.  Would love to get this resolved and working so I can turn the optical duplicate marking back on for BGI/MGI sequencer reads (which over 50% of the sequencer reads we see these days are coming from ...).

Thank you for the consideration.

_Originally posted by @RandyHarr in https://github.com/samtools/samtools/pull/1558#issuecomment-1110075545_

**Comment by whitwham** [comment]
Yes, there is a bug.  Using your example `E100003218L1C034R0294035623` with `C([0-9]{3})R([0-9]{3})` gives **x = 34** and **y = 294035623**.  The handler for the regex results is not using the endpoint when it decodes the numbers.  So when the numbers are separated by a non-number it works fine, but in this case the numbers are all taken together.

Your original regex would not work because you were including **C** and **R** in the coordinates which would not be treated as a number.

**Comment by whitwham** [comment]
> Firstly, I stand up and applaud the addition of the --read-coords option to the samtools markdup command. BGI/MGI/DNB sequencer QNAMES literally "hang" (infinite stall) samtools markdup nearly 50% of the time. So we have to avoid duplicate marking on those sequencer results; which are the majority of files we process.

It is troubling that markdup would just hang.  For optical duplicate marking it should just throw up a lot of warnings for a QNAME format it does not recognise.  Do you know of any publicly available BGI/MGI/DNB data that I could test on?

> As you can see in the above, BGI/MGI/DNB sequencer names have much the same content as Illumina but just without colon separators.

Ah yes, because adding separators would make things too easy.

> I can easily match and manipulate the QNAMEs with the regex processor in Python. And have templates for the many varieties of QNAMES found. (See http://bit.ly/2TfoAP2 if you really care.) It does become a little tougher as the length of the numerical fields can vary. But the placement of the L, C and R are usually enough to figure out the information.

Thanks for the document link, that is very helpful.

> Your example uses "\w" which is PERL REGEX and not POSIX. Otherwise, I would use "\d" instead of [0-9] but that generates the second warning message if used. I tend to abhor [[:digit:]] as it takes me back to the days of Ada.
> 
> As your examples do not have backslashes, I presume you are using EXTENDED REGULAR EXPRESSIONS in POSIX as opposed to BASIC. Would be useful to clarify. I tried both ways and think you cannot handle the backslashes of BASIC. Maybe see https://en.wikibooks.org/wiki/Regular_Expressions/POSIX_Basic_Regular_Expressions

The code allows extended regular expressions.  Unfortunately, as I recently discovered, this depends on the underlying libraries.  So while the extended expressions work on Linux and Windows, on MacOS they do not.

Thank you for your bug report.

**Comment by whitwham** [comment]
> By "extended regular expressions", do you mean POSIX ERE without the baclslash? Or Perl-style (non POSIC BRE or ERE) with \d, \w and the like?

By the documentation [here](https://www.gnu.org/software/libc/manual/html_node/Flags-for-POSIX-Regexps.html) it should be POSIX ERE, but (on Ubuntu at least) it seems to be quite happy to accept some Perl-style additions.  What exactly the library accepts I don't know.

**Comment by whitwham** [comment]
> Firstly, I stand up and applaud the addition of the --read-coords option to the samtools markdup command. BGI/MGI/DNB sequencer QNAMES literally "hang" (infinite stall) samtools markdup nearly 50% of the time. So 
we have to avoid duplicate marking on those sequencer results; which are the majority of files we process.

This looks like a bug that was introduces in 1.12 and fixed in 1.15.  It was never reported externally and something we found when testing something else.
