### ISSUE TITLE
bam header 

### ISSUE THREAD

**Issue by adesalegn** [samtools/samtools#1648]
hi all, 
reading the bam file using the code below `samtools view -H 388.bam | head` showed me this  and don't know what means the **@HD    VN:1.0  SO:unknown**
  
```
@HD     VN:1.0  SO:unknown
@SQ     SN:1    LN:248956422
@SQ     SN:10   LN:133797422
@SQ     SN:11   LN:135086622
@SQ     SN:12   LN:133275309
@SQ     SN:13   LN:114364328
@SQ     SN:14   LN:107043718
@SQ     SN:15   LN:101991189
@SQ     SN:16   LN:90338345
@SQ     SN:17   LN:83257441
```
Thank you!!

**Comment by daviesrob** [comment]
This is explained in [the SAM speification](https://samtools.github.io/hts-specs/SAMv1.pdf#subsection.1.3).

`@HD` lists the format version number (1.0 for this file) and sort order (unknown).
