### ISSUE TITLE
tabix error -conda installation

### ISSUE THREAD

**Issue by desmodus1984** [samtools/samtools#1655]
#### Are you using the latest version of [samtools](https://github.com/samtools/samtools/releases/latest) and [HTSlib](https://github.com/samtools/htslib/releases/latest)? If not, please specify.
(run `samtools --version`)
samtools 1.15.1

 #### Please describe your environment.
- OS (run `uname -sr` on Linux/Mac OS or ` wmic os get Caption, Version` on Windows)
- Linux 3.10.0-1160.59.1.el7.x86_64
- machine architecture (run `uname -m` on Linux/Mac OS or ` wmic os get OSArchitecture` on Windows)
x86_64
- compiler (run `gcc --version` or `clang --version`)
gcc (GCC) 8.4.0

#### Please specify the steps taken to generate the issue, the command you are running and the relevant output.
I am trying to do some genomic analysis I have the gvcf zipped files and then I installed samtools in conda and then when I tried indexing them:
samtools tabix -p vcf W3.vcf.gz
I got the error
[main] unrecognized command 'tabix'

A year ago I had no problem to run tabix and no, it seems to not exist anymore.

**Comment by whitwham** [comment]
That because `tabix` is a stand alone program that comes with htslib not a samtools subcommand.  Try:

`tabix -p vcf W3.vcf.g`
