### ISSUE TITLE
samtools view -t gives "fail to read the header"

### ISSUE THREAD

**Issue by mdehoon** [samtools/samtools#1658]
samtools 1.15.1
Using htslib 1.15.1

Darwin 20.6.0
x86_64
Apple clang version 13.0.0 (clang-1300.0.29.30)
Target: x86_64-apple-darwin20.6.0
Thread model: posix

Create an empty file:

`touch empty.sam`

Create a file `chrom.sizes` with the following text:
```
chr1	248956422
chr2	242193529
chr3	198295559
chr4	190214555
```

Now run samtools to create the header:
```
samtools view -H -t chrom.sizes empty.sam
```

This gives
```
[main_samview] fail to read the header from "empty.sam".
```
and no other output. With samtools version 1.9, this would output
```
@SQ	SN:chr1	LN:248956422
@SQ	SN:chr2	LN:242193529
@SQ	SN:chr3	LN:198295559
@SQ	SN:chr4	LN:190214555
```
which was useful to create a SAM header from a `chrom.sizes` file.

**Comment by daviesrob** [comment]
That's because `samtools` now rejects completely empty files, on the assumption that they were made by an upstream process that failed rather than deliberately.

You can get the above trick to work by making your initial file a bit less minimal, for example:
```
printf '@HD\tVN:1.6\n' > start.sam
samtools view -H -t chrom.sizes > start.sam
@HD	VN:1.6
@SQ	SN:chr1	LN:248956422
@SQ	SN:chr2	LN:242193529
@SQ	SN:chr3	LN:198295559
@SQ	SN:chr4	LN:190214555
@PG	ID:samtools	PN:samtools	VN:1.15.1-14-g1e369b6	CL:samtools view -H -t chrom.sizes start.sam
```

**Comment by yaximik** [comment]
Different versions of samtools still produce different output for the same file.

$ less gor-mt2rCRS.sam
@HD VN1.0 SO:unsorted
@SQ     SN:1    LN:30427671
@SQ     SN:2    LN:19698289
@SQ     SN:3    LN:23459830
@SQ     SN:4    LN:18585056
@SQ     SN:5    LN:26975502
@SQ     SN:M    LN:366924
@SQ     SN:C    LN:154478
@PG ID:nucmer PN:nucmer VN:4.0 CL:"nucmer --maxmatch --threads=4 --sam-short=./gor-hum.sam gorilla.fasta rCRS.fasta"

samtools v <=1.9:
htslib v <=1.9
$ samtools view -H gor-mt2rCRS.sam
@HD VN1.0 SO:unsorted
@SQ	SN:1	LN:30427671
@SQ	SN:2	LN:19698289
@SQ	SN:3	LN:23459830
@SQ	SN:4	LN:18585056
@SQ	SN:5	LN:26975502
@SQ	SN:M	LN:366924
@SQ	SN:C	LN:154478
@PG ID:nucmer PN:nucmer VN:4.0 CL:"nucmer --maxmatch --threads=4 --sam-short=./gor-hum.sam gorilla.fasta rCRS.fasta"

samtools v 1.10 - 1.20
htslib v 1.10 - 1.20

$ samtools view -H gor-mt2rCRS.sam
[main_samview] fail to read the header from "gor-mt2rCRS.sam"

What may be the issue?

**Comment by jkbonfield** [comment]
` @hd VN1.0 SO:unsorted` is malformed.  It should be `VN:1.0`  (1.0 is way old too, but should still be fine.)

What you're seeing is improved validation in newer versions of samtools.

Also, please don't just add comments to old closed issues.  It's best to create new ones for new problems.  Thanks
