### ISSUE TITLE
CIGAR length too long Error

### ISSUE THREAD

**Issue by xbarvazx** [samtools/samtools#1667]
Hi,
I am getting this error after trying to sort a sam file created by minimap2. This is an alignment of to large chromosome scale assemblies.
I thought the problem with CIGAR is only while converting to bam files and that it was solved in sort by converting to cram?

[E::parse_cigar] CIGAR length too long at position 3813 (324596605S)
[W::sam_read1_sam] Parse error at line 2273
samtools sort: truncated file. Aborting

Best,
Raz

**Comment by daviesrob** [comment]
The error should really read "CIGAR **operation** length to long".  Internally HTSlib has a limit of 268435456 bases for any single CIGAR operation, and your soft-clip is quite a bit bigger than that.

I would guess that the alignment record is for some sort of consensus read, and didn't come directly from a sequencing instrument (it would be a record-breaker if it did).  It also looks like it didn't align too well given the size of the soft-clip.  As alignment records this long are likely to cause problems, it might be best to break the single consensus read into a sequence of (possibly overlapping) shorter ones.  It's a little less convenient than having a single read, but it means you're less likely to hit limits like the one above.

**Comment by xbarvazx** [comment]
@daviesrob 
Thanks for the answer. Yes these are two whole genomes aligned so its basically chromosome to chromosome. Overall the alignments are usually good. 
What would be the advantage of breaking the sequence into overlapping short sequences instead of just splitting it into 1Mb sequences? And also what would be a good way to get overlapping sequences?

Best,
Raz

**Comment by daviesrob** [comment]
Hopefully you've managed to work around this by splitting up your reference.  Please reopen if not.

**Comment by LandiMi2** [comment]
@daviesrob I have a similar error message. Could it be because one genome has lots of gaps? I am doing a whole genome alignment of two genomes. One version has 2.3 MB of gaps, and the other 3Kb gaps.

**Comment by aafshinfard** [comment]
I am having the same issue, and I would really appreciate a solution as splitting to smaller pieces will ruin the analyses.

more info:
I am aligning a super contiguous assembly to the T2T assembly of CHM13 (human) to visualize the contiguity of the assembly and to compare the agreement between the two assemblies. If I break to smaller pieces I will have smaller chunks in my visualization...

**Comment by aafshinfard** [comment]
@daviesrob I am experiencing the same issue, and splitting the query to smaller chunks would not help (as I am aligning to visualize the alignment between the two genomes). I'd really appreciate an update on if this is on the plate for upcoming versions or not. Thank you
