### ISSUE TITLE
issue with cram to fastq conversion

### ISSUE THREAD

**Issue by bzmby** [samtools/samtools#1671]
I have a CRAM file and trying to convert it to fastq files. to do so I used this command:

**samtools fastq -@ 8 -1 file_1.fq.gz -2 file_2.fq.gz  PMCRZ791XNL_RNA-Seq.cram**

but I got the following error, do you know how to fix the issue? :

> [E::cram_get_ref] Failed to populate reference for id 0
> [E::cram_get_ref] Failed to populate reference for id 0
> [E::cram_get_ref] Failed to populate reference for id 0
> [E::cram_get_ref] Failed to populate reference for id 0
> [E::cram_get_ref] Failed to populate reference for id 0
> [E::cram_get_ref] Failed to populate reference for id 0
> [E::cram_get_ref] Failed to populate reference for id 0
> [E::cram_get_ref] Failed to populate reference for id 0
> [E::cram_decode_slice] Unable to fetch reference #0 504062..517969
> 
> [E::cram_decode_slice] Unable to fetch reference #0 166665..199255
> 
> [E::cram_decode_slice] Unable to fetch reference #0 139089..157364
> 
> [E::cram_decode_slice] Unable to fetch reference #0 126416..139238
> 
> [E::cram_decode_slice] Unable to fetch reference #0 490971..504209
> 
> [E::cram_decode_slice] Unable to fetch reference #0 11570..126563
> 
> [E::cram_next_slice] Slice decode failure
> [bam2fq_mainloop] Failed to read bam record.
> [bam2fq_mainloop] Error writing to FASTx files.: Resource temporarily unavailable
> [M::bam2fq_mainloop] discarded 0 singletons
> [M::bam2fq_mainloop] processed 0 reads
> [E::cram_decode_slice] Unable to fetch reference #0 157216..166809
> 
> [E::cram_decode_slice] Unable to fetch reference #0 199108..491119
> 
> [E::cram_get_ref] Failed to populate reference for id 0
> [E::cram_get_ref] Failed to populate reference for id 0
> [E::cram_get_ref] Failed to populate reference for id 0
> [E::cram_get_ref] Failed to populate reference for id 0
> [E::cram_decode_slice] Unable to fetch reference #0 629814..630066
> 
> [E::cram_get_ref] Failed to populate reference for id 0
> [E::cram_get_ref] Failed to populate reference for id 0
> [E::cram_get_ref] Failed to populate reference for id 0
> [E::cram_decode_slice] Unable to fetch reference #0 629919..632059
> 
> [E::cram_get_ref] Failed to populate reference for id 0
> [E::cram_decode_slice] Unable to fetch reference #0 532348..629817
> 
> [E::cram_decode_slice] Unable to fetch reference #0 629721..629962
> 
> [E::cram_decode_slice] Unable to fetch reference #0 517821..532496
> 
> [E::cram_get_ref] Failed to populate reference for id 0
> [E::cram_decode_slice] Unable to fetch reference #0 629666..629870
> 
> [E::cram_decode_slice] Unable to fetch reference #0 633898..726384
> 
> [E::cram_get_ref] Failed to populate reference for id 0
> [E::cram_decode_slice] Unable to fetch reference #0 631910..634047
> 
> [E::cram_get_ref] Failed to populate reference for id 0
> [E::cram_get_ref] Failed to populate reference for id 0
> [E::cram_get_ref] Failed to populate reference for id 0
> [E::cram_decode_slice] Unable to fetch reference #0 726235..742090
> 
> [E::cram_get_ref] Failed to populate reference for id 0
> [E::cram_get_ref] Failed to populate reference for id 0
> [E::cram_decode_slice] Unable to fetch reference #0 741942..764931
> 
> [E::cram_get_ref] Failed to populate reference for id 0
> [E::cram_decode_slice] Unable to fetch reference #0 852671..1249580
> 
> [E::cram_decode_slice] Unable to fetch reference #0 1567210..1662250
> [E::cram_decode_slice] Unable to fetch reference #0 1374213..1402202
> 
> [E::cram_decode_slice] Unable to fetch reference #0 1402054..1567358
> 
> [E::cram_decode_slice] Unable to fetch reference #0 764782..852766
> 
> [E::cram_decode_slice] Unable to fetch reference #0 1249499..1374361

**Comment by whitwham** [comment]
> I have a CRAM file and trying to convert it to bam files. to do so I used this command:

Did you mean **convert to fastq files**?  Otherwise I am very confused.

**Comment by bzmby** [comment]
@[whitwham](https://github.com/whitwham) 
sorry, yes (corrected) I want to convert cram file to fastq file,
