### ISSUE TITLE
Is there an option to output only the readnames from a BAM (fast and native, without piping to a filter)

### ISSUE THREAD

**Issue by ms-gx** [samtools/samtools#1672]
I am looking for a way to make `samtools` to output only the readnames. I do not want to filter the readnames via `cut` or `awk` or a similar approach later, since this is to slow for my application.

It would be good to have `samtools` natively only reporting the readnames.

Is this possible? Or is there a another tool you would recommend that does this efficiently?

My approach is the following (awk and gnu parallel not helping me much to speed up):
`samtools view -@ 10 -F 0x100 file.bam | cut -f 1 | pigz > out.gz`

`cut` is currently the bottleneck in the command above.

**Comment by jkbonfield** [comment]
There's nothing to do this right now that I can think of.  Gawk was the fastest I could find (surprisingly beating mawk in this case, and beating cut for me even).  Perl was tragically slow, on par with a sed statement.  This was just outputting to /dev/null.  I'm surprised pigz isn't the bottleneck above (and personally I'd recommend a libdeflate compiled bgzip instead of pigz as it's likely far faster, if we can avoid the other bottleneck obviously).  I tried adding `mbuffer` too, which can sometimes rescue threading throughput for tools that only read small quantities at a time, but it didn't help.

The timings are quite suprising to me:

```
# SAM only
@ seq4c[/tmp]; time samtools view -@ 10 -F 0x100 ~/scratch/data/novaseq.10m.bam  > /dev/null
real	0m3.193s
user	0m25.061s
sys 	0m0.994s

# SAM into awk
@ seq4c[/tmp]; time samtools view -@ 10 -F 0x100 ~/scratch/data/novaseq.10m.bam | awk '{print $1}' > /dev/null
real	0m7.254s
user	0m30.909s
sys 	0m5.171s

# uncompressed BAM only; slower than SAM in wall-clock time
@ seq4c[/tmp]; time samtools view -u -@ 10 -F 0x100 ~/scratch/data/novaseq.10m.bam > /dev/null
real	0m3.691s
user	0m11.474s
sys 	0m1.249s

```

Sadly GNU parallel is a perl script so has its own overhead irrespective of threading the output command.  I think it was designed for CPU intensive jobs and not maximum throughput of efficient tools.

About the only solution I can think of is writing your own multi-threaded cut-equivalent!  Messy.

The alternative would be hacking the `sam_format1_append` function in htslib and seeing what speed it can achieve.  It's possible if this is a big win that we could consider some `--output-fmt-option` extention that lists the SAM columns to emit.

**Comment by jkbonfield** [comment]
Note a really dumb tool to just print the first word is much faster than cut.

```
@ seq4c[/tmp]; cat _1.c
#include <stdio.h>

int main(int argc, char **argv) {
    char line[8192];
    while (fgets(line, 8192, stdin) != NULL) {
	for (int i = 0; i < 8192; i++)
	    if (line[i] == '\t') {
		line[i] = '\n';
		fwrite(line, 1, i+1, stdout);
		break;
	    }
    }
    return 0;
}
@ seq4c[/tmp]; time samtools view -@ 10 -F 0x100 ~/scratch/data/novaseq.10m.bam | ./a.out > /dev/null

real	0m4.351s
user	0m27.035s
sys	0m5.775s
```

It's still 100% CPU, but with some better int64 tab detection (as used [here](https://github.com/jkbonfield/io_lib/blob/master/io_lib/bam.c#L1142-L1151)) it could probably be faster still.

**Comment by jmarshall** [comment]
If you want speed whatever the cost, you want to write C code. It'd also be about a five line program (using the HTSlib API) to read the BAM file and write out just the readnames already compressed, with both reading and writing multithreaded.

**Comment by jkbonfield** [comment]
Thanks @daviesrob.  That's a very good point regarding wanting examples for our HOW-TO guides.

Just for completeness, here's the speed when measured on the same machine and data set I reported above:

```
@ seq4c[/tmp]; time ./a.out -@10 ~/scratch/data/novaseq.10m.bam - > /dev/null
real	0m1.352s
user	0m7.233s
sys 	0m0.628s
```

So 8-9x faster than using cut.  It doesn't have the `-F 0x100`  filtering, but on this particular data there are no secondary reads so it's mainly an irrelevance for speed.

**Comment by ms-gx** [comment]
Works like a charm. Thank you so much!

But somehow it is limited to 10 threads -- even if I set parameter `@` to 60. Is this intentional?

**Comment by ms-gx** [comment]
And if you provide me with a little hint on how to do the -F 0x100 filtering I can try to implement this -- because I need this for my application.

You guys are awesome, thanks much.

**Comment by jkbonfield** [comment]
That'll be the call here:

```
    p.pool = hts_tpool_init(8);
```

It should be `nthreads` instead of 8.

**Comment by whitwham** [comment]
> And if you provide me with a little hint on how to do the -F 0x100 filtering I can try to implement this -- because I need this for my application.

Something like (if I have my flags correct):

if (rec->core.flag & BAM_FSECONDARY) { // then do something}

**Comment by ms-gx** [comment]
Before I close this issue -- What does `hts_set_opt` do? Or different: what changes when I set from `1` to `3` in your change above?

Sorry, tried to find this but was not successful.

**Comment by daviesrob** [comment]
It's an optimisation for cram files.  It tells the cram decoder to only extract the `qname` (1) and `flag` (2) fields, which bitwise-or together to make 3.  That makes it a lot faster as it can avoid unnecessary work.  See the samtools manual page [global command options](https://www.htslib.org/doc/samtools.html#GLOBAL_COMMAND_OPTIONS) section, "required_fields".

**Comment by ms-gx** [comment]
Oh, I understand -- thanks!

**Comment by ms-gx** [comment]
So if I do not use CRAM files I do not have to care about the `CRAM_OPT_REQUIRED_FIELDS` flags in principle?

**Comment by jkbonfield** [comment]
No, but it's harmless and doesn't negatively impact when reading SAM or BAM.  It's an optimisation we tend to add so tools can run efficiently when the file formats permit it.  I think in theory we could use this for the htsget protocol too using the `fields=` filter, as the back-end storage used in htsget could be anything including a number of columnar implementations out there.  I don't know if our htsget implementation supports this though.
