### ISSUE TITLE
How to apply tag division?

### ISSUE THREAD

**Issue by Johnsonzcode** [samtools/samtools#1677]
#### Are you using the latest version of [samtools](https://github.com/samtools/samtools/releases/latest) and [HTSlib](https://github.com/samtools/htslib/releases/latest)? If not, please specify.
(run `samtools --version`)
samtools 1.12
Using htslib 1.12
Copyright (C) 2021 Genome Research Ltd.

Samtools compilation details:
    Features:       build=configure curses=yes
    CC:             /opt/conda/conda-bld/samtools_1616892191687/_build_env/bin/x86_64-conda-linux-gnu-cc
    CPPFLAGS:       -DNDEBUG -D_FORTIFY_SOURCE=2 -O2 -isystem /storage-01/poultrylab1/yin/software/anaconda3/envs/asm_practise/include
    CFLAGS:         -Wall -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -isystem /storage-01/poultrylab1/yin/software/anaconda3/envs/asm_practise/include -fdebug-prefix-map=/opt/conda/conda-bld/samtools_1616892191687/work=/usr/local/src/conda/samtools-1.12 -fdebug-prefix-map=/storage-01/poultrylab1/yin/software/anaconda3/envs/asm_practise=/usr/local/src/conda-prefix
    LDFLAGS:        -Wl,-O2 -Wl,--sort-common -Wl,--as-needed -Wl,-z,relro -Wl,-z,now -Wl,--disable-new-dtags -Wl,--gc-sections -Wl,-rpath,/storage-01/poultrylab1/yin/software/anaconda3/envs/asm_practise/lib -Wl,-rpath-link,/storage-01/poultrylab1/yin/software/anaconda3/envs/asm_practise/lib -L/storage-01/poultrylab1/yin/software/anaconda3/envs/asm_practise/lib
    HTSDIR:
    LIBS:
    CURSES_LIB:     -ltinfow -lncursesw

HTSlib compilation details:
    Features:       build=configure plugins=yes, plugin-path=/storage-01/poultrylab1/yin/software/anaconda3/envs/asm_practise/libexec/htslib libcurl=yes S3=yes GCS=yes libdeflate=yes lzma=yes bzip2=yes htscodecs=1.0
    CC:             /opt/conda/conda-bld/htslib_1616818599374/_build_env/bin/x86_64-conda-linux-gnu-cc
    CPPFLAGS:       -DNDEBUG -D_FORTIFY_SOURCE=2 -O2 -isystem /storage-01/poultrylab1/yin/software/anaconda3/envs/asm_practise/include
    CFLAGS:         -Wall -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -isystem /storage-01/poultrylab1/yin/software/anaconda3/envs/asm_practise/include -fdebug-prefix-map=/opt/conda/conda-bld/htslib_1616818599374/work=/usr/local/src/conda/htslib-1.12 -fdebug-prefix-map=/storage-01/poultrylab1/yin/software/anaconda3/envs/asm_practise=/usr/local/src/conda-prefix -fvisibility=hidden
    LDFLAGS:        -Wl,-O2 -Wl,--sort-common -Wl,--as-needed -Wl,-z,relro -Wl,-z,now -Wl,--disable-new-dtags -Wl,--gc-sections -Wl,-rpath,/storage-01/poultrylab1/yin/software/anaconda3/envs/asm_practise/lib -Wl,-rpath-link,/storage-01/poultrylab1/yin/software/anaconda3/envs/asm_practise/lib -L/storage-01/poultrylab1/yin/software/anaconda3/envs/asm_practise/lib -fvisibility=hidden -rdynamic

HTSlib URL scheme handlers present:
    built-in:    preload, data, file
    S3 Multipart Upload:         s3w, s3w+https, s3w+http
    Amazon S3:   s3+https, s3+http, s3
    libcurl:     imaps, pop3, gophers, http, smb, gopher, sftp, ftps, imap, smtp, smtps, rtsp, scp, ftp, telnet, mqtt, https, smbs, tftp, pop3s, dict
    Google Cloud Storage:        gs+http, gs+https, gs
    crypt4gh-needed:     crypt4gh
    mem:         mem

 #### Please describe your environment.
- OS (run `uname -sr` on Linux/Mac OS or ` wmic os get Caption, Version` on Windows)
- machine architecture (run `uname -m` on Linux/Mac OS or ` wmic os get OSArchitecture` on Windows)
- compiler (run `gcc --version` or `clang --version`)
Linux 3.10.0-1127.19.1.el7.x86_64
x86_64
gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-44)
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

#### Please specify the steps taken to generate the issue, the command you are running and the relevant output.
Using bam generated by minimap2.
```
samtools view -@ $t -bh -e “mapq >= $q && qlen/length(seq) >= $l && [de] <= $4 && [s2] / [s1] <= $5” -o ${bam/%.bam/.filtered.bam} $bam
[E::sam_passes_filter] Couldn't process filter expression
```

**Comment by daviesrob** [comment]
It looks like some variables are being substituted into your command line there.  Do you know what the actual values were?

**Comment by jkbonfield** [comment]
I can reproduce it.  Even things like `[X0]+[X1]`.  I'll investigate.

**Comment by Johnsonzcode** [comment]
> It looks like some variables are being substituted into your command line there. Do you know what the actual values were?

Sure, just some variables.

**Comment by jkbonfield** [comment]
Initially I can see two possibilities, using type morphing;  making the tag return numeric 0 for absent tags, or empty string for absent tags.  Either way I think we'll get `is_true` set for tags that exist and unset for ones that don't.

Then either `eq_expr` and similar need to relax the string and regexp comparisons to handle `"105" =~ "0"` the same as `105 =~ "0"` by automatically converting the numeric value to a string based on the usage context, and then permitting `[XA] =~ "\+"` working when the `XA` tag is absent.

Or `add_expr` and `mul_expr` need to do the opposite of treating a non-true absent string as zero.  Potentially we could also true an actual string containing a numeric value to be the numeric equivalent, so `"15" > 5` returns true (while `"15" > "5"` is false).

The latter is probably easier to do (bar the actual string to numeric value conversion, which for now I don't see a major use for).

**Comment by jkbonfield** [comment]
There's also a third option I just thought of.  Right now we detect mixing string and numeric and complain.   It seemed a reasonable thing to do, and probably is in the genral case, but for the nul string maybe we shouldn't and can instead just return false instead.  This also avoids all the nasties of divide by zeros and similar.

Basically `[s0] / [s1] <= 10` is always false is either `s0` or `s1` is absent.

**Comment by Johnsonzcode** [comment]
Thank your for your work. A possible workaround is
`[s2] <= [s1] * n`
Your options are good. All my reads have both `s1` and `s2`. But it may a divide by zero issue.

**Comment by jkbonfield** [comment]
Ok so divide by zero is a good catch.  I'm inclined to think it perhaps shouldn't complain and instead return false, but I'm open to ideas.  Or maybe to complain with a more appropriate error ("divide by zero" for example!).

Although your issue was a different one, I have been exploring the tri-state logic somewhat and I think what https://modern-sql.com/feature/is-distinct-from has to say on this is interesting.  Their rules are very similar to NAN comparison rules in languages too.  Specifically the doesn't-exist state can't be used in comparisons and will always fail.  We sort of have this already, as `[X0] > 1 |! [X0] <= 1` isn't a truism.  It's basically a test for if X0 tag exists and when it doesn't exist it'll fail.  However it's not applied consistently across the board.

Specifically we state in the documentation that to test for `[X0]!=0` we need to do `[X0] && [X0]!=0` as `[X0]!=0` matches as true for the X0-does-not-exist case.  This is at odds with the null-never-matches logic.  I think this is just confusing, and I propose adopting the rules in a more sensible style.  I've already got code to add an `exists([X0])` interface, meaning we can now filter on `!exists([X0])`.  That was really challenging before, needing the ghastly `!([X1] || [X1]==0)`.
