### ISSUE TITLE
"reset" subtool/functionality

### ISSUE THREAD

**Issue by dkj** [samtools/samtools#1682]
#### Is your feature request related to a problem? Please specify.
I'd like to reset the records in a SAM/BAM/CRAM file to a pre-alignment state ready for a fresh analysis - similar to a BAM->fastq->BAM roundtrip

#### Describe the solution you would like.
- remove alignment related fields, auxtags and flags
  - revcomp'ing seq and rev qual as appropriate
- keep other auxtag e.g. cell or UMI related by default
  - options to default auxtag keeps and discards possibly useful
- drop alignment only records like supplementary and secondary
- work with/include template collation and/or name sorting

Happy for separate subcommand or enhancements to view/sort/collate

**Comment by dkj** [comment]
I didn't know if: 
- auxtag 
- PG and RG header info

would propagate through the roundtrip via fastq - will they?

This is not urgent: the workaround is good to see, and there are other tools.

**Comment by daviesrob** [comment]
This wouldn't take too long to write really, and could be usefully combined with `collate` or `samtools sort -n` to get everything in the right order with a single command.  But are you then just going to pass the results into your aligner via fastq, in which case resetting with a separate program is a bit unnecessary.  I.e. what sort of process would you expect this to be sitting in?

**Comment by dkj** [comment]
This would be useful for resetting to a uCRAM state. i.e. for use by pipelines which start from uCRAM, although admittedly most such pipelines will convert to fastq at some point. (It's that pipeline's decision whether and how to keep the extra (auxtag/PG/RG) info). The particular example which catalysed this issue was a CRAM which had had `SamHaplotag` and `bwa mem` run. The bwa mem info needed removing but not the SamHaplotag info, before feeding to a pipeline using the ema aligner.

**Comment by jkbonfield** [comment]
Fixed by #1767
