### ISSUE TITLE
"samtools depth" command gives depth values limited to 8000 with no warning

### ISSUE THREAD

**Issue by adalisan** [samtools/samtools#1688]
#### Is your feature request related to a problem? Please specify.
I was using "samtools depth" for the first time. The samtools depth command results were very confusing as and were very different than what I expected after using IGV to look at the alignment file.

I understand the reasoning behind the default behaviour, you don't want to break pipelines that use this samtools command because of OOM errors. However it's very hard for new comers to understand why the depth commands  give wrong(?) answers. Only by looking at the documentation in detail, I could understand what was going on. The depth values were sometimes above 8000, so that were more confusing.
#### Describe the solution you would like.
I would recommend changing the "-d max_depth" argument  to a required one. or print a warning message at the shell.
Using version 1.9(although I believe newer versions also have this behaviour)

**Comment by whitwham** [comment]
The samtools depth -d option has been deprecated since version 1.13 and now no longer does anything.
