### ISSUE TITLE
samtools import fails for fastq with long data in headers

### ISSUE THREAD

**Issue by cjw85** [samtools/samtools#1689]
#### Are you using the latest version of [samtools](https://github.com/samtools/samtools/releases/latest) and [HTSlib](https://github.com/samtools/htslib/releases/latest)? If not, please specify.

Version 1.15.1 downloaded from github release page

 #### Please describe your environment.
- Linux 4.15.0-133-generic
- x86_64
- gcc (Ubuntu 5.4.0-6ubuntu1~16.04.12) 5.4.0 20160609

#### Please specify the steps taken to generate the issue, the command you are running and the relevant output.

Round-tripping `samtools fastq` and `samtools import` can fail when the length of the tag data is long (>1024 chars); the second command fails with an EOF error. Ultimately I believe this is a failure in `hts_detect_format2` which appears to read only 1024 chars to use to infer the file type. `samtools import` has a `--input-fmt-option` option, but no `--input-fmt` option.

Quickly hacking the code reveals `sam_read1` to return `-3` in `samtools import`. Adding

```
169a170
>         fp_in[i]->format.format = fastq_format;
```
 to `bam_import.c` allows the import to proceed.

#### Extra context

This likely used to be fine, but with long reads and tags such as the MM and ML containing a lot of data the likelihood of encountering the error has increased. I can't remember what I was doing last week to run into this error, so I can't say if this was a sensible thing to have wanted to be doing! But I would say `samtools import` needs a more helpful message and perhaps gain a `--input-fmt` option (or `hts_detect_format2` needs to work harder).

Sample file (though anything with longer headers will do):
[tmp.fastq.gz](https://github.com/samtools/samtools/files/9282984/tmp.fastq.gz)

**Comment by jmarshall** [comment]
This is really just a deficiency in `hts_detect_format2()`. For FASTA and FASTQ, it checks that the first character is `>` or `@` and (so that it doesn't say positive too often!) checks that the second line contains only the subset of alphabetic characters that represent bases. As you say, if the first line is massively long, it will not see any of the second line and so return false.

If the first line is massively long, it would probably be good enough to forget about checking the second line and essentially just go by the first line (mainly the `>` or `@` character). This would only introduce false positives for files with very long first lines where the `>` or `@` is probably accurate anyway.

**Comment by jkbonfield** [comment]
For `import` it's quite clear that the sole purpose of it is to deal with fasta/fastq so being more liberal with format detection is fine.  I was unsure what the impact of being more liberal to general tools (eg htsfile, or just plain file opening) would do.  In some cases I guess it's an improvement (eg samtools view on a fastq file is a very minimal import), but are there detrimental things?  I was maybe overly cautious as we're really only changing the unknown case to something (probably) known, and not breaking any previously assigned data types.

If you think it's worth while I'm happy to ditch my samtools PR and rewrite the htslib one to be more permissive.

**Comment by jkbonfield** [comment]
Although while I have your attention, is there any way to do a peek on data for htsFile?  We have hpeek for hfile, which is used during file opens for detecting the format, but we can't use it later on after the `hts_hopen` call as it may be bgzf, some network protocol, anything really.  I couldn't figure out a pleasant peek interface short of doing all the fp container elements manually in a switch.  (Although I gave up on that approach so didn't persue it further.)

**Comment by jkbonfield** [comment]
I've got a change written already too (just change `secondline_is_bases` to return -1 if no \n is found and it'll work), however looking again I see my previous assertion is wrong as fasta/fastq detection is done before some other formats.  I think it's unlikely they'd start with `@` or `>` though.  (SAM is in there, but only headerless SAM so the basic one gets spotted already.)

**Comment by jkbonfield** [comment]
Happy to wait for your PR if you wish as it was your thought to fix the detection function, or I'll make my own if you prefer.  (My change is trivial.)

**Comment by jmarshall** [comment]
That's now samtools/htslib#1491 which is a little less trivial as it adds validating that the first line is basically textual and adds a test case.
