### ISSUE TITLE
Issues when convert cram into bam

### ISSUE THREAD

**Issue by 229668880** [samtools/samtools#1693]
Hi, I am trying to extract mapped reads and unmapped reads from cram. I got some errors and googled this issue. Most people said it is an issue of reference genome. But this doesn't solve the issue after I tried several versions of reference genome.
I am very interested in "Failed to populate reference for id". What does this mean?

I got two problems:
**extract mapped reads**
samtools view -c -F 4 example.cram -T GRCh38_full_analysis_set_plus_decoy_hla.fa > example_mapped.bam

generate error:
[E::cram_get_ref] Failed to populate reference for id 33
[E::cram_decode_slice] Unable to fetch reference `#33` 6..30473
[E::cram_next_slice] Slice decode failure
[main_samview] truncated file.
samtools view: error closing "example.cram": -1

**extract unmapped reads**
samtools view -c -f 4 example.cram -T GRCh38_full_analysis_set_plus_decoy_hla.fa > example_unmapped.bam

error:
[E::cram_get_ref] Failed to populate reference for id 73
[E::cram_get_ref] Failed to populate reference for id 85
[E::cram_get_ref] Failed to populate reference for id 104
[E::cram_get_ref] Failed to populate reference for id 106
[E::cram_get_ref] Failed to populate reference for id 123
[E::cram_get_ref] Failed to populate reference for id 136

I got example_unmapped.bam. But I am not sure whether I can use it for the following analysis, considering the errors above.

**Comment by jkbonfield** [comment]
The error message is perhaps a little opaque.  Basically it means failed to find that reference.

Both cases it's likely that the references used in the CRAM file don't match the reference sequence you've given it.  Eg due to GRCh37 vs GRCh38 or hg19 naming differences.  Do a `samtools view -H` on the cram file to look at the SQ lines and compare those to the .fai file.
