### ISSUE TITLE
Samtools View Output Variables

### ISSUE THREAD

**Issue by MichWeb75** [samtools/samtools#1694]
Hi,
Samtools provides very helpful filtering expressions such as **rlen** to calculate the reference span:
`samtools view -e 'rlen>30' in.bam`

To transform the samtools view result to a BLAST-like output, I would like to compute the query and - subject-coverage and add this to the output table. is there a way to return the variable **rlen**, which is internally processed by samtools, to output ?

Is there a way to calculate the alignment length from the CIGAR string, removing the soft clipping region ?

**Comment by jkbonfield** [comment]
There aren't ways to do this in samtools and the filtering language has no mechanism for reporting the values of internal variables or expressions, but if using the htslib C API then it's simply a matter of calling `bam_cigar2qlen` and `bam_cigar2rlen` functions [as defined here](https://github.com/samtools/htslib/blob/develop/htslib/sam.h#L1048-L1086).

Couple that with a [basic SAM read loop ](https://github.com/samtools/samtools/blob/develop/sam_view.c#L734-L751) and you have the heart of a SAM to BLAST conversion tool.

**Comment by MichWeb75** [comment]
Thank you for the reference to the functions bam_cigar2qlen. Unfortunately I am not an expert in C programming and need to adopt this to Python.

The function is 
```
int bam_cigar2rlen(int n_cigar, const uint32_t *cigar)
{
    int k, l;
    for (k = l = 0; k < n_cigar; ++k)
        if (bam_cigar_type(bam_cigar_op(cigar[k]))&2)
            l += bam_cigar_oplen(cigar[k]);
    return l;
}

Can you please help to transform this line` if (bam_cigar_type(bam_cigar_op(cigar[k]))&2)` into Python code ? What is &2 doing ?
```

**Comment by jkbonfield** [comment]
That is rather cryptic, even for seasoned C programmers.

The relevant macro values here are:

```
#define BAM_CMATCH      0
#define BAM_CINS        1
#define BAM_CDEL        2
#define BAM_CREF_SKIP   3
#define BAM_CSOFT_CLIP  4
#define BAM_CHARD_CLIP  5
#define BAM_CPAD        6
#define BAM_CEQUAL      7
#define BAM_CDIFF       8
#define BAM_CBACK       9

/* bam_cigar_type returns a bit flag with:
 *   bit 1 set if the cigar operation consumes the query
 *   bit 2 set if the cigar operation consumes the reference
 *
 * For reference, the unobfuscated truth table for this function is:
 * BAM_CIGAR_TYPE  QUERY  REFERENCE
 * --------------------------------
 * BAM_CMATCH      1      1
 * BAM_CINS        1      0
 * BAM_CDEL        0      1
 * BAM_CREF_SKIP   0      1
 * BAM_CSOFT_CLIP  1      0
 * BAM_CHARD_CLIP  0      0
 * BAM_CPAD        0      0
 * BAM_CEQUAL      1      1
 * BAM_CDIFF       1      1
 * BAM_CBACK       0      0
 * --------------------------------
 */
#define BAM_CIGAR_TYPE  0x3C1A7
#define bam_cigar_type(o) (BAM_CIGAR_TYPE>>((o)<<1)&3) // bit 1: consume query; bit 2: consume reference
```

There are 10 different cigar types, values 0 to 9 as shown above, each of which can progress the query or progress the reference (one of, neither or both).  Hence we basically have a 10 x 2 table as recorded in the comment above, equating 20 bits worth of information.  The 0x3C1A7 constant is basically that entire table represented as a 20-bit number.

The `bam_cigar_type` macro looks data up in that table, selecting the relevant bits from `BAM_CIGAR_TYPE` constant and returning the pair of bits: `(o<<1)&3` .  Eg 0 1 for `BAM_CDEL`.  The user is then expected to select one of those bits themselves - see the comment "bit 1: consume query; bit 2: consume reference".
It's what the `&2` is doing in `if bam_cigar_type(bam_cigar_op(cigar[k]))&2)`.

This interface is a **little bit terse**, but was presumably written this way for maximum performance.

Of course if you're using python, then you'd be best off just using pysam anyway and the [query_alignment_length](https://pysam.readthedocs.io/en/latest/api.html#pysam.AlignedSegment.query_alignment_length) method and the analogous reference length (`reference_end-reference_start+1`? or `rlen` but it claims that is deprecated and the documentation points to a potentially inappriopriate `query_length`, but I'm no python expert so maybe it's correct).

Possibly a better bet for Python would simply be a couple lookup tables: `consumes_query` and `consumes_reference`.

**Comment by jmarshall** [comment]
That pysam `rlen` property's name is short for “read length”, but as noted that confusing name is deprecated in favour of the less misleading `query_length`.

The property the OP wants is `reference_length`, and if writing in Python then using pysam would IMHO be the recommended approach for those unfamiliar with these sorts of encodings.

**Comment by MichWeb75** [comment]
Thanks for the answer. I wrote a very short, perhaps not perfect solution which depends on a Cigar library available on Github.
Counts the number of Matches / Mismatches so far. Next step would be to add Insertions to total reference length.
```
from cigar import Cigar
c=Cigar('20M5I10M3I5M')
test  = sum([x[0] for x in c.items() if x[1] == "M" ])
```

**Comment by jkbonfield** [comment]
You'll need to think about other reference consuming operators, the most common of which is D (deletion).   I'd strongly advise using pysam.

PS.  Duh how did I gloss past `reference_length` when reading that pysam doc.  I even looked for it and didn't find it. Hah.
