### ISSUE TITLE
Very long deletions break `samtools stats`

### ISSUE THREAD

**Issue by jdidion** [samtools/samtools#1707]
I am using `vg giraffe` to align reads to the Human Pan-genome Reference and surject into GRCh38 coordinates. This can create alignments with very large indels. One of my alignments has a CIGAR that looks like this: `14M45516D80M`. `samtools stats` complains with error "FIXME: 80+45530 > 20000", which I take to mean that it only supports indels up to length 20 kb. Is there a way to tell `stats` to ignore reads with indels larger than the supported size? If not, is this a reasonable feature request?

**Comment by jkbonfield** [comment]
This comes from https://github.com/samtools/samtools/blob/develop/stats.c#L498 so it's not just a 20kb limit.  `nrseq_buf` in turn appears to be `fai_ref_len`, but via a very tortuous route I think that is limited by `gcd_bin_size` here: https://github.com/samtools/samtools/blob/develop/stats.c#L2199 (cunningly disguising 20000 as 20e3 so grep fails to find it).

This can be modified on the command line:

```
        --GC-depth <float>              the size of GC-depth bins (decreasing bin size increases memory requirement) [2e4]
```

That will have other implications, although it may be a workaround for now.

I think it's a reasonable request that these records should not be a hard failure when found.

**Comment by daviesrob** [comment]
Pull request #1712 should fix this.  @jdidion It includes a very minimal test, but it would be handy if you could build it and test it on the file that triggered the problem to confirm that it works.
