### ISSUE TITLE
Minor release to include fixes to bugs I created

### ISSUE THREAD

**Issue by nh13** [samtools/samtools#1708]
I’d like to request a minor release so that the fixes #1703 and #1705 to bugs I am responsible for can be part of an official release. I am happy to help in any way to make the release easier for folks. Thank you for your consideration, and again, my sincerest apologies for the bugs I introduced making it into a release.

**Comment by daviesrob** [comment]
This should be possible.  I'll look into it.

**Comment by daviesrob** [comment]
[Minor release 1.16.1](https://github.com/samtools/samtools/releases/tag/1.16.1) is now out.

**Comment by nh13** [comment]
Thank you!
