### ISSUE TITLE
Which version of samtools have included the ampliconclip module?

### ISSUE THREAD

**Issue by kakuk9** [samtools/samtools#1715]
The version number of samtools is a bit cofusing for me.
I was trying to use the samtools ampliconclip module, I found it on samtools 1.12, but not on samtools Version: 1.9 (using htslib 1.9) that is installed in my environment on conda. How can I install a samtools version that consists of the ampliconclip module using conda? Is this ampliconclip module new or it's old and is retired?

**Comment by whitwham** [comment]
The format of our versioning is MAJOR.MINOR (or in the rare case that we do a patch release the full [semantic](https://semver.org/) format of MAJOR.MINOR.PATCH).

So you do not read the MINOR number as a decimal but as a full number and therefore 12 is later than 9.

Ampliconclip was introduced in 1.11 but went through several rounds of development and I would use the latest release (1.16.1) that you can find.

I'm not a conda expert but the instuctions in #1714 might help you.
