### ISSUE TITLE
Samtools ampliconclip hard clip not giving same results as soft clip

### ISSUE THREAD

**Issue by KevinXu264** [samtools/samtools#1717]
Hi all,

After stumbling on this post: https://bioinformatics.stackexchange.com/questions/16112/precisely-clipping-bam-file-to-bed-coordinates, I found out about the samtools ampliconclip package and wanted to use it for my own project. However, I'm running into some issues with using the samtools ampliconclip --soft-clip versus --hard-clip option.

Essentially, what I'm trying to do is clip certain reads of interest in a bam file down to a specific window that I specify using a bed file. However, when I run ampliconclip with --soft-clip, it gives me what I want, but when I run it with --hard-clip, it basically produces a blank bam file as output.

This is a picture of the unprocessed bam file of interest
<img width="807" alt="Screen Shot 2022-09-13 at 8 18 57 PM" src="https://user-images.githubusercontent.com/26608622/190267440-09b3ac8d-bf66-4301-95ee-6716bcead308.png">

This is the complement bed file that I want to clip
```
9   0   33261120
9   33262737    149000000000
```

After running the code 
```
samtools ampliconclip --both-ends --soft-clip -b input.bed input.bam> output.bam
```
 I get the result I want, which is all my reads clipped besides a certain genomic interval
<img width="803" alt="Screen Shot 2022-09-13 at 8 25 54 PM" src="https://user-images.githubusercontent.com/26608622/190267553-9767d8c3-bbca-4e81-ac16-258d8efa9600.png">

However, what I really want is the hard clipped version of these reads. However, when running the same code 
```
samtools ampliconclip --both-ends --hard-clip -b input.bed input.bam> output.bam 
```
I basically get an empty file with no reads at all.
<img width="802" alt="Screen Shot 2022-09-13 at 8 19 20 PM" src="https://user-images.githubusercontent.com/26608622/190267609-f2ad844b-09d5-4cbd-b742-dfc31fad5712.png">

From my understanding, using ampliconclip with --hard-clip versus --soft-clip should only change the CIGAR string and not how the intersection with the bed file should work, so I'm a little stumped as to why its giving me such different outputs. I have even tried --hard-clip with other bam files (from yeast) and it works as intended, but just not with these reads (from human). Any help is greatly appreciated!

**Comment by whitwham** [comment]
> From my understanding, using ampliconclip with --hard-clip versus --soft-clip should only change the CIGAR string and not how the intersection with the bed file should work

You are correct, that is how it should work.

I have not seen this before.  If you look at one of the hard clipped reads, does the CIGAR string show that the entire read has been hard clipped?

**Comment by KevinXu264** [comment]
Each read in the hard-clipped output file looks like it lost all read data, including the sequence and the CIGAR string itself. 

It looks like I can't attached bed files as attachments on github. Any way I could send you these files so you could test them yourself?

**Comment by whitwham** [comment]
Thank you for the test files.  I can replicate your results and now I am trying to see why it is happening.
