### ISSUE TITLE
Allow depth to read from stdin if no input

### ISSUE THREAD

**Issue by mbhall88** [samtools/samtools#1719]
#### Is your feature request related to a problem? Please specify.

If no input file is given to `depth`, the command fails with no message other than the help menu. This can be confusing if piping a SAM file in from stdin. However, it will work when `-` is provided - meaning stdin is obviously supported.

#### Describe the solution you would like.

Other samtools commands seamlessly assume stdin if no input file is given, so it would be nice to have the same functionality for `depth`. (Sorry if this has been covered 1000 times elsewhere but I coulnd't see anyone raising it for `depth`)

**Comment by jkbonfield** [comment]
I'm not convinced this is ideal.  While some commands do this, it's not without problem.  Specifically on Windows it's not easy to distinguish between reading from stdin being a file vs stdin being a tty, which breaks the command usage with e.g. `samtools view`.

I did a survey of commands and found which support stdin without an explicit `-` filename:

```
fasta      Y                                                                    
fastq      Y                                                                    
head       Y                                                                    
sort       Y                                                                    
stats      Y                                                                    
view       Y                                                                    
                                                                                
collate    N (SEGV!)                                                   
consensus  N                                                                    
coverage   N                                                                    
depad      N                                                                    
depth      N                                                                    
flagstat   N                                                                    
import     N                                                                    
mpileup    N                                                                    
samples    N (plus broken error message)                                               
split      N                                                                    
```

There are more subcommands where it's inappropriate, eg needing many filenames (merge), requiring an index (idxstats, bedcov), or have a mandatory argument after the bam file (calmd).

Given bedcov, coverage, depth and mpileup all group together as similar functionality and none of them support implicit stdin, I'm not inclined to do just depth currently.  Ideally if we did this issue, we'd need to do all commands really to be consistent.  (We cannot undo those already done, even if it was deemed a misfeature.)  However the issues of tty checking not being so portable makes me question whether this is a suitable route.

Any thoughts from the other Samtools maintainers?

**Comment by jkbonfield** [comment]
Closing this as we don't have any plans to extend support for implicit stdin right now, but we may revisit this in the futue.
