### ISSUE TITLE
samtools fastq losing data in single end input

### ISSUE THREAD

**Issue by Poshi** [samtools/samtools#1728]
#### Are you using the latest version of [samtools](https://github.com/samtools/samtools/releases/latest) and [HTSlib](https://github.com/samtools/htslib/releases/latest)? If not, please specify.
(run `samtools --version`)
I found this to be happening from version 1.13 and newer. Working properly in 1.12 and older.

 #### Please describe your environment.
- OS: Linux 2.6.32-754.10.1.el6.x86_64
- machine architecture: x86_64
- compiler: gcc (GCC) 6.3.0

#### Please specify the steps taken to generate the issue, the command you are running and the relevant output.
Given a SAM file (also tested with CRAM) called `test.sam`:
```
@HD     VN:1.4  SO:unsorted
@PG     ID:BBMap        PN:BBMap        VN:38.57
@RG     ID:A    SM:unknown      LB:unknown      PU:unknown      PL:ILLUMINA     CN:unknown
A00000:241:HHHHHDSXY:4:1101:23393:1078  69      *       0       0       *       *       0       0       GAACATGTTGGTGTGAGATGGCTGCTGTAGAAACAGTAACTTCTACCTTATTCCTTTGGTAGGTGGAACAGTTGCAGCACACCCATGAGGAACACAGATTT   FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF:FF   BC:Z:1     RG:Z:A
```
the following command
```
samtools fastq -1 test_1.fastq -i --index-format i1 test.sam
```
is giving an output file with
```
@A00000:241:HHHHHDSXY:4:1101:23393:1078 1:N:0:+
GAACATGTTGGTGTGAGATGGCTGCTGTAGAAACAGTAACTTCTACCTTATTCCTTTGGTAGGTGGAACAGTTGCAGCACACCCATGAGGAACACAGATTT
+
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF:FF
```
while the expected output is
```
@A00000:241:HHHHHDSXY:4:1101:23393:1078 1:N:0:1
GAACATGTTGGTGTGAGATGGCTGCTGTAGAAACAGTAACTTCTACCTTATTCCTTTGGTAGGTGGAACAGTTGCAGCACACCCATGAGGAACACAGATTT
+
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF:FF
```

The attention should go to the `BC` tag and the Illumina Casava 1.8 format entry. For some reason, it is giving `1:N:0:+` instead of `1:N:0:1`.
The same happens with `--index-format "i*"`

**Comment by jkbonfield** [comment]
Your BC tag is invalid.  You have `BC:Z:1`, but the SAMtags specification states it must be sequence, possibly with `-` or `+` separating the multiple barcodes.

I'm not sure why you're getting a `+` out of it here and it shouldn't be happening, but it's definitely an issue of bad data in => bad data out.  I suspect it's considering any non ACGTN as a barcode separator and is then parsing "1" as <empty-seq> <separator> <empty-seq> as a double-barcode, which is canonicalised in CASAVA as <seq>+<seq>.

**Comment by Poshi** [comment]
:-O You are right, that tag is supposed to contain a barcode. In that case, it would be good to complain to the user about malformed data rather than generate wrong data.
And now I have to see how to deal with a bunch of FastQ/CRAM files that contain non-barcode data in those locations :-/
Thanks for the insight!

**Comment by jkbonfield** [comment]
Agreed.  We'll leave this issue open as we have other things that need fixing here clearly.

**Comment by Poshi** [comment]
I'd love if you solve the issue by issuing a warning and passing whatever is in the field. But if you issue and error and refuse to process the buggy data I won't complain, as this would be a proper processing of the data.
