### ISSUE TITLE
Samtools markdup (with UMIs)

### ISSUE THREAD

**Issue by yloemie** [samtools/samtools#1730]
Hi team,
first, thanks for your incredible works.

I have an issue, I wanted to use markdup with UMIs (in the read names, with the option --barcode-name)

I have still this error : 
`[markdup] warning: barcode regex match error "No match" on NS500199:732:HG72YBGXM:1:22112:9075:8595:GGGCAGCGT`

 from the doc, it says : `--barcode-name  Use the UMI/barcode embedded in the read name (eigth colon delimited part)`
 
 What do I miss?
 
 Anyway, I saw the --barcode-regex option but without detail I cannot write it, and I found 0 example on the web...
 
 If I may, I suggest to be a little more explicit (as you did for the regex --read-coords option).
 
 Best,
 
 Yann

**Comment by whitwham** [comment]
Yes, that is a bug. All my local test data is formatted like this:
`NS500199:732:202:1:22112:9075:8595:GGGCAGCGT`
With only numbers between the first and last entries.  So your read name with `HG72YBGXM` in it is not being recognised.

Until I fix it you could try this for a **--barcode-regex** option:
`[0-9A-Za-z]+:[0-9]+:[0-9A-Za-z]+:[0-9]+:[0-9]+:[0-9]+:[0-9]+:([!-?A-~]+)`

**Comment by mrubio-chavarria** [comment]
Hi samtools team,

Thank you for the great software. I got a similar problem with this query name:
AV234501:260709-395-A-PE75-FS-HO:2538608933:1:10102:4631:1346:TACCAAGGCT
The --barcode-name option does not recognise the final UMI.
I fixed it by using the regex alternative:
--barcode-rgx "[0-9A-Za-z]+:[0-9]+-[0-9]+-[A-Za-z]+-[0-9A-Za-z]+-[A-Z]+-[A-Z]+:[0-9]+:[0-9]+:[0-9]+:[0-9]+:[0-9]+:([!-?A-~]+)"
but I realised that if I use the regex configuration, the option --move-umi-to-tag does not work, and the UMIs remain in the query name and no tag is added.
Please could you let me know if I misinterpreted anything? Can I solve it somehow? Additional descriptions in the UMI options would be really helpful. Anyway, samtools markdup is a really great tool

Best,

Mario

**Comment by whitwham** [comment]
Hi @mrubio-chavarria, this really should be a new issue.

Anyway, your regex worked for me with **--move-umi-to-tag**.  My command:
`samtools markdup --barcode-rgx '[0-9A-Za-z]+:[0-9]+-[0-9]+-[A-Za-z]+-[0-9A-Za-z]+-[A-Z]+-[A-Z]+:[0-9]+:[0-9]+:[0-9]+:[0-9]+:[0-9]+:([!-?A-~]+)' --move-umi-to-tag move_umi_test.sam result.sam
`

Though if your data has all the same format and all you want is the last colon delimited section then a simpler regex would work.
`--barcode-rgx ':([ACTG]+)$' `
