### ISSUE TITLE
Samtools sort with paired-end RNA-seq

### ISSUE THREAD

**Issue by sofiapuvogelvittini** [samtools/samtools#1736]
Hi, thank you very much for this cool package.
I am working with paired-end RNAseq data, and before sorting with samtools sort the R1 and R2 are organized consequtively in the BAM file (attached picture UNsorted_reads). Using samtools sort, the paired reads are no longer organized consequtively in the sorted bam file (attached picture sorted_reads). Is this the correct way? I would like to use this sorted bam file for UMI deduplication with UMI tools. 
Thank you very much for your gidance,
Best regards,
Sofia
<img width="915" alt="UNsorted_reads" src="https://user-images.githubusercontent.com/48957422/196745237-d51164bd-94dd-4ac6-9175-e0c57a170f56.png">
<img width="916" alt="sorted_reads" src="https://user-images.githubusercontent.com/48957422/196745261-a8425ceb-b138-4b86-948f-49fc82bd15b9.png">

**Comment by whitwham** [comment]
According to the umi tools [documentation](https://github.com/CGATOxford/UMI-tools/blob/master/doc/QUICK_START.md#step-5--deduplication) this is fine.

The default `samtools sort` sorts by alignment position so read pairs will be separated.

**Comment by sofiapuvogelvittini** [comment]
Thanks whitwham!
