### ISSUE TITLE
Error encountered while indexing sorted  BAM file

### ISSUE THREAD

**Issue by dianzhiyong** [samtools/samtools#1737]
dear 
i have used samtools sort and  samtools index bam file for same species  successfully ,but now it can not index  a sorted bam file  successfully  for the  gingko ,it has  same very long chromosomes .  Could you give me same  suggestions ? thanks

"
$ samtools index -c   s1.sort.bam
[E::hts_idx_push] NO_COOR reads not in a single block at the end 0 -1
samtools index: failed to create index for "s1.sort.bam"
"

**Comment by whitwham** [comment]
Which version of samtools are you using?  How long is the very long chromosome? What OS are you using?

**Comment by dianzhiyong** [comment]
samtools  Version: 1.9  in  centos7 ，the longst  chromosome  size is more than 1.1G  bp ,thank you

**Comment by dianzhiyong** [comment]
samtools  Version: 1.9  in  centos7 ，the longst  chromosome  size is more than 1.1G  bp ,thank you

**Comment by jkbonfield** [comment]
Sadly adding `@PG` lines appeared in 1.10, so we cannot check.  However this error message is normally due to the data not bewing sorted by chromosome and position.  Newer samtools releases give you a hint by reporting a specific read and location, eg:

```
[E::hts_idx_push] NO_COOR reads not in a single block at the end 85 -1
[E::sam_index] Read 'HS25_09827:2:1201:1404:93192#49' with ref_name='hs37d5', ref_length=35477943, flags=185, pos=23719271 cannot be indexed
```

Are you absolutely sure your data is sorted?  You can at least visually inspect it with 
```
samtools view in.bam | cut -f 3-4 | head -20
```

**Comment by dianzhiyong** [comment]
i try to install  1.10 and sort again ，thanks very much


$ samtools view s1.sort.bam | cut -f 3-4 | head -20
Chr1    56
Chr1    67
Chr1    72
Chr1    89
Chr1    90
Chr1    93
Chr1    102
Chr1    130
Chr1    190
Chr1    237
Chr1    244
Chr1    318
Chr1    19068
Chr1    19068
Chr1    19068
Chr1    19068
Chr1    19727
Chr1    19727
Chr1    20248
Chr1    20248

**Comment by dianzhiyong** [comment]
i  tested  samtools 1.10   as below

$  samtools index  -c  test.sort.bam 
[E::hts_idx_push] Chromosome blocks not continuous
[E::sam_index] Read 'A00270:439:HLGWNDSX3:3:1536:14886:19288' with ref_name='Chr1', ref_length=1132477351, flags=163, pos=1073741847 cannot be indexed
samtools index: failed to create index for "test.sort.bam": No such file or directory

**Comment by jkbonfield** [comment]
That's likely a size issue:

```
$ printf "%x\n" 1073741847 
40000017
```

I don't understand though why it's triggering at that size given you're using a CSI index.  Can you please test with the current release incase it's an old bug we've already fixed?

**Comment by jkbonfield** [comment]
Indeed this little test file can be converted to BAM and indexed fine for me, even with 1.10.

```
@SQ	SN:chr1	LN:1132477351
foo	99	chr1	1073741847	70	10M	*	0	0	AAAAAAAAAA	*
```

I've tried sorting data that large too and it's working OK.  I cannot explain the cause of this failure, but suggest you look for the reads either side of A00270:439:HLGWNDSX3:3:1536:14886:19288 to see if there is a smoking gun.  (With `grep -A5 -B5` for eample)

**Comment by dianzhiyong** [comment]
thanks very much
with your guidance, I found the problem ，actually the bam is not sorted  correctly  ,as the code  show 

$ samtools view  -@  4  test.sort.bam  | grep -A 5 -B 5 A00270:439:HLGWNDSX3:3:1536:14886:19288  | cut -f 1-3 
A00270:439:HLGWNDSX3:3:1151:22987:10394 147     hic_scaffold_76468
A00783:1036:HJNLFDSX3:3:2336:21495:7780 99      hic_scaffold_76468
A00783:1036:HJNLFDSX3:3:2336:21495:7780 147     hic_scaffold_76468
A00783:1036:HJNLFDSX3:3:2220:24460:17174        99      hic_scaffold_76468
A00783:1036:HJNLFDSX3:3:2220:24460:17174        147     hic_scaffold_76468
A00270:439:HLGWNDSX3:3:1536:14886:19288 163     Chr1
A00270:439:HLGWNDSX3:3:1536:14886:19288 83      Chr1
A00270:439:HLGWNDSX3:3:2230:11939:12023 99      Chr1
A00270:439:HLGWNDSX3:3:2230:11939:12023 147     Chr1
A00270:439:HLGWNDSX3:3:2218:20790:27320 99      Chr1
A00270:439:HLGWNDSX3:3:2218:22426:27774 99      Chr1
A00270:439:HLGWNDSX3:3:2218:20790:27320 147     Chr1

 
the test bam was sorted by  samtools sort  (Version: 1.9)  , how to  correctly sort bam

**Comment by dianzhiyong** [comment]
samtools sort 1.10  can solve it , thank you
