### ISSUE TITLE
`samtools sort` gives "[E::hts_open_format] Failed to open file ... : File exists" for temporary files it creates

### ISSUE THREAD

**Issue by hermidalc** [samtools/samtools#1739]
I'm using the latest samtools available on conda-forge. Sorry I haven't used samtools in a long time, but why am I getting these messages?

```
$ samtools sort CAMI_low_RL_S001__insert_270_pufferfish.sam -o CAMI_low_RL_S001__insert_270_pufferfish.bam
[E::hts_open_format] Failed to open file "CAMI_low_RL_S001__insert_270_pufferfish.bam.tmp.0000.bam" : File exists
[E::hts_open_format] Failed to open file "CAMI_low_RL_S001__insert_270_pufferfish.bam.tmp.0001.bam" : File exists
[E::hts_open_format] Failed to open file "CAMI_low_RL_S001__insert_270_pufferfish.bam.tmp.0002.bam" : File exists
[E::hts_open_format] Failed to open file "CAMI_low_RL_S001__insert_270_pufferfish.bam.tmp.0003.bam" : File exists
```

**Comment by whitwham** [comment]
Do they exist?  If not, check to make sure you can write a file to that directory.

**Comment by hermidalc** [comment]
They do exist and I can write to the directory

**Comment by hermidalc** [comment]
> The temporary files are likely to be left over from a previous failed run. If you don't have any other sorts running that might want to read them, you should remove them.
> 
> Also, what version of samtools did you build? If you didn't use conda-forge, it may have built a very outdated version. Newer samtools releases should be able to work around stray temporary files.
> 
> If you haven't got a recent version, you could try following the instructions [here](https://github.com/samtools/samtools/issues/1714#issuecomment-1237139214) to see if they help.

Ah that's what it is! Sorry. At first I didn't realize it was creating temp files in the BAM directory at all (I was running the command from outside this dir). I use the latest on conda-forge so my version is `1.16.1`. I just tested it now and see that I can also redirect the path where temp files are created with `-T`

**Comment by skchronicles** [comment]
#### Just an FY fir anyone else who stumbles across this issue:

I ran into this issue too when piping a SAM file into `samtools sort`. It was erroring out about files existing (even though the files did not exist prior to execution?!). I was sorting, converting to BAM, and writing an index simulateously in the same process, and I can confirm that providing the `-T` option fixed the problem. 

**Error:**
```bash
$ minimap2 \
            -ax splice \
            -uf \
            -k14 \
            gencode.v42.transcripts.fa \
            test.filtered.fastq.gz \
| samtools sort -@4 \
            -O BAM \
            --write-index \
            -o out.bam##idx##out.bam.bai \
            -

# [M::mm_idx_gen::13.445*1.69] collected minimizers
# [M::mm_idx_gen::17.740*2.00] sorted minimizers
# [M::main::18.152*1.96] loaded/built the index for 252416 target sequence(s)
# [M::mm_mapopt_update::18.890*1.92] mid_occ = 177
# [M::mm_idx_stat] kmer size: 14; skip: 5; is_hpc: 0; #seq: 252416
# [M::mm_idx_stat::19.222*1.90] distinct minimizers: 25289760 (30.25% are singletons); average occurrences: 5.789; average spacing: 2.978; total length: 435903449
# [M::worker_pipeline::321.234*2.91] mapped 584436 sequences
# [M::worker_pipeline::596.149*2.97] mapped 574904 sequences
# [E::hts_open_format] Failed to open file "out.bam" : File exists
# samtools sort: failed to create temporary file "out.bam##idx##out.bam.bai.tmp.0000.bam": File exists
# [E::hts_open_format] Failed to open file "out.bam" : File exists
# [E::hts_open_format] Failed to open file "out.bam" : File exists
# samtools sort: failed to create temporary file "out.bam##idx##out.bam.bai.tmp.0001.bam": File exists
# samtools sort: failed to create temporary file "out.bam##idx##out.bam.bai.tmp.0002.bam": File exists
```

**Solved with `-T TMP_DIR`:**
```bash 
$ mkdir tmp/
$ minimap2 \
            -ax splice \
            -uf \
            -k14 \
            gencode.v42.transcripts.fa \
            test.filtered.fastq.gz \
| samtools sort -@4 \
            -T tmp/
            -O BAM \
            --write-index \
            -o out.bam##idx##out.bam.bai \
            -
 
# [M::mm_idx_gen::13.636*1.69] collected minimizers
# [M::mm_idx_gen::17.941*2.00] sorted minimizers
# [M::main::18.356*1.96] loaded/built the index for 252416 target sequence(s)
# [M::mm_mapopt_update::19.095*1.92] mid_occ = 177
# [M::mm_idx_stat] kmer size: 14; skip: 5; is_hpc: 0; #seq: 252416
# [M::mm_idx_stat::19.427*1.90] distinct minimizers: 25289760 (30.25% are singletons); average occurrences: 5.789; average spacing: 2.978; total length: 435903449
# [M::worker_pipeline::321.673*2.91] mapped 584436 sequences
# [M::worker_pipeline::612.804*2.97] mapped 574904 sequences
# [M::worker_pipeline::714.057*2.85] mapped 142481 sequences
# [M::main] Version: 2.24-r1122
# [M::main] CMD: minimap2 -ax splice -uf -k14 /data/NCBR/projects/NCBR-325/refs/gencode.v42.transcripts.fa /data/NCBR/projects/NCBR-325/FAU70068_pass_0e48be11/fastqs/FAU70068_pass_0e48be11.filtered.fastq.gz
# [M::main] Real time: 714.580 sec; CPU: 2033.573 sec; Peak RSS: 7. 
```

Anyways, I hope this helps anyone else who runs into this issue.

Best Regards,
@skchronicles

**Comment by jkbonfield** [comment]
This is probably some unwanted interaction with naming tmp files after the output filename, but using the file##idx##index notation as the filename.

Instead of `out.bam##idx##out.bam.bai.tmp.0001.bam` the tmp files should be `out.bam.tmp.0001.bam`.  This is our bug.

Out of interest though, why are you using the explicit ##idx## syntax to specify the default bai index filename?  It would use that path with a simpler `-o out.bam` too, which would make life easier for you.

**Comment by jkbonfield** [comment]
Also a FYI for anyone reading the above... update your version of Samtools!

I was able to reproduce this bug with 1.13, and 1.14 onwards it works correctly.  This was probably fixed in https://github.com/samtools/samtools/pull/1510 along with the other tmp file things.
