### ISSUE TITLE
Error recieved in samtools when using faidx

### ISSUE THREAD

**Issue by zjwinn** [samtools/samtools#1742]
I am not sure if this is a bug as much as it may be user error. When I try to index my reference genome, I get this error when using faidx:

samtools: /usr/lib/x86_64-linux-gnu/libcurl.so.4: version `CURL_OPENSSL_3' not found (required by samtools).

I am not sure how to proceed from here. I am on the most current version of samtools, because I just installed it on the server I am working on. I am unsure what is going on with this error and how to install the requested `CURL_OPENSSL_3'...

**Comment by daviesrob** [comment]
It looks like your copy of samtools is trying to use a different libcurl library to the one it was built against.  How did you build your copy of samtools?

**Comment by zjwinn** [comment]
I cannot check the version using:

samtools --version

Because I get the same error.

I have done the following

Sudo apt remove samtools
Sudo apt remove curl

Sudo apt-get install samtools
Sudo apt-get install curl

And I still get the same error. I assume by uninstalling and reinstalling that I would be using the most recent version of both. I inherited this server and several different genetics groups have used it (improperly) before. Is it possible that one of the groups set the system wide default samtools version to an earlier version? Is there some command to remove all previous versions?

- Zachary Winn
________________________________

**Comment by daviesrob** [comment]
You haven't said which OS distribution you're running (try `lsb_release -a` or `cat /etc/issue` to find out), but as they update quite slowly it's likely the version of samtools you installed that way is quite old.  On [Ubuntu](https://packages.ubuntu.com/search?keywords=samtools&searchon=names&suite=all&section=all) this would be 1.13, and [Debian stable](https://packages.debian.org/search?keywords=samtools&searchon=names&suite=all&section=all) is 1.11 (although testing is now at 1.16.1).  This doesn't explain the mismatch in libcurl versions though, as `apt` should resolve that for you.  It's possible that you're not running the copy of `samtools` that you expect - you should check with `which samtools` to see if this is the case.

For an up-to-date copy, you might be better off grabbing the [latest release](https://github.com/samtools/samtools/releases), following the instructions in the INSTALL file for [debian/ubuntu](https://github.com/samtools/samtools/blob/969d44990df7fa9c7bda3a7140a2c1d1bd8c62a0/INSTALL#L218) and then [build it yourself](https://github.com/samtools/samtools/blob/969d44990df7fa9c7bda3a7140a2c1d1bd8c62a0/INSTALL#L72).  Note that you don't have to do the `make install` part - you can run it from the location where you build it - just make sure that this directory comes first in your PATH environment variable.

**Comment by zjwinn** [comment]
When I run cat /ect/issue, it says I am using Ubuntu 20.04.5 LTS. Turns out, there were two copies of samtools running around on the server. I deleted both of them, uninstalled samtools, and then installed samtools... This seems to have fixed the problem.
