### ISSUE TITLE
samtools view -@ 1  does nothing 

### ISSUE THREAD

**Issue by goranvinterhalter** [samtools/samtools#1743]
The root cause: https://github.com/samtools/samtools/blob/develop/sam_view.c#L1236

Only -@ 2 will invoke thread pool, otherwise main thread is used for everything. 
I understand that the use of one thread might seam strange when using a thread pool as effectively three threads are needed to run everything in parallel: decompress thread, main processing thread and compress thread. But, other samtools commands are allowing for -@ 1 to use a dedicated thread for decompression and also, documentation stipulates that this is an additional thread.
In this regard samtools view is an outlier.

Maybe in the end allowing -@ 1 makes no sense, but it at least aligns to the behavior of other commands and the documentation, but also you empower the end user to utilize the resources as he sees fit.

Note: 
 - I'm not sure when this is used  https://github.com/samtools/samtools/blob/develop/sam_view.c#L1551 but it looks to me like thread pool is overriding it.
 - If view is revised, than sort should be as well. I haven't looked into that one, but I've seen > 1 used for threads.

#### Samtools version is not latest
```
samtools 1.16.1
Using htslib 1.16
```

 #### Please describe your environment.
- OS Linux/Mac OS 
- machine architecture: arm64
- compiler: Apple clang version 14.0.0 (clang-1400.0.29.102)

#### Please specify the steps taken to generate the issue, the command you are running and the relevant output.
```bash
(time  samtools view a.bam -c -@ 1  &); sleep 0.3;  ps -M;
```
Btw does anyone know of a better way to visualize currently running threads and their utilization?

**Comment by jkbonfield** [comment]
The `htop` command can list threads, and you can also look at /proc/$pid/task which will have one subdirectory per thread.

For what it's worth, there is some benefit to using a thread pool of 1 even when the main thread is doing nothing, as it turns the I/O into asynchronous mode.  (A pool of N has N+2 threads, with the 2 extra being nothing more than reading and writing.)

**Comment by goranvinterhalter** [comment]
> The `htop` command can list threads, and you can also look at /proc/$pid/task which will have one subdirectory per thread.

I was originally not able to use `htop`.  Using F5 did not show me any threads from htslib.

> For what it's worth, there is some benefit to using a thread pool of 1 even when the main thread is doing nothing, as it turns the I/O into asynchronous mode. (A pool of N has N+2 threads, with the 2 extra being nothing more than reading and writing.)

Very much agree. The combination is very useful in Pysam for example when Python process is struggling doing "nothing" :)
