### ISSUE TITLE
Making consensus error - malloc(): smallbin double linked list corrupted

### ISSUE THREAD

**Issue by trilisser** [samtools/samtools#1744]
#### Are you using the latest version of [samtools](https://github.com/samtools/samtools/releases/latest) and [HTSlib]
samtools 1.16.1
Using htslib 1.16

 #### Please describe your environment.
Linux 5.4.0-131-generic
x86_64
gcc (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0

#### Please specify the steps taken to generate the issue, the command you are running and the relevant output.
Hello! I try to get a consensus from .bam
`samtools consensus barcode01.bam`
and get an error:
```
malloc(): smallbin double linked list corrupted
Aborted (core dumped)
```
Something wrong with .bam?

**Comment by jkbonfield** [comment]
Almost certainly nothing you're doing wrong.  It looks like we have a memory corruption.  Do you have any test data able to demonstrate this please?

**Comment by trilisser** [comment]
This is link to a bam file I work with: https://drive.google.com/file/d/1EcKlK1Q6_zmaJ1M5QLKCcLvevqwYtHCx/view?usp=share_link
Can you please tell me more about what to do with `gdb samtools core` as it gives an error:
```
Reading symbols from samtools...
.../samtools-1.16.1/bin/core: No such file or directory
```

**Comment by trilisser** [comment]
This is link to a bam file I work with: https://drive.google.com/file/d/1EcKlK1Q6_zmaJ1M5QLKCcLvevqwYtHCx/view?usp=share_link
Can you please tell me more about what to do with `gdb samtools core` as it gives an error:
```
Reading symbols from samtools...
.../samtools-1.16.1/bin/core: No such file or directory
```

**Comment by jkbonfield** [comment]
Thanks for the test data.  It's almost certainly due to the zero-length sequences, but I'll work on the code and make an update as it should never simply crash.

In this case however, filtering out QCfailures, duplicate reads, secondaries and supplementaries first resolves the problem:

```
samtools view -u -F 0xf00 barcode01.bam | samtools consensus -o barcode01.cons -
```

**Comment by trilisser** [comment]
Thank you very much, James! It works well now.

Taking this opportunity, I would like to clarify some points:

- I analyze nanopore data, so, in this regard, is there any option/flag to low a Q score threshold to 10? barcode01.cons contains some gaps in sites where gaps are not intended to be, I think it's about QC.
- Previously,  I tried to make a consensus with a reference following [this instructions](https://samtools.github.io/bcftools/howtos/consensus-sequence.html) and got a situation when a nucleotide was put into the position depending on a reference which I used before during alignment with guppy_aligner. For example, in the a bam file, some site contains 90% of A and 10% of T, so when I align a fastq file with a reference containing A, I got A in the consensus, but if I align using a reference containing T in this site, I get T despite T is 10% from coverage in a bam file.  Using your command above resolves this problem. Why that happened?

**Comment by jkbonfield** [comment]
There are two modes for computing consensus - a basic counting method (either +1 per base or +qual), and a more complex Bayesian approach with models for germline diploid sequencing.  Both can produce ambiguity codes (-A option).   PR #1733 extends samtools consensus to better handle platforms with higher indel error rates and produce more accurate consensus.  This was for improving PacBio CCS consensus, but would equally apply to ONT too.

The problem you are reporting however is more one of reference bias in the aligner.  If the aligner cannot cope with IUPAC ambiguity codes, then you may find it's best to emit N in ambiguous locations so the aligner (most) is equally happy to align both A and T to that site.

Thanks for confirming that #1745 solves your original issue.

**Comment by trilisser** [comment]
Thank you very much! But can you please explain exactly how to use `-p` or `--P-indel` from #1733. Samtools doesn't recognize `--P-indel` while `samtools consensus`

**Comment by trilisser** [comment]
Thank you for such  full explanation. Does Nanopore have the same artifact? Also, in the third row of your example alignment, it looks like the third T should be gapped instead of the first T according the trajectory of probabilities, shouldn't?

> Samtools won't recognise --P-indel that option until it gets merged
What does "gets merged" mean? I'm sorry but I didn't find examples of `-p` or `--P-indel` using in #1733. And Do I understand correctly that `-p` is used with `samtools view`?
