### ISSUE TITLE
plot-bamstats 

### ISSUE THREAD

**Issue by putianhuizi** [samtools/samtools#1749]
Hi:
I use samtools 1.61
and gnuplot5.2

`Version 5.2 patchlevel 2    last modified 2017-11-15 

        Copyright (C) 1986-1993, 1998, 2004, 2007-2017
        Thomas Williams, Colin Kelley and many others

        gnuplot home:     http://www.gnuplot.info
        faq, bugs, etc:   type "help FAQ"
        immediate help:   type "help"  (plot window: hit 'h') 
        Terminal type is now 'x11'`
But I had this probolem when I ran " plot-bamstats -r gc -p ./test bamstat.txt "

"set terminal png size 600,400 truecolor
             ^
"./test-quals.gp", line 2: unknown or ambiguous terminal type; type just 'set terminal' for a list

The command exited with non-zero status 256:
        gnuplot ./test-quals.gp

 at /public/software/samtools-1.16.1/installed/bin/plot-bamstats line 51.
        main::error('The command exited with non-zero status 256:\x{a}\x{9}gnuplot ./test-...') called at /public/software/samtools-1.16.1/installed/bin/plot-bamstats line 336
        main::plot('./test-quals.gp') called at /public/software/samtools-1.16.1/installed/bin/plot-bamstats line 683
        main::plot_qualities('HASH(0x1d55df8)') called at /public/software/samtools-1.16.1/installed/bin/plot-bamstats line 33"

How could I sovle this issue? I tried to atteachd bamstat.txt here but it's too big(34Mb).
Thank you so much!

**Comment by daviesrob** [comment]
That version of `gnuplot` should be able to interpret the script made by `plot-bamstats`.  Are you using a system-installed gnuplot?  And what do you get of you run `gnuplot` and then type `set terminal` into it?  Among other possibilities listed, you should see this:
```
              png  PNG images using libgd and TrueType fonts
```

If it's not there, you need to look into why your copy of `gnuplot` doesn't have it.  If you built it yourself, then the most likely reason is [missing dependencies](https://stackoverflow.com/questions/22816030/terminal-png-missing-when-using-gnuplot).

**Comment by putianhuizi** [comment]
Thanks for comment. It did not have 'png' and need more development packages.
