### ISSUE TITLE
Secondary read missing when compared with IGV

### ISSUE THREAD

**Issue by robertzeibich** [samtools/samtools#1753]
I am missing the secondary read when I use samtools mpileup. Is there anything I can do about it? I also tried the --rf and --ff flag, but with no succress. Help is much appreciated. 

version: samtools/1.15.1 (I also tried version  v1.16.1 without success)

`samtools mpileup /scratch/xm41/ct/bams/GALF003.bam -f /scratch/xm41/hg38_resources/resources_broad_hg38_v0_Homo_sapiens_assembly38.fasta -r chr14:77027448-77027448 -A -Q 0`

[mpileup] 1 samples in 1 input files
chr14  77027448 C       27 ,,...-3TGT,.-3TGT..-3TGT,,,-3tgt,.-3TGT,.-3TGT....TTT.,,,    -6*=7*8*4**9*6!.!4!!!0(G'.!

`samtools mpileup /scratch/xm41/ct/bams/GALF003.bam -f /scratch/xm41/hg38_resources/resources_broad_hg38_v0_Homo_sapiens_assembly38.fasta -r chr14:77027448-77027448 -A -Q 0  --output-QNAME | cut -f7 | tr "," "\n"`

[mpileup] 1 samples in 1 input files
V300061512L1C004R0230338646
V300061512L2C003R0341378747
V300061512L1C002R0150409536
V300061512L2C006R0520606002
V300061512L2C004R0620773901
V300061512L2C003R0501096560
V300061512L4C001R0210361514
V300061512L2C004R0200795097
V300061512L3C001R0660916559
V300061512L1C003R0100817806
V300061512L1C004R0311225802
V300061512L1C002R0281090283
V300061512L2C006R0470879189
V300061512L1C003R0370129314
V300061512L3C004R0330244019
V300061512L2C005R0160434098
V300061512L3C003R0440743194
V300061512L3C005R0131034363
V300061512L4C001R0400032912
V300061512L2C005R0671220140
V300061512L2C006R0311008096
V300061512L3C005R0291194259
V300061512L2C002R0700039594
V300061512L3C003R0301026177
V300061512L2C004R0100131268
V300061512L3C003R0440743194
V300061512L3C005R0131034363

<img width="925" alt="secondary read IGV" src="https://user-images.githubusercontent.com/73748542/200727890-bf8a1541-9a05-4533-a589-e5771b86ff3d.PNG">

**Comment by jkbonfield** [comment]
See the mpileup usage, particularly `-ff` option:

```
  --ff, --excl-flags STR|INT  filter flags: skip reads with any of the mask bits set
                                            [UNMAP,SECONDARY,QCFAIL,DUP]
```

The default behaviour strips this data out, but you can re-enable them again with e.g. `-ff 0`.

**Comment by robertzeibich** [comment]
Thanks for the quick and helpful response. 
Much appreciated
Get the same result now.

**Comment by robertzeibich** [comment]
I got one more question regarding the --ff & --rf flag because now, I am getting somewhere else an unexpected output:

0 = UNMAP
1 = SECONDARY
2 = QCFAIL
3 = DUP

Is that correct?

**Comment by robertzeibich** [comment]
Hi, 

 

I just added another comment to the ticket. If you want me to open a new ticket, please let me know. 

 

Kind regards, 

Robert

**Comment by jkbonfield** [comment]
> I got one more question regarding the --ff & --rf flag because now, I am getting somewhere else an unexpected output:
> 
> 0 = UNMAP 1 = SECONDARY 2 = QCFAIL 3 = DUP
> 
> Is that correct? What does --ff 0 exactly mean or what does it do? I only want to include SECONDARY reads.

No, they are bit flags.

See the output from the `samtools flag` command for details.

```
$ samtools flag
About: Convert between textual and numeric flag representation
Usage: samtools flags FLAGS...

Each FLAGS argument is either an INT (in decimal/hexadecimal/octal) representing
a combination of the following numeric flag values, or a comma-separated string
NAME,...,NAME representing a combination of the following flag names:

   0x1     1  PAIRED         paired-end / multiple-segment sequencing technology
   0x2     2  PROPER_PAIR    each segment properly aligned according to aligner
   0x4     4  UNMAP          segment unmapped
   0x8     8  MUNMAP         next segment in the template unmapped
  0x10    16  REVERSE        SEQ is reverse complemented
  0x20    32  MREVERSE       SEQ of next segment in template is rev.complemented
  0x40    64  READ1          the first segment in the template
  0x80   128  READ2          the last segment in the template
 0x100   256  SECONDARY      secondary alignment
 0x200   512  QCFAIL         not passing quality controls or other filters
 0x400  1024  DUP            PCR or optical duplicate
 0x800  2048  SUPPLEMENTARY  supplementary alignment
```

**Comment by robertzeibich** [comment]
Thanks for the response. If I had "--ff UNMAP,DUP" that means that reads that are not mapped to the reference sequence and reads that are marked as duplicates are excluded and the remaining flags are included, e.g. SECONDARY. Is that correct? At least, the numbers seem correct now, I just want to make sure my interpretation is correct as well.

**Comment by jkbonfield** [comment]
Sorry for missing this question earlier.

These options can be a minefield for confusion, especially as they're not consistent between subcommands!  The usage for mpileup states: "skip reads with any of the mask bits set".  The key word there being `any`, which means `--excl-flags UNMAP,DUP` will skip the read if the `UNMAP` or `DUP` or both flags are set.

An example of confusion over terminology is `samtools view --excl-flags` which states "...have none of the FLAGs present".  A little bit of mental gymnastics reveals it's the same thing, but expressed in terms of what to keep instead of what to reject.  I rather wish we hadn't got to this position, but we are where we are.
