### ISSUE TITLE
Samtools 1.15.1 Incorrect Quality Scores for Overlapping Reads

### ISSUE THREAD

**Issue by jau2112** [samtools/samtools#1756]
#### Samtools Version
samtools 1.15.1

 #### Environment
- OS: Linux 3.10.0-1160.49.1.el7.x86_64
- machine architecture: x86_64
- compiler: gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-44)

#### Issue
I am running `samtools mpileup -f <reference> -s <.bam file>`
I did not specify the -x parameter, nor did I change the default -Q setting (bases with qualities < 13 should be skipped). So, Samtools mpileup should sum quality scores when overlapping paired-end reads agree on the same base, and return 0.8x(higher quality score) when they disagree. However, I found some positions where that is not happening and investigated with IGV, see IGV screenshots below:

Example 1: Both ends have a quality score of 37 according to IGV, so I would expect a combined quality score of 74 on the mpileup, but I see 66 (c=99, 99-33=66). 

![Screen Shot 2022-11-09 at 12 18 35 PM](https://user-images.githubusercontent.com/93164179/200897424-06974a9f-1dd1-475b-8cf1-7f449111dcf4.png)

![Screen Shot 2022-11-09 at 12 18 42 PM](https://user-images.githubusercontent.com/93164179/200897452-837062a6-814a-41d2-bd94-0905b5a3c7bf.png)

Example 2: Both ends have a quality score of 37 according to IGV, so I would expect a summed quality score of 74 on the mpileup, but I see 70 (g=103, 103-33=70).

![Screen Shot 2022-11-09 at 12 21 55 PM](https://user-images.githubusercontent.com/93164179/200898109-b7034fd1-91b9-487f-bf87-7824753e188f.png)

![Screen Shot 2022-11-09 at 12 22 03 PM](https://user-images.githubusercontent.com/93164179/200898134-16a5e510-bf29-488a-b0a9-630654e50b8b.png)

Example 3: mpileup should disregard the read with QV = 11, and sum the quality scores of the overlapping paired ends (37 according to IGV), so I should see a 74 on the mpileup, but I see 68 (e=101, 101-33=68).

![Screen Shot 2022-11-09 at 12 23 58 PM](https://user-images.githubusercontent.com/93164179/200898885-81287d22-9b1d-4640-9b06-bc2442ab04f9.png)

![Screen Shot 2022-11-09 at 12 24 20 PM](https://user-images.githubusercontent.com/93164179/200898949-73de6c39-688a-4293-b334-0c7bc01b297e.png)

![Screen Shot 2022-11-09 at 12 25 00 PM](https://user-images.githubusercontent.com/93164179/200898970-456652e7-56d5-4fae-af5d-cdb2ea8afa4e.png)

Does anyone know what is happening here?

**Comment by jkbonfield** [comment]
> I am running `samtools mpileup -f <reference> -s <.bam file>` I did not specify the -x parameter, nor did I change the default -Q setting (bases with qualities < 13 should be skipped). So, Samtools mpileup should sum quality scores when overlapping paired-end reads agree on the same base, and return 0.8x(higher quality score) when they disagree. However, I found some positions where that is not happening and investigated with IGV, see IGV screenshots below:

I suspect you do need to specify `-x`.  The (old) long option for this was `--ignore-overlaps`, but that's a very misleading parameter.  I can't blame people for thinking this code ignores data from overlapping reads.  However what it does is *disable* the inbuilt code that ignores data from overlapping reads, so it's doing the opposite to what the long option implies.

In 1.16 we expanded the long-opt and usage to try and clarify this, but can't really change it completely as people have scripts assuming the arguments work as always:

```
  -x, --ignore-overlaps-removal, --disable-overlap-removal
                          disable read-pair overlap detection and removal
```
