### ISSUE TITLE
samtools coverage number of read

### ISSUE THREAD

**Issue by natchaphon602** [samtools/samtools#1757]
I would like to know that samtools coverage number of reads "Number reads aligned to the region (after filtering)" meaning. What's the different between samtools coverage -r vs samtools view -c with gene region?

**Comment by jkbonfield** [comment]
Look at the usage statements for both commands and you'll see some differences.

```
Usage: samtools coverage [options] in1.bam [in2.bam [...]]
...
  --ff <int|str>          filter flags: skip reads with mask bits set 
                                      [UNMAP,SECONDARY,QCFAIL,DUP]


Usage: samtools view [options] <in.bam>|<in.sam>|<in.cram> [region ...]
  -F, --excl[ude]-flags FLAG ...have none of the FLAGs present
```

There's no default specified for `view -F`, but that's because it filters nothing until specified.

I suspect this is the reason why you are getting a difference in count.
