### ISSUE TITLE
split: use custom tag

### ISSUE THREAD

**Issue by ScottNortonPhD** [samtools/samtools#1758]
#### Is your feature request related to a problem? Please specify.
Currently `samtools split` only splits by tag `RG`, however there may be situations where you'd want to split by a different tag. Example: after soft-demultiplexing an experiment, you align all the reads using STAR, which overwrites tag `RG`.

#### Describe the solution you would like.
Add a new argument `-t ##` to split by the value of the specified tag. Support only tags with integer or string type.

Alternatively: Add a new argument to split by an expression `-e`. In this formulation, `samtools split -e '[XX]'` would be equivalent to `samtools split -t XX`, but using expressions allows for greater flexibility. `samtools split -e '[XX] + "_" + [YY]'` would concatenate the values of tags XX and YY, and use that as the split key.

**Comment by daviesrob** [comment]
This should be possible, but would need a bit of rework inside `split`.  At the moment it looks in the header for `@RG` records and opens an output file for each one.  If it allowed other tags it wouldn't be able to find the file names in advance, so opening would have to happen later as it was going through the data.

There could also be issues with trying to open too many files at once if the tag has lots of different values.  As a first pass we could just give up if that happens, but it might be possible to work around the issue by sorting on the chosen tag so we know each output file can be closed when a new value turns up.

**Comment by valeriuo** [comment]
Maybe some of PR https://github.com/samtools/samtools/pull/1222 can be reused.

**Comment by daviesrob** [comment]
@valeriuo Possibly, yes.
