### ISSUE TITLE
Samtools tview showing more reads than samtools view

### ISSUE THREAD

**Issue by LucasSilvaFerreira** [samtools/samtools#1759]
Why __samtools tview__ is generating more reads than my .bam file total number (inspected using samtools view)?

<img src='https://raw.githubusercontent.com/LucasSilvaFerreira/biodf/main/bam%20aligment%20atac%20bcl11a%20.ipynb%20-%20Colaboratory.png'>

Is that a known bug?
When I visualize the same file on IGV it shows 6 reads .

Thanks

====specs=====
samtools 1.3
Using htslib 1.3
Copyright (C) 2015 Genome Research Ltd.
Linux 5.10.133+
x86_64
gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0

**Comment by jkbonfield** [comment]
That's 6 reads in tview.  Reference, consensus, 6 sequences.

I would say "read the manual", but I just did...  It's, umm, terse!  One for us to improve I think.

**Comment by LucasSilvaFerreira** [comment]
Thank you a lot. I agree, a  few samtools tools have a documentation less comprehensive (peharps the less frequently used tools) and I think the  tview -s parameter is lacking some explanation as well (  Maybe a example).  But again . Thanks for fast replying
