### ISSUE TITLE
samtools index with large chromosomes (>512mb)

### ISSUE THREAD

**Issue by JeremyLGauthier** [samtools/samtools#1761]
#### Is your feature request related to a problem? Please specify.
Dear samtools team,

What is the solution proposed by samtools to index mapping bam on chromosomes larger than 512mb ?
The classic set of tools for filtering mapping such as picard, gatk etc. do not support the .csi format.
I've looked everywhere and I can't find any solution...

With the growing number of genomes being assembled at the chromosome level, this is going to be a real problem...

#### Describe the solution you would like.
?

**Comment by jkbonfield** [comment]
The BAI index simply cannot cope with >512MB chromosomes.  So there really are only two choices I can see:

1. Switch to CSI and encourage htsjdk to start supporting it.  (Maybe by modifying it and making a PR if necessary)
2. Give up and articifically break the chromosome into fragments.

Neither is particularly palatable, but there's little that the samtools team can do to address the short-comings of other packages.

**Comment by valeriuo** [comment]
[Picard](https://github.com/broadinstitute/picard/releases?q=csi&expanded=true) and [HTSJDK](https://github.com/samtools/htsjdk/releases?q=csi&expanded=true) should support CSI indices.

**Comment by jkbonfield** [comment]
My apologies for forgetting about this Valeriuo.  Of course there was a third choice, which you've already taken:

3. Make the change to htsjdk and submit a PR.

Thank you!

To @JeremyLGauthier - the solution therefore is to upgrade htsjdk and siblings.  I can't guarantee GATK will cope with them, but in theory it's just building on top of htsjdk so I'm hoping it already supports them (bar perhaps some trivial code looking for filenames?).

**Comment by JeremyLGauthier** [comment]
Ok I'll test this! Thanks a lot !
