### ISSUE TITLE
about flagstat

### ISSUE THREAD

**Issue by ye00ye** [samtools/samtools#1762]
#### Is your feature request related to a problem? Please specify.
Hello. 

        when i use samtools flagstat to detect HiFi metagenomic data, i found a problem that the number of sequences flagstat found is 1162, but the number of my sequence inputed is 1144. So i want to know why. 

thanks for your help

1162 + 0 in total (QC-passed reads + QC-failed reads)
2 + 0 secondary
16 + 0 supplementary
0 + 0 duplicates
974 + 0 mapped (83.82% : N/A)
0 + 0 paired in sequencing
0 + 0 read1
0 + 0 read2
0 + 0 properly paired (N/A : N/A)
0 + 0 with itself and mate mapped
0 + 0 singletons (N/A : N/A)
0 + 0 with mate mapped to a different chr
0 + 0 with mate mapped to a different chr (mapQ>=5)

**Comment by jkbonfield** [comment]
Well 1162 - 1144 is 18.  That's 2 secondary + 16 supplementary, as reported by flagstats.

**Comment by jkbonfield** [comment]
Also note if you try Samtools 1.13 or newer it would have an additional line:

```
1144 + 0 primary
```

Please consider upgrading too.

**Comment by ye00ye** [comment]
Now I know why, thanks for your help. 


| |
ye--ye
|
|
***@***.***
|
---- Replied Message ----
| From | James ***@***.***> |
| Date | 11/28/2022 18:06 |
| To | ***@***.***> |
| Cc | ***@***.***> ,
***@***.***> |
| Subject | Re: [samtools/samtools] about flagstat (Issue #1762) |

Also note if you try Samtools 1.13 or newer it would have an additional line:

1144 + 0 primary


Please consider upgrading too.
