### ISSUE TITLE
Problem: samtools view: failed to add PG line to the header

### ISSUE THREAD

**Issue by jeromeRlon** [samtools/samtools#1764]
Hi! 

When I use the command: 

 samtools view -h -b $i_index.main.sam -o $i_index.main.bam

the system reported that: 

......

[W::sam_hdr_create] Duplicated sequence "A01224:326:H5TCKDSX3:2:2678:18506:23096" in file "R0001.1.sam.main.sam"
[W::sam_hdr_create] Duplicated sequence "A01224:326:H5TCKDSX3:2:2678:28591:35471" in file "R0001.1.sam.main.sam"
[E::sam_hrecs_update_hashes] Duplicate entry "A01224:326:H5TCKDSX3:2:1101:26076:5490" in sam header
samtools view: failed to add PG line to the header

Is there anything wrong with my .sam files?

**Comment by whitwham** [comment]
Do your alignments read names start with a `@`?

**Comment by jeromeRlon** [comment]
> 

It seems yes. 

But I' m not sure. 

My .fq file like this, which reported error after bowtie2: 

@A01224:326:H5TCKDSX3:2:1101:7469:26660 1:N:0:CCTCTATC
CTTGTCCTGCAATGGATTTGCTACTGGCAGGGCCGCTACAATCACATATCTTGATGAAGATTCCAAAGTTATAAATTTGAGACATGTTTTTAAAACTTTTTCAAACTTAGAACAAAGAGTAGCCCTTCCGGCATCACCAGGAACAAGTAC
+
FFFFFFFFFFFFFFFFFFFFFFFFFFF#FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF,FFFFFFFFFFFFFFFFFFFFF:FFFFFFFFFFFFFFFFFF

Since another .fq file works: 

@SRR7411414.1.1 1 length=122
TGCAAATGAGTATGGAATCATACTAATTAAATTAGCAATAAAAATAAACATAAATAATGTAAAGATCATAGGGAAATATAAACCTCAATTTTTACCTCCAATTTGTCCTTTAAGCATATTTA

**Comment by whitwham** [comment]
Any line that starts with a `@` gets treated like as a header and so will not be treated as a valid SAM file.

It has been a long time since I have used bowtie2, I have no idea why it is not working properly.  At first glance your FASTQ entries look okay though.

**Comment by jeromeRlon** [comment]
My .sam files looks like this: 

@HD	VN:1.5	SO:unsorted	GO:query
@SQ	SN:A01224:326:H5TCKDSX3:2:1101:26076:5490	LN:150
@SQ	SN:A01224:326:H5TCKDSX3:2:1101:26076:5490	LN:150
@SQ	SN:A01224:326:H5TCKDSX3:2:1101:4923:12068	LN:150
@SQ	SN:A01224:326:H5TCKDSX3:2:1101:4923:12068	LN:150
@SQ	SN:A01224:326:H5TCKDSX3:2:1101:24920:16986	LN:150
@SQ	SN:A01224:326:H5TCKDSX3:2:1101:24920:16986	LN:150
@SQ	SN:A01224:326:H5TCKDSX3:2:1101:5860:1772	LN:150
@SQ	SN:A01224:326:H5TCKDSX3:2:1101:5860:1772	LN:150
@SQ	SN:A01224:326:H5TCKDSX3:2:1101:6920:18784	LN:150
@SQ	SN:A01224:326:H5TCKDSX3:2:1101:6920:18784	LN:150
@SQ	SN:A01224:326:H5TCKDSX3:2:1101:26569:5924	LN:150
@SQ	SN:A01224:326:H5TCKDSX3:2:1101:26569:5924	LN:150
@SQ	SN:A01224:326:H5TCKDSX3:2:1101:7301:10918	LN:150

I don't know why it can not be added with PG lines.

**Comment by jeromeRlon** [comment]
Is that something wrong about the "Duplicated sequence" or "Duplicate entry" ?

Normally, the system would not report much information, just about files merging.

**Comment by whitwham** [comment]
That is wrong, `@SQ` lines in the header should be the references and those are query (read) names.

When you used bowtie2 did you give it a proper reference to map your FASTQ files against?

**Comment by whitwham** [comment]
Also, that is why it failed.  You cannot have two (or more) identically named references.

**Comment by jeromeRlon** [comment]
I created a .fa file from the .fq files by sequencing the original strain before evolution. 

Maybe I could try with the original strain. 

Thanks a lot

**Comment by whitwham** [comment]
Are you trying to compare two lots of reads directly?  One lot from the original strain and one from the evolved strain?

**Comment by jeromeRlon** [comment]
No. 

I created the fasta file from the sequence file of the one before evolved strain and make it a reference with the bowtie2. 

Then I compared them.

**Comment by whitwham** [comment]
When you created the fa file did you remember to take off the `@` symbols which are part of the fq format and not part of the read name?

**Comment by jeromeRlon** [comment]
Sure. I checked the fa file again, there is no @ symbol.

**Comment by jeromeRlon** [comment]
I see. Now I know the problem. 

Thanks a lot!

**Comment by kunaljaani** [comment]
Hi!
I am also facing a similar problem, could you please suggest some fix?
Thank you 

`Converting SAM to BAM with samtools view ...
[W::sam_hdr_create] Duplicated sequence "NODE_1753_length_683_cov_1.602310" in file "FDSGM6.sam"
[E::sam_hrecs_update_hashes] Duplicate entry "NODE_1753_length_683_cov_1.602310" in sam header
samtools view: failed to add PG line to the header
`

**Comment by jkbonfield** [comment]
What makes you believe it's not correct?  Have you tried grepping for "NODE_1753_length_683_cov_1.602310" to see if there really are two header entries with the same name?  I suspect your input data to be invalid.

**Comment by kunaljaani** [comment]
Yes, tried using grep and found that there are more than one occurrences. But I am also surprised to see except for 2 samples all my samples ran through successfully. I am using [metaGEM pipeline](https://github.com/franciscozorrilla/metaGEM) which uses sam to bam at various intermediate steps. and this is the last step of the pipeline, if there was some issue it would have created problems earlier and for all the samples. So I am not able to figure out the issue. Could you please suggest some checks and solutions?
