### ISSUE TITLE
Comparison of different variant callers

### ISSUE THREAD

**Issue by robertzeibich** [samtools/samtools#1766]
I would like to evaluate the performance of different variant callers based on the BAM file. 

I saw that you can use samtools to get a strand bias score. Is that function still available in the current release? I somehow was not able to find the option. 
Is there also an automated way to identify whether a specific position in a BAM file is or isn't a potential variant? Is there a kind of score I could use? I do not want to use IGV to evaluate variants manually. 

I was also able to generate the following plot ...

![image](https://user-images.githubusercontent.com/73748542/205888221-57d0fa1e-4987-48e1-a273-99241bd66dfe.png)

... and looked at different statistical test (fisher's exact test, SB, SB-GATK, binomial test), but somehow I am still not able to determine whether the position in a BAM file contains a valid variant or not. If you have an idea or could point me in the right direction, I would highly appreciated it.

**Comment by jkbonfield** [comment]
This sounds more like the various FORMAT fields added by `bcftools mpileup`.  Note it doesn't matter whether `bcftools call` chooses to call a variant or not, the mpileup input contains a bunch of fields for various statistical tests, counts of REF, ALT, etc.
(Samtools used to have this functionality but it was incorporated into bcftools instead).

Maybe @pd3 can answer the specifics.

**Comment by pd3** [comment]
That's correct, `bcftools mpileup` adds annotations like Fisher's test (made functional again only recently by https://github.com/samtools/bcftools/commit/83dba37e8ad552c7b53a8f2d218b1148e6f870f3), `bcftools call` then performs the calling, see for example here http://samtools.github.io/bcftools/howtos/variant-calling.html.

However, the broader question how to recognize a valid variant is impossible to answer here I am afraid. It's a complex problem, there is lot of noise in the data, sequencing, mapping and alignment artifacts. One has to perform some type of filtering and make compromises to achieve the desired level of sensitivity vs specificity.
