### ISSUE TITLE
Issue creating reference index with faidx : format error?

### ISSUE THREAD

**Issue by sarakn97** [samtools/samtools#1783]
Hello,

I made the following reference fasta file (amplicons.fa) with only two sequences: 

```
>BALV3loop
GTACAAGACCCAACAACAATACAAGAAAAAGTATAAATATAGGACCAGGCAGAGCATTTTATACAACAGGAGAAATAATAGGAGATATAAGACAAGCACATTGTAACCTTAGTAGAGCAAAATGGAATGACACTTTAAATAAGATAGTTATAAAATTAAGAGAACAATTTGGGAATAAAACAATAGTCTTTAAGCACTCCTCAGGAGGGGACCCAGAAATTG
>NL4-3V3loop
GTACAAGACCCAACAACAATACAAGAAAAAGTATCCGTATCCAGAGGGGACCAGGGAGAGCATTTGTTACAATAGGAAAAATAGGAAATATGAGACAAGCACATTGTAACATTAGTAGAGCAAAATGGAATGCCACTTTAAAACAGATAGCTAGCAAATTAAGAGAACAATTTGGAAATAATAAAACAATAATCTTTAAGCAATCCTCAGGAGGGGACCCAGAAATTG
```
I am trying to index the reference to run "alfred qc" on my aligned reads with the following command:

```
samtools faidx amplicons.fa 
```
I get the following error:

```
[E::fai_build_core] Format error, unexpected character at line 1
[faidx] Could not build fai index amplicons.fai
```

I am not sure what could be wrong as the reference headers are named correctly according to my knowledge. 
Any help would be appreciated.

Sara

**Comment by whitwham** [comment]
That's interesting, faidx only prints that out when it comes across an unprintable character.

What exactly is in line 1 of your file?

**Comment by jkbonfield** [comment]
Specifically it rejected the file due to something unprintable, eg a nul char.  That may not show up on a file `cat` and whatever it was it didn't cut and paste over to this issue.

You may want to try something like `cat -v amplicons.fa` or use `hd` to show to raw data.

**Comment by sarakn97** [comment]
Thank you! 

using '-v' showed the issue:
```
M-oM-;M-?>BALV3loop
GTACAAGACCCAACAACAATACAAGAAAAAGTATAAATATAGGACCAGGCAGAGCATTTTATACAACAGGAGAAATAATAGGAGATATAAGACAAGCACATTGTAACCTTAGTAGAGCAAAATGGAATGACACTTTAAATAAGATAGTTATAAAATTAAGAGAACAATTTGGGAATAAAACAATAGTCTTTAAGCACTCCTCAGGAGGGGACCCAGAAATTG
>NL4-3V3loop
GTACAAGACCCAACAACAATACAAGAAAAAGTATCCGTATCCAGAGGGGACCAGGGAGAGCATTTGTTACAATAGGAAAAATAGGAAATATGAGACAAGCACATTGTAACATTAGTAGAGCAAAATGGAATGCCACTTTAAAACAGATAGCTAGCAAATTAAGAGAACAATTTGGAAATAATAAAACAATAATCTTTAAGCAATCCTCAGGAGGGGACCCAGAAATTG
```

**Comment by jkbonfield** [comment]
This is the UTF-8 Byte Order Mark (https://en.wikipedia.org/wiki/Byte_order_mark#UTF-8).

I'm assuming this was some Windows-ism, but anyway glad to see you've resolved things.
