### ISSUE TITLE
samtools sort fails if multiple sorts are run in in parallel in the same directory

### ISSUE THREAD

**Issue by diekhans** [samtools/samtools#1784]
#### Are you using the latest version of [samtools](https://github.com
samtools 1.15.1
Using htslib 1.15.1

 #### Please describe your environment.
- OS Linux 3.10.0-1160.53.1.el7.x86_64
- machine architecture x86_64
- compiler gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-44)

#### Please specify the steps taken to generate the issue, the command you are running and the relevant output.

run two sorts in the background in the same file and get the error:

[E::hts_open_format] Failed to open file "BAM.tmp.0000.bam" : File exists

**Comment by diekhans** [comment]
Related to #1172, generally this is problematic handling of tmp files

**Comment by jkbonfield** [comment]
What are your exact commands your are running?

By default the temp filenames are named after the output filename, so assuming you have multiple sorts outputting to different filenames then the temp files won't clash.

If you have multiple sorts running in the same dir outputting to stdout, then you may get issues.  However you can change the tmp filename prefix with `-T` in this case.

**Comment by jkbonfield** [comment]
The only way I can get this to fail is explicitly specifying the same `-T` parameter on multiple sorts.  However note that the T opt is a prefix, not a directory:

```
  -T PREFIX  Write temporary files to PREFIX.nnnn.bam
```

So using the same parameter multiple times is misuse.

However... I can see that the user may not actually care about such trivialities.  So if you do specify a directory, with no filename prefix component, it'll switch to generating unique filenames via a PID.

**Comment by diekhans** [comment]
Hi James!!

-T was not used, however it was in a unix pipeline, so there was no file name.
So it generated names like SAM.* 

What if someone wanted to sort the same file in parallel; by
position and once by name?

Seems honoring TMPDIR and following posix tmp file generation would fix
several cases.

**Comment by jkbonfield** [comment]
I couldn't reproduce your problem, as with pipes it was generating unique names still.

However I chatted with @daviesrob earlier and he informs me this has been changed quite a bit recently anyway, so the next release may have already improved on this by using the appropriate unix functions that guarantee filename uniqueness.

**Comment by diekhans** [comment]
Oh, I think I am one release behind.  I will update and experiment.

**Comment by jkbonfield** [comment]
I think the code new temp Rob was referring is in develop and not a released version yet, but yes it's always best to try the current release when making a bug report.

The issue of sorting the same file with pos and name output, if the output filename is specified and they differ, then this isn't a problem as temp files will be named after the output.  If the outputs are stdout, then it produces samtools.<pid>.<timestamp>.NNNN.bam which is very unlikely to clash.

I'm still curious exactly what commands you are running as try as I may I cannot get this to fail.

**Comment by diekhans** [comment]
I will try to reproduce on the latest later this week...

**Comment by diekhans** [comment]
I am going to close this because now I can't find the case that caused it to fail.  Maybe it was multiple user errors ..

I will reopen if I reproduce it cleanly.
