### ISSUE TITLE
Dynamic mismatches for long reads

### ISSUE THREAD

**Issue by colindaven** [samtools/samtools#1789]
#### Is your feature request related to a problem? Please specify.

In metagenomic alignments, I would like to filter by mismatches (NM tag). This works great for short reads with a constant read length. 

For long reads, I see read lengths from <500 to >50kbp + .

I would like to configure a `dynamic `read length filter, say 10% of total read length. This is obviously not globally configurable per read file, but must be calculated per read, i.e. 10% of 500 or 10% of 50000. Is this possible with samtools ?

#### Describe the solution you would like.

Is there a solution to this in samtools as already implemented ? 

Thanks
Colin

**Comment by jkbonfield** [comment]
The expression language may fit the bit.  Either of these:

```
samtools view -e '[NM]/length(seq) < 0.1'
samtools view -e '[NM]/sclen < 0.1'
```

The latter is soft-clipped length, although you may want a small size correction in there to handle the tiny sequences post-clipping.

**Comment by jkbonfield** [comment]
Closing as a question, with an answer.
