### ISSUE TITLE
Consensus Quality

### ISSUE THREAD

**Issue by AlsoATraveler** [samtools/samtools#1790]
According to the samtools pileup results，how is Consensus Quality obtained? What does its value mean? In addition, is the greater the SNP quality, the better?

**Comment by jkbonfield** [comment]
For simple mode, it's basically just a ratio of agreement.  Higher is better.

For the default Bayesian mode, it's broadly speaking a phred-scaled quality value, but not calibrated.  So as the number gets higher, the likelihood of it being incorrect decreases exponentially.  In theory anyway.

In both cases, if the quality drops below the specified threshold, it'll emit an "N" in the consensus instead and give quality 0.

The actual algorithm is complex and it's had further tweaks for the up-coming 1.17 release.  It's not designed to be a full replacement for variant callers, and in particular it doesn't have a built-in realignment step which will harm the quality.  (I may consider this as a standalone separate tool though.)  However tests show it's still reasonably accurate (occasionally more so than proper variant callers).  Good enough for most cases.

**Comment by AlsoATraveler** [comment]
Thanks.
