### ISSUE TITLE
Documentation for samtools fasta/q extraction involving clipped reads?

### ISSUE THREAD

**Issue by rlorigro** [samtools/samtools#1792]
Hi,

I have been reading through the manual for [samtools fasta](http://www.htslib.org/doc/samtools-fasta.html) and there is no mention of clipping in the document. Could anyone clarify what happens with hardclipped reads? Especially in the case where I would like to extract a full length read from a supplementary alignment.

Thanks

**Comment by jkbonfield** [comment]
If it's a hard clipped read then quite obviously there's no way we can ressurect the missing bases as, well, they're missing!  So I'm not really sure what you're asking for here.

However generally hard clipping is only used for secondary and/or supplementary reads, which aren't output by default for fasta/fastq as they're duplicated in their primary alignments.  (See the documentation for `-F`.)

**Comment by rlorigro** [comment]
Thank you, this is exactly the information I was looking for. I don't think it is totally obvious though, and it would be convenient if it was mentioned in the samtools documentation somewhere. The description, "Converts a BAM or CRAM into either FASTQ or FASTA" is the extent of what is written about this program's behavior regarding unpaired alignments, and considering that long reads are becoming more common, I think this behavior with clipped alignments is fairly useful to understand.

**Comment by jkbonfield** [comment]
Well, "Converts a BAM or CRAM into either FASTQ or FASTA" is the first sentence, but then it's got 171 lines worth of text in the man page so it's a little unfair to claim that's the extent of it.  It also has several paragraphs covering paired vs single ended data.  If there is a specific sentence you wish to be amended, then please make a suggestion.

I will however look at adding something about read clipping.

Also, for long reads, I'm not aware of any long read aligners that do hard clipping on the *primary* alignment.  I think perhaps the misunderstanding here, which is something I'll look at addressing, is `samtools fastq` is attempting to undo the alignment process and go from aligned BAM et al to original style FASTQ.  It's definitely not attempting to create one FASTQ record per SAM record.  I think this is probably where the confusion is arising.

That means if a read aligns in many places, creating supplementaries and/or secondaries, then once it's converted back to FASTQ there will once again only be a single record - as the machine originally produced.  Hence it doesn't need to do anything magic with clipping anyway.

**Comment by rlorigro** [comment]
Thanks for the update. To explain more about my use case, and why I asked this: I am hoping to fetch long reads from a specific region in the BAM, and I cannot guarantee that all the alignments in that region are the primaries (non-supplementary), and as a result some of the alignments are almost definitely hardclipped. However I was hoping that, in a particular region, the `samtools fasta` behavior would still be as you described, reproducing the full sequence of each read involved. But I would need to reproduce the reads that had supplementaries in the subregion too, because they can contain important information for structural variation relative to the reference. I understand that this is not possible with the hardclipped reads alone, but I was hoping there was a mechanism to seek to other alignments in the BAM which contain the full sequence for each read, before outputting them. The alternative solution requires gathering read IDs and then using a separate FASTA and index to fetch the reads, which is straightforward, but not strictly necessary assuming that the BAM actually contains the full sequence somewhere in it.

**Comment by jkbonfield** [comment]
It's quite a complex thing to do, as the data simply doesn't exist.  Fundamentally if you're pulling data for a specific region, then the only data you can work off is the data returned for that region.   We discussed this scenario yesterday and I was hoping `samtools view --fetch-pairs` code would also trigger fetching of primary alignments off any supplementary (as it does for the "other" primary alignments off an existing primary alignment), but apparently that's not the case and I was told it wasn't an easy fix.

Some aligners however have options controlling whether they do hard-clipping vs soft-clopping in supplementary alignments, so that may be a route forward.  Otherwise all I could suggest is some manual code that parses the SA tags to return a list of regions to query, and do it via some homebrew scripting.

**Comment by rlorigro** [comment]
I see, the softclip-only route is probably the easiest. Though I could imagine a 100Kbp read (if using ONT) having many supplementaries, which could explode the BAM file size. So we can revert to the read-ID-to-Fasta method. Thanks again for the added documentation
