### ISSUE TITLE
Is there a way to limit @SQ tags to references having a hit?

### ISSUE THREAD

**Issue by bistace** [samtools/samtools#1793]
Hello and thank you for developing Samtools,

I work in metagenomics and I have aligned RNA-seq transcripts to a very large gene catalog (several hundred million) with Minimap2. The resulting problem is that the header of the SAM file contains several hundred million lines in turn, please take a look at this:
```
samtools view -H my.sam | wc -l
259896615
```

To overcome this problem, I first align the transcripts to the entire catalog and then extract the references with a hit. I then gather these sequences in a single FASTA which I use for a second alignment. This procedure allows to reduce the size of the SAM headers but is problematic in terms of computation time since I have to do two alignments while I have hundreds of samples.

Would you see a way for me to limit the size of the SAM headers to the references that have a match?

**Comment by bistace** [comment]
Just to clarify my request, I know that the alignments contained in a BAM file do not directly contain the name of the reference but an index corresponding to an @SQ line. 

My question is more about whether you knew of any tools to reformat the BAM with a new header and alignments with the correct @SQ index.

**Comment by daviesrob** [comment]
That's a lot of references.  Unfortunately BAM limits the size of the header to 2³¹ bytes, which can cause problems when you have a lot of `@SQ` lines.  `samtools` however has more generous limits if you're using the `SAM` or `SAM.gz` formats and have enough memory - with a big enough machine you can get up to 2³¹ references.  This is why your `samtools view -H` worked above.  Unfortunately not all tools (and possibly some samtools subcommands) will be so accommodating so it would be useful to limit the size of the header.

To answer your specific question, there's no direct way to do this with `samtools`, but you can use some standard UNIX tools to make a new file with a reduced list of references.  You need to use a SAM file as input, and have to read it a few times so you can't read from a pipe.  For example:

```
# Get the list of references used
awk '!/^@/ && $3 != "*" { print "SN:" $3 }' test/dat/view.001.sam | sort -u > /tmp/refs_used
# Output non-@SQ headers, then the filtered @SQ ones, then the rest of the data
( awk '/^@/ && !/^@SQ/ { print } !/^@/ { exit }' test/dat/view.001.sam ; awk '/^@SQ/ { print } !/^@/ { exit }' test/dat/view.001.sam | grep -w -f /tmp/refs_used ; grep -v '^@' test/dat/view.001.sam ) > /tmp/out.sam
```

You could alternately use `samtools reheader` for the second part, although it would need more memory as it would want to read in the entire original header before applying the replacement.  You'd probably want to save the replacement header somewhere for it to use, so there's not much advantage compared to the example above.

Alternatively you could reduce the number of `@SQ` lines by concatenating some of the transcripts together, separated by sufficient 'N's to prevent `minimap2` from mapping across the joins.  It wouldn't be particularly pretty as you'd nee to track where each original reference ended up in the combined ones, but it might get the job done.

**Comment by bistace** [comment]
Thanks a lot for your fast and detailed answer, I will try your solution and report back to you!

**Comment by bistace** [comment]
It worked like a charm! I just modified a bit the awk and grep part, as grep without `-F` was filling the RAM. Here is what I did:
```
awk '/^@/ && !/^@SQ/ { print } !/^@/ { exit }' my.sam > my.formatted.sam
awk '/^@SQ/ { print } !/^@/ { exit }' my.sam | grep -F -w -f my_ref_names.txt >> my.formatted.sam
grep -v '^@' my.sam >> my.formatted.sam
```
