### ISSUE TITLE
error in samtools sort: truncated file. 

### ISSUE THREAD

**Issue by AnduinIs** [samtools/samtools#1810]
``#### Are you using the latest version of [samtools](https://github.com/samtools/samtools/releases/latest) and [HTSlib](https://github.com/samtools/htslib/releases/latest)? If not, please specify.
(run `samtools --version`)
I am using samtools in docker to build snakemake workflow.
`docker run -it --rm -v {project_dir}:{project_dir} -w {project_dir} staphb/samtools:1.16.1`

 #### Please describe your environment.
- OS (run `uname -sr` on Linux/Mac OS or ` wmic os get Caption, Version` on Windows)
- machine architecture (run `uname -m` on Linux/Mac OS or ` wmic os get OSArchitecture` on Windows)
- compiler (run `gcc --version` or `clang --version`)
`staphb/samtools`
#### Please specify the steps taken to generate the issue, the command you are running and the relevant output.

``
rule sam_to_bam:
    input:
        "{project_dir}/{trail_accession}.sam"
    output:
        "{project_dir}/sam_to_bam_{trail_accession}.bam"
    threads: 4
    shell:
        "docker run -it --rm -v {project_dir}:{project_dir} -w {project_dir} staphb/samtools:1.16.1 samtools view -S -h -b {input} > {output}"
        
rule sort:
    input:
        "{project_dir}/sam_to_bam_{trail_accession}.bam"
    output:
        "{project_dir}/{trail_accession}_sorted.bam"
    threads: 4
    shell:
        "docker run -it --rm -v {project_dir}:{project_dir} -w {project_dir} staphb/samtools:1.16.1 samtools sort -@ 4 -m 8G {input} -o {output}"
``

I use samtools quickcheck to check the input and output of rule sam_to_bam.
And it shows the` /home/ubuntu/sam_to_bam_SRR2589044.bam could not be opened for reading`
while /home/ubuntu/SRR2589044.bam return with 0 code. I think it might mean the problem origin from the rule sam_to_bam.
What should I do to check the process of it and get the right bam file?

**Comment by AnduinIs** [comment]
Plu, when I try to run the whole snakemake file. It reports error in sort:
`[E::bgzf_uncompress] Inflate operation failed: invalid distance too far back
[E::bgzf_read] Read block operation failed with error 1 after 0 of 4 bytes
[E::bam_hdr_read] Invalid BAM binary header
samtools sort: failed to read header from "/home/ubuntu/sam_to_bam_SRR2584866.bam"`
I have been searching for similar question but rare information really upsets me.

**Comment by daviesrob** [comment]
Could `docker run` be writing anything to `stdout`?  If it does, the text would be mixed up with the output of `samtools view` which is likely to result in an unreadable file.  You could test this by using the `samtools view` `-o` option to specify the output file, i.e. change:
```
"docker run -it --rm -v {project_dir}:{project_dir} -w {project_dir} staphb/samtools:1.16.1 samtools view -S -h -b {input} > {output}"
```
to:
```
"docker run -it --rm -v {project_dir}:{project_dir} -w {project_dir} staphb/samtools:1.16.1 samtools view -S -h -b -o {output} {input}"
```

**However**, you don't actually need to run `samtools view` at all.  `samtools sort` will quite happily read your `sam` file as-is, so you can drop `rule sam_to_bam` and just do this:

```
rule sort:
    input:
        "{project_dir}/{trail_accession}.sam"
    output:
        "{project_dir}/{trail_accession}_sorted.bam"
    threads: 4
    shell:
        "docker run -it --rm -v {project_dir}:{project_dir} -w {project_dir} staphb/samtools:1.16.1 samtools sort -@ 4 -m 8G -o {output} {input}"
```
which will save the space needed to store the intermediate file, and run faster as well.
