### ISSUE TITLE
samtools view creates duplicate lines when extracting reads from HLA-* contigs

### ISSUE THREAD

**Issue by jensreeder** [samtools/samtools#1819]
#### 

I am seeing  some unexpected behavior when trying to extract reads using samtools view  that are mapping to the HLA alleles from a cram file created using  an ALT aware bwa in a functional equivalence pipeline using the Broad's GRCh38_full_analysis_set_plus_decoy_hla.fa . The same read, that appears only once in the source cram is printed many times, more often if I include certain other HLA contigs in the bed query.

I am running
```
$ samtools --version
samtools 1.17
Using htslib 1.17
```

My test file is a 30x whole genome cram file:
```
$ ls -lh test.cram
-rw-r--r-- 1 reederj Bioinfo 16G Mar 27 21:19 test.cram
```
Let's start by using a single region in a bed file and look at just a single read that falls into that region:
```
$ cat one_region.bed 
HLA-A*01:03 0   3503
$ samtools view --regions-file one_region.bed -T GRCh38_full_analysis_set_plus_decoy_hla.fa test.cram  | grep "H2CGNDSX2210503:1:2309:15393:10958" 
H2CGNDSX2210503:1:2309:15393:10958	97	HLA-A*01:03	528	0	151M	chr6_GL000251v2_alt	1422510	0	TCACATCCGTGTCCCGGCCCGGCCGCGGGGAGCCCCGCTTCATCGCCGTGGGCTACGTGGACGACACGCAGTTCGTGCGGTTCGACAGCGACGCCGCGAGCCAGAAGATGGAGCCGCGGGCGCCGTGGATAGAGCAGGAGGGGCCGGAGTA	???????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????	MC:Z:151M	MQ:i:0	AS:i:151	MD:Z:151	NM:i:0	RG:Z:H2CGN.1
```

We see this one read mapping on HLA-A*01:03	with its mate going elsewhere. So far so good.

Now let's add a few more unrelated HLA alleles to the bed file:
```
$ cat five_regions.bed 
HLA-A*01:03 0   3503
HLA-A*02:01:01:01   0   3517
HLA-A*02:259    0   2978
HLA-A*02:81 0   3309
HLA-A*02:95 0   3388
```

and repeat the same view command
```
$ samtools view --regions-file five_regions.bed -T GRCh38_full_analysis_set_plus_decoy_hla.fa test.cram  |grep "H2CGNDSX2210503:1:2309:15393:10958" 
[W::hts_itr_multi_cram] No index entry for region 2885:0-3388
H2CGNDSX2210503:1:2309:15393:10958	97	HLA-A*01:03	528	0	151M	chr6_GL000251v2_alt	1422510	0	TCACATCCGTGTCCCGGCCCGGCCGCGGGGAGCCCCGCTTCATCGCCGTGGGCTACGTGGACGACACGCAGTTCGTGCGGTTCGACAGCGACGCCGCGAGCCAGAAGATGGAGCCGCGGGCGCCGTGGATAGAGCAGGAGGGGCCGGAGTA	???????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????	MC:Z:151M	MQ:i:0	AS:i:151	MD:Z:151	NM:i:0	RG:Z:H2CGN.1
H2CGNDSX2210503:1:2309:15393:10958	97	HLA-A*01:03	528	0	151M	chr6_GL000251v2_alt	1422510	0	TCACATCCGTGTCCCGGCCCGGCCGCGGGGAGCCCCGCTTCATCGCCGTGGGCTACGTGGACGACACGCAGTTCGTGCGGTTCGACAGCGACGCCGCGAGCCAGAAGATGGAGCCGCGGGCGCCGTGGATAGAGCAGGAGGGGCCGGAGTA	???????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????	MC:Z:151M	MQ:i:0	AS:i:151	MD:Z:151	NM:i:0	RG:Z:H2CGN.1
H2CGNDSX2210503:1:2309:15393:10958	97	HLA-A*01:03	528	0	151M	chr6_GL000251v2_alt	1422510	0	TCACATCCGTGTCCCGGCCCGGCCGCGGGGAGCCCCGCTTCATCGCCGTGGGCTACGTGGACGACACGCAGTTCGTGCGGTTCGACAGCGACGCCGCGAGCCAGAAGATGGAGCCGCGGGCGCCGTGGATAGAGCAGGAGGGGCCGGAGTA	???????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????	MC:Z:151M	MQ:i:0	AS:i:151	MD:Z:151	NM:i:0	RG:Z:H2CGN.1
```
The same behaviour if I remove my reference file and rely on samtools fetching it:
```
$ samtools view --regions-file four_regions.bed  test.cram  | grep "H2CGNDSX2210503:1:2309:15393:10958"  | wc -l 
3
```

Now, the same read is printed three times. Adding more unrelated HLA contigs makes it even worse. Using the full HLA contig set, I am getting 8 copies of the exact same read. This happens for several reads, however I have only observed it for reads that are mapping to the HLA-* contigs.   Now, of course this trips up downstream tools, so I would like to know if this is a bug in samtools, my cram file or just me doing something wrong. 

I do see a warning ([W::hts_itr_multi_cram] No index entry for region 2885:0-3388) that I think refers to the HLA-A*02:95  sequence, but using the md5sum for this contig in the cram header, I can see the EBI has an entry for it [36b421cc1baeb1cc37291f98566cc5f9](https://www.ebi.ac.uk/ena/cram/md5/36b421cc1baeb1cc37291f98566cc5f9) so I am not sure why samtools is complaining. Can this be related?

thanks for any feedback!

**Comment by daviesrob** [comment]
There was a recent bug fix to cram indexing.  It would be useful if you could build the `develop` branches of HTSlib and SAMtools, and let us know if you see the same problem.

**Comment by jensreeder** [comment]
Good news, using the dev version does seem to fix it on my toy example:
```
$ samtools --version
samtools 1.17-4-g1eee54d
Using htslib 1.17-11-gc1634e7
Copyright (C) 2023 Genome Research Ltd.
```

```
$ samtools view --regions-file five_regions.bed -T GRCh38_full_analysis_set_plus_decoy_hla.fa test.cram  |grep "H2CGNDSX2210503:1:2309:15393:10958" 
H2CGNDSX2210503:1:2309:15393:10958	97	HLA-A*01:03	528	0	151M	chr6_GL000251v2_alt	1422510	0	TCACATCCGTGTCCCGGCCCGGCCGCGGGGAGCCCCGCTTCATCGCCGTGGGCTACGTGGACGACACGCAGTTCGTGCGGTTCGACAGCGACGCCGCGAGCCAGAAGATGGAGCCGCGGGCGCCGTGGATAGAGCAGGAGGGGCCGGAGTA	???????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????	MC:Z:151M	MQ:i:0	AS:i:151	MD:Z:151	NM:i:0	RG:Z:H2CGN.1
 $ samtools view --regions-file one_region.bed -T GRCh38_full_analysis_set_plus_decoy_hla.fa test.cram  |grep "H2CGNDSX2210503:1:2309:15393:10958" 
H2CGNDSX2210503:1:2309:15393:10958	97	HLA-A*01:03	528	0	151M	chr6_GL000251v2_alt	1422510	0	TCACATCCGTGTCCCGGCCCGGCCGCGGGGAGCCCCGCTTCATCGCCGTGGGCTACGTGGACGACACGCAGTTCGTGCGGTTCGACAGCGACGCCGCGAGCCAGAAGATGGAGCCGCGGGCGCCGTGGATAGAGCAGGAGGGGCCGGAGTA	???????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????	MC:Z:151M	MQ:i:0	AS:i:151	MD:Z:151	NM:i:0	RG:Z:H2CGN.1
```

I will re-run it on the original query that made me find this bug and let you know if anything still looks unusual. 
Do you have an estimate on when 1.18 will be releases with all the fixes in dev?

**Comment by jensreeder** [comment]
One last update from me. I was not able to reproduce the error on my large dataset using the dev version of samtools.
I am now patiently awaiting the next release.
