### ISSUE TITLE
Unable to keep reads with secondary and supplementary alignments from BAM to FASTQ with `samtools fastq`

### ISSUE THREAD

**Issue by pilargmarch** [samtools/samtools#1820]
#### Are you using the latest version of [samtools](https://github.com/samtools/samtools/releases/latest) and [HTSlib](https://github.com/samtools/htslib/releases/latest)? If not, please specify.
Yes. samtools 1.17 and htslib 1.17.

 #### Please describe your environment.
- Linux 5.15.0-58-generic
- x86_64
- gcc (Ubuntu 11.3.0-1ubuntu1~22.04) 11.3.0

#### Please specify the steps taken to generate the issue, the command you are running and the relevant output.

I'm trying to convert a single-end .BAM to .FASTQ, but I want to retain reads with secondary and supplementary alignments. `samtools flagstat` gives this output.

```
37634824 + 0 in total (QC-passed reads + QC-failed reads)
28558403 + 0 primary
8874809 + 0 secondary
201612 + 0 supplementary
0 + 0 duplicates
0 + 0 primary duplicates
37216413 + 0 mapped (98.89% : N/A)
28139992 + 0 primary mapped (98.53% : N/A)
0 + 0 paired in sequencing
0 + 0 read1
0 + 0 read2
0 + 0 properly paired (N/A : N/A)
0 + 0 with itself and mate mapped
0 + 0 singletons (N/A : N/A)
0 + 0 with mate mapped to a different chr
0 + 0 with mate mapped to a different chr (mapQ>=5)
```

If I understand correctly (which is unlikely), according to `flagstat` there are 37634824 total reads, which is the number I'm trying to convert onto my FASTQ (primary + secondary + supplementary). But then, `samtools stats` tells me something different:

```
raw total sequences:	28558403	# excluding supplementary and secondary reads
filtered sequences:	0
sequences:	28558403
is sorted:	1
1st fragments:	28558403
last fragments:	0
reads mapped:	28139992
reads mapped and paired:	0	# paired-end technology bit set + both mates mapped
reads unmapped:	418411
reads properly paired:	0	# proper-pair bit set
reads paired:	0	# paired-end technology bit set
reads duplicated:	0	# PCR or optical duplicate bit set
reads MQ0:	896577	# mapped and MQ=0
reads QC failed:	0
non-primary alignments:	8874809
supplementary alignments:	201612
```

Now, seeing `stats` it seems that there are 28558403 reads? Anyways, let's try to convert the BAM. The documentation says this for `samtools fastq`:

> - -f INT only include reads with all  of the FLAGs in INT present [0]
> - -F INT only include reads with none of the FLAGS in INT present [0x900]
> - -G INT only EXCLUDE reads with all  of the FLAGs in INT present [0]

By default, `samtools fastq input.bam > default.fq` processes 28558403 reads (with primary alignments, I think) and the resulting .fastq has 28558403 reads. 

Now, if I want to include secondary and supplementary reads, I'd have to change the -F argument (which is 0x900 by default: the sum of secondary, 0x100, and supplementary, 0x800). So I do `samtools fastq input.bam -F 0 > all_reads.fq` and it says it processes 37634824 reads, which is good because I want all reads... but the resulting .fastq only has 28558403 reads. Both files (default.fq and all_reads.fq) have the same size, 5.1 GB.

I've tried with other tools, such as `Picard`'s `SamToFastq` with `--INCLUDE_NON_PRIMARY_ALIGNMENTS = true` and it results in a .FASTQ with 37634824 reads, as expected (with 6.8 GB). 

What exactly is happening? Am I misinterpreting the total number of reads?

Thank you in advance!

**Comment by jkbonfield** [comment]
The secondary and supplementary reads are duplicates of the primary reads.  Including them in fastq output would mean some reads get doubled up.  Furthermore it may not actually be possible to get back the original sequence from a secondary or supplementary, depending on the aligner options used.  Many aligners will hard-clip the unaligned bases for second/supp alignments, and only retain full sequence for the primary read.

What is the reason for wanting secondary and supplementary alignments too in fastq format?  The original intention of the command was to reverse the alignments and get back to a file you can realign, which implicitly means only one fastq entry per original sequence.

However, if you really want a fastq with duplicated data in it - one record per alignment rather than one per original read - then you can use `samtools fastq -F 0` to turn off the default filtering (0x900, which is SECONDARY,SUPPLEMENTARY).

**Comment by pilargmarch** [comment]
Thank you! I see now that I was mixing up alignments with reads. As you said, I only want one record per read, so the default call (with -F 0x900) is probably what I need. 

However, why do I get the same .FASTQ with `samtools fastq` and `samtools fastq -F 0`? Shouldn't the second option duplicate the reads, as you said? I get exactly the same number of records and the same file size.

**Comment by pilargmarch** [comment]
I did a test with a paired-end sample that I'm also working with. Calling `samtools fastq` gives 2 .FASTQ files: one with 46529119 records (6,2 GB) and another with 46529119 records as well (6,2 GB). On the other hand, calling `samtools fastq -F 0` gives 2 different .FASTQ files, as I expect would also happen with the single-end sample: one with 54854358 records (7,4 GB) and another with 54717767 records (7,3 GB).

Why isn't this the case as well for the single-end sample? Could it be because of the way I'm calling the function? `samtools fastq single_input.bam -F 0 > all_reads.fq` vs. `samtools fastq paired_input.bam -F 0 -1 all_reads1.fq -2 all_reads2.fq`.

**Comment by jkbonfield** [comment]
It appears `samtools fastq` is only ever capable of giving me 2 reads, even when there are pairs + supplementary.  I suspect this is simply a fundamental limitation of how it works.  Maybe @mp15 (original author) can comment?

I guess fundamentally it was simply never designed for outputting anything other than primary alignments as the use-case for doing otherwise is really unclear.  Likely the filtering options are intended primary for adding additional filtering rules (eg read1 only) rather than relaxing the existing ones.

Note you can just convert a BAM to FASTQ without any filtering whatsoever by using `view`.  In my example above:

```
$ expr $(samtools view -O fastq _.sam|wc -l) / 4
9908
```

**Comment by pilargmarch** [comment]
> It may still be causing issues, so if it's not been name-sorted then please try again after running through samtools sort -n.

Just to be thorough, I ran `samtools fastq -F 0` on the resulting .bam after sorting with `samtools sort -n` and it gave me the same .FASTQ. `samtools collate` on the initial .BAM did not help either.

Thank you for looking into this! I'm trying to perform quantification on repetitive elements, which is why I thought I had to keep multiple alignments (but now I understand it's enough to just keep the primary alignments, which really is the total number of reads). The way the `flagstats` output was worded really threw me off, since it says that there are 37634824 QC-passed reads, which is the sum of primary, secondary and supplementary (reads? alignments? I see now that it means "alignments"; but because the total sum are given as "reads", I mistook them as reads). I think 37634824 would be better worded as "alignments" instead of "reads", right?

```
37634824 + 0 in total (QC-passed reads + QC-failed reads)
28558403 + 0 primary
8874809 + 0 secondary
201612 + 0 supplementary
```

In any case, I no longer have a need to retain reads more than once in my .FASTQ, so the default `samtools fastq` will do.

Thanks again!

**Comment by jkbonfield** [comment]
Agreed the wording probably isn't ideal.  I confess I was confused myself with some of the output until I double checked the man page.  It's an interesting question as to whether it should be changed.  I think we could get away with it, but I also wouldn't be surprised if there was code out there parsing this output and assuming it to never change. *shrug*
