### ISSUE TITLE
Samtools mpileup vs. pileup

### ISSUE THREAD

**Issue by abdivito** [samtools/samtools#1827]
I am trying to run an analysis that requires a pileup file and is incompatible with an mpileup input. 

1) is there anywhere I can obtain an old version of samtools before mpileup was adopted?
2) is there any way to convert an mpileup file to pileup format?

**Comment by jkbonfield** [comment]
1. Not unless you install a truely ancient version of samtools.  The old pileup was removed years ago in 0.1.17 c350a570e955d5b4c2c13f607b7442df6d332c67 - well before any of the current maintainers started working on samtools.

2. That depends what column it is you need.  One of the things that got dropped in mpileup was the ability to add a consensus call.  I'm not sure why - it's useful, and one of the reasons for `samtools consensus`.  That's not just a reformatting job, but needs processing of data to make a call.  Looking at that old consensus caller I see it's pretty complex - basically what became bcftools mpileup/call by the look of it.

I'd say if you don't need the consensus, then maybe it's just a bit of awk/perl hackery to juggle columns around (sorry, but I'm not certain on how the original data was laid out, best read the docs on the tool you're using).  If you absolutely do require a consensus column, maybe start from `samtools consensus -f pileup` instead.  That's its own format, mainly intended for human readability and debugging, but it may be an easier starting point.

**Comment by jkbonfield** [comment]
Closed as pileup is not supported.
