### ISSUE TITLE
samtools calmd with empty BAM/CRAM file

### ISSUE THREAD

**Issue by fgvieira** [samtools/samtools#1839]
#### Is your feature request related to a problem? Please specify.

I am running `samtools calmd` on a pipeline and, sometimes, the input file has no references.
As it is now, `samtools` will fail on:
https://github.com/samtools/samtools/blob/556c60fdff977c0e6cadc4c2581661f187098b4d/bam_md.c#L412-L416

#### Describe the solution you would like.

I'd like for `samtools calmd`, in case of an empty file, to just process the file normally (maybe give a warning).
I tried with a file with just a version header and a dummy reference:
```
@HD VN:1.6 SO:coordinate
@SQ SN:dummy LN:1
```
and it worked fine (i.e it output an empty file with just an extra `PG` line).

**Comment by jkbonfield** [comment]
I can see how this minimalist case may occur in a pipeline, and working around it is a bit of faffing for the users.

So I agree with the idea that the error should be a warning instead.
