### ISSUE TITLE
Obtain the reads

### ISSUE THREAD

**Issue by AndyLy2Zy** [samtools/samtools#1840]
Dear authors,

I wander if we can achieve the reads from SAM or BAM files that aligned into both forward and reverse strands at same time? It's mean that one read, whose part region can be mapped to forward strand, and the other region mapped to opposite strand. I wander if there have some special mark in SAM or BAM for the kind of reads ?

Best,
Andy

**Comment by jkbonfield** [comment]
I guess if it's been through fixmates or equivalent then you can look at position plus length of alignment on the reference vs the mate position. Eg for matching left ends of read-pairs: `samtools view -e 'rname == mrname && pos <= mpos && pos+rlen > mpos'`.  That doesn't work for the right end though, as you don't have a "mate rlen".    Infact you have no knowledge at all about how long the mate pair is.

You could perhaps just make an assumption - the mate is the same length as us.  Eg:

```
samtools view -e 'rname == mrname && ((pos <= mpos && pos+rlen > mpos) || (pos >= mpos && pos < mpos+length(seq)))' in.bam
```

Not perfect, but maybe in the ballpark?  There's also `tlen` field, but again it lacks knowledge about the mate end point.  If you control your own pipeline, you can of course compute this and put it into an aux tag as the first thing you do before position sorting the data, which will make this exact later on.

**Comment by AndyLy2Zy** [comment]
Dear @jkbonfield,

Thanks for your suggestions. These reads generated from PicBio. The SAM or BAM file is achieved by minimap2 `minimap2 -ax asm20 --MD -L ~/data/refgenome/S288C_SGDR64_reChr.fas 01_raw/infile.fastq > 02_align/outfile.sam` 
I wander if there have ways to get my expect reads?

Best,
Andy

**Comment by daviesrob** [comment]
Hopefully the solution above worked out.
