### ISSUE TITLE
slice a gene that is aligned to transcriptom 

### ISSUE THREAD

**Issue by XqKang** [samtools/samtools#1843]
Hi I have a questions. 
I am used minimap2 to align my RNA sequencing data to a transcriptome. And i want to slice out few transcripts from a gene (ENST00000362079.2 for example) from the bam file. 

When I run
samtools view -h -Sb {bamfile path} chr1:35603303-35603363 > {output path}
It gives error
[main_samview] region "chr1:35603303-35603363" specifies an invalid region or unknown reference. Continue anyway.

When I run 
samtools view -h -Sb {bamfile path} ENST00000362079.2 > {output path}
it gives
[main_samview] region "ENST00000362079.2" specifies an invalid region or unknown reference. Continue anyway.

Is there any way to solve this?

**Comment by whitwham** [comment]
> chr1:35603303-35603363

Is the the chromosome name correct?  Is the range valid?

**Comment by XqKang** [comment]
Yes. When I aligned my data to genome. It works perfectly fine. But when I aligned it to transcriptome it does not work. The transcriptome fasta file I downloaded is from here
https://www.gencodegenes.org/human/
Is it because it does not have genomics coordinate?

**Comment by XqKang** [comment]
![image](https://github.com/samtools/samtools/assets/132936335/cd7891b6-131b-4c0c-9974-352973130270)
The data that aligned to genome and transcriptome looks like this by the way

**Comment by whitwham** [comment]
It looks like your reference/chromosome name in the transcriptome file is:

> ENST00000456328.2|ENSG00000290825.1|-|OTTHUMT00000362751.1|DDX11L2-202|DDX11L2|1657|lncRNA|

rather than just ENST00000456328.2 (or similar).
