### ISSUE TITLE
Filter BAM file based on custom flags values

### ISSUE THREAD

**Issue by pclavell** [samtools/samtools#1846]
I am working with the output of TieBrush (tool that collapses several BAM files into 1) which consists on a BAM file with three custom flags (such as YC=number of reads with the same location and CIGAR). 

My objective is to filter this BAM file to keep only those alignments that have a YC >2 using samtools (which I expect to be faster than the awk approach I am currently using)

I've seen in the [manual](http://www.htslib.org/doc/samtools.html) that there are options to filter using custom FLAGS but I can not find any example and my tries have not been successful.

Thanks

**Comment by pclavell** [comment]
Yes, it works! Thanks, I tried many options and even -e but i messed up

**Comment by jkbonfield** [comment]
Great :)
