### ISSUE TITLE
in-place reheadering doesn't follow CRAM standard?

### ISSUE THREAD

**Issue by matt-sexton** [samtools/samtools#1852]
#### Are you using the latest version of [samtools](https://github.com/samtools/samtools/releases/latest) and [HTSlib](https://github.com/samtools/htslib/releases/latest)? If not, please specify.
(run `samtools --version`)

samtools 1.15
Using htslib 1.15

 #### Please describe your environment.
- OS (run `uname -sr` on Linux/Mac OS or ` wmic os get Caption, Version` on Windows)
- machine architecture (run `uname -m` on Linux/Mac OS or ` wmic os get OSArchitecture` on Windows)
- compiler (run `gcc --version` or `clang --version`)

Ubuntu 18.04 LTS

#### Please specify the steps taken to generate the issue, the command you are running and the relevant output.

When performing in-place reheadering of a CRAM file, samtools grows the first header block into the padding header block (the second raw block of all zeroes).  The container header is modified to indicate that there is now only a single block in the container.  The length field of the container header is updated to count the new single block plus any remaining padding zeroes following that block.

However, the CRAM standard from 15 Aug 2022 defines the container header length field as

>  the sum of the lengths of all blocks in this container (headers and data); equal to the total byte length of the container minus the byte length of this header structure

I read that to mean that all bytes not in the container header must be in a header or data block, that extra bytes at the end of the container are not permitted.  Can you please clarify whether samtool's behavior is permitted by the standard?  If so, I would suggest making that clearer in the document.  If not, should samtools organize any remaining padding into a second block?

**Comment by matt-sexton** [comment]
Wow!  I didn't expect such a detailed look back into the archives.

I do agree that the current implementation is the simplest approach and the most natural way to handle in-place expansion of the header.  However, I would take issue with this statement:

> there's nothing explicitly stating all blocks must sum to container length

The spec defines the length field in the container header as:

> the sum of the lengths of all blocks in this container (headers and data)

Those appear contradictory to me.   I'm coming at this from the perspective of someone who implemented a CRAM encoder/decoder from scratch, based on the specification.  And the spec led me to expect there to be no padding, which was nice for consistency checking.  (Of course, that makes the information redundant, which isn't great for compression.)   It's been trivial to change my code to maintain compatibility with files reheadered by samtools, but I just want to make sure that the spec is clear in this regard.

And it does raise related questions.  Is padding allowed in containers that don't have headers?  Is the padding required to be zeroes?  Any there any restrictions on padding?

> It needs to explicitly permit what we're doing.

Agreed.  That would be great.

Thank you for looking into this issue.

**Comment by jkbonfield** [comment]
I see there was conversation on this in https://github.com/samtools/hts-specs/issues/396, and https://github.com/samtools/hts-specs/issues/398 in response to that added the "the sum of the lengths of all blocks in this container (headers and data)" statement.

I suspect at the time we didn't think through the implications, or simply forgot about the header padding code.  I don't believe this restriction of the specification was deliberate, rather it was over-zealous tidying up that invalidated existing usage.  So I think the Samtools (technically HTSlib) code isn't really the problem here.  I added PR https://github.com/samtools/hts-specs/pull/731 to relax the CRAM specification once more.

**Comment by jkbonfield** [comment]
Closing this issue as we've decided it's not going to change in code and the spec has a wording update pending in https://github.com/samtools/hts-specs/pull/731.
