### ISSUE TITLE
samtools mpileup --excl-flags doesn't work

### ISSUE THREAD

**Issue by ydLiu-HIT** [samtools/samtools#1859]
#### Are you using the latest version of [samtools](https://github.com/samtools/samtools/releases/latest) and [HTSlib](https://github.com/samtools/htslib/releases/latest)? If not, please specify.
(run `samtools --version`)
> version 1.17
 #### Please describe your environment.
- OS (run `uname -sr` on Linux/Mac OS or ` wmic os get Caption, Version` on Windows)
> Linux 3.10.0-862.14.4.el7.centos.plus.x86_64
- machine architecture (run `uname -m` on Linux/Mac OS or ` wmic os get OSArchitecture` on Windows)
> x86_64
- compiler (run `gcc --version` or `clang --version`)
> gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-44)

#### Please specify the steps taken to generate the issue, the command you are running and the relevant output.
When I use `mpileup`  to pile up the alignments with filtration parameters `--excl-flags` as follow:
`samtools mpileup example.bam --min-MQ 20 --min-BQ 13 -r chr22:36863317-36863317 --no-output-ends --excl-flags 256`
to filter secondary alignment and I got the pileup result:
`chr22   36863317        N       1       T       D`
From the pileup results, there are only one alignment can be used, but when I traverse all the alignments covered chr22:36863317 with `-F 256` as follow:
`samtools view example.bam chr22:36863317-36863317 -F 256`
there are 8 alignments output without any secondary alignment. Hence, the `mpileup --excl-flags` doesn't seem to be able to get the corresponding result compared with `view -F`

Looking forward to your reply！
Thanks.
Yadong.

**Comment by vasudeva8** [comment]
What about the quality of those other 8 alignments? Can you try 'view' with --min-MQ 20 and see whether that makes any difference in view output?
If not, could you please share the 8 alignments, data masked if required, that I could reproduce the issue from my side?

**Comment by ydLiu-HIT** [comment]
I have run `samtools view example.bam --min-MQ 20 -F 256 chr22:36863317-36863317` and output the 8 alignment in the attachment 
[test.zip](https://github.com/samtools/samtools/files/11745773/test.zip)

**Comment by ydLiu-HIT** [comment]
Thanks. I will close the issue.
