### ISSUE TITLE
Non-in-place reheadering a CRAM v2.1 file produces a broken v3.0 file

### ISSUE THREAD

**Issue by jmarshall** [samtools/samtools#1866]
#### Are you using the latest version of [samtools](https://github.com/samtools/samtools/releases/latest) and [HTSlib](https://github.com/samtools/htslib/releases/latest)? If not, please specify.

Tested with both current **develop** and the 1.17 release.

 #### Please describe your environment.

Primarily tested on macOS.

#### Please specify the steps taken to generate the issue, the command you are running and the relevant output.

Doing a non-in-place `samtools reheader` of a CRAM v2.1 file produces a CRAM file that cannot be indexed (here demonstrated using the test files from `test_reheader()`):

```
$ samtools reheader test/reheader/hdr.sam test/dat/view.001.tmp.v21.cram > bork.cram
$ samtools index bork.cram
[E::cram_index_container] CRAM slice offset 582 does not match landmark 0 in container header (578)
samtools index: failed to create index for "bork.cram"
```

Perhaps relatedly, it turns out that _bork.cram_ identifies itself as a v3.0 CRAM file — which is presumably incorrect:

```
$ htsfile test/dat/view.001.tmp.v21.cram bork.cram
test/dat/view.001.tmp.v21.cram:	CRAM version 2.1 compressed sequence data
bork.cram:	CRAM version 3.0 compressed sequence data
```

v2.1 files are fairly obsolete, so if it would be difficult to fix this so that out-of-place `samtools reheader` of a v2.1 CRAM file instead produces a valid indexable v2.1 CRAM file, a sufficient alternative might be for out-of-place reheadering to fail with an error message when given a v2.1 file.

**Comment by jkbonfield** [comment]
It seems to have been this way since Samtools 1.3.  Odd as when I wrote it it clearly had v2.1 code.  It must have been very short-lived in a working state!

I'll see if it's trivial to fix, if not as you say just don't allow it as the number of v2.1 files must be minimal.

**Comment by jmarshall** [comment]
Thanks for the quick fix. Incidentally it's not that I'm particularly interested in v2.1 files! I am writing a quick hack script to do streaming reheadering of files from a GCS bucket, and grabbed a file from the samtools test suite to test it locally. As luck would have it, the file I grabbed happened to be v2.1 and exhibit the problem. As the resulting file claimed to be v3.0, it took a while to accurately figure out just how widespread the problem was… :smile:

**Comment by jkbonfield** [comment]
I did wonder.  Fortuitous though as technically CRAM 3.1 files were invalid too (they worked as nothing changed to the data layout, but used codecs not legal in 3.0).

It clearly shows that 2.1 is basically dead in the wild as we'd moved to CRAM 3 before it really got widespread acceptance.  I have sometimes wondered about tidying up the code by simply nuking it and dropping support.  I wonder if SRA / ENA have any way to record the version number of files in their archives.
