### ISSUE TITLE
samtools-index does not support --threads as stated in man page

### ISSUE THREAD

**Issue by outpaddling** [samtools/samtools#1869]
The man pages lists --threads as equivalent to -@, but it's not actually supported by the code.

```
--- doc/samtools-index.1.orig   2023-06-28 13:24:30 UTC
+++ doc/samtools-index.1
@@ -125,7 +125,7 @@ Write the output index to
 .IR FILE .
 (Currently may only be used when exactly one alignment file is being indexed.)
 .TP
-.BI "-@, --threads " INT
+.BI "-@ " INT
 Number of input/output compression threads to use in addition to main thread [0].
 
 .SH AUTHOR
```

**Comment by jkbonfield** [comment]
Good spot!  Mea culpa. :)

I've made a PR to add this along with some other long options for consistency with `bcftools index`.

**Comment by outpaddling** [comment]
Cool, thanks.  I prefer long options, since I script pretty much everything, and they vastly improve readability.
