### ISSUE TITLE
bam2fq duplicated portions of reads with full read in output as well

### ISSUE THREAD

**Issue by agos316** [samtools/samtools#1870]
Hello, I used bam2fq a year ago to extract the fastq from a BAM file. The experiment was PE150 and the output from the files were duplicated. One full read and others were pieces of the same read. 

#### Describe the solution you would like.

If I remove these small duplicates should that solve my issue ? Or more curiously what is the mechanism that does this ? Thank you any help would be very much appreciated.

**Comment by jkbonfield** [comment]
Samtools fastq was rewritten a few years ago, including fixing many bugs.

What version of samtools are you using?  Do you have a small example portion of file to demonstrate your problem?  You should be able to reduce it down to just one alignment name, in SAM format.

**Comment by agos316** [comment]
I unfortuantely dont have the exact version, this was from a year ago so I don't have the logs anymore, however the output looked like this for 1 read.  

@A00738:267:HH5VMDSX2:3:1362:13874:30624/2

AAAAAAAAATAAAAATAAAAAAAAAAACAAAAAAAA

+

:,:F:F:,,,F,F,:,:,F,FF,,F,F,,F,,,,:,

--

@A00738:267:HH5VMDSX2:3:1362:13874:30624/2

GGGGGGGGTGATAAAAAAAAAAAAATAAAAATAAAAAAAAAAACAAAAAAAACAAAAAAAAAAAAAAAAAAAAAAAAAAATAAAAAATAAAAAAAAATTAAAAACTAAAAAAAAAAAAAATAAAAAAATAAATTTAAAAAAAAAAAAAAC

+

F:F,F:,,,,,,::,,:,:F:F:,,,F,F,:,:,F,FF,,F,F,,F,,,,:,,:FFFF:,F,F,,:,::FF,FFF:F,,,,,:,F,:,,:,:FFF,,,,,:,F,,,F,FF:::,FFF,F,,F:,,::,,,,,,,F,F:F,:FFFFFFFF,

--

@A00738:267:HH5VMDSX2:3:1362:13874:30624/2

AAAAAATTAAAAACTAAAAAAAAAAAAAATAAAAAAA

+

:FFF,,,,,:,F,,,F,FF:::,FFF,F,,F:,,::,

--

@A00738:267:HH5VMDSX2:3:1362:13874:30624/2

AAAAAAAAAAAAAAATAAAAAATAAAAAAAAAT

+

:,::FF,FFF:F,,,,,:,F,:,,:,:FFF,,,

--

@A00738:267:HH5VMDSX2:3:1362:13874:30624/2

AATAAAAAAATAAATTTAAAAAAAAAAAAAAC

+

F,,F:,,::,,,,,,,F,F:F,:FFFFFFFF,

**Comment by agos316** [comment]
Completely understandable. Thank you for your help.

**Comment by jkbonfield** [comment]
No problem.

**Comment by jkbonfield** [comment]
Yes 0.1.18 is positively ancient.  It looks like back then the bam2fq code was basically nothing more than a "while read-bam-record, write-fastq".  It had no filtering for things like secondary alignments, and the user would have been expected to do a `samtools view -F` command first to filter such things out.

I think we can safely say this issue is no longer a problem.  Thanks for getting back to us to confirm the version.
