### ISSUE TITLE
Samtools merge reduces size of original bam files

### ISSUE THREAD

**Issue by stacyhung** [samtools/samtools#1871]
Hi - I noticed that `samtools merge` reduces the size of each bam file that is in the merge.  

For example, if applying samtools merge on a single file:

`samtools merge merged.bam sample.bam`

The "merged" bam is smaller than the original bam.

**What information is being removed from the original bam file?**

I am running samtools 1.17 with clang 14.0.0 in a MacOS environment (Ventura).

Thank you!

**Comment by jkbonfield** [comment]
I would expect the summed size of multiple input files to be larger than the single output file as there is greater opportunity for data compression through deduplication of DNA sequence.  That doesn't apply to a single file obviously.

I suspect it's simply the default Deflate compression levels and the library being used (eg zlib vs libdeflate).

You can do `samtools view merged.bam | md5sum` and `samtools view sample.bam | md5sum` to check the contents match.  Or head both of them and do a `diff`.

**Comment by stacyhung** [comment]
The contents of `samtools view` between the original and the single "merged" bam are identical.  A difference in compression method makes sense and is something I hadn't thought about - thanks for your help!!
