### ISSUE TITLE
subsampling in Samtools view - choosing with or without repititions

### ISSUE THREAD

**Issue by idoc-bioinfo** [samtools/samtools#1883]
Dear Sir/Madam,
My question concerns the subsampling feature in the "samtools view" tool.
Maybe I missed something, but In the current [samtools view page](http://www.htslib.org/doc/samtools-view.html), I coulnt find wether the subsampling feature (-s) is with or without repititions.
What option is currently used?
Could you please add add a flag that allows the user to choose between subsampling with/without repititions?
Best Regards,
Ido Carmel

**Comment by jkbonfield** [comment]
Subsampling is simply a filter where we discard a fraction of the data, so -s 0.1 will keep 10% and discard 90%.  Hence each input record can only occur at most once in the output.

Note that the sampling is done by hashing the read name, so we either keep all of the reads matching that hash or none of the reads.  This means we won't randomly discard one of a read-pair, so it represents a true down-sampling of the input data as if the sequencing instrument simply produced less data.

**Comment by idoc-bioinfo** [comment]
Thanks a lot for the fast response
