### ISSUE TITLE
[Question]: Guidance/Docs on combining multiple -f and/or -F options with samtools view

### ISSUE THREAD

**Issue by tamuanand** [samtools/samtools#1885]
Hi

I came across this webpage - https://wikis.utexas.edu/dsplay/CoreNGSTools/Filtering+with+SAMTools that states

```
samtools view only pays attention to one -F or -f option 
so to specify more than one flag value you need to 
combine them into one number. For example, combining 
0x100 and 0x4 yields 0x104
```

Is the above correct? If so, could you point to the relevant docs about this. The reason I ask is I have seen things like this 

```
samtools view -b -h -f 3 -F 4 -F 8 -F 256 -F 1024 -F 2048 -q 15 example.sorted.bam  \
  | samtools sort -@ 7 -o example.rmdup.sorted.bam -
```
Thanks in advance.

**Comment by jkbonfield** [comment]
No, the webpage is not correct. (It's easy to validate too with `view -c` and some tests)

You can see the source code [here](https://github.com/samtools/samtools/blob/develop/sam_view.c#L914-L929), which shows it does a bit-wise OR of the existing flag for each new option, so you can build them up if you wish.

**Comment by tamuanand** [comment]
Thanks a lot @jkbonfield
