### ISSUE TITLE
samtools expression filtering not working as intended?

### ISSUE THREAD

**Issue by tamuanand** [samtools/samtools#1887]
#### Are you using the latest version of [samtools](https://github.com/samtools/samtools/releases/latest) and [HTSlib](https://github.com/samtools/htslib/releases/latest)? If not, please specify.
see same behavior with both samtools 1.17 and samtools 1.15.1

 #### Please describe your environment.
- OS Linux 5.15.0-1038-aws
- machine architecture x86_64
- compiler (run `gcc --version` or `clang --version`)

#### Please specify the steps taken to generate the issue, the command you are running and the relevant output.

I am trying to use `samtools view -e` as suggested by @jkbonfield @daviesrob here https://github.com/samtools/samtools/issues/1610#issuecomment-1066598993 to get bams without chrM

```
samtools view -@ 8 --write-index -o TEST.bam##idx##TEST.bam.bai -e 'rname != "chrM"' my_sorted.bam
```

I am then checking to see if chrM is retained or gone from my TEST.bam file - however I do see chrM in my output

```
samtools view -H TEST.bam | perl -ne 'if(/^@SQ.*?SN:(\w+)\s+LN:(\d+)/){print $1,"\t",$2,"\n"}'

```

Am I missing anything? 

Thanks,
Anand

**Comment by jkbonfield** [comment]
That's a check for the SAM header, but the filter expression is applied to alignment records.  The header won't be modified.

You can use `samtools reheader` if you wished, but I'd advise against it as it's easier to keep the header intact and you may find other issues such as a read pair with a mate aligned to chrM.  `view -e` won't fix up those MRNAME records - it'll just become a singleton.  So leaving the header intact is definitely the right thing to do here.

**Comment by daviesrob** [comment]
The `-e` filter will only remove the data lines containing `chrM` reads.  It won't touch the header, as you've seen.  The remaining line is harmless, but you could use [`samtools reheader`](https://www.htslib.org/doc/samtools-reheader.html) if you really want to get rid of it.

**Comment by tamuanand** [comment]
Thanks both
