### ISSUE TITLE
samtools view SAM to BAM error - no SQ lines present in the header

### ISSUE THREAD

**Issue by rpeguil** [samtools/samtools#1888]
Hello,
I'm using samtools v1.17 on Linux 3.10.0-1160.el7.x86_64

I am trying to convert my sam file (minimap2 output, PacBio data) to a bam file with the following comand line:
samtools view -b $INPUTDIR/361PacBio_Bacillus.sam > $OUTPUTDIR/361PacBio_Bacillus.bam

But I received the following error. It was perfectly working with other sam files from Bowtie2.

samtools: /zfs/softs/contrib/apps/anaconda/3/envs/samtools-1.17/bin/../lib/libtinfow.so.6: no version information available (required by samtools)
samtools: /zfs/softs/contrib/apps/anaconda/3/envs/samtools-1.17/bin/../lib/libncursesw.so.6: no version information available (required by samtools)
samtools: /zfs/softs/contrib/apps/anaconda/3/envs/samtools-1.17/bin/../lib/libncursesw.so.6: no version information available (required by samtools)
[E::sam_parse1] no SQ lines present in the header
[W::sam_read1_sam] Parse error at line 2

Minimap2 comand line: 
minimap2 -ax map-pb -L bacillus.fasta.gz XREPL_20191218_S64018_PL100147411-1_C01_bc1009-bc1009.fastq.gz --secondary=no --sam-hit-only > 331PacBio_Bacillus.sam

Thank you for your feedback.

**Comment by arslan9732** [comment]
Hi,
It is not samtools issue, it is a minimap issue. see [FAQ3 minimap](https://github.com/lh3/minimap2/blob/master/FAQ.md#3-the-output-sam-doesnt-have-a-header)

**Comment by rpeguil** [comment]
Hi,
Thank you for the information. I will ckeck that.

**Comment by daviesrob** [comment]
The best (and likely fastest) solution would be to use the `minimap2` `-I` option and give minimap lots of memory, as suggested in the FAQ.  Although another possibility would be to make your own header using `samtools dict` and then splice that in front of the minimap2 output.  E.g.:

```
( printf "@HD\tVN:1.6\tSO:unsorted\n" ; samtools dict -H bacillus.fasta.gz ) > bacillus_hdr.sam
```
would create a minimal header that could be spliced in front of the `minimap` output:
```
( cat bacillus_hdr.sam ; minimap2 -ax map-pb -L bacillus.fasta.gz XREPL_20191218_S64018_PL100147411-1_C01_bc1009-bc1009.fastq.gz --secondary=no --sam-hit-only ) > 331PacBio_Bacillus.sam
```
You could also do it in one, but saving the header made from the reference would be useful if you want to use it more than once.

**Comment by rpeguil** [comment]
Hi,
Thank you for the details. I'm trying the minimap2 -I solution and waiting for the results.

**Comment by dazhuang420** [comment]
Hi,
my command is :minimap2  -ax map-hifi -t 120 -I 20G bbcc.fasta.mmi  all_hifi.fq.gz -o hifi2genome.sam.But I still get an error when converting the sam file into the bam file:
[E::sam_parse1] no SQ lines present in the header
[E::sam_parse1] no SQ lines present in the header
samtools view: error reading file "hifi2genome.sam"
[E::sam_parse1] no SQ lines present in the header
samtools view: error closing "hifi2genome.sam": -5
Is there any better solution?
thank you  for your feedback.

**Comment by whitwham** [comment]
Did you try [this](https://github.com/samtools/samtools/issues/1888#issuecomment-1650571925) mentioned above?

**Comment by dazhuang420** [comment]
Hi, I did not try the method mentioned above, but I resolved my issue by adding the -T parameter.
