### ISSUE TITLE
ChatGPT says `samtools markdup` is deprecated. True or False?

### ISSUE THREAD

**Issue by felixm3** [samtools/samtools#1891]
From ChatGPT: "However, note that as of my last update, samtools markdup is considered deprecated, and it is recommended to use Picard's MarkDuplicates instead."

<img width="800" alt="image" src="https://github.com/samtools/samtools/assets/43228120/f80bd207-023a-4282-8466-dfc859edf8be">

**Comment by whitwham** [comment]
As usual, ChatGPT is inaccurate.  It is not something you should put your trust in.

**Comment by mp15** [comment]
The old tool rmdup, which only removed duplicates rather than marking them was depreciated and removed from samtools quite some time ago, that bucket of statistical bolts has gone and mixed them up.
