### ISSUE TITLE
Bam2fq error

### ISSUE THREAD

**Issue by SamQu25** [samtools/samtools#1892]
Hello,

I am trying to convert a .subreads.bam file into a fastq file using the bam2fq option. 
My command is:

`samtools bam2fq file.subreads.bam > file.fastq`

I get the error:

```
[W::bam_hdr_read] EOF marker is absent. The input is probably truncated
[E::bgzf_read_block] Failed to read BGZF block data at offset 19894617765 expected 27054 bytes; hread returned 14665
[E::bgzf_read] Read block operation failed with error 4 after 0 of 4 bytes
samtools bam2fq: Failed to read bam record
samtools bam2fq: Error writing to FASTx files.: No such file or directory
[M::bam2fq_mainloop] discarded 0 singletons
[M::bam2fq_mainloop] processed 890329 reads
```

It still creates a fastq file with about the right size (bam: 19.8 GB, fastq: 20.6 GB) and the fastq-file looks fine.

Do I have to worry about anything or is it fine to just continue downstream?

**Comment by whitwham** [comment]
How many reads in the fastq file compared to the bam file?

Also, what version of samtools are you using?

**Comment by whitwham** [comment]
Is there any update on this?  Otherwise we will close the issue.

**Comment by jkbonfield** [comment]
If you have an index already then `samtools idxstats` can give some summaries, however this simply sounds like you have a corrupted file.  You'll need to redownload or regenerate it.  Check you haven't run out of disk space too.

**Comment by SamQu25** [comment]
Thanks for your reply then I need to check that. Unluckily this is older data from a previous student...
