### ISSUE TITLE
Calling in high sno density region

### ISSUE THREAD

**Issue by Axze-rgb** [samtools/samtools#1893]
Hello, it's my understanding that those regions might cause a decrease in the calling qualitry meatrics, like GQ. 

However, am working with an organism where I know we have more than 2 percent heterozygosity. What callers tend to do, is to not call the denser regions, or call only a few of the SNPs. In other words, I would need to increase the sensitivity. I know this will comme at the cost of speficficity. 

What parameters would you particluarly tweak? Something in the bayesian prior? Thank you

**Comment by whitwham** [comment]
So, what command are you actually running?

**Comment by Axze-rgb** [comment]
> So, what command are you actually running?

Nothing at the moment, my point is to ask what parameters to tweak, since the default completely miss high snp density regions, which have been confirmed by HiFi sequencing. I suspect just the high proximity is causing an issue but I don't know enough on how samtools works under the hood. 

Is there something wrong with my question?

**Comment by jkbonfield** [comment]
Are you following an outdated recipe for variant calling with samtools?  We no longer support variant calling in Samtools, and instead recommend `bcftools mpileup` instead.  Your issue is best addressed there where the author is more likely to spot questions.

**Comment by Axze-rgb** [comment]
No, I hadn't realised I was on the samtools and not bcftools github.
