### ISSUE TITLE
[view] remove reads by a file containing read names

### ISSUE THREAD

**Issue by ftian9** [samtools/samtools#1895]
It would be convenient if users could remove reads based on a file containing read names.
That is, only output the reads not in a file (one read name per line).
`samtools view --no-N -b read_names.txt input.bam > output.bam`

**Comment by jmarshall** [comment]
Look at the `-U` option: `samtools view -N read_names.txt -U output.bam -o /dev/null input.bam`

**Comment by ftian9** [comment]
Thank you, but the `-U` option will not work well if I need to use other options at the same time.
For example:
```samtools view -L region.bed -N read_names.txt -U output.bam -o /dev/null input.bam```

**Comment by jkbonfield** [comment]
Bcftools uses `^` for negation, eg from bcftools view usage:

```
    -S, --samples-file [^]FILE        File of samples to include (or exclude with "^" prefix)
```

I'm not sure if I like the syntax or not, but we could be consistent and do something similar.

**Comment by jkbonfield** [comment]
> Thank you, but the `-U` option will not work well if I need to use other options at the same time. For example: `samtools view -L region.bed -N read_names.txt -U output.bam -o /dev/null input.bam` It will output the reads not in region.bed OR not in read_names.txt But I would like the reads in region.bed AND not in read_names.txt

As for this point, you can do multiple views piped together.  Eg:

```
samtools view -L region.bed -u input.bam | samtools view -N read_names.txt -U output.bam -o /dev/null
```

It's not ideal, but it's a viable workaround for now.
