### ISSUE TITLE
Issues with downloading reference data when running samtools index on CRAMs

### ISSUE THREAD

**Issue by michaelgatzen** [samtools/samtools#1899]
This issue falls somewhere between a bug report and a feature request. In order to generate an index to a CRAM file, `samtools index` requires a reference. Right now, when running that command, it will look in a cache directory if the respective reference sequences matching the contig MD5s are present. If not, it will automatically attempt to download the references from the EBI server, as described in [the documentation](http://www.htslib.org/workflow/cram.html). There, it also says that the reference files can be made available for use locally by running the perl script `seq_cache_populate.pl`. I see a few issues with that approach:

1. This approach seems convenient if running samtools locally on a workstation or on-prem system, and the files only have to be downloaded once. However, when running in the cloud, this caching does not work, because the machines only exist for the duration of the workflow. That is why the Broad's production secondary analysis pipeline [WARP has to use the perl script](https://github.com/broadinstitute/warp/blob/1a8bb664cea6bb0e0480d740fe4da4626d5fb9e8/tasks/broad/Utilities.wdl#L140C13-L140C13), otherwise this would result in hundreds of thousands of queries to the EBI server.
1. It seems not ideal to me that it is invisible to the user that data is being downloaded from a remote server when indexing a CRAM file. I would find it more transparent if there would be some log output that data is being downloaded, or even having to explicitly set a flag that allows a download. On the other hand, I would find it more intuitive if the default behavior would be to expect the input of a reference FASTA as an input to samtools index (with the option of setting a flag to download from EBI), rather than having to run a separate perl script
1. **This way this is currently implemented can lead to significant cost**. As an example, I did not know that data would automatically be downloaded from a remote server in the UK (due to the lack of log output). Running a samtools index on a small-ish CRAM file in the cloud took over two hours. After doing a lot of searching I was finally able to track it down to this issue, and using the perl script with a localized FASTA file and subsequently indexing the same CRAM was a matter of one minute. Users not knowing about this functionality might spend significant money on cloud cost for downloading references from EBI over and over again.
1. It also feels not ideal that the references are cached permanently when running samtools index just once with a new reference, leading to potentially a lot of disk space being used.

My suggestion would be to
1. At least print a log message about data being downloaded
3. Perhaps disabling the download altogether unless an explicit command line flag is set
4. Adding a command line argument to provide an index file to `samtools index`

**Comment by daviesrob** [comment]
I'm surprised that `samtools index` did want a reference to index your CRAM file, unless it's a very old version.  From version 1.9 it should be able to run without them - the way to check this would be to set REF_PATH to something that stops samtools from finding the references and then see if index still works.  For example:
```sh
REF_PATH=: samtools index test.cram
```
Please let us know if that doesn't work, and if so what was in the CRAM file and which reference it attempted to download.

`samtools` will [print a warning](https://github.com/samtools/htslib/blob/5098983e426ac74bf0d1edaf5e8902bab72e5947/cram/cram_io.c#L3097) if it needs to create a cache directory, although this doesn't explicitly mention downloading anything.  Maybe we should make that more clear.  There is also some code to log what's being put in the cache, but only if you increase the verbosity.  I don't think that's possible for `index` but you can do it for other commands like `view`.

A while back there was some discussion about asking some of the major cloud providers to set up refget servers (which is the API used to get the references).  Unfortunately nothing came of that, which is a pity as only having the EBI server is not that good for resilience.  It is possible to avoid EBI downloads by providing your own reference cache and setting REF_PATH to use it.  The ENA have a page on how to [cache references using squid](https://ena-docs.readthedocs.io/en/latest/retrieval/programmatic-access/cram-reference-cache.html), but if you know which references you want then a pre-populated S3 bucket (or equivalent) should also work.  As long as your cloud service allows free local traffic, it should be possible to avoid most of the network cost that way.

**Comment by daviesrob** [comment]
Closing as we think this was fixed in 1.9. Please let us know if you see it happening in a newer version, and can provide an example we can use for testing.
