### ISSUE TITLE
Documentation clarification request -- samtools split

### ISSUE THREAD

**Issue by SHuang-Broad** [samtools/samtools#1905]
#### Is your feature request related to a problem? Please specify.
No.

#### Describe the solution you would like.

The documentation for `samtools split` currently doesn't clearly state if the order of the input bam is preserved in its outputs. Based on our experience, it looks like it is.

Thanks,
Steve

**Comment by whitwham** [comment]
Yes, input order should be preserved by all our tools unless the documentation says otherwise.

**Comment by SHuang-Broad** [comment]
Nice to have that confirmation. Thank you!
