### ISSUE TITLE
samtools mpileup shows no coverage at start of reference

### ISSUE THREAD

**Issue by otradnaya** [samtools/samtools#1906]
samtools 1.16.1
Linux 3.10.0-1160.6.1.el7.x86_64
x86_64
gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-44)

Input bam file contains a single read, aligned to a reference using BWA.
Per BWA, read aligns to nt 1 of the reference after soft-clipping several bases.

Yet, mpileup output shows coverage of reference starting at nt 3 of reference, not nt 1.
Quality scores are high in the region in question.

Command run is: 
` samtools mpileup sample.sam -o sample.mpileup -f ref.fa `

Attached is an archive containing the following files:
- sample.sam (input)
- ref.fa (reference)
- sample.mpileup (output)

Thanks!

[sample.zip](https://github.com/samtools/samtools/files/12340784/sample.zip)

**Comment by jkbonfield** [comment]
I see:

```
$ samtools mpileup sample.sam -f ref.fa | head
[mpileup] 1 samples in 1 input files
ref	1	C	0	*	*
ref	2	A	0	*	*
ref	3	A	0	*	*
ref	4	G	1	.	4
ref	5	G	1	.	;
ref	6	A	1	.	C
ref	7	A	1	.	J
ref	8	T	1	.	O
ref	9	G	1	.	H
ref	10	G	1	.	G
```

If you want all bases shown, you need to disable the base quality threshold (defaults to 13), and maybe also disable BAQ.

```
$ samtools mpileup -B -Q0 sample.sam -f ref.fa |head
[mpileup] 1 samples in 1 input files
ref	1	C	1	^].	H
ref	2	A	1	.	J
ref	3	A	1	.	N
ref	4	G	1	.	N
ref	5	G	1	.	I
ref	6	A	1	.	K
ref	7	A	1	.	S
ref	8	T	1	.	S
ref	9	G	1	.	H
ref	10	G	1	.	G
```

**Comment by otradnaya** [comment]
Thanks for the explanation, @jkbonfield. Very helpful!
