### ISSUE TITLE
Cannot query HTTPS or S3 resource via samtools/htslib under macOS Catalina (x86)

### ISSUE THREAD

**Issue by alexpreynolds** [samtools/samtools#1911]
#### Are you using the latest version of [samtools](https://github.com/samtools/samtools/releases/latest) and [HTSlib](https://github.com/samtools/htslib/releases/latest)? If not, please specify.
(run `samtools --version`)

I am using the latest version of `samtools` and `htslib` pulled from their respective Github repositories (as of 1 Sep 2023):

```
% samtools --version
samtools 1.18-7-gae19296
Using htslib 1.18-17-g5acbc15-dirty
```

I configured the compilation of `htslib` with `./configure --enable-libcurl --enable-s3`.

I configured the compilation of `samtools` with `./configure --enable-htslib=[path_to_htslib_dir]`.

 #### Please describe your environment.
- OS (run `uname -sr` on Linux/Mac OS or ` wmic os get Caption, Version` on Windows)

```
% uname -sr
Darwin 22.6.0
```

- machine architecture (run `uname -m` on Linux/Mac OS or ` wmic os get OSArchitecture` on Windows)

```
% uname -m
x86_64
```

- compiler (run `gcc --version` or `clang --version`)

```
% clang --version
Apple clang version 14.0.3 (clang-1403.0.22.14.1)
Target: x86_64-apple-darwin22.6.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
```

#### Please specify the steps taken to generate the issue, the command you are running and the relevant output.

I am trying to query a file with `samtools` via HTTPS or S3 protocols and I am getting errors from the binary and no output, e.g.:

```
% samtools view https://resources.altius.org/~areynolds/public/fiberview/072823/HUDEP.control.DS182418.chr22.bam.bai chr22:30265855-30267901
[E::hts_hopen] Failed to open file https://resources.altius.org/~areynolds/public/fiberview/072823/HUDEP.control.DS182418.chr22.bam.bai
[E::hts_open_format] Failed to open file "https://resources.altius.org/~areynolds/public/fiberview/072823/HUDEP.control.DS182418.chr22.bam.bai" : Inappropriate file type or format
samtools view: failed to open "https://resources.altius.org/~areynolds/public/fiberview/072823/HUDEP.control.DS182418.chr22.bam.bai" for reading: Inappropriate file type or format
```

An S3 URL pointing to the same resource and index results the same error (but pointing to the S3 URL). A Cloudwatch HTTPS URL pointing to the same resource and index results in the same error (again, but pointing to the Cloudwatch URL). I'm not pasting these for privacy reasons but can share them privately.

As a positive control, I am able to query this URL (and similar) via a Javascript-based library independent of `htslib` (`bam-js`). So this resource can be reached and can be queried over HTTPS through means other than `samtools`/`htslib`.

**Comment by jmarshall** [comment]
For `samtools view`, “Inappropriate file type or format” indicates that this is not a SAM, BAM, or CRAM file. Which indeed it is not:

```
% samtools view https://…chr22.bam.bai …
```

**Comment by alexpreynolds** [comment]
Hmm, I was sure that I was querying a BAM file and not its index when I was running into issues with an earlier version of 'pysam` and `samtools`/`htslib`, which is why I recompiled the kit. I'll close this up, but I think there is something going on.
