### ISSUE TITLE
samtools consensus

### ISSUE THREAD

**Issue by bsb2014** [samtools/samtools#1915]
Is it possible to output reference sequence when no reads covering a region? In other words, I would like to replace the "N" with reference sequence in the consensus output. Thanks.

**Comment by jkbonfield** [comment]
Not at the moment.  That's probably something you still need to use bcftools consensus for.  Specifically samtools consensus is a consensus generation tool and not a reference variant caller, so it currently has no knowledge of the reference whatsoever.

I could consider adding it.  What is the use case please?

**Comment by bsb2014** [comment]
I would like to use samtools consensus to polish my long read assembly.

**Comment by jkbonfield** [comment]
Interesting.  So I assume you aligned short reads against an assembly fasta as reference?

Basically you need to seed the default consensus with something other than unknowns (Ns).  We could add this as an option, but for now the only way to do that is with actual read alignments.  You could include the long reads in with the short reads in the alignment process so you get full coverage.  Or alternatively make a fake BAM from from the fasta itself.  Each record starting at base 1 and being mapped <length>M CIGAR field.  It may need shredding into overlapping fragments if it's too long.

Something ghastly like this (plus something to build the SAM header, or just copy it from your alignment file).

```
perl -e 'sub dump_seq {($n,$s)=(@_);$l=length($s);$p=1000000;for ($i=0;$i<$l;$i+=$p) {$sub=substr($seq,$i,$p);print "$n-$i\t0\t$n\t",$i+1,"\t0\t",length($sub),"M\t*\t0\t0\t$sub\t*\n"}} while (<>) {if (/^>(\S+)/) {dump_seq($chr,$seq) if $seq;$seq="";$chr=$1;next} chomp($_);$seq.=$_} dump_seq($chr,$seq)'  assembly.fasta
```

You could then do a merge of that and your short-read alignment to add minimal 1-depth coverage everywhere.  I'm not sure on what quality value should be used, so I went with "*".

**Comment by bsb2014** [comment]
Thanks for your excellent ideas. Could you please modify the code to add base quality (e.g. 20)? So, I can use the --min-BQ 20 afterwards. 

Is -5  required for  -X hiseq option? 

Thanks.

**Comment by jkbonfield** [comment]
Sorry I forgot about this.  The quality is "*" in my perl code above, but you can change this to any qual using chr(33+qual) x length($sub).  Eg:

```
perl -e 'sub dump_seq {($n,$s)=(@_);$l=length($s);$p=1000000;for ($i=0;$i<$l;$i+=$p) {$sub=substr($seq,$i,$p);print "$n-$i\t0\t$n\t",$i+1,"\t0\t",length($sub),"M\t*\t0\t0\t$sub\t",chr(33+20) x length($sub),"\n"}} while (<>) {if (/^>(\S+)/) {dump_seq($chr,$seq) if $seq;$seq="";$chr=$1;next} chomp($_);$seq.=$_} dump_seq($chr,$seq)'  assembly.fasta
```

The second question, yes the Bayesian mode is the default.  The -5 confused me, but I remember now it's because in early drafts the Bayesian consensus mode was referred to as "gap5" mode as that's where that consensus algorithm originated from.  It's since been renamed, and infact -5 is no longer a valid option.  This is a bug in our documentation which I will fix.

**Comment by bsb2014** [comment]
Thanks for your codes and confirmation.

**Comment by schorlton-bugseq** [comment]
+1 for this feature request. Would be awesome to set min depth to 0 and have the reference base preserved instead of masked!
