### ISSUE TITLE
Samtools missing some commands

### ISSUE THREAD

**Issue by CaroSegami** [samtools/samtools#1916]
Hi, I am running samtools in linux in an hpc. I've tried with the hpc installed version (1.4) and with my own version (1.9) in a conda environment : htslib 1.9

I am interested in using the command consensus: http://www.htslib.org/doc/samtools-consensus.html

However, both the in directly hpc installed version and in my own conda environment, when I call samtools, the command is not listed.

There are other ways to do what I am interested in doing. However, I am puzzled as to why this happens?
Moreover, in the manual page (http://www.htslib.org/doc/samtools.html) there are 39 commands listed but in my samtools there are only 29 commands listed.

Thank you.

**Comment by jkbonfield** [comment]
Both of those versions are pretty ancient.  The consensus command is more recent, so please install the latest version.  It may also be good to inform your HPC maintainers that their version is old and likely much slower than it needs to be.

**Comment by whitwham** [comment]
Consensus was first released in samtools 1.15.
