### ISSUE TITLE
Querying of HTTPS data via `samtools` v1.18/`htslib` v1.18 hangs

### ISSUE THREAD

**Issue by alexpreynolds** [samtools/samtools#1918]
#### Are you using the latest version of [samtools](https://github.com/samtools/samtools/releases/latest) and [HTSlib](https://github.com/samtools/htslib/releases/latest)? If not, please specify.
(run `samtools --version`)

I am using the following version of `samtools`:

```
% samtools --version
samtools 1.18-7-gae19296
Using htslib 1.18-17-g5acbc15-dirty
```

 #### Please describe your environment.
- OS (run `uname -sr` on Linux/Mac OS or ` wmic os get Caption, Version` on Windows)
- machine architecture (run `uname -m` on Linux/Mac OS or ` wmic os get OSArchitecture` on Windows)
- compiler (run `gcc --version` or `clang --version`)

```
% uname -sr
Darwin 22.6.0

% uname -m
x86_64

% clang --version
Apple clang version 15.0.0 (clang-1500.0.40.1)
Target: x86_64-apple-darwin22.6.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
```

#### Please specify the steps taken to generate the issue, the command you are running and the relevant output.

I am attempting to query or retrieve reads from a large, indexed BAM file, e.g.:

```
$ ls -al HUDEP.control.DS182418.chr2.bam*
-rw-r--r-- 1 areynolds stamlab 58434647581 Sep 20 22:14 HUDEP.control.DS182418.chr2.bam
-rw-r--r-- 1 areynolds stamlab     8338720 Sep 22 11:41 HUDEP.control.DS182418.chr2.bam.bai
```

I am querying via four `htslib`-dependent means: 1) `samtools` to a local file, 2) `samtools` to an HTTPS-hosted file, 3) `pysam`/`htslib` to a local file, 4) `pysam`/`htslib` to a HTTPS-hosted file.

Queries via `samtools` and `pysam`/`htslib` to a local file appear to work correctly, *e.g.*:

```
$ samtools view HUDEP.control.DS182418.chr2.bam chr2:18472960-18473760 | head -5 | cut -f1-4
m64323e_220609_191124/25362523/ccs      16      chr2    18455551
m64323e_220609_191124/179766422/ccs     0       chr2    18456853
m64323e_221012_230238/84410813/ccs      16      chr2    18457473
m64323e_221014_083319/66193327/ccs      0       chr2    18459718
m64323e_221002_034726/60099319/ccs      16      chr2    18459723
```

The same `htslib`-backed query via Python, *e.g.*:

```
#!/usr/bin/env python

import pysam

seqname = 'chr2'
start = 18472960
end = 18473760
bam_url = 'HUDEP.control.DS182418.chr2.bam'
with pysam.AlignmentFile(bam_url, 'rb') as bam_fh:
    iter = bam_fh.fetch(seqname, start, end)
    for x in iter:
        print(str(x))
```

If I perform the same query via HTTPS and `samtools`, however, the command hangs and I get no output:

```
% samtools view https://resources.altius.org/~areynolds/public/fiberview/072823/HUDEP.control.DS182418.chr2.bam chr2:18472960-18473760 | head -5 | cut -f1-4
*nothing, it just hangs*
```

Via `pysam`/`htslib`, the process does not hang, but I get an error message and no output, which may be informative to the bug:

```
[E::bgzf_read_block] Invalid BGZF header at offset 4339935225
[E::bgzf_read] Read block operation failed with error 2 after 0 of 4 bytes
...
  File "pysam/libcalignmentfile.pyx", line 1750, in pysam.libcalignmentfile.AlignmentFile.__exit__
  File "pysam/libcalignmentfile.pyx", line 1682, in pysam.libcalignmentfile.AlignmentFile.close
OSError: [Errno 0] Success
```

(I realize this issue is specific to `samtools`, but I am reporting what I see with `pysam` in case its error sheds light on the cause.)

I have verified the integrity of the BAM files involved with these errors by using `gunzip -t` and the `bamrescue` utility (https://github.com/Arkanosis/bamrescue).

Both tools report that the test BAM file has no corrupt blocks.

The BAI index file was generated after the BAM file was generated and written to disk. 

For testing purposes, I have used `samtools index` v1.6, v1.9, and v1.14 to remake the index file on repeated query tests.

Further, as a positive control that I am hosting HTTPS files at the correct location and with correct CORS policies, etc., I am able to use the Javascript-based `bam-js` library (https://github.com/GMOD/bam-js) to correctly perform the same query at the same test location. 

I am able to retrieve alignment data via `bam-js`, and so I believe that my web server is configured to serve BAM data correctly over HTTPS.

Please let me know if I can provide any additional information that is relevant or useful.

**Comment by jmarshall** [comment]
You might try the following patch:

```diff
diff --git a/hfile_libcurl.c b/hfile_libcurl.c
index 1e4a448..e70550e 100644
--- a/hfile_libcurl.c
+++ b/hfile_libcurl.c
@@ -837,7 +837,7 @@ static ssize_t libcurl_read(hFILE *fpv, void *bufferv, size_t nbytes)
         got = fp->buffer.ptr.rd - buffer;
 
         if (to_skip >= 0) { // Skipping over a small seek
-            if (got < to_skip) { // Need to skip more data
+            if (got <= to_skip) { // Need to skip more data
                 to_skip -= got;
             } else {
                 got -= to_skip;
```

I don't know if that's the most correct fix, but if it changes the behaviour then it suggests that there is a bug here that the author of HTSlib's libcurl backend's small-seek-skipping code may wish to look into.

**Comment by daviesrob** [comment]
@jmarshall Yes, the patch should fix it.  The problem is that `to_skip` wasn't set to zero on the `got == to_skip` case, so it kept on looping around for longer than it should.  It does need to go around once though as it needs to get some data that it can return.  I'll turn your patch into a pull request.

@alexpreynolds Thanks for the very comprehensive report, and a file where we can reliably reproduce the problem.  This may also explain #1622, samtools/htslib#1037 and samtools/htslib#1625...
