### ISSUE TITLE
'Duplicate entry in sam header' of a BAM file, want to convert to SAM

### ISSUE THREAD

**Issue by hanrong-chen** [samtools/samtools#1919]
#### Are you using the latest version of [samtools](https://github.com/samtools/samtools/releases/latest) and [HTSlib](https://github.com/samtools/htslib/releases/latest)? If not, please specify.
(run `samtools --version`)

samtools 1.17
Using htslib 1.18

 #### Please describe your environment.
- OS (run `uname -sr` on Linux/Mac OS or ` wmic os get Caption, Version` on Windows)

Linux 4.18.0-372.32.1.el8_6.x86_64
- machine architecture (run `uname -m` on Linux/Mac OS or ` wmic os get OSArchitecture` on Windows)

x86_64
- compiler (run `gcc --version` or `clang --version`)

gcc (GCC) 8.5.0 20210514 (Red Hat 8.5.0-10)

#### Please specify the steps taken to generate the issue, the command you are running and the relevant output.

I received a BAM file from a collaborator. I am unable to parse it as there are duplicates in the header. When I run `samtools view xxx.bam`, and also with `-h` or `-H` options, I get:
> [E::sam_hrecs_update_hashes] Duplicate entry "opera_contig_71600" in sam header
> samtools view: failed to add PG line to the header

Apart from asking the collaborator to regenerate the BAM file, can I convert the BAM to SAM despite the offending duplicate header, so I can try to manually remove it?

Thanks.

**Comment by whitwham** [comment]
I managed to create and read a bam file with two SQ lines using an old version of samtools.  I used version 1.2, which came before we tightened up the header checks.  So if you can use an earlier version that might work for you.

We should maybe add an option to fix broken headers, but that is a longer term solution.

**Comment by whitwham** [comment]
You can also try:

`samtools view --no-PG -h infile.bam -o outfile.sam`

The **--no-PG** option should prevent the header from being parsed in this case.

**Comment by hanrong-chen** [comment]
this works! thanks very much.
