### ISSUE TITLE
Samtools does not compile on Mac OS Ventura 13.5. gcc permission issue

### ISSUE THREAD

**Issue by SLehto** [samtools/samtools#1921]
#### Are you using the latest version of [samtools](https://github.com/samtools/samtools/releases/latest) and [HTSlib]

cannot compile

 #### Please describe your environment.
- OS (run `uname -sr` on Linux/Mac OS or ` wmic os get Caption, Version` on Windows)
- machine architecture (run `uname -m` on Linux/Mac OS or ` wmic os get OSArchitecture` on Windows)
- compiler (run `gcc --version` or `clang --version`)

Apple clang version 11.0.3 (clang-1103.0.32.59)
Target: x86_64-apple-darwin22.6.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin

#### Please specify the steps taken to generate the issue, the command you are running and the relevant output.

I have problems compiling Samtools on Mac OS Ventura 13.5. I can run "./configure" apparently without any issues, but "make" gives the following error:

gcc -Wall -g -O2 -I. -Ihtslib-1.18 -I./lz4  -c -o bam_aux.o bam_aux.c
make: gcc: Permission denied
make: *** [Makefile:139: bam_aux.o] Error 127

**Comment by whitwham** [comment]
I was compiling from a Github clone on Ventura 13.6 yesterday so it should work.

What result does `gcc -Wall -g -O2 -I. -Ihtslib-1.18 -I./lz4 -c -o bam_aux.o bam_aux.c` by itself give you?

**Comment by SLehto** [comment]
ok, this gives an error:
~ % gcc -Wall -g -O2 -I. -Ihtslib-1.18 -I./lz4 -c -o bam_aux.o bam_aux.c
clang: error: no such file or directory: 'bam_aux.c'
clang: error: no input files

**Comment by whitwham** [comment]
Are you in the right directory?

**Comment by SLehto** [comment]
I’m in the directory where gcc is installed

InstalledDir: /Library/Developer/CommandLineTools/usr/bin

**Comment by whitwham** [comment]
Well you really need to run that command in the samtools directory.

Back to basics though.  The **make: gcc: Permission denied** error seems to crop up when there is something odd in the build environment.

 Did you install samtools straight from Github?

**Comment by SLehto** [comment]
I have tried installing from the source code from Github, but ”make” failed with gcc: permission denied.

I then tried istalling using Anaconda, but that produced a rather long error report, so yes, something is messed up in my build environment. Any ideas how I should proceed?

**Comment by whitwham** [comment]
Not really, not without seeing your computer.  If you just want to use samtools, rather than compile it as well, then you could use [homewbrew](https://brew.sh/).  That has an up-to-date version of samtools.

When you installed it from Github, did you clone the repository or did you download the release?

**Comment by SLehto** [comment]
I need samtools as a part of more complex pipeline, so should get it installed somehow. From Github, I downloaded the release.

**Comment by whitwham** [comment]
Okay, then what did you do?  Did you make sure there was no Anaconda stuff around that could interfere with the environment variables?

**Comment by SLehto** [comment]
If I try to remove the failed package installation I get the same lenghty error report it gave when I tried to install. There seems to be something going on with the python:

% conda remove samtools
Collecting package metadata (repodata.json): failed
WARNING conda.exceptions:print_unexpected_error_report(1251): KeyError('pkgs_dirs')
Traceback (most recent call last):
  File "/Users/samulilehtonen/opt/anaconda3/lib/python3.7/site-packages/conda/exceptions.py", line 1129, in __call__
    return func(*args, **kwargs)
  File "/Users/samulilehtonen/opt/anaconda3/lib/python3.7/site-packages/conda/cli/main.py", line 86, in main_subshell
    exit_code = do_call(args, p)
  File "/Users/samulilehtonen/opt/anaconda3/lib/python3.7/site-packages/conda/cli/conda_argparse.py", line 93, in do_call
    return getattr(module, func_name)(args, parser)
  File "/Users/samulilehtonen/opt/anaconda3/lib/python3.7/site-packages/conda/cli/main_remove.py", line 90, in execute
    txn = solver.solve_for_transaction()
  File "/Users/samulilehtonen/opt/anaconda3/lib/python3.7/site-packages/conda/core/solve.py", line 159, in solve_for_transaction
    should_retry_solve)
  File "/Users/samulilehtonen/opt/anaconda3/lib/python3.7/site-packages/conda/core/solve.py", line 200, in solve_for_diff
    force_remove, should_retry_solve)
  File "/Users/samulilehtonen/opt/anaconda3/lib/python3.7/site-packages/conda/core/solve.py", line 304, in solve_final_state
    ssc = self._collect_all_metadata(ssc)
  File "/Users/samulilehtonen/opt/anaconda3/lib/python3.7/site-packages/conda/common/io.py", line 86, in decorated
    return f(*args, **kwds)
  File "/Users/samulilehtonen/opt/anaconda3/lib/python3.7/site-packages/conda/core/solve.py", line 439, in _collect_all_metadata
    _supplement_index_with_system(virtual_pkg_index)
  File "/Users/samulilehtonen/opt/anaconda3/lib/python3.7/site-packages/conda/core/index.py", line 172, in _supplement_index_with_system
    cuda_version = context.cuda_version
  File "/Users/samulilehtonen/opt/anaconda3/lib/python3.7/site-packages/conda/auxlib/decorators.py", line 276, in new_fget
    cache[inner_attname] = func(self)
  File "/Users/samulilehtonen/opt/anaconda3/lib/python3.7/site-packages/conda/common/decorators.py", line 24, in wrapper
    return func(*args, **kwargs)
  File "/Users/samulilehtonen/opt/anaconda3/lib/python3.7/site-packages/conda/base/context.py", line 935, in cuda_version
    return cuda_detect()
  File "/Users/samulilehtonen/opt/anaconda3/lib/python3.7/site-packages/conda/common/cuda.py", line 38, in cuda_detect
    import ctypes
  File "/Users/samulilehtonen/opt/anaconda3/lib/python3.7/ctypes/__init__.py", line 7, in <module>
    from _ctypes import Union, Structure, Array
ImportError: dlopen(/Users/samulilehtonen/opt/anaconda3/lib/python3.7/lib-dynload/_ctypes.cpython-37m-darwin.so, 0x0002): Library not loaded: @rpath/libffi.6.dylib
  Referenced from: <66269FD6-56F9-32A5-8A25-F986023901A1> /Users/samulilehtonen/opt/anaconda3/lib/python3.7/lib-dynload/_ctypes.cpython-37m-darwin.so
  Reason: tried: '/opt/concourse/worker/volumes/live/d698b2ce-b4b9-4fb4-6268-e633fba1b324/volume/python_1565725718142/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehol/lib/libffi.6.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/opt/concourse/worker/volumes/live/d698b2ce-b4b9-4fb4-6268-e633fba1b324/volume/python_1565725718142/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehol/lib/libffi.6.dylib' (no such file), '/opt/concourse/worker/volumes/live/d698b2ce-b4b9-4fb4-6268-e633fba1b324/volume/python_1565725718142/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehol/lib/libffi.6.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/opt/concourse/worker/volumes/live/d698b2ce-b4b9-4fb4-6268-e633fba1b324/volume/python_1565725718142/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehol/lib/libffi.6.dylib' (no such file), '/opt/concourse/worker/volumes/live/d698b2ce-b4b9-4fb4-6268-e633fba1b324/volume/python_1565725718142/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehol/lib/libffi.6.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/opt/concourse/worker/volumes/live/d698b2ce-b4b9-4fb4-6268-e633fba1b324/volume/python_1565725718142/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehol/lib/libffi.6.dylib' (no such file), '/Users/samulilehtonen/opt/anaconda3/lib/python3.7/lib-dynload/../../libffi.6.dylib' (no such file), '/opt/concourse/worker/volumes/live/d698b2ce-b4b9-4fb4-6268-e633fba1b324/volume/python_1565725718142/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehol/lib/libffi.6.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/opt/concourse/worker/volumes/live/d698b2ce-b4b9-4fb4-6268-e633fba1b324/volume/python_1565725718142/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehol/lib/libffi.6.dylib' (no such file), '/opt/concourse/worker/volumes/live/d698b2ce-b4b9-4fb4-6268-e633fba1b324/volume/python_1565725718142/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehol/lib/libffi.6.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/opt/concourse/worker/volumes/live/d698b2ce-b4b9-4fb4-6268-e633fba1b324/volume/python_1565725718142/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehol/lib/libffi.6.dylib' (no such file), '/opt/concourse/worker/volumes/live/d698b2ce-b4b9-4fb4-6268-e633fba1b324/volume/python_1565725718142/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehol/lib/libffi.6.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/opt/concourse/worker/volumes/live/d698b2ce-b4b9-4fb4-6268-e633fba1b324/volume/python_1565725718142/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehol/lib/libffi.6.dylib' (no such file), '/Users/samulilehtonen/opt/anaconda3/lib/python3.7/lib-dynload/../../libffi.6.dylib' (no such file), '/opt/concourse/worker/volumes/live/d698b2ce-b4b9-4fb4-6268-e633fba1b324/volume/python_1565725718142/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehol/lib/libffi.6.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/opt/concourse/worker/volumes/live/d698b2ce-b4b9-4fb4-6268-e633fba1b324/volume/python_1565725718142/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehol/lib/libffi.6.dylib' (no such file), '/opt/concourse/worker/volumes/live/d698b2ce-b4b9-4fb4-6268-e633fba1b324/volume/python_1565725718142/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehol/lib/libffi.6.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/opt/concourse/worker/volumes/live/d698b2ce-b4b9-4fb4-6268-e633fba1b324/volume/python_1565725718142/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehol/lib/libffi.6.dylib' (no such file), '/Users/samulilehtonen/opt/anaconda3/bin/../lib/libffi.6.dylib' (no such file), '/opt/concourse/worker/volumes/live/d698b2ce-b4b9-4fb4-6268-e633fba1b324/volume/python_1565725718142/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehol/lib/libffi.6.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/opt/concourse/worker/volumes/live/d698b2ce-b4b9-4fb4-6268-e633fba1b324/volume/python_1565725718142/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehol/lib/libffi.6.dylib' (no such file), '/opt/concourse/worker/volumes/live/d698b2ce-b4b9-4fb4-6268-e633fba1b324/volume/python_1565725718142/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehol/lib/libffi.6.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/opt/concourse/worker/volumes/live/d698b2ce-b4b9-4fb4-6268-e633fba1b324/volume/python_1565725718142/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehol/lib/libffi.6.dylib' (no such file), '/Users/samulilehtonen/opt/anaconda3/bin/../lib/libffi.6.dylib' (no such file), '/usr/local/lib/libffi.6.dylib' (no such file), '/usr/lib/libffi.6.dylib' (no such file, not in dyld cache)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/samulilehtonen/opt/anaconda3/lib/python3.7/site-packages/conda/exceptions.py", line 1249, in print_unexpected_error_report
    message_builder.append(get_main_info_str(error_report['conda_info']))
  File "/Users/samulilehtonen/opt/anaconda3/lib/python3.7/site-packages/conda/cli/main_info.py", line 237, in get_main_info_str
    info_dict['_' + key] = ('\n' + 26 * ' ').join(info_dict[key])
KeyError: 'pkgs_dirs'

# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "/Users/samulilehtonen/opt/anaconda3/lib/python3.7/site-packages/conda/exceptions.py", line 1129, in __call__
        return func(*args, **kwargs)
      File "/Users/samulilehtonen/opt/anaconda3/lib/python3.7/site-packages/conda/cli/main.py", line 86, in main_subshell
        exit_code = do_call(args, p)
      File "/Users/samulilehtonen/opt/anaconda3/lib/python3.7/site-packages/conda/cli/conda_argparse.py", line 93, in do_call
        return getattr(module, func_name)(args, parser)
      File "/Users/samulilehtonen/opt/anaconda3/lib/python3.7/site-packages/conda/cli/main_remove.py", line 90, in execute
        txn = solver.solve_for_transaction()
      File "/Users/samulilehtonen/opt/anaconda3/lib/python3.7/site-packages/conda/core/solve.py", line 159, in solve_for_transaction
        should_retry_solve)
      File "/Users/samulilehtonen/opt/anaconda3/lib/python3.7/site-packages/conda/core/solve.py", line 200, in solve_for_diff
        force_remove, should_retry_solve)
      File "/Users/samulilehtonen/opt/anaconda3/lib/python3.7/site-packages/conda/core/solve.py", line 304, in solve_final_state
        ssc = self._collect_all_metadata(ssc)
      File "/Users/samulilehtonen/opt/anaconda3/lib/python3.7/site-packages/conda/common/io.py", line 86, in decorated
        return f(*args, **kwds)
      File "/Users/samulilehtonen/opt/anaconda3/lib/python3.7/site-packages/conda/core/solve.py", line 439, in _collect_all_metadata
        _supplement_index_with_system(virtual_pkg_index)
      File "/Users/samulilehtonen/opt/anaconda3/lib/python3.7/site-packages/conda/core/index.py", line 172, in _supplement_index_with_system
        cuda_version = context.cuda_version
      File "/Users/samulilehtonen/opt/anaconda3/lib/python3.7/site-packages/conda/auxlib/decorators.py", line 276, in new_fget
        cache[inner_attname] = func(self)
      File "/Users/samulilehtonen/opt/anaconda3/lib/python3.7/site-packages/conda/common/decorators.py", line 24, in wrapper
        return func(*args, **kwargs)
      File "/Users/samulilehtonen/opt/anaconda3/lib/python3.7/site-packages/conda/base/context.py", line 935, in cuda_version
        return cuda_detect()
      File "/Users/samulilehtonen/opt/anaconda3/lib/python3.7/site-packages/conda/common/cuda.py", line 38, in cuda_detect
        import ctypes
      File "/Users/samulilehtonen/opt/anaconda3/lib/python3.7/ctypes/__init__.py", line 7, in <module>
        from _ctypes import Union, Structure, Array
    ImportError: dlopen(/Users/samulilehtonen/opt/anaconda3/lib/python3.7/lib-dynload/_ctypes.cpython-37m-darwin.so, 0x0002): Library not loaded: @rpath/libffi.6.dylib
      Referenced from: <66269FD6-56F9-32A5-8A25-F986023901A1> /Users/samulilehtonen/opt/anaconda3/lib/python3.7/lib-dynload/_ctypes.cpython-37m-darwin.so
      Reason: tried: '/opt/concourse/worker/volumes/live/d698b2ce-b4b9-4fb4-6268-e633fba1b324/volume/python_1565725718142/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehol/lib/libffi.6.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/opt/concourse/worker/volumes/live/d698b2ce-b4b9-4fb4-6268-e633fba1b324/volume/python_1565725718142/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehol/lib/libffi.6.dylib' (no such file), '/opt/concourse/worker/volumes/live/d698b2ce-b4b9-4fb4-6268-e633fba1b324/volume/python_1565725718142/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehol/lib/libffi.6.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/opt/concourse/worker/volumes/live/d698b2ce-b4b9-4fb4-6268-e633fba1b324/volume/python_1565725718142/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehol/lib/libffi.6.dylib' (no such file), '/opt/concourse/worker/volumes/live/d698b2ce-b4b9-4fb4-6268-e633fba1b324/volume/python_1565725718142/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehol/lib/libffi.6.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/opt/concourse/worker/volumes/live/d698b2ce-b4b9-4fb4-6268-e633fba1b324/volume/python_1565725718142/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehol/lib/libffi.6.dylib' (no such file), '/Users/samulilehtonen/opt/anaconda3/lib/python3.7/lib-dynload/../../libffi.6.dylib' (no such file), '/opt/concourse/worker/volumes/live/d698b2ce-b4b9-4fb4-6268-e633fba1b324/volume/python_1565725718142/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehol/lib/libffi.6.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/opt/concourse/worker/volumes/live/d698b2ce-b4b9-4fb4-6268-e633fba1b324/volume/python_1565725718142/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehol/lib/libffi.6.dylib' (no such file), '/opt/concourse/worker/volumes/live/d698b2ce-b4b9-4fb4-6268-e633fba1b324/volume/python_1565725718142/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehol/lib/libffi.6.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/opt/concourse/worker/volumes/live/d698b2ce-b4b9-4fb4-6268-e633fba1b324/volume/python_1565725718142/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehol/lib/libffi.6.dylib' (no such file), '/opt/concourse/worker/volumes/live/d698b2ce-b4b9-4fb4-6268-e633fba1b324/volume/python_1565725718142/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehol/lib/libffi.6.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/opt/concourse/worker/volumes/live/d698b2ce-b4b9-4fb4-6268-e633fba1b324/volume/python_1565725718142/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehol/lib/libffi.6.dylib' (no such file), '/Users/samulilehtonen/opt/anaconda3/lib/python3.7/lib-dynload/../../libffi.6.dylib' (no such file), '/opt/concourse/worker/volumes/live/d698b2ce-b4b9-4fb4-6268-e633fba1b324/volume/python_1565725718142/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehol/lib/libffi.6.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/opt/concourse/worker/volumes/live/d698b2ce-b4b9-4fb4-6268-e633fba1b324/volume/python_1565725718142/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehol/lib/libffi.6.dylib' (no such file), '/opt/concourse/worker/volumes/live/d698b2ce-b4b9-4fb4-6268-e633fba1b324/volume/python_1565725718142/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehol/lib/libffi.6.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/opt/concourse/worker/volumes/live/d698b2ce-b4b9-4fb4-6268-e633fba1b324/volume/python_1565725718142/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehol/lib/libffi.6.dylib' (no such file), '/Users/samulilehtonen/opt/anaconda3/bin/../lib/libffi.6.dylib' (no such file), '/opt/concourse/worker/volumes/live/d698b2ce-b4b9-4fb4-6268-e633fba1b324/volume/python_1565725718142/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehol/lib/libffi.6.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/opt/concourse/worker/volumes/live/d698b2ce-b4b9-4fb4-6268-e633fba1b324/volume/python_1565725718142/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehol/lib/libffi.6.dylib' (no such file), '/opt/concourse/worker/volumes/live/d698b2ce-b4b9-4fb4-6268-e633fba1b324/volume/python_1565725718142/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehol/lib/libffi.6.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/opt/concourse/worker/volumes/live/d698b2ce-b4b9-4fb4-6268-e633fba1b324/volume/python_1565725718142/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehol/lib/libffi.6.dylib' (no such file), '/Users/samulilehtonen/opt/anaconda3/bin/../lib/libffi.6.dylib' (no such file), '/usr/local/lib/libffi.6.dylib' (no such file), '/usr/lib/libffi.6.dylib' (no such file, not in dyld cache)

`$ /Users/samulilehtonen/opt/anaconda3/bin/conda remove samtools`

  environment variables:
conda info could not be constructed.
KeyError('pkgs_dirs')

An unexpected error has occurred. Conda has prepared the above report.

**Comment by whitwham** [comment]
Wow, that a big error report!  I think this issue is moving into tech support territory and I cannot really help you there.  I would suggest that you get someone more local to help you clean up the Anaconda installation and then try samtools again.

**Comment by SLehto** [comment]
that is what I was afraid of… but thanks a lot, I’ll try to figure this out with someone

**Comment by whitwham** [comment]
Best of luck.
