### ISSUE TITLE
Samtools index terminates prematurely without error

### ISSUE THREAD

**Issue by marcelglueck** [samtools/samtools#1927]
#### Are you using the latest version of [samtools](https://github.com/samtools/samtools/releases/latest) and [HTSlib]
Yes, I am running the latest version of samtools: 
```
samtools 1.18
Using htslib 1.18
Copyright (C) 2023 Genome Research Ltd.

Samtools compilation details:
    Features:       build=configure curses=yes 
    CC:             gcc
    CPPFLAGS:       
    CFLAGS:         -Wall -g -O2
    LDFLAGS:        
    HTSDIR:         htslib-1.18
    LIBS:           
    CURSES_LIB:     -lncursesw

HTSlib compilation details:
    Features:       build=configure libcurl=no S3=no GCS=no libdeflate=no lzma=yes bzip2=yes plugins=no htscodecs=1.5.1
    CC:             gcc
    CPPFLAGS:       
    CFLAGS:         -Wall -g -O2 -fvisibility=hidden
    LDFLAGS:        -fvisibility=hidden 

HTSlib URL scheme handlers present:
    built-in:    preload, data, file
    crypt4gh-needed:     crypt4gh
    mem:         mem
```
 #### Please describe your environment.
I have containerized samtools 1.18 together with bwa 0.7.17 in a Singularity container with Ubuntu 20.04. I run array jobs were each job runs a single pool-seq sample. Each job uses 26 cores that are split equally across the different steps of the pipeline (see below). 125 GB of RAM is provided to every job.

#### Please specify the steps taken to generate the issue, the command you are running and the relevant output.

The array job is parsed through the following PBS script:

```
#PBS -l nodes=1:ppn=26
#PBS -l walltime=48:00:00
#PBS -l mem=125gb
#PBS -S /bin/bash
#PBS -N ddRAD_align_reads
#PBS -t 1-333
#PBS -j oe
#PBS -o /REDACTED/align_reads/logs
#PBS -e /REDACTED/align_reads/logs

# Go where your container is located
cd /REDACTED/containers

# Run container 
singularity exec bwa_0-7-17_samtools_1-18.sif ../align_reads/align_reads_v001.sh
```

The important parts of the script look like this:

```
set -o nounset
set -o pipefail

/usr/local/bwa-0.7.17/bwa mem -t "$((threads/3))" -MPa -v 0 -R $(echo "@RG\tID:${sl}\tSM:${sl}") \
-k $k -w $w -d $d -r $r -c $c -A $A -B $B -O $O -E $E -L $L -U $U \
"$ref_out" <(gunzip -c "$read1") <(gunzip -c "$read2") | 
samtools sort -@ "$((threads/3))" -u -  | # Default-sort bam file; avoid compression to speed up processing
samtools index -@ "$(((threads/3)-1))" - -o "$fout_aligned_sorted_indexed" # Index and write to bam

# Check the pipeline's exit status (note the set -o pipefail at the beginning of the script).
# Abort with non-zero exit status if issues have been encountered.
if [ $? -eq 0 ]; then
  echo "
  INFO: Aligning, sorting and indexing successful."
else
  echo "
  ERROR: Aligning, sorting and indexing not successful. Aborting ..."
  exit 1
fi

# Check indexed bam file for integrity
echo "
Checking $fout_aligned_sorted_indexed for integrity ..."
if samtools quickcheck "$fout_aligned_sorted_indexed"; then
    echo "INFO: $fout_aligned_sorted_indexed is healthy. Gathering alignment stats ..."
    # Gather alignment stats. As for samtools index, -@ is the number of ADDITIONAL threads
    samtools flagstat -@ "$((threads-2))" "$fout_aligned_sorted_indexed"
else
    echo "ERROR: $fout_aligned_sorted_indexed is corrupted! Aborting ..."
    exit 1
fi
```

Interestingly, the exit status of the bwa-sort-index pipeline is 0. However, the indexed files are very small and checking their integrity fails with 
```
Checking ../align_reads/results/An_AEW25/An_AEW25_aligned_sorted_indexed.bam for integrity ...
../align_reads/results/An_AEW25/An_AEW25_aligned_sorted_indexed.bam could not be opened for reading.
ERROR: ../align_reads/results/An_AEW25/An_AEW25_aligned_sorted_indexed.bam is corrupted! Aborting ...
```

In a previous version of the script, I wrote the results of samtools sort to a bam file for which samtools quickcheck did not find any issues. The issue started when trying to index the file. Indexing stopped prematurely without prompting any error and the indexed bam files were way smaller than the sorted but non-indexed files. I hoped to solve this issue by piping the output of sort directly to index. I have extensively searched for similar cases and found https://github.com/samtools/samtools/issues/1057. To prevent bwa from writing anything to stderr, I have set -v 0 and `#PBS -e /REDACTED/align_reads/logs` to prevent any modification or redirection of stdout to log files. Even then, bwa writes stderr to log files ...
```
[bwa_index] Pack FASTA... 6.40 sec
[bwa_index] Construct BWT for the packed sequence...
[BWTIncCreate] textLength=1359869734, availableWord=107684980
[BWTIncConstructFromPacked] 10 iterations done. 99999990 characters processed.
[BWTIncConstructFromPacked] 20 iterations done. 199999990 characters processed.
```
However, piping bwa output to samtools sort is an often-realized approach and has worked for many people. Because of this, I doubt that this is causing the issues. The absence of any errors complicates troubleshooting this problem. I am at my wits end and appreciate any help.

**Comment by whitwham** [comment]
I may be missing something, but where in your script are you writing the bam file?  **samtools index** writes an index file, not the bam file itself.

**Comment by whitwham** [comment]
Also, you can use the **--write-index** option with **samtools sort** so you do not have to run two separate commands.

**Comment by marcelglueck** [comment]
Weird. For some reason, I though samtools index would also write the bam file. Combining samtools sort with --write-index worked like a charm. Thanks for your fast reply.
