### ISSUE TITLE
samtools sort: truncated file. Aborting

### ISSUE THREAD

**Issue by rmormando** [samtools/samtools#1937]
I'm trying to convert a SAM file into a BAM file.

I performed the alignment with minimap2 to get the SAM file and now I'm using this command to convert to BAM:
`samtools sort -o sample.bam sample.sam`

And I keep getting this error message:
```
[W::sam_read1_sam] Parse error at line 332558
samtools sort: truncated file. Aborting
```

I have tried:
```
samtools sort sample.sam > sample.bam
samtools view -bs sample.sam > sample.bam
samtools view -H sample.sam   #to see if there was anything wrong with the SAM headers
```
And re-mapping the sample with minimap2 to generate a new SAM file but nothing is working and I keep getting the same error message.

**Comment by whitwham** [comment]
Which version of samtools are you using?

How are you using minimap2?

What is on line 332558?

**Comment by rmormando** [comment]
samtools version: samtools 1.18

minimap2 command: `minimap2 -ax sr ref.fasta sample_R1.fastq.gz sample_R2.fastq.gz > sample.sam`

that particular line is just a normal alignment call - I don't see anything out of the ordianry.

I just redid the alignment using bwa instead and I was able to get a BAM and BAI file...does samtools no longer work with minimap2 alignments?

**Comment by whitwham** [comment]
As far as I know minimap2 should still work.

Could you do `sed -n 332558p sample.sam | cat -t` and paste the results?  That might give us some insight into what is going wrong.

**Comment by rmormando** [comment]
This is happening with some of the alignments using bwa now too - do you know what the reason is for the excessive `^@^@^@` ?

The bwa command I'm using is: `bwa mem reference.fatsa sample_R1.fastq.gz sample_R2.fastq.gz > sample.sam`

**Comment by whitwham** [comment]
Well, I'm not entirely sure what is going on with all the `^@`s but look at this from your output:
//6E<EEEEEEEEEAEEEEEEAEE<EEAEE<</AEAEEEE/EEAE</E/EEEE/AE:**HKYCVBGXN**:2:22102:22206:6319 163 chrIV 1094186

The bolded section is part of a new alignment joined onto the end of another alignment's quality string.  So something is messing up your sam file.

I've seen this before where stderr and stdout are writing to the same file.  Are you using minimap2 straight from the command line or are you using it indirectly (as part of a script or pipline)?

You could try explicitly writing to a file with minimap2 and see if that helps. e.g.
`minimap2 -ax sr ref.fasta sample_R1.fastq.gz sample_R2.fastq.gz -o sample.sam`

**Comment by rmormando** [comment]
I was using the command in a pipeline at first in order to read in samples from a list because I have over 100 samples I want to send through alignment. I just tried to do the alignment directly on the command line and I'm getting the same error:

```
head -3460217 sample.sam | tail +3460217

NB551191:1036:HKYCVBGXN:2:12301:6239:11726	147	chrVII	519632	60	147M4S	=	519594	-185	CGTCTACGCCAACCCCATCTTCAAAGGCATCCTCTCTGTTGCTTACACCATCAACATCCTCTTTAAGTCAGGTTGCTACAAATACTAATGTACAGACGAGTTTAACAACGGAATCGACGACCGTTTTAGAACCATCAACGACTAACACTCG	EEEAEA6<<<AA//AA/EAEEA/<A<A<AAE<EAE/A<AEAEEAE</EEEEEAEEEAEEE/A/EE/EEEAE/AEAEEEEEEEEEEAEEEEAEEAA<EEEE6EEE/E/A6EEEEEEE/EAEEEAEEEEEEEEEEEEEEEEAAEE/EGTAGAGAAAAACGAAATTGGCAAGATGTACGATGAGTACCTGGGCTCCCACACGGACCAACCGGTCAACGTGCTGCTGGTACAGAGCCTCAATACCC	EEEEEEEEEEEEEEAEEEEAEEEEAEEEEEEEEEEEEEEE<AAEAEE/EEEEEEEEEEEEEEEAAEEEEEEEEEEEEEE/AEEEEEEEEEAEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEAEEEEEEEEEEEEEEEEEEEEEAAAAA	NM:i:2	MD:Z:8C109C28	MC:Z:4S147M	MQ:i:60	AS:i:137	XS:i:0
```
(this was with a different sample so it's a different coordinate with the error)

**Comment by daviesrob** [comment]
Your output suggests that you've still got two reads glued together in a way that's not supposed to happen.  All those `^@^@^@^@` characters (which are actually zeros in the file) make me suspect some sort of filesystem or hardware problem.  Do you have another machine you could try to see if minimap2 works there?

You could also try running this (you may need to use `md5sum` instead of `md5` depending on the software you have installed locally):
```
minimap2 -ax sr ref.fasta sample_R1.fastq.gz sample_R2.fastq.gz | tee sample.sam | md5

md5 sample.sam
```

The two hex strings from `md5` should match.  If they don't minimap2's output isn't being stored correctly.  If they do, I'd suspect either the input files, or something going wrong inside `minimap2`.

**Comment by rmormando** [comment]
can the same command be run for bwa? I want to switch over to this alignment tool for now since I want to call variants with GATK after the alignment (and for some reason GATK doesn't work right with minimap2 alignments...)

**Comment by daviesrob** [comment]
Yes, it should work.

**Comment by rmormando** [comment]
Okay so it looks like the md5 string matches when calling both of those commands:
`90c2476c2a9df136178142069f54b5db`
`MD5 (sample.sam) = 90c2476c2a9df136178142069f54b5db`

So I think it might be code I'm using to run through the samples? I can't imagine why that would be happening but this is the code I'm using to run minimap2/bwa:

```
#!/bin/bash

# move into directory with tool
cd /Volumes/MyPassport/TOOLS/minimap2

REFERENCE="/path/to/reference.fasta"

file="/path/to/listofSequences.txt"

while read -r line; do
R1="/path/to/files/${line}_R1.fastq.gz"
R2="/path/to/files/${line}_R2.fastq.gz"

OUTPUT_DIRECTORY="/path/to/output/${line}"
mkdir ${OUTPUT_DIRECTORY}

SAM_OUT="${OUTPUT_DIRECTORY}/${line}_reference.sam"

./minimap2 \
	-ax sr \
	${REFERENCE} \
	${R1} ${R2} \
	-o ${SAM_OUT}
done <$file

echo Run Complete!
```

It reads in a text file that's a list of all the sample IDs separated by a new line - I know everything here works correctly and I made sure nothing else was running on my local machine while this ran through all the samples but now it won't convert the sam to bam with the same error messages and half the time if I do get a bam file to generate I can't index it

**Comment by whitwham** [comment]
You're script looks fine to me.  If there is something wrong with it I can't see it with a quick read through.

As @daviesrob said, it may be a hardware/filesystem error.  That would not be something that we could diagnose.

**Comment by daviesrob** [comment]
Did the `sample.sam` file you made work when read by `samtools`?  If not, you might want to check the inputs, e.g. try `gunzip -t` or `bgzip -t` on the `fastq.gz` files to check they're OK.  If you have another copy of the reference, you could try comparing that to the one you're using to check they're the same.  You may also want to try `md5` on `sample.sam` again to check it hasn't changed once the file has been flushed out of the cache and has to be read back in from storage.

You could also try looking for runs of zero bytes in your files using something like this:
```
perl -ne 'BEGIN { $t = 0; } while (/\x00+/g) { print $t+@-[0],"\n"; } $t += length($_)' ref.fasta
```

They shouldn't appear at all in any text files (sam, fasta) or uncompressed `fastq.gz` files.

If the inputs are OK but the output isn't, the problem may be occurring somewhere inside `minimap2`.

**Comment by jkbonfield** [comment]
I've also seen blocks of nuls in files when there is more than one process attempting to write to the file at the same time.  This could happen if you accidentally have a duplicate entry in your list of samples for example (provided you're submitting jobs in parallel rather than sequentially).

Either way, if you can detect nuls in the text SAM input before feeding into samtools sort then the problem lies elsewhere.  If it's a direct pipe, then that's trickier (without a `tee` to save the data for subsequent debugging).

**Comment by daviesrob** [comment]
Closing, as while we haven't quite worked out what was going on here, it looks like the problem occurred before `samtools` was involved.
