### ISSUE TITLE
samtools view: error reading file ".." input/output error

### ISSUE THREAD

**Issue by figbeirns** [samtools/samtools#1941]
samtools --version-only output: 1.18+htslib-1.18

 #### Please describe your environment.
- Linux
- x86_64
- 8.5.0 20210514 (Red Hat 8.5.0-18)

I'm running samtools view to convert .sam files to .bam files. I've run samtools quickcheck and that comes up empty, so I assume the input file is fine. My code is:

samtools view -@36 -b --verbosity 8 ${filepath}/01_GR1P1biofilm.aligned.sam -o ${filepath}/02_GR1P1biofilm.aligned.bam

This produces the output .bam file, however it also generates the following error messages:

samtools view: error reading file "/filepath/01_GR1P1biofilm.aligned.sam": Input/output error
samtools view: error closing "/filepath/01_GR1P1biofilm.aligned.sam": -5

How can samtools produce an output if it supposedly can't read it? Can I ignore the error message and use the output file?

**Comment by jkbonfield** [comment]
Does it get this error immediately, or after some time?  Does it still error when not using threads?

If it's immediate, does doing `strace -f samtools view ${filepath}/01_GR1P1biofilm.aligned.sam -o ${filepath}/02_GR1P1biofilm.aligned.bam` show a cause for the I/O error?  I'm not sure what quickcheck would do on minimal files such as an empty one.  It's easier for it to validate BAM where there are clear signatures and an EOF marker, than it is SAM, so I wouldn't rely on it as evidence the SAM is correct.

I assume you've done `head` and `tail` to also check the SAM file at least is valid.

**Comment by figbeirns** [comment]
Some time passes. As I said, an output file is generated, so it's doing something. The input .sam file is 60GB and the output .bam file is 11GB. I don't know if it's worth noting that the error output remains completely empty until the job is completed.

I've run samtools head and there are SQ lines, so I'm pretty sure the file is valid. I'm not sure what you mean by tail, since there isn't a tail command in the samtools manual
I'm using my organisations HPC service and I've filled up about 60% of my allotted space, so I don't expect I'm running into a space issue.

I've just rerun the same code without the threads and the error message has changed! I still get an output .bam file and now the error message is:
`W::sam_read1_sam] Parse error at line 130968094
samtools view: error reading file "filepath/01_GR1P1biofilm.aligned.sam"`

**Comment by whitwham** [comment]
>  I'm not sure what you mean by tail, since there isn't a tail command in the samtools manual

@jkbonfield means using the linux **tail** command:

`tail ${filepath}/01_GR1P1biofilm.aligned.sam`

**tail** by default will show the last 10 lines of a text file.  On a 60GB file it will take some time, but it will show us what the end of your sam file looks like.

**Comment by figbeirns** [comment]
I've done a line count using `wc -l ${filepath}/01_GR1P1biofilm.aligned.sam` and that is telling me that there are 130968093 lines in the file. The error from samtools is `[W::sam_read1_sam] Parse error at line 130968094`. Which is one more than the line count, so that's confusing

I've also run `tail ${filepath}/01_GR1P1biofilm.aligned.sam` and the output is:
`A00551:680:HVC2MDSX5:2:2678:9742:18991.2:N:0:ACTCGATGTG+GTAGGACTCA#0	153	k141_668718	3051	42	150M	=	3051	0	ATTGCAGATGACATATTTGACATAATCATCAATACATAAAATATCACCTTGGTCTAAAATTTTACTGTCGGTGTTAATTTCGATTTTTGAAAAGTCACTCTCTTCGTTAGGATCAGTGCTACAAATAATAGCACGTTTACCTTCTAGGAT	FF:FFFFFFFFFFFF:FFFFFFFFFF:F:FFFFF:FFFFFFFFFFFFFFFFF:FFFFFFFFFFFFFFFFFFFFFFFFF,:FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF	AS:i:0	XN:i:0	XM:i:0	XO:i:0	XG:i:0	NM:i:0	MD:Z:150	YT:Z:UP
A00551:680:HVC2MDSX5:2:2678:8377:31908.1:N:0:ACTCGATGTG+GTAGGACTCA#0	101	k141_668718	3051	0	*	=	3051	0	AGGTTATCAATTCATACAGTATCTTCCAGCAAACTCCATTGCTATTGGAGATAAAGGTTATGTTTCGTCAAAGTTAGAAGCTTTTTTAAAACGATTTGATATTGTCCTAGCACCCATTGGGCGTAATAATATGTCAAAAGTAAACAAAGA	FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF:FFFFFFFFFFFFFFFFFFFFFFFFF:FFFFFFFFFFFFFFFFFFF,FFFF:FFFFFF:FFFFFFFFFFFFFFFFFFFFFF:FFFFFFFFFF:FFFFFFFFF:FF:	YT:Z:UP
A00551:680:HVC2MDSX5:2:2678:8377:33004.1:N:0:ACTCGATGTG+GTAGGACTCA#0	81	k141_142876	36342	42	150M	k141_557134	811	0	TATTGAGTTACCGTTTATAATGTATTCCAAGCCATTCAAAAACCGTAAGCCACCAGAGGCGCGAATTCTGAGGTTTGGAAACAAAGTGAGTCTCATCAGGAAAATATAAAAACTTACTCTTCACCCCAAGCCGCTGAAGCGATGTGAACA	FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF:FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF:FFFFFFFFFFFFFFFFFFFFFFFF:FFFFFFFFFF:FFFFFFFFFFFFFFFFFF	AS:i:0	XN:i:0	XM:i:0	XO:i:0	XG:i:0	NM:i:0	MD:Z:150	YS:i:0	YT:Z:DP
A00551:680:HVC2MDSX5:2:2678:9742:19554.2:N:0:ACTCGATGTG+GTAGGACTCA#0	161	k141_557134	811	42	150M	k141_142876	36342	0	GACATCGTCCTGCTGGACATCGGACTACCCGGCGAGGACGGGTTTTCCATCGCGGGGCGACTCCACCGAGAATACCCCCGGATCGGCATCATCATGCTCACCTCCCGCGATCGGGTTGACGATCGCGTGCAGGGACTGGATTGCGGGGCA	FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF::FFFFFFFFFFFFFFFFFFFFFFF,FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF:FFFFFFFFFFFFFFFFFFFF:FFFFF:	AS:i:0	XN:i:0	XM:i:0	XO:i:0	XG:i:0	NM:i:0	MD:Z:150	YS:i:0	YT:Z:DP
A00551:680:HVC2MDSX5:2:2678:8377:33974.1:N:0:ACTCGATGTG+GTAGGACTCA#0	73	k141_229416	55616	42	150M	=	55616	0	AAAATGCTGCGATTCCAGTTGTTAATGGTATTCCTGCGGCGATTGTCGCAGCAATCGCCAATGCGACAATGACCGAAACTATTTTCCTTATCCCTGGTCTTGGTAAAATGTTACCAGATTCGATTGCTGCCAATAACAGTCCGATGGTTG	FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF:FFFFFFFFFFFFFFFFFFFFFF	AS:i:0	XN:i:0	XM:i:0	XO:i:0	XG:i:0	NM:i:0	MD:Z:150	YT:Z:UP
A00551:680:HVC2MDSX5:2:2678:9742:20087.2:N:0:ACTCGATGTG+GTAGGACTCA#0	133	k141_229416	55616	0	*	=	55616	0	TTTATCGCTTTAATAGTAAATGGAGGTTAATAAAATACCAAAAAGGCCTTCCCCTCTGTCGGAAAAGGCCTTCTTTACAAATTCTGCAGATGGGTGAAATTATTTCACGCCAACAAATTCTTTTACTTTATCGTTCGGTACAATGTCTTC	FFFFFFF:FF:F,F::F:FFFFFFFFFFFFFFFFFFFF:FFFFF:FF:FFF:FFFFFF:F:FFFFFFFFFFFFFFFFFFFFFFFFF:FFFFFF:FFFFFF,FFFF:FFF:FFFFFFFFFFF,F:F:F:F:FF:FFFFFFF,FFFFFFFFF	YT:Z:UP
A00551:680:HVC2MDSX5:2:2678:8377:34100.1:N:0:ACTCGATGTG+GTAGGACTCA#0	113	k141_579104	5605	42	150M	k141_691116	1489	0	TACATTATGTTTTTTAATGCTGTCCTGTATAAATCCAAAACCTTTTGTGGTGTCAAAAAATATAACGGTACCGGTTTTTATGGGCGAATTATCTTCAGTATTTCTGTCGCGTGGAATATTAATTTCAATATCCTCTGCTATCACTTTAGT	FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF::FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF:FFFFFFFFFFFFFFFFFFFFFFFF:FFFFFFFFFFFFFFF	AS:i:0	XN:i:0	XM:i:0	XO:i:0	XG:i:0	NM:i:0	MD:Z:150	YS:i:-15	YT:Z:DP
A00551:680:HVC2MDSX5:2:2678:9742:21934.2:N:0:ACTCGATGTG+GTAGGACTCA#0	177	k141_691116	1489	42	150M	k141_579104	5605	0	GATAACATATAGTAATTTATAATTTAATAATTTACGATTTACAATTGATTGTAAGATCGTTTGAGAAGTTGATATAAGTATTAAAAAAAACTTTCCGTCGATGGGCTTTGTAAGTCTATGACGGAAAGTTTTGTGTATCGAAGGTATGAT	FFFFF,FFFFF:FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF:FFFFF,FFFF:FF:FFF:F:FFFFF::FF,FFFFFFFFFFFFFFFFFFFFFFFFFFFFF:FFFFFFFFFFFFFFFFF,:FFFFFFFFFFFFFFFFFFFF	AS:i:-15	XN:i:0	XM:i:3	XO:i:0	XG:i:0	NM:i:3	MD:Z:46A2A7G92	YS:i:0	YT:Z:DP
A00551:680:HVC2MDSX5:2:2678:8377:35164.1:N:0:ACTCGATGTG+GTAGGACTCA#0	113	k141_324769	7613	42	150M	k141_390219	327	0	GCGATTTCAGCGCCATCTAATTTTATGATTGAAGCGGTTTCTTCTACGCTGGTGGTTCTAATCCCAAACAAACTTACTATAATGATTTTTTTTGCATCTTTAAATGCCGAAAAAAGAGGGGCCTTTGTTTTTGAAATAATCACATCAAAT	FFFFFFF:FFFF:FFFFFF:FFFF,FFFFF:FFFFFFFFFFFFFFFFF:FFFFFFFF:FFFFFF,FF:::FFFFFFFF:FF,FF,FFFFFF:FF:FFFFFFFFFFFFF:F:FFF,FFFFFFFFFFFFF:FFF:FFFFFFFFFFFFFFFFF	AS:i:0	XN:i:0	XM:i:0	XO:i:0	XG:i:0	NM:i:0	MD:Z:150	YS:i:0	YT:Z:DP
A00551:680:HVC2MDSX5:2:2678:9742:22310.2:N:0:ACTCGATGTG+GTAGGACTCA#0	177	k141_390219	3`

It looks like that final line is incomplete, but no errors were produced by bowtie when I did the initial alignment

**Comment by figbeirns** [comment]
Is it possibly because I have less reads in PE1 than I do in PE2?

**Comment by whitwham** [comment]
It is not just an incomplete line, it looks like bowtie did not even finish writing out the position (POS) entry on that line.  The two most likely things I can think of is that you ran out of disc space (seems unlikely with your quota) or that bowtie stopped running prematurely.

**Comment by jkbonfield** [comment]
That's definitely truncated output, so it's correct that samtools sort is erroring, although the error message could be better.   I think part of the problem is when it's multi-threading it's harder to propagate the exact error from one of the child threads all the way back up to the main one, so it's becoming a generic "I/O error" instead of the specific issue.

It sounds like bowtie silently failed.  I don't know if a different number of reads in PE1 and PE2 would make it fail in that manner, but it's not good as if they got out of sync then the alignments are likely being given incorrect mapping qualities and wrong read-pairing data.  Either that or the disk was full at the time the command failed, giving truncated output.

**Comment by figbeirns** [comment]
Ok, I'll investigate bowtie and potentially go back to kneaddata to sort out the desynced pairing. Thank you for your suggestions on how to check things! Seems it wasn't a samtools issue at the root, but I agree with jkbonfield, the error message could have been better
