### ISSUE TITLE
Problem with compilation of samtools 1.18

### ISSUE THREAD

**Issue by thierrygrange** [samtools/samtools#1942]
#### Are you using the latest version of [samtools](https://github.com/samtools/samtools/releases/latest) and [HTSlib](https://github.com/samtools/htslib/releases/latest)? Yes 1.18 just downloaded today
(run `samtools --version`)

 #### Please describe your environment.
- OS Linux 3.10.0-1160.99.1.el7.x86_64
- machine architecture x86_64
- compiler (gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-44)

#### Please specify the steps taken to generate the issue, the command you are running and the relevant output.
during compilation I received the following error message:
bam_tview_curses.c:42:20: fatal error: curses.h: No such file or directory
Is there a problem with my environment or with this last version I downloaded from https://www.htslib.org/download/ today November 15 2023? 
Thanks for your insights

**Comment by whitwham** [comment]
Were any problems mentioned when you ran **./configure**?

**Comment by thierrygrange** [comment]
The error message with configure:

configure: error: curses development files not found

The 'samtools tview' command uses the curses text user interface library.
Building samtools with tview requires curses/ncurses/etc development files
to be installed on the build machine; you may need to ensure a package such
as libncurses5-dev (on Debian or Ubuntu Linux) or ncurses-devel (on RPM-based
Linux distributions) is installed.

FAILED.  Either configure --without-curses or resolve this error to build
samtools successfully.

Should I do it without curses or install curses independently before?

Best

Thierry


________________________________
De : Andrew Whitwham ***@***.***>
Envoyé : mercredi 15 novembre 2023 18:45:17
À : samtools/samtools
Cc : GRANGE Thierry; Author
Objet : Re: [samtools/samtools] Problem with compilation of samtools 1.18 (Issue #1942)


Were any problems mentioned when you ran ./configure?

**Comment by thierrygrange** [comment]
problem fixed after I run yum install ncurses-devel Thanks


________________________________
De : GRANGE Thierry
Envoyé : mercredi 15 novembre 2023 18:53:00
À : samtools/samtools; samtools/samtools
Cc : Author
Objet : RE: [samtools/samtools] Problem with compilation of samtools 1.18 (Issue #1942)


The error message with configure:

configure: error: curses development files not found

The 'samtools tview' command uses the curses text user interface library.
Building samtools with tview requires curses/ncurses/etc development files
to be installed on the build machine; you may need to ensure a package such
as libncurses5-dev (on Debian or Ubuntu Linux) or ncurses-devel (on RPM-based
Linux distributions) is installed.

FAILED.  Either configure --without-curses or resolve this error to build
samtools successfully.

Should I do it without curses or install curses independently before?

Best

Thierry


________________________________
De : Andrew Whitwham ***@***.***>
Envoyé : mercredi 15 novembre 2023 18:45:17
À : samtools/samtools
Cc : GRANGE Thierry; Author
Objet : Re: [samtools/samtools] Problem with compilation of samtools 1.18 (Issue #1942)


Were any problems mentioned when you ran ./configure?

**Comment by jkbonfield** [comment]
The [INSTALL](https://github.com/samtools/samtools/blob/develop/INSTALL) file describes the purpose of ncurses, which is mainly the `samtools tview` command.  If you build with curses disabled then basically that's the only thing that is missing.

Also the full list of dependencies are listed in INSTALL here, with https://github.com/samtools/samtools/blob/develop/INSTALL#L222-L229 detailing the commands necessary for RedHat based systems.
