### ISSUE TITLE
samtools: error while loading shared libraries: libcrypto.so.10: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by vini8cs** [samtools/samtools#1943]
- OS: Linux 5.15.0-88-generic
- machine architecture: x86_64
- compiler: gcc (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0

I'm getting this error doesn't matter which version I'm using: "samtools: error while loading shared libraries: libcrypto.so.10: cannot open shared object file: No such file or directory". I installed with conda. What is happening? I couldn't find anyone with the same issue.

**Comment by whitwham** [comment]
Are you using conda?  This sometimes crops up with that.

**Comment by whitwham** [comment]
Sorry, you have already said it was with conda.  How exactly did you install it?

**Comment by vini8cs** [comment]
> Sorry, you have already said it was with conda. How exactly did you install it?

**Comment by vini8cs** [comment]
I used the command "conda install -c bioconda samtools=1.18". And I've tried past versions, such as 1.17, 1.9, and so on. The error is still the same

**Comment by jkbonfield** [comment]
See https://github.com/samtools/samtools/issues/1714 or the [previous issues](https://github.com/samtools/samtools/issues?q=is%3Aissue+conda+libcrypto+) related to this.

This is a common problem with conda configurations, which tend to be extremely fragile.

**Comment by whitwham** [comment]
It could be conda-forge channel is not activated.  Look at [this](https://www.biostars.org/p/455593/#455593) Biostars answer.  As @jkbonfield says, the conda configurations are not always the most reliable.

**Comment by vini8cs** [comment]
It's weird because no one had a problem similar to mine. Every topic is talking about a problem related to "libcrypto.so.1.0.0". Mine is related to "libcrypto.so.10". None of the solutions are working for me.

**Comment by jmarshall** [comment]
We all assumed “libcrypto.so.10” was a typo, because that is a very uncommon filename soversion to have for this file.

The only “libcrypto.so.10” files that google finds are built for the RHEL, Alma, Fedora, etc distributions. However you say you are using Ubuntu.

It is possible that you have also installed a samtools package from one of these RPM-based distributions? What does `which samtools` say, and is that the samtools on the path you think you are installing via conda? However, really this is a problem that will be best solved by someone knowledgable at your university who can look over your shoulder and test things on your command line.

**Comment by vini8cs** [comment]
It's Ubuntu. 100% sure. I found out the problem. Because I was creating the environment and downloading it without sudo, the samtools was being installed in a directory without this file. When I used sudo, the software was installed perfectly. But I really don't understand why samtools was requesting libcrypto.so.10 since it is not aimed to Ubuntu. Unfortunately, I'm the most knowledgeable person at my university in term of developing pipelines and using conda, at leat in my lab kkkkkkk

**Comment by yinshiyi** [comment]
@vini8cs I ran into the exact same problem, I have some pre-existing env, then I copy them into a new server, (forgot if I use sudo), then in this new server, all the conda is giving this error `libcrypto.so.10`. 
did you solve this by doing `sudo conda install samtools`
