### ISSUE TITLE
return non-zero exit status 1 when running samtools sort using subprocess.run

### ISSUE THREAD

**Issue by yeeus** [samtools/samtools#1944]
#### Are you using the latest version of [samtools](https://github.com/samtools/samtools/releases/latest) and [HTSlib](https://github.com/samtools/htslib/releases/latest)? If not, please specify.
(run `samtools --version`)
```
samtools --version
samtools 1.18
Using htslib 1.18
```
 #### Please describe your environment.
- OS (run `uname -sr` on Linux/Mac OS or ` wmic os get Caption, Version` on Windows)
```
uname -sr
Linux 3.10.0-1160.el7.x86_64
```
- machine architecture (run `uname -m` on Linux/Mac OS or ` wmic os get OSArchitecture` on Windows)
```
x86_64
```
- compiler (run `gcc --version` or `clang --version`)
```
gcc --version
gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-44)
```

#### Please specify the steps taken to generate the issue, the command you are running and the relevant output.
I used `samtools sort` in python by using subprocess.run
Here is my code:
```
subprocess.run(f'samtools sort {file} -o {directory}/{random_string}.bam', shell=True, capture_output=True, check=True)
```
Then this got:
```
subprocess.CalledProcessError: Command 'samtools sort ./mq_10_30.filter.bam -o ./Kqv7T7aNZ1.bam' returned non-zero exit status 1.
```
and next I check the stderr, I got
```
b'[W::hts_set_opt] Cannot change block size for this format\nsamtools sort: failed to read header from "./mq_10_30.filter.bam"\n'
```

Interestingly, when I run the same command in the terminal, it got no problems:
```
samtools sort ./mq_10_30.filter.bam -o ./Kqv7T7aNZ1.bam
samtools view ./Kqv7T7aNZ1.bam | less -S
```
![image](https://github.com/samtools/samtools/assets/118142448/c1cb57c7-043a-4afe-98fa-de34cb7a9835)

It looks nice, so anyone had encountered this problem???
Best wishes!

**Comment by daviesrob** [comment]
It looks like the sort run via python didn't like your input file.  Was it exactly the same file as when you ran on the terminal, or did you re-create it for the terminal run?

If it's not the same file, you probably need to look at the process before `samtools sort` that created the input.

**Comment by yeeus** [comment]
Sorry for being late to reply. I figured out the reason yesterday and that because I forgot to close the file when I created the bam using pysam.
