### ISSUE TITLE
Samtools merge

### ISSUE THREAD

**Issue by bsb2014** [samtools/samtools#1960]
SYNOPSIS
samtools merge [options] -o out.bam [options] in1.bam ... inN.bam
samtools merge [options] out.bam in1.bam ... inN.bam

I am wondering if samtools merge also works for SAM and CRAM. Thanks.

**Comment by daviesrob** [comment]
Yes, it does work on all three formats.  It will automatically detect the input file formats.  The output format can also be either sam, bam or cram and does not have to be the same as the one used for the inputs.
