### ISSUE TITLE
Set `samtools depth -s` as default?

### ISSUE THREAD

**Issue by schorlton** [samtools/samtools#1964]
Thanks for all of your work on samtools. This is a somewhat controversial proposal so I thought I'd initiate discussion before opening a PR.

In my view, `samtools depth -s` (ie only count overlaps once) should be the default setting. Apologies if this has been proposed, but I actually couldn't find it. The default to count overlaps once seems to be supported by the bioinformatics community (https://bioinformatics.stackexchange.com/questions/5427/double-counting-coverage-of-overlapped-read-pairs), would make `depth` consistent with `mpileup`, and is the behavior of alternative tools (eg. coverm).

I realize this may break or alter the behavior of workflows for some groups. However, I believe the cost of not doing this is greater than the cost of making the change. Very often, I see groups using `samtools depth` without this flag, comparing their results between pipelines (some with the flag), and making inaccurate conclusions based on sequencing depth. Reviewing the GitHub issues, I believe there are also some which question the difference between `depth` and `mpileup`.

Therefore, would the maintainers consider a PR to set `-s` to default of `samtools depth`?

**Comment by whitwham** [comment]
On the one hand, yes, counting overlaps once would be the better default but, on the other hand, I think you are underestimating the amount of chaos changing the default behaviour would be.

> I realize this may break or alter the behavior of workflows for some groups

Not just that, if different version of **depth** behaved differently then no one would know what to expect.  Not everyone uses the most recent version of samtools and people often do not check which version they are using.  So two different groups could have two different sets of results with the same data and using exactly the same command but with different versions.

If we did a samtools version 2 we could change it or we could add a **depth2** command, which would be exactly the same as **depth** but with different defaults.  We cannot really change the defaults on **depth** though, it has been around too long to make that viable.

**Comment by schorlton** [comment]
Thanks @whitwham for your input! Was waiting to see if any others wanted to weigh in but feel free to close whenever.

I do agree that it would be challenging and perhaps confusing for some, but this isn't unprecedented - many tools change their behaviour over time (including breaking changes) and maintain the same command. The important thing is to have a change management plan, clear communication through multiple channels, ample time to adjust workflows, etc. Mission critical users (eg. clinical) should be pinning their version of samtools and testing with each update.

Perhaps a version 2 of samtools would be the best for this change, but are there any plans for that? If not, you could imagine that users are still double counting overlaps 10 years from now...that to me (naively) seems like more cumulative bioinformatic errors and misinterpretations across the community than the users who would miss all of the notifications, blindly update their samtools (likely multiple times), and fail to include the new flag to disable adjustment for overlaps.

Any way, I'm super appreciative of the work you and the samtools team have done. Won't push for this any harder but if you decide that it is worth pursuing, I'm happy to contribute.
