### ISSUE TITLE
compilation of samtools-1.19. does not work on Linux Mint

### ISSUE THREAD

**Issue by mprous1** [samtools/samtools#1966]
I downloaded the latest version of samtools (https://github.com/samtools/samtools/releases/download/1.19/samtools-1.19.tar.bz2).

Did not get past ./configure --prefix=\$HOME/samtools

"checking for gawk... gawk
checking for gcc... gcc
checking whether the C compiler works... no
configure: error: in '/home/mprous/samtools-1.19':
configure: error: C compiler cannot create executables
See 'config.log' for more details"

config.log file is attached.

- OS Linux 5.15.0-91-generic
- machine architecture x86_64
- compiler gcc (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0

[config.log](https://github.com/samtools/samtools/files/13928774/config.log)

**Comment by daviesrob** [comment]
These lines are buried in your `config.log` file:

```
```

It looks like your gcc installation hasn't pulled in the libc development files that it needs to work for some reason.  [This stack exchange answer](https://unix.stackexchange.com/a/216857) suggests installing either the `libc6-dev` or `build-essential` package ought to fix it.

(Ubuntu [lists `libc6-dev` as "recommends"](https://packages.ubuntu.com/jammy/gcc-11), which is maybe why you didn't get it automatically.)

**Comment by mprous1** [comment]
Thanks! I got it to work with build-essential, but with additionally installing zlib from source (https://zlib.net/) (surprisingly it worked) and disabling several things iteratively based on error messages. Finally it worked this way:
./configure --prefix=\$HOME/samtools --without-curses --disable-bz2 --disable-lzma

samtools seems to work so far, although tried now only a few functions.

**Comment by whitwham** [comment]
I span up a VM with the latest Mint release and I managed to replicate your problem.

The step you were missing was to get the prerequisites before you run configure.  From the INSTALL file:

>   Debian / Ubuntu
> ---------------
>
> sudo apt-get update  # Ensure the package list is up to date
> sudo apt-get install autoconf automake make gcc perl zlib1g-dev libbz2-dev liblzma-dev libcurl4-gnutls-dev libssl-dev libncurses5-dev

After that, I could configure and make samtools without any trouble.

**Comment by mprous1** [comment]
Indeed, after installing these additional packages it worked without issues. Thanks again!
