### ISSUE TITLE
bgzip command unrecognised

### ISSUE THREAD

**Issue by chinnyy** [samtools/samtools#1967]
I am currently running samtools v1.15.1 on linux.

I am trying to run bgzip, however I get the error "bash: bgzip: command not found..."

**Comment by whitwham** [comment]
bgzip is part of htslib.  Have you installed that too?

**Comment by chinnyy** [comment]
Yes, it is installed too.

**Comment by whitwham** [comment]
How did you install it?  Where did you install it?  What is your setup?  Work with me @chinnyy, if you continue to provide the minimum possible details I am not going to be able to help you.
