### ISSUE TITLE
samtools view -L with same inputs outputs different reads in 1.19.1 vs 1.19.0

### ISSUE THREAD

**Issue by astaric** [samtools/samtools#1974]
#### Are you using the latest version of [samtools](https://github.com/samtools/samtools/releases/latest) and [HTSlib]samtools 
samtools 1.19.1

 #### Please describe your environment.
Darwin 23.2.0
(using bioconda build of samtools, environment to reproduce can be created with
`conda create -n samtools-1191 -c bioconda -c conda-forge samtools=1.19.1`)

#### Please specify the steps taken to generate the issue, the command you are running and the relevant output.
Using the command
```
samtools view -L bed.txt sam.txt
```

using the following files input files:
[bed.txt](https://github.com/samtools/samtools/files/14022263/bed.txt)
```
chrX  133551173 133551336
chrX  123220438 123220646
chr11 32417784  32418003
```

[sam.txt](https://github.com/samtools/samtools/files/14022264/sam.txt)
```
@HD VN:1.5  SO:coordinate
@SQ SN:chr11  LN:135006516
@SQ SN:chrX LN:155270560
VH00330:4:AAAGCGNM5:1:1203:10657:15502  147 chrX  123220531 60  29M1I121M = 123220410 -271  TCAGCAGCCGGGGGTCAACAGTACGGAGTAAAAAAATCAAAACCATCTACAGGAAAACGGAAAGTGGTTGAGGGCATGCAGCTTTCACTCAGTAAGGATATAATTTATTCTCTTTATATTTATCCCTAATGTTTACCAACTGAATTGTCAT ;CCC;CCCCCCCCCCCCCCCCCCCCCCCC;CC;CCC;CCCC;CC;CCCCCCCCCCCCCCCCCCCCC;CCCCCCCCCCCCCCCCC-CCCCCCCCCC;CCCCCCC-CCCCCCCCCC;CCCCCCCCCCCCCCCCCCCCCCCCC-CCCCC-CCCC NM:i:1  MD:Z:150  MC:Z:97M  AS:i:143  XS:i:0  RG:Z:ATCCGTCTCAAGCTGAGG
```

samtools 1.19.1 outputs no reads while samtools 1.19.0 (and earlier) outputs one read.

**Comment by daviesrob** [comment]
I think this is happening because the `chrX` entries in your BED file are not in order.  Sorting it gets the expected output:

```
$ sort -k1,1 -k2n,2 bed.txt > bed2.txt

$ cat /tmp/bed2.txt 
chr11	32417784	32418003
chrX	123220438	123220646
chrX	133551173	133551336

$ ./samtools view -L bed2.txt sam.txt
VH00330:4:AAAGCGNM5:1:1203:10657:15502	147	chrX	123220531	60	29M1I121M	=	123220410	-271	TCAGCAGCCGGGGGTCAACAGTACGGAGTAAAAAAATCAAAACCATCTACAGGAAAACGGAAAGTGGTTGAGGGCATGCAGCTTTCACTCAGTAAGGATATAATTTATTCTCTTTATATTTATCCCTAATGTTTACCAACTGAATTGTCAT	;CCC;CCCCCCCCCCCCCCCCCCCCCCCC;CC;CCC;CCCC;CC;CCCCCCCCCCCCCCCCCCCCC;CCCCCCCCCCCCCCCCC-CCCCCCCCCC;CCCCCCC-CCCCCCCCCC;CCCCCCCCCCCCCCCCCCCCCCCCC-CCCCC-CCCC	NM:i:1	MD:Z:150	MC:Z:97M	AS:i:14XS:i:0	RG:Z:ATCCGTCTCAAGCTGAGG
```

Although this is a bit odd as the entries are supposed to be [sorted](https://github.com/samtools/samtools/blob/8f34ff4eed1f55e90cece374a8f0d57478a07934/bedidx.c#L146) after they've been read so I'll have to see what's going on there.

**Comment by astaric** [comment]
@daviesrob, thanks for a quick reply

I also noticed that sorting the bed file helps, and so does removing the irrelevant chr11 line from the bed file. (I spent some time coming up with a minimum example that could reproduce the issue). samtools 1.19 and 1.15 (did not test other versions) produce expected result even with bed file in original (unsorted) order so it seems that the change was introduced in the last couple of commits.

```
$ cat /tmp/bed2.txt 
chrX	133551173	133551336
chrX	123220438	123220646

$ samtools view -L bed2.txt sam.txt
VH00330:4:AAAGCGNM5:1:1203:10657:15502	147	chrX	123220531	60	29M1I121M	=	123220410	-271	TCAGCAGCCGGGGGTCAACAGTACGGAGTAAAAAAATCAAAACCATCTACAGGAAAACGGAAAGTGGTTGAGGGCATGCAGCTTTCACTCAGTAAGGATATAATTTATTCTCTTTATATTTATCCCTAATGTTTACCAACTGAATTGTCAT	;CCC;CCCCCCCCCCCCCCCCCCCCCCCC;CC;CCC;CCCC;CC;CCCCCCCCCCCCCCCCCCCCC;CCCCCCCCCCCCCCCCC-CCCCCCCCCC;CCCCCCC-CCCCCCCCCC;CCCCCCCCCCCCCCCCCCCCCCCCC-CCCCC-CCCC	NM:i:1	MD:Z:150	MC:Z:97M	AS:i:143	XS:i:0	RG:Z:ATCCGTCTCAAGCTGAGG
```

**Comment by daviesrob** [comment]
Yes, rather embarrassingly, two new checks for failure in the revised BED indexing code were inverted.  As these bugs cancelled each other out, the problem wasn't evident on sorted BED inputs, apart from filtering with large BED files would have slowed down.  It broke sorting on all but one reference though, so filtering against a BED file where the start locations are not in order stopped working correctly.

Pull request #1975 should fix this.
