### ISSUE TITLE
flag names not checked for validity

### ISSUE THREAD

**Issue by notestaff** [samtools/samtools#1977]
#### Are you using the latest version of [samtools](https://github.com/samtools/samtools/releases/latest) and [HTSlib](https://github.com/samtools/htslib/releases/latest)? If not, please specify.
(run `samtools --version`)
1.19.2

When specifying samtools flags using symbolic strings, samtools doesn't raise an error if an invalid symbolic flag name is used.
E.g. writing samtools view -c -f UMAP myfile.bam (using UMAP instead of the correct UNMAP) silently outputs 0.

**Comment by whitwham** [comment]
Good find, and there are three other tools that have the same problem.
