### ISSUE TITLE
Creation of CRAM with view ignores -T reference

### ISSUE THREAD

**Issue by dkj** [samtools/samtools#198]
(As alluded to in #155) there's a -T option to view whose description suggests that a reference can be provided. This is not used (as of 0.2.0-rc7 7a871697ba5a5ab4e724f8b2a287c5beca62a52e ) for CRAM file creation (either from SAM or BAM). CRAM file generation, which requires the reference, uses the UR field in the SAM or BAM file SQ headers to find the reference (or M5 field if appropriate environment variable is set?). I think this should be overridden if a valid reference is provided with the -T option.

**Comment by tfenne** [comment]
I'm trying to debug a case where converting CRAM -> BAM with `samtools view` appears much slower than I expect.  Does anyone know if the scenario described above is still true (i.e. even when providing the reference via `-T`, the reference sequences are downloaded by MD5)?

**Comment by jkbonfield** [comment]
I just checked this and `samtools view -T ref.fa` overrides looking up MD5 files in $REF_PATH and also overrides any UR:/path tags in the SQ headers.

This was probably fixed years ago.
