### ISSUE TITLE
samtools consensus: Low coverage cutoff for Bayesian mode

### ISSUE THREAD

**Issue by gtrichard** [samtools/samtools#1982]
Currently samtools consensus supports a "min coverage" option, but that's only for the simple mode. After tweaking the Bayesian method parameters I tend to obtain better results than with the simple mode indeed. However calling a nucleotide when covered by only a single read is frigthening to say the least, especially when it's a mismatch compared to the reference and the mismatch is called nonetheless. 

I think the tool would greatly benefit from a "N masking" pass over the sequence to flag the positions that aren't deeply covered enough as N. This can be done at the end of the bayesian consensus sequence call. Or at the very least output them in lower letter for instance so the end user can easily flag these nucleotides and replace them with Ns.

**Comment by jkbonfield** [comment]
That seems like a reasonable request.  I assume however the quality for the single-depth reads will be low (as low as the read qual anyway).

**Comment by gtrichard** [comment]
Indeed, but in some edge cases you can have one or two very high quality reads with good mapping score as well which are used to call a sequence in the consensus. In my opinion it is a bit dangerous to do so and I would prefer to have "N" instead of the called sequence.

Looking forward to have this implemented 👍
