### ISSUE TITLE
samtools coverage histogram saved as png/svg

### ISSUE THREAD

**Issue by LandiMi2** [samtools/samtools#1986]
Is it possible to save the histogram output as png or svg?

**Comment by LandiMi2** [comment]
@nickzoic

**Comment by jkbonfield** [comment]
Currently no, but samtools coverage outputs a histogram in text form by default which is in a format trivially parseable by your favouring plotting tool.

Personally I think samtools shouldn't be concentrating on graphical reports, and instead should focus on data gathering, as whatever we do we'll be getting requests to change it to this method or that method - we could never keep everyone happy on the type of visual report we produce.
