### ISSUE TITLE
samtools fastq could merge pair members and output just a single FASTA/Q entry

### ISSUE THREAD

**Issue by mmokrejs** [samtools/samtools#1991]
Hi,
  there are many tools (bbmerge.sh from BBmap, NGmerge, VSEARCH, USEARCH, ...) which can look for some overlap between members of a FASTA/Q read pair but is there a tool which can use already mapped pair members to their common reference and just merge them, evtl. insert the needed `N`s as a linker in between with proper length? I have the original `.fastq.gz` files still around so it could maybe just act on position-sorted SAM/BAM and poke through the synced read pairs in `R1` and `R2` files and merge them accordingly (replace `N`s with a nucleotide from the other mate, eventually prefer higher `QUAL`)?

https://sourceforge.net/projects/bbmap/
https://drive5.com/usearch/manual/merge_pair.html
https://github.com/jsh58/NGmerge
https://cme.h-its.org/exelixis/web/software/pear/
https://gitlab.com/german.tischler/biobambam2/-/blob/master/src/programs/bamtofastq.1

Thank you,

**Comment by jkbonfield** [comment]
The intention of samtools fastq is very much to reverse the alignment process.  Ie to take an aligned file and reproduce something akin to the original instrument outputs so it can then be realigned with other tools and/or parameters.  This would be quite a departure from that goal.

So no, it cannot do this currently. I'll have to take a look at what other tools do, but this does feel a bit out of the normal remit for samtools fastq.

**Comment by jkbonfield** [comment]
There has been no other comments on this issue, and so I question the benefit of it being a core samtools command given the to-do list has lots on it.  (That's not to say it has a use, just the lack of responses seem to imply it's overly specialised.)

So closing this for now.  However if multiple groups suddenly start asking for the same functionality then we may reconsider.
