### ISSUE TITLE
Duplicated qname with different reads in pileup file

### ISSUE THREAD

**Issue by LongTianPy** [samtools/samtools#1992]
Hi, I'm using samtools v1.17 and I don't see my issue below addressed in the recent releases.

In some cases I see duplicated read names in the `qname` column and there are different bases reported in the `read bases` column. I use default `--min-BQ` and don't have `-x` enabled.

Here's the command that I use:
`samtools mpileup --output-QNAME -a --rf 3 -r {chromosome} -f {ref_genome_name} -o {output} --no-output-ins --no-output-del --no-output-ends {bam_name}`

I expect there is only one base reported for each read.

**Comment by jkbonfield** [comment]
I'm not sure what's going on, but I'd expected it to only report each read name once with the removal enabled too.
I can trivially reproduce this, so will explore.

**Comment by jkbonfield** [comment]
An example:

```
$ cat _n.sam
@HD	VN:1.5	SO:coordinate
@SQ	SN:1	LN:249250621
r1	147	1	100000	50	15M	*	0	0	CACTAAGCACACAGA	XXXXXXXXXXXXXXX
r1	99	1	100000	50	5M5D5M	*	0	0	CACTAACAGA	YYYYYYYYYY

$ samtools mpileup --output-QNAME _n.sam
1	100000	N	1	^Sc	~	r1
1	100001	N	1	a	~	r1
1	100002	N	1	c	~	r1
1	100003	N	1	t	~	r1
1	100004	N	1	a	~	r1
1	100005	N	2	a*	XY	r1,r1
1	100006	N	2	g*	XY	r1,r1
1	100007	N	2	c*	XY	r1,r1
1	100008	N	2	a*	XY	r1,r1
1	100009	N	2	c*	XY	r1,r1
1	100010	N	2	aA	XY	r1,r1
1	100011	N	1	c	~	r1
1	100012	N	1	a	~	r1
1	100013	N	1	g	~	r1
1	100014	N	1	a$	~	r1
```

It appears that deletions don't count as duplicates, unlike substitutions (where each read has a different call).  Insertions didn't trigger this behaviour too.

I still don't know why this is so, although I'm wondering what the impact would be on downstream analysis.

**Comment by LongTianPy** [comment]
Hi, thanks for looking into this.
In my cases, I see substitution and wild type for repeated reads, besides deletion and wild type.
And their base qualities aren't too different: 6 and 9 in ASCII characters.

I use pileup to get the haplotypes and this repeated reads issue gives me different haplotypes for the same read.
