### ISSUE TITLE
Duplicate reads on different flowcell tiles marked as "optical" duplicates

### ISSUE THREAD

**Issue by pwh124** [samtools/samtools#1996]
Hello,

I am attempting to classify duplicates from a NextSeq 2000 sequencing run as PCR or "optical."

In the course of doing this, I found that ~10% of reads that samtools called "optical duplicates" were on a different tile than the supposed "original" read (see more information below).

I thought a prerequisite for being called an "optical" duplicate was sharing of the same flowcell tile between the original and duplicate read?

Is this a bug? Why are reads on different tiles called as optical duplicates (SQ)?

Of note: I see the same behavior when running duplicate calling with Picard.

Thanks,
Paul

#### Are you using the latest version of [samtools](https://github.com/samtools/samtools/releases/latest) and [HTSlib](https://github.com/samtools/htslib/releases/latest)? If not, please specify.
(run `samtools --version`)

samtools 1.19

 #### Please describe your environment.
- OS (run `uname -sr` on Linux/Mac OS or ` wmic os get Caption, Version` on Windows)

Linux 5.15.0-94-generic

- machine architecture (run `uname -m` on Linux/Mac OS or ` wmic os get OSArchitecture` on Windows)

x86_64

- compiler (run `gcc --version` or `clang --version`)

gcc (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0

#### Please specify the steps taken to generate the issue, the command you are running and the relevant output.
- Sequencing was performed on a NextSeq 2000 Illumina instrument
- Data was aligned with bowtie2 and filtered for properly paired, primary alignments
- Ran samtools to identify duplicates:
`samtools markdup
-t 
-d 2500
-@48
-f optical_dups/k562.igg_2500.log
sorted_fixmate_collate_blacklist_sorted_filtered_k562_illumina_igg_rep1.bam
optical_dups/k562.igg_2500.bam`
- Pulled out original/dup read pairs using samtools/awk

> VH00570:6:AACT2KWM5:1:1308:29290:3726 VH00570:6:AACT2KWM5:1:2111:45158:26217
VH00570:6:AACT2KWM5:1:1308:29290:3726 VH00570:6:AACT2KWM5:1:2111:45158:26217
VH00570:6:AACT2KWM5:1:2309:51690:50354 VH00570:6:AACT2KWM5:1:2309:51918:50354
VH00570:6:AACT2KWM5:1:2304:55269:16032 VH00570:6:AACT2KWM5:1:1304:50459:13609
VH00570:6:AACT2KWM5:1:1304:50497:13495 VH00570:6:AACT2KWM5:1:1304:50459:13609
VH00570:6:AACT2KWM5:1:1304:38530:10655 VH00570:6:AACT2KWM5:1:1304:50459:13609
VH00570:6:AACT2KWM5:1:1304:47846:12548 VH00570:6:AACT2KWM5:1:1304:50459:13609
VH00570:6:AACT2KWM5:1:1304:43927:12681 VH00570:6:AACT2KWM5:1:1304:50459:13609
VH00570:6:AACT2KWM5:1:2210:16129:23510 VH00570:6:AACT2KWM5:1:2210:15561:24116
VH00570:6:AACT2KWM5:1:1306:50535:7702 VH00570:6:AACT2KWM5:1:2306:53679:4483

- Processed tile/x/y information for analysis in R
- Found ~10% of duplicates marked as SQ (optical) do not originate from the same tile (mismatched tile examples shown below).
![Screen Shot 2024-02-20 at 1 21 15 PM](https://github.com/samtools/samtools/assets/7634060/5b024920-99f9-4a6f-9a5e-dd9ad79a16b7)

**Comment by whitwham** [comment]
Try running it with `--no-multi-dup` to stop the duplicate chaining.

The details are [here](http://www.htslib.org/algorithms/duplicate.html) under the Duplicate Chaining heading.  If samtools and Picard are demonstrating the same behaviour this is where I would start.

**Comment by pwh124** [comment]
Thank you for a quick response, Andrew!

Adding `--no-multi-dup` seems to have fixed this.

Original command classification of dups on different flowcell tiles:
LB - 639489
SQ - 64547

Command with `--no-multi-dup` classification of dups on different flowcell tiles:
LB - 701597
SQ - 0

Thanks for the help! I will close the issue.

There are probably only a few people that care about quantifying this classification of duplicates, but it might be useful to have `--no-multi-dup` as the default when searching for optical dups or have some sort of note about this.

**Comment by whitwham** [comment]
> There are probably only a few people that care about quantifying this classification of duplicates, but it might be useful to have `--no-multi-dup` as the default when searching for optical dups or have some sort of note about this.

No, I shouldn't have made it the default in the first place.  From a processing point of view it has been nothing but trouble.  I have updating the markdup man page on my list of things to do, which I will get around to eventually.
