### ISSUE TITLE
why is mpileup producing an empty file?

### ISSUE THREAD

**Issue by gabrielet** [samtools/samtools#1998]
After running `bwa mem`, `samtools view` and `samtools sort` to obtain a suitable bam file for `samtools mpileup`, and verifying each output with `Picard ValidateSamFile`, what i get is an empty mpileup. The solution i found [online ](https://www.seqanswers.com/forum/bioinformatics/bioinformatics-aa/13835-samtools-mpileup-generates-an-empty-output)is to use the `-A` option, but i need to understand what that implies. What does it mean to use "anomalous reads", as mentioned in the manual:

> -A, --count-orphans Do not skip anomalous read pairs in variant calling. Anomalous read pairs are those marked in the FLAG field as paired in sequencing but without the properly-paired flag set. 

How is it possible all my reads are anomalous if Picard didn't notice anything weird?

In addition, if i apply `samtools fixmate` at any step of the pipeline, it messes up the sam/bam file (meaning that Picard will then return a load of errors).

I also tried `samtools flagstat` on the bam i am passing to `samtools mpileup` and QC-failed reads was always at zero, suggesting all is good.

If all seems good, why do i end up with an empty mpileup?

This is the pipeline i am using:

```

# running fastp to clean and trim raw sequences
# fastp -i /home/user/raw_data/NG_2_1.fastq \
	# -I /home/user/raw_data/NG_2_2.fastq \
	# -o /home/user/raw_data/NG_2_1_trimmed.fastq \
	# -O /home/user/raw_data/NG_2_2_trimmed.fastq \
	# -h /home/user/data_report.html \
	# -j /home/user/data_report.json

# move to folder with reference genome
cd /home/user/reference/

echo "running bwa"

# Align each set of FASTQ files against reference genome using
bwa mem -P prefix \
	-t 4 \
	-R "@RG\tID:3333\tLB:2349857\tSM:3333\tPL:ILLUMINA" \
	/home/user/raw_data/NG_2_1_trimmed.fastq \
	/home/user/raw_data/NG_2_2_trimmed.fastq \
	> /home/user/data.sam

echo "sam to bam"

# Convert SAM files to BAM files
samtools view -S -b /home/user/data.sam \
	> /home/user/data_new.bam

echo "sorting"

# Sort BAM files by coordinates using
samtools sort -T temp_3684_lib736370.prefix \
	-O bam \
	-o /home/user/data_sorted.bam \
	/home/user/data_new.bam

echo "indexing"

# Index BAM file using
samtools index -b /home/user/data_sorted.bam \
	-o /home/user/data_sorted.bam.bai

echo "creating the mpileup file"

# run samtools to get mpileup files
samtools mpileup /home/user/data_sorted.bam \
	-A \
        -q 1 \
        -f /home/user/reference/a_reference_file.fna \
        -o /home/user/data_mpileup.tsv
```

**Comment by jkbonfield** [comment]
There is no need to convert from SAM to BAM before sorting.  This is a samtools myth which has been copied from pipeline to pipeline for many years and I wish it would vanish!

Also this isn't really a pipeline.  It's just a series of commands.  Samtools can read from stdin, so you could do `bwa ... | samtools sort --write-index ...` if you wanted a genuine pipeline.

As to why mpileup is producing no data, I can't say without seeing at least one alignment record.  What does `samtools view file.bam | head -1` show you? (Assuming it can be made public).  Do you actually have any aligned records?  (`samtools flagstat` would give some basic information).  If you do, do they have any quality values?

**Comment by gabrielet** [comment]
@jkbonfield thanks for you reply, and yes, i am aware of the points you raised. i will improve the flow, just wanted to keep everything separated for now. per the samtools view output i inquired to upper levels and i hope i can give you what you need. in the meanwhile this is the output of samtools flagstat:

252668241 + 0 in total (QC-passed reads + QC-failed reads)
246137140 + 0 primary
0 + 0 secondary
6531101 + 0 supplementary
0 + 0 duplicates
0 + 0 primary duplicates
251228123 + 0 mapped (99.43% : N/A)
244697022 + 0 primary mapped (99.41% : N/A)
246137140 + 0 paired in sequencing
123068570 + 0 read1
123068570 + 0 read2
0 + 0 properly paired (0.00% : N/A)
243917590 + 0 with itself and mate mapped
779432 + 0 singletons (0.32% : N/A)
31712088 + 0 with mate mapped to a different chr
20602246 + 0 with mate mapped to a different chr (mapQ>=5)

I suppose the problem is here. But then...what?

> 0 + 0 properly paired (0.00% : N/A)

**Comment by jkbonfield** [comment]
Unpaired shouldn't mean discarded as you're specifying `mpileup -A`.  However if nothing is properly paired, then maybe also everything has a terrible quality, so try `-Q0` too. (Disabling BAQ with `-B` is always a good starting point too.)

Basically look at the usage options from mpileup and try changing all those filter parameters!  That plus manually inspect the first couple reads and ask yourself which filter option could cause mpileup to not display it.  Perhaps `-x` for example.

**Comment by gabrielet** [comment]
so i also checked the output of `fastp` and the header of the R1 and R2 reads match:

```
head -n 500 NG_2_1_trimmed.fastq | grep \@ > head_R1
head -n 500 NG_2_2_trimmed.fastq | grep \@ > head_R2

diff <(cut -d" " -f1 head_R1) <(cut  -d" " -f1 head_R2)
```

`diff` gives no output, i.e. all is good.

the question then is: do you think these data i am using are reliable?

if i need to set `-q0` to me it means that something is not wrong. would you make a variant call on these data and call it reliable?

**Comment by jkbonfield** [comment]
Without knowing anything about your library type, instrument and data, I really cannot answer these questions.  It's perhaps better as a discussion or question in BioStars.

Generally however, if the data is paired in sequencing and not a single one is paired up by bwa, I'd be wondering if I gave bwa the incorrect parameters.  Eg are they actually a paired-end library that points towards one another, or is it some other chemistry / instrument type where the normal pairing is a different orientation.  Or is the insert size widely different to what bwa expects? Etc.

If the mapping qualities have been suppressed to 0, I definitely wouldn't be trusting variant calling either.

**Comment by gabrielet** [comment]
@jkbonfield , just to give more context for future readers: the data is paired end read, 150bp, Illumina 6000.

I am now running the alignment again, after re-indexing the reference genome. I don't know why but i have the feeling that something went wrong with the indexing and how i was using the reference genome later in the `bwa mem` call.

This works, but i am not sure why. I will investigate and send news, if i find something!

```
cd /home/user/data-02/ref/

bwa index ref_genome.fna

bwa mem -t 8 ref_genome.fna \
	/home/user/data/NG_2_1_trimmed.fastq \
	/home/user/data/NG_2_2_trimmed.fastq | samtools sort -T temp.prefix \
	-O bam \
	-o /home/user/data/sorted.bam

samtools flagstat /home/user/data/sorted.bam > /home/user/data/flagstat_out.txt

samtools index -b /home/user/data/sorted.bam \
	-o /home/user/data/sorted.bam.bai

samtools mpileup /home/user/data/sorted.bam \
        -q 1 \
        -f /home/user/data-02/ref/ref_genome.fna \
        -o /home/user/data/sorted_mpileup.tsv
```

**Comment by jkbonfield** [comment]
Looking at the differences, your original bwa command was:

```
bwa mem -P prefix \
	-t 4 \
	-R "@RG\tID:3333\tLB:2349857\tSM:3333\tPL:ILLUMINA" \
	/home/user/raw_data/NG_2_1_trimmed.fastq \
	/home/user/raw_data/NG_2_2_trimmed.fastq \
	> /home/user/data.sam
```

Your new one has ref_genome.fna in there and checking the bwa usage statement I do see indeed that you missed this out, so it was probably using the _1_trimmed.fastq as the reference.  Hence no READ2 records, no proper pairs, and importantly for the `mpileup` no alignments to the reference genome!

Closing this as it was bwa usage error and not a samtools bug.  Glad you found the problem.

**Comment by gabrielet** [comment]
@jkbonfield thanks for clarifying. bwa is still a mystery to me. the documentation is not so clear as it should, in my opinion.

**Comment by jkbonfield** [comment]
Agreed!
