### ISSUE TITLE
sam files invert fq files

### ISSUE THREAD

**Issue by xeqal27244** [samtools/samtools#1999]
Hello，
when i tried to invert the sam file to fq file uesd this code,
   
samtools fastq -F 4 alignment.sam > al1.mini.fq 
 i met the errors like this ,
 
[M::bam2fq_mainloop] discarded 0 singletons
[M::bam2fq_mainloop] processed 0 reads

Is there any problems with my sam file?

**Comment by jkbonfield** [comment]
There's not enough information to say, but probably yes.

Please do a `samtools flagstat alignment.sam`.  That will give some indication on how many reads there are, whether they're primary alignments,  and how many are unmapped.  I'm also not really sure why you're wanting to exclude unmapped data when converting back to fastq.  It may be problematic if you have read-pairs, but on single-ended data it could give a viable fastq file.

**Comment by xeqal27244** [comment]
> There's not enough information to say, but probably yes.
> 
> Please do a `samtools flagstat alignment.sam`. That will give some indication on how many reads there are, whether they're primary alignments, and how many are unmapped. I'm also not really sure why you're wanting to exclude unmapped data when converting back to fastq. It may be problematic if you have read-pairs, but on single-ended data it could give a viable fastq file.
Thanks for your advice very much, it is my problems of sam files, when i used `samtools flagstat alignment.sam`,i got these results:
  8843520 + 0 in total (QC-passed reads + QC-failed reads)
0 + 0 secondary
0 + 0 supplementary
0 + 0 duplicates
0 + 0 mapped (0.00% : N/A)
0 + 0 paired in sequencing
0 + 0 read1
0 + 0 read2
0 + 0 properly paired (N/A : N/A)
0 + 0 with itself and mate mapped
0 + 0 singletons (N/A : N/A)
0 + 0 with mate mapped to a different chr
0 + 0 with mate mapped to a different chr (mapQ>=5)
  
i will try it again.

**Comment by jkbonfield** [comment]
Your file consists entirely of unmapped reads, yet you are telling `samtools fastq` to exclude unmapped reads.  Hence you get no data.  This is working correctly.

I think you maybe misunderstand what this command is attempting to do.  It recreates the unaligned representation from a BAM file (be it aligned or unaligned data).
