### ISSUE TITLE
Samtools depth reports positions with zero depth

### ISSUE THREAD

**Issue by marcellevstek** [samtools/samtools#2006]
**Samtools version:**
samtools 1.19
Using htslib 1.19
Copyright (C) 2023 Genome Research Ltd.

**Envrionment:**
Darwin 23.3.0
arm64
Apple clang version 15.0.0 (clang-1500.1.0.2.5)

When I run samtools depth with a BED file containing regions of interest, I also get positions with zero depth in the output. I must add that I did not specify the -a flag and not all positions in the BED file are reported. By using the -a flag, I get the same number of positions as the number of bases covered in the BED file.

The command used is the following:

`samtools depth -b regions.bed input.bam -o coverage.tsv`

**Comment by jkbonfield** [comment]
By default depth reports regions where records align against the reference, post filtering (eg -Q).  However within a single alignment, it can sometimes add to depth and sometimes not.  So `-q200` for example may will likely give lots of zeros.  It'll still be skipping regions that are uncovered by alignments (hence `-a` and `-aa`), but there can be places that have data aligned but individual bases have been excluded.   Another similar case is deletions.  A single depth region may have a deletion so the depth over that region goes from 1 to 0 (the deletion, unless `-J` option is used) and back to 1.

This was a deliberate implementation decision by the original author, and I don't want to simply reverse that as I don't know what tools are relying on this feature.

Note the `-a` option states that we'll get all locations in the chromosome, even the 0s.  However it does not state that the absence of `-a` means we'll get no 0s.

**Comment by jkbonfield** [comment]
I think this is working as intended, and changing it may affect existing pipelines, so we don't intend of adding any explicit removal of 0-depth regions in the default output.  Thanks for raising it though.
