### ISSUE TITLE
Sorting by name does not guarantee primary alignment sorts before secondary and supplementary

### ISSUE THREAD

**Issue by micans** [samtools/samtools#2010]
Apologies for missing data - this was already confirmed by @jkbonfield .

`samtools sort -n` sorts on name. Its secondary sort does not guarantee that within-group (the same read with multiple alignments) the primary alignment sorts before secondary and supplementary alignments. This affects stream processing as the primary alignment has the read sequence.

**Comment by jkbonfield** [comment]
I have a PR incoming to fix this.  It's https://github.com/samtools/samtools/blob/develop/bam_sort.c#L1968 (and one other place).  0xc0 is READ1 vs READ2.  For ties we then need to fall back to primary vs supplementary / secondary.

Do we wish to sort on supplementary before secondary too, given supplementary reads are nominally a part of the primary (just another half of it)?

**Comment by micans** [comment]
My interest stems primarily from the stream processing angle, so I'm agnostic regarding supplementary/primary, but the proposal sounds sensible.
