### ISSUE TITLE
Help: During the use of Samtools sort, the terminal displayed garbled characters and many C62 characters, but the final file was not generated and there were no errors.

### ISSUE THREAD

**Issue by yogacori** [samtools/samtools#2013]
#### Are you using the latest version of [samtools](https://github.com/samtools/samtools/releases/latest) and [HTSlib]
(run `samtools --version`)

Help:
During the use of Samtools sort, the terminal displayed garbled characters and many C62 characters, but the final file was not generated and there were no errors.

 #### Please describe your environment.
- OS (run Linux/Centos 7)
- machine architecture (run `uname -m` on Linux/Mac OS or ` wmic os get OSArchitecture` on Windows)
- compiler (run `gcc --version` or `clang --version`)

![image](https://github.com/samtools/samtools/assets/66674834/ab02fe65-16ce-4fa9-befa-b82c038e75a1)

**Comment by whitwham** [comment]
It looks like it was writing binary data (bam/cram) to the terminal.

What exactly was the command you were trying to run?

**Comment by yogacori** [comment]
> It looks like it was writing binary data (bam/cram) to the terminal.
> 
> What exactly was the command you were trying to run?

---
samtools sort -@ 12 SRR23948463.sam -o SRR23948463.bam

Thank you for your answer. I am still troubled by this question and have not received the final document.

**Comment by whitwham** [comment]
That shouldn't happen.  Can you capture the beginning of the output in a text file?  It might give us some clues as to what is going on.

**Comment by jmarshall** [comment]
What version of samtools is it that you are running?

**Comment by whitwham** [comment]
Closing as there has been no response from @yogacori for two weeks.

**Comment by jmarshall** [comment]
My theory BTW was that the OP was running a prehistoric 0.1.x version of samtools, in which `sort -o` meant “write to standard output” and `SRR23948463.bam` was being interpreted as a (mostly unused) output prefix.

**Comment by jkbonfield** [comment]
I thought the same.

I've sometimes wondered if we should move all the old sourceforge releases sideways into a subdirectory, to deliberately break all those ancient legacy pipelines that still install rediculously outdated bits of software!  Obviously it should be easy for people to fix such pipelines to download the new URL, but it should take a conscious effort and decision.  Do we still want this legacy version, or should we actually use a less buggy and faster implementation?

0.1.18/19 combined have a similar number of weekly downloads to 1.19.2 via sourceforge.  Scary!  (I also see no benefit in continuing to upload new versions there - it's needless).  Infact 0.1.18 releases have been gradually climbing over the years.  It's almost certainly just cargo-cult cut and paste or ancient legacy pipeline setups with hard-coded downloads.
