### ISSUE TITLE
plot-bamstats: Issue with accuracy of quality score plot

### ISSUE THREAD

**Issue by TBradley27** [samtools/samtools#2017]
#### Are you using the latest version of [samtools](https://github.com/samtools/samtools/releases/latest) and [HTSlib](https://github.com/samtools/htslib/releases/latest)? If not, please specify.
1.19.2+htslib-1.19.1

 #### Please describe your environment.
- OS: Linux 4.18.0-372.32.1.el8_6.x86_64
- machine architecture: x86_64
- compiler: gcc (GCC) 8.5.0 20210514 (Red Hat 8.5.0-10)

#### Please specify the steps taken to generate the issue, the command you are running and the relevant output.
1. ONT ubams converted to fastq
`samtools bam2fq -T 1 --reference (hg38.reference.genome) {input} > {output}`

2. minimap2 alignment
`minimap2 -y -ax map-ont {input} {output}`

3. samtools bam merging, sorting and indexing

4. `samtools stats {input} > {output}`

5. `plot-bamstats -p {prefix} {input} > {output}` 

#### Description of the problem

The quality score distribution given by plot-bamstats does not seem commensurate with other QC metrics that have been computed on this data.

For this data, other QC scoring algorithms (i.e. NanoPlot) tell me, for this specific dataset, I have a median read length of 2049, and a median read quality score of 16.5, with a small number of reads greater than 100 kb in length.

<img width="446" alt="image" src="https://github.com/samtools/samtools/assets/13511784/dbf06699-f8b5-41d6-8cb4-7477f2601c72">

These plots would imply that the average quality score for most reads should be about 30, which is not commensurate with other QC metrics available to me. For comparison, here is the plot generated from NanoPlot using the same data:

<img width="382" alt="image" src="https://github.com/samtools/samtools/assets/13511784/4584e428-9b1c-4c08-9d44-dce7fbdce391">

The NanoPlot QC plot is computed directly from the ubams, and not from the aligned bam file

Or maybe I am misinterpreting the results of the plot?

I wonder if there is an issue with the decoding of quality scores from the bam files for this data type?

**Comment by jkbonfield** [comment]
There are major issues with samtools stats and the plot-bamstats functionality on long-read technology.  When it was written Illumina (or even Solexa) was the only data considered.  Hence reports for things like "cycles" in the plots, and no binning capabilities.  These issues essentially make many of the either worthless or sometimes illegible on long read instruments.

We do have plans to do a major overhaul, see https://github.com/samtools/samtools/issues/1997, but it's not got any time allocated to it yet due to many other pressures.  If you have ideas on features that you'd want though, please do add them to that issue so we can track all the improvements needed in one place.  Thanks.

**Comment by TBradley27** [comment]
Many thanks for this

I agree with your comments about the best way to calculate an average quality score.

Regarding the differences we see between Illumina-platform derived data and what we see with ONT data - I think the relevant lines in the codebase are as follows:

https://github.com/samtools/samtools/blob/edf213137c6b34510e7bc11d77874b1723cd7a31/misc/plot-bamstats#L643-L659

In particular,   https://github.com/samtools/samtools/blob/edf213137c6b34510e7bc11d77874b1723cd7a31/misc/plot-bamstats#L647

It seems that the array of quality scores for a given cycle are being multiplied by the index of that quality score within the array? For Illumina-derived data, this is producing the correct result. But I think this could be what is causing things to go a little wrong when working with ONT data

Do you have an idea why the quality score is being multiplied by its own index here? For whatever reason, this seems to be producing the right result for illumina-derived data. I could try removing this multiplication and see what effect it has on some of our ONT data

**Comment by TBradley27** [comment]
Many thanks for this.

I agree with your comments on the appropriateness of taking the average of quality scores.

This is just a quick comment to say that I have relooked at the FFQ table for my ONT table, and the plot-bamstats code. And the issue isn't with plot-bamstats.

So the problem must lie elsewhere or with some of the other QC tools I am using, or rather my understanding of how some of these metrics compare/relate to each other. Will keep on investigating

**Comment by jkbonfield** [comment]
Agreed.  IMO it's "wrong" for all technologies, however I suspect some tools and platforms quote those "wrong" stats in some situations as it fluffs their figures into looking better!  The norm that people expect may also be a naive average, so changing it has problems too.

I think it probably needs options for controlling such things.

**Comment by TBradley27** [comment]
Yes, agreed. From a user perspective, having an option to choose either approach would be great

**Comment by TBradley27** [comment]
Relevant to this discussion is that a similar conversation is taking place on the FastQC repository: https://github.com/s-andrews/FastQC/issues/110

**Comment by TBradley27** [comment]
Fixed by 031f439007e7293a9ddd4afce79b7564a5098ded and 6b0cc4a0e047f9c309bdefc531cdc117dd6e09d1
