### ISSUE TITLE
mpileup returns different reference sequence for different bam given same input bed and fasta

### ISSUE THREAD

**Issue by joegeorgeson** [samtools/samtools#2018]
Hi samtools,

I'm trying to figure out why `samtools mpileup` gives different reference sequences for different bam files given that the bam were generated from alignment to the same reference genome (via STAR) and during mpileup I pass the same input bed and fasta.

I initially thought the issue stemmed from another program, but after troubleshooting see that it comes from samtools. Please see my comment on other github, which also contains example data; [https://github.com/y9c/cpup/issues/1#issuecomment-2019116796](https://github.com/y9c/cpup/issues/1#issuecomment-2019116796)

And of course, if this is user error, please advise!

(run `samtools --version`)
```
$ samtools --version
samtools 1.18
Using htslib 1.18
Copyright (C) 2023 Genome Research Ltd.

Samtools compilation details:
    Features:       build=configure curses=yes
    CC:             gcc
    CPPFLAGS:       -I/apps/easybd/easybuild/software/cURL/8.0.1-GCCcore-12.3.0/include -I/apps/easybd/easybuild/software/XZ/5.4.2-GCCcore-12.3.0/include -I/apps/easybd/easybuild/software/bzip2/1.0.8-GCCcore-12.3.0/include -I/apps/easybd/easybuild/software/zlib/1.2.13-GCCcore-12.3.0/include -I/apps/easybd/easybuild/software/ncurses/6.4-GCCcore-12.3.0/include
    CFLAGS:         -O2 -ftree-vectorize -march=x86-64 -mtune=generic -fno-math-errno -fPIC
    LDFLAGS:        -L/apps/easybd/easybuild/software/cURL/8.0.1-GCCcore-12.3.0/lib64 -L/apps/easybd/easybuild/software/cURL/8.0.1-GCCcore-12.3.0/lib -L/apps/easybd/easybuild/software/XZ/5.4.2-GCCcore-12.3.0/lib64 -L/apps/easybd/easybuild/software/XZ/5.4.2-GCCcore-12.3.0/lib -L/apps/easybd/easybuild/software/bzip2/1.0.8-GCCcore-12.3.0/lib64 -L/apps/easybd/easybuild/software/bzip2/1.0.8-GCCcore-12.3.0/lib -L/apps/easybd/easybuild/software/zlib/1.2.13-GCCcore-12.3.0/lib64 -L/apps/easybd/easybuild/software/zlib/1.2.13-GCCcore-12.3.0/lib -L/apps/easybd/easybuild/software/ncurses/6.4-GCCcore-12.3.0/lib64 -L/apps/easybd/easybuild/software/ncurses/6.4-GCCcore-12.3.0/lib -L/apps/easybd/easybuild/software/GCCcore/12.3.0/lib64 -L/apps/easybd/easybuild/software/GCCcore/12.3.0/lib
    HTSDIR:         htslib-1.18
    LIBS:           -lm -lpthread
    CURSES_LIB:     -lncursesw

HTSlib compilation details:
    Features:       build=configure libcurl=yes S3=yes GCS=yes libdeflate=no lzma=yes bzip2=yes plugins=no htscodecs=1.5.1
    CC:             gcc
    CPPFLAGS:       -I/apps/easybd/easybuild/software/cURL/8.0.1-GCCcore-12.3.0/include -I/apps/easybd/easybuild/software/XZ/5.4.2-GCCcore-12.3.0/include -I/apps/easybd/easybuild/software/bzip2/1.0.8-GCCcore-12.3.0/include -I/apps/easybd/easybuild/software/zlib/1.2.13-GCCcore-12.3.0/include -I/apps/easybd/easybuild/software/ncurses/6.4-GCCcore-12.3.0/include
    CFLAGS:         -O2 -ftree-vectorize -march=x86-64 -mtune=generic -fno-math-errno -fPIC
    LDFLAGS:        -L/apps/easybd/easybuild/software/cURL/8.0.1-GCCcore-12.3.0/lib64 -L/apps/easybd/easybuild/software/cURL/8.0.1-GCCcore-12.3.0/lib -L/apps/easybd/easybuild/software/XZ/5.4.2-GCCcore-12.3.0/lib64 -L/apps/easybd/easybuild/software/XZ/5.4.2-GCCcore-12.3.0/lib -L/apps/easybd/easybuild/software/bzip2/1.0.8-GCCcore-12.3.0/lib64 -L/apps/easybd/easybuild/software/bzip2/1.0.8-GCCcore-12.3.0/lib -L/apps/easybd/easybuild/software/zlib/1.2.13-GCCcore-12.3.0/lib64 -L/apps/easybd/easybuild/software/zlib/1.2.13-GCCcore-12.3.0/lib -L/apps/easybd/easybuild/software/ncurses/6.4-GCCcore-12.3.0/lib64 -L/apps/easybd/easybuild/software/ncurses/6.4-GCCcore-12.3.0/lib -L/apps/easybd/easybuild/software/GCCcore/12.3.0/lib64 -L/apps/easybd/easybuild/software/GCCcore/12.3.0/lib -fvisibility=hidden

HTSlib URL scheme handlers present:
    built-in:	 preload, data, file
    S3 Multipart Upload:	 s3w, s3w+https, s3w+http
    Amazon S3:	 s3+https, s3+http, s3
    Google Cloud Storage:	 gs+http, gs+https, gs
    libcurl:	 imaps, pop3, gophers, http, smb, gopher, ftps, imap, smtp, smtps, rtsp, ftp, telnet, mqtt, https, smbs, tftp, pop3s, dict
    crypt4gh-needed:	 crypt4gh
    mem:	 mem
```

 #### Please describe your environment.
- OS (run `uname -sr` on Linux/Mac OS or ` wmic os get Caption, Version` on Windows)
```
$ uname -sr
Linux 3.10.0-1160.81.1.el7.x86_64
```
- machine architecture (run `uname -m` on Linux/Mac OS or ` wmic os get OSArchitecture` on Windows)
```
$ uname -m
x86_64
```
- compiler (run `gcc --version` or `clang --version`)
```
$ gcc --version
gcc (GCC) 12.3.0
Copyright (C) 2022 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

**Comment by jkbonfield** [comment]
Oh I see what you mean now.  Sorry!

It's just printed up from the reference, see https://github.com/samtools/samtools/blob/develop/bam_plcmd.c#L625 and https://github.com/samtools/samtools/blob/develop/bam_plcmd.c#L369

I don't really see how this can change from one file to another, but you are correct.  Thank you for the demonstration data.  I'll need to dig into it further tomorrow to see what's happening.  Eg:

```
@ seq4d[tmp/ex_cpup]; samtools mpileup -aa ex1.bam -f ex.fa|head -175|tail
[mpileup] 1 samples in 1 input files
tRNA-Ala-AGC-10	51	C	0	*	*
tRNA-Ala-AGC-10	52	T	0	*	*
tRNA-Ala-AGC-10	53	T	0	*	*
tRNA-Ala-AGC-10	54	A	0	*	*
tRNA-Ala-AGC-10	55	G	0	*	*
tRNA-Ala-AGC-10	56	C	0	*	*
tRNA-Ala-AGC-10	57	A	0	*	*
tRNA-Ala-AGC-10	58	T	0	*	*
tRNA-Ala-AGC-10	59	G	0	*	*
tRNA-Ala-AGC-10	60	T	0	*	*
@ seq4d[tmp/ex_cpup]; samtools mpileup -aa ex2.bam -f ex.fa|head -175|tail
[mpileup] 1 samples in 1 input files
tRNA-Ala-AGC-10	51	C	2	..	JJ
tRNA-Ala-AGC-10	52	T	2	..	EE
tRNA-Ala-AGC-10	53	T	2	..$	8B
tRNA-Ala-AGC-10	54	A	0	*	*
tRNA-Ala-AGC-10	55	C	0	*	*
tRNA-Ala-AGC-10	56	A	0	*	*
tRNA-Ala-AGC-10	57	T	0	*	*
tRNA-Ala-AGC-10	58	G	0	*	*
tRNA-Ala-AGC-10	59	C	0	*	*
tRNA-Ala-AGC-10	60	A	0	*	*

@ seq4d[tmp/ex_cpup]; samtools faidx ex.fa tRNA-Ala-AGC-10:51-60
>tRNA-Ala-AGC-10:51-60
CTTAGCATGC
```

So neither actually match what faidx reports.  Weird.

It looks to have got out of sync too.  Using a region gives different reference reported than head/tail.

**Comment by jkbonfield** [comment]
I think I can see the problem.  When switching from one ref to the next, it's already loaded the next reference up before calling `print_empty_pileup`, so it gets the incorrect reference listed against all the "*" fields.  I need to double check, but if so it's been buggy since b4e452c3a (2016)!

**Comment by joegeorgeson** [comment]
Thank you very much for checking so quickly!

**Comment by jkbonfield** [comment]
Fixed in #2019.  Thanks for the bug report.

**Comment by joegeorgeson** [comment]
Hi Yuri, I'm not a samtools dev, but I originated this bug and am familiar with using mpileup for RNA modification detection. Perhaps I can help. The first question is which version of samtools are you using? The second question is if you use the -B flag? ([As is so often the case with mpileup problems, the answer typically lies in disabling BAQ!](https://github.com/samtools/samtools/issues/2082#issuecomment-2228022223))

**Comment by joegeorgeson** [comment]
Hmmmm, if you revert back to 1.19 do you get a different result (this is my 'stable version')? Does the CIGAR include clipped reads (do you allow clipping during alignment?)? Are you passing with the -aa flag?

**Comment by joegeorgeson** [comment]
Try passing the command with a bed file. I think a bed is needed to capture all positions 'when there no actual reads covering the position AT THE END of the sequence'

If that still doesn't work, some other considerations:
- Go with 1.19.2
- If paired end reads, using -Q0 will be the same as -x which will count overlapped reads twice
- Try -aa instead of -a
