### ISSUE TITLE
An error:[E::sam_hdr_create] Invalid header line: must start with @HD/@SQ/@RG/@PG/@CO

### ISSUE THREAD

**Issue by shizuka0420** [samtools/samtools#2024]
When I tried to use samtools(version:1.19.2) to view sam files, it occured an error.
[E::sam_hdr_create] Invalid header line: must start with @HD/@SQ/@RG/@PG/@CO
However, I have checked many times about the header of sam files, which are fit to the format.
A part of the sam file is as follow:
![image](https://github.com/samtools/samtools/assets/159701855/91fad967-7a99-4559-8e2e-a0ceb98df4d9)
The code to get the sam files is as follow:
bowtie -x "$REF_GENOME_INDEX" -f "$FILE" -S "$SAM_FILE"
Does anyone know how to solve this problem? Is the sam file damaged when my bowtie is in use?

**Comment by whitwham** [comment]
Can you post the entire header as a text file?  Can you also tell us what samtools command you were using.

**Comment by shizuka0420** [comment]
> Usually when I see such errors it's because there is something else being mixed in with stdout and you're using a pipe. Possibly related to nohup or sometimes caused by some batch submission systems. The full command line and what environment it is being ran under may well impact this.
> 
> However I also see your header file uses spaces instead of tabs. This is an error. It _may_ be how you saved it, or something like cut and paste. Or possibly it's what samtools is complaining about. However it looks to give different error with spaces, so I think this malformed headersam.txt is a second problem.

Thank you for your detailed answer.I will try to regenerate the sam file and check the separator.

**Comment by daviesrob** [comment]
Hopefully the regenerated file worked.  Please let us know if you still have a problem.

**Comment by shizuka0420** [comment]
> Hopefully the regenerated file worked. Please let us know if you still have a problem.

I'm sorry to ignore your reply at before. I have already solved this problem by using fastaq data to instead of fasta data.
