### ISSUE TITLE
samtools on Windows segfaults if invalid command line options

### ISSUE THREAD

**Issue by divonlan** [samtools/samtools#2029]
#### Are you using the latest version of [samtools](https://github.com/samtools/samtools/releases/latest) and [HTSlib](https://github.com/samtools/htslib/releases/latest)? If not, please specify.
(run `samtools --version`)

tested in 1.17

 #### Please describe your environment.
- OS (run `uname -sr` on Linux/Mac OS or ` wmic os get Caption, Version` on Windows)
- machine architecture (run `uname -m` on Linux/Mac OS or ` wmic os get OSArchitecture` on Windows)
- compiler (run `gcc --version` or `clang --version`)

samtools on MingW installed with pacman (MingW package manger) - running on Windows.

#### Please specify the steps taken to generate the issue, the command you are running and the relevant output.

When entering an invalid command line option, the software segfaults. This happens only on Windows, not Linux.

For example:
samtools.exe view --junk

**Comment by jkbonfield** [comment]
A fresh build of develop doesn't have this problem, so I assume it's something we've fixed.  Will try 1.17 release too.
