### ISSUE TITLE
samtools merge very slow with many files

### ISSUE THREAD

**Issue by jrandall** [samtools/samtools#203]
samtools merge appears to work fine for a small number of files (up to 50 or so it goes fairly fast).  However, when merging larger numbers of files, the operations to examine and build the header (before the actual data merge even begins) starts to dominate the time. 

Each additional input file that is opened is processed more and more slowly. I think this is because the regexes are searching through all of the data that has been loaded previously (this appears to especially be a problem for the PG ID searches). 

By the 100th file, it takes around a second to process each additional file. By the 200th, each file open takes a few seconds. By the 500th file, it takes around 50s each. By the 1200th file, it is around 200s. We had to stop testing beyond that, but expect that opening the 5000th file would take nearly an hour to process, and the whole process of getting all files opened and headers processed would take several months to complete. 

I have refactored some of the code in bam_sort.c to assist with profiling (07e333effffe6ce72e2d9fad124a52debc0e2906), and I believe the issue comes down to a few of the regexes dealing with PG lines. 

If we had a header parser, we could replace the regex implementation with one that built sensible data structures to keep track of the needed merge information.

**Comment by SamStudio8** [comment]
See #481

**Comment by daviesrob** [comment]
Closing as this was made more efficient a while back.
