### ISSUE TITLE
Using view command to filter the records from bam file, but also report the number of reads passed the filter or dropped. 

### ISSUE THREAD

**Issue by y9c** [samtools/samtools#2038]
The built-in argument `-c` of the view command can print only the count of matching records. However, if the filtered records are stored in an output file, it is difficult to tell how many reads passed the filter. One solution is to run the view command again on the input and output files with the `-c` argument, but this wastes time and computational resources. It would be better if the view command could support this functionality out of the box.

**Comment by daviesrob** [comment]
It shouldn't be too difficult.  We'll look into this.
