### ISSUE TITLE
ampliconclip retains sequence between two regions covered by the same read

### ISSUE THREAD

**Issue by wiedenhoeft** [samtools/samtools#2040]
I am using samtools ampliconclip to retain only bases covering small regions of interest (prespecified variants). Whenever a read covers two of these regions, I would expect ampliconclip to retain two small chunks of the read. Instead, it retains the read from the start of the leftmost region to the end of the rightmost region:

![IGV Screenshot](https://github.com/samtools/samtools/assets/2615901/45b64b00-0003-4574-ab40-146156105f8b)

Running samtools samtools 1.19.2 on Ubuntu 20.04.6 LTS (Linux 5.16.2-051602-generic, x86_64, gcc 9.4.0).

**Comment by whitwham** [comment]
No, ampliconclip clips the ends of read alignments.  Any regions too far from the alignment beginning or end are ignored.
