### ISSUE TITLE
Different versions of samtools produce different output for the same file

### ISSUE THREAD

**Issue by yaximik** [samtools/samtools#2044]
Scientific Linux 7.9, conda installs, different versions of samtools, the same .sam file.

Different versions of samtools produce different output for the same file.

$ less gor-mt2rCRS.sam
@HD VN1.0 SO:unsorted
@SQ	SN:1	LN:30427671
@SQ	SN:2	LN:19698289
@SQ	SN:3	LN:23459830
@SQ	SN:4	LN:18585056
@SQ	SN:5	LN:26975502
@SQ	SN:M	LN:366924
@SQ	SN:C	LN:154478
@PG ID:nucmer PN:nucmer VN:4.0 CL:"nucmer --maxmatch --threads=4 --sam-short=./gor-hum.sam gorilla.fasta rCRS.fasta"

samtools v <=1.9:
htslib v <=1.9
$ samtools view -H gor-mt2rCRS.sam
@HD VN1.0 SO:unsorted
@SQ	SN:1	LN:30427671
@SQ	SN:2	LN:19698289
@SQ	SN:3	LN:23459830
@SQ	SN:4	LN:18585056
@SQ	SN:5	LN:26975502
@SQ	SN:M	LN:366924
@SQ	SN:C	LN:154478
@PG ID:nucmer PN:nucmer VN:4.0 CL:"nucmer --maxmatch --threads=4 --sam-short=./gor-hum.sam gorilla.fasta rCRS.fasta"

samtools v 1.10 - 1.20
htslib v 1.10 - 1.20

$ samtools view -H gor-mt2rCRS.sam
[main_samview] fail to read the header from "gor-mt2rCRS.sam"

What may be the issue?

**Comment by yaximik** [comment]
Sorry for the persistence, but this does not seem the issue:

$ less gor-mt2rCRS2.sam
@HD     VN:1.0  SO:unsorted
@SQ     SN:1    LN:30427671
@SQ     SN:2    LN:19698289
@SQ     SN:3    LN:23459830
@SQ     SN:4    LN:18585056
@SQ     SN:5    LN:26975502
@SQ     SN:M    LN:366924
@SQ     SN:C    LN:154478
@PG ID:nucmer PN:nucmer VN:4.0 CL:"nucmer --maxmatch --threads=4 --sam-short=./gor-hum.sam gorilla.fasta rCRS.fasta"

samtools <=1.9, htslib <=1.9
$ samtools view -H gor-mt2rCRS2.sam
@HD	VN:1.0	SO:unsorted
@SQ	SN:1	LN:30427671
@SQ	SN:2	LN:19698289
@SQ	SN:3	LN:23459830
@SQ	SN:4	LN:18585056
@SQ	SN:5	LN:26975502
@SQ	SN:M	LN:366924
@SQ	SN:C	LN:154478
@PG ID:nucmer PN:nucmer VN:4.0 CL:"nucmer --maxmatch --threads=4 --sam-short=./gor-hum.sam gorilla.fasta rCRS.fasta"

samtools =>1.9, htslib =>1.9
$ samtools view -H gor-mt2rCRS2.sam
[E::sam_hdr_create] Invalid header line: must start with @HD/@SQ/@RG/@PG/@CO
[main_samview] fail to read the header from "gor-mt2rCRS2.sam"

The header line does start from @HD and the version syntax is correct now !

**Comment by yaximik** [comment]
BTW, all header lines were in the upper case upon writing the comment, but change to the lower case (i.e. @HD -> @hd) upon posting.

**Comment by jmarshall** [comment]
If you wrap your output in \`\`\` … \`\`\` (as I have edited your previous comment to do), GitHub will show it verbatim.

Doing that shows that you had two problems: the `VN1.0` thing, and your `@PG` header line is made out of spaces.

Note that it's not really the case that different samtools versions have produced different output here. Really the more recent samtools has **rejected** your input and not produced any output.

**Comment by yaximik** [comment]
Spaces in @PG header do not seem to be the problem either as explicit replacement of spaces with tabs and even deleting the @PG header line altogether produces similar output. Explicit check of the entire file shows now no spaces anywhere:

cat -T gor-mt2rCRS3.sam
@HD^IVN:1.0^ISO:unsorted
@SQ^ISN:1^ILN:30427671
@SQ^ISN:2^ILN:19698289
@SQ^ISN:3^ILN:23459830
@SQ^ISN:4^ILN:18585056
@SQ^ISN:5^ILN:26975502
@SQ^ISN:M^ILN:366924
@SQ^ISN:C^ILN:154478
@PG^IID:nucmer^IPN:nucmer^IVN:4.0^ICL:"nucmer^I--maxmatch^I--threads=4^I--sam-short=./gor-hum.sam^Igorilla.fasta^IrCRS.fasta"
NC_012920_1^I0^Igi|195952353|ref|NC_011120.1|^I1^I10^I576S143M1I238M3I799M1D5M1I450M1I13M1D875M1I2787M3D1621M1D761M1D227M1D4M1I1352M1D3M1I2087M1I2M1D1855M1D3M1I1630M1I3M1D507M1D187M429S^I*^I0^I0^I*^I*^INM:i:1625
NC_012920_1^I2048^Igi|195952353|ref|NC_011120.1|^I15654^I10^I16301H51M1I128M1D55M1D33M^I*^I0^I0^I*^I*^INM:i:24
NC_012920_1^I2048^Igi|195952353|ref|NC_011120.1|^I15923^I10^I59M1D5M1I128M1D9M1I2M1D30M16334H^I*^I0^I0^I*^I*^INM:i:24

Yet with samtools =>1.10
$ samtools view -H gor-mt2rCRS3.sam
[main_samview] fail to read the header from "gor-mt2rCRS3.sam"

I am not trying to be nauseating, only I try to figure out what is wrong with sam output generated by mummer/nucmer4, which can be handled only by samtools <=1.9

**Comment by jmarshall** [comment]
(It's [backquote characters](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#quoting-code) to get the verbatim formatting.)

The error messages show that you are still using a fairly old version of samtools. If you use the current release, you will get better error messages that pinpoint the problem better.

This is why I clarified that the `@PG` header needs to **delimit** its **fields** with tabs. What you have now is (written over several lines for clarity):

```
@PG
<tab>ID:nucmer
<tab>PN:nucmer
<tab>VN:4.0
<tab>CL:"nucmer
<tab>--maxmatch
<tab>--threads=4
<tab>--sam-short=./gor-hum.sam
<tab>gorilla.fasta
<tab>rCRS.fasta"
```

Everything from `--maxmatch` down is not a valid tagged header field.

What you need is for the fields of the `@PG` line to be tab-delimited, just like the other headers here, and for the `CL` value not to contain any tabs (only spaces). Thus:

```
@PG
<tab>ID:nucmer
<tab>PN:nucmer
<tab>VN:4.0
<tab>CL:nucmer --maxmatch --threads=4 --sam-short=./gor-hum.sam gorilla.fasta rCRS.fasta
```

**Comment by jmarshall** [comment]
This broken output is BTW a long-standing mummer bug: see mummer4/mummer#24 and https://github.com/mummer4/mummer/blob/master/src/umd/nucmer_main.cc#L107-L108

**Comment by yaximik** [comment]
Yes, unfortunately the bug is still there since v4.0.0beta release in 2017. All I can do is to try fixing the source code of the latest v4.0.0rc1 released in 2020 and recompile. This is why I am trying to figure what is the problem. It is still no avail (below).

Thanks for patience and your time. I am using the latest version of samtools 1.20, but also tested older version to see where the  noncompliance shows up.  It begin to show up from v1.10. Fixing the @PG per your response is still insufficient to resolve the noncompliance:

```
$ cat -T gor-mt2rCRS7.sam
@HD^IVN:1.0^ISO:unsorted
@SQ^ISN:1^ILN:30427671
@SQ^ISN:2^ILN:19698289
@SQ^ISN:3^ILN:23459830
@SQ^ISN:4^ILN:18585056
@SQ^ISN:5^ILN:26975502
@SQ^ISN:M^ILN:366924
@SQ^ISN:C^ILN:154478
@PG^IID:nucmer^IPN:nucmer^IVN:4.0^ICL:nucmer –maxmatch –threads=4 –sam-short=./gor-hum.sam gorilla.fasta rCRS.fasta
NC_012920_1^I0^Igi|195952353|ref|NC_011120.1|^I1^I10^I576S143M1I238M3I799M1D5M1I450M1I13M1D875M1I2787M3D1621M1D761M1D227M1D4M1I1352M1D3M1I2087M1I2M1D1855M1D3M1I1630M1I3M1D507M1D187M429S^I*^I0^I0^I*^I*^INM:i:1625
NC_012920_1^I2048^Igi|195952353|ref|NC_011120.1|^I15654^I10^I16301H51M1I128M1D55M1D33M^I*^I0^I0^I*^I*^INM:i:24
NC_012920_1^I2048^Igi|195952353|ref|NC_011120.1|^I15923^I10^I59M1D5M1I128M1D9M1I2M1D30M16334H^I*^I0^I0^I*^I*^INM:i:24

samtools 1.20

$ samtools view -H gor-mt2rCRS7.sam
[main_samview] fail to read the header from "gor-mt2rCRS7.sam"

```

**Comment by jmarshall** [comment]
At this point, it works for me when copying the output from your `cat` command. Try with `cat -A gor-mt2rCRS7.sam` to see if there are some other nonprinting characters in there causing chaos.

**Comment by yaximik** [comment]
YES!!! You were totally correct - a lot of non-printing characters snicked in. After cleaning v 1.20 works just fine:
```
$ samtools view -H gor-mt2rCRS9.sam
@HD	VN:1.0	SO:unsorted
@SQ	SN:1	LN:30427671
@SQ	SN:2	LN:19698289
@SQ	SN:3	LN:23459830
@SQ	SN:4	LN:18585056
@SQ	SN:5	LN:26975502
@SQ	SN:M	LN:366924
@SQ	SN:C	LN:154478
@PG	ID:nucmer	PN:nucmer	VN:4.0	CL:nucmer --maxmatch --threads=4 --sam-short=./gor-hum.sam gorilla.fasta rCRS.fasta
@PG	ID:samtools	PN:samtools	PP:nucmer	VN:1.20	CL:samtools view -H gor-mt2rCRS9.sam
```
Thanks a lot for your patience with me and help. I already found the sam output lines in the nucmer source and know what to correct.

**Comment by jkbonfield** [comment]
The mummer bug looks easy to fix, but sadly there are other simple bug fixes that have pull requests against them for 5+ years, so I suspect it's now abandonware.

**Comment by yaximik** [comment]
Thanks much to John Marshall for help, I fixed this issue already. That is always unfortunate when a promising software is abandoned...
