### ISSUE TITLE
SamTools merge in SamTool/1.11

### ISSUE THREAD

**Issue by AzlanNI** [samtools/samtools#2045]
Hello everyone! 
I am currently using samtools merge with the Version 1.11 on bam files generated by Nanopore basecalling. These bam files also include MM and ML Tags. Is it a known issue, that samtools merge of Version <1.14 do not handle the merging of MM and ML tag reads well ? 

Since i read in a Paper that Versions <1.14 are not able to handle the merging of reads with these tags. 
Also i used the samtools view -c command to check the number of total reads. I also checked it with Pysam. And the sum of Reads for the singular files is smaller then the Read count in my merged.bam file. 
I am merging with this command 
samtools merge Merged.bam *.bam
and i double checked only the bam files and bam.bai files are in that directory. So this is not making sense to me. 

Would be great to get a answer on what exactly the problem was there. 

Kind regards, 

Azlan

**Comment by jkbonfield** [comment]
The base modifications tags only became official in the SAM spec in 2022, and were merged in as a draft tag in mid 2021.  We don't backport new specification changes to older samtools releases.  Please consider upgrading to a newer version of samtools.  This will bring many more improvements and bug fixes too as well as better support for base modifications.

However that said, I don't understand the problem with merging.  The base modification tags are applied per read.  Merging is done per-read too, so I cannot see how the modifications would become invalid after merging.  Can you explain the problem with an example please?

**Comment by jkbonfield** [comment]
Closing as answered and no response
