### ISSUE TITLE
 samtools sort: couldn't allocate memory for bam_mem

### ISSUE THREAD

**Issue by hachemi23** [samtools/samtools#2051]
I'm havaing the error message with this command :  samtools sort: couldn't allocate memory for bam_mem
samtools sort -@ 4 -m 1500M file.bam -o file_sort.bam

with free -h i get this
 total        used        free      shared  buff/cache   available
Mem:           3.7Gi       457Mi       2.5Gi       2.0Mi       772Mi       3.1Gi
Swap:          1.0Gi          0B       1.0Gi

**Comment by whitwham** [comment]
Could you please tell us which version of samtools you are running and what environment you are running on.

**Comment by hachemi23** [comment]
the version of samtools is 1.6. i am working with Ubuntu on widows11

**Comment by whitwham** [comment]
The memory allocation is **per thread**.  So you are allocating 6G, which you may not have available.

Try allocating less memory.

**Comment by hachemi23** [comment]
with : samtools sort -@ 4 -m 700M .......it works.
thank you for your help.
