### ISSUE TITLE
fixmate creates invalid SAM flags

### ISSUE THREAD

**Issue by wiedenhoeft** [samtools/samtools#2052]
#### Are you using the latest version of [samtools](https://github.com/samtools/samtools/releases/latest) and [HTSlib](https://github.com/samtools/htslib/releases/latest)? If not, please specify.
Yes, 1.20.

 #### Please describe your environment.
- OS: Linux 5.16.2-051602-generic
- machine architecture: x86_64
- compiler: gcc (Ubuntu 9.4.0-1ubuntu1~20.04.2) 9.4.0

#### Please specify the steps taken to generate the issue, the command you are running and the relevant output.
An interleaved FASTQ file was mapped using `bwa mem -p -c 250 -M -t 9 hg19.fa in.bam mapped.bam`. The following lines appear next to each other in the output, and the flags (73, 133) are correct, valid and complementary (sequences and quality scores removed for readability):

A01174:196:HGKFNDSX2:4:1651:6433:35336:TCA_TCA  73      chrM    8481    21      3S143M  =       8481    0      NM:i:3  MD:Z:115A20A2C3 AS:i:131        XS:i:121        XA:Z:chr1,+569030,3S143M,5;

A01174:196:HGKFNDSX2:4:1651:6433:35336:TCA_TCA  133     chrM    8481    0       *       =       8481    0        MC:Z:3S143M     AS:i:0  XS:i:0

After running `samtools collate -@ 1 -O -u mapped.bam 2> map.log  | samtools fixmate -Mrcm - out.bam`, only the first of these is retained (sequences match), and the SAM flag is now invalid (72: mate unmapped, first in pair, but paired bit not set):

A01174:196:HGKFNDSX2:4:1651:6433:35336:TCA_TCA  72      chrM    8481    21      3S143M  =       8481    0        NM:i:3  MD:Z:115A20A2C3 AS:i:131        XS:i:121        XA:Z:chr1,+569030,3S143M,5;     MC:Z:*  ms:i:2872

This creates downstream problems with fgbio GroupReadsByUMI for me:

> Exception in thread "main" htsjdk.samtools.SAMFormatException: SAM validation error: ERROR::INVALID_FLAG_MATE_UNMAPPED:Record 1248, Read name A01174:196:HGKFNDSX2:4:1651:6433:35336, Mate unmapped flag should not be set for unpaired read.

Picard complains about a 72 flag as well: https://broadinstitute.github.io/picard/explain-flags.html

**Comment by whitwham** [comment]
There are a couple of things here.

Firstly, _fixmate_ should not be removing the paired flag (0x1).  That flag is an indication about the sequencing technology rather than the alignments themselves.  We will have to look at fixing that.

Secondly, a flags value of 72, that is MUNMAP (0x8) and READ1 (0x40) without PAIRED (0x1), is an entirely valid combination.  From the [specs](https://samtools.github.io/hts-specs/SAMv1.pdf),

> If 0x1 is unset, no assumptions can be made about 0x2, 0x8, 0x20, 0x40 and 0x80.

fgbio and Picard regarding the combination as invalid is a misunderstanding of the format specifications.
