### ISSUE TITLE
Segmentation fault on some CRAMs (but not all) when extracting reads over particular sets of intervals with multi-region iterator

### ISSUE THREAD

**Issue by acorvelo** [samtools/samtools#2063]
samtools 1.20
htslib 1.20
Linux 3.10.0-1160.71.1.el7.x86_64

Hi,
when extracting reads overlapping particular sets of intervals with `-M,` on some CRAMs but not all (despite the fact that all were generated by the same pipeline), samtools throws the following error before [not] producing a single read:
```
Segmentation fault (core dumped)
``` 
The command:
```
samtools view -T ${REFERENCE} -F 3840 -M -L ${BED} ${CRAM}
``` 
Initially, I thought it could be something wrong with the CRAM indices but after regenerating them, the problem persisted. Removing some intervals from the BED file results, for the most part, in successful executions but it's unclear why. Splitting the interval file can also result in successful executions. It's quite puzzling why some combinations of intervals don't go well with particular CRAMs.

I manage to replicate the behavior on a few of the high-coverage 1000 Genomes Project CRAMs that can be pulled via FTP:

Successful CRAM path:
[ftp://ftp-trace.ncbi.nlm.nih.gov/1000genomes/ftp/1000G_2504_high_coverage/data/ERR3240128/HG00112.final.cram
ftp://ftp-trace.ncbi.nlm.nih.gov/1000genomes/ftp/1000G_2504_high_coverage/data/ERR3240128/HG00112.final.cram.crai](url)

Unsuccessful CRAM path:
[ftp://ftp-trace.ncbi.nlm.nih.gov/1000genomes/ftp/1000G_2504_high_coverage/data/ERR3240129/HG00113.final.cram
ftp://ftp-trace.ncbi.nlm.nih.gov/1000genomes/ftp/1000G_2504_high_coverage/data/ERR3240129/HG00113.final.cram.crai](url)

BED file:
[test.bed.gz](https://github.com/user-attachments/files/15506635/test.bed.gz)

I tried earlier versions, down to 1.12, and had the same error. Version 1.10 appears to be working fine, even though it is very slow on this type of operation, compared to more recent versions (when they work).

Please let me know if you didn't manage to replicate the behavior and/or if there's any additional information I should provide.

Thanks!

**Comment by daviesrob** [comment]
Thanks for the comprehensive bug report.  I've managed to reproduce the crash - it looks like the iterator fell off the end of its intervals list [here](https://github.com/samtools/htslib/blob/5d3186803e627766aedcc381043a788995dd8f1b/hts.c#L4455).  I'll need to do some more digging to find out exactly why that happened.

**Comment by daviesrob** [comment]
I've made an HTSlib pull request that should fix this.

The crash happened because you had many more locations on chr7 than chr6 in the BED file, HTSlib was incorrectly trying to look up the chr7 regions in the much shorter chr6 regions list and so went off the end.  The fix prevents in invalid look-ups.

**Comment by acorvelo** [comment]
Any idea why, given the same set of regions, it consistently crashes on some CRAMs but not on others?

**Comment by daviesrob** [comment]
I think you were just lucky that it worked, probably due to the layout of data in memory.  With [address sanitizer](https://github.com/google/sanitizers/wiki/AddressSanitizer) enabled, I get a crash even with the "good" file.
