### ISSUE TITLE
Allow users to specify index location for idxstats

### ISSUE THREAD

**Issue by smlchen** [samtools/samtools#2071]
#### Is your feature request related to a problem? Please specify.
No

#### Describe the solution you would like.
`samtools idxstats` assumes the bai file lives in the same directory as the bam file, but in my use case, bai files are in a different directory.

**Comment by jkbonfield** [comment]
You can use the generic `filename##idx##indexname`. Eg:

```
samtools idxstats /tmp/_2.bam##idx##/tmp/idx.csi|head
...
```

**Comment by smlchen** [comment]
OH I did not see this in the `samtools idxstats` documentation. Now I found this mentioned in the main samtools documentation. With such notation, why is there a need to use `-X` in samtools view, which I have used as a way to specify the location of the index file?

**Comment by whitwham** [comment]
The quick answer to your question is that the `-X` options was implemented in a selection of tools first.  There were limitations to that option so the `filename##idx##indexname` was added.  If you want to dig through the links of this #978 you can get the whole story.

**samtools** is about 15 years old now and has had multiple authors so a certain amount of history is involved.
