### ISSUE TITLE
samtools markdup on PacBio HiFi long reads

### ISSUE THREAD

**Issue by kamilafras** [samtools/samtools#2074]
#### Are you using the latest version of [samtools]
samtools 1.19

 #### Please describe your environment.
-Linux 6.5.0-35-generic
-x86_64
-gcc (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0

#### Please specify the steps taken to generate the issue, the command you are running and the relevant output.

I have been adapting a standard short sequencing pipeline to long reads. The short sequence pipeline can have a remove duplicates step. Therefore, I have also done this to my long reads, although from my understanding of PacBio HiFi, there should not be any duplicates. 
I am running samtools markdup on fastq files generated by PacBio HiFi: 
samtools markdup -r -l 50000 -s ${file_location}.sorted.bam ${file_location}.bam

The results show a substantial amount of single duplicates:

READ: 2441520
WRITTEN: 2395200
EXCLUDED: 342824
EXAMINED: 2098696
PAIRED: 0
SINGLE: 2098696
DUPLICATE PAIR: 0
DUPLICATE SINGLE: 46320
DUPLICATE PAIR OPTICAL: 0
DUPLICATE SINGLE OPTICAL: 0
DUPLICATE NON PRIMARY: 0
DUPLICATE NON PRIMARY OPTICAL: 0
DUPLICATE PRIMARY TOTAL: 46320
DUPLICATE TOTAL: 46320
ESTIMATED_LIBRARY_SIZE: 0

My question is, how can this be possible and should I include this remove duplicates step in the long read pipeline?

**Comment by whitwham** [comment]
So, **samtools markdup** was written for paired short read data.  The check for single read duplicates is much less rigorous than it is for paired reads.  This does not really matter for Illumina style sequencing, but for PacBio where everything is unpaired (I think) it becomes a problem.

If you are not expecting duplicate reads then I would not run a duplicate marking step for your pipeline.  I think it will just produce dubious results.

However, if you look at the results and they really are duplicates I would be very interested in looking at your data.

Also, nice use of the **-l** option.  At least someone looks at the documentation.
