### ISSUE TITLE
add an option to write down readnames which failed primer check under FSS stats section

### ISSUE THREAD

**Issue by mmokrejs** [samtools/samtools#2077]
`samtools ampliconstats` verifies if the PCR products aligned to the reference originate in the primer regions. I want to get a list of readnames which failed this QC check. The list of those passing would be supposedly too large but either would do for me. I will discard both mates so I do not need if it was R1 or R2 read failing.

I assume this is the section frm the `astats` file:

```
# Summary stats.
# Use 'grep ^FSS | cut -f 2-' to extract this part.
FSS     mysample      MN908947.3_S_protein    raw total sequences:    360823
FSS     mysample      MN908947.3_S_protein    filtered sequences:     337
FSS     mysample      MN908947.3_S_protein    failed primer match:    951
FSS     mysample      MN908947.3_S_protein    matching sequences:     359535
FSS     mysample      MN908947.3_S_protein    consensus depth count < 1 and >= 1:     0       350
```

A cmdline switch to write them to some txt file would be helpful in general.

BTW: What are those "filtered sequences"? The manpage lacks info about the "failed primer match" at least. Thank you.

**Comment by whitwham** [comment]
> BTW: What are those "filtered sequences"? The manpage lacks info about the "failed primer match" at least. Thank you.

From the manual page: `filtered sequences	Number of sequences filtered with -F option`.

If you want to discard unclipped reads, and keep a record of them, you can do that at the ampliconclip stage.

`samtools ampliconclip -b mybedfile.bed --clipped --rejects-file stuffidontwant.bam -o stuffiwant.bam infile.bam`

**Comment by whitwham** [comment]
No reply from OP, closing.
