### ISSUE TITLE
samtools faidx selected regions do not include the description

### ISSUE THREAD

**Issue by korneel-emweb** [samtools/samtools#2080]
#### Are you using the latest version of [samtools](https://github.com/samtools/samtools/releases/latest) and [HTSlib](https://github.com/samtools/htslib/releases/latest)? If not, please specify.
samtools 1.12
Using htslib 1.12

 #### Please describe your environment.
- OS: Linux 5.15.0-106-generic
- machine architecture: x86_64
- compiler: gcc (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0

#### Please specify the steps taken to generate the issue, the command you are running and the relevant output.

When I run `samtools faidx input.fasta -r acc.txt`, where `acc.txt` is a list of one accession per line. The output selects the listed sequences as expected, but it doesn't output the full sequence description (only the accession). I also didn't find a flag to enable this or something. Is this expected? Is there a way to include the description in the output?

```
korneel@jarvis:~/tmp/samtools-faidx$ samtools faidx msa.fasta -r acc.txt -o msa-subset.fasta

korneel@jarvis:~/tmp/samtools-faidx$ grep -f acc.txt msa.fasta
>GU397408.1.1459 Bacteria;Proteobacteria;Gammaproteobacteria;Pseudomonadales;Halomonadaceae;Salicola;Salicola marasensis
>AM271002.1.1457 Bacteria;Proteobacteria;Alphaproteobacteria;Sphingomonadales;Sphingomonadaceae;Porphyrobacter;Porphyrobacter meromictius
>KM507127.1.1475 Bacteria;Firmicutes;Bacilli;Bacillales;Bacillaceae;Bacillus;Bacillus anthracis
>CP001147.916471.917963 Bacteria;Nitrospirota;Thermodesulfovibrionia;Thermodesulfovibrionales;Thermodesulfovibrionaceae;Thermodesulfovibrio;Thermodesulfovibrio yellowstonii DSM 11347
>CP032931.634692.636265 Bacteria;Firmicutes;Bacilli;Lactobacillales;Lactobacillaceae;Levilactobacillus;Lactobacillus brevis

korneel@jarvis:~/tmp/samtools-faidx$ grep "^>" msa-subset.fasta 
>CP032931.634692.636265
>AM271002.1.1457
>CP001147.916471.917963
>KM507127.1.1475
>GU397408.1.1459
```

**Comment by jkbonfield** [comment]
The way the .fai index works is it holds the entry name and the byte offset of the sequence data follwing the name.

```
$ head -1 $HREF38
>chr1  AC:CM000663.2  gi:568336023  LN:248956422  rl:Chromosome  M5:6aef897c3d6ff0c78aff06ac189178dd  AS:GRCh38

$ head -1 $HREF38.fai
chr1	248956422	112	80	81
```

Therefore to extract the comment data, we'd need to use the previous entry in the .fai file, do some maths to work out where its sequence ends, and then use that to re-read the name field to get the comments.  Plus caveats for the first entry obviously.

While possible, it's clearly not what the designers had in mind for faidx so the decision to omit arbitrary comment information was a deliberate policy.  I'm not inclined to overturn that decision unless I understand the use case, as it's quite fiddly and opens a huge can of worms given the ill defined nature of the fasta format.  At the very least it would have to be optional and disabled by default.

How important is this data to you?   Generally it seems to mostly just be human readable data (sometimes more in fastq, but not in any files we tend to index).
