### ISSUE TITLE
`samtools markdup` optical duplicate distance calculation

### ISSUE THREAD

**Issue by prosequtor** [samtools/samtools#2088]
First and foremost: huge thanks to everyone involved in creating and maintaining this software tool.

It appears that `samtools markdup` for each original/duplicate or duplicate/duplicate pair of read cluster X,Y-coordinates on the flow cell compares the delta(x1, x2) and/or delta(y1, y2) against the pixel distance `-d` parameter value instead of calculating the Pythagorean distance between the read clusters sqrt((x1-x2)^2 + (y1-y2)^2): lines of code 885 -- 901 in https://github.com/samtools/samtools/blob/develop/bam_markdup.c

```
if (ox > dx) {
xdiff = ox - dx;
} else {
xdiff = dx - ox;
}

if (xdiff <= max_dist) {
     // still might be optical

     if (oy > dy) {
     ydiff = oy - dy;
     } else {
     ydiff = dy - oy;
     }

     if (ydiff <= max_dist) ret = 1;
}
```

Is there any mechanistic reason for such algorithm design? It seems more appropriate to use a Pythagorean distance, at least on nonpatterned flow cell reads where optical duplicate cluster coordinates are not limited to being offset only along one axis (X or Y).

As of today, at least three other tools that I know of that can classify duplicates as optical do the exact same thing (I have not yet inquired about this on their respective pages, as `samtools markup` is my preferred tool for the current analysis pipeline):
`picard markuplicates` v.3.2.0
`biobambam2 bammarkduplicatesopt` v.2.0.87
`doppelmark` v.0.1.1

On the other hand, `bbmap clumpify` v.39.08 and `rumidup` (original release) seem to calculate the Pythagorean distance between clusters to compare it against the pixel distance parameter.

My first ever report on github, apologies for breaking any etiquette rules.
Thank you!!

cc: @whitwham

**Comment by whitwham** [comment]
We use the Manhattan distance for speed.  There are fewer calculations and integer maths is faster than floating point maths.  The speed might not make much of a difference when you are doing a single calculation but when you are doing millions or billions then the time starts adding up.

Also, the distances involved in deciding what is an optical duplicate are really just estimates.  I am not sure more precision would be appropriate or beneficial.

**Comment by prosequtor** [comment]
Thank you for the explanation! Speed vs. importance considerations make sense.

Since the algorithm compares cluster coordinate differences against the distance parameter `-d` for each axis separately without summing them this looks more like a case of measuring the [Chebyshev distance](https://en.wikipedia.org/wiki/Chebyshev_distance).
