### ISSUE TITLE
Request for release 1.21

### ISSUE THREAD

**Issue by nh13** [samtools/samtools#2090]
Hey folks, I would request a release (1.21?) as needed for the [nf-core fastquorum pipeline](https://github.com/nf-core/fastquorum/issues/53#issuecomment-2260066846).  The last one was in April, and I am looking for functionality in the merged PR #2062 as part of the release.  Thank-you for considering this request

**Comment by whitwham** [comment]
We are working towards it but we have no firm relase date yet.

**Comment by nh13** [comment]
I understand, I appreciate your work and a response!

**Comment by nh13** [comment]
And I’d be glad to help of course

**Comment by jkbonfield** [comment]
Closing as 1.21 is out.
