### ISSUE TITLE
Not an issue, more of a question.

### ISSUE THREAD

**Issue by TJrogers86** [samtools/samtools#2092]
Hello! Sorry, this isnt an issue, its more of a question on proper use of samtools. I have multiple samples and I want to compare relative abundance of contigs across those samples. I used bowtie2 to create a sam file and then use samtools view, sort, and index to convert and sort the sam file to a bam file. Now, I see that the default set up for samtools view is "samtool view -F 4", which if I understand correctly, excludes unmapped read counts. I see a lot of people using this default setting and then converting the sam file to create relative abundance down stream. However, it would seem to be better to use "samtools view -F 2048" as this would exclude unmapped reads as well as secondary and supplementary alignments, leaving only primary alignments. Am I mistaken in this thought process? Thanks for any insight you can offer!

**Comment by whitwham** [comment]
`samtools view -F 2048` only excludes supplementary reads.  To do unmapped, supplementary and secondary you would need `samtools view -F 2308`.  You can use the `samtools flags` command to check your binary values.

As for whether this is a valid approach?  I don't know, it doesn't seem bad.  Maybe someone else can comment.

**Comment by whitwham** [comment]
No further comment from OP, closing.
