### ISSUE TITLE
samtools fastq with -T option to extract methylation tag generates truncated fastq header.  

### ISSUE THREAD

**Issue by qiangfu-eu** [samtools/samtools#2102]
We are handling raw Nanopore reads generated by dorado basecaller in BAM file with methylation information. To align the reads with methylation information, we extract read sequence from BAM with MM and ML tag using **samtools fastq** command with **-T** option. 

`samtools fastq -T MM,ML -@ 8 SQK-NBD114-96_barcode18.bam > PAS51605_barcode18.fastq`

The annotated fastq file are then aligned by minimap2 and sorted. However, when sorting by **samtools**, it compliants `[E::sam_parse_B_vals_r] Malformed B:C`. Checking the SAM file generated by minimap2, I noticed that for some records ML tags is missing. After a closer search, I found that ML tag is already missing after running **samtools fastq**.

I noticed that this is a very long read with large MM and ML tags. I wonder whether also there is some limits on the size of the header? I tested samtools v1.20, v1.16, both have same issue.

Attached three files containing:
- the original read record in unaligned BAM
- the extract read record in FASTQ (ML missing)

[PAS51605_barcode18_e8981b67-73e1-493c-9448-f4910286e532.original_bam.rcd.txt](https://github.com/user-attachments/files/16697535/PAS51605_barcode18_e8981b67-73e1-493c-9448-f4910286e532.original_bam.rcd.txt)
[PAS51605_barcode18_e8981b67-73e1-493c-9448-f4910286e532.fastq_rcd.txt](https://github.com/user-attachments/files/16697537/PAS51605_barcode18_e8981b67-73e1-493c-9448-f4910286e532.fastq_rcd.txt)

**Comment by jkbonfield** [comment]
I'm not able to reproduce this.  The ML tag is there in the fastq output.  `samtools import -T MM,ML` parses it back out again too when ingesting fastq to unaligned SAM, so it's apparently in the valid format.

There shouldn't be any line length limitations as it's using a `kstring`.  Also I note it constructs the entire FASTQ record as a single string, so including name, sequence and quality.  If it was a length limit then it'd have truncated quality and/or sequence.
