### ISSUE TITLE
consensus docs 1:1 coordinate correspondence inaccurate?

### ISSUE THREAD

**Issue by schorlton-bugseq** [samtools/samtools#2111]
Hi! Thanks for the recent work on `consensus` - it is great. I'm wondering if the docs (accessed Sep 12, 2024) could be improved on this line:
![image](https://github.com/user-attachments/assets/fc8ff8ad-6ab3-487b-9208-cf6f44adcafe)

This post (and my reasoning) would suggest that `--show-del yes` is also needed in the command: https://github.com/samtools/samtools/issues/1806#issuecomment-1477751524

Thanks!

**Comment by jkbonfield** [comment]
You are correct.  Thank you for raising this issue.  I'll fix the man page.

**Comment by schorlton-bugseq** [comment]
Thanks all!
