### ISSUE TITLE
markdup error with updated samtools

### ISSUE THREAD

**Issue by kristyhoran** [samtools/samtools#2117]
#### Are you using the latest version of [samtools](https://github.com/samtools/samtools/releases/latest) and [HTSlib](https://github.com/samtools/htslib/releases/latest)? 
Yes 
If not, please specify.

 #### Please describe your environment.
- OS : Linux **4.18.0-553.16.1.el8_10.x86_64**
- machine architecture : x86_64
- compiler: gcc (GCC) 8.5.0 20210514 (Red Hat 8.5.0-22)
- 
#### Please specify the steps taken to generate the issue, the command you are running and the relevant output.

I want to run `markdup -r`. In previous versions, 

```
bwa mem -T 50 -Y -M -R '@RG\tID:Sample\tSM:Sample' -t 8 reference.fa R1.fastq.gz R2.fastq.gz | samclip --max 10 --ref reference.fa.fai | samtools sort -n -l 0 --threads 8 -m 1000M  | samtools fixmate -m - - | samtools sort -l 0  --threads 8 -m 1000M | samtools markdup  -r -s - - > output.bam
```

Has worked (samtools v1.20). However, when i try to run the same command with version 1.21 the following errorr is reported

```
samtools markdup: error, no ms score tag. Please run samtools fixmate on file first.

samtools markdup: error, no ms score tag. Please run samtools fixmate on file first.
```

I note that in the recent release on https://newreleases.io/project/github/samtools/samtools/release/1.21 the following change has been made to `fixmate`:

```
samtools fixmate no longer removes the PAIRED flag from reads that have no mate. This is done on the understanding that the PAIRED flag is a sequencing technology indicator not a feature of alignment. This is a change to previous fixmate behaviour. (PR [#2056](https://github.com/samtools/samtools/pull/2056), fixes [#2052](https://github.com/samtools/samtools/issues/2052). Reported by John Wiedenhoeft)
```

And i wonder if this has caused my problem. I will rollback to 1.20 for now - but thought it would be nice to get your opinion/advice on this.

Many thanks in advance

Cheers
Kristy

**Comment by whitwham** [comment]
Thank you for that report.  I appear to have broken my own program.
