### ISSUE TITLE
Tool to convert from genome-aligned bam to transcriptome bam

### ISSUE THREAD

**Issue by joegeorgeson** [samtools/samtools#2124]
#### Is your feature request related to a problem? Please specify.
I am not aware of a tool to convert from 'genome space' to 'transcriptome space' at the level of the bam file.

#### Describe the solution you would like.
A new function, perhaps integrated into `samtools view` to pass a genome-aligned bam and bed file, and get returned a transcriptome bam file. The opposite of the rsem function `rsem-tbam2gbam`

**Comment by whitwham** [comment]
We do not really have the time or resources to dedicate to writing a tool like this.  Unless we discover a widespread need, we can not really justify it.

You could try asking on [Biostars](https://www.biostars.org).  Someone there might know of a tool that you can use.

**Comment by joegeorgeson** [comment]
Thanks for the reply, but bummer...I figured if anyone could do this it's samtools.

**Comment by whitwham** [comment]
Sorry we can't help.  We're not a big team and we have other projects to do alongside samtools.
