### ISSUE TITLE
samtools idxstats counts multiple times reads mapped more than once or in multiple fragments

### ISSUE THREAD

**Issue by nicolo-tellini** [samtools/samtools#2129]
#### Describe the solution you would like.
samtools idxstats counts reads multiple times if they are mapped more than once or in multiple fragments. However, this approach can be inconvenient and often confusing. Counting the same reads multiple times inflates the total read count, leading to a number that is difficult to interpret because:

    It results in more reads than those present in the FASTQ files.
    It does not indicate how many reads are counted more than once, which would be useful information.

**Comment by jkbonfield** [comment]
The SAM specification [states](https://github.com/samtools/hts-specs/blob/master/SAMv1.tex#L1326-L1331):


```
The index file may optionally contain additional metadata providing a summary
of the number of mapped and placed unmapped read-segments per reference sequence,
and of any unplaced unmapped read-segments.\footnote{By \emph{placed unmapped
read} we mean a read that is unmapped according to its {\sf FLAG} but whose
{\sf RNAME} and~{\sf POS} fields are filled in, thus ``placing'' it on a
reference sequence (see Section~\ref{sec:recommended-practice}).
```

Note _read-segments_ here.  Samtools idxstats is just reporting the index meta-data bins, and we cannot change the meaning of the data here as it is part of the BAM specification.

Instead you will need to use `samtools flagstat` and do a full scan through the file.  There is no other alternative to this unfortunately.
