### ISSUE TITLE
Consensus IUPAC Heterozygous Fraction

### ISSUE THREAD

**Issue by schorlton-bugseq** [samtools/samtools#2130]
#### Are you using the latest version of [samtools](https://github.com/samtools/samtools/releases/latest) and [HTSlib](https://github.com/samtools/htslib/releases/latest)? If not, please specify.
(run `samtools --version`)

Yes - samtools 1.2.1

 #### Please describe your environment.
- OS (run `uname -sr` on Linux/Mac OS or ` wmic os get Caption, Version` on Windows)
- machine architecture (run `uname -m` on Linux/Mac OS or ` wmic os get OSArchitecture` on Windows)
- compiler (run `gcc --version` or `clang --version`)

micromamba docker

#### Please specify the steps taken to generate the issue, the command you are running and the relevant output.

Hi! I ran `samtools mpileup --min-BQ 4 test.bam` and got the following line:
```
contig_10       776752  N       20      gGA*GgGGAgaAaAa*agaG    ;*96-&<2&?D-;.>'?0,&
```

I then run `samtools consensus -o test.fna -H 0.5 -c 0.25 --min-BQ 4 --show-ins no --min-depth 10 --show-ins no -m simple test.bam`

My goal was to always output a base, hence setting `-c` to 0.25. Based on the pile up, I was expecting an `R` at this position (both `A` and `G` are at 9/20), however I got an `A`. Am I misunderstanding the parameters or is there a potential bug here? Thanks for your help!!

**Comment by jkbonfield** [comment]
I haven't gone through the quality string checking, but it's likely it's not 9/20 for the sum.  If you want it to purely work off base frequency and to ignore base quality you'll need to specify `-q`.

**Comment by schorlton-bugseq** [comment]
Thanks for the quick response. Reading the docs, I understood `-q` as the opposite of above, i.e. that it _enabled_ used of qualities for simple consensus mode. Is this not the case?

![image](https://github.com/user-attachments/assets/626ae446-3c95-4c0e-9025-531a65ab8640)

**Comment by jkbonfield** [comment]
Oh sorry, yes I'm reading my usage statement wrongly!  Ignore me.

In that case I'm not sure.  Is it possible to provide the test.bam data, or to produce a minimal test case of that column only?

**Comment by schorlton-bugseq** [comment]
Hopefully this does it. Same coordinate as the pileup from the issue description. Thanks!

[region.bam.gz](https://github.com/user-attachments/files/17398628/region.bam.gz)

**Comment by jkbonfield** [comment]
Ah I see the problem!  I've forgotten how to use my own code, but it also indicates it probably ought to be a bit more obvious.

The problem is simply that you didn't ask for ambiguity codes to be generated (via the `-A`) option.  I good argument could be made for options that govern the thresholds for ambiguous bases, such as `-H`, to automatically imply `-A` as otherwise they have no impact.  However that's not how it works.

So a simple fix fortunately is just to add `-A` onto the argument list.

**Comment by schorlton-bugseq** [comment]
OH! Silly me. Thanks for catching that! Agree that a warning or even error would be helpful for `-H` without `-A` or imply `-A` from `-H`.
