### ISSUE TITLE
samtools mpileup doesn't count insertion at the begining of a read

### ISSUE THREAD

**Issue by TausifIqbal** [samtools/samtools#2132]
#### Version
samtools 1.21
htslib 1.21

 #### Environment.
- OS                 Linux 6.8.0-1016-aws
- machine architecture      x86_64
- compiler 13.2.0

#### Issue
When using samtools mpileup, the tool does not count insertions at the beginning of a read. 
For example, with a CIGAR string of 3I65M, the insertion (3I) is not represented in the mpileup output for the position where the read is aligned.

**Comment by jkbonfield** [comment]
Unfortunately this is a fundamental flaw in BAM with CIGAR strings.  Alignments have a position which is listed as the first mapped based.  With 3I65M the inserted bases arrive before the first mapped base so cannot end up in a pileup as the record isn't added to the list of in-flight alignments until it is too late.  Even worse, if doing a region query, they may not be found by the index either.

It is possible to fix, but it would break way too many things.  In [Gap5](https://staden.sourceforge.net/) import of SAM/BAM I fixed this with some highly dubious hackery by decrementing the position of all incoming alignments and prepending them with 1D, as that deletion *is* anchored on a reference base (unless chr pos 1) and the insertions will then get detected.  It then has some clean up code to go through removing the leading gap.  It was a horrid hack, but I couldn't find any other way of getting POS + CIGAR to correctly honour leading insertions.

Unfortunately doing this trick in htslib would cause mayhem as it's not a transparent operation.  A possible other fix is simply to include reads that start 1 base further on if they contain an insertion at the start, but it would require code using the pileup structures to double check the read position to detect this scenario and nothing currently does that so this would have to be an option/extension - so a new API basically.

I suspect it's simply not viable to achieve.  What is the scenario you have where this data is cropping up?  It can't happen with normal alignments, but in Gap5 I had it from manual editing or local reassembly of data.

**Comment by TausifIqbal** [comment]
Thankyou for the reply,
I was trying to count the number of inserted bases in a BAM file for that I was using samtools mpileup.
In the official documentation of samtools [mpileup](https://www.htslib.org/doc/samtools-mpileup.html), I didn't find any note about `insertion at the begining of a read`. I thought it might be a bug.

I can use different approach to count the number of inserted bases.

I am closing this issue, as it is a flaw in BAM with CIGAR strings. 
Thankyou again for time and clarification.

**Comment by jkbonfield** [comment]
As I say it's possible to implement something like this yourself if you do some editing of the incoming BAM reads before putting into the queue for the pileup algorithm, namedly decrement position by 1 and insert 1D to the CIGAR string!  If you only care about INS then the other problems that creates will vanish.  However there's no command-line way of doing this.  (I guess a sed statement or script could hack CIGAR to make it work before running samtools mpileup.  It'd be ugly though, but it may solve your immediate issue!)
