### ISSUE TITLE
samtools consensus threads

### ISSUE THREAD

**Issue by sejmodha** [samtools/samtools#2134]
Hi

I have noticed that `samtools consensus` command always uses 1 thread despite more (-@ 8) threads have been specified in the command. As shown in the processing time stats below, multiple thread specification does not have any substantial impact.

```
time samtools consensus -X r10.4_sup -o ~/analyses/samtools_test_cons.fa ~/analyses/BIOINFO_plasmid_test/results/minimap2/TEST_1_1/TEST_1_1_mapped.bam

real    3m12.478s
user    3m11.181s
sys     0m1.286s

time samtools consensus -@ 8 -X r10.4_sup -o ~/analyses/samtools_test_cons.fa ~/analyses/BIOINFO_plasmid_test/results/minimap2/TEST_1_1/TEST_1_1_mapped.bam

real    3m18.814s
user    3m19.436s
sys     0m1.992s
```

Results are for a smaller subset of data (~25k ONT reads), but I have observed this for large datasets too. `samtools consensus` threading is creating a bottleneck in data processing. Is this behaviour anticipated? Any suggestions on how to tackle this would be appreciated.

Thanks
Sej

**Comment by jkbonfield** [comment]
The multi-threading is on file decode only as the algorithm itself is not multi-threaded.  A better threading system for stitching together embarassingly parallel operations like this (and mpileup) is on my to-do list, but it's a big project.

Hence the CPU time is often dominated by the consensus algorithm itself.  I suspect with long reads this becomes even more significant as there is more consensus to compute per read and so the shift in where CPU is spent changes a bit.

We should probably change the usage to say "number of additional decompression threads to use".

**Comment by sejmodha** [comment]
Thanks for that clarification. 
I have not tried to call consensus with CRAM but such little benefit, I might just leave it as is for now.

**Comment by jkbonfield** [comment]
Indeed.  I added better documentation anyway, even if it's not a particularly satisfactory solution.

Ideally I'd like it to do the right thing, which would be to split the file or initial region up into smaller sub-regions and have one thread per sub-region computing the consensus, stitching them together again at the end.  This has some duplication of work, especially on long read techologies, as some reads will be processed twice given they overlap neighbouring regions.  However with large enough sub-regions we'd get sensible parallelism.  The same could be applied to many data producing tasks such as mpileup too, or mergable stats gathering functions.

It's a long term goal as I know how it can be done, but I just haven't found the time to do it yet.
