### ISSUE TITLE
Samtools stats seems to incorrectly report inward/outward oriented pairs?

### ISSUE THREAD

**Issue by rachaelanndetar** [samtools/samtools#2137]
samtools 1.17 (using htslib 1.18)
OS: Linux 3.10.0-1160.119.1.el7.x86_64
machine architecture: x86_64
compiler: gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-44)

#### Please specify the steps taken to generate the issue, the command you are running and the relevant output.

I aligned my (stranded) reads to a reference transcriptome using bowtie2. I then filtered my alignment for reads with sam flags 163/83 as follows:

        samtools view -h -f 83 -q 10 alignment.sam > filteredmate1.sam #enable for filtering
        samtools view -h -f 163 -q 10 alignment.sam >>filteredmate2.sam #enable for filtering
        samtools merge filtered_alignment.sam filteredmate1.sam filteredmate2.sam
        samtools sort -O bam -o filtered_alignment.bam filtered_alignment.bam

I then did as follows to get alignment statistics:

          samtools stats filtered_alignment.bam > filtered_alignment_stats.txt

Oddly, samtools stats reported 8172095 inward oriented pairs, and 19180 outward facing pairs. Based on the Samtools documentation, Shouldn't all my pairs be outward facing after filtering for Sam flags 163 ( 0x1,0x2,0x40,0x20) or 83 (0x1,0x2,0x80,0x10)? I actually wouldn't expect these to be outward oriented, its just a standard  stranded Illumina RNA seq library, just that most first in pair reads map reverse since its a stranded cDNA library. Maybe there is just something here I am not understanding?

**Comment by vasudeva8** [comment]
The flag as well as the position matters in determining a pair as inward or outward.
With 163 (0x - 1,2,20,80), pos > mpos gives outward and pos < mpos gives inward pair.
With 83 (0x - 1,2,10,40), pos < mpos gives outward and pos > mpos gives inward pair.
You can try -e to filtering using relative position of a read and its mate position.
