### ISSUE TITLE
merging from 2 files and 80 in-memory blocks...

### ISSUE THREAD

**Issue by Taylorain** [samtools/samtools#2138]
Hi, I am reaching out to seek clarification regarding an issue I encountered while using the `samtools merge` command in combination with `samtools sort`. 
I executed the following command to merge 129 BAM files generated by Dorado:

```bash
samtools merge -@ 80 -O BAM - *.bam | samtools sort -@ 80 -o /bio/2.merge_bam/sorted_bam -
```

While the command successfully generates the sorted BAM file, I noticed an unusual warning in the output:

```
[bam_sort_core] merging from 0 files and 80 in-memory blocks...
```

This message seems to indicate that no input files were detected, despite the fact that the merge process appears to have completed successfully.

Could you please help me understand why this warning is displayed? Is it possible that there is an issue with how the files are being piped between the commands? Any guidance you can provide would be greatly appreciated.

Thank you for your time and assistance.

**Comment by jkbonfield** [comment]
That message is from sort.  It splits input into blocks per thread, which can spill to disk if memory usage is too high.  It's simply saying you have 80 in-memory blocks and no blocks spilled to disk.  So it worked fine.

Although what you're doing is slow.  It's better to use `-u` instead of `-O bam` as you're spending a lot of time writing compressed BAM to stdout and then decompressing it again.  For a pipe there's no reason to compress and decompress.

**Comment by Taylorain** [comment]
I get, thanks pretty much!

**Comment by Taylorain** [comment]
Hi, thank you for your kind reminder.
I have confirmed that my BAM files are indeed sorted by coordinate. I would like to clarify whether the BAM files generated by basecallers like Dorado or Guppy, which internally use minimap2, are always coordinate-sorted upon generation. Is this also true for BAM files generated by other software?

Additionally, in what situations is it necessary to sort BAM files after they have been generated?

Thank you for your assistance!

**Comment by whitwham** [comment]
This is an impossible question to answer.  Programs that create BAM files will output in an order (or lack of order) chosen by that program's creators.  You will have to check each program individually.

You need to sort the BAM files depending on the use you are putting them to.  Again, this is something you have to determine for yourself.

**Comment by jkbonfield** [comment]
Typically alignment tools will not sort their output.  Some will maintain the same output order as input order, while others may shuffle things a bit (possibly in large blocks if threading).    If an aligner is inputting paired sequences then they will need the data collated by name if given a single file, or a pair of files with records arriving in each in the same order.  As you're using Dorado I doubt that's an issue though as it'll be single ended long-reads.

It's quite possible however that your alignment files were themselves the result of an `aligner input.fastq | samtools sort -o output.bam` style pipeline, which would explain why your input files pre-merging are already coordinate sorted.  Theoretically you can do `samtools head file.bam | egrep '^@PG'` to look at the program-group records which *should* tell you the list of commands executed to produce that file.  In practice it's down to the pipelines as to whether they record data provenance.  A good one will, but not everyone writes good software. ;-)

To make matters more complicated, it's possible you just have unaligned BAMs, as that's a native output format of Dorado.  (Indeed it's a sensible alternative to gzipped fastq as BAM offers auxilary tags and is a much richer file format for storing such things than fastq.).   While technically an entire file of unaligned data is position sorted, it's a bit of a nul-case as all random orderings are also position sorted as everything has the same position (ref "*" pos 0).  You should check with a `samtools view` to take a look at a few records.

**Comment by Taylorain** [comment]
Ah, I see. Thank you very much for explaining it!
