### ISSUE TITLE
faidx --write-index invalid free with process substitution regions

### ISSUE THREAD

**Issue by ASLeonard** [samtools/samtools#2142]
It seems using a process substitution for extraction regions can cause issues with `--write-index`. I ran *almost* the same command on the same data using the two-pass approach in #2118 and never hit this issue, so may be related to the region list already being consumed before freeing at the end?

```
# error
samtools faidx --write-index -r <(echo -e "1\n2\n3") -o region.fa.gz genome.fa.gz
free(): invalid next size (fast)
Aborted

# no error
echo -e "1\n2\n3" > temp.txt
samtools faidx --write-index -r temp.txt -o region.fa.gz genome.fa.gz
```
GDB tracked the error back to this free, but all the variables were optimised out despite trying to recompile htslib/samtools more debug friendly.

https://github.com/samtools/samtools/blob/86fd06e804387b3a2175967875faa74a2b6259c1/faidx.c#L666

This was run with
```
samtools 1.21-13-g86fd06e-dirty
Using htslib 1.21-15-g1d2e493b-dirty
```

-Alex

**Comment by vasudeva8** [comment]
Tried to reproduce using the mentioned version, on ubuntu and Mac, but didn't work.

Could you share more information like full version output fromx samtools, OS in which the issue was observed, any error log observed, presence of output index file and if possible dummy data with which it can be reproduced.

**Comment by ASLeonard** [comment]
The invalid free seems quite sporadic, this happened about 10 times out of maybe 2000 faidx calls. Even more strangely, the following sequence works without error, so I don't think there in anything inherently wrong with these sequences.

```
samtools faidx -r <(echo -e "1\n2\n3") -o region.fa.gz genome.fa.gz
samtools faidx region.fa.gz
samtools faidx --write-index -r <(cut -f 1 region.fa.gz.fai) -o region2.fa.gz region.fa.gz
```

There are 20 chromosome contigs I'm trying to pull out, and taking up to `head -n 16` or `tail -n 18` works, so it isn't any one contig that is always problematic.

Also interestingly, but even despite the crash, the output files all look correct. The md5sum of the 2-step extract-then-index ".fai" matches the md5sum of the crashed ".fai", and I can pull any contig from the compressed output (`samtools faidx region.fa.gz 2`), so it does all it needs to and then crashes at the end.

I can't make a smaller reproducible example, and the offending genome is consortium data that I can't share openly. I can probably send you a private link to an email if you [reach me here](https://ag.ethz.ch/people/person-detail.Mjc3MDky.TGlzdC8yODA0LC0yMDQxNjc4MDA1.html).


This was on Ubuntu 22.04.5 LTS with kernel 5.15.0-124-generic. The full version output
```
samtools 1.21-13-g86fd06e-dirty
Using htslib 1.21-15-g1d2e493b-dirty
Copyright (C) 2024 Genome Research Ltd.

Samtools compilation details:
    Features:       build=configure curses=yes 
    CC:             x86_64-conda-linux-gnu-cc
    CPPFLAGS:       -DNDEBUG -D_FORTIFY_SOURCE=2 -O2 -isystem
    CFLAGS:         -Wall -flto=auto -pipe -march=x86-64-v3 -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O3 -ffunction-sections 
    LDFLAGS:        -Wl,-O2 -Wl,--sort-common -Wl,--as-needed -Wl,-z,relro -Wl,-z,now -Wl,--disable-new-dtags -Wl,--gc-sections -Wl,--allow-shlib-undefined
    HTSDIR:         ../htslib
    LIBS:           
    CURSES_LIB:     -lncursesw

HTSlib compilation details:
    Features:       build=configure libcurl=yes S3=yes GCS=yes libdeflate=yes lzma=yes bzip2=yes plugins=no htscodecs=1.6.0-5-g5a2627e
    CC:           x86_64-conda-linux-gnu-cc
    CPPFLAGS:       -DNDEBUG -D_FORTIFY_SOURCE=2 -O2 -isystem
    CFLAGS:         -Wall -flto=auto -pipe -march=x86-64-v3 -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O3 -ffunction-sections -isystem -fvisibility=hidden
    LDFLAGS:        -Wl,-O2 -Wl,--sort-common -Wl,--as-needed -Wl,-z,relro -Wl,-z,now -Wl,--disable-new-dtags -Wl,--gc-sections -Wl,--allow-shlib-undefined -fvisibility=hidden 

HTSlib URL scheme handlers present:
    built-in:	 file, preload, data
    S3 Multipart Upload:	 s3w+https, s3w+http, s3w
    Amazon S3:	 s3+https, s3, s3+http
    Google Cloud Storage:	 gs+http, gs+https, gs
    libcurl:	 gophers, smtp, wss, smb, rtsp, tftp, pop3, smbs, imaps, pop3s, ws, ftps, https, http, ftp, gopher, imap, sftp, smtps, scp, dict, mqtt, telnet
    crypt4gh-needed:	 crypt4gh
    mem:	 mem
```

**Comment by vasudeva8** [comment]
Thank you for the reporting this issue and sharing details. I have identified an issue in #2125 and a fix will be made soon.

**Comment by ASLeonard** [comment]
Great thanks! I can confirm 9e91173 fixes the test cases that were crashing before.
