### ISSUE TITLE
samtools index issue

### ISSUE THREAD

**Issue by mushroomm221** [samtools/samtools#2151]
Hi,
I just performed :
samtools index 49hisat2_output.bam.
the error message [E::hts_idx_push] NO_COOR reads not in a single block at the end 19-1
[E::sam_index] Read 'SRR12571149.3' with ref_name='chrM', ref_length=16299, flags=83, pos=6456 cannot be indexed
samtools index: failed to create index for "49hisat2_output.bam". 
What might have gone wrong? Do you have any suggestions?
thanks.

**Comment by jkbonfield** [comment]
It implies your bam file hasn't been coordinate sorted as it has found unmapped reads followed by mapped ones and then unmapped again.

Please use `samtools sort` before indexing (or add `--write-index` to the sort command to auto-index).

**Comment by mushroomm221** [comment]
> It implies your bam file hasn't been coordinate sorted as it has found unmapped reads followed by mapped ones and then unmapped again.
> 
> Please use `samtools sort` before indexing (or add `--write-index` to the sort command to auto-index).
command I used is：
hisat2 -p 8 -x /mnt/d/hisat2_index/hisat2_index -1  SRR12571149_1.fastq -2  SRR12571149_2.fastq -S 49hisat2_output.sam
samtools view -bS 49hisat2_output.sam > 49hisat2_output.bam
samtools reheader header.sam 49hisat2_output.bam > 49hisat2_output_with_rg.bam (this is done to add header to bam file)
samtools sort 49hisat2_output_with_rg.bam -o 49sorted_hisat2_output.bam，But there is an error：samtools sort: truncated file. Aborting.

**Comment by jkbonfield** [comment]
Also what's the *exact* error you get?  This biostars thread is an example of multiple errors being reported where listed the final line wouldn't be useful. https://www.biostars.org/p/368774/

Note the SAM output from hisat2 is plain text, so you can just use `less` on it to view the contents and check whether there is something unexpected in there, such as stderr debugging information.

**Comment by mushroomm221** [comment]
> I don't understand what's happening here. Does hisat output aligned SAM without outputting a header first? It seems unlikely, especially as you were able to do a samtools view to convert from sam to bam. (Also you appear to be following some ancient set of instructions. `view -S` to specifying the input as SAM hasn't been needed for maybe a decade. It auto-senses the file format.)
> 
> I suspect the reheader command is breaking things as it doesn't do much in the way of error checking. So it's possible to take a working BAM and break it by rewriting a new BAM with an incompatible header. You should be able to run `samtools view -H` on the sam and bam files to view their headers and validate that it's correct, and compare that to your header.sam to see what's going on.
> 
> Finally, note you can probably do all this in one command:
> 
> `hisat2 [options] [fastq files] | samtools sort -o hisat_output.bam`
> 
> (Maybe with `-@8` or similar to parallelise the sort).

 I am a beginner in bioinformatics and am not proficient in code. Thank you very much for your patient help.

**Comment by whitwham** [comment]
We don't support Picard, but (as @jkbonfield  said) the problem is with the read names.  MarkDuplicates uses the coordinates embedded in the Illumina read names to calculate optical duplicates.  Since the NCBI has removed those read names then the optical duplicate marking will not work.

If you are not using Illumina sequence data then optical duplicates are probably not a real thing anyway.
