### ISSUE TITLE
Casava tag lost during import/fastq with cram but not bam.

### ISSUE THREAD

**Issue by ASLeonard** [samtools/samtools#2154]
I was testing out converting fastq to uCRAM for some Illumina reads, but seem to have an issue going fastq->uCRAM->fastq that doesn't happen when going fastq->uBAM->fastq or even fastq->uCRAM->uBAM->fastq.

```
samtools import -i -1 reads_1.fq.gz -2 reads_2.fq.gz -o reads.cram
samtools fastq -i --index-format i8i8 -1 reads_roundtrip_1.fq.gz -2 reads_roundtrip_2.fq.gz reads.cram
```

If I roundtrip through uBAM (or uCRAM->uBAM), the original and roundtrip read looks like
```
@A01050:184:HCK2CDSXY:3:1101:2510:1141 1:N:0:ATGAGTCG+AACTAGGC
TGCTTCCACTCGAGATGAATGCCTGTCTCCCCGGGTGCGTCTGGAATGCAACCCCGAGATCCCTGTCGCCCCTGGAGAGGAACAGTGGCTTCTGGACACAAGCCTAGATGAGGTCTATTGGCCCTGCAGTCACTCGAGAGCAATCCCCAG
+
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF:FFFFFFFFFFFFFF,FFFFFFFFFF:FFFFFFF
```

But when I try and go directly back from uCRAM->fastq, the barcode tag is wrong ("0" instead of "ATGAGTCG+AACTAGGC")
```
@A01050:184:HCK2CDSXY:3:1101:2510:1141 1:N:0:0
TGCTTCCACTCGAGATGAATGCCTGTCTCCCCGGGTGCGTCTGGAATGCAACCCCGAGATCCCTGTCGCCCCTGGAGAGGAACAGTGGCTTCTGGACACAAGCCTAGATGAGGTCTATTGGCCCTGCAGTCACTCGAGAGCAATCCCCAG
+
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF:FFFFFFFFFFFFFF,FFFFFFFFFF:FFFFFFF
```

This was on
```
samtools 1.21-17-g9e91173-dirty
Using htslib 1.21-15-g1d2e493b-dirty
htscodecs=1.6.0-5-g5a2627e
```

but also occurs on the bioconda v1.21 version.

**Comment by jkbonfield** [comment]
Thanks for the clear report.  I'll investigate.

**Comment by jkbonfield** [comment]
I see it's a case of over-optimisation.

Given the columnar nature of the format, CRAM decoding can be sped up by requesting specific fields only to be decoded.  We don't decode tags unless we need to.  However in this case we need tags!

You can try `samtools fastq -T BC -i --index-format i8i8 -1 reads_roundtrip_1.fq.gz -2 reads_roundtrip_2.fq.gz reads.cram`.

I'll get the code fixed so `--index-format` also enables tag decoding, as it was an oversight.

**Comment by ASLeonard** [comment]
Yep, running with `-T BC` fixes it in the meantime! Thanks for the tip

**Comment by jkbonfield** [comment]
Actually `-T __` is better maybe as it doesn't then add the BC tag to the header.   We just need something to force CRAM to decode tags (it's all or nothing as it currently stands as far as the optimisations go).

See also PR https://github.com/samtools/samtools/pull/2155
