### ISSUE TITLE
Segmentation fault (core dumped) ; samtools index error

### ISSUE THREAD

**Issue by achimmiri** [samtools/samtools#233]
Hi ,
     I did re hearing of my bam file . My bam file looks good . I did apply samtools flagstat on it . I could able to sort the file but indexing gives me this error .
Segmentation fault (core dumped)

This is the header of my bam file
@HD	VN:1.3	SO:coordinate
@SQ	SN:chr1	LN:249250621
@SQ	SN:chr2	LN:243199373
@SQ	SN:chr3	LN:198022430
@SQ	SN:chr4	LN:191154276
@SQ	SN:chr5	LN:180915260
@SQ	SN:chr6	LN:171115067
@SQ	SN:chr7	LN:159138663
@SQ	SN:chrX	LN:155270560
@SQ	SN:chr8	LN:146364022
@SQ	SN:chr9	LN:141213431
@SQ	SN:chr10	LN:135534747
@SQ	SN:chr11	LN:135006516
@SQ	SN:chr12	LN:133851895
@SQ	SN:chr13	LN:115169878
@SQ	SN:chr14	LN:107349540
@SQ	SN:chr15	LN:102531392
@SQ	SN:chr16	LN:90354753
@SQ	SN:chr17	LN:81195210
@SQ	SN:chr18	LN:78077248
@SQ	SN:chr20	LN:63025520
@SQ	SN:chrY	LN:59373566
@SQ	SN:chr19	LN:59128983
@SQ	SN:chr22	LN:51304566
@SQ	SN:chr21	LN:48129895
@RG	ID:SRR203401	PL:ROADMAP	PU:DGF	LB:brain.SRR203401	SM:brain.SRR203401
############################
achimmiri@idash-cloud-707:/mnt/oncogxA/anusha/ReadGroup_Bam$ samtools view brain.SRR203401.RS.bam|head -15
SRR203401.10537348	16	chr1	9996	37	6M1I29M	*	0	0	TCCGATCTACCCTAACCCTAACCCTAACCCTAACCC	@<@?=?A?9AAB?@=@AB?B7BAC?B?BCB@C:BBB	X0:i:1	X1:i:0	MD:Z:6A28	RG:Z:SRR203401	XG:i:1	NM:i:2	XM:i:1	XN:i:5	XO:i:1	XT:A:U
SRR203401.10840330	16	chr1	9996	37	6M1I29M	*	0	0	TCCGATCTACCCTAACCCTAACCCTAACCCTAACCC	A@BAA=B<8>ABAB?B>B@B=BBCAB<??BBC@BBB	X0:i:1	X1:i:0	MD:Z:6A28	RG:Z:SRR203401	XG:i:1	NM:i:2	XM:i:1	XN:i:5	XO:i:1	XT:A:U
SRR203401.8026022	16	chr1	9997	25	36M	*	0	0	CCGATCTCCCTAACCCTAACCCTAACCCTAACCCTA	@BA@AB@B@B@B@BBBBBABCCAC?BBBBC@BCCAB	X0:i:1	X1:i:0	MD:Z:5A0A29	RG:Z:SRR203401	XG:i:0	NM:i:2	XM:i:2	XN:i:4	XO:i:0	XT:A:U
SRR203401.7201125	16	chr1	9999	25	36M	*	0	0	GATCTCCCTAACCCTAACCCTAACCCTAACCCTAAC	>=7A<@BA<A>BBA?A>BBB?@>BBBAB@BBB@BAB	X0:i:1	X1:i:0	MD:Z:3A0A31	RG:Z:SRR203401	XG:i:0	NM:i:2	XM:i:2	XN:i:2	XO:i:0	XT:A:U
SRR203401.8228359	16	chr1	9999	25	36M	*	0	0	GATCTCCCTAACCCTAACCCTAACCCTAACCCTAAC	4;?A=@BBAA?@@B@B:ABBBB>BBCAC?ABBAB@B	X0:i:1	X1:i:0	MD:Z:3A0A31	RG:Z:SRR203401	XG:i:0	NM:i:2	XM:i:2	XN:i:2	XO:i:0	XT:A:U
SRR203401.1392856	16	chr1	10002	0	36M	*	0	0	AACCCTAACCCTAACCCTAACCCTAACCCTAACCCT	A3ABBA<8BCBAB6BCBBC3ACBBA?BCCBCBCAA@	X0:i:629	MD:Z:36	RG:Z:SRR203401	XG:i:0	NM:i:0	XM:i:0	XO:i:0	XT:A:R
SRR203401.2060198	0	chr1	10003	0	36M	*	0	0	ACCCTAACCCTAACCCTAACCCTAACCCTAACCCTA	B@@BBBBB?BBBBAABBBB@AABBA?@@ABB:@@AB	X0:i:637	MD:Z:36	RG:Z:SRR203401	XG:i:0	NM:i:0	XM:i:0	XO:i:0	XT:A:R
SRR203401.8690266	0	chr1	10003	0	36M	*	0	0	ACCCTAACCCTAACCCTAACCCTAACCCTAACCCTA	B@BBCCCAA@B@@ABBBCCBBBBBB@BBAAB=<AAA	X0:i:637	MD:Z:36	RG:Z:SRR203401	XG:i:0	NM:i:0	XM:i:0	XO:i:0	XT:A:R
SRR203401.7330924	0	chr1	10004	0	36M	*	0	0	CCCTAACCCTAACCCTAACCCTAACCCTAACCCTAA	BCCCCCBBCCBCBABCCCABBBBB@BBBCBBBABBB	X0:i:635	MD:Z:36	RG:Z:SRR203401	XG:i:0	NM:i:0	XM:i:0	XO:i:0	XT:A:R
SRR203401.11245646	0	chr1	10004	0	36M	*	0	0	CCCTAACCCTAACCCTAACCCTAACCCTAACCCTAA	BABCBCBBCCCCBBBBCB@BBCBBB?BBBB?BBBBB	X0:i:635	MD:Z:36	RG:Z:SRR203401	XG:i:0	NM:i:0	XM:i:0	XO:i:0	XT:A:R
SRR203401.10665860	16	chr1	10005	0	36M	*	0	0	CCTAACCCTAACCCTAACCCTAACCCTAACCCTAAC	@A6?8?@A>A9AAA?A9@BA5@:BBA7A8AAB@B@B	X0:i:631	MD:Z:36	RG:Z:SRR203401	XG:i:0	NM:i:0	XM:i:0	XO:i:0	XT:A:R
SRR203401.14139690	16	chr1	10005	0	36M	*	0	0	CCTAACCCTAACCCTAACCCTAACCCTAACCCTAAC	B8<4(?8;=?9<A7:855>A@4+?A9>?-@?;B;>A	X0:i:631	MD:Z:36	RG:Z:SRR203401	XG:i:0	NM:i:0	XM:i:0	XO:i:0	XT:A:R
SRR203401.10553638	16	chr1	10006	0	36M	*	0	0	CTAACCCTAACCCTAACCCTAACCCTAACCCTAACC	B?@:BBB@A?BBC?B8BBCAB=CBB@B>BBCAC@BB	X0:i:637	MD:Z:36	RG:Z:SRR203401	XG:i:0	NM:i:0	XM:i:0	XO:i:0	XT:A:R
SRR203401.12582760	16	chr1	10006	0	36M	*	0	0	CTAACCCTAACCCTAACCCTAACCCTAACCCTAACC	C==:AAA8@:@A@8@=ABB@@:BBB=B8BBA@B=BB	X0:i:637	MD:Z:36	RG:Z:SRR203401	XG:i:0	NM:i:0	XM:i:0	XO:i:0	XT:A:R
SRR203401.4073983	0	chr1	10008	0	36M	*	0	0	AACCCTAACCCTAACCCTAACCCTAACCCTAACCCT	BBBBBBBBBBB@A?A@BBBBA?BAB@?@@9<=?@@@	X0:i:629	MD:Z:36	RG:Z:SRR203401	XG:i:0	NM:i:0	XM:i:0	XO:i:0	XT:A:R
achimmiri@idash-cl

**Comment by tk2** [comment]
Can you point us to a test file so we can re-test on the recent v1.3 release?
