### ISSUE TITLE
Multithreaded reading of BAM file

### ISSUE THREAD

**Issue by rob-p** [samtools/samtools#235]
Hi,
  I'm currently working on a feature in our RNA-seq quantification software, [Sailfish](https://github.com/kingsfordgroup/sailfish/tree/jellyfish2) to perform rapid abundance estimation from aligned reads should a user have them available.  The inference algorithm is pretty fast, and I discovered that on larger data sets, the big bottleneck ended up being the actual reading, decompression and parsing of the BAM file.  I searched around for an implementation of a multi-threaded BAM parser, and came across Nils' [fork of samtools](https://github.com/nh13/samtools), which seemed to reduce the bottleneck from BAM parsing substantially.

  Anyway, I've been using that code for a while, but ideally, I'd like to have our tool depend on the mainline branch of samtools instead of a fork that hasn't been updated in a while.  Is there any plan to incorporate any of the improvements from that fork into the official samtools repo?  A few message board threads suggested there was interest, but that was a year or so ago?  Is this something that is likely going to happen?  Is the functionality already there but hidden behind some type of non-standard compilation flag?  If I have to rely on the forked Samtools to get the fast BAM parsing, that's not a problem, but I figured I see what the official options are first.  

Thanks!
Rob

**Comment by rob-p** [comment]
Hi all (specifically, @jkbonfield),

  I was just curious how this is looking.  I've seen a number of changes here and in htslib that suggest multithreaded bam parsing / reading should be available soon.  Is this something that is likely to show up soon or not?  I've been using io_lib happily for quite a while.  However, I'd really be interested in using [seqlib](https://github.com/walaj/SeqLib) in my project, which would require me to switch over to htslib in the background, rather than io_lib.

Thanks,
Rob

**Comment by jkbonfield** [comment]
I forgot this issue still exists to be honest! Sorry about that - I'd have replied sooner.

Yes htslib now has multi-threaded reading at the core using a derivative of the thread pool from io_lib.  It's more complicated in htslib as the library supports much more than io_lib; specifically seeking within BAMs.   This is in the develop branch which should be making its way to an official 1.4 release "Real Soon Now".   We're waiting on a few final tweaks and someone to come back off holiday, but *hopefully* that'll be 1-2 weeks.

You can try it right now by checking out develop branches of htslib, samtools and bcftools.  (If there are bugs, we'd much rather they're found just before a release than just after!)

**Comment by valeriuo** [comment]
Available from [version 1.4](https://github.com/samtools/samtools/releases/tag/1.4) onwards.
