### ISSUE TITLE
samtools index on large chromosomes

### ISSUE THREAD

**Issue by mcshane** [samtools/samtools#241]
Possibly resurrecting old issues, but still problems with indexing and large chromosomes.
1. `samtools index large-chrom.bam` happily creates a bai file, even though index will not work for the large (>2^29) chromosome. Expect this should fail and give the suggestion of switching to .csi.
2. `samtools index -c large-chrom.bam` creates the .csi file as expected, however, `samtools view large-chrom.bam large-chrom` does not retrieve reads beyond ~2^29. Doing `samtools view large-chrom.bam large-chrom:from-to` works fine, so the .csi index is working, just the filling in to the chromosome end when no `from-to` specified is broken.

I'll try to put this in a test if I have time.

**Comment by jmarshall** [comment]
I believe item (2) is now fixed everywhere in htslib and samtools, but item (1) is likely still outstanding.

**Comment by daviesrob** [comment]
After samtools/htslib#470 trying to index `test/dat/large_chrom.sam` results in this:
```
$ ./samtools view -b test/dat/large_chrom.sam > /tmp/large_chrom.bam
$ ./samtools index /tmp/large_chrom.bam
[E::hts_idx_push] Region 536880910..536880925 cannot be stored in a bai index. Try using a csi index with min_shift = 14, n_lvls >= 6
samtools index: "/tmp/large_chrom.bam" is corrupted or unsorted
```
The error message from index needs to be fixed. There's nothing wrong with `large_chrom.bam`, it just can't be represented in a `.bai` index
