### ISSUE TITLE
samtools index returns 0 even on failure

### ISSUE THREAD

**Issue by mcshane** [samtools/samtools#247]
Looks like in `bam_index.c`, the return value of `bam_index_build` is not checked. So always returns 0 after trying to build the index.

**Comment by mdshw5** [comment]
I'm also running into this issue, and currently have to check the stderr from `samtools index` as the return code is always `0`.

**Comment by jmarshall** [comment]
Fixed by #362 and 9bbc79ec8d793705007e2141c8f9483b39a4b397.
