### ISSUE TITLE
mpileup defaults

### ISSUE THREAD

**Issue by mp15** [samtools/samtools#256]
Just a few quick user experience notes from recent testing.

By default mpileup produces a pileup file, which is the least likely option that a user might choose.

Also mpileup doesn't warn when no reference is supplied but bcftools by default filters all sites where reference = N.  Thus bcftools by default produces an empty VCF/BCF as output if used naively.

**Comment by mp15** [comment]
The pileup output vs VCF output part of this is due to be fixed as part of the migration of pileup to bcftools.

**Comment by jrandall** [comment]
@jenniferliddle will check this has been resolved after pileup migration is complete
