### ISSUE TITLE
sort outputs sam regardless of input

### ISSUE THREAD

**Issue by earonesty** [samtools/samtools#261]
cat my.sam | samtools-0.2 sort -f - out.bam
cat my.bam | samtools-0.2 sort -f - out.bam

Both output a SAM file, which is probably a bug.   

The sort program should a) check the file extension of the output file to get the output format right and b) rely on a command-line switch (-S, -B) if the -o option is present instead.   (I've taken to using 0.1.19 for the sort command, and 0.2 for the view command since it autodetects input)

**Comment by jmarshall** [comment]
The outputting-SAM thing is long since fixed, and since 1.0 the output format is determined by the output filename extension or an **-O** option.
