### ISSUE TITLE
System endiannes and unaligned memory access issues on mips

### ISSUE THREAD

**Issue by azlicic** [samtools/samtools#268]
Hello,
package python-pysam (samtools is a dependency of python-pysam) fails
to build on Debian for mips/mipsel architectures.

During tests in python-pysam output of samtools executable is used as a
reference (its output is compared with output from pysam python module),
but samtools has both unaligned memory access and system endianness issues.

I have already reported a bug on Debian bug tracking system at:
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=753485
with proposed patches attached.

Current version of samtools on Debian is 0.1.19-1.

I am currently adapting the patch to fit the latest samtools version.
I will send you a pull request as soon as I'm done.

Best Regards
Aleksandar Zlicic

**Comment by daviesrob** [comment]
HTSlib should now work on both little- and big-endian platforms.
