### ISSUE TITLE
Makefile adjustment for dynamic linking

### ISSUE THREAD

**Issue by charles-plessy** [samtools/samtools#275]
Hello,

I am preparing Debian packages for samtools, where I pass `HTSDIR="/usr/include"` and `LDLIBS="-lhts"` to link samtools to the system-installed htslib.  However, the Makefile unconditionally includes $(HTSDIR)/htslib.mk, which makes necessary to have a full clone of the htslib side-to-side with the samtools clone.

How about the following patch, which makes the include optional ?

```
diff --git a/Makefile b/Makefile
index e110b31..5ea3dc8 100644
--- a/Makefile
+++ b/Makefile
@@ -82,7 +82,7 @@ all: $(PROGRAMS) $(BUILT_MISC_PROGRAMS) $(BUILT_TEST_PROGRAMS)
 
 # Adjust $(HTSDIR) to point to your top-level htslib directory
 HTSDIR = ../htslib
-include $(HTSDIR)/htslib.mk
+-include $(HTSDIR)/htslib.mk
 HTSLIB = $(HTSDIR)/libhts.a
 BGZIP  = $(HTSDIR)/bgzip
```

Have a nice day,

-- 
Charles Plessy
Debian Med packaging team
http://www.debian.org/devel/debian-med
Tsurumi, Kanagawa, Japan

**Comment by jmarshall** [comment]
Samtools now has a configure script; the incantation you want is `--with-htslib=system`.  (There are a few documentation and other additions yet to come.)
