### ISSUE TITLE
samtools mpileup -d <depth> doesn't work

### ISSUE THREAD

**Issue by ghuls** [samtools/samtools#29]
When looking at the help of the mpileup subcommand:
```
$ /software/samtools/samtools-git/samtools mpileup

Usage: samtools mpileup [options] in1.bam [in2.bam [...]]

Input options:

       -6           assume the quality is in the Illumina-1.3+ encoding
       -A           count anomalous read pairs
       -B           disable BAQ computation
       -b FILE      list of input BAM files [null]
       -C INT       parameter for adjusting mapQ; 0 to disable [0]
       -d INT       max per-BAM depth to avoid excessive memory usage [250]
...
```
it says that the default value is 250.

When you run samtools mpileup, you get something like this:
```
$ /software/samtools/samtools-git/samtools mpileup -q 0 -Q 0 -r chr17:80887038-80887038 -f Homo_sapiens_assembly19_sorted.fasta test.bam
[mpileup] 1 samples in 1 input files
<mpileup> Set max per-file depth to 8000
chr17	80887038	G	202	><<.$A$a$a$AA,aA...AA,aa,AaaaaA.A.aa,a,aaaaaaaaA,aaA.,AA,AAaaa,aA.aaa..AaAA.Aaaaa,aa,aAA.A,aa,a,,aAaa,aaaA.aaa.aaaa,aaAa,aa.,aa.,a,,aAa,A,,a,,aAAa,,,,aa.AAAaaaaaaaA.aaaaaaaaAA,Aaaaaa,aa,,.aa,A.A..,.aaa,aAa^SA	IBF#:C@@#BCCA#:CAB@CC:=D:D#>:DCHAHHDHHFHH?D>FHHC<+@AICDH@)CGD:IGH>DD=CACDDDFD;FFB5CCCEDDBDFFEFFA@CCD?F7;BB)DBDB?BDJ<???#8@DG?<@@@I@?G@B@8B8EID@28?5?GG?IDB2?<8?JI??0<D#DDJI)IB8?202(?@BC#?2GHHBF#3B8@#BA8#
```
It uses 8000 instead of 250 as depth.

Settting the depth manually, doesn't change the 8000 value:
```
$ /software/samtools/samtools-git/samtools mpileup -d 5 -q 0 -Q 0 -r chr17:80887038-80887038 -f Homo_sapiens_assembly19_sorted.fasta test.bam
[mpileup] 1 samples in 1 input files
<mpileup> Set max per-file depth to 8000
chr17	80887038	G	202	><<.$A$a$a$AA,aA...AA,aa,AaaaaA.A.aa,a,aaaaaaaaA,aaA.,AA,AAaaa,aA.aaa..AaAA.Aaaaa,aa,aAA.A,aa,a,,aAaa,aaaA.aaa.aaaa,aaAa,aa.,aa.,a,,aAa,A,,a,,aAAa,,,,aa.AAAaaaaaaaA.aaaaaaaaAA,Aaaaaa,aa,,.aa,A.A..,.aaa,aAa^SA	IBF#:C@@#BCCA#:CAB@CC:=D:D#>:DCHAHHDHHFHH?D>FHHC<+@AICDH@)CGD:IGH>DD=CACDDDFD;FFB5CCCEDDBDFFEFFA@CCD?F7;BB)DBDB?BDJ<???#8@DG?<@@@I@?G@B@8B8EID@28?5?GG?IDB2?<8?JI??0<D#DDJI)IB8?202(?@BC#?2GHHBF#3B8@#BA8#
```

**Comment by nhayden** [comment]
:+1:

As hinted at earlier comments it seems max_depth is playing two roles:
- capping num reads per BAM file (not advertised)
- capping depth per position (advertised)

But the `-d, --max-depth` argument only seems to be used for the unadvertised behavior. And then, only if `max_depth * num files > 8000`, which it seems should be documented in the man page in addition to emitting the warning (as well as the stated default updated).

See samtools/htslib#243

**Comment by jkbonfield** [comment]
I've started looking at this and it's just bizarre.

max_depth is raised to 8000/n (where n is number of BAM files) if it's smaller.  I can't see why this happens, especially given the default of 250.  What's the point of it?

Conversely max_indel_depth is multiplied by n and has 8000 increase anywhere.  Why is it different?

The documentation states that -d (max_depth) is per-BAM (it is not, it is downscaled by the number of BAMs so therefore is total depth) while -L (max_indel_depth) is per-SAMPLE (it is not, it is per BAM.  One BAM with 10 samples is not multiplied by 10, but 10 BAMS using the same sample are).

I could fix the documentation, which is probably the safest thing, but it'll be a bit bizarre. I'm not sure what the impact is of fixing the options to be sane though as I don't understand all the nuances as to why it was coded this way.  @lh3 ?

**Comment by jkbonfield** [comment]
PR #525 documents how these work, but I don't know if that is sufficient.  Assuming as such until we hear otherwise.

**Comment by qins** [comment]
One of the most popular bioinfo softwares has such bug or ERROR.
I saw many discussions, and no REAL answer
