### ISSUE TITLE
rmdup: Samtools-htslib-API: bam_get_library() not yet implemented

### ISSUE THREAD

**Issue by zeeev** [samtools/samtools#291]
Program: samtools (Tools for alignments in the SAM format)
Version: 1.0 (using htslib 1.0)

I've used 1.0 sam->bam->sort->rmdup

rmdup isn't working?  Sorry if this a duplicate?

Is there a stable version?

**Comment by fabioticconi** [comment]
Hi,

looks like the gentoo-sci guys have implemented this function for 1.0, 1.1 and 1.2.

https://github.com/gentoo-science/sci/commit/9de36f0052f04b80223de81c59c9125a5e95fef5#diff-8775b99c8f043225fe82af88af6aa5ba

Could this patch be evaluated and included if sound?

**Comment by fabioticconi** [comment]
Actually, scratch that. I see that the pull request was refused: https://github.com/samtools/samtools/pull/368

**Comment by jmarshall** [comment]
This was fixed by the commit above (PR #461, in particular 13de48f8dd6bcd71277128143fadc9ab3aa50576); an `rmdup` command that works as well as it ever did will reappear in the upcoming 1.3 release.

**Comment by zeeev** [comment]
:+1:
