### ISSUE TITLE
samtools sort documentation misleading regarding -O and -T options

### ISSUE THREAD

**Issue by jrandall** [samtools/samtools#295]
When I give `samtools sort` the `-O bam` option, it exits with error, saying: "[bam_sort] no prefix specified for temporary files (use -T option)".

However, the usage information indicates that "either -O or -T is required" - that doesn't seem right as `-T` seems to be required no matter what? (https://github.com/samtools/samtools/blob/develop/bam_sort.c#L1097)

Cheers,

Josh.

**Comment by plijnzaad** [comment]
I concur, ran into the same problem (samtools 1.2, htslib 1.21), has this been fixed yet? 

(The -T requirement seems unnesssary since samtools could always invent its own prefix based on $TMPDIR or somesuch).

**Comment by jmarshall** [comment]
Fixed by removing the legacy `<out.prefix>` invocation style; this removal enables `-T` to be optional.
