### ISSUE TITLE
view is producing sam when extension is .bam for output file

### ISSUE THREAD

**Issue by mp15** [samtools/samtools#296]
samtools branch based on: b67461fa100824e378f9f319036910f322e20482
htslib: e770a1b390bc72ba467831a67ffb2d4e1c2091f4
~/dev/samtools/samtools view -s .643780772666927 -o 13350_1_5x_2.bam 13350_1_rg.bam
expected 13350_1_5x_2.bam to be a BAM not the SAM that was actually produced

**Comment by daviesrob** [comment]
Closing as suffixes have been used to choose the output format for a while.
