### ISSUE TITLE
sam vs bam vs tam vs ARGH

### ISSUE THREAD

**Issue by jkbonfield** [samtools/samtools#297]
If I look at this longer I think I'll cry!

Attempting to understand how to convert samtools flagstat to handle sam, bam or cram instead of bam only, I have drifted into the murky world of #defines, typedefs and oddly named functions.

Can we please sanitise this? Eg sam_view.c has this (with bits removed inbetween for brevity):

    bam_hdr_t *h; 
    ...
    h = sam_hdr_read(fp);
    ...
    bam_hdr_destroy(h);

Reading with sam_hdr and destroying with bam_hdr is confusing.  I thought that maybe we had both sam_hdr_read and bam_hdr_read as aliases to each other, but no, they're totally different:

     htslib/sam.h:    bam_hdr_t *bam_hdr_read(BGZF *fp);
     htslib/sam.h:    bam_hdr_t *sam_hdr_read(samFile *fp);

Permission to rock gently back and forth on my chair?

**Comment by jmarshall** [comment]
Revisit this after header API has fixed it up a little bit… (#481).

**Comment by jkbonfield** [comment]
Also see samtools/htslib#297, which is really where the problem lies (htslib, not samtools).

**Comment by jkbonfield** [comment]
Infact, closing as duplicate - it doesn't belong as samtools issue and is tracked elsewhere.
