### ISSUE TITLE
Samtools SNP calling

### ISSUE THREAD

**Issue by Sung-Huan** [samtools/samtools#298]
Dear all,
I would like to use samtools to call SNP. I use the latest version 1.0. 
First, I have to generate bcf file. 
I run the following command.

samtools mpileup -t DP -ugf my.fasta my.bam

the result is always like this:

[mpileup] 1 samples in 1 input files
<mpileup> Set max per-file depth to 8000
Aborted

If I just run

samtools mpileup -f my.fasta my.bam

it works fine.
I have no idea what happens.
If I go back to use samtools-0.1.19 to run

samtools mpileup -uD -f my.fasta my.bam

everything is okay.
Could anyone helps me? Thank you.

I also parsed the BAM file to short one. I found when the line comes to 88, it will aborted. Before line 88, everythin is fine. But I checked the file, I didn't see anything wrong. I can send the short BAM file to you if you can help me. Thanks a lot.

Sung-Huan

**Comment by tk2** [comment]
Can you provide a test file please so we can re-test on v1.3 release of Samtools?
