### ISSUE TITLE
samtools idxstats produces incorrect values for cram

### ISSUE THREAD

**Issue by ctsa** [samtools/samtools#303]
(copying here from samtools-help) I’ve come across one issue working with cram files in the samtools 1.x release, which is that idxstats will run on cram files, but doesn’t actually provide read counts.

This can be reproduced on master (b7c4b4d05154887ec8587165c6da505aad024f52) :

```
# from samtools directory:
$ samtools idxstats test/mpileup/ce#5b.bam
CHROMOSOME_I    15072423        1       0
CHROMOSOME_II   15279345        1       0
CHROMOSOME_III  13783700        1       0
CHROMOSOME_IV   17493793        1       0
CHROMOSOME_V    20924149        3       0
*       0       0       0
$ samtools idxstats test/mpileup/ce#5b.cram
CHROMOSOME_I    15072423        0       0
CHROMOSOME_II   15279345        0       0
CHROMOSOME_III  13783700        0       0
CHROMOSOME_IV   17493793        0       0
CHROMOSOME_V    20924149        0       0
*       0       0       139886584375224
```

**Comment by mp15** [comment]
Reproduced on current 1.3 develop

```
$ ./samtools idxstats test/mpileup/ce#5b.bam
CHROMOSOME_I	15072423	1	0
CHROMOSOME_II	15279345	1	0
CHROMOSOME_III	13783700	1	0
CHROMOSOME_IV	17493793	1	0
CHROMOSOME_V	20924149	3	0
*	0	0	0
$ ./samtools idxstats test/mpileup/ce#5b.cram
CHROMOSOME_I	15072423	0	0
CHROMOSOME_II	15279345	0	0
CHROMOSOME_III	13783700	0	0
CHROMOSOME_IV	17493793	0	0
CHROMOSOME_V	20924149	0	0
*	0	0	748549960834809858
```

That last number looks weird, it may be uninitialised.

**Comment by jkbonfield** [comment]
One question - what do we actually want to happen?

Some of the output is impossible to generate for CRAM due to the index holding different information.  Eg it cannot count the number of aligned and unaligned reads.  This makes idxstats potentially rather useless.

Should it simply not work on cram?

**Comment by jmarshall** [comment]
Compare `hts_idx_get_n_no_coor()` with its partner in crime, `hts_idx_get_stat()`.

It should return 0.

Or perhaps it should return -1 (modulo signed v. unsigned, sigh), which would give idxstats an opportunity to print `N/A` or similar.  It currently has this opportunity with `hts_idx_get_stat()` but doesn't take advantage of it...

**Comment by kyleabeauchamp** [comment]
I wanted to ping this issue, which I just encountered.  

Is it unreasonable to use a slow code path that just walks over the entries in the CRAM and counts the reference names?

**Comment by kyleabeauchamp** [comment]
If we can't make the tool replicate the behavior of BAMs, then I almost think it should raise an exception and exit.  The current behavior silently gives corrupted results.

**Comment by jkbonfield** [comment]
This is a fair comment.  Right now it's just broken - we either need to return an error code (easy) or trawl through the entire file computing stats in a slow manner (more work, and maybe not what users want).  Although counting reads in CRAM is *usually* quite quick - much more so than it would be in BAM as the data is in the container headers (normally).  Ie it would be comparable to the time taken to build a cram index.

Obviously the ideal scenario would be a revised cram index format, but that's a spec issue and not likely to happen unless we have other reasons for releasing a new CRAM format.

**Comment by dpryan79** [comment]
Maybe create a function in htslib to handle this then? In deepTools I have to iterate over the reads via pysam to get this information, which takes a bit of time. If one can create a function to just iterate over the headers then that could be exposed in pysam so many of us won't need to roll our own slower implementations.

**Comment by jkbonfield** [comment]
Where it gets complex is containers with multiple references in them.  The container header has ref id, start, end (end-start actually), and number of records.  This all looks great, but ref id can be -2 to imply mixed references are present.  At this stage the records then use an RI data series instead to state which reference they are on.

We can still do better than decoding the entire read though, as we can analyse the compression header and if RI is in a block by itself (the norm for modern CRAMs) then we can decompress that one single block in isolation to get counts per slice per container.  Otherwise the full read needs decoding instead.  It's doable and I swear I even did this somewhere or other, but I'm struggling at present to see a general purpose API unless it is for this very single specific feature.

**Comment by jkbonfield** [comment]
Good point on mapped and unmapped together.  Bah.

Hmm, maybe this is something for optimisation using required_fields parameter.  Do you already use this from python?  In theory if we set *only* required_fields to 0x6 (FLAG|RNAME) then we could have an iterator that does little more than generate N empty records with the same 'tid' without ever decoding anything but the flag block.  The required_fields parameter already has all the optimisations to skip work, but if flag is mixed in with other fields then it'll do the right thing and decode more.

Right now I'm not sure how much work it'll do, but it's a pretty good starting point.  It's pretty nippy - this is just counting records, but they contain both flag and tid fields populated:

```
perf stat samtools view -c --input-fmt-option required_fields=6 ~/scratch/data/9827_2#49.cram
56463236

 Performance counter stats for 'samtools view -c --input-fmt-option required_fields=6 /nfs/users/nfs_j/jkb/scratch/data/9827_2#49.cram':

      16371.725528 task-clock                #    0.999 CPUs utilized          
                29 context-switches          #    0.000 M/sec                  
                 2 CPU-migrations            #    0.000 M/sec                  
           3972772 page-faults               #    0.243 M/sec                  
       48892386488 cycles                    #    2.986 GHz                     [83.34%]
       22642500227 stalled-cycles-frontend   #   46.31% frontend cycles idle    [83.34%]
       10309868646 stalled-cycles-backend    #   21.09% backend  cycles idle    [66.67%]
       73845219176 instructions              #    1.51  insns per cycle        
                                             #    0.31  stalled cycles per insn [83.34%]
       11093871771 branches                  #  677.624 M/sec                   [83.33%]
          62839998 branch-misses             #    0.57% of all branches         [83.32%]

      16.395479195 seconds time elapsed
```

So around 3.4 million records per second.  Run on a BAM file the same operation decodes around 550k records per second.

It's not as quick as a single index lookup, but maybe this is sufficient for now.

**Comment by dpryan79** [comment]
Yes, I already use the `required_fields` in python, though not optimally for this purpose (I additional fields since I reuse the function). Inevitably things become much faster if they can get pushed to C, though (the python overhead really kills performance).
