### ISSUE TITLE
bam_prob_realn_core() corrupts records without base qualities

### ISSUE THREAD

**Issue by jmarshall** [samtools/samtools#320]
When called on a record that has no base qualities (i.e., QUAL = `*`), `bam_prob_realn_core()` appends a ZQ or BQ field with contents that are hopelessly out of range.  For these records `bam1_qual()` returns an array of 0xFF, which on recalculation produces a ZQ/BQ string containing non-printable characters, in particular '\0' NUL characters.  These are later mistaken for BAM tagged field separators, leading to the observed crash in `skip_aux()`.

There are two problems here that may both need fixing:

1. The ZQ or BQ field is written without any checking that its contents are within range; perhaps even for valid QUAL data the recalculated values could be outside the valid Z-field range.

2. When QUAL is missing, recalculating ZQ/BQ from it is probably meaningless.  So probably `bam_prob_realn_core()` should do nothing for reads without QUAL.

    (In fact, perhaps `if (...b->core.l_qseq == 0) ...do nothing` at the top of the function is intended to do this -- so fixing this test would suffice.)

Reproducible via `mpileup -f ref.fa`; originally [reported by Nick Loman on samtools-help](http://sourceforge.net/p/samtools/mailman/message/32990669/) who provides test data:

    samtools mpileup -Q 0 -f NC_000913.fna -g Ecoli_R73_2D.bam

**Comment by jmarshall** [comment]
Encountered again [here](https://www.biostars.org/p/132723/).  It seems data without QUAL is becoming more common...

**Comment by dpryan79** [comment]
Wouldn't the simplest change simply be to convert the `b->core.l_qseq == 0` test to `b->core.l_qseq == 0 || qual[0] == (uint8_t) -1`? Doing that fixes the issue on the example from biostars and shouldn't cause any side effects.

**Comment by jmarshall** [comment]
Well, yes -- see parenthesised second paragraph of (2) in the original report.  I don't think @pd3 has time to look at this code in detail at the moment, but I had been hoping he would be able to comment on this issue.

**Comment by pd3** [comment]
Skipping these reads from realignment will fix the core dump issue, but I don't know if it's an optimal solution: another possibility is to assume a constant quality for all bases so that the realignment can still be performed. I am unable to tell without more work whether it's worth it (my guess is yes) and if so, what default value is best to use. @lh3 is more competent to comment.

**Comment by jkbonfield** [comment]
Given the lack of any response on a better solution, I'll be applying the trivial fix discussed above so we can avoid the core dumps for the 1.3 release.

If anyone thinks of a better solution then we can amend it later.
