### ISSUE TITLE
Feature request: mpileup rename samples (@RG SM:) on fly

### ISSUE THREAD

**Issue by travc** [samtools/samtools#324]
It would be quite nice if we could have mpileup rename samples on the fly instead of having to make a new bam file with a different SM: tag.  I imagine providing a file which simply lists the old and new sample names.  Samples which don't appear in that file just keep their name from the SM tag unchanged.

The use case:  We've got sequences from different tissues (and/or prep protocols) which make sense to keep as separate samples for some studies, but should be combined (as a single sample) for others.  It seems wrong to have to keep two (or more) copies of the bam files which only vary by SM tag.

PS: Perhaps there is an elegant work-around I haven't thought of.
Streaming the output of reheader isn't an option in this case, since we're sending multiple files into mpileup.

**Comment by mp15** [comment]
Being able to do this on the fly with a remapping file like GATK is desirable. For the next release of samtools we're looking at redoing the header API so we shall revisit this.

**Comment by jmarshall** [comment]
Contingent on a header API (#481).

**Comment by mpschr** [comment]
This would improve the performance for some task drastically!

**Comment by daviesrob** [comment]
Closing as bcftools can now do this.
