### ISSUE TITLE
Samtools view withmultiple flag filtering

### ISSUE THREAD

**Issue by Dronte** [samtools/samtools#326]
I am trying to use samtools view with -F flag to filter some alignments.  The naive way i used was:

samtools view -F 4 -F 16 something.bam

This works exactly as samtools view -F 4 something.bam

wheres the right commadline is

samtools view -F 20 something.bam

But I'd like to get an error or a warning on the first call. I'd save me a couple of hours - and probably to someone else too.

**Comment by jmarshall** [comment]
Believe this is fixed by later addition of `|=`.
