### ISSUE TITLE
index segfault

### ISSUE THREAD

**Issue by sb10** [samtools/samtools#341]
I'm getting a segfault during samtools index with samtools 1.1 (using htslib 1.1), but not with 0.1.19-96b5f2294a.

$ cd /lustre/scratch107/user/sb10/samtools
$ samtools index index_segfault.bam
Segmentation fault
$ /software/vertres/bin-external/samtools-0.1.19-tagged_release/samtools index index_segfault.bam
[works fine]

**Comment by pd3** [comment]
I believe this should fix it, let me know if not

**Comment by jmarshall** [comment]
The problem is this record:

    HS20_07369:5:1202:14911:32945#30        141     *       0       37      89M1I10M        *       0       0       TGAAA[snip]

It's unmapped according to its flags, but has MAPQ and CIGAR nonetheless (due presumably to the usual bwa reasons?).

**Comment by sb10** [comment]
Latest version 1.1-40-ge2ce81d (using htslib 1.1-143-gb16799b) fixes it for me, thanks Petr
