### ISSUE TITLE
Curses library fails for Suse and Fedora distros. Quick fix possible

### ISSUE THREAD

**Issue by luiceur** [samtools/samtools#346]
On Suse and Fedora, the brew installation of samtools will fail since the Makefile calls `-lcurses` instead to `-lncurses`. A call to `-lncurses` will work for all Linux distributions

**Comment by wookietreiber** [comment]
That's why some distros, like Arch Linux, for the sake of compatibility just symlink /usr/lib/libcurses.so -> libncurses.so (IIRC maybe some other hacks necessary, see [PKGBUILD](https://projects.archlinux.org/svntogit/packages.git/tree/trunk/PKGBUILD?h=packages/ncurses)). Still, you need to be aware of that even though -lncurses will work with most current Linux distros, it is still not fully compatible / portable.

An autoconf configure should be able to detect which one to use. Wasn't this in the works for samtools?

**Comment by luiceur** [comment]
Brew install downloads the package from the main repository and runs the `Makefile`. Although we have the curses library installed, samtools fails because it cannot find `-lcurses`. We could try to symlink `libncurses.so` to `libcurses.so` and see if that bypasses the installation.

**Comment by luiceur** [comment]
Well, I got much further in the compilation process but still fails
```
gcc -g -Wall -O2 -D_FILE_OFFSET_BITS=64 -D_LARGEFILE64_SOURCE -D_CURSES_LIB=1 -I. -I/home/U008/lcebaman/EdGen/bcbio/opt/htslib/include -c -o test/merge/test_trans_tbl_init.o test/merge/test_trans_tbl_init.c
/usr/lib64/gcc/x86_64-suse-linux/4.3/../../../../x86_64-suse-linux/bin/ld: cannot find -lcurses
```

**Comment by wookietreiber** [comment]
I think you'd be better of if you'd work with the [`LIBCURSES` setting from Makefile](https://github.com/samtools/samtools/blob/1.2/Makefile#L40).

**Comment by luiceur** [comment]
I can easily change `LIBCURSES` from the Makefile. The difficulty comes when I call `brew install`. Either downloads the package directly from the main repo or if I force it to install my "modified" `Makefile` package, `brew` detects that the package has been modified and it does not allow me to install it:
```
brew install --force samtools
==> Installing samtools from homebrew/homebrew-science
==> Downloading https://github.com/samtools/samtools/archive/1.1.tar.gz
Already downloaded: /home/U008/lcebaman/.cache/Homebrew/samtools-1.1.tar.gz
Error: SHA1 mismatch
Expected: ca446ec24eabd2f71605dde55a787f182cb50f13
Actual: 9a1c7c8da524719fa3e2219c6cc3ca10e30281ac
Archive: /home/U008/lcebaman/.cache/Homebrew/samtools-1.1.tar.gz
To retry an incomplete download, remove the file above.
```
Any ideas here?

**Comment by wookietreiber** [comment]
Try working with environment variables. `make -e` (at least GNU make) means precedence for environment variables to settings in `Makefile`:

```
$ export LIBCURSES=-lncurses
$ export MAKEFLAGS="-e"
$ brew install samtools
```

brew should pick these environment variables up to be passed along to the subprocesses, including make (as long as brew doesn't start some magic build environment, uses a special build user, etc. I know to few about brew, but you can try and share your experience).

**Comment by luiceur** [comment]
I thought I had a good chance setting those env variables but unfortunately it keeps failing. It does not seem to pick the value of `LIBCURSES` since it keeps looking for `lcurses`, however:
`$echo $LIBCURSES` returns `-lncurses`

**Comment by luiceur** [comment]
I got it installed. Here is what I did:
1- Unzip the package (`tar xzvf samtools.1.1tar.gz`)
2 - Modify the Makefile (`LIBCURSES=-lncurses`)
3- Zip it back (tar cvf samtools.1.1tar.gz samtools.1.1` )
4 - `brew install samtools` to get the actual SHA1 value
4 -Edit  the brew formula (`$brew edit samtools`) with the new SHA1 value
