### ISSUE TITLE
How to use bam_get_tid?

### ISSUE THREAD

**Issue by lamortenera** [samtools/samtools#347]
Dear all,
I have the same problem as the one in this issue:
http://sourceforge.net/p/samtools/mailman/message/30597102/

This is a 2 years old issue, so maybe time has changed and the htslib provides this functionality, but I am limited to use a standalone version of samtools (in particular version 0.18).

Is there a clean way of initializing the header hash? or some other way of getting the id from a chromosome name?

Thanks a lot!
Alessandro

**Comment by jmarshall** [comment]
This will be tidied up by a header API (#481) for htslib.  For the old 0.1.18 API, I'm afraid there are no further clean ways.
