### ISSUE TITLE
samtools sort -o should not require a filename

### ISSUE THREAD

**Issue by ekg** [samtools/samtools#356]
I'd like to use `samtools sort -o -` in a pipeline, but I have to specify a dummy filename as in `samtools sort -o - x` in order for it not to break.

I think the `-o` flag should remove the need for a file name.

**Comment by ekg** [comment]
I think I see what's happening. It needs the name in order to specify temporary files. A smarter way would require more code.

**Comment by jmarshall** [comment]
Which samtools are you using?  In samtools 1.x, this is... more complicated.  In a pipeline in samtools 1.x, you can say

    ... | samtools sort -Obam -Ttmpprefix - | ...

which is supposed to be easier, and eventually at least one of -O and -T may be able to go away (but see also #295 and #349; currently they're both required it seems).

**Comment by ekg** [comment]
@jmarshall I'm using 0.1.19-44428cd.

**Comment by jmarshall** [comment]
The legacy `<out.prefix>` invocation style has now been removed on **develop**.  If you move to current samtools, I think you'll find the `sort` command's options more tasteful than those of 0.1.19.
