### ISSUE TITLE
samtools rmdup and inconsistent BAM file for pair message 

### ISSUE THREAD

**Issue by jjfarrell** [samtools/samtools#359]
Samtools rmdup generates the following error message when processing a bam file generated with bwa mem:

inconsistent BAM file for pair  ''HWI-D00536:42:C59KFACXX:1:2306:17181:9216'" Continue anyway.

This error message is triggered when for a read that appears multiple times in the bam file.

However, having a read multiple times is now permitted with bwa mem according to bwa mem documentation.....

Why does a read appear multiple times in the output SAM?

BWA-SW and BWA-MEM perform local alignments. If there is a translocation, a gene fusion or a long deletion, a read bridging the break point may have two hits, occupying two lines in the SAM output. With the default setting of BWA-MEM, one and only one line is primary and is soft clipped; other lines are tagged with 0x800 SAM flag (supplementary alignment) and are hard clipped.

It looks like the flag should be checked for 0x800 SAM flag before generating this error message....

**Comment by BIGgaoyf** [comment]
Hi, I have this problem,too.Do you have solved it?

**Comment by davidui** [comment]
I'm using another aligner, but i have the same problem. It seems that those reads are written in the final bam, so simpley are skipped in the removal process therefore not looks like will have big consequences, but i 'm not sure completly. Anybody know the reasons, solution or complications of this behaviour? 
Thanks in advance.

**Comment by kirkmcclure** [comment]
rmdup with no option (neither -s nor -S) expects alignment pairs with alternating +/- TLEN values. It is a special-purpose tool for removing PCR duplicates which conform to that pattern.

The warning is issued for consecutive positive TLEN values. A simple contrived example:
````
cat rmdupExample.sam
@SQ	SN:c2	LN:9
s1	67	c2	1	0	9M	=	1	30	CTAATAATC	XXXXXXXXX	RG:Z:1st
s1	67	c2	1	0	9M	=	1	-30	CTAATAATC	XXXXXXXXX	RG:Z:1st
s1	259	c2	1	0	9M	=	1	30	CTAATAATC	YXXXXXXXX	RG:Z:2nd
s1	131	c2	1	0	9M	=	1	30	CTAATAATC	XXXXXXXXX	RG:Z:3rd
s1	131	c2	1	0	9M	=	1	-30	CTAATAATC	XXXXXXXXX	RG:Z:3rd

./samtools view -b -o /tmp/rmdupExample.bam /tmp/rmdupExample.sam
../samtools-0.1.19/samtools rmdup /tmp/rmdupExample.bam /tmp/test_input_1_rmdup.bam
[bam_rmdup_core] processing reference c2...
[bam_rmdup_core] inconsistent BAM file for pair 's1'. Continue anyway.
[bam_rmdup_core] 2 / 3 = 0.6667 in library '	'
./samtools view /tmp/test_input_1_rmdup.bam
s1	67	c2	1	0	9M	=	1	-30	CTAATAATC	XXXXXXXXX	RG:Z:1st
s1	259	c2	1	0	9M	=	1	30	CTAATAATC	YXXXXXXXX	RG:Z:2nd
````

**Comment by whitwham** [comment]
Closing as rmdup is deprecated.
