### ISSUE TITLE
`samtools index` silently fails to detect corrupted BAM files and `samtools view` reports them as truncated rather than corrupted

### ISSUE THREAD

**Issue by jrandall** [samtools/samtools#362]
We have for a long time been teaching users that running `samtools index` on a bam file is good way to verify that a BAM file is not truncated (in addition to usefully generating the index). 

I have recently discovered a truncated BAM file which `samtools index` on 0.1.19 catches as possibly truncated, but for which samtools versions 1.0, 1.1, and 1.2 give no warnings (although `samtools view` does give a warning: `[main_samview] truncated file.` as does `samtools flagstat`: `[bam_flagstat_core] Truncated file? Continue anyway.`). 

I am working on preparing a minimal example that displays this behaviour, but so far I haven't figured out in which way this file is truncated such that it isn't caught by `samtools index` (as it does catch most truncated files). 

One hint may be the error this particular truncated file gives from Picard/GATK (from htsjdk): 
```
htsjdk.samtools.SAMFormatException: Did not inflate expected amount
        at htsjdk.samtools.util.BlockGunzipper.unzipBlock(BlockGunzipper.java:98)
```

**Comment by jrandall** [comment]
Ok, after some digging I've managed to contrive a test bam that exhibits this behaviour. 

In fact, the file that causes this issue is technically not *truncated* (despite what `samtools view` assertively says) but *corrupted*. See below for a use case (based on data in the mpileup test dir: https://github.com/samtools/samtools/blob/develop/test/mpileup/ce%23large_seq.bam) that demonstrates this issue. 

I think there are two separate issues here:
- the misreporting of the nature of the problem when processing a corrupted file by `main_samview` - stating that the file is truncated when in fact the EOF block is intact and the actual problem has to do with a failure to successfully decompress an internal BGZF block. 
- the failure for `samtools index` to report any issues when a BGZF decompression error causes it to fail to completely process the BAM file.

```bash
$ cp ce#large_seq.bam test_corrupted.bam
$ md5sum test_corrupted.bam
bc6b0096f76e42675bec983c0c7d48ca  test_corrupted.bam
$ echo "corruption" | dd of=test_corrupted.bam bs=1 count=10 seek=150000 conv=notrunc
10+0 records in
10+0 records out
10 bytes (10 B) copied, 0.000480286 s, 20.8 kB/s
$ md5sum test_corrupted.bam
c185d46b4682750307ef26e28b5a5ad3  test_corrupted.bam
$ samtools --version
samtools 1.2
Using htslib 1.2.1
Copyright (C) 2015 Genome Research Ltd.
$ samtools view test_corrupted.bam > test_corrupted.sam
[main_samview] truncated file.
$ samtools index test_corrupted.bam
$ samtools index ce#large_seq.bam
$ stat -c "%s %n" *.bai
608 ce#large_seq.bam.bai
584 test_corrupted.bam.bai
$ samtools-0.1.19 index test_corrupted.bam
[bam_index_core] truncated file? Continue anyway. (-4)
$ od -t x1 -j $[$(stat --printf="%s" test_corrupted.bam)-28] test_corrupted.bam
1242307 1f 8b 08 04 00 00 00 00 00 ff 06 00 42 43 02 00
1242327 1b 00 03 00 00 00 00 00 00 00 00 00
1242343
$ zcat test_corrupted.bam > /dev/null

gzip: test_corrupted.bam: invalid compressed data--crc error

gzip: test_corrupted.bam: invalid compressed data--length error
```

**Comment by marcelm** [comment]
Here is another way to create a corupt BAM file:
```
echo hello > hello.bam
samtools index hello.bam
```
No failure is reported and the exit code is 0.

**Comment by jmarshall** [comment]
With 9bbc79ec8d793705007e2141c8f9483b39a4b397, files without EOF blocks produce a warning, and even-more-truncated (truncated.bam) or grossly corrupt files produce an error message, no BAI file, and a failed exit status:

$ samtools index seq.bam || echo FAILED
$ samtools index noeof.bam || echo FAILED
[W::bam_hdr_read] EOF marker is absent. The input is probably truncated.
$ samtools index truncated.bam || echo FAILED
[W::bam_hdr_read] EOF marker is absent. The input is probably truncated.
[bam_index] corrupted or unsorted input file
FAILED
$ samtools index test_corrupted.bam || echo FAILED
[bam_index] corrupted or unsorted input file
FAILED
$ samtools index hello.bam || echo FAILED
[bam_index] corrupted or unsorted input file
FAILED
$ ls *.bai
noeof.bam.bai seq.bam.bai

**Comment by marcelm** [comment]
Nice, thanks a lot!
