### ISSUE TITLE
More powerful samtools view flag filtering

### ISSUE THREAD

**Issue by jmarshall** [samtools/samtools#364]
From a user:

> Please can you add functionality to allow removal of neither end mapped read pairs using samtools view? E.g by adding an option to filter reads for which all bits are set as well as the current -F for any bits set.

We should be able to find some way to do this by adding optional `+` or `-` prefixes to `-f`/`-F`, akin to find(1)'s `-flags` and `-perm`.

**Comment by jkbonfield** [comment]
Fixed by merging PR #505.
