### ISSUE TITLE
problems --with-irods

### ISSUE THREAD

**Issue by mcast** [samtools/samtools#367]
Hi,

Two small problems,

1. It would be nice to have a working `--with-irods` option on samtools.
  * I built `htslib-1.2.1` separately, which got me `bin/htsfile` etc., but then couldn't figure out how to link to it using `make HTSDIR=$HOME/build/src/htslib-1.2.1 install` or similar - it was failing to link, and I couldn't feed it a `-lRodsAPIs` the right way [transcript a. below]
  * I got it working with a pointy stick instead [transcript b. below].  Possibly I learned relevant things about controlling the build in between these attempts.
2. Once built, the only way to discover whether the binary is `--with-irods` is to try it.  [transcript c. below]

It works for me now, I just thought I should mention the problem.
Thanks,

----

a.
```
[...]
gcc -pthread  -o samtools bam_index.o bam_plcmd.o sam_view.o bam_cat.o bam_md.o bam_reheader.o bam_sort.o bedidx.o kprobaln.o bam_rmdup.o bam_rmdupse.o bam_mate.o bam_stat.o bam_color.o bamtk.o bam2bcf.o bam2bcf_indel.o errmod.o sample.o cut_target.o phase.o bam2depth.o padding.o bedcov.o bamshuf.o faidx.o stats.o stats_isize.o bam_flags.o bam_split.o bam_tview.o bam_tview_curses.o bam_tview_html.o bam_lpileup.o libbam.a /nfs/users/nfs_m/mca/build/src/htslib-1.2.1/libhts.a  -lcurses  -lm -lz
/nfs/users/nfs_m/mca/build/src/htslib-1.2.1/libhts.a(hfile_irods.o): In function `irods_exit':
/nfs/users/nfs_m/mca/build/src/htslib-1.2.1/hfile_irods.c:70: undefined reference to `rcDisconnect'
/nfs/users/nfs_m/mca/build/src/htslib-1.2.1/libhts.a(hfile_irods.o): In function `irods_close':
/nfs/users/nfs_m/mca/build/src/htslib-1.2.1/hfile_irods.c:192: undefined reference to `rcDataObjClose'
/nfs/users/nfs_m/mca/build/src/htslib-1.2.1/libhts.a(hfile_irods.o): In function `irods_seek':
/nfs/users/nfs_m/mca/build/src/htslib-1.2.1/hfile_irods.c:156: undefined reference to `rcDataObjLseek'
/nfs/users/nfs_m/mca/build/src/htslib-1.2.1/libhts.a(hfile_irods.o): In function `irods_write':
/nfs/users/nfs_m/mca/build/src/htslib-1.2.1/hfile_irods.c:139: undefined reference to `rcDataObjWrite'
/nfs/users/nfs_m/mca/build/src/htslib-1.2.1/libhts.a(hfile_irods.o): In function `irods_read':
/nfs/users/nfs_m/mca/build/src/htslib-1.2.1/hfile_irods.c:120: undefined reference to `rcDataObjRead'
/nfs/users/nfs_m/mca/build/src/htslib-1.2.1/libhts.a(hfile_irods.o): In function `hopen_irods':
/nfs/users/nfs_m/mca/build/src/htslib-1.2.1/hfile_irods.c:221: undefined reference to `parseRodsPath'
/nfs/users/nfs_m/mca/build/src/htslib-1.2.1/hfile_irods.c:232: undefined reference to `rcDataObjOpen'
/nfs/users/nfs_m/mca/build/src/htslib-1.2.1/hfile_irods.c:229: undefined reference to `addKeyVal'
/nfs/users/nfs_m/mca/build/src/htslib-1.2.1/libhts.a(hfile_irods.o): In function `irods_init':
/nfs/users/nfs_m/mca/build/src/htslib-1.2.1/hfile_irods.c:79: undefined reference to `getRodsEnv'
/nfs/users/nfs_m/mca/build/src/htslib-1.2.1/hfile_irods.c:82: undefined reference to `rcConnect'
/nfs/users/nfs_m/mca/build/src/htslib-1.2.1/hfile_irods.c:88: undefined reference to `clientLogin'
/nfs/users/nfs_m/mca/build/src/htslib-1.2.1/hfile_irods.c:100: undefined reference to `rcDisconnect'
collect2: ld returned 1 exit status
make: *** [samtools] Error 1
```

b.
```
$ tar xfj samtools-1.2.tar.bz2 
$ cd samtools-1.2/htslib-1.2.1/
$ ./configure --with-irods=/usr/local/iRODS --prefix=$HOME/build
$ cd ..
$ make LDLIBS='-L/usr/local/iRODS/lib/core/obj -lRodsAPIs' prefix=$HOME/build install
```

c.
```
$ ~/build/bin/samtools --version
samtools 1.2
Using htslib 1.2.1
Copyright (C) 2015 Genome Research Ltd.
$ /software/hgi/pkglocal/samtools-1.2/bin/samtools --version   # just a.n.other build
samtools 1.2
Using htslib 1.2.1
Copyright (C) 2015 Genome Research Ltd.
$ /software/hgi/pkglocal/samtools-1.2/bin/samtools view -H irods:/cgp-dev/intproj/212/sample/xxx/xxx_RNA.bam
[E::hts_open] fail to open file 'irods:/cgp-dev/intproj/212/sample/xxx/xxx_RNA.bam'
samtools: failed to open "irods:/cgp-dev/intproj/212/sample/xxx/xxx_RNA.bam" for reading: No such file or directory
$ ~/build/bin/samtools view -H irods:/cgp-dev/intproj/212/sample/xxx/xxx_RNA.bam
@HD     VN:1.4  GO:none SO:coordinate
[...]
```

**Comment by jmarshall** [comment]
1. Yes, building things that link with an iRODS-enabled htslib is a pain at the moment.  This pain is only going to get worse as we get more file-access backends.  Hence the plan is to change the file-access backends to separately-linked plugins, so the dependencies like `-lRodsAPIs` don't leak out to things linking to htslib itself, such as samtools.  This should be happening in the near future.

2. I'm not too sure what to do about this.  When file-access backends are separately-installable plugins, whether a particular backend is available becomes a runtime question.  I'm not particularly keen to invent an API-blessed way of enumerating them, though it would be good to have something.  Perhaps an option like `htsfile ‑‑list‑url‑schemes` would suffice?

**Comment by mcast** [comment]
On Mon, Mar 23, 2015 at 02:05:14AM -0700, John Marshall wrote:

> 1. [...] the plan is to change the file-access backends to
> separately-linked plugins, so the dependencies like `-lRodsAPIs`
> don't leak out to things linking to htslib itself, such as samtools.
> This should be happening in the near future.

Excellent, you're ahead of me then.


> 2. [...]  When file-access backends are separately-installable
> plugins, whether a particular backend is available becomes a runtime
> question.

Yes; so the original question of "what did I compile?" goes away, but
could potentially become a "what is available after runtime linking?"
problem and so continue to cause puzzlement.

(Will it be possible to build a static version?  I only ask because it
is one of my escape hatches when I have problems building stuff.)


> I'm not particularly keen to invent an API-blessed way of
> enumerating them, though it would be good to have something.
> Perhaps an option like `htsfile ‑‑list‑url‑schemes` would suffice?

It would do nicely.  I can see it might look like a non-productive
feature, but I think it will make it easier for users to understand
what's happening.

Presumably you have to pass stuff round all plugins anyway, to get
URLs handled?  I would suspect the existence of a library to do it,
since plugins commonly want to modify the argv parsing and --help
output...  can't suggest anything though, sorry.


Thanks for your thoughts,
-- 
Matthew


-- 
 The Wellcome Trust Sanger Institute is operated by Genome Research 
 Limited, a charity registered in England with number 1021457 and a 
 company registered in England with number 2742969, whose registered 
 office is 215 Euston Road, London, NW1 2BE.

**Comment by jmarshall** [comment]
Re (1), hFILE plugins have now landed in htslib's **develop** branch.  When htslib has been configured with ‑‑enable-plugins, you now just need `make LDFLAGS=-rdynamic LIBS=-ldl` to compile samtools. This too will go away with a sufficient sprinkling of pkg-config and/or configure…

**Comment by jmarshall** [comment]
Samtools now has a configure script, so you can configure samtools and it will pass `--enable-plugins` down to htslib.  It will also set `-rdynamic`/`-ldl` as needed (this is currently a bit of a hack), so samtools should now build cleanly when configured with iRODS.

I'm going to call plugin enumeration a separate problem :smile:  You can list them with `htsfile -vvvv file://foo.bam` for example…
