### ISSUE TITLE
prefered zlib 

### ISSUE THREAD

**Issue by ink1** [samtools/samtools#370]
Hi, this is not an issue but a question.
It's good to see in 1.2 release notes that the release has been tested against Intel-optimised zlib
https://github.com/jtkukunas/zlib
There is another performance fork of zlib thanks to CloudFlare
https://github.com/cloudflare/zlib
And here's an attempt at comparing the two
https://www.snellman.net/blog/archive/2014-08-04-comparison-of-intel-and-cloudflare-zlib-patches.html
"The summary is that CloudFlare's fork is much faster with decompression and a little faster with high compression levels, while Intel's is faster with low and medium compression levels."
What would be the merits of each fork as far as samtools is concerned?

**Comment by jkbonfield** [comment]
A good question.

I did briefly experiment with both to verify that they at least
worked.  All it needed was an LD_PRELOAD before running samtools
basically, or just permanently putting in LD_LIBRARY_PATH perhaps.

Intel put a lot of effort into speeding up compression and probably
come out the winners there but I think none into speeding up
decompression, while CloudFlare put effort into both.  Ideal would be
a mix of both!

I don't have BAM specific benchmarks though to indicate which is
best.  It may not be the same as that comparison as the
compressability of the data will impact the relative speeds.  At
default compression levels though I suspect there is little to choose
between them for compressing BAM.


-- 
James Bonfield (jkb@sanger.ac.uk) | Hora aderat briligi. Nunc et Slythia Tova
                                  | Plurima gyrabant gymbolitare vabo;
  A Staden Package developer:     | Et Borogovorum mimzebant undique formae,
https://sf.net/projects/staden/   | Momiferique omnes exgrabure Rathi. 


-- 
 The Wellcome Trust Sanger Institute is operated by Genome Research 
 Limited, a charity registered in England with number 1021457 and a 
 company registered in England with number 2742969, whose registered 
 office is 215 Euston Road, London, NW1 2BE.

**Comment by ink1** [comment]
Thank you, James.
According to this
http://stackoverflow.com/questions/28583687/is-cloudflare-fork-of-zlib-optimized-only-for-amd
fast compression was the objective of CloudFlare too. 
I presume that samtools (and BAM files in general) uses default compression level ie -6 and therefore created BAM files should not suffer from poor compression of Intel zlib when fast deflate strategy is used.

**Comment by jkbonfield** [comment]
On Tue, Mar 31, 2015 at 09:35:46AM -0700, ink1 wrote:
> I presume that samtools (and BAM files in general) uses default compression level ie -6 and therefore created BAM files should not suffer from poor compression of Intel zlib when fast deflate strategy is used.

I forget which level is used by default in samtools, but it basically
has two options - the samtools default (likely -6) and -1.  The -1
level is good for when you're temporarily creating BAMs and just want
to save a bit of I/O with minimal CPU overhead.

In this respect the Intel variant may have some potential, although
arguably if this is entirely internal to samtools itself it would be
better off using something like LZ4.

-- 
James Bonfield (jkb@sanger.ac.uk) | Hora aderat briligi. Nunc et Slythia Tova
                                  | Plurima gyrabant gymbolitare vabo;
  A Staden Package developer:     | Et Borogovorum mimzebant undique formae,
https://sf.net/projects/staden/   | Momiferique omnes exgrabure Rathi. 


-- 
 The Wellcome Trust Sanger Institute is operated by Genome Research 
 Limited, a charity registered in England with number 1021457 and a 
 company registered in England with number 2742969, whose registered 
 office is 215 Euston Road, London, NW1 2BE.

**Comment by ink1** [comment]
Looking at the help page, only view and merge can have  fast BAM compression (-1 option).
sort can have any compression level from 0 to 9.
I can't see how temporary compression can be changed. I agree, fast compression should be the right choice in this case.

**Comment by ink1** [comment]
I have finally got around doing some testing and I must say I'm baffled. 
The tests were performed on 2x E5-2670 (2x8 cores @ 2.60GHz) running Scientific Linux 6.4.
Compiler: gcc (GCC) 4.4.7 20120313 (Red Hat 4.4.7-3)
The SAM file was slightly over 3 GB (when compressed ~ 750MB).
The default zlib is 1.2.3. 
The build of zlib 1.2.8 was using defaults. The only difference with building the Intel and CloudFlare forks was I used CFLAGS="-mssse4.2 -mpclmul" because CloudFlare needed these options.
When using zlib 1.2.8 the binary was the same (the default built).

Compression
Default: samtools view -Sb    out.sam > out.bam
Fast: samtools view -Sb -1 out.sam > out.bam

          DEFAULT     FAST (option -1)

zlib 1.2.3
elapsed 131.589 s     53.248 s
elapsed 131.267 s     52.896 s
elapsed 134.295 s     53.152 s

zlib 1.2.8
elapsed 136.507 s     52.845 s
elapsed 137.850 s     52.631 s
elapsed 136.641 s     53.077 s

zlib 1.2.8 intel
elapsed 207.016 s     66.129 s
elapsed 207.647 s     65.743 s
elapsed 205.219 s     66.554 s

zlib 1.2.8 cloudflare
elapsed 160.872 s     79.657 s
elapsed 160.134 s     79.998 s
elapsed 159.769 s     80.429 s

Decompression:
samtools view out.bam > output.sam

zlib 1.2.3
elapsed 24.580 s
elapsed 24.191 s
elapsed 24.549 s

zlib 1.2.8
elapsed 24.969 s
elapsed 26.081 s
elapsed 25.013 s

zlib 1.2.8 intel
elapsed 37.914 s
elapsed 37.754 s
elapsed 40.300 s

zlib 1.2.8 cloudflare
elapsed 38.121 s
elapsed 38.932 s
elapsed 38.423 s

**Comment by jkbonfield** [comment]
That's definitely odd, and not matching my own tests. See http://www.htslib.org/benchmarks/zlib.html

Was it actually correctly working?  We'd expect the -1 bam to be substantially larger when using Intel zlib than the default zlib as Intel introduced a different speed/ratio data point (a good idea IMO).  If your files aren't substantially larger then maybe it implies something isn't working.  However I'm sure you've already checked that - I'm just clutching at straws to identify why it would be so different.

I can see how elapsed time for Intel zlib -1 could be slower for elapsed time; the files are larger and if file I/O is slow then the elapsed time becomes dominated by file write times.  However it ought to be substantially faster for system+user CPU time, unless this is also dominated by a particularly slow I/O kernel driver. (This may be the case for some filesystems, like lustre.)

**Comment by ink1** [comment]
As it happens, I AM on Lustre so will try writing elsewhere, e.g. ram.
The file sizes produced with -1 aren't substantially larger, simply larger.
```
  785784279  out.bam-zlib-1.2.8
  906687767  out.bam-zlib-1.2.8-1
  786806130  out.bam-zlib-1.2.8-cloudflare
  890086922  out.bam-zlib-1.2.8-cloudflare-1
  793320689  out.bam-zlib-1.2.8-intel
 1144714270  out.bam-zlib-1.2.8-intel-1
 3337335043  out.sam
```

**Comment by ink1** [comment]
The good news, our Lustre setup is fine (and not to blame). 

James, using your command
```
time  LD_PRELOAD=/path/to/lib \
samtools view -b -@ 4 -o /dev/shm/output.bam /dev/shm/out.bam
```
I got the following
```
zlib 1.2.8
elapsed 41.090 s
elapsed 41.037 s
elapsed 41.121 s

zlib 1.2.8 intel
elapsed 71.954 s
elapsed 72.124 s
elapsed 71.926 s

zlib 1.2.8 cloudflare
elapsed 60.354 s
elapsed 60.499 s
elapsed 60.118 s
```

**Comment by jmarshall** [comment]
Interesting results… not sure if there's anything that can be addressed here, other than it's best to do one's own benchmarking.

**Comment by ink1** [comment]
I just had another look at it. I rebuilt both zlib and samtools using gcc 4.8.3 and saw the same picture. I also found that building zlib 1.2.8 with
```
CFLAGS="-mssse4.2 -mpclmul"
```
breaks configure. This gave me a hint and the next thing I did was to remove my changes to CFLAGS (see above). Here is the results for both standard zlib and Intel zlib using the same test as earlier 
```
# time  LD_PRELOAD=/path/to/lib samtools view -b -@ 4 -o out.bam in.bam

# Using gcc 4.8.3 and NOT setting CFLAGS="-mssse4.2 -mpclmul"

zlib 1.2.8 defaults
elapsed 40.588 s
elapsed 40.978 s
elapsed 41.175 s

zlib 1.2.8 intel
elapsed 32.171 s
elapsed 31.679 s
elapsed 31.496 s

# Using gcc 4.4.7 and NOT setting CFLAGS="-mssse4.2 -mpclmul"

zlib 1.2.8
elapsed 42.732 s
elapsed 42.465 s
elapsed 42.506 s

zlib 1.2.8 intel
elapsed 33.268 s
elapsed 32.972 s
elapsed 32.992 s
```
The speedup from using Intel zlib is obvious (~ 22 % faster) whereas the difference due compilers is marginal. 

As I said before, I can't build CloudFlare zlib without those CFLAGS. What compiler version did you use in your tests? Did you have to set CFLAGS?

**Comment by ink1** [comment]
A quick update: CloudFlare zlib has to be built with CFLAGS="-O3 -msse4.2 -mpclmul"
This results in even better performance than Intel zlib (thanks to Vlad https://github.com/vkrasnov)
```
zlib 1.2.8 cloudflare
elapsed 26.587 s
elapsed 26.994 s
elapsed 27.002 s
```
Mystery solved. 36% speedup

**Comment by tchwpkgorg** [comment]
Hmm, how did you manage to compile Cloudflare zlib? It errors for me during the compilation:

[root@kvmtest zlib-gcc.amd64]# ./configure 
Checking for gcc...
Checking for shared library support...
Building shared library libz.so.1.2.8 with gcc.
Checking for off64_t... Yes.
Checking for fseeko... Yes.
Checking for strerror... Yes.
Checking for unistd.h... Yes.
Checking for stdarg.h... Yes.
Checking whether to use vs[n]printf() or s[n]printf()... using vs[n]printf().
Checking for vsnprintf() in stdio.h... Yes.
Checking for return value of vsnprintf()... Yes.
Checking for attribute(visibility) support... Yes.
Checking for PCLMUL support ... No
Checking for SSE4.2 support ... No
[root@kvmtest zlib-gcc.amd64]# make
gcc -O3  -D_LARGEFILE64_SOURCE=1 -DHAVE_HIDDEN -I. -c -o example.o test/example.c
gcc -O3  -D_LARGEFILE64_SOURCE=1 -DHAVE_HIDDEN   -c -o adler32.o adler32.c
gcc -O3  -D_LARGEFILE64_SOURCE=1 -DHAVE_HIDDEN   -c -o crc32.o crc32.c
gcc -O3  -D_LARGEFILE64_SOURCE=1 -DHAVE_HIDDEN   -c -o deflate.o deflate.c
gcc -O3  -D_LARGEFILE64_SOURCE=1 -DHAVE_HIDDEN   -c -o infback.o infback.c
gcc -O3  -D_LARGEFILE64_SOURCE=1 -DHAVE_HIDDEN   -c -o inffast.o inffast.c
gcc -O3  -D_LARGEFILE64_SOURCE=1 -DHAVE_HIDDEN   -c -o inflate.o inflate.c
gcc -O3  -D_LARGEFILE64_SOURCE=1 -DHAVE_HIDDEN   -c -o inftrees.o inftrees.c
gcc -O3  -D_LARGEFILE64_SOURCE=1 -DHAVE_HIDDEN   -c -o trees.o trees.c
gcc -O3  -D_LARGEFILE64_SOURCE=1 -DHAVE_HIDDEN   -c -o zutil.o zutil.c
gcc -O3  -D_LARGEFILE64_SOURCE=1 -DHAVE_HIDDEN   -c -o compress.o compress.c
gcc -O3  -D_LARGEFILE64_SOURCE=1 -DHAVE_HIDDEN   -c -o uncompr.o uncompr.c
gcc -O3  -D_LARGEFILE64_SOURCE=1 -DHAVE_HIDDEN   -c -o gzclose.o gzclose.c
gcc -O3  -D_LARGEFILE64_SOURCE=1 -DHAVE_HIDDEN   -c -o gzlib.o gzlib.c
gcc -O3  -D_LARGEFILE64_SOURCE=1 -DHAVE_HIDDEN   -c -o gzread.o gzread.c
gcc -O3  -D_LARGEFILE64_SOURCE=1 -DHAVE_HIDDEN   -c -o gzwrite.o gzwrite.c
ar rc libz.a adler32.o crc32.o deflate.o infback.o inffast.o inflate.o inftrees.o trees.o zutil.o compress.o uncompr.o gzclose.o gzlib.o gzread.o gzwrite.o 
gcc -O3  -D_LARGEFILE64_SOURCE=1 -DHAVE_HIDDEN -o example example.o -L. libz.a
libz.a(deflate.o): In function `fill_window':
deflate.c:(.text+0xce): undefined reference to `_mm_crc32_u32'
libz.a(deflate.o): In function `deflate_fast':
deflate.c:(.text+0x4e9): undefined reference to `_mm_crc32_u32'
deflate.c:(.text+0x67f): undefined reference to `_mm_crc32_u32'
deflate.c:(.text+0x96a): undefined reference to `_mm_crc32_u32'
libz.a(deflate.o): In function `deflate_stored':
deflate.c:(.text+0xf1f): undefined reference to `_mm_crc32_u32'
libz.a(deflate.o):deflate.c:(.text+0x1415): more undefined references to `_mm_crc32_u32' follow
collect2: error: ld returned 1 exit status
make: *** [example] Error 1

**Comment by jkbonfield** [comment]
I can't remember that being an issue.  I think it worked.

The error you are seeing looks like it is failing to find the GCC intrinsics.  I would normally expect those names to be expanded into inline assembly, not function calls to be resolved by the linker.  I could be wrong though as I'm not an expert in intrinsics.

**Comment by ink1** [comment]
Hi, I recommend setting CFLAGS="-O3 -march=native" before you run configure. Then you should see
```
Checking for PCLMUL support ... Yes
Checking for SSE4.2 support ... Yes
```
rather than
```
Checking for PCLMUL support ... No
Checking for SSE4.2 support ... No
```
unless your hardware does not support it (check /proc/cpuinfo) or your compiler is too old. You may say it is an error in configure which should have yielded an error in the first place rather than finish quietly. 
This is due to specific hardware support the code requires. This support can be enabled by setting CFLAGS="-msse4.2 -mpclmul" but the important thing is the "-O3" is required too for good performance and "-march=native" covers both sse4.2 and pclmul if they are available hence the suggestion above.

**Comment by avilella** [comment]
@ink1 is there a self-contained fork of zlib and samtools+htslib using this? Or is there a zipped folder with all the prebuilt binaries and libraries to download and test? Thx

**Comment by ink1** [comment]
Not that I'm aware of
