### ISSUE TITLE
samtools sort 1.2 (and 1.1) hang during file merging stage in "pretty_header"

### ISSUE THREAD

**Issue by pdblood** [samtools/samtools#373]
Using this command (running on node with 128 GB memory): 

samtools sort -m 7G -o out.bam -n -T $prefix -@ 15 in.bam

to sort large BAM file (40 GB).  When it gets to this stage:

[bam_sort_core] merging from 45 files...

it gets stuck in the pretty_header function in bam_merge_core2 and stays there indefinitely.  Here is the backtrace from attaching with gdb:

(gdb) backtrace
#0  0x00002aaaab87a0db in __strlen_sse2 () from /lib64/libc.so.6
#1  0x00002aaaab8b59d8 in regexec@@GLIBC_2.3.4 () from /lib64/libc.so.6
#2  0x000000000040dabd in pretty_header ()
#3  0x0000000000413b8e in bam_merge_core2 ()
#4  0x00000000004165a7 in bam_sort_core_ext ()
#5  0x00000000004169e8 in bam_sort ()
#6  0x00002aaaab817c36 in __libc_start_main () from /lib64/libc.so.6
#7  0x0000000000403e89 in _start () at ../sysdeps/x86_64/elf/start.S:113

**Comment by nathanweeks** [comment]
This is probably related to https://github.com/samtools/samtools/pull/337

**Comment by pdblood** [comment]
Yes, applying this patch solves the problem.  What are the chances of this patch being pulled into the next release?
