### ISSUE TITLE
samtools depth - output for zero-coverage positions

### ISSUE THREAD

**Issue by tseemann** [samtools/samtools#374]
The default behaviour for ```samtools depth``` seems to be to skip over positions that have zero depth in all the provided BAM files.

Would you consider adding an option ```-a   output all positions``` to output _every_ position in every sequence even if it is zero?

This would make it much more straightforward for downstream streaming applications. Currently they need to have more complicated stateful parsers (to keep track of skipped locations) and also they need to the reference FASTA and .fai file to determine if any sequences (or bases at the end of a sequence) were missed.

**Comment by jkbonfield** [comment]
I'll look into this, but have a few questions.  Do you want zero depth coverage reported for reference sequences in the header that have no coverage in the file?  Technically "all" would include these, but I don't think it's particularly useful.

A related question is how to deal with terminal positions of a reference. Eg maybe we have po2 100 to 4900 covered for a 5Kb reference.  Should we output the first 99 bp and last 100bp as depth zero too, or just internal regions where it goes from +ve depth to 0 and back up to +ve? 

My instinct is to reported all locations (terminal or otherwise) on any reference that is at least partially covered, but not on references totally uncovered.

**Comment by jkbonfield** [comment]
It doesn't look hard to have -a being an incremental counter, so -a means all and -aa or -a -a means absolutely all.  The difference being whether to output depth information for references that are not used.

**Comment by tseemann** [comment]
@jkbonfield  James, sorry I missed your reply here. 

I did want all positions in all sequences. I work mainly with 100-1000s of bacterial isolates, and looking at depths is a standard task for determining core and pan genome locii. Your ```-a``` and ```-a -a``` options are ideal. 

Thank you so much considering this request and implementing them! This will simplify downstream analyses significantly,

Torst

**Comment by johnmu** [comment]
Should the -a option ignore N positions in the reference instead of just ignoring on the end? That is take a reference genome and ignore N positions in the genome when outputting depth. 

Maybe I am missing something, but it seems like -a will ignore the telomere regions in a chromosome but still output zeros in the centromere region or any internal unmappable regions. Is that right?

**Comment by mfoll** [comment]
@jkbonfield, I think @johnmu is right and there is bug here: `samtools depth -a` omits the end of each chromosome after the last position having a non-zero depth. Here is an example where the end of chr1 having zero coverage is missing (but as you can see the beginning of chr2 is here, and the beginning of chr1 is here too):
```
$ samtools depth -a test.bam | grep -B 5 chr2 | head 
chr1	249231316	7
chr1	249231317	2
chr1	249231318	2
chr1	249231319	2
chr1	249231320	1
chr2	1	0
chr2	2	0
chr2	3	0
chr2	4	0
chr2	5	0
```
Here is the size of chr1 as indicated in the BAM header:
```
$ samtools view -H test.bam | grep "SN:chr1 "
@SQ	SN:chr1	LN:249250621
```
When specifying `-r chr1` the chromosome is complete:
```
$ samtools depth -a -r chr1 test.bam | tail -5
chr1	249250617	0
chr1	249250618	0
chr1	249250619	0
chr1	249250620	0
chr1	249250621	0
```
This was done with the last dev branch:
```
$ samtools --version
samtools 1.3.1-9-ge5dfb0a
Using htslib 1.3.1-23-g375ba53
Copyright (C) 2016 Genome Research Ltd.
```

**Comment by jkbonfield** [comment]
Reopening while I look at the PR.   Agreed there is still a bug.

**Comment by jkbonfield** [comment]
I'm not even sure how the -a vs -aa distinction should works when used in conjunction with regions or bed files.

Without any region information, -a shows the entire chromosome/reference when at least one record is pulled back while -aa shows other references that aren't covered.

What about if we limit to say chr1:1000000-2000000 and only have coverage in chr1:3000000 onwards?  We pull no records back with our initial search.  Should -a show nothing and -aa show all the requested region (but not other chromosomes)?

What about bed files?  Our SQ lines may list chr 1-22, X and Y while the bed file may have regions covering chr 10-15 only, of which say chr 11 has any data at all in the BAM file.   Should -b bed -a show all of chr11 listed in the bed file (so not ALL of it, but all of it requested) and -aa show all of the other requested regions?  This is actually quite a lot of work as the bed parsing is in a different piece of code and the internals are opaque to the depth/pileup code.  I regret ever adding these features!  Would it be so bad just to say they don't support bed? ;-)

**Comment by mfoll** [comment]
For me specifying -a and a region/bed means that I want all positions in this region/bed even if the BAM contains nothing in the positions specified. For consistency I think it's quite important to always output the same thing whether the BAM contains reads or not (think about tools processing the output). 

My feeling is that using -aa and specifying a region/bed doesn't make sense. It should be either not allowed or simply behave like -a.

**Comment by jkbonfield** [comment]
We've discussed it in the office and I think the consensus is this:

If we had data covering all locations and specify a bed file then we clearly get data for all spots listed in that bed file.  -a/-aa should make this true regardless of whether we do actually have data covering all locations.  Thus conceptually -a / -aa apply on the input and bed then applies as a streaming filter.

The same can apply to regions.

**Comment by mfoll** [comment]
So in practice there won't be any difference using `-b bed -a` or `-b -bed -aa` right?

**Comment by jkbonfield** [comment]
Possibly; it depends if I can be bothered to fish into the bed parser code.  In theory it could be possible to distinguish the case of a bed file referencing a segment that has no hits vs a bed file references a segment that has a partial overlap.  However in practice it may make sense to just make -a/-aa be the same thing for BED given the complexity of doing anything else.

**Comment by mfoll** [comment]
Agreed!

**Comment by johnmu** [comment]
Thanks for fixing this!

**Comment by AnnieJforster** [comment]
Hi! In bam files I've been analysing -a outputs nothing for certain regions (and -aa outputs 0 depth as described above) - however there is coverage on the same chromosome in the bam file so it isn't wholly unused. How can this be? Just trying to wrap my head around what this means.
