### ISSUE TITLE
samtools stats ACGT content per cycle - N's counted as T's

### ISSUE THREAD

**Issue by ces** [samtools/samtools#376]
hi

In the ACGT content per cycle section in the output from samtools (version used = 1.2-2-gf8a6274) it appears N's are being counted as Ts e.g. output from test file containing reads which are all only N's;

# ACGT content per cycle. Use `grep ^GCC | cut -f 2-` to extract this part. The columns are: cycle, and A,C,G,T counts [%]
GCC	        1	0.00	0.00	0.00	100.00
GCC  	2	0.00	0.00	0.00	100.00
GCC	        3	0.00	0.00	0.00	100.00
GCC	        4	0.00	0.00	0.00	100.00
etc

Perhaps count N's separately or exclude 

Thanks
Carol

**Comment by jmarshall** [comment]
Confirmed in **develop**: [SVTWYHKDBN are all counted as T](https://github.com/samtools/samtools/blob/develop/stats.c#L661-L669), and M as C and R as G.  (Though only N is actually likely to occur!)

Perhaps best to just exclude them unless it might be useful to graph Ns as well...

**Comment by ces** [comment]
Thanks John - excluding is fine with me.

**Comment by dkj** [comment]
If dividing by the sum of ACGTs then we'll lose the info about Ns -  though better for base composition display that will hide problems. So I'd suggest either exclude Ns but divide by number of reads, or if dividing by number of ACGTs then a separate column/stat for Ns by cycle.

**Comment by jrandall** [comment]
Suggest a fix for this issue should be included in v1.3, as it is making it impossible to use `samtools stats` output to do QC based on base content vs read cycle deviation.

**Comment by jmarshall** [comment]
The existing `bam-plotstats` script will accept `GCC` input lines with an extra percentage column without problems.  (Verified just now.  This is what I was worried about when I said "Perhaps best to just exclude" above.)

So we should add an `other` column at the end of the GCC lines to show the information about Ns.  (And certainly the divisor should remain the same as now, and the sum of all five columns should be approx 100%.)

And at our leisure we can update `bam-plotstats` to display an N line to the _Per-base sequence content_ graph if the extra column is in the input.  I guess this would be useful information in the graph?
