### ISSUE TITLE
segfault in samtools merge with -R option

### ISSUE THREAD

**Issue by dg13** [samtools/samtools#377]
Minor issue, but if you try to merge non-indexed bams in a specific region using the -R option you get a segfault without an informative error message e.g.

samtools merge -f tmp.bam -n Data/yeung/bams//9305_4#1.bam Data/yeung/bams//9305_5#1.bam -R 1:3030000-6000000
Segmentation fault

If I index the bams, the merge completes without error. Probably just need to include an informative error message to tell users that the indices are missing as is already done for samtools view i.e.

samtools view Data/yeung/bams//9305_4#1.bam 1:1-10
[main_samview] random alignment retrieval only works for indexed BAM or CRAM files.

**Comment by jmarshall** [comment]
Fixed by #378.
