### ISSUE TITLE
samtools doesn't understand 'localhost' in url

### ISSUE THREAD

**Issue by dcolligan** [samtools/samtools#382]
Using `0.0.0.0` works for remote fetches of BAM files:

```
$ samtools view 'http://0.0.0.0:8002/wgEncodeUwRepliSeqBg02esG1bAlnRep1_sample.bam'
... output ...
```

But using `localhost` does not:

```
$ samtools view 'http://localhost:8002/wgEncodeUwRepliSeqBg02esG1bAlnRep1_sample.bam'
connect: Connection refused
[E::hts_open] fail to open file 'http://localhost:8002/wgEncodeUwRepliSeqBg02esG1bAlnRep1_sample.bam'
samtools: failed to open "http://localhost:8002/wgEncodeUwRepliSeqBg02esG1bAlnRep1_sample.bam" for reading: Bad file descriptor
```

**Comment by jmarshall** [comment]
It works fine elsewhere, so you'll have to say more about your local environment if you want help debugging it.

What version of samtools?  HTSlib?  Is `$http_proxy` set?  Most importantly, which ports is your server listening on (`netstat -an` etc)?

**Comment by jmarshall** [comment]
Apparently this was unreproducible by the OP.
