### ISSUE TITLE
getline() missing on snow leopard Mac

### ISSUE THREAD

**Issue by pcantalupo** [samtools/samtools#392]
Hello,

I'm having problems compiling Samtools on Mac snow leopard 10.6 with GCC version 4.9.2_1 (from Homebrew). I was able to compile Bcftools successfully on the same system. Here are the last several lines of output:

```
gcc -g -Wall -O2 -D_FILE_OFFSET_BITS=64 -D_LARGEFILE64_SOURCE -D_CURSES_LIB=1 -I. -I../htslib  -c -o misc/wgsim.o misc/wgsim.c
gcc  -o misc/wgsim misc/wgsim.o -lm -lz
gcc -g -Wall -O2 -D_FILE_OFFSET_BITS=64 -D_LARGEFILE64_SOURCE -D_CURSES_LIB=1 -I. -I../htslib  -c -o test/merge/test_bam_translate.o test/merge/test_bam_translate.c
test/merge/test_bam_translate.c: In function 'main':
test/merge/test_bam_translate.c:386:5: warning: implicit declaration of function 'getline' [-Wimplicit-function-declaration]
     if ( (getline(&res, &len, check) == -1 ) &&
     ^
gcc -g -Wall -O2 -D_FILE_OFFSET_BITS=64 -D_LARGEFILE64_SOURCE -D_CURSES_LIB=1 -I. -I../htslib  -c -o test/test.o test/test.c
gcc -pthread  -o test/merge/test_bam_translate test/merge/test_bam_translate.o test/test.o ../htslib/libhts.a -lz
Undefined symbols:
  "_getline", referenced from:
      _main in test_bam_translate.o
      _main in test_bam_translate.o
      _main in test_bam_translate.o
      _main in test_bam_translate.o
      _main in test_bam_translate.o
      _main in test_bam_translate.o
      _main in test_bam_translate.o
      _main in test_bam_translate.o
      _main in test_bam_translate.o
      _main in test_bam_translate.o
      _main in test_bam_translate.o
      _main in test_bam_translate.o
     (maybe you meant: _hts_getline, _bgzf_getline )
ld: symbol(s) not found
collect2: error: ld returned 1 exit status
make: *** [test/merge/test_bam_translate] Error 1
```

What do I try next?

Thank you,

Paul

**Comment by jmarshall** [comment]
Alas, `getline()` is provided on OS X only on 10.7 and later.  In samtools, it's only used by the test suite so in fact you have successfully compiled **samtools** itself.  I would suggest you ignore the test suite for now by modifying the samtools makefile to comment out the last word on the `all` line:

    all: $(PROGRAMS) $(BUILT_MISC_PROGRAMS)  # $(BUILT_TEST_PROGRAMS)

and you will succeed with `make` and `make install`.

We may eradicate the use of `getline()`.  I have been experimenting with adding a kstring_t `kgetline()`, and `ks_getuntil()` probably already suffices, though kstream may be best avoided.

**Comment by pcantalupo** [comment]
Hello,
Wonderful...that worked. Thank you,

Paul
