### ISSUE TITLE
Samtools sort -n is not a lexical sort!

### ISSUE THREAD

**Issue by smowton** [samtools/samtools#398]
I just got burned by using samtools sort -n to sort by QNAME. Since that field is an arbitrary string, I assumed this would sort in natural textual order, but in fact it tries to parse variable-width numerical fields when they occur in the same place in both strings, to e.g. place A:2:5 before A:10:5.

At the very least you should mention that some clever ordering is being attempted that disagrees with coreutils 'sort' et al, and I suggest adding a new option -N that uses the expected ordering.

**Comment by smowton** [comment]
(and/or export strnum_cmp from htslib, so the ordering you're using can be duplicated without copy-pasting the code)

**Comment by smowton** [comment]
Finished tracing the related bugs today: the remaining ones were due to samtools sort -n producing a different sort order to Picard / htsjdk with SORTORDER=queryname. The latter produces plain ol' strcmp-esque results, meaning that merging datasets sorted by samtools and sorted by Picard produced nonsensical results.

Since the SAM spec doesn't say anything about a curious strnum_cmp-based ordering, and defines QNAME as a plain string, I suggest Samtools should match Picard's behaviour.

**Comment by jmarshall** [comment]
I suggest you read samtools/hts-specs#5 and the [samtools-devel thread](http://sourceforge.net/p/samtools/mailman/message/26674128/) linked from there.

**Comment by smowton** [comment]
Aha, thanks. I'll close this and comment on #5.
