### ISSUE TITLE
install target does not install headers in prefix/include

### ISSUE THREAD

**Issue by kotoroshinoto** [samtools/samtools#403]
it really ought to instal whichever .h files are intended for distribution for use linking against libbam

**Comment by jmarshall** [comment]
Historically samtools has not had an _install_ target at all, and various third parties have installed the headers into `PREFIX/include`, `PREFIX/include/bam`, `PREFIX/include/samtools`, and so on.  So whatever convention we chose would be not what some client software was expecting.

[HTSlib](https://github.com/samtools/htslib) is now our recommended API, and its _install_ target does install headers and libraries for development.  The legacy samtools API is only barely supported for historical reasons, so we shouldn't start installing it now.

**Comment by kotoroshinoto** [comment]
I personally don't understand why some of the bioinformatics tools are so resistant to changes in API of support libraries. Tophat disliked the change so much they actually froze samtools versions and keep a copy of old samtools code with their source tree. 

Perhaps they call libraries directly too often instead of abstracting access, so it complicates updates if you change the api too much? 

They did something similar with SeqAn 1.3, which is now causing a problem with compiling using newer gcc. It is quite frustrating to encounter developers that do this, it nearly always leads to eventual problems, since their dependencies receive no updates..
