### ISSUE TITLE
mpileup coverage and samtools tview coverage inconsistent

### ISSUE THREAD

**Issue by inodb** [samtools/samtools#408]
I am trying to parse the output of pileup (http://samtools.sourceforge.net/pileup.shtml) and determine allelic frequencies of the reported indels. The problem I'm facing is that the coverage as given by samtools mpileup is different from what I see in samtools tview. For instance when I run:

```
$ samtools mpileup -r X:150349557 -q 0 -f human_g1k_v37.fa S10.bam
X       150349557       C       24      .$,-12caccactggcca.-12CACCACTGGCCA.,.,,,,.-12CACCACTGGCCA,..,,-12caccactggcca..-12CACCACTGGCCA,,,..,    ;FCDDDDDDD/FDCC/C/E<FBDC
```
The reported coverage is 24. If I count the dots and commas:
```python
$ test2= ".$,-12caccactggcca.-12CACCACTGGCCA.,.,,,,.-12CACCACTGGCCA,..,,-12caccactggcca..-12CACCACTGGCCA,,,..,"
$ test2.count(".") + test2.count(",")
24
```
That would seem correct. Now when I pull up the same region in samtools tview:
```
$ samtools tview -p X:150349557 S10.bam human_g1k_v37.fa
```
There are 26 reads aligning. Am I misunderstanding something or is this a bug?
![screen shot 2015-06-13 at 12 39 21 pm](https://cloud.githubusercontent.com/assets/1334004/8145145/c6251826-11c9-11e5-93cb-d0f442554feb.png)

**Comment by tseemann** [comment]
I think samtools mpileup has -Q 13 as default, so any bases with Q < 13 will not be counted in the depth. I suspect samtools tview shows all bases. Does the colouring of two of the bases match the Q=0..9 range (type 'h' to see the legend).

**Comment by inodb** [comment]
Thanks for the reply! It could be something with the base quality, two of them are colored in yellow:
![screen shot 2015-06-14 at 11 31 06 am](https://cloud.githubusercontent.com/assets/1334004/8149194/e8f41fe0-1288-11e5-8324-ce4f8386fc7e.png)
But Q < 13 should be either blue or green:
![screen shot 2015-06-14 at 11 32 14 am](https://cloud.githubusercontent.com/assets/1334004/8149198/05540e7a-1289-11e5-8f15-161b89bea417.png)
For mpileup the default is indeed -Q 13 but when I run mpileup with -q 0 and -Q 0 I get the same results as above.

**Comment by jkbonfield** [comment]
It could be due to the automatic filtering of anomalous read pairs or removal of overlapping reads.

Try using mpileup -A -x (and maybe for good measure -B just to see if BAQ recalculation changes anything).

**Comment by inodb** [comment]
Thanks for the feedback. I tried using -A -x and -B now. There is indeed one anomalous read pair that is filtered because I get one more comma in the mpileup output. That still however adds up the coverage to 25 and not 26 as I see in tview. The version I am using is:
```
samtools 1.2
Using htslib 1.2.1
Copyright (C) 2015 Genome Research Ltd.
```

**Comment by inodb** [comment]
Same results with:
```
samtools 5363823fae72b5de29c02d726002886b30c80eb0
htslib 10c4920894eeba6911413e13e59a3cc574f48346
```

**Comment by jkbonfield** [comment]
Experimenting on some local files I think this is probably due to filtering of duplicates or secondary reads.  This is correct behaviour, but to check that this is the cause of the difference to tview (which doesn't filter nor does it have options to filter), try ```samtools mpileup --ff 4``` to request only filtering of unmapped data.

**Comment by inodb** [comment]
Great! Yes that was the inconsistency, ``samtools tview`` showed one extra read that was an anomalous read pair and one other read that was a duplicate read. Setting ``-A`` and ``--ff 4`` for ``mpileup`` made the number of reads consistent for this case. I guess to make all cases consistent the mpileup command is ``mpileup -A --ff4 -x -B -q 0 -Q 0``. Thanks a bunch everybody.
