### ISSUE TITLE
Samtools sort loses RG/PG entries when using tmp files

### ISSUE THREAD

**Issue by mktrost** [samtools/samtools#416]
On the latest development version, when samtools sort uses temporary files, it appears to lose the RG/PG lines of the header.  The lines are maintained if it does not use temporary files.
Samtools version 1.2 keeps the RG/PG even when using temporary files, so it appears to be an issue that was introduced since then.

**Comment by mp15** [comment]
This is caused by the same issue as #411 caused by 55c852f. Currently working on a fix.

**Comment by mktrost** [comment]
Sorry, didn't realize this would be a duplicate.  Thank you for working on it!

**Comment by mp15** [comment]
Fixed by 227c142c288b4757e9bd7907a0b52a9f16ee451b
