### ISSUE TITLE
samtools mpileup returns error code 1 if no results are generated

### ISSUE THREAD

**Issue by lbeltrame** [samtools/samtools#417]
I opened this to see if this is by design, as it causes breakage in software that used to rely on it being 0 even if there was no mpileup output (see chapmanb/bcbio-nextgen#918).

samtools 1.2
Using htslib 1.2

**Comment by jkbonfield** [comment]
I haven't investigated yet, but my instinct is it's wrong.  If the correct answer to an query is no output, then it shouldn't fail.

**Comment by jmarshall** [comment]
Samtools mpileup exits with status 0 even if there is no pileup output to be printed.

I suspect what you have encountered is a corrupted BAM file or otherwise broken other input files — which has not been adequately diagnosed with an error message (which would itself be a samtools bug).

**Comment by jkbonfield** [comment]
We believe this is working. If you can demonstrate otherwise please reopen the ticket.  Thanks.
