### ISSUE TITLE
Usage message for samtools sort unclear

### ISSUE THREAD

**Issue by dg13** [samtools/samtools#418]
Hi,
Very minor thing, but I find the usage message for samtools sort unhelpful. The usage message states "either -O or -T is required", but this doesn't seem to be true:

samtools sort tmp.bam -O bam
[bam_sort] no prefix specified for temporary files (use -T option)

while

samtools sort tmp.bam -T blah
[bam_sort] can't determine output format

so sort requires *both* -O and -T options to be used. Another odd thing is that, even though -o is "Write final output to FILE", if you don't use option -T, the final output is sent to stdout anyway. This is really confusing - it seems like -T is always required, whatever output you want. 
D
ps - using samtools 1.2

**Comment by SamStudio8** [comment]
Duplicates #295

**Comment by dg13** [comment]
OK thanks. There is a separate issue in my post (about -o -T leading to output on stdout rather than to the file specified in -o). Could this be merged also? Should I do this by posting in this issue?
D

====================================
Daniel Gaffney
Career Development Fellow
Wellcome Trust Sanger Institute
Wellcome Trust Genome Campus
Hinxton,
Cambridge, CB10 1SA
UK

http://www.sanger.ac.uk/research/faculty/dgaffney/

Tel: ++44 (0) 122 349 6866
====================================

**Comment by SamStudio8** [comment]
That might be touched on by #356, I'm not entirely sure...

**Comment by dg13** [comment]
I think its a separate issue i.e. behaviour of -o changes depending on whether you use the -T flag or not

====================================
Daniel Gaffney
Career Development Fellow
Wellcome Trust Sanger Institute
Wellcome Trust Genome Campus
Hinxton,
Cambridge, CB10 1SA
UK

http://www.sanger.ac.uk/research/faculty/dgaffney/

Tel: ++44 (0) 122 349 6866
====================================

**Comment by SamStudio8** [comment]
It seems to me that the problem is caused by a check in the argument parsing for sort; where use of either `-O` or `-T` triggers the options to be parsed with a "modern" flag. Otherwise the options are parsed as "legacy" usage, which for `-o` sets `is_stdout = 1`:

`case 'o': if (modern) fnout = optarg; else is_stdout = 1; break;`

Perhaps this is what is meant by "either -O or -T is required [to trigger 'modern' options]".

What happens if you specify `-o` and `-O` without `-T`?

**Comment by dg13** [comment]
Using -o and -O without -T gives:
"[bam_sort] no prefix specified for temporary files (use -T option)"

**Comment by SamStudio8** [comment]
Ok that'll be due to `-T` not being set automatically (which it is when the command is in "legacy" mode). I think this `modern` flag does explain the odd behaviour you see in `-o` changing whether `-T` is set or not.

**Comment by dg13** [comment]
Right - so this is mostly down to a not great choice of option labels. In legacy mode -o means output to stdout, in modern mode -o means the opposite. Would make more sense if you had -O correspond to output to file, and another flag altogether for format (-f?). Probably too late to change this now, so should probably be explained a bit more clearly in the usage, as it stands its fairly confusing.

**Comment by SamStudio8** [comment]
Correct, sorry for taking the longest route to give you an answer!
Having an option that is ambiguously opposite depending on arbitrary version selection (did the user specify `-O` or `-T`) seems like a strange design choice to me and is clearly causing confusion. I don't understand why we have to have this "legacy" mode at all -- though presumably it is/was to avoid breaking old pipelines.

This recent PR looks set to kickstart a discussion on input/output format options:
https://github.com/samtools/samtools/pull/395

**Comment by SamStudio8** [comment]
See also; #171
