### ISSUE TITLE
`samtools sort` clobbers temporary files if "misusing" `-T`

### ISSUE THREAD

**Issue by SamStudio8** [samtools/samtools#432]
Providing a duplicate prefix, or incorrectly specifying a directory for `-T` when performing simultaneous execution of `samtools sort` causes temporary files to be clobbered, leading to incorrect output and errors.

### Reproduce
Execute two sorts providing a duplicate prefix or duplicate directory path to `-T`:
```
samtools sort -m1K -O sam -T tmp/ -o output1.sam input1.sam
samtools sort -m1K -O sam -T tmp/ -o output2.sam input2.sam
```
### Result
* output1.sam contains input2.sam's header along with read groups appearing in input2.sam and potentially some from input1.sam.
* output2.sam is not created as the job aborts.

### Behaviour
* Job A begins executing, creating temporary files in `tmp/` with the name `.0000.tmp` to `.NNNN.tmp`.
* Job B begins, chasing Job A, clobbering temporary files in `tmp/` from `.0000.tmp` to `.MMMM.tmp`.
* Job A completes sorting temporary files and merges `.0000.tmp` to `.NNNN.tmp`. Thus incorrectly including read groups from Job B in place of the desired read groups from Job A where N <= M).
* Job A completes merging and deletes temporary files.
* Job B crashes attempting to read `.0000.tmp` as it no longer exists.

### Solution
* `samtools sort` should attempt to check whether a `.tmp` file exists already and either issue a sensible warning or abort.

**Comment by ghuls** [comment]
Probably the best thing to do is to use **mkstemp** to create temporary files as it ensures that they are unique:
http://unixhelp.ed.ac.uk/CGI/man-cgi?mkstemp+3

**Comment by SamStudio8** [comment]
@jkbonfield @jmarshall Is there a particular reason that a user would need/want to select their own `PREFIX` for `-T`? I presume it just makes it easier to merge the temporary files back in later (just select all files starting with `PREFIX`)?

If we used `mkstemp`, I guess we'd need to store some form of sorted structure of `char*` of temporary file names for the merge step at the end?

**Comment by jkbonfield** [comment]
On Fri, Jul 17, 2015 at 01:23:43AM -0700, Sam Nicholls wrote:
> @jkbonfield @jmarshall Is there a particular reason that a user would need/want to select their own `PREFIX` for `-T`? I presume it just makes it easier to merge the temporary files back in later (just select all files starting with `PREFIX`)?

When sorting very large files it can be useful to specify somewhere
other than /tmp as maybe /tmp isn't large enough.

However I haven't looked into the implementation details.  I'll let
John go into those as it's his code I believe (or was that just the
CLI bit?).

James

-- 
James Bonfield (jkb@sanger.ac.uk) | Hora aderat briligi. Nunc et Slythia Tova
                                  | Plurima gyrabant gymbolitare vabo;
  A Staden Package developer:     | Et Borogovorum mimzebant undique formae,
https://sf.net/projects/staden/   | Momiferique omnes exgrabure Rathi. 


-- 
 The Wellcome Trust Sanger Institute is operated by Genome Research 
 Limited, a charity registered in England with number 1021457 and a 
 company registered in England with number 2742969, whose registered 
 office is 215 Euston Road, London, NW1 2BE.

**Comment by ghuls** [comment]
> When sorting very large files it can be useful to specify somewhere other than /tmp as maybe /tmp
> isn't large enough.

If the main concern is that /tmp might not big enough, it would be nice if samtools would use **TMPDIR** (seems to be POSIX) environment variable as temp dir if it is set. Other non-POSIX operating systems might use **TEMP**, **TEMPDIR** and **TMP** instead.
https://en.wikipedia.org/wiki/TMPDIR

**Comment by SamStudio8** [comment]
Hi James,
That seems sensible, although passing just a directory to `-T` leads to the
issue at hand, the user must specify a prefix at the end of the path too to
avoid clobbering other jobs.
If I remember correctly `mkstemp` accepts a template which could easily be
preceded by both a user's desired tmp directory and even something useful
to us for grouping tmp files: `path/to/user/tmp/inputbamname.NNNNNN.tmp`.

I just wondering if there's a reason a user might want to provide the
actual prefix (rather than a path).

Sam

**Comment by ghuls** [comment]
> If I remember correctly `mkstemp` accepts a template which could easily be preceded by both a
> user's desired tmp directory and even something useful to us for grouping tmp files:
> `path/to/user/tmp/inputbamname.NNNNNN.tmp`.
mkstemp requires a template. The template needs to end with **XXXXXX**, which will be replaced with something unique.

Maybe it is better to use **mkdtemp**, which would create a subdirectory in which the temporary BAM files are placed (.0000.tmp to .NNNN.tmp), so most of the current logic can be kept and in case of failure of **samtools sort**, the user can just delete a subdirectory instead of deleting individual files.

pseudocode in bash:
```bash
output_filename='/some/path/output.sorted.bam'

if [ "${TMPDIR}" != "" ] ; then
    # Use temporary dir if TMPDIR is defined.
    tmp_sort_output_dir_template="${TMPDIR}/$(basename "${output_filename}").XXXXXX";
else
    # Create temporary dir in same dir as output file.
    tmp_sort_output_dir_template="${output_filename}.XXXXXX";
fi

# This would be a call to mkdtemp in C.
tmp_sort_output_dir=$(mktemp -d "${tmp_sort_output_dir_template}");

# Create temporary sorted files in ${tmp_sort_output_dir};
```
http://unixhelp.ed.ac.uk/CGI/man-cgi?mkdtemp+3

**Comment by SamStudio8** [comment]
I'd be happy to look at replacing the current temp handling with *mkdtemp*
as part of improving samtools sort usage (#425) if James or John think it's
better than the current `-T`.

**Comment by jmarshall** [comment]
As James noted, the historical concern was that these files are larger than the typical /tmp; in fact are of such a size that the user needs to be able to specify a bespoke location for them (as $TMPDIR is likely for "normal"-sized files too).

A pipeline author might wish to specify an actual prefix with a nonempty base filename prefix, so that (especially in the case of `samtools sort` aborting) the wrapper script can reliably delete the temporary files itself without fear of clobbering other unrelated files.  (It could do this with a directory-only non-"actual" prefix by creating a directory for each sort invocation, but then it has the additional complexity of creating and removing a directory as well.)

Fear not, @ghuls, everyone here is familiar with the POSIX functions available.

**Comment by jrandall** [comment]
It sounds like we all agree that the `-T` option is sensible. Do we also agree that it would be sensible for samtools to refuse to clobber files that already exist as @SamStudio8 suggested? 

That makes sense to me - the error message it prints in that case would be a good opportunity to advise the user that each `samtools sort` invocation should get a unique `-T` prefix to avoid collisions (although probably this could be made more clear in the docs as well).

**Comment by SamStudio8** [comment]
I think the "right" way to do this, would be for `htslib` to actually allow opening of files with a mode similar to `open`'s `O_EXCL`. [samtools/htslib#245], rather than trying to hack a clobbering check on top of `samtools sort` (and later, `samtools split` and whatever else comes to mind).

**Comment by jmarshall** [comment]
@SamStudio8: `hts_open()` now does have an exclusive mode, and _bam_sort.c_ has otherwise settled down again.  Would you like to see if using `x` to avoid this clobbering can be done with little risk to the code?

**Comment by SamStudio8** [comment]
@jmarshall This appears to work for me!

```
$ samtools sort -m1K -O sam -T tmp/ -o output1.sam test.sam
```
```
$ samtools sort -m1K -O sam -T tmp/ -o output2.sam test.sam
[bam_sort_core] merging from 154 files...
[E::hts_open_format] fail to open file 'tmp/.0000.bam'
[bam_merge_core] fail to open file tmp/.0000.bam
```

See #490

**Comment by SamStudio8** [comment]
@jmarshall Is it worth having some documentation about running simultaneous sorts/merges? Or improving the error to something more obvious - e.g. "File opened exclusively by another process/sort"

**Comment by jmarshall** [comment]
I don't think we should worry about that.  If the file is left behind by a previous aborted sort/merge, it wouldn't be true to say it's opened exclusively by another process.

`Can't write to temporary file tmp/.0000.bam: File exists` I think will do.  Which is not actually what it says now… which reminds me… sorry, I need to look at #467 before we revisit this.  Thanks, will look at that and #490 together.

**Comment by SamStudio8** [comment]
> ...it wouldn't be true to say it's opened exclusively by another process.

Ah! Yes of course. My concern was just that it might be a surprise to users that multiple simultaneous sorts and merges of files in the same directory (using the same `-T`) is potential problematic. Here at AU we do a lot of processing on BAMs that share a directory, using a job scheduler to submit them concurrently, and I know I've surprised colleagues to say "please don't do that!".

**Comment by SamStudio8** [comment]
Though I suppose this is moot now, given that `-T` defaults to something sensible now.

**Comment by plijnzaad** [comment]
I would be very much in favour of this ... for each job, our queueing system instantiates a  new RAM disks to use as $TMPDIR, for speed and for resource management.  I now have to work around this thing by wrapping all my samtools sort in a shell script that finds out the current name of $TMPDIR ...

**Comment by jmarshall** [comment]
Fixed by PR #530.

**Comment by shouldsee** [comment]
Is it safe now to do the following?

> Execute two sorts providing a duplicate prefix or duplicate directory path to `-T`:
> 
> ```
> samtools sort -m1K -O sam -T tmp/ -o output1.sam input1.sam
> samtools sort -m1K -O sam -T tmp/ -o output2.sam input2.sam
> ```
> ### Result
> * output1.sam contains input2.sam's header along with read groups appearing in input2.sam and potentially some from input1.sam.
> * output2.sam is not created as the job aborts.

**Comment by tseemann** [comment]
I use `-T tmp/output1.$$` so I know which tmp files belonged to which process (`$$` is PID) and input file (`1`)

**Comment by daviesrob** [comment]
It should be safe, as long as the directory `tmp` already exists.  Since samtools release 1.3.1, if you pass a directory (say, `tmp/`) to the `-T` option, `sort` will make temporary files with prefixes like `tmp/samtools.<pid>.<random>.tmp`, where `<pid>` is the samtools process ID and `<random>` is a random number derived from the CPU clock.

Note that it uses `stat` to find out if the `-T` option is a directory, which is why it has to exist before running `sort`.

**Comment by tseemann** [comment]
@daviesrob i did not realise that! Thanks for the clarification.
