### ISSUE TITLE
Test suite failure on 32-bit machines (floating point differences)

### ISSUE THREAD

**Issue by jmarshall** [samtools/samtools#445]
f845404614caaaf960e5219b0b7ad46b2b7d35c8 introduced a failure on 32-bit machines in the test case it changed, mpileup number 52.  The expected output, presumably generated on a 64-bit machine, contains:

> 17	2041	…VDB=0.768075…

but on lucid-dev32 this position is calculated as VDB=0.768076.

**VDB** is one of the fields that was filtered by bcf_filter.sh and by `vcf-miniview -f`… perhaps we need to be using `-f` here after all.

**Comment by jkbonfield** [comment]
Ah so **that's** what all the filtering was for. I did wonder given it appeared to work without it, although I was also hoping that we could have at least one full test that checked the entire file without having to filter lots away.  Mutter! (Arguably it's a bug to output more bits of precision than are valid.)

I guess in the interests of sanity we'll just have to remove testing of the variable fields.

**Comment by jmarshall** [comment]
>  Arguably it's a bug to output more bits of precision than are valid.

Yes.  …sigh…
