### ISSUE TITLE
Output formats option: CRAM version

### ISSUE THREAD

**Issue by tk2** [samtools/samtools#452]
samtools view -O cram,version=4.0 my.bam

outputs an error:
Unknown version string; use 1.0, 2.0, 2.1 or 3.0

but continues on writing. I guess it should be terminating on this error.

**Comment by tk2** [comment]
The CRAM that is written appears to be defaulting to v3.0. Could just append to the warning to say that the program will continue and write a CRAM 3.0.

**Comment by jkbonfield** [comment]
Fixed by https://github.com/samtools/htslib/commit/5b0bb75ca6171c67a309165c061dcdfe183e4dfe

It doesn't continue working (infact it didn't before for you either as I suspect it just gave a truncated output), but now reports an appropriate error code.
