### ISSUE TITLE
CRAM sam_itr_queryi failure: Unable to fetch reference... Failure to decode slice

### ISSUE THREAD

**Issue by ctsa** [samtools/samtools#455]
I've run into a problem which occurs for CRAM files only using the latest samtools and htslib. Specifically, over multiple calls to `sam_itr_queryi` some accumulated side-effect causes iteration over the requested regions to fail. The same code run on a BAM file works without error. The failure shows up when `sam_itr_next` is called as:

    Unable to fetch reference #1 9997..12124
    Failure to decode slice

For one example region case. A secondary problem is that I can't find a way through the official API to detect this failure: `sam_itr_next` returns -1 for both the failure case and for an empty region.

I  have reduced the failure case enough to reproduce this with a few lines of code and a cram file sliced down to about 1.5 Megs. The following commit on top of today's develop branch contains everything to reproduce it:

https://github.com/ctsa/samtools/commit/a16f09bd6f2333f5a2ffe6b529f91a6ea82083fb

Running make on this commit will build `reproduce_cram_iter_bug`, which when run will look for `reproduce_cram_iter_bug.cram` in the same directory (also part of this commit), and (hopefully) reproduce the error I see here. The CRAM slice is from NA12878.

**Comment by jkbonfield** [comment]
This is due to bizareness in the reference handling of CRAM.  It's a complex mess trying to handle local vs remote references in either fasta format or MD5 format.  There is some broken code that assumes if it's not been loaded already with the MD5 search then it is a fasta file to index and parse instead.

Unfortunately this got triggered when switching away from a file and then back again to that same file.  Fix is incoming shortly.  Thanks for the well explained bug report.

**Comment by ctsa** [comment]
Thanks for the quick patch James, I will give this a try. I found this while experimenting with CRAM support for our SV caller (https://github.com/Illumina/manta). The first phase of this operation is just like an SNV caller - parallel end-to-end genome scan, and this works very well. The second phase is a large number of these small unordered region calls to go back and look-up breakend region evidence -- this is where the above issue came from, I'll let you know if I run across anything else.

**Comment by ctsa** [comment]
Followup: we're passing all tests now using htslib: https://github.com/samtools/htslib/commit/8197cfdfa076d1c3ed5fd8428cf6c8c62c3d1d31 ...which enabled a new CRAM support release: https://github.com/Illumina/manta/releases/tag/v0.29.0

Thanks again for the help with this.
