### ISSUE TITLE
mpileup on regions for large numbers of cram files uses lots of memory

### ISSUE THREAD

**Issue by mcshane** [samtools/samtools#456]
I haven't had time to delve into further details, but is looks like the memory usage for mpileup calling on regions from many CRAM files is using an large amount of memory:

10 CRAM files: 149M
100 CRAM files: 620M
500 CRAM files: 2.5G
1000 CRAM files: 5.1G
2000 CRAM files:  10.4G

In the past I have called from a superset of these CRAM files when stored as BAM files. ~5000 BAM files in the same region used just 2.3G.

**Comment by jkbonfield** [comment]
On Wed, Aug 19, 2015 at 08:58:50AM -0700, Shane McCarthy wrote:
> I haven't had time to delve into further details, but is looks like the memory usage for mpileup calling on regions from many CRAM files is using an large amount of memory:
> 
> 10 CRAM files: 149M
> 100 CRAM files: 620M
> 500 CRAM files: 2.5G
> 1000 CRAM files: 5.1G
> 2000 CRAM files:  10.4G

Clearly it's going to be holding in memory the current cram block for
each open file.  The same is true for BGZF blocks in BAM, but BAM's
blocks are 64Kb while CRAMs are typically a couple MB when
uncompressed. A random test file showed around 2.7Mb on average, meaning
merging 2000 crams would consume 5.4G.

It's still using around double that, so there may be other
inefficiencies and ways to improve memory.  Eg freeing up the blocks
that mpileup doesn't use (auxiliary data, read names), checking
whether I have too many small mallocs and maybe using a pooled memory
allocator if so, etc.

However the only way I can see of drastically reducing memory usage is
to reduce the number of sequences per cram slice. Eg:

```./samtools view -@ 8 -C --output-fmt-option seqs_per_slice=1000 -o 9827_2#49.1k.cram /9827_2#49.cram```

A small test showed this grew the file by around 6% (and the index by
10 fold at a guess).  The optimal chunking size is unknown, but will depend on
the application.  The default of 10000 is completely arbitrary (I just
copied the default from cramtools, which itself may well have been
arbitrarily chosen).


-- 
 The Wellcome Trust Sanger Institute is operated by Genome Research 
 Limited, a charity registered in England with number 1021457 and a 
 company registered in England with number 2742969, whose registered 
 office is 215 Euston Road, London, NW1 2BE.

**Comment by jkbonfield** [comment]
I need to explore memory usage a lot more, but I did some further stats on using fewer reads per container.

```
-rw-r--r-- 1 jkb team117 6548191924 Jan 13  2014 9827_2#49.bam
-rw-r--r-- 1 jkb team117    2431088 Aug 17 11:39 9827_2#49.bam.bai
-rw-r--r-- 1 jkb team117 3513686872 Aug 19 18:12 9827_2#49.1k.cram
-rw-r--r-- 1 jkb team117     944911 Aug 20 09:20 9827_2#49.1k.cram.crai
-rw-r--r-- 1 jkb team117 3307711440 Jun  9 18:31 9827_2#49.10k.cram
-rw-r--r-- 1 jkb team117     106055 Aug 17 11:10 9827_2#49.10k.cram.crai
```

We can then use io_trace (https://github.com/jkbonfield/io_trace) to parse the strace output and see how much I/O is done per file. (Edited to remove 0 element figures, for brevity.)

```
File: 9827_2#49.bam
    Num. open           1
    Num. close          1
    Num. seeks          6
    Num. read           16
    Bytes read          416239

File: 9827_2#49.bam.bai
    Num. open           2
    Num. close          2
    Num. read           40
    Bytes read          2431088
```

Standard 10K reads per slice CRAM:

```
jkb@seq3a[scratch/data] io_trace -S -r cram -- ~/work/samtools_master/samtools/samtools view 9827_2#49.10k.cram 10:10000000-10000000 11:10000000-10000000 12:10000000-10000000 13:10000000-10000000  | egrep -v '   0$'

File: /nfs/srpipe_references/cram_cache/51/85/1ac0e1a115847ad36449b0015864
    Num. open           1
    Num. close          1
    Num. seeks          1
    Num. read           9
    Bytes read          557056

File: /nfs/srpipe_references/cram_cache/98/c5/9049a2df285c76ffb1c6db8f8b96
    Num. open           1
    Num. close          1
    Num. seeks          1
    Num. read           10
    Bytes read          622592

File: 9827_2#49.10k.cram.crai
    Num. open           2
    Num. close          2
    Num. read           4
    Bytes read          106055

File: /nfs/srpipe_references/cram_cache/98/8c/28e000e84c26d552359af1ea2e1d
    Num. open           1
    Num. close          1
    Num. seeks          1
    Num. read           9
    Bytes read          557056

File: 9827_2#49.10k.cram
    Num. open           1
    Num. close          1
    Num. seeks          4
    Num. read           24
    Bytes read          2390817
```

And the new 1K reads per container CRAM:

```
jkb@seq3a[scratch/data] io_trace -S -r cram -- ~/work/samtools_master/samtools/samtools view 9827_2#49.1k.cram 10:10000000-10000000 11:10000000-10000000 12:10000000-10000000 13:10000000-10000000  | egrep -v '    0$'

File: /nfs/srpipe_references/cram_cache/51/85/1ac0e1a115847ad36449b0015864
    Num. open           1
    Num. close          1
    Num. seeks          1
    Num. read           2
    Bytes read          98304

File: /nfs/srpipe_references/cram_cache/98/c5/9049a2df285c76ffb1c6db8f8b96
    Num. open           1
    Num. close          1
    Num. seeks          1
    Num. read           2
    Bytes read          98304

File: /nfs/srpipe_references/cram_cache/98/8c/28e000e84c26d552359af1ea2e1d
    Num. open           1
    Num. close          1
    Num. seeks          1
    Num. read           2
    Bytes read          98304

File: 9827_2#49.1k.cram.crai
    Num. open           2
    Num. close          2
    Num. read           17
    Bytes read          944911

File: 9827_2#49.1k.cram
    Num. open           1
    Num. close          1
    Num. seeks          4
    Num. read           13
    Bytes read          396426
```

As you can see the total number of bytes read goes from 4.2MB down to 1.6MB (including reference), vs 2.8MB for BAM.  That won't directly be equivalent to memory usage as there is uncompression etc and maybe more complex data structures, but it's worth investigating.

Do you have some public data somewhere for me to check merge/mpileup memory usage?

Thanks.

**Comment by mcshane** [comment]
>Do you have some public data somewhere for me to check merge/mpileup memory usage?

I'll email you off github.

**Comment by jkbonfield** [comment]
I've locally made some changes and can see how to reduce the memory a bit.  On my own test set of 1000 copies of 9827_2#49.cram memory has dropped from 7916 to 5109Mb.  It's still high, but that's mostly down to having 10,000 reads per slice.  Maybe with more cunning some of it could be culled (do we really need 638Mb of aux data? likely most of it isn't used by mpileup, nor is the 425Mb worth of read names), but it's a considerable amount of extra complexity.

With 1,000 reads per slice the memory drops to 962Mb which is very manageable.  I can maybe drop it some more still.

The big problem I have left to solve is how the reference handling works.  I need to hoist some of that code out of the file descriptors and into a global cache.  Right now it can't share references between open file descriptors (except via mmap which shows up as huge virtual memory as the same file is mmaped many times).  That may be complex, but I'll investigate further.

**Comment by jkbonfield** [comment]
See https://github.com/samtools/htslib/commit/6d2810cdbbbe4646dcf7a4fab1003aa99319c55a for a starting point on this.  It saves approx 50% of memory usage on my test data, but I haven't been able to try it on your data.

Note there are still some improvements that could be made with regards to reference handling, but these may not have a significant memory change.
