### ISSUE TITLE
Colorblind-friendlier output for tview

### ISSUE THREAD

**Issue by pjvandehaar** [samtools/samtools#457]
Many colorblind users can see the colors used in tview, but not when they are on so few pixels at a time.

Could you add an option to tview to color the background instead of the foreground?

**Comment by mp15** [comment]
That's an excellent idea, thank you. We will have a look into this.

**Comment by dlaehnemann** [comment]
In case you're searching for good palettes to use, ColorBrewer has a 
bunch of palettes and an option to restrict your search to color-blind 
friendly palettes. Although there aren't too many palettes for diverging 
colors, but have a quick look yourself:
http://colorbrewer2.org/

cheers,
david

On 24.08.2015 15:27, Martin Pollard wrote:
> That's an excellent idea, thank you. We will have a look into this.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/samtools/samtools/issues/457#issuecomment-134200359>.
>

-- 
David Laehnemann
Algorithmic Bioinformatics
University of Duesseldorf
Building 25.12
Room 01.50

+49 - (0)2 11 - 8 11 26 44

**Comment by jkbonfield** [comment]
Unfortunately we can't pick arbitrary colours.  We have to pick from the supported terminal colour codes: http://ascii-table.com/ansi-escape-sequences.php

However, I am colourblind and have issues with the current colours (particularly the yellow/greens), so I'll experiment and see if I can get something better.

**Comment by jkbonfield** [comment]
Do we want this to be editable?   On an example set the existing code in nucleotide non-dot mode is:

![screenshot-untitled window-1](https://cloud.githubusercontent.com/assets/2210525/9445464/33ee35b6-4a84-11e5-8fa3-549e11bd0048.png)

With (IMO) improved colours to avoid yellow/green conflicts it looks like:

![screenshot-untitled window-2](https://cloud.githubusercontent.com/assets/2210525/9445476/492e27ba-4a84-11e5-9d5d-b4d4599f04e0.png)

And with a new inverse video mode (press "v") it looks like:

![screenshot-untitled window-3](https://cloud.githubusercontent.com/assets/2210525/9445487/544397a2-4a84-11e5-81ae-f41dd9bac026.png)

I can make these adjustable by an environment variable, although it's quite foul encoding. Eg:

```SAMTOOLS_TVIEW_COLOUR=402030702060501040/740203070206757174 ./samtools tview -p 1:10050  ~/scratch/data/9827_2#49.bam```

Suggestions?

**Comment by pjvandehaar** [comment]
Great work!  For me, your second view is an improvement and the third view is perfect.

**Comment by dlaehnemann** [comment]
Even without any color-blindness I very much like the third view with 
its clean columns and being able to toggle back and forth with v is 
probably also a good idea -- who knows who prefers which view for what.
