### ISSUE TITLE
Can you host Bio::DB::SAM here too?

### ISSUE THREAD

**Issue by dbolser-ebi** [samtools/samtools#458]
Not sure where it's hosted but...

**Comment by jmarshall** [comment]
It's part of [GMOD/GBrowse-Adaptors](https://github.com/GMOD/GBrowse-Adaptors).  Just as [Pysam](https://github.com/pysam-developers/pysam/issues) is elsewhere, I'm not sure that there would be much to gain from hosting it here.  At present _C code here, other language bindings (with, naturally, other authors) elsewhere_ is a pretty good division of labour.

Anyway, it's @lstein's baby and his to locate as he will.  Certainly we should have better links to it and pysam on our web pages; and it's more than about time I looked again at his htslib-using **samtools-1.1** branch and the work your EBI colleagues are doing in this area.

**Comment by dbolser-ebi** [comment]
Many thanks for the clear reply John, if it's already hosted on GitHub, that's perfect. I just couldn't find it after a short search. htslib? How did you guess ;-)

From my naive understanding of C bindings in Perl, is this a question of 'plumbing' or is it structurally deeper than that? ... And is this the right place to pick up the discussion?

Cheers,
