### ISSUE TITLE
have samtools 'make install' also install tabix and bgzip

### ISSUE THREAD

**Issue by bw2** [samtools/samtools#462]
Can samtools make install just run `make install` on htslib?

**Comment by jmarshall** [comment]
Having samtools `make install` do this itself wouldn't be ideal, as if you were also compiling and installing htslib separately then the two would conflict.

However you are right that it should be easier than what _INSTALL_ currently suggests.  I had forgotten that _htslib.mk_ provides samtools with an `install-htslib` target that just about does the trick.  So I've added the missing link and updated the instructions to recommend `make install-htslib` essentially.  They're still fairly opaque instructions, but I think that can be improved with an eventual rewrite in the style of htslib's _INSTALL_.

Thanks for bringing this up!
