### ISSUE TITLE
Samtools view pipe + position

### ISSUE THREAD

**Issue by kaktus42** [samtools/samtools#468]
following unexpected error and comparison without error.

```
$ samtools merge -u -b all_files.list - | samtools view -u -q 20 -F 0x704 - "1:1-10000" > /dev/null
[main_samview] random alignment retrieval only works for indexed BAM or CRAM files.

$ samtools merge -u -b all_files.list - | samtools view -u -q 20 -F 0x704 - > /dev/null
```

samtools seems to interpret the position string as a file.

Version: 1.2 (using htslib 1.2.1)

**Comment by jmarshall** [comment]
The error message is telling you that specifying a region as an argument (`1:1-10000`) requires the file to be indexed, and standard input (`-`) is not indexed.  In particular, the file that the message is referring to is `-`, not the position string.

Doing what you want on a non-indexed input file is less efficient, as you need to scan through the whole file.  You could for example do what you want by constructing a BED file representing 1:1-10000 and using `samtools view -L`.
