### ISSUE TITLE
samtools faidx returns an incorrect result when two sequences have the same ID

### ISSUE THREAD

**Issue by sjackman** [samtools/samtools#474]
In the output below, the result of `samtools faidx bar.fa` is incorrect. It reports that the length of the first sequence is 8 nucleotides, when in fact it is 4.

```
❯❯❯ head foo.fa bar.fa
==> foo.fa <==
>1
ACGT
>2
ACGTACGT

==> bar.fa <==
>1
ACGT
>1
ACGTACGT
❯❯❯ samtools faidx foo.fa
❯❯❯ samtools faidx bar.fa
❯❯❯ head foo.fa.fai bar.fa.fai
==> foo.fa.fai <==
1	4	3	4	5
2	8	11	8	9

==> bar.fa.fai <==
1	8	11	8	9
1	8	11	8	9
❯❯❯ samtools --version
samtools 1.2
Using htslib 1.2
Copyright (C) 2015 Genome Research Ltd.
```

**Comment by mcshane** [comment]
I think this was solved in #380? Would be in 1.3 whenever that surfaces.

**Comment by sjackman** [comment]
Glad to hear it. Thanks, Shane.

**Comment by jmarshall** [comment]
Duplicate indeed, already fixed by samtools/htslib@4854ee6688593c6d66f2886af1f878c1c855fc92.  Re _one heck of a nasty samtools bug_, I'm not sure what you were expecting given the garbage-in nature of duplicate sequence names.  Which sequence were you expecting subsequent requests for `1:1-4` etc to return?

**Comment by sjackman** [comment]
Hi, John. The nasty samtools bug is that it silently produced an incoherent index file. Garbage-in should produce error out.

**Comment by jmarshall** [comment]
No, a _nasty_ bug is when it produces erroneous output for reasonable input.  This is a minor infelicity that's already been fixed; you're welcome.
