### ISSUE TITLE
samtools merge fails with [trans_tbl_add_hd] No @HD tag found.

### ISSUE THREAD

**Issue by peterjc** [samtools/samtools#475]
Older versions of samtools would happily merge BAM files with no ``@HD`` header line, new versions on the ``develop`` branch fail:

```
$ ./samtools --version
samtools 1.2-216-gdffc67f
Using htslib 1.2.1-217-g66fbb28
Copyright (C) 2015 Genome Research Ltd.
$ ./samtools merge -f out.bam examples/toy.sam examples/toy.sam
[trans_tbl_add_hd] No @HD tag found.
```

Using BAM for comparison, since older versions of merge only allowed BAM input:

```
$ ./samtools view -b -S examples/toy.sam > toy.bam
$ ./samtools merge -f out.bam toy.bam toy.bam
[trans_tbl_add_hd] No @HD tag found.
```

Testing with 1.2 (*edit:* and 1.2.1) works:

```
$ ./samtools --version
samtools 1.2
Using htslib 1.2
Copyright (C) 2015 Genome Research Ltd.
$ ./samtools merge -f out.bam examples/toy.sam examples/toy.sam
$ ./samtools merge -f out.bam toy.bam toy.bam
```

Using v1.0 and v1.1 only BAM inputs works,

```
$ ./samtools --version
samtools 1.1
Using htslib 1.1
Copyright (C) 2014 Genome Research Ltd.
$ ./samtools merge -f out.bam examples/toy.sam examples/toy.sam 
[sam_bam_cram_readrec] Not implemented for SAM files -- Exiting
Abort trap: 6
$ ./samtools view -b -S examples/toy.sam > toy.bam
$ ./samtools merge -f out.bam toy.bam toy.bam
```

Stepping back to the pre-htslib version 0.1.19 again this works.

I believe this is a regression from https://github.com/samtools/samtools/commit/858b0e7c73494d9273e23c41c2ec8628a9fd85df which introduced the new error message ``[trans_tbl_add_hd] No @HD tag found.``

CC @daviesrob

**Comment by daviesrob** [comment]
Actually, this appeared in 55c852fc17cd37a38751aa396644e7c62f94fb43, so I'm blaming @mp15 for this one :smiley:.

It doesn't look too difficult to make it put in a minimal @HD if it doesn't find one.  I'll roll up a pull request for it, at least as a starting point for discussion.

**Comment by mp15** [comment]
Aye, I guess we can say SO:coordinate (unless explicitly told it is name sorted) and VN:1.5. Completely unsorted files make little sense in the context of samtools merge, they should be processed with samtools cat. Also perhaps we should add translation to samtools cat?

**Comment by jkbonfield** [comment]
On Wed, Oct 07, 2015 at 04:31:54AM -0700, Martin Pollard wrote:
> Aye, I guess we can say SO:coordinate (unless explicitly told it is
> name sorted) and VN:1.5. Completely unsorted files make little sense
> in the context of samtools merge, they should be processed with
> samtools cat. Also perhaps we should add translation to samtools cat? 

I'm wary of making up a header where one doesn't exist.  We don't know
what version of the specification the data conforms to.

Are version numbers strictly backwards compatible, so 1.5 permits
everything 1.3 did and more (in which case it's fine to just make up
the version number), or are there potential changes in meaning?

Agreed that merge isn't going to work on non-coordinate sorted data so
that's one assumption that is valid.


-- 
 The Wellcome Trust Sanger Institute is operated by Genome Research 
 Limited, a charity registered in England with number 1021457 and a 
 company registered in England with number 2742969, whose registered 
 office is 215 Euston Road, London, NW1 2BE.

**Comment by peterjc** [comment]
Apologies for flagging the merge commit rather than the actual commit with the new code, but glad you've pin-pointed this.

My example here just used the first SAM/BAM file I could find in the samtools repository without an ``@HD`` line to use as a test case - I was not thinking about the read order.

**Comment by daviesrob** [comment]
On reflection, I think I'll put in a place-holder for where the header could be added if we decide to put one in.  I can't find an easy way at the moment to work out what the highest version of SAM we support is, unfortunately.

Including the header is just one line, so it's easy to slot in later.

There are a couple of places in samtools where `@HD` lines are created.  One in bam_sort.c says `VN:1.3`, one in dict.c says `VN:1.0`.  So it looks at the moment that they get fossilized to the current version when the code was written, which is not ideal.

**Comment by jmarshall** [comment]
See also discussion in #390.
