### ISSUE TITLE
A question about -l :

### ISSUE THREAD

**Issue by WinterLi1993** [samtools/samtools#479]
Dear professor:

In samtools mpileup : 
-l FILE      list of positions (chr pos) or regions (BED) [null] 

I do not know which list should I use ?   Now I am doing Whole exome sequencing about cancer research, I have a tumor bam and a normal bam.

I need convert into pileup format,use the below command : 
samtools mpileup –l  ?  -f hg18.fasta Normal.cleaned.bam >Normal.pileup

but  I do know -l means what ?  is SeqCapExomeRegion.bed ???

**Comment by mp15** [comment]
If you just want data from the pulldown region yes, -l just tells samtools to restrict it's calling to reads covering the regions specified. What exactly you put here does depends on what you did in the lab, and therefore how far off baits you're expecting to get a signal. With Agilent V5 for example I tend to go ±100bp from targets. I would also note that hg18 is a very old reference and most of the modern resources are mapped to later references like GRCh37 (hg19).

**Comment by WinterLi1993** [comment]
got it ,thank you !
