### ISSUE TITLE
Error in converting SAM to BAM

### ISSUE THREAD

**Issue by stegg** [samtools/samtools#487]
Hi, I am a novice user with NGS data processing.I have a problem in converting SAM to BAM with samtools.
Background: 
Trim: using trimmomatic-0.32.jar to treat a pair of  pair-end fq files 
Index: using bwa index to construct bwa.
SAM generation: using bwa mem to directly generate the sam file without using .sai file.
Sam reordering: using picard-tools-1.96/ReorderSam.jar to reorder the sam file.
Result:
When i use the samtools view -bS to convert the .sam file to .bam file, i received the following:

[W::sam_read1] parse error at line 115160780
[main_samview] truncated file.
I have extracted the line 115160780 of my .sam file.
"ST-E00144:107:HF52VCCXX:8:2223:32323:33217	147	LK032016.1	790695	21	76M	=	790472	-299	TATTTGGATACATAAAGTGGTGGAGAATCACTAGGAAGTTGAATAAGTCTCATAGGAGTTGGG"

I doubt whether the problem is the information of this line is not complete?Can i solve this problem by remove this line.And how can i this problem？

**Comment by SamStudio8** [comment]
Hi @stegg, are you sure BWA didn't terminate early?
Could you try validating the SAM with `Picard ValidateSam` to ensure it is intact.

**Comment by jmarshall** [comment]
Please retest and reopen if problem persists.

**Comment by skr3178** [comment]
I face same issue when running this tutorial
https://github.com/fenderglass/jax-meta-tutorial
`minimap2 -ax map-hifi assembly_graph.fasta SRR13128014_1gb.fastq.gz -t 30 | samtools sort > graph_alignment.bam
samtools index graph_alignment.bam`


![image](https://user-images.githubusercontent.com/79299617/199446658-11f303a8-8966-4793-90bf-427f5d436473.png)

**Comment by jkbonfield** [comment]
I'm not sure what your image is trying to show, but it's malformed data.  Maybe your aligner failed.

Regardless, this github is for reporting bugs and suggesting improvements.  For general bioinformatics queries you are more likely to get a response from things like BioStars,
