### ISSUE TITLE
mpileup.1.sam and possibly others are invalid

### ISSUE THREAD

**Issue by mp15** [samtools/samtools#489]
They reference hs37d5 in their body but not in the header.

**Comment by jmarshall** [comment]
These are indeed invalid (§1.4/3, _If @SQ header lines are present, RNAME (if not ‘*’) must be present in one of the SQ-SN tag_, and similar text in §1.4/7 for RNEXT).

When reading a SAM file with an unknown sequence name in the RNAME column, current htslib says

> [W::sam_parse1] urecognized reference name; treated as unmapped

and standalone samtools said equivalently but rather opaquely

> [sam_read1] reference 'foo' is recognized as '*'.

When the unknown sequence name is in the RNEXT column, both treat it as unmapped without a diagnostic.
