### ISSUE TITLE
undefined reference to `gzopen64' when compiling

### ISSUE THREAD

**Issue by kdaily** [samtools/samtools#493]
When compiling the latest release (1.2) I'm getting the following:

```
gcc -pthread  -o samtools bam_index.o bam_plcmd.o sam_view.o bam_cat.o bam_md.o bam_reheader.o bam_sort.o bedidx.o kprobaln.o bam_rmdup.o bam_rmdupse.o bam_mate.o bam_stat.o bam_color.o bamtk.o bam2bcf.o bam2bcf_indel.o errmod.o sample.o cut_target.o phase.o bam2depth.o padding.o bedcov.o bamshuf.o faidx.o stats.o stats_isize.o bam_flags.o bam_split.o bam_tview.o bam_tview_curses.o bam_tview_html.o bam_lpileup.o libbam.a htslib-1.2.1/libhts.a  -lcurses  -lm -lz
bedidx.o: In function `bed_read':
/root/src/samtools-1.2/bedidx.c:170: undefined reference to `gzopen64'
phase.o: In function `loadpos':
/root/src/samtools-1.2/phase.c:507: undefined reference to `gzopen64'
bedcov.o: In function `main_bedcov':
/root/src/samtools-1.2/bedcov.c:98: undefined reference to `gzopen64'
collect2: ld returned 1 exit status
make: *** [samtools] Error 1
```

I'm on CentOS 6.7 and have `zlib` and `zlib-devel` installed from the yum package repository (1.2.3).

**Comment by kdaily** [comment]
Sorry, didn't see this thread:

http://sourceforge.net/p/samtools/mailman/message/25012431/

Any suggestions on getting a newer version of zlib? The entire system depends on the package-manager installed version (which is not 1.2.3.3).

**Comment by jmarshall** [comment]
As in that mailing list thread, you need to figure out where bedidx.c etc are seeing _gzopen**64**()_, which you can do with `gcc -H` to see exactly which zlib headers are being used.  You should then correlate that with which _libz.a/.so_ is being used, at which point probably the problem on your local machine will be apparent.

**Comment by jmarshall** [comment]
Please reopen and comment here if this is still an issue.

**Comment by farshadf** [comment]
Hi,
I still cannot get past this point. zlib is installed and is available through PATH. The error message says:
```
gcc -pthread -rdynamic   -o samtools bam_index.o bam_plcmd.o sam_view.o bam_cat.o bam_md.o bam_reheader.o bam_sort.o bedidx.o kprobaln.o bam_rmdup.o bam_rmdupse.o bam_mate.o bam_stat.o bam_color.o bamtk.o bam2bcf.o bam2bcf_indel.o errmod.o sample.o sam_opts.o cut_target.o phase.o bam2depth.o padding.o bedcov.o bamshuf.o faidx.o dict.o stats.o stats_isize.o bam_flags.o bam_split.o bam_tview.o bam_tview_curses.o bam_tview_html.o bam_lpileup.o bam_quickcheck.o bam_addrprg.o libbam.a htslib-1.3/libhts.a -lncursesw -lm -lz -ldl
bedidx.o: In function `bed_read':
bedidx.c:(.text+0x1481): undefined reference to `gzopen64'
phase.o: In function `main_phase':
phase.c:(.text+0x3cfb): undefined reference to `gzopen64'
bedcov.o: In function `main_bedcov':
bedcov.c:(.text+0x319): undefined reference to `gzopen64'
dict.o: In function `dict_main':
dict.c:(.text+0x59c): undefined reference to `gzopen64'
collect2: error: ld returned 1 exit status
```

Is there any easy way to get past this error? Thank you

**Comment by mattsmithau** [comment]
Was getting this error trying to build a program called LRSIM.  Here is what I had to do to make it build:

It didn't want to use our custom samtools but had its own to build against.  It didn't want to use our zlib properly.   Had to go into the Makefiles in the src folder and change the line to point directly at our zlib in the CFLAGS line:

pwd
/tools/lrsim-1/DWGSIMSrc

cd into DWGSIMSrc
ls
dwgsim  dwgsim_eval  INSTALL  LICENSE  Makefile  README  samtools  scripts  src
cd into samtools
modified this line in the Makefile:
CFLAGS=  -g -Wall $(VERSION) -O2 -L /tools/hpclib/zlib-1.2.8/lib
make  and it built this samtools
cd ..
went into that Makefile and did the same thing
make and it built the binaries: dwgsim  dwgsim_eval
cd ..
ls
4M-with-alts-february-2016.txt  clean.sh  DWGSIMSrc     extractReads.cpp  _Inline  LICENSE  msort     README.md  simulateLinkedReads.pl  SURVIVORSrc
clean                           dwgsim    extractReads  faFilter.pl       lib      make.sh  msortSrc  samtools   SURVIVOR                test

Then ran the:  sh make.sh and it built proper

This was for this program on a centos 6.6 machine.

https://github.com/aquaskyline/LRSIM

Hope that helps someone.
