### ISSUE TITLE
Support sequence synonyms in SAM specification?

### ISSUE THREAD

**Issue by dbolser-ebi** [samtools/samtools#501]
Hi,

I think allowing sequence name synonyms in the header would be a good addition. i.e. querying a BAM for 1 or chr1 or Chr1 or 01 or Chromosome-1 could all return results if that list of synonyms were provided. In an ideal world everyone would use INSDC accessions, but unfortunately that isn't where we live.

**Comment by jmarshall** [comment]
This is samtools/hts-specs#100.  I suppose samtools could consider implementing something ahead of the spec to provide experience with some existing practice to standardise…

> In an ideal world everyone would use INSDC accessions

Very funny.

**Comment by dbolser-ebi** [comment]
"Before we can create an ideal world, we have to imagine one" -- Hearty
White.

**Comment by jmarshall** [comment]
This was implemented by samtools/htslib#931 and appeared in 1.10.
