### ISSUE TITLE
weird characters of sort sub-command man in some computers

### ISSUE THREAD

**Issue by lpantano** [samtools/samtools#511]
Hi,

It is a very weird error, and not affecting everything, so I am aware that maybe it's not deserved a lot of time.

We were using `samtools sort` command to check if the command was accepting `-@` paramenter in our pipeline. After version 1.3 I am having problems with this only in the compute nodes of harvard medical school cluster.

I get the following as the output of that command: `^_<8B>^H^D^@^@^@^@^@<FF>^F^@BC^B^@?^@sr<F4>e<94>d``p<F0>p<E1>^L<F3><B3>2<D4>3<E6>^L<F6><B7>J<CE><CF>/J<C9><CC>K,I<E5>^B<CA>1^@^@<D1><E7>˾%^@^@^@^_<8B>^H^D^@^@^@^@^@<FF>^F^@BC^B^@ESC^@^C^@^@^@^@^@^@^@^@^@`

But it works at expected in the login node and interactive jobs. I am working with them to fix it, but since for previous versions it was ok, I was wondering what I can look for or change to fix that. Or if any ones knows something.

thanks in advance.

**Comment by lpantano** [comment]
Just as a comment. If I add any other thing to the command like `samtools sort -O BAM` or `-h` it will print it ok.

**Comment by jmarshall** [comment]
Samtools's `sort` command now writes to standard output by default.  The output you are seeing is the BAM-formatted sorted output.  (See the release notes and man page.)  Use `-o FILE` to write the output to a file.

What is the complete command line (including options) that you are using here?

**Comment by lpantano** [comment]
oh yeah, i know that. That is the complete command line. Let me know explain again. If I send i job only with the following command:

`samtools sort` 

I get a bunch of weird characters instead of the usage message. In my computer or login nodes of the cluster I get this (like expected):

```
Usage: samtools sort [options...] [in.bam]
Options:
  -l INT     Set compression level, from 0 (uncompressed) to 9 (best)
  -m INT     Set maximum memory per thread; suffix K/M/G recognized [768M]
  -n         Sort by read name
  -o FILE    Write final output to FILE rather than standard output
  -T PREFIX  Write temporary files to PREFIX.nnnn.bam
  -@, --threads INT
             Set number of sorting and compression threads [1]
      --input-fmt-option OPT[=VAL]
               Specify a single input file format option in the form
               of OPTION or OPTION=VALUE
  -O, --output-fmt FORMAT[,OPT[=VAL]]...
               Specify output format (SAM, BAM, CRAM)
      --output-fmt-option OPT[=VAL]
               Specify a single output file format option in the form
               of OPTION or OPTION=VALUE
      --reference FILE
               Reference sequence FASTA FILE [null]
```

what is the expected. 

So I am not trying to run the sort command with  bam files or anything. I just want to get the usage message. but If I add any other option to samtools sort like `samtools sort -h` it will print the usage message correctly (telling of course the `-h` doesn't exists).

We were doing that to know if the samtools that the user has, was allowing threads and differentiate from previous version. So we were just executing from python `samtools sort` to get the usage message and find "@" parameter. This stopped working with version 1.3 and only in the compute nodes of the clusters, so for sure the compute nodes have something different than the login nodes. I am trying to find what.

It just that it is weird to me that the output `samtools sort` command are binary characters instead of the usage message in plain text in some computers and only from version 1.3.

thanks for your time.

**Comment by jmarshall** [comment]
In your non-interactive compute node environment, `samtools sort` reads from standard input, sorts, and writes to standard output.  (Plain `samtools sort` only displays the usage if standard input has not been redirected from an input file, which is approximated by "stdin is a terminal".)

I suggest you use `samtools --version` and/or `samtools sort -@5 /dev/null > /dev/null` to determine whether sort has a `-@` option.  Or you could use `samtools sort --help` which will at the moment output usage to standard error, and in future we may implement a `--help` option here which would send usage to standard output instead.  (So you may actually want `samtools sort --help 2>&1`.)

**Comment by lpantano** [comment]
you are awesome! thanks so much!

sent not from my computer
