### ISSUE TITLE
samtools sort command line options inconsistent with usage

### ISSUE THREAD

**Issue by balwierz** [samtools/samtools#514]
```
$ samtools sort foo.bam -o bar.bam --output-fmt BAM
Usage: samtools sort [options...] [in.bam]
Options:
  -l INT     Set compression level, from 0 (uncompressed) to 9 (best)
  -m INT     Set maximum memory per thread; suffix K/M/G recognized [768M]
  -n         Sort by read name
  -o FILE    Write final output to FILE rather than standard output
  -T PREFIX  Write temporary files to PREFIX.nnnn.bam
  -@, --threads INT
             Set number of sorting and compression threads [1]
      --input-fmt-option OPT[=VAL]
               Specify a single input file format option in the form
               of OPTION or OPTION=VALUE
  -O, --output-fmt FORMAT[,OPT[=VAL]]...
               Specify output format (SAM, BAM, CRAM)
      --output-fmt-option OPT[=VAL]
               Specify a single output file format option in the form
               of OPTION or OPTION=VALUE
      --reference FILE
               Reference sequence FASTA FILE [null]
```
The versions are as follows:
```
$ samtools --version
samtools 1.3
Using htslib 1.3
Copyright (C) 2015 Genome Research Ltd.
```

PS. I am annoyed by the constant change of command line options.

**Comment by jmarshall** [comment]
The problem here is that the description of `--output-fmt` in the usage lists the names of the formats (SAM/BAM/CRAM), but the actual values needed for the option argument are `sam`, `bam`, or `cram` in lower case.  This is described correctly in the [manual page](http://www.htslib.org/doc/samtools.html), but needs clarifying in the usage display.

FYI there has been **one** change in sort's command line options in 2.5 years (i.e., since the release of 0.1.19), and the old-style options continued to be accepted for over a year.

**Comment by tpibob** [comment]
Robert@DESKTOP-14EL82S /usr/local/bin/samtools-1.3
$  samtools sort -o -O 4006-288319-Hawthorn.bam
[bam_sort_core] merging from 8 files...
Robert@DESKTOP-14EL82S /usr/local/bin/samtools-1.3

creates temp files in same folder and .bam and samtools are contained.

my problem is I can't find the output

anyone any ideas

not in cygwin64/home

**Comment by SamStudio8** [comment]
@tpibob That command will create an output file named `-O`. You need to provide a name to `-o` as per the documentation:
```
  -o FILE    Write final output to FILE rather than standard output
```
You've also used `-O` without specifying a format, which should default to the same as the input (BAM in your case). Consider:
```
$ samtools sort -o myout.bam 4006-288319-Hawthorn.bam
```

**Comment by tpibob** [comment]
Sam
Thats the bit I wanted and the outfile ended where I thought it should right alongside the infile

Thanks

 Bob May
DNA Projects I2b L415, I2c L596 HG, Spriggs of Cleve SA Family & Tyler Surname and ISOGG YTree

Date: Sat, 30 Jan 2016 19:58:19 -0800

**Comment by kemin711** [comment]
Just need to confirm the input file format.  It seems that samtools sort can take input.sam, input.bam, or input.cram  The tool help only dislay in.bam

```
samtools sort
Usage: samtools sort [options...] [in.bam]
```
The man page seems to be more comprehensive

```
man samtools  sort     
 samtools sort [-l level] [-m maxMem] [-o out.bam] [-O format] [-n] [-t tag] [-T tmpprefix] [-@ threads] [in.sam|in.bam|in.cram]
```
It might be better to put the in.sam and in.cram in the STDOUT display.  Most users don't even know how to type man page.
