### ISSUE TITLE
fastq/a samtools COMMAND ERROR FAULT

### ISSUE THREAD

**Issue by tpibob** [samtools/samtools#518]
fastq/a
samtools fastq [options] in.bam 
samtools fasta [options] in.bam
Converts a BAM or CRAM into either FASTQ or FASTA format depending on the command invoked.

using (-0 (ZERO)) (fa or fai)
samtools fasta -n -0 out.fa in bam

what I get is the fa and fai files created in the folder wint 0 KB and the results printed to the screen

any ideas

Bob

**Comment by jmarshall** [comment]
From the manual page:
>   **-0 FILE** Write reads with both or neither of the BAM_READ1 and BAM_READ2  flags  set  to  FILE instead of outputting them.

Having both or neither of these flags set is unusual in paired-end sequencing, so presumably none of your reads are in this category, and all reads have gone to standard output which is the default.  So this is functioning as expected.

Many problems like this with using these tools are probably easier to solve by posting to the [samtools-help mailing list](https://lists.sourceforge.net/lists/listinfo/samtools-help), where lots of people can help you and the solutions will be seen by many.  Oftentimes there is not an actual bug in the program, so it would be more helpful to discuss the problem on the mailing list before filing an issue here.  Thanks.
