### ISSUE TITLE
samtools bam2fq skipped some reads in bam file

### ISSUE THREAD

**Issue by haiwangyang** [samtools/samtools#522]
Hi,

I tested the samtools bam2fq and found something I cannot understand

samtools bam2fq sorted.bam -s sorted.fastq
The sorted.bam has 21105 reads, but the sorted.fastq have 21104
One read exist in the bam file but absent in the fastq

I also proved that bedtools it works:
samtools view -bS sorted.bam | bedtools bamtofastq -i /dev/stdin -fq /dev/stdout | wc
21105

The tested sorted.bam can be found here:
ftp://helix.nih.gov/pub/haiwangyang/sorted.bam

Look forward to your reply. Thanks!

Haiwang
National Institutes of Health
build 50, room 3343,
9000 Rockville Pike, 
Bethesda, MD, 20814
301-594-1411
haiwang.yang@nih.gov

**Comment by jmarshall** [comment]
The samtools **fastq** aka **bam2fq** command always discards alignments with the secondary or supplemental flags set.  (@mp15 I believe the man page doesn't mention this, which needs fixing.)

Your file has one secondary read, `SN398:452:C7VUWACXX:5:2109:9603:96673`, which is not making it to samtools's output.

**Comment by haiwangyang** [comment]
Got it and thanks for the explanation
