### ISSUE TITLE
Default samtools sort temp-prefix leads to data corruption when reading from stdin

### ISSUE THREAD

**Issue by holgerbrandl** [samtools/samtools#523]
Usually I like to pipe alignments until I have a sorted bam file. Like this:
``` 
bwa mem ${assembly} ${fastqFile} | samtools view -bSF 4 - | samtools sort -o ${outputBase}.bam -
```

However with v1.3 this fails when creating multiple bam files in the same directory, because samtools sort seems to use the input file name '-' as PREFIX for the temporary files.  So different parallel samtools instances run into conflict with each other since all temporary files are named
```
-.tmp.0001.bam
-.tmp.0002.bam
-.tmp.0003.bam
```

Imho in case of - as input, samtools should rather use the output name (-o) as prefix or if this one is not defined either (and the users just want to write to stdout) `sort` should require the user to specify a prefix with -T.

I think to recall that this was working correctly with earlier versions of samtools.

**Comment by jmarshall** [comment]
I think this worked correctly with earlier versions by virtue of them always insisting on a prefix being specified?

Anyway, yes this needs improving and I want to revisit the way these temporary filenames get invented, along with #432 and #490.  Perhaps when the input file is `-` or omitted (or even always), it should be adding some `tmpnam()`-style stuff to the temporary filenames.

**Comment by jrandall** [comment]
@jmarshall I'd vote for this being P1 (and possibly a candidate for a 1.3.x point release) as it has the potential to silently corrupt the data and result in bad science.

**Comment by jkbonfield** [comment]
Agreed @jrandall, and indeed I just fell into that very same category and arrived at incorrect conclusions after my experiments this morning.

Hence there's now a partial fix - partial as it spots the error, but doesn't automatically pick unique filenames for you.
