### ISSUE TITLE
Installing headers and libbam.a

### ISSUE THREAD

**Issue by outpaddling** [samtools/samtools#531]
Would you consider adding libbam.a and header files to the install target?

I'm developing packages that depend on samtools and some of them depend on the headers and libraries.  Using bundled dependencies is considered bad form in package development.

Thanks,

    Jason

**Comment by mp15** [comment]
Which bits of samtools are you after? If you can make a sane argument for a specific part we could shift some more of the APIs to htslib. I suspect we'd be hesitant about encouraging future use of samtools as a library unless it was with the understanding that we will break the interfaces a lot.

**Comment by outpaddling** [comment]
Not sure you'd call it "sane", but RSEM (http://deweylab.github.io/RSEM/) uses a bundled samtools 1.3 and relies on libbam.a, sam.h, and bam.h.

From the RSEM Makefile:

SAMTOOLS = samtools-1.3
HTSLIB = htslib-1.3
SAMFLAGS = -I$(SAMTOOLS) -I$(SAMTOOLS)/$(HTSLIB)
SAMLIBS = $(SAMTOOLS)/libbam.a $(SAMTOOLS)/$(HTSLIB)/libhts.a

I've patched this to use our separately installed samtools 1.3 in /usr/local.  If you don't want to support this sort of thing, let me know.  We can make an exception about bundled dependencies in this case if it's really necessary.

**Comment by jmarshall** [comment]
Sorry, we're not going to start installing libbam.a and its headers: [HTSlib](https://github.com/samtools/htslib) is now our recommended API — see #403 for details.

I have looked at RSEM and it uses only facilities that already exist in HTSlib.  (With one exception, which can be worked around, and which will arrive in htslib soon after an improved header API.)  So we would recommend that you convert to use the maintained HTSlib API instead.  HTSlib does have a good `install` target, and there are various facilities for selecting a bundled source tree or external installation to compile against.

Please consider the PR I've just created, which should get you folks a long way towards conversion!

**Comment by outpaddling** [comment]
This is a better solution.  Thanks so much for your efforts digging into the RSEM code!
