### ISSUE TITLE
bam_get_library segfaults if read groups lack LB tags

### ISSUE THREAD

**Issue by dpryan79** [samtools/samtools#538]
On line 114 of bam.c (https://github.com/samtools/samtools/blob/74a3e0a744f91bc2b1f65a4144a509d6dd791631/bam.c#L114), `bam_get_library()` looks for `LB` tags in `@RG` lines. That's all well and good if they're there, but apparently some people are adding read groups that don't contain all of the normal tags (cf., here http://seqanswers.com/forums/showthread.php?t=66333, which was subsequently posted to the samtools-help list here https://sourceforge.net/p/samtools/mailman/message/34857333/).

I presume that a simple `if(LB) {` around line 112 would solve this, though it'd probably be good to print a warning to alert the user that the read group should really have an `LB` tag.

**Comment by jmarshall** [comment]
Okay, that's easily fixable.  Have you confirmed with the OP that this was the cause in his case, i.e., that the headers in question do not have LB tags?

**Comment by dpryan79** [comment]
No, but I made a test file where I stripped out the LB tags from the read groups and it segfaulted at the exact same place

**Comment by jkbonfield** [comment]
Ah guilty as charged on this one (although it now only sometimes dies instead of always dying!).

John, are you fixing this already or shall I take it?

**Comment by jkbonfield** [comment]
It needs if (!LB || !ID) return NULL or something similar. Although it may have already been sanity checked (hah!) to spot lack of ID, we should be robust to that too.

With it returning NULL, rmdup will then fall through to counting all the LB-less libraries as being in library "\t" instead.

**Comment by jmarshall** [comment]
The OP has now confirmed via email that this was indeed the cause in his case.  Good job, everyone! :smile:
