### ISSUE TITLE
[main_samview] failed to write the SAM header

### ISSUE THREAD

**Issue by antozito** [samtools/samtools#542]
Hi all, happy to write

I am trying to convert .bam to .cram but I get the error below:

samtools view -T GCA_000001405.15_GRCh38_genomic.fa -C -O output.cram input.bam

[main_samview] failed to write the SAM header

Why this error is generated?
All the best,
anto

**Comment by mp15** [comment]
Err isn't -O output format not output file name?

**Comment by antozito** [comment]
I get the same error

samtools view -T GCA_000001405.15_GRCh38_genomic.fa -C -o output.cram input.bam

main_samview] failed to write the SAM header

**Comment by mp15** [comment]
Okay can you confirm what version of samtools you're running and that you have the correct access permissions to write to output.cram.

**Comment by antozito** [comment]
samtools 1.2 version,
and yes, I have the persmissions to write and read 

many thanks for the support

**Comment by mp15** [comment]
Hmm that bit of code doesn't have good error reporting. Do you have strace installed? If so could you prefix your command with strace and upload the result'to a GitHub gist please?

**Comment by antozito** [comment]
Hi martin, 
[strace.txt](https://github.com/samtools/samtools/files/145220/strace.txt)

it is fine ?
best
anto

**Comment by jkbonfield** [comment]
There are no obvious errors in that trace, but can you confirm whether the problem still exists with samtools & htslib version 1.3 please?

The only other thing I could suspect would be a mismatch between the BAM header and the given fasta file.  (I also forget which is which for -T vs -t, one being .fa and ther other being .fai, but likely it adds or removes the .fai as needed?)

**Comment by antozito** [comment]
Hi, the -T parameter indicates a .fa file. If .fai is not present it will be generated (as in my case).
The version I am using is the 1.2. But I can try if with older versions I experience the same problem

**Comment by jkbonfield** [comment]
I was thinking about 1.3 rather than older releases.  If it still fails in the current release then obviously we'll do our best to figure out the issue, but there were many changes between 1.2 and 1.3 including a bunch of CRAM things so maybe it has been fixed already.

**Comment by antozito** [comment]
Thanks, I will try with the new version (1.3)  as soon as possible. 
Anyway, is the conversion to CRAM able to produce  file with reduced size, it is right?
We have a lot of big BAM files and if the conversion to CRAM will be useful to save a good amount 
of hard disk space we will implement for all of them. Additionally, is the re-conversion CRAM to BAM
still efficient to avoid any loss of infomation?

All the Best and many thanks for the support
anto

**Comment by jkbonfield** [comment]
The command line looks OK to me.  You may like to try the htslib test_view tool too, just incase it's an issue with samtools (although it seems unlikely).

Regarding data loss, it depends on how you define loss.  The information content should be preserved, but it may not necessarily be bit-perfect.  Eg the order of auxiliary tags could be changed.  Additionally some records may be corrected; eg if calmd corrects a mistake in an NM or MD tag then there is a high chance that CRAM -> BAM -> CRAM would correct the same mistake too.  Similarly some of the issues that samtools fixmates fixes can sometimes be fixed by CRAM.

(You'd think that this is a good thing, but we had to put more work in to stop the TLEN field being fixed.)

**Comment by antozito** [comment]
Ok, important to know that. But, is a CRAM file smaller that the corresponding BAM ?
Best
anto

**Comment by mp15** [comment]
In short most of the time yes. In my large datasets I've got approx 1/3rd saving.

**Comment by antozito** [comment]
Many Thanks, I will let you know once I test the conversion (if 1.3 allows to do it)

**Comment by antozito** [comment]
Hi all, 

samtools 1.3 seems to work quite well. The conversion requires 2 hours per .bam file.
The .cram seems to be 10 times smaller than the corresponding .bam. It is fine for me.
As regards to the re-conversion cram -> bam, I will test soon. 
Is there some way to quickly see which changes (corrections) have been made in the .bam file when converting to .cram? 

Best
anto

**Comment by jkbonfield** [comment]
10x seems unexpectedly good, but maybe your input BAM file was uncompressed.

In order to see what changed you'll need to convert both the BAM and the CRAM to SAM and then compare the textual representation.  It's not so trivial as some of the auxiliary tags will change order.  Part of the htslib test harness is a perl script to compare SAM files so you could use that:

https://github.com/samtools/htslib/blob/develop/test/compare_sam.pl

You'll need to read the code (mainly the GetOptions line at the start) to figure out how to drive it though as it wasn't really intended as a user runnable tool.

**Comment by antozito** [comment]
Hi all, 
during the conversion of one of the files, there was the following message:
Segmentation fault (core dumped)

Seems to be an error related to the memory. But was the conversion for that file successfully completed or do I need to reimplement the command?

Best
anto

**Comment by antozito** [comment]
Sorry I meant that the cram is 2 times smaller than the corresponding bam.
Thanks, I will try, if necessary, to compare bam and cram despite I am not so familiar with perl language.

thanks
anto

**Comment by antozito** [comment]
Hi all, and I sorry If I am writing again but we are really interested to the question.
Once the conversion bam to cram, Is there any efficient way to compress the cram file?
Hi @mp15 , How did you achieve the 1/3rd of savings?

All the best and many thanks for the support
anto

**Comment by mp15** [comment]
I didn't use any of CRAM lossy modes though that is an option.

What I did was simply run the conversion on a rather large dataset and the law of averages did the rest. 164T of BAMs became 102T of CRAMs. My data was 13535 whole exome sample BAMs from the DDD project. These sample BAMs had been mkdup'd, realigned and BQSR'd. Your results may vary.

**Comment by jkbonfield** [comment]
On Mon, Mar 07, 2016 at 07:38:48AM -0800, Martin Pollard wrote:
> What I did was simply run the conversion on a rather large dataset and the law of averages did the rest. 164T of BAMs became 102T of CRAMs. My data was 13535 whole exome sample BAMs from the DDD project. These sample BAMs had been mkdup'd, realigned and BQSR'd. Your results may vary.

BQSR tags is one way to get "better" savings, for some definition of
better.

The BQ tags are highly redundant, but CRAM typically compresses them
better than BAM does.  Therefore having them may mean CRAM has a
higher compression ratio than BAM.  (However it doesn't make sense to
add them as in both cases the file size goes up, obviously!)

In short, some data compresses better than others.

The only way to increase compression ratio is by bumping up the
compression level (like gzip -1 to -9, there is an analogous in CRAM)
and using additional codecs like bzip2 and lzma; note at present these
are unsupported in samtools.

-- 
James Bonfield (jkb@sanger.ac.uk) | Hora aderat briligi. Nunc et Slythia Tova
                                  | Plurima gyrabant gymbolitare vabo;
  A Staden Package developer:     | Et Borogovorum mimzebant undique formae,
https://sf.net/projects/staden/   | Momiferique omnes exgrabure Rathi. 


-- 
 The Wellcome Trust Sanger Institute is operated by Genome Research 
 Limited, a charity registered in England with number 1021457 and a 
 company registered in England with number 2742969, whose registered 
 office is 215 Euston Road, London, NW1 2BE.

**Comment by antozito** [comment]
Hi, @jkbonfield 
I agree with you to do not add tags to the CRAM, this will cause an increase of the size.
Additonally, since at the moment we do not have any intention to implement CRAM lossy modalities
I am implementing a bzip2 compression to each CRAM, increasing as much as possible the compression level (despite longer computational time).
 I will update you once I will check the compressed file size.

All the best 
anto
PhD student 
Kings College London
