### ISSUE TITLE
memory misspelling leads to thousands of files for samtools sort

### ISSUE THREAD

**Issue by Jorisvansteenbrugge** [samtools/samtools#547]
When using samtools sort with the -m flag, one can assign more memory to the program.
for example:
`$ samtools sort -m 10G` assigns 10GB of memory. However when one misspells the command, for example like this:
`$ samtools sort -m G10` the program assigns 10B of memory, resulting in countless intermediate files.

It took us more than 3 days to remove the intermediate files from our server, because the file system really did not like the amount of files created. Maybe a warning can be given when memory is assigned lower than the default value?

**Comment by agarwal** [comment]
Also [reported](https://sourceforge.net/p/samtools/mailman/message/33575059/) on the mailing list a year ago.

**Comment by Jorisvansteenbrugge** [comment]
My bad I didn't knew about this list

**Comment by daviesrob** [comment]
It's better to report issues here, as they are tracked.

And yes, sort should either refuse to run if not given enough memory, or print a warning and lift the setting to a reasonable minimum level.

**Comment by agarwal** [comment]
@Jorisvansteenbrugge
> My bad I didn't knew about this list

I should've posted it as an issue back then myself. Thanks for doing so.

@daviesrob 
> sort should either refuse to run if not given enough memory, or print a warning and lift the setting to a reasonable minimum level.

Perhaps, but the issue here is just parsing of the command line parameter. `G10` and `1.75G` are simply invalid syntax, so I'd expect an immediate error.

**Comment by tseemann** [comment]
Here is the code for the parsing logic of the `-m` paramter:
https://github.com/samtools/samtools/blob/74a3e0a744f91bc2b1f65a4144a509d6dd791631/bam_sort.c#L1771-L1777
