### ISSUE TITLE
Warning in the process or 'samtools sort -n'

### ISSUE THREAD

**Issue by Shicheng-Guo** [samtools/samtools#550]
Dear All, 

I tried to sort a bam files, However, it reported a little warning. Any suggestion?

> samtools sort RRBS-6P17.sorted.clipped.bam -o RRBS-6P17.nsorted.clipped.bam

[bam_sort_core] merging from 5 files...
[E::trans_tbl_add_sq] @SQ SN (chr1) found in binary header but not text header.
[E::trans_tbl_add_sq] @SQ SN (chr2) found in binary header but not text header.
[E::trans_tbl_add_sq] @SQ SN (chr3) found in binary header but not text header.
[E::trans_tbl_add_sq] @SQ SN (chr4) found in binary header but not text header.
[E::trans_tbl_add_sq] @SQ SN (chr5) found in binary header but not text header.
[E::trans_tbl_add_sq] @SQ SN (chr6) found in binary header but not text header.
[E::trans_tbl_add_sq] @SQ SN (chr7) found in binary header but not text header.
[E::trans_tbl_add_sq] @SQ SN (chr8) found in binary header but not text header.
[E::trans_tbl_add_sq] @SQ SN (chr9) found in binary header but not text header.
[E::trans_tbl_add_sq] @SQ SN (chr10) found in binary header but not text header.
[E::trans_tbl_add_sq] @SQ SN (chr11) found in binary header but not text header.
[E::trans_tbl_add_sq] @SQ SN (chr12) found in binary header but not text header.
[E::trans_tbl_add_sq] @SQ SN (chr13) found in binary header but not text header.
[E::trans_tbl_add_sq] @SQ SN (chr14) found in binary header but not text header.
[E::trans_tbl_add_sq] @SQ SN (chr15) found in binary header but not text header.
[E::trans_tbl_add_sq] @SQ SN (chr16) found in binary header but not text header.
[E::trans_tbl_add_sq] @SQ SN (chr17) found in binary header but not text header.
[E::trans_tbl_add_sq] @SQ SN (chr18) found in binary header but not text header.
[E::trans_tbl_add_sq] @SQ SN (chr19) found in binary header but not text header.
[E::trans_tbl_add_sq] @SQ SN (chr20) found in binary header but not text header.
[E::trans_tbl_add_sq] @SQ SN (chr21) found in binary header but not text header.
[E::trans_tbl_add_sq] @SQ SN (chr22) found in binary header but not text header.
[E::trans_tbl_add_sq] @SQ SN (chrX) found in binary header but not text header.
[E::trans_tbl_add_sq] @SQ SN (chrY) found in binary header but not text header.
[E::trans_tbl_add_sq] @SQ SN (chrM) found in binary header but not text header.
[E::trans_tbl_add_sq] @SQ SN (chrLambdaNEB) found in binary header but not text header.

samtools --version
samtools 1.3
Using htslib 1.3
Copyright (C) 2015 Genome Research Ltd.

Thanks.

**Comment by jmarshall** [comment]
This is probably the same problem as #548.  Can you share the _RRBS-6P17.sorted.clipped.bam_ file or even just the first 20 Kb so I can have a look at its headers?  (How many chromosomes are there in the BAM file?)

My email address is [here](https://github.com/samtools/samtools/blob/develop/test/vcf-miniview.c#L5) if you can share the file or headers privately.

**Comment by jmarshall** [comment]
I've reproduced this with a BAM file with **no** text `@SQ` headers, so a fix will be forthcoming that will hopefully fix this for your files too.

Such BAM files are valid but uncommon.  What tool did you use to produce your _.bam_ file?

**Comment by HuaLing1** [comment]
I came across this issue when using samtools 1.3 but not for samtools 0.1.18. 

Has anybody had this issue solved for samtools 1.3?

**Comment by jmarshall** [comment]
@HuaLing1: The problem existed in 1.3, but we believe it has been fixed in 1.3**.1** (by f63a28226a63742c84e4647f5b7d02df69a1f444).

So please try samtools **1.3.1**.
