### ISSUE TITLE
samtools 1.3 faidx does not return non-zero status code upon detecting line length error

### ISSUE THREAD

**Issue by stevendavis** [samtools/samtools#561]
Please return non-zero status codes upon errors.

Deliberately change the fasta file line lengths
$ sed -i 's/A/AA/g' myFile.fasta

$ samtools faidx myFile.fasta
[fai_build_core] different line length in sequence 'gi|9626243|ref|NC_001416.1|'.

$ echo $?
0

**Comment by jmarshall** [comment]
Already fixed by de96bfb6100645541cec1b5c1119a9a16f5820ec.
