### ISSUE TITLE
samtools sort can duplicate @CO lines in the header when merging is involved

### ISSUE THREAD

**Issue by bli25wisc** [samtools/samtools#563]
Hi,

I detected that the latest samtools will duplicate @CO lines if there is a need to split the BAM file for sorting and then merge them together. 

Here is an example:

The header before sort:

@HD	VN:1.0	SO:unsorted
@SQ	SN:1	LN:249250621
@SQ	SN:10	LN:135534747
@SQ	SN:11	LN:135006516
@SQ	SN:12	LN:133851895
@SQ	SN:13	LN:115169878
@SQ	SN:14	LN:107349540
@SQ	SN:15	LN:102531392
@SQ	SN:16	LN:90354753
@SQ	SN:17	LN:81195210
@SQ	SN:18	LN:78077248
@SQ	SN:19	LN:59128983
@SQ	SN:2	LN:243199373
@SQ	SN:20	LN:63025520
@SQ	SN:21	LN:48129895
@SQ	SN:22	LN:51304566
@SQ	SN:3	LN:198022430
@SQ	SN:4	LN:191154276
@SQ	SN:5	LN:180915260
@SQ	SN:6	LN:171115067
@SQ	SN:7	LN:159138663
@SQ	SN:8	LN:146364022
@SQ	SN:9	LN:141213431
@SQ	SN:MT	LN:16569
@SQ	SN:X	LN:155270560
@SQ	SN:Y	LN:59373566
@PG	ID:Bowtie	VN:1.1.1	CL:"bowtie --wrapper basic-0 -q --phred33-quals -n 2 -e 99999999 -l 25 --chunkmbs 512 --nofw -p 8 -a -m 200 -S ../Ref/Human_GRCh37_hg19_Ensembl_84 ../Input_data/GTL16WT_1M.fastq"
@PG	ID:RSEM
@CO	This BAM file is processed by rsem-tbam2gam to convert from transcript coordinates into genomic coordinates.

The header after sort:

@HD	VN:1.0	SO:coordinate
@SQ	SN:1	LN:249250621
@SQ	SN:10	LN:135534747
@SQ	SN:11	LN:135006516
@SQ	SN:12	LN:133851895
@SQ	SN:13	LN:115169878
@SQ	SN:14	LN:107349540
@SQ	SN:15	LN:102531392
@SQ	SN:16	LN:90354753
@SQ	SN:17	LN:81195210
@SQ	SN:18	LN:78077248
@SQ	SN:19	LN:59128983
@SQ	SN:2	LN:243199373
@SQ	SN:20	LN:63025520
@SQ	SN:21	LN:48129895
@SQ	SN:22	LN:51304566
@SQ	SN:3	LN:198022430
@SQ	SN:4	LN:191154276
@SQ	SN:5	LN:180915260
@SQ	SN:6	LN:171115067
@SQ	SN:7	LN:159138663
@SQ	SN:8	LN:146364022
@SQ	SN:9	LN:141213431
@SQ	SN:MT	LN:16569
@SQ	SN:X	LN:155270560
@SQ	SN:Y	LN:59373566
@PG	ID:Bowtie	VN:1.1.1	CL:"bowtie --wrapper basic-0 -q --phred33-quals -n 2 -e 99999999 -l 25 --chunkmbs 512 --nofw -p 8 -a -m 200 -S ../Ref/Human_GRCh37_hg19_Ensembl_84 ../Input_data/GTL16WT_1M.fastq"
@PG	ID:RSEM
@CO	This BAM file is processed by rsem-tbam2gam to convert from transcript coordinates into genomic coordinates.
@CO	This BAM file is processed by rsem-tbam2gam to convert from transcript coordinates into genomic coordinates.
@CO	This BAM file is processed by rsem-tbam2gam to convert from transcript coordinates into genomic coordinates.
@CO	This BAM file is processed by rsem-tbam2gam to convert from transcript coordinates into genomic coordinates.
@CO	This BAM file is processed by rsem-tbam2gam to convert from transcript coordinates into genomic coordinates.
@CO	This BAM file is processed by rsem-tbam2gam to convert from transcript coordinates into genomic coordinates.
@CO	This BAM file is processed by rsem-tbam2gam to convert from transcript coordinates into genomic coordinates.
@CO	This BAM file is processed by rsem-tbam2gam to convert from transcript coordinates into genomic coordinates.
@CO	This BAM file is processed by rsem-tbam2gam to convert from transcript coordinates into genomic coordinates.
@CO	This BAM file is processed by rsem-tbam2gam to convert from transcript coordinates into genomic coordinates.
@CO	This BAM file is processed by rsem-tbam2gam to convert from transcript coordinates into genomic coordinates.
@CO	This BAM file is processed by rsem-tbam2gam to convert from transcript coordinates into genomic coordinates.
@CO	This BAM file is processed by rsem-tbam2gam to convert from transcript coordinates into genomic coordinates.
@CO	This BAM file is processed by rsem-tbam2gam to convert from transcript coordinates into genomic coordinates.
@CO	This BAM file is processed by rsem-tbam2gam to convert from transcript coordinates into genomic coordinates.
@CO	This BAM file is processed by rsem-tbam2gam to convert from transcript coordinates into genomic coordinates.

**Comment by SamStudio8** [comment]
Heh, I guess this is a side effect of
https://github.com/samtools/samtools/issues/390 (and specifically commit
https://github.com/samtools/samtools/commit/e8f27a32bae18b04f8da8e5a367e68a42096fece
)?

**Comment by jmarshall** [comment]
Indeed.  See #390 for discussion of why handling `@CO` potential duplication is non-trivial for the general case of `merge`.  We should do better for `sort` at least, though the lack of outcry may suggest something about how many people are using `@CO` in earnest…

**Comment by daviesrob** [comment]
The easy solution would be to strip the `@CO` tags out of all but the first temporary file.

Better still would be to not store the header in the temporary files at all, but that would need a bit of rework in the merge code.

**Comment by mp15** [comment]
Or we could make an equiv to the option that merges pg lines and rg lines (I'm starting to think I should have made it one option and not two)
