### ISSUE TITLE
configure htslib script error with 1.3.1 and current develop branch

### ISSUE THREAD

**Issue by cfriedline** [samtools/samtools#564]
When running configure, the AX_WITH_HTSLIB command produces:

```
$ ./configure
checking for gcc... gcc52
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables...
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc52 accepts -g... yes
checking for gcc52 option to accept ISO C89... none needed
checking for special C compiler options needed for large files... no
checking for _FILE_OFFSET_BITS value needed for large files... no
./configure: line 2838: AX_WITH_HTSLIB: command not found
configure: error: HTSlib development files not found

Samtools uses HTSlib to parse bioinformatics file formats etc.  Building it
requires an unpacked HTSlib source tree (which will be built in conjunction
with samtools) or a previously-installed HTSlib.  In either case you may
need to configure --with-htslib=DIR to locate the appropriate HTSlib.

FAILED.  You must supply an HTSlib in order to build samtools successfully.
```
However, when supplying this option, it is not available to configure
```
$ ./configure --with-htslib=../htslib
configure: WARNING: unrecognized options: --with-htslib
```

**Comment by jmarshall** [comment]
See #500 for how to set up a samtools git checkout to use _configure_ at the moment.

If this seems like a bother, you should just use today's 1.3.1 release tarball instead, which has _configure_ pre-generated.

**Comment by cfriedline** [comment]
Appears to be a duplicate of #500.  

Steps to fix:
1. download the current [autoconf archive](https://mirrors.ocf.berkeley.edu/gnu/autoconf-archive/) to `../autoconf-archive`
1. download the m4.txt file from #500 
1. rename to .m4 in automate-cache/m4
1. `rm -rf autom4te.cache` in samtools tree
1. run `aclocal` and `autoconf` again
1. `./configure`

Sorry for the duplicate

**Comment by jmarshall** [comment]
No apology needed; it's a good reminder for me to get around to fixing this :smile:
