### ISSUE TITLE
About Format:DP

### ISSUE THREAD

**Issue by orisnas** [samtools/samtools#565]
It means "Number of high-quality bases"
How to define a high-quality base? 
It seems that both base quality and mapping quality affect that ?
Thanks

**Comment by q623928815** [comment]
I have the same question too. The Depth in 'samtools mpileup' always smaller than in 'samtools depth'. Are there some additional filter in mpileup?
Does someone have an answer?
Thanks.

**Comment by jkbonfield** [comment]
Closing as this is (now) a bcftools issue given pileup moved there.   Run "bcftools pileup" to see the default values.

If this doesn't answer your question, please reopen a new issue in bcftools.  Thanks.
