### ISSUE TITLE
BCF written by mpileup not readable by bcftools ([E::bcf_hdr_read] failed to read BCF header)

### ISSUE THREAD

**Issue by cfriedline** [samtools/samtools#567]
Ran across this issue with our current dataset.  Please see the [this gist](http://bit.ly/1XVdklC) for more information:

Output from the pileup as VCF is usable, BCF is not.

```
/home/cfriedline/bin/samtools mpileup -t DP,AD,ADF,ADR,SP,INFO/AD,INFO/ADF,INFO/ADR  -Iuvf /home/cfriedline/eckertlab/SugarPine_genome/pila.v1.0.scafSeq subset.bam > subset.bam.vcf
```

```
/home/cfriedline/bin/samtools mpileup -t DP,AD,ADF,ADR,SP,INFO/AD,INFO/ADF,INFO/ADR  -Iugf /home/cfriedline/eckertlab/SugarPine_genome/pila.v1.0.scafSeq subset.bam > subset.bam.bcf
```

bcftools view of bcf:
```
[E::bcf_hdr_read] failed to read BCF header
Failed to open subset.bam.bcf: could not parse header
```

**Comment by cfriedline** [comment]
BCF is [here](https://dl.dropboxusercontent.com/u/861789/subset.bam.bcf)
VCF is [here](https://dl.dropboxusercontent.com/u/861789/subset.bam.vcf.gz)

**Comment by jmarshall** [comment]
Your VCF file, like the Sugar Pine v1.0 assembly, has 58 million `##contig` header lines.  This amounts to  ~1.9GiB of header text.

The BCF file's headers are truncated part-way through `##contig=<ID=scaffold11210,…`, rather suspiciously after 1048568 (= 1MiB - 8) characters.  It would appear that you have run into a bug in writing out such voluminous headers.  And it wouldn't be too surprising if there were other bugs with headers of this size as well.

**Comment by cfriedline** [comment]
Thanks, John.  We will definitely run into this again as we work with these tree megagenomes.  In the meantime, doing the pile up with uncompressed VCF seems to be working, though I suspect there is a computational tradeoff there.  Another solution may be to remove any contigs from the header that don't have mappings, which will dramatically reduce the size (at least for this dataset).  We find with these GBS data that we are only mapping to about 3% of the sugar pine contigs.

Perhaps we can have a compile flag that allows for huge BCF headers going forward?

**Comment by jmarshall** [comment]
Yes, removing the contig headers that are otherwise not referred to should be a good workaround for this for the moment.

No need for a compile flag — we'll just fix the bugs, as fixing them won't make things any worse for files with human-sized headers.  And your files are useful test cases for doing that with.

----

Incidentally, in your gist log

> !$samtools view -h -s 0.01 $bam > subset.bam
> !$samtools index subset.bam
> samtools index: "subset.bam" is in a format that cannot be usefully indexed

I suspect this is because _subset.bam_ is in fact a SAM file; you probably want `-b` in the samtools view command.

**Comment by cfriedline** [comment]
Yup - re: the -b flag.  It's in there, just uploaded an older copy of the notebook to gist.  Sorry for the confusion.  Either way, the bug remains.  Thanks for your help!

**Comment by jmarshall** [comment]
Try compiling both samtools and bcftools against htslib's **hugeheaders** branch (PR samtools/htslib#373); this should suffice to fix this issue.  It still uses an astonishing amount of memory to parse your headers, which may or may not be practical to improve.

(That branch will work with the samtools/bcftools 1.3.1 tags/releases.  To compile current **develop** samtools, you'd need to merge htslib/**hugeheaders** and htslib/**develop**… or just still with samtools 1.3.1, as samtools/**develop** hasn't changed significantly.)
