### ISSUE TITLE
samtools index/view bug with unmapped reads

### ISSUE THREAD

**Issue by carsonhh** [samtools/samtools#568]
When no reads align to the last real contig (i.e. BAI has empty bins for the last contig), using samtools view to select the unmapped reads (i.e. seq ID *) gives irregular behavior. If unamapped reads are present, it prints everything from the start of the file (not just unmapped reads).

And if unmapped reads are not present it gives the following error -->
[main_samview] region "*" specifies an unknown reference name. Continue anyway.

I believe the error occurs because samtools view is trying to use the pseudo-bin of the last contig to implicitly derive the location of the unmapped reads, and when that psuedo-bin is empty it causes irregular behavior. If my suspicion is correct, it means that the correct behavior should be to scan for the last defined bin/pseudo-bin as opposed to assuming one exists for the last contig.

**Comment by daviesrob** [comment]
Problem has been reproduced.  Results below should be 2 for the *_unmapped.bam files and 0 with no warning for *_no_unmapped.bam files.
```
# ./samtools view -O bam  test/dat/view.001.sam > /tmp/v1_2refs_unmapped.bam

# perl -pe 's/^(\@SQ\tSN:ref2.*)/$1\n\@SQ\tSN:ref3_unused\tLN:70\tM5:5fdd18c2c6ecac4838996d029bf395b5/' test/dat/view.001.sam | ./samtools view -O bam - > /tmp/v1_3refs_unmapped.bam

# perl -nae 'if ($F[2] ne "*") { print }' test/dat/view.001.sam | ./samtools view -O bam - > /tmp/v1_2refs_no_unmapped.bam

# perl -nae 's/^(\@SQ\tSN:ref2.*)/$1\n\@SQ\tSN:ref3_unused\tLN:70\tM5:5fdd18c2c6ecac4838996d029bf395b5/; if ($F[2] ne "*") { print }' test/dat/view.001.sam | ./samtools view -O bam - > /tmp/v1_3refs_no_unmapped.bam

# for i in /tmp/{v1_2refs_unmapped.bam,v1_3refs_unmapped.bam,v1_2refs_no_unmapped.bam,v1_3refs_no_unmapped.bam} ; do ./samtools index $i ; done

# for i in /tmp/{v1_2refs_unmapped.bam,v1_3refs_unmapped.bam,v1_2refs_no_unmapped.bam,v1_3refs_no_unmapped.bam} ; do echo -n "${i}: " ;  ./samtools view $i '*' | wc -l ; done
/tmp/v1_2refs_unmapped.bam: 2
/tmp/v1_3refs_unmapped.bam: 34
/tmp/v1_2refs_no_unmapped.bam: 0
/tmp/v1_3refs_no_unmapped.bam: [main_samview] region "*" specifies an unknown reference name. Continue anyway.
0
```
