### ISSUE TITLE
Bug in DP4 calculation for indels？

### ISSUE THREAD

**Issue by orisnas** [samtools/samtools#569]
I wonder what does  DV  mean in indel? It seems to be high-quality IDV.

```
##INFO=<ID=IDV,Number=1,Type=Integer,Description="Maximum number of reads supporting an indel">
##FORMAT=<ID=DV,Number=1,Type=Integer,Description="Number of high-quality non-reference bases">
```
But I got an insertion which DV larger than IDV

`7	128533516	.	C	CA	65	PASS	INDEL;IDV=2;IMF=0.0181818;DP=110;VDB=0.968566;SGB=-0.616816;MQSB=0.8;MQ0F=0;ICB=1;HOB=0.5;AC=1;AN=2;DP4=0,1,2,4;MQ=48	GT:PL:DP:DV    0/1:98,0,8:7:6`

**Comment by jmarshall** [comment]
Now posted to the [samtools-help mailing list](https://sourceforge.net/p/samtools/mailman/message/35051201/), which is a better place for this sort of question.

**Comment by tseemann** [comment]
No one responded on the mailing list. Is that still the preferred place for this stuff ?
