### ISSUE TITLE
samtools fastq bug?

### ISSUE THREAD

**Issue by alorfel** [samtools/samtools#570]
Hello,
I mapped a set of paired reads with a contigs file using bowtie2/2.2.9 with the -k option and a pipe to the samtools view to get the bam file. Samtools version 1.3.1. I used the next command line:

bowtie2 -k 2 --no-discordant -x ref -p 24 -1 pair1.fq -2 pair2.fq | samtools view -bS > pair.bam

This is the report of this step:

96638688 reads; of these:
  96638688 (100.00%) were paired; of these:
    58383048 (60.41%) aligned concordantly 0 times
    33253711 (34.41%) aligned concordantly exactly 1 time
    5001929 (5.18%) aligned concordantly >1 times
    ----
    58383048 pairs aligned 0 times concordantly or discordantly; of these:
      116766096 mates make up the pairs; of these:
        44519451 (38.13%) aligned 0 times
        49204659 (42.14%) aligned exactly 1 time
        23041986 (19.73%) aligned >1 times
76.97% overall alignment rate

Then, I wanted to extract the reads that mapped two times using samtools fasq with the option -f and the Flag 256 (Secondary alignment). I used the next command line:

samtools fastq -f 256 pair.bam

But the samtools fasq doesn't get results and report the next message:

[M::bam2fq_mainloop] processed 0 reads

I tried too without the -f option but I get the same result. What could be happen?. Thanks.

**Comment by mp15** [comment]
Your problem is caused by us not thinking of your usecase, specifically this line:
https://github.com/samtools/samtools/blob/develop/sam_view.c#L915
By default we exclude secondary and supplementary reads from the FASTQ. For your use case you should remove this line. We will look into a way of meeting your needs.

**Comment by alorfel** [comment]
Thanks for your response mp15,
we followed your instructions removing this line, but it does'nt work. Then we try removing line 1005 too and as result it works, but the fourth line (the quality line) of each read is filled with """""""" in the resulting fastqs.

**Comment by mp15** [comment]
" is quality 1 which is the default quality when a read doesn't have a quality. I suspect the secondary reads produced by bowtie2 have quality set to *, in which case this is working as designed and you need to tell bowtie to output the quality for these reads.
