### ISSUE TITLE
samtools reheader : unexpected ref name in output

### ISSUE THREAD

**Issue by carl-** [samtools/samtools#572]
the `samtools reheader` command do not output corrected ref name. here is the example.
==
> samtoos view -h test.bam
@HD	VN:1.0	SO:coordinate
@SQ	SN:chr1	LN:195471971
@SQ	SN:chr2	LN:182113224
@SQ	SN:chr3	LN:160039680
ST-E00192:208:HNFMTCCXX:8:1216:23906:5071	83	chr1	3000481	42	150M	=	3000164	-467	GGTTGATTTCAGCTCTGAGTTTGATTATTTCCTGCTGTCTACTCATCTTGGGTGAATTTGCTTCCTTTTGTTCTAGAGCTTCTAGATTTGCTGTCAGGCTGCTAGTGTATACTCTAGTTTCCTTTTGGAGGCACACAGGCCTGTGAGTTT	KKKKKKKKKFKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKFKKKKKKKKKKKKKKKKKKKKKFFFAA	MD:Z:150	PG:Z:MarkDuplicates	XG:i:0	NM:i:0	XM:i:0	XN:i:0	XO:i:0	AS:i:0	YS:i:-12	YT:Z:CP
ST-E00192:208:HNFMTCCXX:8:1104:6319:3647	163	chr2	3050011	42	150M	=	3050090	228	CAGGAAAGAAAGAAAGAAAGAAAGAAAGAAGGAAGGAAGGAAGGAAGGAAGGAAGGAAGGAAGGAAGGAAGGAAGGAAGGAAGGAAGGAAGGAAGGAAGAAAAATGAAAGTAAGAAACTAAAATTACTTTTATGTTTTGTAGTTTTGTTG	AAFFFKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKFKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKFKKKAKK,AFKKKKKKKKKKAAAAAA,AKA,A,<FKKFFFAAFKFAAFAA,7A	MD:Z:30A119	PG:Z:MarkDuplicates	XG:i:0	NM:i:1	XM:i:1	XN:i:0	XO:i:0	AS:i:-6	YS:i:0	YT:Z:CP
ST-E00192:208:HNFMTCCXX:8:1114:16965:67797	99	chr3	2999983	40	29M1D121M	=	3000223	304	AGTATATTGGAGCACTGTGACATCACAGTGGAGCACTGTGACCCCAAAGTAGAGAACTATGACAAAACAGTGAACACTGAAACACATCAGTGGAGGACTCAGACAGCACAGTGGAGTTCTATGTCACCACAGTGCAGCACTGTTTCATCA	AAFFFKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKFKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKFFKKKKKKKKKKKKKKKKKKKKKKKKFKKKKKKK	MD:Z:0N0N0N0N0N0N0N0N0N0N0N0N0N0N0N0N0N0N11^G9G12A98	PG:Z:MarkDuplicates	XG:i:1	NM:i:21	XM:i:20	XN:i:18	XO:i:1	AS:i:-38	YS:i:0	YT:Z:CP

# if i change the order of ref name, make it from chr3 to chr1 .
> cat hdr.sam 
@HD	VN:1.0	SO:coordinate
@SQ	SN:chr3	LN:160039680
@SQ	SN:chr2	LN:182113224
@SQ	SN:chr1	LN:195471971

# then I run samtools reheader, then samtools view it
>samtools reheader hdr.sam test.bam >reheader.bam
>samtools view -h reheader.bam

@HD	VN:1.0	SO:coordinate
@SQ	SN:chr3	LN:160039680
@SQ	SN:chr2	LN:182113224
@SQ	SN:chr1	LN:195471971
@PG	ID:samtools	PN:samtools	VN:1.3.1	CL:samtools reheader hdr.sam new.bam 
ST-E00192:208:HNFMTCCXX:8:1216:23906:5071	83	chr3	3000481	42	150M	=	3000164	-467	GGTTGATTTCAGCTCTGAGTTTGATTATTTCCTGCTGTCTACTCATCTTGGGTGAATTTGCTTCCTTTTGTTCTAGAGCTTCTAGATTTGCTGTCAGGCTGCTAGTGTATACTCTAGTTTCCTTTTGGAGGCACACAGGCCTGTGAGTTT	KKKKKKKKKFKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKFKKKKKKKKKKKKKKKKKKKKKFFFAA	MD:Z:150	PG:Z:MarkDuplicates	XG:i:0	NM:i:0	XM:i:0	XN:i:0	XO:i:0	AS:i:0	YS:i:-12	YT:Z:CP
ST-E00192:208:HNFMTCCXX:8:1104:6319:3647	163	chr2	3050011	42	150M	=	3050090	228	CAGGAAAGAAAGAAAGAAAGAAAGAAAGAAGGAAGGAAGGAAGGAAGGAAGGAAGGAAGGAAGGAAGGAAGGAAGGAAGGAAGGAAGGAAGGAAGGAAGAAAAATGAAAGTAAGAAACTAAAATTACTTTTATGTTTTGTAGTTTTGTTG	AAFFFKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKFKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKFKKKAKK,AFKKKKKKKKKKAAAAAA,AKA,A,<FKKFFFAAFKFAAFAA,7A	MD:Z:30A119	PG:Z:MarkDuplicates	XG:i:0	NM:i:1	XM:i:1	XN:i:0	XO:i:0	AS:i:-6	YS:i:0	YT:Z:CP
ST-E00192:208:HNFMTCCXX:8:1114:16965:67797	99	chr1	2999983	40	29M1D121M	=	3000223	304	AGTATATTGGAGCACTGTGACATCACAGTGGAGCACTGTGACCCCAAAGTAGAGAACTATGACAAAACAGTGAACACTGAAACACATCAGTGGAGGACTCAGACAGCACAGTGGAGTTCTATGTCACCACAGTGCAGCACTGTTTCATCA	AAFFFKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKFKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKFFKKKKKKKKKKKKKKKKKKKKKKKKFKKKKKKK	MD:Z:0N0N0N0N0N0N0N0N0N0N0N0N0N0N0N0N0N0N11^G9G12A98	PG:Z:MarkDuplicates	XG:i:1	NM:i:21	XM:i:20	XN:i:18	XO:i:1	AS:i:-38	YS:i:0	YT:Z:CP

# the order of ref name in the header changes as expected. but each read mapped to a different ref after reheader. 
for example, the first record:
"ST-E00192:208:HNFMTCCXX:8:1216:23906:5071" mapped to chr1 before reheader, and after reheader, it mapped to chr3, which is expected to be chr1.
I alse check the bam_reheader.c, and find that this command just read from input bam and directly output to stdout with bam1_core.tid field untouched.

Does this work as it was designed ?

**Comment by mp15** [comment]
Yes this is exactly as designed because if you think about it SN is just a nice human alias. Reads in bam don't contain the text name of the chr just an index into the header. The reads that mapped to the item in index 0 still mapped to index 0 regardless of what you name it

M

> On 11 May 2016, at 06:32, WEI ZH <notifications@github.com> wrote:
> 
> the samtools reheader command do not output corrected ref name. here is the example.
> 
> samtoos view -h test.bam
> @HD VN:1.0 SO:coordinate
> @SQ SN:chr1 LN:195471971
> @SQ SN:chr2 LN:182113224
> @SQ SN:chr3 LN:160039680
> ST-E00192:208:HNFMTCCXX:8:1216:23906:5071 83 chr1 3000481 42 150M = 3000164 -467 GGTTGATTTCAGCTCTGAGTTTGATTATTTCCTGCTGTCTACTCATCTTGGGTGAATTTGCTTCCTTTTGTTCTAGAGCTTCTAGATTTGCTGTCAGGCTGCTAGTGTATACTCTAGTTTCCTTTTGGAGGCACACAGGCCTGTGAGTTT KKKKKKKKKFKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKFKKKKKKKKKKKKKKKKKKKKKFFFAA MD:Z:150 PG:Z:MarkDuplicates XG:i:0 NM:i:0 XM:i:0 XN:i:0 XO:i:0 AS:i:0 YS:i:-12 YT:Z:CP
> ST-E00192:208:HNFMTCCXX:8:1104:6319:3647 163 chr2 3050011 42 150M = 3050090 228 CAGGAAAGAAAGAAAGAAAGAAAGAAAGAAGGAAGGAAGGAAGGAAGGAAGGAAGGAAGGAAGGAAGGAAGGAAGGAAGGAAGGAAGGAAGGAAGGAAGAAAAATGAAAGTAAGAAACTAAAATTACTTTTATGTTTTGTAGTTTTGTTG AAFFFKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKFKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKFKKKAKK,AFKKKKKKKKKKAAAAAA,AKA,A,<FKKFFFAAFKFAAFAA,7A MD:Z:30A119 PG:Z:MarkDuplicates XG:i:0 NM:i:1 XM:i:1 XN:i:0 XO:i:0 AS:i:-6 YS:i:0 YT:Z:CP
> ST-E00192:208:HNFMTCCXX:8:1114:16965:67797 99 chr3 2999983 40 29M1D121M = 3000223 304 AGTATATTGGAGCACTGTGACATCACAGTGGAGCACTGTGACCCCAAAGTAGAGAACTATGACAAAACAGTGAACACTGAAACACATCAGTGGAGGACTCAGACAGCACAGTGGAGTTCTATGTCACCACAGTGCAGCACTGTTTCATCA AAFFFKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKFKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKFFKKKKKKKKKKKKKKKKKKKKKKKKFKKKKKKK MD:Z:0N0N0N0N0N0N0N0N0N0N0N0N0N0N0N0N0N0N11^G9G12A98 PG:Z:MarkDuplicates XG:i:1 NM:i:21 XM:i:20 XN:i:18 XO:i:1 AS:i:-38 YS:i:0 YT:Z:CP
> 
> if i change the order of ref name, make it from chr3 to chr1 .
> 
> cat hdr.sam 
> @HD VN:1.0 SO:coordinate
> @SQ SN:chr3 LN:160039680
> @SQ SN:chr2 LN:182113224
> @SQ SN:chr1 LN:195471971
> 
> then I run samtools reheader, then samtools view it
> 
> samtools reheader hdr.sam test.bam >reheader.bam
> samtools view -h reheader.bam
> 
> @HD VN:1.0 SO:coordinate
> @SQ SN:chr3 LN:160039680
> @SQ SN:chr2 LN:182113224
> @SQ SN:chr1 LN:195471971
> @PG ID:samtools PN:samtools VN:1.3.1 CL:samtools reheader hdr.sam new.bam 
> ST-E00192:208:HNFMTCCXX:8:1216:23906:5071 83 chr3 3000481 42 150M = 3000164 -467 GGTTGATTTCAGCTCTGAGTTTGATTATTTCCTGCTGTCTACTCATCTTGGGTGAATTTGCTTCCTTTTGTTCTAGAGCTTCTAGATTTGCTGTCAGGCTGCTAGTGTATACTCTAGTTTCCTTTTGGAGGCACACAGGCCTGTGAGTTT KKKKKKKKKFKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKFKKKKKKKKKKKKKKKKKKKKKFFFAA MD:Z:150 PG:Z:MarkDuplicates XG:i:0 NM:i:0 XM:i:0 XN:i:0 XO:i:0 AS:i:0 YS:i:-12 YT:Z:CP
> ST-E00192:208:HNFMTCCXX:8:1104:6319:3647 163 chr2 3050011 42 150M = 3050090 228 CAGGAAAGAAAGAAAGAAAGAAAGAAAGAAGGAAGGAAGGAAGGAAGGAAGGAAGGAAGGAAGGAAGGAAGGAAGGAAGGAAGGAAGGAAGGAAGGAAGAAAAATGAAAGTAAGAAACTAAAATTACTTTTATGTTTTGTAGTTTTGTTG AAFFFKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKFKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKFKKKAKK,AFKKKKKKKKKKAAAAAA,AKA,A,<FKKFFFAAFKFAAFAA,7A MD:Z:30A119 PG:Z:MarkDuplicates XG:i:0 NM:i:1 XM:i:1 XN:i:0 XO:i:0 AS:i:-6 YS:i:0 YT:Z:CP
> ST-E00192:208:HNFMTCCXX:8:1114:16965:67797 99 chr1 2999983 40 29M1D121M = 3000223 304 AGTATATTGGAGCACTGTGACATCACAGTGGAGCACTGTGACCCCAAAGTAGAGAACTATGACAAAACAGTGAACACTGAAACACATCAGTGGAGGACTCAGACAGCACAGTGGAGTTCTATGTCACCACAGTGCAGCACTGTTTCATCA AAFFFKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKFKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKFFKKKKKKKKKKKKKKKKKKKKKKKKFKKKKKKK MD:Z:0N0N0N0N0N0N0N0N0N0N0N0N0N0N0N0N0N0N11^G9G12A98 PG:Z:MarkDuplicates XG:i:1 NM:i:21 XM:i:20 XN:i:18 XO:i:1 AS:i:-38 YS:i:0 YT:Z:CP
> 
> the order of ref name in the header changes as expected. but each read mapped to a different ref after reheader.
> 
> for example, the first record:
> "ST-E00192:208:HNFMTCCXX:8:1216:23906:5071" mapped to chr1 before reheader, and after reheader, it mapped to chr3, which is expected to be chr1.
> I alse check the bam_reheader.c, and find that this command just read from input bam and directly output to stdout with bam1_core.tid field untouched.
> 
> Does this work as it was designed ?
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> 



-- 
 The Wellcome Trust Sanger Institute is operated by Genome Research 
 Limited, a charity registered in England with number 1021457 and a 
 company registered in England with number 2742969, whose registered 
 office is 215 Euston Road, London, NW1 2BE.

**Comment by carl-** [comment]
then, this command is just providing a method to rename the reference/ contig name ??
if so, I suggest considering rename this command or add more details to the manual for this command

**Comment by lh3** [comment]
The primary goal of reheader is to efficiently amend header tags. For example, you can change sample names, add reference MD5, insert comment lines, etc. Renaming reference/contig names is a side-effect – we only realized later that reheader is a convenient way to do that.

As its name suggests, "reheader" only changes the header. You should not expect it to change bam1::core.tid, the alignment body; otherwise it would not be named reheader. In addition, the manpage does said that "nor that [reheader] is suitable to use with the sequence data itself".
