### ISSUE TITLE
1.3.1 would not compile with --enable-libcurl

### ISSUE THREAD

**Issue by andrewyatz** [samtools/samtools#573]
I've just tried to compiled samtools version 1.3.1 on OSX 10.5 with `clang-700.1.81` with HTTPS support (well libcurl) turned on.

```
./configure --enable-libcurl
```

htslib compiled fine. samtools didn't and I got the error

```
gcc -pthread -rdynamic   -o samtools bam_index.o bam_plcmd.o sam_view.o bam_cat.o bam_md.o bam_reheader.o bam_sort.o bedidx.o kprobaln.o bam_rmdup.o bam_rmdupse.o bam_mate.o bam_stat.o bam_color.o bamtk.o bam2bcf.o bam2bcf_indel.o errmod.o sample.o sam_opts.o cut_target.o phase.o bam2depth.o padding.o bedcov.o bamshuf.o faidx.o dict.o stats.o stats_isize.o bam_flags.o bam_split.o bam_tview.o bam_tview_curses.o bam_tview_html.o bam_lpileup.o bam_quickcheck.o bam_addrprg.o libbam.a htslib-1.3.1/libhts.a -lncurses -lm -lz -ldl
clang: warning: argument unused during compilation: '-pthread'
Undefined symbols for architecture x86_64:
  "_curl_easy_cleanup", referenced from:
      _hopen_libcurl in libhts.a(hfile_libcurl.o)
      _libcurl_close in libhts.a(hfile_libcurl.o)

...

ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [samtools] Error 1
```

It seems that `-lcurl` hasn't been added to any libs compilation step in samtools in response to the `--enable-libcurl`. I fixed it by adding `-lcurl` to `ALL_LIBS` in `Makefile` but this doesn't seem like the right way to do it.

Looking at htslib it seemed to do it in `config.mk` though I'm not sure how that works really so I'll leave that fixing to someone who knows what they're doing.

**Comment by jmarshall** [comment]
This is why `--enable-plugins` is the recommended configuration.

**Comment by andrewyatz** [comment]
Fair enough I didn't consult README as I thought it was a duplication of README.md.
