### ISSUE TITLE
Cram to bam conversion - incorrect bin field

### ISSUE THREAD

**Issue by dshiga** [samtools/samtools#574]
Hello,

I'm having a problem using samtools view to convert from cram to bam. A small fraction of the records in the resulting bam files appear to have the "bin" field set to an incorrect value. (This shows up as error messages from Picard ValidateSamFile like: FLOWCELLXXX, bin field of BAM record does not equal value computed based on alignment start and end, and length of sequence to which read is aligned)

I have seen this problem with multiple different cram files converted to bam. If you convert the same cram files to sam first, and then to bam, they validate correctly so it definitely seems to be an issue with cram to bam conversion specifically.

The error occurs only in a small fraction of the reads in my files. I'm not sure what the pattern is that causes problems for these specific reads and not others.

You can reproduce this with the attached sam file by converting to cram and then back to bam with samtools view, then run through ValidateSamFile:
```
samtools view -C -h example_bin_field_error.sam -o example_bin_field_error.cram -T hg38.fasta
samtools view -b -h example_bin_field_error.cram -o example_bin_field_error.bam -T hg38.fasta
java -jar picard.jar ValidateSamFile I=example_bin_field_error.bam
```

[example_bin_field_error.sam.txt](https://github.com/samtools/samtools/files/262104/example_bin_field_error.sam.txt)

Thanks,

Dave

**Comment by jmarshall** [comment]
These two reads are located at 48381952–48382027 and 48382074–48382149, which puts them in bins 954 and 7634, respectively, which a SAM→BAM conversion of your example file gets correct.  However a SAM→CRAM→BAM conversion puts them both in bin 7634.

```
$ bincalc 954 7634 48381952-48382027 48381953-48382028 48382074-48382149
Bin 954 spans 48365569-48496640 on level 4
Bin 7634 spans 48381953-48398336 on level 5
48381952-48382027 lies in bin 954, which spans 48365569-48496640 on level 4
48381953-48382028 lies in bin 7634, which spans 48381953-48398336 on level 5
48382074-48382149 lies in bin 7634, which spans 48381953-48398336 on level 5
```

This is an off-by-one error in the [CRAM code that sets `bin`](https://github.com/samtools/htslib/blob/develop/cram/cram_samtools.c#L93), caused alas by a lack of documentation that `hts_reg2bin()` takes 0-based coordinates.  It affects only a small fraction of the reads as they need to be exactly 1bp away from a bin boundary to be affected.

Bin fields are pretty much useless and not actually used by anything, but until we get around to deprecating them we need to write them correctly.  Thanks for the comprehensive bug report.

**Comment by jkbonfield** [comment]
Thanks for the clear bug report and quickly spotted John, that does indeed look like the issue right there.  I note that io_lib's variant of this code is ```bam_set_bin(*b, reg2bin(pos-1,end));``` so it looks like I had a brain fade during my conversion to htslib functions.

Cheers

**Comment by dshiga** [comment]
Excellent, thanks for your quick response @jkbonfield and @jmarshall! I didn't realize that the bin field is unused. I suppose it is redundant due to the same info being available in the bam index file?

**Comment by jmarshall** [comment]
It was basically a premature optimisation: in the past, it was used when generating the index (and it's not useful for much else).  But it's more reliable to recalculate it as you're generating the index, and that's what both htslib and htsjdk do these days.  It's also specific to the 14,5 geometry of the BAI index, and so no use if you're using large chromosomes or CSI indices with other geometries.

**Comment by dshiga** [comment]
Ah, good to know, thanks!

**Comment by jkbonfield** [comment]
While I concede the error and are about to fix it, what version of Picard is this?  I tried a recent one and it doesn't complain.  Maybe you can work around the problem by upgrading your picard.

**Comment by dshiga** [comment]
Great, thanks for fixing so quickly!

**Comment by tmm211** [comment]
Hi- I googled this issue and I am seeing it too! I tried to convert cram to bam, create a sam validation report, then create a BAM index. In the BAM index workflow this error shows up. I am using whatever version of Picard is on the Genomes in the Cloud docker linked below :
To get help, see http://broadinstitute.github.io/picard/index.html#GettingHelp
Exception in thread "main" htsjdk.samtools.SAMFormatException: SAM validation error: ERROR: Record 27205, Read name H06HDADXX130110:1:1101:10032:94873, bin field of BAM record does not equal value computed based on alignment start and end, and length of sequence to which read is aligned

Docker: broadinstitute/genomes-in-the-cloud:2.3.1-1500064817

**Comment by jkbonfield** [comment]
This issue is closed because the bug has been fixed.

However old BAM files produced by samtools (or scramble) and new files produced by an outdated copy of samtools, will still have the issue.  There is nothing we can do to prevent this.

We recommend instead you convert the BAM to SAM and back again in order for the bin to be recomputed.  Eg (with multi-threading; feel free to adjust the -@ parameters):

```
samtools view -@2 -h in.bam | samtools view -@8 -b -o out.bam
```

Note to others maintainers: is there no easier way to recompute bin without having to go to SAM and back?

**Comment by tmm211** [comment]
Are there commands for going from Cram to Sam to Bam and generate a Bam index and Validation report?

**Comment by jkbonfield** [comment]
I don't know what you mean by a validation report.  We don't have tools to do anything like that.  Maybe Picard has something like this, but if so this is the wrong place to ask.

As far as going from *bam* to sam to bam, see the above command.  Samtools cannot generate an index on-the-fly, so you'll need to follow that with an index command. Eg:

```
samtools view -h in.bam | samtools view -b -o out.bam
samtools index out.bam
```

 However you said *cram* to sam to bam.  That isn't necessary as you can just go from cram to bam directly.  The issue with incorrect bins is due to an old version of htslib.  The current code will work fine.  You can therefore do something like:

```
samtools view -b -o out.bam in.cram
samtools index out.bam
```

All of these accept the `-@` parameter for multi-threading, which will be useful in speeding things up.

**Comment by tmm211** [comment]
So I just inspected the version of tools on the Docker file I am using and discovered this:
LABEL GOTC_PICARD_VER=1.1150
LABEL GOTC_GATK34_VER=3.4-g3c929b0
LABEL GOTC_GATK35_VER=3.5-0-g36282e4
LABEL GOTC_GATK36_VER=3.6-44-ge7d1cd2
LABEL GOTC_GATK4_VER=4.beta.1
LABEL GOTC_SAMTOOLS_VER=1.3.1
LABEL GOTC_BWA_VER=0.7.15.r1140
LABEL GOTC_TABIX_VER=0.2.5_r1005
LABEL GOTC_BGZIP_VER=1.3
LABEL GOTC_SVTOOLKIT_VER=2.00-1650

So we are using an older version of Samtools, 1.3.1. When you say the current code will work fine, do you mean the current version of Samtools (1.5)?

**Comment by daviesrob** [comment]
Yes, 1.5 should be OK.
