### ISSUE TITLE
error: unknown type name ‘WINDOW’

### ISSUE THREAD

**Issue by chrisju** [samtools/samtools#577]
system: CentOS 6.5

cd samtools-1.3.1
./configure --enable-plugins --enable-libcurl --with-plugin-path=$PWD/htslib-1.3.1
make all plugins-htslib

...
gcc -g -O2 -I. -Ihtslib-1.3.1  -c -o bam_tview.o bam_tview.c
gcc -g -O2 -I. -Ihtslib-1.3.1  -c -o bam_tview_curses.o bam_tview_curses.c
bam_tview_curses.c:46:5: error: unknown type name ‘WINDOW’
bam_tview_curses.c: In function ‘curses_init_colors’:
bam_tview_curses.c:107:22: error: ‘COLOR_WHITE’ undeclared (first use in this function)
...

**Comment by jmarshall** [comment]
It would appear that the curses installation on CentOS is a bit unusual.  Please show us _config.h_ and _config.log_ from your _samtools-1.3.1_ directory.

**Comment by daviesrob** [comment]
I grabbed a CentOS 6.5 image from http://cloud.centos.org/centos/6.5/images/ and after a bit of faff getting a login on the thing, managed to build samtools without seeing this error.  Installs needed on top of the base image were:

```
sudo yum install gcc
sudo yum install libcurl-devel
sudo yum install zlib-devel
sudo yum install openssl-devel
sudo yum install ncurses-devel 
```
`yum list` says that `ncurses` is the only curses available.  I don't think there's anything wrong with the default CentOS curses.  It must have been finding an incompatible curses.h from somewhere else.  We'll need more information to find out where it came from.

**Comment by chrisju** [comment]
config.h
`/* config.h.  Generated from config.h.in by configure.  */
/* config.h.in -- template for config.h.  If you use configure, this file
   provides #defines reflecting your configuration choices.  If you don't
   run configure, suitable conservative defaults will be used.

   This template file can be updated with autoheader, but do so carefully
   as autoheader adds #defines such as PACKAGE_* that we don't want.  */

/* Define to 1 if a SysV or X/Open compatible Curses library is present */
#define HAVE_CURSES 1

/* Define to 1 if library supports color (enhanced functions) */
/* #undef HAVE_CURSES_COLOR */

/* Define to 1 if library supports X/Open Enhanced functions */
/* #undef HAVE_CURSES_ENHANCED */

/* Define to 1 if <curses.h> is present */
/* #undef HAVE_CURSES_H */

/* Define to 1 if library supports certain obsolete features */
/* #undef HAVE_CURSES_OBSOLETE */

/* Define to 1 if the Ncurses library is present */
/* #undef HAVE_NCURSES */

/* Define to 1 if the NcursesW library is present */
#define HAVE_NCURSESW 1

/* Define to 1 if <ncursesw/curses.h> is present */
/* #undef HAVE_NCURSESW_CURSES_H */

/* Define to 1 if <ncursesw.h> is present */
/* #undef HAVE_NCURSESW_H */

/* Define to 1 if <ncurses/curses.h> is present */
/* #undef HAVE_NCURSES_CURSES_H */

/* Define to 1 if <ncurses.h> is present */
/* #undef HAVE_NCURSES_H */

/* Enable large inode numbers on Mac OS X 10.5.  */
#ifndef _DARWIN_USE_64_BIT_INODE
# define _DARWIN_USE_64_BIT_INODE 1
#endif

/* Number of bits in a file offset, on hosts where this is settable. */
/* #undef _FILE_OFFSET_BITS */

/* Define for large files, on AIX-style hosts. */
/* #undef _LARGE_FILES */
`

config.log
`This file contains any messages produced by compilers while
running configure, to aid debugging if configure makes a mistake.

It was created by Samtools configure 1.3.1, which was
generated by GNU Autoconf 2.69.  Invocation command line was

  $ ./configure --enable-plugins --enable-libcurl --with-plugin-path=/home/zhuweiwei/bwadata/samtools-1.3.1/htslib-1.3.1

## --------- ##
## Platform. ##
## --------- ##

hostname = vsc-server
uname -m = x86_64
uname -r = 2.6.32-431.el6.x86_64
uname -s = Linux
uname -v = #1 SMP Fri Nov 22 03:15:09 UTC 2013

/usr/bin/uname -p = unknown
/bin/uname -X     = unknown

/bin/arch              = x86_64
/usr/bin/arch -k       = unknown
/usr/convex/getsysinfo = unknown
/usr/bin/hostinfo      = unknown
/bin/machine           = unknown
/usr/bin/oslevel       = unknown
/bin/universe          = unknown

PATH: /opt/centos/devtoolset-1.0/root/usr/bin/
PATH: /usr/lib64/qt-3.3/bin
PATH: /usr/local/bin
PATH: /bin
PATH: /usr/bin
PATH: /usr/local/sbin
PATH: /usr/sbin
PATH: /sbin
PATH: /home/zhuweiwei/bwadata/sratoolkit.2.5.7-ubuntu64/bin
PATH: /home/zhuweiwei/bin


## ----------- ##
## Core tests. ##
## ----------- ##

configure:1902: checking for gcc
configure:1918: found /opt/centos/devtoolset-1.0/root/usr/bin//gcc
configure:1929: result: gcc
configure:2158: checking for C compiler version
configure:2167: gcc --version >&5
gcc (GCC) 4.7.0 20120507 (Red Hat 4.7.0-5)
Copyright (C) 2012 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

configure:2178: $? = 0
configure:2167: gcc -v >&5
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/opt/centos/devtoolset-1.0/root/usr/libexec/gcc/x86_64-redhat-linux/4.7.0/lto-wrapper
Target: x86_64-redhat-linux
Configured with: ../configure --prefix=/opt/centos/devtoolset-1.0/root/usr --mandir=/opt/centos/devtoolset-1.0/root/usr/share/man --infodir=/opt/centos/devtoolset-1.0/root/usr/share/info --with-bugurl=http://bugzilla.redhat.com/bugzilla --enable-bootstrap --enable-shared --enable-threads=posix --enable-checking=release --disable-build-with-cxx --disable-build-poststage1-with-cxx --with-system-zlib --enable-__cxa_atexit --disable-libunwind-exceptions --enable-gnu-unique-object --enable-linker-build-id --enable-languages=c,c++,lto --enable-plugin --with-linker-hash-style=gnu --enable-initfini-array --disable-libgcj --with-ppl --with-cloog --with-mpc=/home/centos/rpm/BUILD/gcc-4.7.0-20120507/obj-x86_64-redhat-linux/mpc-install --with-tune=generic --with-arch_32=i686 --build=x86_64-redhat-linux
Thread model: posix
gcc version 4.7.0 20120507 (Red Hat 4.7.0-5) (GCC) 
configure:2178: $? = 0
configure:2167: gcc -V >&5
gcc: error: unrecognized command line option '-V'
gcc: fatal error: no input files
compilation terminated.
configure:2178: $? = 4
configure:2167: gcc -qversion >&5
gcc: error: unrecognized command line option '-qversion'
gcc: fatal error: no input files
compilation terminated.
configure:2178: $? = 4
configure:2198: checking whether the C compiler works
configure:2220: gcc    conftest.c  >&5
configure:2224: $? = 0
configure:2272: result: yes
configure:2275: checking for C compiler default output file name
configure:2277: result: a.out
configure:2283: checking for suffix of executables
configure:2290: gcc -o conftest    conftest.c  >&5
configure:2294: $? = 0
configure:2316: result: 
configure:2338: checking whether we are cross compiling
configure:2346: gcc -o conftest    conftest.c  >&5
configure:2350: $? = 0
configure:2357: ./conftest
configure:2361: $? = 0
configure:2376: result: no
configure:2381: checking for suffix of object files
configure:2403: gcc -c   conftest.c >&5
configure:2407: $? = 0
configure:2428: result: o
configure:2432: checking whether we are using the GNU C compiler
configure:2451: gcc -c   conftest.c >&5
configure:2451: $? = 0
configure:2460: result: yes
configure:2469: checking whether gcc accepts -g
configure:2489: gcc -c -g  conftest.c >&5
configure:2489: $? = 0
configure:2530: result: yes
configure:2547: checking for gcc option to accept ISO C89
configure:2610: gcc  -c -g -O2  conftest.c >&5
configure:2610: $? = 0
configure:2623: result: none needed
configure:2652: checking for special C compiler options needed for large files
configure:2697: result: no
configure:2703: checking for _FILE_OFFSET_BITS value needed for large files
configure:2728: gcc -c -g -O2  conftest.c >&5
configure:2728: $? = 0
configure:2760: result: no
configure:2888: checking location of HTSlib source tree
configure:2909: result: htslib-1.3.1
configure:3127: checking for NcursesW wide-character library
configure:3151: gcc -o conftest -g -O2   conftest.c  -lncursesw >&5
configure:3151: $? = 0
configure:3160: result: yes
configure:3180: checking for working ncursesw/curses.h
configure:3213: gcc -o conftest -g -O2   conftest.c  -lncursesw >&5
/opt/centos/devtoolset-1.0/root/usr/libexec/gcc/x86_64-redhat-linux/4.7.0/ld: /tmp/cceXsODk.o: undefined reference to symbol 'stdscr'
/opt/centos/devtoolset-1.0/root/usr/libexec/gcc/x86_64-redhat-linux/4.7.0/ld: note: 'stdscr' is defined in DSO /lib64/libtinfo.so.5 so try adding it to the linker command line
/lib64/libtinfo.so.5: could not read symbols: Invalid operation
collect2: error: ld returned 1 exit status
configure:3213: $? = 1
configure: failed program was:
| /* confdefs.h */
| #define PACKAGE_NAME "Samtools"
| #define PACKAGE_TARNAME "samtools"
| #define PACKAGE_VERSION "1.3.1"
| #define PACKAGE_STRING "Samtools 1.3.1"
| #define PACKAGE_BUGREPORT "samtools-help@lists.sourceforge.net"
| #define PACKAGE_URL "http://www.htslib.org/"
| #define HAVE_NCURSESW 1
| #define HAVE_CURSES 1
| /* end confdefs.h.  */
| 
|                         #define _XOPEN_SOURCE_EXTENDED 1
|                         #include <ncursesw/curses.h>
| 
| int
| main ()
| {
| 
|                         chtype a = A_BOLD;
|                         int b = KEY_LEFT;
|                         chtype c = COLOR_PAIR(1) & A_COLOR;
|                         attr_t d = WA_NORMAL;
|                         cchar_t e;
|                         wint_t f;
|                         int g = getattrs(stdscr);
|                         int h = getcurx(stdscr) + getmaxx(stdscr);
|                         initscr();
|                         init_pair(1, COLOR_WHITE, COLOR_RED);
|                         wattr_set(stdscr, d, 0, NULL);
|                         wget_wch(stdscr, &f);
| 
|   ;
|   return 0;
| }
configure:3222: result: no
configure:3244: checking for working ncursesw.h
configure:3277: gcc -o conftest -g -O2   conftest.c  -lncursesw >&5
conftest.c:13:46: fatal error: ncursesw.h: No such file or directory
compilation terminated.
configure:3277: $? = 1
configure: failed program was:
| /* confdefs.h */
| #define PACKAGE_NAME "Samtools"
| #define PACKAGE_TARNAME "samtools"
| #define PACKAGE_VERSION "1.3.1"
| #define PACKAGE_STRING "Samtools 1.3.1"
| #define PACKAGE_BUGREPORT "samtools-help@lists.sourceforge.net"
| #define PACKAGE_URL "http://www.htslib.org/"
| #define HAVE_NCURSESW 1
| #define HAVE_CURSES 1
| /* end confdefs.h.  */
| 
|                         #define _XOPEN_SOURCE_EXTENDED 1
|                         #include <ncursesw.h>
| 
| int
| main ()
| {
| 
|                         chtype a = A_BOLD;
|                         int b = KEY_LEFT;
|                         chtype c = COLOR_PAIR(1) & A_COLOR;
|                         attr_t d = WA_NORMAL;
|                         cchar_t e;
|                         wint_t f;
|                         int g = getattrs(stdscr);
|                         int h = getcurx(stdscr) + getmaxx(stdscr);
|                         initscr();
|                         init_pair(1, COLOR_WHITE, COLOR_RED);
|                         wattr_set(stdscr, d, 0, NULL);
|                         wget_wch(stdscr, &f);
| 
|   ;
|   return 0;
| }
configure:3286: result: no
configure:3308: checking for working ncurses.h
configure:3341: gcc -o conftest -g -O2   conftest.c  -lncursesw >&5
/opt/centos/devtoolset-1.0/root/usr/libexec/gcc/x86_64-redhat-linux/4.7.0/ld: /tmp/ccPm37nr.o: undefined reference to symbol 'stdscr'
/opt/centos/devtoolset-1.0/root/usr/libexec/gcc/x86_64-redhat-linux/4.7.0/ld: note: 'stdscr' is defined in DSO /lib64/libtinfo.so.5 so try adding it to the linker command line
/lib64/libtinfo.so.5: could not read symbols: Invalid operation
collect2: error: ld returned 1 exit status
configure:3341: $? = 1
configure: failed program was:
| /* confdefs.h */
| #define PACKAGE_NAME "Samtools"
| #define PACKAGE_TARNAME "samtools"
| #define PACKAGE_VERSION "1.3.1"
| #define PACKAGE_STRING "Samtools 1.3.1"
| #define PACKAGE_BUGREPORT "samtools-help@lists.sourceforge.net"
| #define PACKAGE_URL "http://www.htslib.org/"
| #define HAVE_NCURSESW 1
| #define HAVE_CURSES 1
| /* end confdefs.h.  */
| 
|                         #define _XOPEN_SOURCE_EXTENDED 1
|                         #include <ncurses.h>
| 
| int
| main ()
| {
| 
|                         chtype a = A_BOLD;
|                         int b = KEY_LEFT;
|                         chtype c = COLOR_PAIR(1) & A_COLOR;
|                         attr_t d = WA_NORMAL;
|                         cchar_t e;
|                         wint_t f;
|                         int g = getattrs(stdscr);
|                         int h = getcurx(stdscr) + getmaxx(stdscr);
|                         initscr();
|                         init_pair(1, COLOR_WHITE, COLOR_RED);
|                         wattr_set(stdscr, d, 0, NULL);
|                         wget_wch(stdscr, &f);
| 
|   ;
|   return 0;
| }
configure:3350: result: no
configure:3374: WARNING: could not find a working ncursesw/curses.h, ncursesw.h or ncurses.h
configure:3866: checking for zlib.h
configure:3866: gcc -c -g -O2  conftest.c >&5
configure:3866: $? = 0
configure:3866: result: yes
configure:3875: checking for inflate in -lz
configure:3900: gcc -o conftest -g -O2   conftest.c -lz   >&5
configure:3900: $? = 0
configure:3909: result: yes
configure:4051: creating ./config.status

## ---------------------- ##
## Running config.status. ##
## ---------------------- ##

This file was extended by Samtools config.status 1.3.1, which was
generated by GNU Autoconf 2.69.  Invocation command line was

  CONFIG_FILES    = 
  CONFIG_HEADERS  = 
  CONFIG_LINKS    = 
  CONFIG_COMMANDS = 
  $ ./config.status 

on vsc-server

config.status:795: creating config.mk
config.status:795: creating config.h
configure:5276: === configuring in htslib-1.3.1 (/home/zhuweiwei/bwadata/samtools-1.3.1/htslib-1.3.1)
configure:5339: running /bin/sh ./configure --disable-option-checking '--prefix=/usr/local'  '--enable-plugins' '--enable-libcurl' '--with-plugin-path=/home/zhuweiwei/bwadata/samtools-1.3.1/htslib-1.3.1' --cache-file=/dev/null --srcdir=.

## ---------------- ##
## Cache variables. ##
## ---------------- ##

ac_cv_c_compiler_gnu=yes
ac_cv_env_CC_set=
ac_cv_env_CC_value=
ac_cv_env_CFLAGS_set=
ac_cv_env_CFLAGS_value=
ac_cv_env_CPPFLAGS_set=
ac_cv_env_CPPFLAGS_value=
ac_cv_env_CURSES_LIB_set=
ac_cv_env_CURSES_LIB_value=
ac_cv_env_LDFLAGS_set=
ac_cv_env_LDFLAGS_value=
ac_cv_env_LIBS_set=
ac_cv_env_LIBS_value=
ac_cv_env_build_alias_set=
ac_cv_env_build_alias_value=
ac_cv_env_host_alias_set=
ac_cv_env_host_alias_value=
ac_cv_env_target_alias_set=
ac_cv_env_target_alias_value=
ac_cv_header_zlib_h=yes
ac_cv_lib_z_inflate=yes
ac_cv_objext=o
ac_cv_prog_ac_ct_CC=gcc
ac_cv_prog_cc_c89=
ac_cv_prog_cc_g=yes
ac_cv_sys_file_offset_bits=no
ac_cv_sys_largefile_CC=no
ax_cv_curses=yes
ax_cv_curses_color=no
ax_cv_curses_enhanced=no
ax_cv_curses_obsolete=no
ax_cv_curses_which=ncursesw
ax_cv_header_ncurses_h_with_ncursesw=no
ax_cv_header_ncursesw_curses_h=no
ax_cv_header_ncursesw_h=no
ax_cv_htslib=yes
ax_cv_htslib_which=source
ax_cv_ncursesw=yes

## ----------------- ##
## Output variables. ##
## ----------------- ##

CC='gcc'
CFLAGS='-g -O2'
CPPFLAGS=''
CURSES_LIB='-lncursesw'
DEFS='-DHAVE_CONFIG_H'
ECHO_C=''
ECHO_N='-n'
ECHO_T=''
EXEEXT=''
HTSDIR='htslib-1.3.1'
HTSLIB_CPPFLAGS='-Ihtslib-1.3.1'
HTSLIB_LDFLAGS='-Lhtslib-1.3.1'
Hinstall='#'
Hsource=''
LDFLAGS=''
LIBOBJS=''
LIBS=''
LTLIBOBJS=''
OBJEXT='o'
PACKAGE_BUGREPORT='samtools-help@lists.sourceforge.net'
PACKAGE_NAME='Samtools'
PACKAGE_STRING='Samtools 1.3.1'
PACKAGE_TARNAME='samtools'
PACKAGE_URL='http://www.htslib.org/'
PACKAGE_VERSION='1.3.1'
PATH_SEPARATOR=':'
SHELL='/bin/sh'
ac_ct_CC='gcc'
bindir='${exec_prefix}/bin'
build_alias=''
datadir='${datarootdir}'
datarootdir='${prefix}/share'
docdir='${datarootdir}/doc/${PACKAGE_TARNAME}'
dvidir='${docdir}'
exec_prefix='${prefix}'
host_alias=''
htmldir='${docdir}'
includedir='${prefix}/include'
infodir='${datarootdir}/info'
libdir='${exec_prefix}/lib'
libexecdir='${exec_prefix}/libexec'
localedir='${datarootdir}/locale'
localstatedir='${prefix}/var'
mandir='${datarootdir}/man'
oldincludedir='/usr/include'
pdfdir='${docdir}'
prefix='/usr/local'
program_transform_name='s,x,x,'
psdir='${docdir}'
sbindir='${exec_prefix}/sbin'
sharedstatedir='${prefix}/com'
subdirs=' htslib-1.3.1'
sysconfdir='${prefix}/etc'
target_alias=''

## ----------- ##
## confdefs.h. ##
## ----------- ##

/* confdefs.h */
#define PACKAGE_NAME "Samtools"
#define PACKAGE_TARNAME "samtools"
#define PACKAGE_VERSION "1.3.1"
#define PACKAGE_STRING "Samtools 1.3.1"
#define PACKAGE_BUGREPORT "samtools-help@lists.sourceforge.net"
#define PACKAGE_URL "http://www.htslib.org/"
#define HAVE_NCURSESW 1
#define HAVE_CURSES 1
#define HAVE_LIBZ 1

configure: exit 0
`

**Comment by chrisju** [comment]
> ./configure --enable-plugins --enable-libcurl --with-plugin-path=$PWD/htslib-1.3.1 --without-curses

By adding `--without-curses` can make and run successfully.

**Comment by jkbonfield** [comment]
Our #ifdefs are wrong given this scenario:

On Wed, May 18, 2016 at 06:26:48PM -0700, zz wrote:
> config.h
> /* Define to 1 if a SysV or X/Open compatible Curses library is present */
> #define HAVE_CURSES 1
> 
> /* Define to 1 if library supports color (enhanced functions) */
> /* #undef HAVE_CURSES_COLOR */
> 
> /* Define to 1 if library supports X/Open Enhanced functions */
> /* #undef HAVE_CURSES_ENHANCED */
> 
> /* Define to 1 if <curses.h> is present */
> /* #undef HAVE_CURSES_H */
> 
> /* Define to 1 if library supports certain obsolete features */
> /* #undef HAVE_CURSES_OBSOLETE */
> 
> /* Define to 1 if the Ncurses library is present */
> /* #undef HAVE_NCURSES */
> 
> /* Define to 1 if the NcursesW library is present */
> #define HAVE_NCURSESW 1
> 
> /* Define to 1 if <ncursesw/curses.h> is present */
> /* #undef HAVE_NCURSESW_CURSES_H */
> 
> /* Define to 1 if <ncursesw.h> is present */
> /* #undef HAVE_NCURSESW_H */
> 
> /* Define to 1 if <ncurses/curses.h> is present */
> /* #undef HAVE_NCURSES_CURSES_H */
> 
> /* Define to 1 if <ncurses.h> is present */
> /* #undef HAVE_NCURSES_H */

So we -DHAVE_CURSES and -DHAVE_NCURSESW, but haven't defined *any* of
the various CURSES_H defs.

The code in bam_tview_curses.c makes an assumption that if HAVE_CURSES
is set then at least one header file is defined.  Maybe this is an
error of the C code, but ideally the autoconf macro shouldn't be so
broken as to define HAVE_CURSES in this scenario.

bam_tview_curses.c:
    #ifdef HAVE_CURSES
    
    #if defined HAVE_NCURSESW_CURSES_H
    #include <ncursesw/curses.h>
    #elif defined HAVE_NCURSESW_H
    #include <ncursesw.h>
    #elif defined HAVE_NCURSES_CURSES_H
    #include <ncurses/curses.h>
    #elif defined HAVE_NCURSES_H
    #include <ncurses.h>
    #elif defined HAVE_CURSES_H
    #include <curses.h>
    #endif
    
    ...

    #else // !HAVE_CURSES                                                                                             

   #warning "No curses library is available; tview with curses is disabled."

Either we need to change that initial #ifdef to also have "and (foo_H
or bar_H)" or we fix the ax_with_curses macros.

James

-- 
James Bonfield (jkb@sanger.ac.uk) | Hora aderat briligi. Nunc et Slythia Tova
                                  | Plurima gyrabant gymbolitare vabo;
  A Staden Package developer:     | Et Borogovorum mimzebant undique formae,
https://sf.net/projects/staden/   | Momiferique omnes exgrabure Rathi. 


-- 
 The Wellcome Trust Sanger Institute is operated by Genome Research 
 Limited, a charity registered in England with number 1021457 and a 
 company registered in England with number 2742969, whose registered 
 office is 215 Euston Road, London, NW1 2BE.

**Comment by jmarshall** [comment]
The thing with the `*_H` \#defines is symptom rather than cause; see from the log

> WARNING: could not find a working ncursesw/curses.h, ncursesw.h or ncurses.h

This seems to be an interesting collision of changed GCC default settings, CentOS's [historic `-ltinfo` flakiness](https://bugs.centos.org/view.php?id=6668), and an `AX_WITH_CURSES` macro that until very recently didn't check for tinfo foibles (even though things like that are surely its raison d'être).

Anyway, as @chrisju has found, configuring `--without-curses` avoids all this, at the cost of disabling the `tview` command.  If you find you do need tview, configuring as follows should make these curses checks work correctly and enable you to build samtools with tview:

    ./configure LIBS=-ltinfo --enable-plugins --enable-libcurl --with-plugin-path=$PWD/htslib-1.3.1

We'll see what we can do to make this work without needing that workaround in future.

**Comment by daviesrob** [comment]
I've managed to reproduce this now.  The clue was:
```
/opt/centos/devtoolset-1.0/root/usr/libexec/gcc/x86_64-redhat-linux/4.7.0/ld
```
which means you're using gcc from the [developer toolset](https://access.redhat.com/documentation/en/red-hat-developer-toolset/).  It looks like the linker is set up slightly differently to the one that comes with CentOS 6.5, specifically it uses the `--no-add-needed` option.  There's some information about this on the Fedora website ([Gold incompatibilities](https://fedoraproject.org/wiki/GoldIncompatibilities) and [Understanding DSO link change](https://fedoraproject.org/wiki/UnderstandingDSOLinkChange)).

This change causes the test for `ncursesw/curses.h` to fail, but the failure is due to a linker error rather than the thing it was actually testing for (the existence of the header file).  The result is that the curses-related autoconf flags end up in an unexpected state.  

You can avoid this problem if you compile samtools with the default CentOS gcc instead of the devtools one.  If you want to use the devtools one, adding the `--add-needed` linker flag also solves it:

```
./configure --enable-plugins --enable-libcurl --with-plugin-path=$PWD/htslib-1.3.1 LDFLAGS='-Wl,--add-needed'
```

A newer `ax_with_curses.m4` might also fix it, although judging from the [changelog](http://git.savannah.gnu.org/gitweb/?p=autoconf-archive.git;a=history;f=m4/ax_with_curses.m4) you need quite a recent one.

This probably explains a few other CentOS build problems that we've seen.  @jmarshall, I can lend you a VM if you need something to test on.

**Comment by chrisju** [comment]
Both your commands are worked(I haven't test tview command). Thank you all.

**Comment by MatthewRalston** [comment]
Thanks. `--without-curses` solved my issue as well.
