### ISSUE TITLE
Description of "samtools bedcov" is misleading

### ISSUE THREAD

**Issue by dpryan79** [samtools/samtools#588]
See [here](https://www.biostars.org/p/195497/) for an example of what people assume it to be doing.

In short, bedcov is described as computing the "read depth per BED region". What it's actually returning is the "sum of per-base read depths per BED region". I haven't followed the discussion leading to the creation of the bedcov tool, so I can't say whether what it's doing is actually what was originally intended...but in any case it'd be nice if the description were tweaked.

**Comment by jmarshall** [comment]
Fixed by PR #594 / 26e1ea5b4a58e7bff0fac45c821e7fd2df45261d.

**Comment by WortJohn** [comment]
@dpryan79 How do you solve it? Does the new version bedcov subcommand calculate the read depth of each region, not the sum of per-base of each region?

**Comment by BhaktiLimaye** [comment]
@jmarshall  @lh3 
Please let me know , is there any tool in samtools package, which can give me number of reads mapped per bed region ?  I am interested in the breadth of coverage per bed region.
I was assuming that bedcov will give me "read depth per BED region". But then after reading this post, I came to know that it is wrong. 
I am looking for the similar output as coverageBed from bedtools. 
Thank you for the help
