### ISSUE TITLE
samtools faidx doesn't work correctly on fasta files with many millions of sequences

### ISSUE THREAD

**Issue by tfenne** [samtools/samtools#590]
I tried using `samtools faidx` to index the fasta file that contains all the sequences from NCBI's `nt` blast database.  A quick check using grep/awk/sed shows that the downloaded file (ftp://ftp.ncbi.nlm.nih.gov/blast/db/FASTA/nt.gz) contains 36,813,382 sequences, but faidx produces an index with only 3,600,907 entries, with no warning.

I tried uncompressing the file and got the same results:
```
$ samtools faidx nt.fa
$ wc -l nt.fa.fai
3600907 nt.fa.fai
$ egrep '^>' nt.fa | wc -l
36813382
```

**Comment by jmarshall** [comment]
Works for me.  On the _nt.gz_ file as downloaded I get `Cannot index files compressed with gzip, please use bgzip` `Could not build fai index nt.gz.fai` as expected; on the decompressed _nt.fa_ I get a 36813382-line _.fai_ file.

What version are you using?  Platform?

**Comment by tfenne** [comment]
Ugh, thanks @jmarshall .  I am using a version bundled with bwa.kit which I thought was fairly recent, but upon inspection is quite old (1.1).  I'll grab the latest release and try again.  Sorry.

Oh, and yes about the downloaded `nt.gz` - I had re-compressed it with pbgzip.

**Comment by jmarshall** [comment]
Yay for bundling :cry:

**Comment by tfenne** [comment]
Confirmed: latest version works just fine.  Sorry for the noise.
