### ISSUE TITLE
Being confrused about extracting  the unique reads from the bam file  when use the samtools 

### ISSUE THREAD

**Issue by yinyao41** [samtools/samtools#591]
HI,
  @EllenEWinchester   i extract the unqiue reads from bam file ,which one should i consider firstly ? filter XS to avoid multiple mapping  or  care MAPQ value 
This is my command line :SAMTOOLS view -q 40 -f 2 -o ${sample}.P.rmdup.Q40.bam ${sample}.P.rmdup.bam 
or 
samtools view -hf 0x2 alignments.bam | grep -v "XS:i:" > filtered.alignments.sam
which one should i use ? Should i need to get rid of the tags with XS:I?

**Comment by tk2** [comment]
Hi - we would recommend that you post this question on the samtools-help mailing list:

https://lists.sourceforge.net/lists/listinfo/samtools-help

as it appears to be a question about usage, rather than a bug in the code (github issues are primarily for bugs or new code contributions).
