### ISSUE TITLE
Result of a systematic screen for crashes.

### ISSUE THREAD

**Issue by charles-plessy** [samtools/samtools#60]
Hello,

the Cylab, Carnegie Mellon University, conduced a systematic screen for crashes on the whole Debian archive and reported to us their results for the samtools package with the following entries in our bug tracker.
- http://bugs.debian.org/715675 (bcftools)
- http://bugs.debian.org/716147 (razip)
- http://bugs.debian.org/716197 (maq2sam-long)
- http://bugs.debian.org/716199 (maq2sam-short)

Please let us know if you find these bugs reports useful, and when we can close them.

Best,
## 

Charles Plessy
Debian Med packaging team
http://www.debian.org/devel/debian-med
Tsurumi, Kanagawa, Japan

**Comment by daviesrob** [comment]
All referenced bugs were fixed a while back.
