### ISSUE TITLE
BAM->CRAM Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by nunofonseca** [samtools/samtools#600]
Hi,

samtools (Version: 1.3.1 using htslib 1.3.1) fails while creating a CRAM file from a BAM with 
Segmentation fault (core dumped)

Command: samtools view -C -T sam_ref.fa fail.bam -o fail.cram
Files are available here: 
http://www.ebi.ac.uk/~nf/tmp/sam_ref.fa
http://www.ebi.ac.uk/~nf/tmp/fail.bam

The fail.bam file is a small subset (only a few alignments) of the initial BAM.  

The fail.bam (and original BAM)  fail in the same place of the code (the output of gdb is below).
... 
(gdb) bt
#0  body (ctx=0x709ef0, data=<value optimized out>, size=18446744073697102976) at md5.c:148
#1  0x0000000000468b25 in hts_md5_update (ctx=0x709ef0, data=0x70cdd6, size=<value optimized out>) at md5.c:262
#2  0x0000000000498b4a in cram_encode_container (fd=0x71ac10, c=0x7504a0) at cram/cram_encode.c:1367
#3  0x00000000004a01e9 in cram_flush_container (fd=0x71ac10, c=0x7504a0) at cram/cram_io.c:3240
#4  0x00000000004a1343 in cram_close (fd=0x71ac10) at cram/cram_io.c:4335
#5  0x0000000000461f3d in hts_close (fp=0x71ab80) at hts.c:835
#6  0x0000000000411b5c in check_sam_close (subcmd=0x4c83f2 "view", fp=<value optimized out>, fname=0x6e2270 "fail.cram", null_fname=0x4c4a6e "standard output", retp=0x7fffffffde0c) at sam_view.c:221
#7  0x00000000004146db in main_samview (argc=7, argv=0x7fffffffdf30) at sam_view.c:495
#8  0x00000031d841ed5d in __libc_start_main () from /lib64/libc.so.6
#9  0x000000000040d959 in _start ()

Thanks,

Nuno

**Comment by jkbonfield** [comment]
On Mon, Aug 01, 2016 at 03:22:58AM -0700, Nuno Fonseca wrote:
> samtools (Version: 1.3.1 using htslib 1.3.1) fails while creating a CRAM file from a BAM with 
> Segmentation fault (core dumped)

I can reproduce the problem.  Many thanks for the clear report and
data.  I'll investigate the cause.

James

-- 
James Bonfield (jkb@sanger.ac.uk) | Hora aderat briligi. Nunc et Slythia Tova
                                  | Plurima gyrabant gymbolitare vabo;
  A Staden Package developer:     | Et Borogovorum mimzebant undique formae,
https://sf.net/projects/staden/   | Momiferique omnes exgrabure Rathi. 


-- 
 The Wellcome Trust Sanger Institute is operated by Genome Research 
 Limited, a charity registered in England with number 1021457 and a 
 company registered in England with number 2742969, whose registered 
 office is 215 Euston Road, London, NW1 2BE.

**Comment by jkbonfield** [comment]
The cause is a lack of error checking (in both Samtools and Scramble) for this specific scenario.  Your sequences **start** beyond the end of the reference.

Ie:

```@SQ	SN:supercont12.10	LN:125404``` vs sequences with start pos 174919.

The failure is in attempting to compute the md5sum for the locally covered region of the reference sequence.   I have a trivial fix that I'll push soon to fix this.  The rest of the code behaves OK and the sequences end up non-reference encoded (about the only thing that can be done with broken inputs).
