### ISSUE TITLE
samtools depth -b <bed> bam didn't quit after finished output.

### ISSUE THREAD

**Issue by ltnetcase** [samtools/samtools#606]
After updated to samtools 1.3.1, using:
        
       samtools depth -b test.bed test.bam

will stuck after all results have been output.

**Comment by jmarshall** [comment]
With `-b` it still streams through the entire file, filtering each read based on the BED regions.  To use the index to speed this up, combine `-b` with an appropriate `-r` option.

If you need further details please post on the [samtools-help mailing list](http://www.htslib.org/support/), where there are many more people sharing the load of answering questions, and many more reading postings and learning from the resulting conversations.
