### ISSUE TITLE
rmdup segfault

### ISSUE THREAD

**Issue by jdmontenegro** [samtools/samtools#614]
I just run into a segfault problem with the latest dev version of samtools.
After sorting and filtering the bam file I run:

$> samtools rmdup in.sorted.bam out.sorted.d.bam

[bam_rmdup_core] processing reference 1A_concat...
[bam_rmdup_core] processing reference 1B_concat...
[bam_rmdup_core] processing reference 1D_concat...
[bam_rmdup_core] processing reference 2A_concat...
[bam_rmdup_core] processing reference 2B_concat...
[bam_rmdup_core] processing reference 2D_concat...
[bam_rmdup_core] processing reference 3A_concat...
[bam_rmdup_core] processing reference 3B_concat...
[bam_rmdup_core] processing reference 3D_concat...
[bam_rmdup_core] processing reference 4A_concat...
[bam_rmdup_core] processing reference 4B_concat...
[bam_rmdup_core] processing reference 4D_concat...
[bam_rmdup_core] processing reference 5A_concat...
[bam_rmdup_core] processing reference 5B_concat...
[bam_rmdup_core] processing reference 5D_concat...
[bam_rmdup_core] processing reference 6A_concat...
[bam_rmdup_core] processing reference 6B_concat...
[bam_rmdup_core] processing reference 6D_concat...
[bam_rmdup_core] processing reference 7A_concat...
[bam_rmdup_core] processing reference 7B_concat...
[bam_rmdup_core] processing reference 7D_concat...
[bam_rmdup_core] processing reference Chapman_unm...
[bam_rmdup_core] processing reference Unmapped_IDBAUD...
[bam_rmdup_core] processing reference gi|14017551|ref|NC_002762.1|...
[bam_rmdup_core] processing reference gi|81176508|ref|NC_007579.1|...
[bam_rmdup_core] processing reference 6B_concat...
Segmentation fault

For some reason, after finishing processing all the references, it goes back to the 6B_concat reference and then breaks. Is that normal behaviour? I have run into the same problem with versions 1.3.1 and 0.1.19

Regards,

Juan Daniel

**Comment by kirkmcclure** [comment]
It appears that the data are not sorted as rmdup expects (RNAME primary, then POS).
This would explain the repetition of 6B_concat. (The input is processed once; it does not 'go back'.)

To demonstrate reference repetition for improperly (QNAME, in this example) sorted data:
`./samtools view -b test/dat/view.001.sam | ./samtools sort -n > /tmp/view.001.bam
./samtools rmdup /tmp/view.001.bam /tmp/out.Issue614.bam                      
[bam_rmdup_core] processing reference ref1...
[bam_rmdup_core] processing reference ref2...
[bam_rmdup_core] processing reference ref1...
[bam_rmdup_core] processing reference ref2...
[bam_rmdup_core] processing reference ref1...
[bam_rmdup_core] processing reference ref2...
[bam_rmdup_core] 0 / 6 = 0.0000 in library 'Library 1'
[bam_rmdup_core] 0 / 6 = 0.0000 in library 'Library 2'
[bam_rmdup_core] 0 / 2 = 0.0000 in library '    '
`

**Comment by kirkmcclure** [comment]
The original data should be re-tested with a recent build.

After this problem was reported, a bug that caused rmdup segmentation faults was corrected; [Issue #538](https://github.com/samtools/samtools/issues/538).

**Comment by jkbonfield** [comment]
The existing rmdup code isn't supported in its current state and we don't recommend anyone to be using it.  Indeed we even removed it for a while.  https://github.com/samtools/samtools/blob/develop/NEWS#L144-L146

The good news is that we are working on a rewrite (perhaps "markdup").

Closing this issue with the assumption that the issue was fixed in #538.
