### ISSUE TITLE
Reheader bams in place

### ISSUE THREAD

**Issue by pd3** [samtools/samtools#618]
The in place option of reheader does not work, the command `samtools reheader -i hdr.txt file.bam` streams the file to stdout. If it is not possible to do in-place reheadering for bams, perhaps the command could complain instead of dumping the binary output to terminal.

**Comment by ycl6** [comment]
I like to report the same problem, with samtools version: 1.3.1 (using htslib 1.3.1)

**Comment by jkbonfield** [comment]
Dumping binary data to a terminal is unfriendly and it probably ought to check it's a terminal first before dumping output (but it's acceptable to output to stdout if it's a pipe).  However this isn't the only tool to do that.

However ```reheader -i``` cannot write back to the file as this is basically impossible in the BAM format.  Agreed it should simply report a failure at that point.

**Comment by dantaki** [comment]
I get the same error with this version

```
Version: 1.7 (using htslib 1.7)
```

**Comment by map2085** [comment]
same in version 1.8

**Comment by odoublewen** [comment]
samtools 1.9 - bug still present
