### ISSUE TITLE
samtools sort fails with "Output header text too long"

### ISSUE THREAD

**Issue by Unode** [samtools/samtools#633]
Running:

    samtools sort --reference genes.fna -T /tmp/samsort. -@ 10 -O BAM data.bam > genes.sorted.bam

is currently failing with the error:

    [bam_sort_core] merging from 20 files...
    [finish_merged_header] Output header text too long

This doesn't happen with all datasets. Some work fine others don't.

The reference file (genes.fna) contains roughly 88M sequences and one of the failing BAM/SAMs roughly 41M entries (lines).

It seems like I'm hitting a limit as the code where that message comes from reads that the header is larger than an INT32.

Is there any solution or workaround to this?

**Comment by jkbonfield** [comment]
Indeed I see the code in bam_sort.c:

```
    // Check output text size
    txt_sz = (ks_len(&merged_hdr->out_hd)
              + ks_len(&merged_hdr->out_sq)
              + ks_len(&merged_hdr->out_rg)
              + ks_len(&merged_hdr->out_pg)
              + ks_len(&merged_hdr->out_co));
    if (txt_sz >= INT32_MAX) {
        fprintf(stderr, "[%s] Output header text too long\n", __func__);
        return NULL;
    }
```

The header length ```hdr->l_text``` is a uint32_t so in theory this check could be changed to UINT32_MAX, but I haven't tried it to see if there are any locations that treat it as a signed value and choke.   The BAM spec labels l_text as int32_t though and again I don't know the impact of trying to make it unsigned without testing this.  It only buys us a factor of 2 expansion too though.

I'm struggling to think of ways to solve this given a hard limit in the BAM specification itself.  CRAM has the same issue, with a signed 32-bit value for uncompressed block size.  All I can think of is shrinking your header by other means.  Eg do you have UR: fields in the @SQ lines which could be discarded safely, or similar tweaks?

**Comment by Unode** [comment]
Hi @jkbonfield,

I don't think I can do much about reducing `@SQ` line content.
This is how they currently look like:

    @SQ     SN:1292726.TMREA178261.MTHC23190       LN:1098

The large number of them seems to be the main issue, **88M** of them.

**Comment by jkbonfield** [comment]
In that case I'm sorry but I'm not really sure what else we can do here.  88M of those is already around 4Gb of text, so even making it unsigned is pushing the boundaries and there's no way it'd work in CRAM with the additional M5 strings.  Theoretically it's possible to keep it all in BAM without text headers at all, using just the binary name+length fields, but most tools automatically convert this to textual header and will run into the int32 limit again.

The file formats simply weren't designed around having that many references.

**Comment by jkbonfield** [comment]
Actually it's sort of possible, but ghastly!  Using a [sexagesimal](https://en.wikipedia.org/wiki/Sexagesimal) system of encoding numbers you can get to 88 million seq ids with just 5 characters (say A-Za-z0-7).  This would shrink your lines sufficiently that they (just) fit inside 2Gb.  You'd then need an external file as a lookup table to figure out your reference names to sexagesimal encoding.  Ghastly, but it's about the best that is possible.

PS.  What produced this data?  I assume it's a mammothly fragmented sequence assembly.

**Comment by Unode** [comment]
Thanks for the feedback. I'll see if I can workaround the issue with your suggestion.
But just to be sure I understand this before getting my hands dirty and hitting another roadblock ahead, in the example I included above:  

    @SQ     SN:1292726.TMREA178261.MTHC23190       LN:1098

Would this record occupy something like 34 bytes (SN + LN + padding -> 29 + 4 + 1).

Not an assembly but a huge reference set. Splitting this into smaller sets may be an option but complicates things a little.

**Comment by jkbonfield** [comment]
Closing this issue as sadly it is beyond the bounds of what is possible within either the BAM or CRAM specification.

If you wish to propose amendments to the file formats themselves (although we'd need some concrete use case examples I think) then please submit to the hts-specs repository.

PS. Regarding the above query - yes; the header is purely a textual representation.

**Comment by Unode** [comment]
@jkbonfield Thanks for the feedback. Currently trying out your suggestion of reducing the header footprint as a temporary measure. I'll post the limitation to the other repository later.

Thanks again.
