### ISSUE TITLE
samtools-1.3 sort creates way too many tmp files

### ISSUE THREAD

**Issue by mmokrejs** [samtools/samtools#636]
Hi,
  I just a had job which created 6286541 files during a single sorting step:

`samtools sort -@ 15 -m G -O bam -o xxxx-PB.bwa.sorted.bam xxxx-PB.bwa.bam`

  I ended up with:
`xxxx-PB.bwa.bam.tmp.0000.bam` to `xxxx-PB.bwa.bam.tmp.##########.bam` . Each of the files had size about 43287 bytes. Why so small?

  From issue #603 I infer my file limits were unset and bwa went loose. Would you please install a meaningful default value in n_files variable (or whichever is internally used)? I do not think retriction my parent shell's limits is the right way to 'fix this'.

```
$ ulimit -a
core file size          (blocks, -c) 0
data seg size           (kbytes, -d) unlimited
scheduling priority             (-e) 0
file size               (blocks, -f) unlimited
pending signals                 (-i) 515365
max locked memory       (kbytes, -l) unlimited
max memory size         (kbytes, -m) unlimited
open files                      (-n) 1048576
pipe size            (512 bytes, -p) 8
POSIX message queues     (bytes, -q) 819200
real-time priority              (-r) 0
stack size              (kbytes, -s) 10240
cpu time               (seconds, -t) unlimited
max user processes              (-u) 1024
virtual memory          (kbytes, -v) unlimited
file locks                      (-x) unlimited
$
```

  I had the impression bwa in some `for loop` just kept creating tmp files because it received some temporary error from the filesystem upon file creation request and it just kept asking for yet another tmp file to be created. Is there any code like this in the bam_sort.c or related code? I am just guessing.

  What we saw with strace samtools was (continually looping):
```


1486561790.173665 futex(0x2b6711b7b9d0, FUTEX_WAIT, 106331, NULL) = 0
1486561790.204759 clone(child_stack=0x2b6711b7aff0, flags=CLONE_VM|CLONE_FS|CLONE_FILES|CLONE_SIGHAND|CLONE_THREAD|CLONE_SYSVSEM|CLONE_SETTLS|CLONE_PARENT_SETTID|CLONE_CHILD_CLEARTID, parent_tidptr=0x2b6711b7b9d0, tls=0x2b6711b7b700, child_tidptr=0x2b6711b7b9d0) = 106335
1486561790.204941 futex(0x2b6711b7b9d0, FUTEX_WAIT, 106335, NULL) = 0
1486561790.219479 clone(child_stack=0x2b6711b7aff0, flags=CLONE_VM|CLONE_FS|CLONE_FILES|CLONE_SIGHAND|CLONE_THREAD|CLONE_SYSVSEM|CLONE_SETTLS|CLONE_PARENT_SETTID|CLONE_CHILD_CLEARTID, parent_tidptr=0x2b6711b7b9d0, tls=0x2b6711b7b700, child_tidptr=0x2b6711b7b9d0) = 106336
1486561790.219686 futex(0x2b6711b7b9d0, FUTEX_WAIT, 106336, NULL) = 0
1486561790.231003 clone(child_stack=0x2b6711b7aff0, flags=CLONE_VM|CLONE_FS|CLONE_FILES|CLONE_SIGHAND|CLONE_THREAD|CLONE_SYSVSEM|CLONE_SETTLS|CLONE_PARENT_SETTID|CLONE_CHILD_CLEARTID, parent_tidptr=0x2b6711b7b9d0, tls=0x2b6711b7b700, child_tidptr=0x2b6711b7b9d0) = 106337
1486561790.231172 futex(0x2b6711b7b9d0, FUTEX_WAIT, 106337, NULL) = 0
1486561790.250437 clone(child_stack=0x2b6711b7aff0, flags=CLONE_VM|CLONE_FS|CLONE_FILES|CLONE_SIGHAND|CLONE_THREAD|CLONE_SYSVSEM|CLONE_SETTLS|CLONE_PARENT_SETTID|CLONE_CHILD_CLEARTID, parent_tidptr=0x2b6711b7b9d0, tls=0x2b6711b7b700, child_tidptr=0x2b6711b7b9d0) = 106338
1486561790.250648 futex(0x2b6711b7b9d0, FUTEX_WAIT, 106338, NULL) = 0
1486561790.262180 clone(child_stack=0x2b6711b7aff0, flags=CLONE_VM|CLONE_FS|CLONE_FILES|CLONE_SIGHAND|CLONE_THREAD|CLONE_SYSVSEM|CLONE_SETTLS|CLONE_PARENT_SETTID|CLONE_CHILD_CLEARTID, parent_tidptr=0x2b6711b7b9d0, tls=0x2b6711b7b700, child_tidptr=0x2b6711b7b9d0) = 106339
1486561790.262336 futex(0x2b6711b7b9d0, FUTEX_WAIT, 106339, NULL) = 0
1486561790.274038 clone(child_stack=0x2b6711b7aff0, flags=CLONE_VM|CLONE_FS|CLONE_FILES|CLONE_SIGHAND|CLONE_THREAD|CLONE_SYSVSEM|CLONE_SETTLS|CLONE_PARENT_SETTID|CLONE_CHILD_CLEARTID, parent_tidptr=0x2b6711b7b9d0, tls=0x2b6711b7b700, child_tidptr=0x2b6711b7b9d0) = 106340
```

**Comment by dpryan79** [comment]
Try specifying a more meaningful amount of memory than `G`, such as `1G`.

**Comment by mmokrejs** [comment]
Indeed, was an unset variable. Thanks @dpryan79 !

**Comment by agarwal** [comment]
This was [reported](https://sourceforge.net/p/samtools/mailman/samtools-help/thread/CAMu2m2LAMvGdr-CY-gYTwtVe3BYTTbz--1MFF61B807Ds2jZKg%40mail.gmail.com/#msg33575059) on the mailing list in March 2015. There was a reply stating it would be fixed in samtools 1.3, but seems the fix didn't make it in.

**Comment by daviesrob** [comment]
It was fixed in #581 (now merged).  It enforces a minimum size of about 1MiB - sort will refuse to run if you don't ask for this much.

It hasn't made it to a release yet (hopefully soon...) but the 'develop' branch has this protection.  It does catch the mistake here:

```
$ ./samtools sort -@ 15 -m G -O bam -o xxxx-PB.bwa.sorted.bam xxxx-PB.bwa.bam
[bam_sort] -m setting (0 bytes) is less than the minimum required (1M).

Trying to run with -m too small can lead to the creation of a very large number
of temporary files.  This may make sort fail due to it exceeding limits on the
number of files it can have open at the same time.

Please check your -m parameter.  It should be an integer followed by one of the
letters K (for kilobytes), M (megabytes) or G (gigabytes).  You should ensure it
is at least the minimum above, and much higher if you are sorting a large file.
```

**Comment by agarwal** [comment]
If I understand #581 correctly, it sets a minimum but doesn't check that the input argument follows the required format. Is that better? Before samtools continued with an absurdly low value, but now it continues with a reasonable value that is completely different than what the user intended. Why not simply check the input argument format and give the user an error right away.

**Comment by daviesrob** [comment]
If you try it, you will find it prints out the message above and exits with a non-zero return code.  It does not try to do anything else.

**Comment by agarwal** [comment]
Right. Apologies, I misread your output text.

**Comment by mmokrejs** [comment]
Hi,
  thank you for all your responses, they were indeed helpful. However, I should note that I did not hit any per-process limits like a number of opened files but like other users I brought down to its knees our LustreFS (the metadata server actually). So, I wonder whether the below text is really a proper description:

```
Trying to run with -m too small can lead to the creation of a very large number
of temporary files.  This may make sort fail due to it exceeding limits on the
number of files it can have open at the same time.
```

I could have stated the error message I received from samtools:

`[E::hts_open_format] fail to open file 'XXXX-PB.bwa.bam.tmp.6283688.bam'`

Actually many files with randomized numerical portion of the filename. That was actually the reason I thought samtools kept asking for yet another tmp file to be created in some loop. Why didn't samtools realize at the very first moment a filename was not not created? Why did it proceed that far into its downstream code?

I think `-m 1M` is too low. Who has a machine with just $threads*1M of memory available for bionformatics? I think for my exome alignments with 5.6GB BAM files and 16 threads the default will be still killing our machines (why not 256M by default?). The current defaults are simply not sane. Can't you compute relatively easily how much `(free memory * 0.85) / $threads` gives? That is what I am doing in my shell wrapper:

```
threads=16

# get amount of available memory
total_memory=`free -g | grep 'Mem:' | awk '{print $2}'`

# go for 85% of the free mem
ask_for_memory=`echo "$total_memory * 0.95" | bc | sed -e 's/\..*//'`

# set memory for java programs
java_memory="-Xmx${ask_for_memory}g"

# set memory per thread, like samtools
gb_mem_per_thread=`echo "$ask_for_memory / $threads" | bc | sed -e 's/\..*//'`

# for Picard's SortSam and MergeSamFiles set number of entries per tempfile batch, use 250000 per GB of available RAM
MAX_RECORDS_IN_RAM=`echo "$ask_for_memory * 250000" | bc | sed -e 's/\..*//'`
# https://www.biostars.org/p/105489/
```

**Comment by dpryan79** [comment]
I really hate it when tools decide to use some large percentage of free memory. That tends to work horribly on shared servers.

**Comment by mmokrejs** [comment]
I would tend to agree but basing the calculations using the actually free mem (unlike total mem) is a good guess. It is better to rely on the kernel's decision what can be done with the memory available, at worst trigger some swap activity. I don't think in general this is a way to trigger 'Out of memory' (OOM) condition but finally, Linux these days has a good code to find the victim process and kill it. More importantly, it is better to kill user's samtools instance then to kill a fileserver shared by all users.

Either way, 1M is not enough for any common use case IMHO. An average user will run under 1-4 threads and the machine will have at least 2GB of RAM. Placing the default to 256M is a sane default, even 256M would be IMHO. Provided a user can lower the value I find it perfectly OK.

Alternatively I propose a sanity check that samtools will exit cleanly would the number of temp files exceed 5k. Already having 30k files in a single directory is a disaster; I had 6.3M files and the reporter from https://sourceforge.net/p/samtools/mailman/samtools-help/thread/CAMu2m2LAMvGdr-CY-gYTwtVe3BYTTbz--1MFF61B807Ds2jZKg%40mail.gmail.com/#msg33575059 had 83M files.

**Comment by dpryan79** [comment]
The default is 768M currently...

**Comment by jkbonfield** [comment]
Any calculation based on memory available will simply lead to non-deterministic behaviour and a source of confusion for the users (cough... hello Java!).  The default should be something appropriate that works on most systems, with the flexibility to adjust.  This is exactly what we have and I see no reason to change that.

1M is a **minimum** value for when users try to drive the memory limit too low.  It is most definitely not the default nor recommended.

As for a maximum number of files, this may work, but I'm wary of something low as many file systems are quite capable of dealing 100k, just not lustre.  Arguably it should be checking ulimit and estimating up front if able (eg a rough back of the envelope calculation based on file size).  If it knows it'll get close to that limit then fail early.  This gives the user and indeed even the sysadmin the ability to control how many files may be open simultaneously without artificially creating additional barriers to the software.
