### ISSUE TITLE
OS X Deadlock issues on current develop

### ISSUE THREAD

**Issue by mp15** [samtools/samtools#639]
3a7d0f02e8693620014cb59aea17028c5ab427e2 has random deadlock issues on OS X.

**Comment by jkbonfield** [comment]
Found and fixed it, testing right now on other platforms.  It's an accidental 2nd unlock of the same mutex.

https://github.com/samtools/htslib/blob/develop/bgzf.c#L1144

I guess this doesn't matter on Linux, but it's a clear mistake.
