### ISSUE TITLE
Samtools stats does not limit coverage calculation to the target specified with -t

### ISSUE THREAD

**Issue by jkmatila** [samtools/samtools#640]
Hi,

When running `samtools stats` and specifying the target regions with the `-t` option, the reported coverage histogram is not strictly limited to the target regions.  Instead, it reports coverage for the whole length of all reads which overlap at all with the target regions, including portions of the reads which extend outside the target.

Is this by design? Would it be possible to limit the coverage calculation to only the parts of the reads within the target?

**Comment by ChenYuelong** [comment]
Same request too. No limit within the target may fussy for target region coverage calculation。
