### ISSUE TITLE
bcftools call piping seems broken

### ISSUE THREAD

**Issue by ChevyXu** [samtools/samtools#647]
I used the command :
nohup samtools mpileup -gsf ~/reference/genome/hg19/hg19.fa unmapped_contigs.sort.bam | bcftools call -vmO v -o variant.vcf &
and got the error :
[E::vcf_hdr_read] no sample line
Failed to open: -

but the command works fine :
samtools mpileup -gsf ~/reference/genome/hg19/hg19.fa unmapped_contigs.sort.bam | bcftools call -vmO v -o variant.vcf

I have no ideas what  happened, so come here for help.
thanks

**Comment by mcshane** [comment]
Could you do something like:
```
nohup sh -c "samtools mpileup ... | bcftools call ..." &
```
as suggested here: http://stackoverflow.com/a/26912222 ?

**Comment by ChevyXu** [comment]
problem solved, thanks
