### ISSUE TITLE
why we need recalculate MD/NM tags from a orign bam ?

### ISSUE THREAD

**Issue by zeronot** [samtools/samtools#648]
HI,
      A BAM has their own MD tag and NM tag , why we need to recalculate MD/NM tags ? MD or NM from the origin bam is wrong ??

Best !

**Comment by jkbonfield** [comment]
Closing this as it is not an appropriate question here.

Samtools has the ability to recalculate MD and NM tags (via ```samtools calmd```), but it is not a requirement and you do not have to use it.  That said, some pipelines will deliberately recalculate even when a BAM file has MD and NM as some high profile aligners have bugs in where very rarely they will emit incorrect MD and NM tags.
