### ISSUE TITLE
Bam_sort function problem with memory deallocation

### ISSUE THREAD

**Issue by RaiaN** [samtools/samtools#65]
Hello. Thank you for your fantastic tool! We often use it and so i have the next issue: i have a problem regarding -m option in bam_sort function. I'll describe more clearly:
1) We integtared Samtools in our software (Ugene) and executed the bam_sort function with -m option value equal to size of input BAM file by 5. As a result we got too long memory deallocation loop at the end of this function.
2) I'm not clearly understand what does mean "Approximately the maximum required memory". How correctly define amount of required memory? Will it strongly depend on size of input file?
3) We executed bam_sort function with -m option value that is ten times less than size of input file and it stored sorted chunks at the HDD. Size of all sorted chunks was the same as input file size. What will will be with big BAM files? 

Best regards, 
Peter

Samtools v.0.1.18

**Comment by valeriuo** [comment]
Issue no longer present as of [version 1.8](https://github.com/samtools/samtools/releases/tag/1.8)
Tried successfully with a 2.4G BAM file. Also, **valgrind** reports no leaks.
