### ISSUE TITLE
samtools BAQ question

### ISSUE THREAD

**Issue by prasundutta87** [samtools/samtools#655]
Hi, according to http://samtools.sourceforge.net/mpileup.shtml, BAQ strategy is invoked by default in mpileup. You also have -E as one of your options to recalculate BAQ. I would be grateful if someone could kindly clear if BAQ is calculated by default from BQ (original phred scaled base quality score) in the default settings or I need to use -E and what is the exact difference between the two.

I am using samtools 1.3.

Is there an updated document/recent publication about mpileup except than the one I pasted above?

**Comment by daviesrob** [comment]
`BQ` here refers to the "Offset to base alignment quality (BAQ)" optional tag.  The original quality scores use the tag `OQ`.  See [the SAMtags specification](http://samtools.github.io/hts-specs/SAMtags.pdf) for the definitions.

The default is to only calculate `BQ` if the tag is not already present.

The -E option makes mpileup remove any existing `BQ` tag, and then recalculate the values and store them in a new `BQ` tag.

The -B option turns off BAQ realignment.  You won't get any new tags, but existing ones will be left alone.

I don't know if there's any newer documentation than your link.  @pd3 may be able to help if there is anything better.

**Comment by pd3** [comment]
There is a description of the math in the document down on this page http://samtools.github.io/bcftools/

**Comment by prasundutta87** [comment]
Thank you for sharing this. I may need some time to digest the math to actually understand what's going on inside.

**Comment by prasundutta87** [comment]
I am also checking this document: https://samtools.github.io/hts-specs/SAMv1.pdf. 

Please correct me if I am misunderstanding the flow of events-

So the 11th column in a SAM file which refers to the QUAL (ASCII of Phred-scaled base QUALity+33) is composed of OQ (original perbase quality). 

When I run mpileup, by default, BQ (or BAQ) is calculated and the recalibrated data is stored in the mpileup file which in turn is used by bcftools call for calling variants.

**Comment by pd3** [comment]
When the BAQ qualities are not present in the input BAM, they are calculated on the fly in https://github.com/samtools/htslib/blob/develop/realn.c#L85. mpileup does not store the values after using them, so if you are interested what they look like, you could add a debug output here https://github.com/samtools/bcftools/blob/develop/mpileup.c#L232

**Comment by prasundutta87** [comment]
Thank you for sharing these. I am closing this issue now.

**Comment by lrkai123** [comment]
Hello, may I ask when I need to redo the BAQ ？

**Comment by lrkai123** [comment]
Thank you for your reply ,It helps me a lot !
