### ISSUE TITLE
Core dump when processing large sam header

### ISSUE THREAD

**Issue by bbushnell** [samtools/samtools#67]
Samtools 0.1.19 and later do not seem to be able to handle more than 2GB of header data.  Error message:
append_text FIXME: 2147483672>=0, x=2147483648,y=4294967296
Aborted (core dumped)

Samtools 0.1.18 is able to handle these files.

**Comment by jelber2** [comment]
Had the same error as @bbushnell with samtools 0.1.19-96b5f2294a, samtools 1.6 (using htslib 1.6) fixed the problem
