### ISSUE TITLE
samtools faidx exits when querying a non existing sequence

### ISSUE THREAD

**Issue by jregalad** [samtools/samtools#673]
when extracting sequences from an indexed fasta file, if query is not present in the fasta, samtools exits without looking for the rest of the queries. Is it possible for samtools to just ignore any queries it does not find?

**Comment by tseemann** [comment]
I think asking for a non-existent sequence is a good reason to die and exit with non-zero?

```
% cat test.fa
>I
GATTACA
>II
TAGATAG
>III
CATCAGC

% samtools faidx test.fa II
>II
TAGATAG

% samtools faidx test.fa I X III
>I
GATTACA
>X
[W::fai_fetch] Reference X not found in FASTA file, returning empty sequence
Failed to fetch sequence in X

% echo $?
1
```
