### ISSUE TITLE
Fast way to get per-site counts of 4 alleles from mapped reads

### ISSUE THREAD

**Issue by snayfach** [samtools/samtools#685]
I need to use samtools to obtain counts of the 4 bases (A,T,G,C) at each position in a reference sequence from a set of mapped reads. My desired output would be something like: chrom, position, readcount_a, readcount_t, readcount_g, readcount_c.

Unfortunately using samtools mpileup to generate a VCF file doesn't work, because only reference and non-reference allele counts are stored. So when there are multiple non-reference alleles it messes things up.

I can parse this information directly from the pileup format using python, but this is relatively slow, especially when read depth is very high.

I also tried using pysam to call samtools mpileup and parse the output, but this was even slower.

Any help with the problem would be greatly appreciated.

Thanks!
Stephen

**Comment by kyleabeauchamp** [comment]
Pysam count_coverage

**Comment by snayfach** [comment]
Perfect. Thank you!

**Comment by mfoll** [comment]
Also check https://github.com/gatoravi/mpileup2readcounts or our improved version that supports indels and multi-sample mpileups: https://github.com/IARCbioinfo/mpileup2readcounts
