### ISSUE TITLE
samtools 1.4.1 bai indices created with multiple threads can lose reads

### ISSUE THREAD

**Issue by chapmanb** [samtools/samtools#687]
We've been working on tracking down an issue with missing reads (chapmanb/bcbio-nextgen#1966) that @pfpjs isolated to a problem with indexing using samtools 1.4.1 and the `-@` threading option. With `-@`, the resulting index cause subsequent retrievals to miss files in the region. Here is a reproducible test case where we get different number of total reads in a region using the same input file indexed two ways with samtools:
```
wget -c https://s3.amazonaws.com/chapmanb/testcases/samtools/NA12878-sort-X_62863839_99551893-prep-prealign.bam
INPUTBAM=NA12878-sort-X_62863839_99551893-prep-prealign.bam

# create index using single-threaded samtools
echo "Single thread"
cp $INPUTBAM NA12878-samtools-index.bam
samtools index NA12878-samtools-index.bam
samtools idxstats NA12878-samtools-index.bam | grep ^X
samtools view -c NA12878-samtools-index.bam X:99551000-99553000

# create index using multi-threaded samtools
echo "Multi thread"
cp $INPUTBAM NA12878-samtools-mt-index.bam
samtools index -@ 1 NA12878-samtools-mt-index.bam
samtools idxstats NA12878-samtools-mt-index.bam | grep ^X
samtools view -c NA12878-samtools-mt-index.bam X:99551000-99553000
```
This reports:
```
Single thread
X       155270560       842966  706
1084
Multi thread
X       155270560       842966  706
274
```
So we see the same number of total reads with idxstats but only get 274 reads when retrieving using ranges from a bai generated by the `-@` flag, instead of the 1084 that are present.

Thanks for looking into this and please let us know if we can provide any other information to help.

**Comment by daviesrob** [comment]
Thanks for the report and the very useful test case.

It looks like this is due to the threaded version of bgzf_read_block() reading a stale value of block_address at the end of the file.  That gets passed to hts_idx_finish(), resulting in a broken index.

Patch should be arriving soon.

**Comment by chapmanb** [comment]
Thanks so much for this fix. We've tested and put samtools multithreaded indexing back into bcbio with the 1.5 release. Thank you for all the great work on samtools development.
