### ISSUE TITLE
autoconf warnings

### ISSUE THREAD

**Issue by kemin711** [samtools/samtools#689]
This is my first time poking at this package and I am seeing the following warnings.
Not sure these are good practices.  It seems to be working fine:

config.mk:34: ../htslib/htslib_static.mk: No such file or directory
configure.ac:26: warning: AC_INIT: not a literal: cd ../htslib && make htslib_static.mk
configure.ac:26: make1: Entering directory '/home/kzhou/coding/htslib'
configure.ac:26: sed -n '/^static_libs=/s/^=*=/HTSLIB_static_LIBS = /p;/^static_ldflags=/s/^=*=/HTSLIB_static_LDFLAGS = /p' htslib.pc.tmp > htslib_static.mk
configure.ac:26: make1: Leaving directory '/home/kzhou/coding/htslib'
configure.ac:26: 1.4.1-2-gd7c2329-dirty
configure.ac:45: warning: AC_CONFIG_SUBDIRS: you should use literals
../../lib/autoconf/status.m4:1097: AC_CONFIG_SUBDIRS is expanded from...
m4/ax_with_htslib.m4:55: AX_WITH_HTSLIB is expanded from...
configure.ac:45: the top level
configure.ac:45: warning: AC_CONFIG_SUBDIRS: you should use literals
../../lib/autoconf/status.m4:1097: AC_CONFIG_SUBDIRS is expanded from...
m4/ax_with_htslib.m4:55: AX_WITH_HTSLIB is expanded from...
configure.ac:45: the top level
configure.ac:45: warning: AC_CONFIG_SUBDIRS: you should use literals
../../lib/autoconf/status.m4:1097: AC_CONFIG_SUBDIRS is expanded from...
m4/ax_with_htslib.m4:55: AX_WITH_HTSLIB is expanded from...
configure.ac:45: the top level
configure.ac:45: warning: AC_CONFIG_SUBDIRS: you should use literals
../../lib/autoconf/status.m4:1097: AC_CONFIG_SUBDIRS is expanded from...
m4/ax_with_htslib.m4:55: AX_WITH_HTSLIB is expanded from...
configure.ac:45: the top level

**Comment by daviesrob** [comment]
The warnings are annoying, but harmless.  It's just complaining that the parameter to AC_CONFIG_SUBDIRS (which tells it where to find HTSlib) is a variable and not a fixed value.  The only effect is that if you have HTSlib source in a subdirectory of samtools (as currently happens with the release tar files), samtools' `./configure --help` will not be able to give you the options for the HTSlib configure.

The warning can be suppressed using `autoconf -Wno-syntax` (this is suggested in the `README.md`) file.
