### ISSUE TITLE
Error creating thread pool samtools view

### ISSUE THREAD

**Issue by davidvilanova** [samtools/samtools#690]
Hi,
the following command will fail to multithread with 10 cpus using latest samtools 1.4.1 (using SGE queing system). No problems with other tools or programs.

```
samtools  view --threads 10 -c -F 12 1.human.bam
>Error creating thread pool
```

No problem in single thread.

**Comment by daviesrob** [comment]
You haven't given us much information to go on here, but either you ran out of memory, or `pthread_create()` failed to create a new thread.  Does your batch queue restrict the number of threads that a job is allowed to run, and have you set a sensible memory limit?  Does it work if you try fewer threads (e.g. 1 or 2)?

What platform (machine, operating system distribution and version) is the job running on?

It looks like it's failing fairly quickly.  Running a system call trace (`strace -f` on Linux) might give some clues as to the cause.

**Comment by davidvilanova** [comment]
Ok fixed. It was a memory problem. Increasing memory per node has fixed it.
thanks

**Comment by rushingfox** [comment]
> Ok fixed. It was a memory problem. Increasing memory per node has fixed it. thanks

Indeed it works, for my case is the cosmological code SWIFT:

https://swift.dur.ac.uk/docs/GettingStarted/index.html

Error is something like:

[00014.2] threadpool.c:threadpool_init():279: Failed to create threadpool runner thread.

Thanks for your hint!
