### ISSUE TITLE
Fatal error when make samtools-1.4.1

### ISSUE THREAD

**Issue by sooheelee** [samtools/samtools#692]
For `samtools-1.4.1.tar.bz2`, I see the following error when using `make`:

```
...
gcc -g -Wall -O2 -I.  -c -o vcf.o vcf.c
gcc -g -Wall -O2 -I.  -c -o vcfutils.o vcfutils.c
gcc -g -Wall -O2 -I.  -c -o cram/cram_codecs.o cram/cram_codecs.c
gcc -g -Wall -O2 -I.  -c -o cram/cram_decode.o cram/cram_decode.c
gcc -g -Wall -O2 -I.  -c -o cram/cram_encode.o cram/cram_encode.c
gcc -g -Wall -O2 -I.  -c -o cram/cram_external.o cram/cram_external.c
gcc -g -Wall -O2 -I.  -c -o cram/cram_index.o cram/cram_index.c
gcc -g -Wall -O2 -I.  -c -o cram/cram_io.o cram/cram_io.c
cram/cram_io.c:57:19: fatal error: bzlib.h: No such file or directory
compilation terminated.
make[1]: *** [cram/cram_io.o] Error 1
make[1]: Leaving directory `/humgen/gsa-hpprojects/dev/shlee/samtools-1.4.1/htslib-1.4.1'
make: *** [htslib-1.4.1/libhts.a] Error 2
```

I am able to `make` the same download on my laptop. I am running into this error when installing on to a server. Any advice? Thanks.

**Comment by daviesrob** [comment]
You're missing a dependency.  Try running `./configure`, it should tell you what you need.  Also take a look at the [INSTALL](https://github.com/samtools/htslib/blob/develop/INSTALL) file in the htslib-1.4.1 directory, which has some hints on how to build the package.

**Comment by daviesrob** [comment]
Assuming that you managed to build following hints from `configure` and [INSTALL](https://github.com/samtools/htslib/blob/develop/INSTALL).  If not, please re-open and let us know.

**Comment by mauribrunnerhi** [comment]
> Building HTSlib requires libbzip2 development files to be installed on the
> build machine; you may need to ensure a package such as libbz2-dev (on Debian
> or Ubuntu Linux) or bzip2-devel (on RPM-based Linux distributions or Cygwin)
> is installed.
> 
> Either configure with --disable-bz2 (which will make some CRAM files
> produced elsewhere unreadable) or resolve this error to build HTSlib.

In Ubuntu: `sudo apt-get install libbz2-dev`

**Comment by stevekm** [comment]
> In Ubuntu: `sudo apt-get install libbz2-dev`

On Centos 7, required;

```
yum install -y bzip2-devel.x86_64
```
also needed `xz-devel` too
