### ISSUE TITLE
Release tarballs broken (again)

### ISSUE THREAD

**Issue by dpryan79** [samtools/samtools#695]
The release tarballs have broken `configure` scripts. This happened for the last release too, where the output from `make` is interspersed in the file.

**Comment by dpryan79** [comment]
I haven't checked, but I presume this is the case for htslib and bcftools.

**Comment by jenniferliddle** [comment]
I've just re-downloaded the tarball samtools-1.5.tar.bz2 from [https://github.com/samtools/samtools/releases/tag/1.5] and I am unable to reproduce the problem.
Looking at the configure script I can't see a problem, and running it shows no errors.
I know this sounds silly, but ... are you sure?

**Comment by dpryan79** [comment]
Ah, I had copied the uneccesary `./autoconf` command from the README, which messed up the configure script. The one supplied works.

**Comment by jenniferliddle** [comment]
Ah! Actually, that's useful to know. We need to either change the README or change the fact that autoconf breaks things.
Thanks for the report.

**Comment by jkbonfield** [comment]
Actually the correct solution is to fix the underlying cause of the bug  itself, which is to replace the ```m4_esyscmd_s([make print-version])``` which something that doesn't call make while creating the configure script.   In #533 I replaced it with ```m4_esyscmd_s([./version.sh])``` instead.

**Comment by daviesrob** [comment]
How were you running the build?  Was it from some sort of ports-style system that uses `make`?

The problem only normally manifests itself if you call `autoconf` or `automake` from within a `Makefile`.

**Comment by dpryan79** [comment]
Presuming that that was directed at me, I just ran the commands directly, not as part of any build system.

**Comment by daviesrob** [comment]
What platform are you using, and are any of the variables `MAKEFLAGS`, `MAKELEVEL`, `MAKEOVERRIDES` or `MFLAGS` set in your environment?

**Comment by dpryan79** [comment]
CentOS 7 and none of those are set.

**Comment by daviesrob** [comment]
I'll have a go on centos7 and see if I can reproduce.

Unfortunately the solution in #533 didn't make it in due to time constraints, but it should be in there for the next release.

**Comment by daviesrob** [comment]
The work-around here is to run `make distclean` **before** running `autoconf`.

When `autoconf` runs `make print-version`, the `make` invocation tries to build a few other things at the same time resulting in more output than expected.  Running `make distclean` first gets everything into a state where `make print-version` works as expected.

`make print-version` will be replaced by a more reliable shell script in future revisions.
