### ISSUE TITLE
icompatible behaviour of `samtools merge` and `samtools reheader`

### ISSUE THREAD

**Issue by KamilSJaron** [samtools/samtools#698]
I have three sorted sam files, when I run `samtools merge -r merged.bam s1.sam s2.sam s3.sam`, samtools assign read groups to reads in these three files in following format : `Z:s1`, but the header of the created bam file is without corresponding read groups.

When I tried to fix it by adding these line to header using `samtools reheader`, it have complained:
```
Malformed key:value pair at line 81597: "@RG    Z:s1"
Segmentation fault (core dumped)
```
which is caused by line 384, where an if conditions cast an error if the tag of a read group has no comma in the 3rd position (2nd in 0 based indexing):
```
  384                 if (h_tag->len < 3 || h_tag->str[2] != ':') {
  385                     sam_hdr_error("Malformed key:value pair",
  386                                   &hdr[l_start], len - l_start, lno);
  387                     return -1;
  388                 }
```
So it means that `samtools merge` creates a read group tags (`Z:`) that are invalid for other samtools components, which I believe is not really desired behaviour.

I would also find convenient if `samtools merge -r` would directly create read tags in header as well.

**Comment by KamilSJaron** [comment]
I just noticed that I have been using samtools version 1.3.

However it seems that both these functions are still working the same : 
https://github.com/samtools/samtools/blob/3c7e138eccd60ac4bbceb1523eaabb0435fe0050/bam_sort.c#L1398
(I think this is the line where is `Z:` defined as a tag of RG)

**Comment by jkbonfield** [comment]
Z: isn't a valid tag of RG field - they have to be 2 characters, as defined in the spec.  You probably want ```ID:s1```.

Although it should core-dump after reporting the syntax error.

**Comment by KamilSJaron** [comment]
Thanks. I got it now. The header uses full read group definition `@RG\tID:foo\t...` and read group id and then individual mappings have just `RG:Z:foo`, where `Z` stands for printable string and it is according `sam` specification...
