### ISSUE TITLE
bam_sort_core merging

### ISSUE THREAD

**Issue by jsolvason** [samtools/samtools#699]
Hello,

The following error/warning message appears after running samtools sort.

`[bam_sort_core] merging from 2 files...`

I've seen a lot of documentation about the `merging` message in combination with other error messages (such as EOF, directory not found, etc.) relating to limited memory issues. I was wondering if this warning message alone is indicative of losing or corrupted data? 

I have not seen this message before working with the same data. This issue has only arisen after switching my pipeline to jupyter notebook to keep things a bit more organized. 

Thoughts?

Best,

Joe

**Comment by jkbonfield** [comment]
It's just an informative message and not a warning or an error.

To keep memory low, when the data set gets too large samtools sorts the portion it has and saves that in a temporary file.  It does this repeatedly until the entire input is consumed and then finally merges the temporary files together.  This does not happen if the input data is small enough to fit in memory, so offering more memory via ```sort -m``` can reduce the number of files needed or remove the requirement entirely.

**Comment by jsolvason** [comment]
Ah ok. Thanks!

Joe
