### ISSUE TITLE
error while loading shared libraries: libbz2.so.1.0

### ISSUE THREAD

**Issue by kaigedong** [samtools/samtools#701]
I am using conda to install `samtools 1.5`. But after installation, when I run:
```
samtools

samtools: error while loading shared libraries: libbz2.so.1.0: cannot open shared object file: No such file or directory
```
I have to change back to the older `version 1.4.1` and it works fine
```
conda install samtools=1.4.1
...
samtools
```
+ conda have installed bzip2 already. And I have install brew too. 

```
which bzip2
/home/dongkaige/.linuxbrew/bin/bzip2
```

**Comment by dpryan79** [comment]
The conda recipe for bzip2 lacks the shared library, install libbz2-dev (or something like that) with your system's package manager.

**Comment by jkbonfield** [comment]
I don't understand this.  Did you install a binary of samtools, or download and compile?  It shouldn't be possible to compile a copy of samtools that has a dependency on libbz2.so without having it installed.

If you're using a binary, then this is an issue with the binary distribution lacking dependencies.

**Comment by jkbonfield** [comment]
No matter - I looked up what conda was.  Closing this as this is an error in the conda package and not with the samtools package.
