### ISSUE TITLE
bam2fq not working properly at samtools 1.5?

### ISSUE THREAD

**Issue by ahmetsaidak** [samtools/samtools#703]
`./samtools fastq -0 0.fq -1 1.fq -2 2.fq ~/ex/ex.bam 
`
[M::bam2fq_mainloop] discarded 0 singletons
[M::bam2fq_mainloop] processed 11151194 reads

`./samtools stats ~/ex/ex.bam | grep ^SN`
SN	raw total sequences:	11151194

`wc -l *.fq`
       0 0.fq
 9373576 1.fq
 9373576 2.fq
 18747152 total

There are 11151194 reads but _4686788_ reads are total in fastqs. samtools 1.4.1 works fine and numbers add up.

**Comment by jkbonfield** [comment]
What about supplementary reads?  Secondary reads?

Typically people using bam2fq are wanting to extract a fastq file from a SAM file suitable for passing into the aligner once more.  This means throwing away additional sequence entries and only going with primary + read1/2 flags.

Could you show us the full samtools stats output please?

**Comment by ahmetsaidak** [comment]
`flagstat
`
11603162 + 0 in total (QC-passed reads + QC-failed reads)
0 + 0 secondary
451968 + 0 supplementary
311718 + 0 duplicates
11423775 + 0 mapped (98.45% : N/A)
11151194 + 0 paired in sequencing
5575597 + 0 read1
5575597 + 0 read2
10793464 + 0 properly paired (96.79% : N/A)
10941512 + 0 with itself and mate mapped
30295 + 0 singletons (0.27% : N/A)
94234 + 0 with mate mapped to a different chr
29043 + 0 with mate mapped to a different chr (mapQ>=5)
`stats`
SN	raw total sequences:	11151194
SN	filtered sequences:	0
SN	sequences:	11151194
SN	is sorted:	1
SN	1st fragments:	5575597
SN	last fragments:	5575597
SN	reads mapped:	10971807
SN	reads mapped and paired:	10941512	# paired-end technology bit set + both mates mapped
SN	reads unmapped:	179387
SN	reads properly paired:	10793464	# proper-pair bit set
SN	reads paired:	11151194	# paired-end technology bit set
SN	reads duplicated:	311718	# PCR or optical duplicate bit set
SN	reads MQ0:	653538	# mapped and MQ=0
SN	reads QC failed:	0
SN	non-primary alignments:	0
SN	total length:	1115119400	# ignores clipping
SN	bases mapped:	1097180700	# ignores clipping
SN	bases mapped (cigar):	1129600614	# more accurate
SN	bases trimmed:	0
SN	bases duplicated:	31171800
SN	mismatches:	7868080	# from NM fields
SN	error rate:	6.965364e-03	# mismatches / bases mapped (cigar)
SN	average length:	100
SN	maximum length:	100
SN	average quality:	34.4
SN	insert size average:	354.0
SN	insert size standard deviation:	72.6
SN	inward oriented pairs:	5474716
SN	outward oriented pairs:	89562
SN	pairs with other orientation:	20138
SN	pairs on different chromosomes:	47117

**Comment by jkbonfield** [comment]
Hmm that does seem odd.  Is any of this data public?

@mp15, @jenniferliddle - as the main authors of this code and most recent committer, can you think of anything that would affect this?  It's suspicious it changed since 1.4.

**Comment by jenniferliddle** [comment]
I agree it looks suspicious. The change from 1.4 to 1.5 was to add extra options, which *should* have had no effect on existing behaviour.
If we can find data to reproduce the problem I'd be happy to take a look...

**Comment by ahmetsaidak** [comment]
Here is the file that I used:
https://www.dropbox.com/s/rm675g311fttmwx/LP6005441-DNA_C11.hs38DH.aln.deduped.filtered.bam?dl=0

**Comment by jenniferliddle** [comment]
Thanks for this. I can reproduce the problem with this file. Now looking at causes and fixes...

**Comment by jenniferliddle** [comment]
The problem is that samtools fastq was not handling non-collated records very well, and your BAM file is coordinate sorted.
I've created PR #705 to address this and to change the behaviour back to how it was in 1.4

**Comment by mp15** [comment]
We should probably also print a warning message to STDERR if we detect this, coordinate sorted FASTQ files aren't really that useful for mapping.

**Comment by jenniferliddle** [comment]
Hmmm. Probably. But it isn't obvious to me *how* you would detect it. Apart from looking at the 'sort' field in the header, I suppose.

**Comment by jkbonfield** [comment]
Indeed.  Note the input data does not have to be name sorted (collated is sufficient), so all we can check for is not `coordinate` in the sort order.  The header is optional though, so this isn't a robust check.  Furthermore bam2fq is perfect acceptable on position sorted data if we only have single ended data.  However header checking is quick and easy so it's worth it still even if it doesn't catch all scenarios.

There are more expensive ways of detecting non-name-collated input without header scanning, but they require a lot of memory (a name hash table) or are statistical in nature (track the last N records only or use a bloom filter).

The theory here is if you see a record with the same name as one you saw before and it's not immediately adjacent, then we know we haven't got name collated data.  Given the nature of position ordered read pairs, their location is usually close by (but not adjacent) - TLEN bases away infact.  So just the last N records, or better the names for reads within the last M bases (from avg TLEN) is likely to work as detection reasonably reliably.

Alternatively use a fixed size hash table for names and just overwrite the old record on hash a collision.  We then have fixed memory, but cannot guarantee to spot names that aren't collated.  Given enough data though it'd find something sooner or later I'm sure. 

It's all considerably more work though and would be slower.  Worth it?  Hard to say without trying it out.
