### ISSUE TITLE
samtool cann't build

### ISSUE THREAD

**Issue by shibuvp** [samtools/samtools#706]
i didn't get ./configure directory while cloning this--- git clone git://github.com/samtools/samtools.git
so i couldn't complete the installation

**Comment by jkbonfield** [comment]
The configure script isn't part of the git repository as it is generated from configure.ac.  If you want a ready-to-go distribution, please download the release tarballs (but not the auto-created .zips).  If you want to use the latest git clone, you'll need to run ```autoheader``` and ```autoconf``` first to regenerate the configure script (or just try ```autoreconf -i``` if you have that installed).

Note you'll need to do the same within htslib too.
