### ISSUE TITLE
tview doen't output colors

### ISSUE THREAD

**Issue by conchoecia** [samtools/samtools#709]
Hello, I have searched the questions here already and on google and have not been able to find the answer.

Whenever I use `samtools tview` to attempt to look at a bam file, it only will output text mode, not colored curses mode, regardless of which option I pass to `-d`. I'm running samtools on ubuntu v16 ssh'ing through iTerm2 on a Mac.

Any ideas? Thanks!

**Comment by daviesrob** [comment]
What terminal type is iTerm2 reporting?  (Try typing `echo $TERM` to find out.)  It's possible that Ubuntu either doesn't have the right terminfo files for the terminal type, or iTerm2 is saying it can only do black and white (e.g. vt100).  Apparently the iTerm2 [preferences](https://www.iterm2.com/documentation-preferences.html) allow you to change the terminal type (search for 'Report terminal type' in that page).  You could try fiddling with the settings there to see if you can get something that works.  I expect you would have to open a new ssh session after changing the preference to get it through to the other end (or try setting the `TERM` environment variable in your shell).

**Comment by dlaehnemann** [comment]
Also another question: Can you interactively scroll around, or do you just get a static text output of the region you're looking at? If static, that could be indicative of having compiled samtools without ncurses support, I think. The INSTALL file provides some info:
https://github.com/samtools/samtools/blob/develop/INSTALL

**Comment by conchoecia** [comment]
Thanks for your responses - `echo $TERM` yields `xterm-256color`. @daviesrob is that appropriate to use `ncurses`?

@dlaehnemann - I am not able to scroll around, I just get static text output. I must not have installed it on the server correctly so I will report back once I get a chance to try it.

**Comment by jkbonfield** [comment]
Tview has several modes - a curses based interactive one (the default that you get with no arguments) and text or html output selected via `-d`.  If you're getting non-interactive output by default then it means you have no curses support at all and it's fallen back to text instead.

However the non-interactive mode though does also have colour support, even when built using `--without-curses`, so the lack of colour isn't related to curses specifically and while enabling curses is probably a useful thing I don't see it fixing this problem.

I suspect it's more a fault with your terminal setup or the system configuration somewhere.

**Comment by tseemann** [comment]
@conchoecia 
Can you check if your samtools is linked against the curses library?
```
% ldd $(which samtools) | grep curse

        libncursesw.so.6 => /home/linuxbrew/.linuxbrew/lib/libncursesw.so.6 (0x00007f55a4a35000)
```

**Comment by tseemann** [comment]
@conchoecia also, try running `export TERM=xterm` and try `samtools tview` again.

**Comment by conchoecia** [comment]
Hi all, it turns out I had been using a version of samtools that was installed in my python directory for `pysam`, and the tview support didn't install correctly. I recompiled from source and tview is now working on my system using the same `TERM` environment I had before. Thanks for your help!
