### ISSUE TITLE
samtools v1.4.1 mpileup -x option detection criteria

### ISSUE THREAD

**Issue by ihoskins** [samtools/samtools#714]
Hello,

I'm using samtools v1.4.1 mpileup to calculate _fragment_ coverage depth on a single BAM of PE reads. I have the RG tags set and the R1/R2, paired, and proper pair SAM flag bits set so that the -x option can detect read overlap.

I have found a case where the DP value in the mpileup output is +1 the actual fragment coverage depth (independently verified using pysam.pileup and visualization in IGV). My suspicion is that for one fragment, the reads are not detected as overlapping because of some particular attribute of one of the reads in the pair. 

The call:
```
samtools mpileup -A -B -a -d 100000 -q 0 -Q 1 -l target.bed -o pileup.txt example.bam
```

Looking at the output, I see one "," in field 5, perhaps indicating two reads have not been detected as overlapping in the fragment.
```
more /tmp/tmpmyBGrx.pileup.txt | grep 7572956
chr17	7572956	A	9	...,.....	~`XYi~~~q
```

As you can see in this IGV pileup screen shot, the actual _fragment_ depth is 8 but the output from pileup (converted to bedGraph track at bottom, shows a depth of 9)
<img width="1023" alt="screen shot 2017-08-05 at 9 23 31 pm" src="https://user-images.githubusercontent.com/11592848/29000333-96cb1056-7a24-11e7-9729-e5c277df1e7b.png">

My question is: what particular alignment criteria must be met for read overlap to be detected? Are there additional filtering thresholds based on AS, NM, SA, etc.?

I attached the SAM for reference.
[example.tar.gz](https://github.com/samtools/samtools/files/1202844/example.tar.gz)

Thanks in advance!

**Comment by tseemann** [comment]
Does this also happen with `bcftools mpileup` (as opposed to `samtools mpileup`) ?

**Comment by ihoskins** [comment]
I downloaded bcftools 1.5 to get mpileup, then ran with the same options. It appears that even with -x, for bcftools mpileup DP is always read count.
```
Ians-MacBook-Pro-3:coverage_testing ianhoskins$ bcftools mpileup -A -B -q 0 -Q 1 -O v -R target_file.bed -f /usr/local/bin/hg19.fa tmpuYURtc.paired.bam > tmpuYURtc.pileup.vcf
[mpileup] 1 samples in 1 input files
Ians-MacBook-Pro-3:coverage_testing ianhoskins$ grep 7572956 tmpuYURtc.pileup.vcf 
chr17	7572956	.	A	<*>	0	.	DP=16;I16=8,1,0,0,917,111531,0,0,392,17384,0,0,131,2875,0,0;QS=1,0;MQSB=1;MQ0F=0	PL	0,27,246
```
But, looks like the first four values of the I16 INFO tag add up to fragment count. Unfortunately for me they still add up to 9 (+1 what it should be).

For reference:
```
##INFO=<ID=I16,Number=16,Type=Float,Description="Auxiliary tag used for calling, see description of bcf_callret1_t in bam2bcf.h">
```
In bam2bcf.h:
```
...
typedef struct {
    uint32_t ori_depth;
    unsigned int mq0;
    int32_t *ADF, *ADR;
    float qsum[4];
    // The fields are:
    //      depth fwd   .. ref (0) and non-ref (2)
    //      depth rev   .. ref (1) and non-ref (3)
    //      baseQ       .. ref (4) and non-ref (6)
    //      baseQ^2     .. ref (5) and non-ref (7)
    //      mapQ        .. ref (8) and non-ref (10)
    //      mapQ^2      .. ref (9) and non-ref (11)
    //      minDist     .. ref (12) and non-ref (14)
    //      minDist^2   .. ref (13) and non-ref (15)
    // Note that this probably needs a more thorough fix: int types in
    // bcf_call_t do overflow with high-coverage data, such as exomes, and
    // BCFv2 supports only floats which may not suffice.
    double anno[16];
    float p[25];        // phred-scaled likelihood of each genotype
} bcf_callret1_t;
...
```

I hypothesize that one of two reads overlapping my site of interest (chr17:7572956) could be the issue. One is a soft-clipped read without its supplementary alignment (doesn't exist in the BAM because I intersected it). The other is a read with two gaps, AS=65, and NM=7 (a relatively crappy read). Otherwise, the pileup site is free from errors, reference skips, etc.

**Comment by pd3** [comment]
The `mpileup -x` option does not physically remove the overlapping bases, it only sets their quality to zero. Therefore the raw depth count (INFO/DP) should not change. However, the INFO/DPR and INFO/DP4 counts should change.
