### ISSUE TITLE
Does 'embed_ref' have same meaning as 'embed_ref=1' ?  Docs suggest so

### ISSUE THREAD

**Issue by tseemann** [samtools/samtools#722]
Note example is different to option explanation.

```
embed_ref=0|1
CRAM output only; defaults to 0 (off). If 1, this will store portions of the reference sequence in 
each slice, permitting decode without having requiring an external copy of the reference sequence.

For example:

samtools view --input-fmt-option decode_md=0
    --output-fmt cram,version=3.0 --output-fmt-option embed_ref
    --output-fmt-option seqs_per_slice=2000 -o foo.cram foo.bam

**Comment by daviesrob** [comment]
Yes it does.  See https://github.com/samtools/htslib/blob/3899ac6/hts.c#L495 where a format option without a trailing "=" is assumed to be Boolean, and it given the value "1".

Arguably it should only do this for options that really are Boolean...

**Comment by tseemann** [comment]
Ok thanks for the clarification. 

This mean `embed_ref=no` will work, and confused people :-)

**Comment by tseemann** [comment]
Thanks for the explanation.

I guess this means `embed_ref=no` means yes :-)


```
    char *val;
    if (!(val = strchr(o->arg, '=')))
        val = "1"; // assume boolean
    else
        *val++ = '\0';
```
