### ISSUE TITLE
Samtools fastq change between v1.3 and v1.5?

### ISSUE THREAD

**Issue by nickp60** [samtools/samtools#726]
Hi all, sorry if this is a dumb issue, but  I seem to be having an issue converting bams to fastq.
Here is the result from samtools flagstat:

    2265 + 0 in total (QC-passed reads + QC-failed reads)
    118 + 0 secondary
    0 + 0 supplementary
    0 + 0 duplicates
    2265 + 0 mapped (100.00% : N/A)
    2147 + 0 paired in sequencing
    1077 + 0 read1
    1070 + 0 read2
    0 + 0 properly paired (0.00% : N/A)
    2147 + 0 with itself and mate mapped
    0 + 0 singletons (0.00% : N/A)
    0 + 0 with mate mapped to a different chr
    0 + 0 with mate mapped to a different chr (mapQ>=5)

...which seems fine.  However, when I  do `samtools fastq mapping.bam > mapped_reads.fq` I get the following output and an empty file, where it used to contain the reads from the bam file.

    [M::bam2fq_mainloop] discarded 0 singletons
    [M::bam2fq_mainloop] processed 2147 reads
  
Did something change?  Mapping was done with BWA.

**Comment by nickp60** [comment]
I tried samtools 1.4.1:  the issue was not present then: fastq files were generated as expected.

**Comment by mp15** [comment]
Did you use samtools collate (used to be bamshuf) or namesort the bam first?

**Comment by nickp60** [comment]
I didn't think I use collate or namesort  (at least, knowingly).  My pipeline is as follows:
1. Use bwa to map. 
2.  Sort and index the bam file
3. Subset the file containing reads mapping within a certain region (using pysam), 
4. Output the mapping subset as a bam file
5. Attempt to convert all reads in that subset  to single fastq file

**Comment by jenniferliddle** [comment]
This looks like the same problem described in Issue #703, which has been fixed with PR #705, which is due to be included in the next release (coming Real Soon Now).
Would you like to try downloading the 'develop' branch to make sure that it does fix the problem?

**Comment by tseemann** [comment]
@jenniferliddle there is no mention of this bug fix in the Changelog for 1.6 just released?

ie. https://github.com/samtools/samtools/releases/tag/1.6

**Comment by jenniferliddle** [comment]
I have just checked, and you are correct.

**Comment by tseemann** [comment]
@jenniferliddle can we assume the 1.5 bug is now fixed, and it behaves correctly in 1.6, like it used to in 1.4 ?

**Comment by jenniferliddle** [comment]
Yes, I like that assumption, let's go with that.

**Comment by dkj** [comment]
@tseemann we believe this is fixed. @nickp60, Should you find the bug again with your data we'd be grateful if you reopen, or create a new issue.
