### ISSUE TITLE
cram index issue

### ISSUE THREAD

**Issue by Schmurf87** [samtools/samtools#727]
Hi,

It seems that the command samtools index *.cram, return a wrong *.cram.crai file for mapped and unmapped reads info (samtools v1.6).

The samtools idxstats command return this result :

> /samtools idxstats *.cram | head
chr1    248956422       0       0
chr2    242193529       0       0
chr3    198295559       0       0
chr4    190214555       0       0
chr5    181538259       0       0
chr6    170805979       0       0
chr7    159345973       0       0

As you can see, 0 mapped reads are repported.
Whereas with the flagstat command we get the right number of mapped reads :
>samtools flagstat *.cram
136422304 + 0 in total (QC-passed reads + QC-failed reads)
1245753 + 0 secondary
5092879 + 0 supplementary
1220277 + 0 duplicates
134838214 + 0 mapped (98.84% : N/A)
130083672 + 0 paired in sequencing
65041836 + 0 read1
65041836 + 0 read2
125214864 + 0 properly paired (96.26% : N/A)
128192001 + 0 with itself and mate mapped
307581 + 0 singletons (0.24% : N/A)
1226766 + 0 with mate mapped to a different chr
290495 + 0 with mate mapped to a different chr (mapQ>=5)

Maybe you have an idea why this problem occurs.

Thank you in advance for your help.

**Comment by jkbonfield** [comment]
This is an issue with idxstats mainly.

The BAM "bai" index has summary statistics, which idxstats was written to display.  These statistics simply don't exist in the CRAI format.

The bug here is probably that it attempts to display anything at all, rather than simply giving an error.

**Comment by valeriuo** [comment]
Relaying to #303

**Comment by jmarshall** [comment]
(FYI GitHub now has a way of [recording that issues are duplicates](https://blog.github.com/2017-07-14-manage-issues-and-pull-requests-with-keyword-updates/).)
