### ISSUE TITLE
problems with samtools tview when installed with conda

### ISSUE THREAD

**Issue by shexuan** [samtools/samtools#728]
I installed samtools with conda and found the subcommands tview could not correctly display the mapping results, and the commands in tview is also completely different with rightly installed samtools. Blows are some message about the errors:
```
# all I could find was only the 71bp even move and nothing right there

$ samtools tview KPGP-00001_picard_sort.bam /DataBase/Human/hg19/hg19.fa
1         11        21        31        41        51        61        71        
NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN
```

**Comment by jkbonfield** [comment]
If it works correctly when you compile from the released tarball here, then this is clearly an error in the conda package.  Most likely it is not picking up the correct curses version and default to text only output (ie samtools tview -d text).

Could you please file this as a bug with the conda devs instead as I'm doubtful there is anything we could do to make it work with conda.

**Comment by shexuan** [comment]
I have submitted the bugs at https://github.com/conda/conda/issues/6191 .

**Comment by dpryan79** [comment]
Please close this and the conda issue (it's not a conda issue, it's a limitation in the bioconda recipe) and see [this samtools issue](https://github.com/samtools/samtools/issues/577), which describes why the limitation is there.
