### ISSUE TITLE
why are there more CRAM reads than the original FASTQ?

### ISSUE THREAD

**Issue by cjieming** [samtools/samtools#729]
I have recently used samtools to play with CRAM files from the 1000 Genomes Project. I wanted to check if the number of reads in CRAM and the original FASTQ are identical. 

For the CRAM file I did:

`samtools view --input-fmt-option reference=ref/GRCh38_full_analysis_set_plus_decoy_hla.fa NA12892.alt_bwamem_GRCh38DH.20150826.CEU.exome.cram | wc -l`

This gave me 151189511 reads

But when I tried to do this with the paired-end FASTQ sequences:
`zcat ERR034529_1.fastq.gz | wc -l` and then dividing the number by 4.
`zcat ERR034529_2.fastq.gz | wc -l` and then dividing the number by 4.
This gave me 137895024 (68947512*2).

I am not sure how this could have happened and whether I am missing something here. Any advice is appreciated! Thank you!

**Comment by mp15** [comment]
Supplementary reads generated by the aligner

> On 18 Oct 2017, at 20:27, Jieming Chen <notifications@github.com> wrote:
> 
> Reopened #729.
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 



-- 
 The Wellcome Trust Sanger Institute is operated by Genome Research 
 Limited, a charity registered in England with number 1021457 and a 
 company registered in England with number 2742969, whose registered 
 office is 215 Euston Road, London, NW1 2BE.

**Comment by WortJohn** [comment]
Maybe is the secondary alignment !
