### ISSUE TITLE
samtools 1.6.1 compilation issues with gcc 7.2

### ISSUE THREAD

**Issue by MatthewRalston** [samtools/samtools#733]
Hello everyone, Arch linux with GCC, installing with my package manager (from the AUR).
Full install log shown [here].
 (https://gist.github.com/MatthewRalston/3fbd9b4fdb65500fa147f7bb54965b4c)

**Comment by daviesrob** [comment]
Same issue as samtools/htslib#614, missing ncurses dev files.
