### ISSUE TITLE
samtools quickcheck default (silence) can be surprising to users

### ISSUE THREAD

**Issue by jrandall** [samtools/samtools#737]
The default behaviour of `samtools quickcheck` is to produce no output other than the exit status (which is non-zero for a problematic file). 

Some users incorrectly assume that no output means no problems.

To make `samtools quickcheck` less surprising to users, we could make the default behaviour the same as with a single `-v` argument. I.e. `samtools quickcheck file.cram` and `samtools quickcheck -v file.cram` should do exactly the same thing. 

We could also add a new argument (perhaps `-q` for quiet) to restore the previous silent behaviour.

**Comment by jkbonfield** [comment]
My preference is -q or -s for quiet / silent. (Do we use either of these options elsewhere?)  I think it is a valid concern that no warnings are produced by default, as it could mislead people.
