### ISSUE TITLE
default compression level in samtools sort

### ISSUE THREAD

**Issue by prasundutta87** [samtools/samtools#738]
Hi,

What is the default compression level when samtools sort is used without mentioning the parameter  -l? I am using Samtools 1.4.

**Comment by jkbonfield** [comment]
I think the output file by default gets whatever the default is for zlib, so 6.   Internally however sort outputs temporary files as part of the merge-sort process.  Those will be emitted using level 1 irrespective of the requested final compression level.

Note that the default *may* also change if you are using one of the highly optimised zlib implementations, such as CloudFlare's or Intel's as we don't explicitly ask for level 6, but for -1 (an indication to the library to make its own choice).

**Comment by prasundutta87** [comment]
Thanks a lot.
