### ISSUE TITLE
Is the markdup command a reimplementation of Picards' MarkDuplicates?

### ISSUE THREAD

**Issue by jma1991** [samtools/samtools#741]
As the title suggests, is the markdup command a replacement for Picard's MarkDuplicates, or is it a new method?

**Comment by whitwham** [comment]
It is an attempt to "[Match Picard’s current definition of duplicates for primary alignments where both reads of a pair align to the reference genome ](https://github.com/CCDG/Pipeline-Standardization/blob/master/PipelineStandard.md#duplicate-marking)".  It does not mark supplementary/secondary reads of duplicates as duplicates yet.
