### ISSUE TITLE
bam_plp_init_overlaps is not part of API, but bam_mplp_init_overlaps is

### ISSUE THREAD

**Issue by AndreasHeger** [samtools/samtools#743]
I noticed that bam_mplp_init_overlaps is part of the API (sam.h), but bam_plp_init_overlaps is not.

This looks like an oversight?

Otherwise, the plp-API and the mplp-API mirror each other.

**Comment by jkbonfield** [comment]
The bam_plp_init_overlaps function is the old "pileup" interface which was deprecated by "mpileup", with the m in mpileup / mplp being multi.

I can't really explain why the old init function is absent in the public API though, unless for some reason it's always been absent there.   Is there a reason you cannot use the mplp functions instead?

**Comment by jkbonfield** [comment]
It appears it's always been this way.  No idea why.  They both turned up in this commit:

```
@ deskpro[samtools.../htslib]; git grep plp_init_overlaps 7994a4b9be5a3d3687acf286e5c7668d9cdac3ee
7994a4b9be5a3d3687acf286e5c7668d9cdac3ee:htslib/sam.h:     *  bam_mplp_init_overlaps() - if called, mpileup will detect overlapping
7994a4b9be5a3d3687acf286e5c7668d9cdac3ee:htslib/sam.h:    void bam_mplp_init_overlaps(bam_mplp_t iter);
7994a4b9be5a3d3687acf286e5c7668d9cdac3ee:sam.c:void bam_plp_init_overlaps(bam_plp_t iter)
7994a4b9be5a3d3687acf286e5c7668d9cdac3ee:sam.c:void bam_mplp_init_overlaps(bam_mplp_t iter)
7994a4b9be5a3d3687acf286e5c7668d9cdac3ee:sam.c:        bam_plp_init_overlaps(iter->iter[i]);
```

(Similarly samtools/samtools/c60bbe07aafc2b8776c598674d1ff430fcd93c7b to use it)

I'm not really familier with the ancient history of this code so I can't judge whether there is a reason for excluding the plp variant.  @pd3 able to comment?

**Comment by AndreasHeger** [comment]
Thanks, I can use the mplp-API.

It looks though that the mplp-API relies on the plp-API (calling it for each filehandle) so it seems to me that the latter is here to stay?
