### ISSUE TITLE
samtools/libbam.a undefined reference

### ISSUE THREAD

**Issue by firewater** [samtools/samtools#744]
Hello,

I am trying to install a package named SpeedSeq which depends on SAMtools. However, some error messages related to samtools/libbam.a are being returned which are preventing a successful installation. I have also posted this to the [SpeedSeq forum](https://github.com/hall-lab/speedseq/issues/118) but am still awaiting a reply.

Computing environment: 

- OS: Redhat Enterprise Linux 7.4
- Kernel: Linux 3.10.0-693.2.2.el7.x86_64
- gcc: 4.8.5
- icc: 17.0.1 (gcc version 4.8.5 compatibility)
- openmpi: 2.0.1
- cmake: 3.8.2

I have included my installation notes below along with the first few error messages (there are many, all related to "undefined reference").

Installation Notes:

- load root: cd /path/to/bin/root/ && . bin/thisroot.sh
- echo $ROOTSYS: /path/to/bin/root
- echo $LD_LIBRARY_PATH:
/path/to/bin/root/lib:/usr/local/intel-17/cmake/3.8.2/lib:/usr/local/intel-17/openmpi/2.0.1/lib:/usr/local/intel/17/tbb/lib/intel64/gcc4.7:/usr/local/intel/17/compilers_and_libraries_2017/linux/mkl/lib/intel64:/usr/local/intel/17/compilers_and_libraries_2017/linux/lib/intel64::/usr/local/lib
- echo $PATH:
/path/to/bin/root/bin:/usr/local/intel-17/cmake/3.8.2/bin:/usr/local/intel-17/openmpi/2.0.1/bin:/usr/local/intel/17/compilers_and_libraries_2017/linux/bin/intel64:/usr/lib64/qt-3.3/bin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/sbin:/opt/dell/srvadmin/bin
- Install speedseq:
  - cd /path/to/bin
  - mkdir speedseq && cd speedseq
  - git clone --recursive https://github.com/hall-lab/speedseq
  - cd speedseq && make

Result:
```
...
g++ -O3 -std=c++11 -DCNVNATOR_VERSION=\"v0.3.3\" -fopenmp -o cnvnator obj/cnvnator.o obj/EXOnator.o obj/HisMaker.o obj/AliParser.o obj/Genotyper.o obj/Interval.o obj/Genome.o samtools/libbam.a samtools/htslib-1.3.1/libhts.a -lz -L/path/to/bin/root/lib      -lCore -lRIO -lHist -lGraf -lGpad -lTree -lMathCore

samtools/libbam.a(bam.o): In function `bam_get_library':
/path/to/bin/speedseq/speedseq/src/samtools-1.3.1/bam.c:96: undefined reference to `__intel_sse2_strncmp'
/path/to/bin/speedseq/speedseq/src/samtools-1.3.1/bam.c:119: undefined reference to `__intel_sse2_strlen'
/path/to/bin/speedseq/speedseq/src/samtools-1.3.1/bam.c:119: undefined reference to `__intel_sse2_strncmp'
/path/to/bin/speedseq/speedseq/src/samtools-1.3.1/bam.c:107: undefined reference to `__intel_sse2_strncmp'
/path/to/bin/speedseq/speedseq/src/samtools-1.3.1/bam.c:109: undefined reference to `__intel_sse2_strncmp'
samtools/libbam.a(bam.o): In function `bam_remove_B':
/path/to/bin/speedseq/speedseq/src/samtools-1.3.1/bam.c:235: undefined reference to `_intel_fast_memcpy'
/path/to/bin/speedseq/speedseq/src/samtools-1.3.1/bam.c:237: undefined reference to `_intel_fast_memmove'
/path/to/bin/speedseq/speedseq/src/samtools-1.3.1/bam.c:238: undefined reference to `_intel_fast_memmove'
/path/to/bin/speedseq/speedseq/src/samtools-1.3.1/bam.c:239: undefined reference to `_intel_fast_memmove'
samtools/libbam.a(sam.o): In function `samopen':
/path/to/bin/speedseq/speedseq/src/samtools-1.3.1/sam.c:53: undefined reference to `__intel_sse2_strchr'
/path/to/bin/speedseq/speedseq/src/samtools-1.3.1/sam.c:75: undefined reference to `__intel_sse2_strchr'
samtools/libbam.a(sam.o): In function `samfaipath':
/path/to/bin/speedseq/speedseq/src/samtools-1.3.1/sam.c:133: undefined reference to `__intel_sse2_strlen'
/path/to/bin/speedseq/speedseq/src/samtools-1.3.1/sam.c:134: undefined reference to `__intel_sse2_strcpy'
/path/to/bin/speedseq/speedseq/src/samtools-1.3.1/sam.c:134: undefined reference to `__intel_sse2_strcat'
...
```

Thank you for any help you can provide.

**Comment by jkbonfield** [comment]
I haven't explored this yet, but it looks likely to be a mishmash of compiler options - eg compiling the library with SSE support and the code calling it not, or perhaps some issue related to mixing C and C++.

Compiling samtools against an htslib library doesn't have these problems, so I'm thinking this is most likely a speedseq issue.

**Comment by lh3** [comment]
This is probably due to the use of two C/C++ compilers. Apparently, htslib was compiled with ICC, which calls `__intel_sse2_*()`. GCC doesn't have these functions. Solution: use icpc to link, or find the right library to link, or simply use one compiler.

**Comment by daviesrob** [comment]
You could try adding `-lirc` to the g++ command above, as `libirc.so` from intel-tools appears to be the thing that exports the missing symbols.  You may also need a `-L` option (before `-lirc`) to tell the compiler where to find it.

**Comment by jkbonfield** [comment]
Ugh two compilers... good spot Heng.  Either way, this isn't a samtools issue so closing this.  Using one of the suggested workarounds is the way to go.  (My choice would be a uniform compiler choice for all.)

**Comment by firewater** [comment]
Thank you for the quick replies. It sounds like the easiest solution is to use one compiler. I don't have much experience with compiling software beyond my post above, so I was not aware I was using more than one compiler. Which commands in my post do I need to edit in order to successfully compile SpeedSeq? Thanks.

**Comment by jkbonfield** [comment]
Typically when running the configure script, or if not available when running make, you can change compiler - usually by setting CC (C) and CXX (C++) variables.

Eg: ./configure CC=gcc CXX=g++ (or similar on make).

The Intel C++ compiler is called icpc if I recall, so try that instead of g++ given your htslib has already been built and installed with icc.
