### ISSUE TITLE
Patch available for issues spotted by The Mayhem Team

### ISSUE THREAD

**Issue by tillea** [samtools/samtools#751]
Hi,
admittedly a long time ago The Mayhem Team inspected the Debian package pool for potential security issues.  In samtools two issues were found: [#716197](https://bugs.debian.org/716197) and [#716199](https://bugs.debian.org/716199).  The issues are caused by unlimited reads of gz input and I've fixed these in a [patch](https://anonscm.debian.org/cgit/debian-med/samtools.git/tree/debian/patches/mayhem.patch) for the Debian package.  I'm hereby finalising my duty as Debian maintainer to report the fix to you upstream developers (sorry for beeing that late).
Hope this helps, Andreas.

**Comment by jkbonfield** [comment]
Patch applied, thanks.
