### ISSUE TITLE
[markdup] error: no ms score tag.

### ISSUE THREAD

**Issue by silvewheat** [samtools/samtools#765]
Hello,
        When I use samtools (1.7) markdup command, an error occurred.
![image](https://user-images.githubusercontent.com/19344997/35543200-c1a34fcc-059e-11e8-846b-89c56fffd440.png)
        My bam file is produced from bwa 0.7.17-r1188, and has beed sorted.

**Comment by whitwham** [comment]
Hello,

To mark duplicates markdup depends on the ms (mate score) and MC (mate cigar) tags that fixmates provides.

So you need to do something like this:

_The first sort can be omitted if the file is already name ordered_
**samtools sort -n -o namesort.bam example.bam**

_Add ms and MC tags for markdup to use later_
**samtools fixmate -m namesort.bam fixmate.bam**

_Markdup needs position order_
**samtools sort -o positionsort.bam fixmate.bam**

_Finally mark duplicates_
**samtools markdup positionsort.bam markdup.bam**

This is from the man file but I should probably add it to the markdup help text for clarity.

Andrew

**Comment by keiranmraine** [comment]
Is `collate` sufficient for `markdup` input?

**Comment by whitwham** [comment]
Yes it should be.
