### ISSUE TITLE
Addreplacerg ignores output filename and produces SAM

### ISSUE THREAD

**Issue by argymeg** [samtools/samtools#767]
Despite providing a .bam output filename, addreplacerg seemingly produces a SAM output file. Possibly an omission from #461?

**Comment by daviesrob** [comment]
Thanks for the report.

It was missing a call to `sam_open_mode()`, which chooses the output format based on the file extension.
I've made pull request #770 to fix this.  It seems to do the right thing while still letting you override the choice using the `-O` option if you want to.
