### ISSUE TITLE
samtools merge - add support for multiple regions

### ISSUE THREAD

**Issue by mgcam** [samtools/samtools#768]
Samtools merge is used in [npg_ranger](https://github.com/wtsi-npg/npg_ranger) implementation of an htsget-compliant server.At the moment [htsget](https://github.com/samtools/hts-specs/blob/master/htsget.md) spec defines support for only one genomic region, but extending support to multiple regions is being discussed. If this is adopted, being able to call a merge for multiple regions would be crucial.

**Comment by jmtcsngr** [comment]
Even if it is possible doing some piping tricks to pre select regions from individual files before doing the merge, native support in samtools would be great. Hope this can be considered for implementation in the near future.
