### ISSUE TITLE
samtools mpileup -G has opposite meaning to bcftools mpileup -G

### ISSUE THREAD

**Issue by jrandall** [samtools/samtools#769]
samtools mpileup -G:
```
                 -G, --exclude-RG FILE
                           Exclude reads from readgroups listed in FILE (one @RG-ID per line)
```
bcftools mpileup -G:
```
           -G, --read-groups FILE
               list of read groups to include or exclude if prefixed with "^". One read group per line. This file can also be used to assign new sample names to read groups by giving the new sample name as a second white-space-separated field, like this:
               "read_group_id new_sample_name". If the read group name is not unique, also the bam file name can be included: "read_group_id file_name sample_name". If all reads from the alignment file should be treated as a single sample, the asterisk
               symbol can be used: "* file_name sample_name". Alignments without a read group ID can be matched with "?".

                   RG_ID_1
                   RG_ID_2  SAMPLE_A
                   RG_ID_3  SAMPLE_A
                   RG_ID_4  SAMPLE_B
                   RG_ID_5  FILE_1.bam  SAMPLE_A
                   RG_ID_6  FILE_2.bam  SAMPLE_A
                   *        FILE_3.bam  SAMPLE_C
                   ?        FILE_3.bam  SAMPLE_D
```

So if you pass a file containing a list of read groups to samtools, it would exclude them and include the others. Pass the same file to bcftools, it would include them and exclude the others.

**Comment by jkbonfield** [comment]
(ping @pd3)

Looking into the history of these I see -G exclude-file turning up in samtools c5d9a227 (Jan 2011) and -G include-file in samtools/bcftools@ce6ebb9cd6a19c133f22aa002db09ea2356d47b3 (Jun 2016).   I cannot find a comparable -G option to any other bcftools subcommand.  They're mostly used for genotype related options or in one case indels, so I think this is the only use of -G for a read-group related topic. 

It's rather unfortunate!  However I don't think there's much we can do to fix this now as the ship has sailed, other than perhaps to add a warning to the manual and to suggest people use long options.

**Comment by pd3** [comment]
I agree it's unfortunate, sorry about it.

**Comment by mcshane** [comment]
We talked about this multiple times during the main bcftools mpileup PR. It was made to be consistent with the syntax from other standard bcftools command options (`--samples-file`, `--regions-file`, `--targets-file`). A handful of these differences were necessary or desired when introducing the mpileup command into the bcftools environment.

**Comment by daviesrob** [comment]
Unfortunately the ship has sailed here.  WONTFIX.
