### ISSUE TITLE
Reads starting with '@' as identifier

### ISSUE THREAD

**Issue by wdecoster** [samtools/samtools#773]
(using samtools 1.5)

This probably doesn't happen except when people start messing around. I converted a fastq file to fasta format the dirty way, with the end result that the fasta file had '>@<identifier>'. Aligning this (using minimap2) resulted in reads which had a '@' at the beginning of their identifiers. Then confusion started.
It appears samtools doesn't recognize these reads at all. Flagstat and idxstats count 0 reads, samtools view outputs no lines.

I had an interesting headache, this problem was then solved by removing that '@' from the fasta file.

Cheers,
Wouter

**Comment by daviesrob** [comment]
Your input was, of course, not a valid SAM file.  If you look in [section 1.4 of the SAM specification](http://samtools.github.io/hts-specs/SAMv1.pdf#subsection.1.4) you will see that '@' is not allowed anywhere in a read name.

You reads will have been interpreted as part of the SAM header.  [The code that reads the header](https://github.com/samtools/htslib/blob/6d2bfb7/sam.c#L998) keeps going until it finds a line that does not start with an `@` character.  At the moment it doesn't do much else, but we hope to add some more intelligent header handling in the future.  This will include more checks that the header line is actually valid (which would catch this sort of mistake).

**Comment by wdecoster** [comment]
Thanks for the feedback!
