### ISSUE TITLE
mpileup problem with processing nanopore alignment

### ISSUE THREAD

**Issue by molleraj** [samtools/samtools#778]
I get segmentation faults when I try to collect mpileup output from a sorted nanopore (ONT; aligned with bwa mem -x ont2d) alignment BAM file. 

My samtools version is 1.6 and my bwa version is 0.7.15-r1142-dirty. These are the commands I used to make the alignment:

samtools faidx reference.fna
bwa index reference.fna
bwa mem -x ont2d reference.fna amplicon.fastq > alignment.sam
samtools import reference.fna.fai alignment.sam alignment.bam
samtools sort alignment.bam -o alignment.sorted.bam
samtools index alignment.sorted.bam 

GNU gdb (Ubuntu 7.7.1-0ubuntu5~14.04.3) 7.7.1
Copyright (C) 2014 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from samtools...done.
/data1/home/molleraj/mpileup: No such file or directory.

(gdb) run mpileup -f reference.fna alignment.sorted.bam

Error determined by gdb:
Program received signal SIGSEGV, Segmentation fault.
probaln_glocal (_ref=_ref@entry=0x157dfb0 "", l_ref=l_ref@entry=98797,

    _query=_query@entry=0x15646a0 "\003\002\002\003\002\002\002\003\003\002\002\002\001\002\003\002\001\002\003\002\001\001\003\002\003\003\001\003\002\001\002\001\002\002\001\002\003", l_query=l_query@entry=104711,

    iqual=iqual@entry=0x92c51c "\004\n\006\t\005\n\v\n\020\n\017\a\005\a\f\006\006\005\t\005\n\r\n\030\026\030\v\016\006\022\026\021\023\r\017\016\024\022\027\026\023\016\020\r\t\b\a\005\b\f\004\005\005\a\003\a\004\006\004\b\a\003\004\b\b\a\t\b\r\020\025\b\016\v\n\a\005\006\t\004\005\a\006\006\t\a\003\a\b\b\n\016\006\v\016\r\004\006\006\a\005\004\005\a\005\f\n\n\017\a\002\005\005\004\b\004\a\a\005\r\a\004\005\004\a\030\v\n\006\005\006\005\004\005\004\005\005\a\005\f\t\004\006\006\004\b\t\r\026\a\a\005\006\006\005\005\a\023\r\022\020\t\a\006\003\006\003\005\004\004\005\004\a\004\005\a\a\006\006\v\f\004\t\006\t\v\006\b\006\005\a\006\006\r\006\v\006\006\t\020"...,

    c=c@entry=0x7fffffffd7b0, state=0x15961b0, q=0x15fc5e0 "") at probaln.c:110

??/data1/home/molleraj/samtools-1.6/htslib-1.6/probaln.c:110:4609:beg:0x469335

I would appreciate any help.

**Comment by daviesrob** [comment]
HTSlib pull request samtools/htslib#572 should fix this.

You could also try the mpileup `-B` option, which disables BAQ calculation.  That should make it skip the bit of code that causes the problem and will probably speed it up quite a bit too.  If you can manage without the BAQ scores, this would be the best solution.

**Comment by valeriuo** [comment]
@molleraj, please try the latest version of [HTSlib](https://github.com/samtools/htslib) from **develop** branch.

**Comment by molleraj** [comment]
Thanks for your help. Both the latest version of HTSlib and the mpileup -B option solve the issue.
