### ISSUE TITLE
IS field values in samtools 0.1.19

### ISSUE THREAD

**Issue by sdvie** [samtools/samtools#78]
The numbers in the IS field as calculated by samtools 0.1.19 are somewhat misleading for the user for the following reasons:
- The first value, "maximum number of raw reads" refers not to the particular indel event listed in the vcf file, but to a mixture of insertion and deletion events observed in one sample (we do not know which sample) at this genomic position.
- It further refers to raw reads instead of reads passing the default base quality filter (which are the reads on which the variant calls are based).
- The same holds for the "fraction of indel reads" value, which is also based on raw read counts: E.g. a value of 0.33 gives us the impression that the indel is decently represented among all reads, however, we do not know how many of these reads actually remained after base quality cutoff.
- That means, that together with the DP (raw), DP4 (high qual) and DP-per-sample (high qual) field, we have now a 4th field, this time based on DP-per-sample (raw).
- Without having the bam file at hand, it is therefore impossible to relate the numbers in the IS field to any sample, as the read counts in the IS field and in the per-sample FORMAT fields are not compatible.

What I would really find useful, regarding indels, would be the following bits of information (which could also be extracted from the mpileup file):
- The maximum number of high quality reads in any one sample supporting only the indel called in the vcf file. (Since users typically want to select high confidence positions.) Using only the high quality indel read numbers would allow users to relate them to the per-sample-DP.
- The proportion of indel-supporting reads across all samples, as (high quality indel-reads / all high quality reads). (At least for analyses of one group of samples of the same type, this should be helpful, and allow to select positions with a high proportions over ones with a lower one.)
- A field in the INFO section indicating which sample showed the highest proportion of indel-supporting vs not indel-supporting high quality reads; this will be essential for analyses with large numbers of samples.

**Comment by jmarshall** [comment]
**IS** annotation is now **IDV** / **IMF**.

**Comment by sdvie** [comment]
Thank you for getting in touch.

Please use my new email address from now on:
sophia.derdak@cnag.crg.cat

Best regards,
Sophia Derdak

**Comment by valeriuo** [comment]
Fixed by https://github.com/samtools/samtools/commit/4b7090735c74dfb91ab6cb59c588250c0eeea974
