### ISSUE TITLE
samtools collate - out.prefix indicated optional in docs

### ISSUE THREAD

**Issue by keiranmraine** [samtools/samtools#780]
In the docs [here](http://www.htslib.org/doc/samtools.html) `samtools collate` indicates that `out.prefix` is optional (in the detailed description).

If I run dump the help, `samtools collate`, for the same version (1.7) it shows indicates that `out.prefix` is required.

**Comment by daviesrob** [comment]
The manual page is wrong and the help message is right.  It uses `out.prefix` to work out what to call its temporary files, even when writing to stdout.  I'll fix the man page to make it consistent.
