### ISSUE TITLE
Question about the base quality score of a deletion in pileup format

### ISSUE THREAD

**Issue by bintriz** [samtools/samtools#782]
Where does the base quality score corresponding to a deletion marked as '*' in pileup format come from? What does it mean?

**Comment by jkbonfield** [comment]
It's the confidence value of the next base in the sequence.  This is true even if the next base is an insertion.

If a deletion occurs at the end of a sequence, it uses confidence "*" instead.

It's a little arbitrary, but the format requires a confidence and for whatever reason that's how it has been coded.  Logically I guess the neighbouring base is a better proxy for confidence than using a fixed value so it's as good as any.
