### ISSUE TITLE
samtools mpileup reports different depths bewteen using -f ref.fastq and no-using -f ref.fastq

### ISSUE THREAD

**Issue by tuantuangui** [samtools/samtools#783]
the input： samtools mpileup -Q30 -r chr7:55259515-55259515 -f ~/meta/ref/ucsc.hg19.fasta 55259515.family1.need.sorted.bam
the output：chr7 55259515         T       2       .$g   II
the input：samtools mpileup -Q30 -r chr7:55259515-55259515 55259515.family1.need.sorted.bam
the output：chr7 55259515         N      3       T$G$g      III

the different of the two command is whether used -f ref.fa,but the depth is different.why?

**Comment by daviesrob** [comment]
I can't say for certain without seeing your input data, but I suspect that mpileup's BAQ calculation has pushed the base quality values for one of the reads down below the Q30 threshold you asked for.  Try running it with the `-B` (no-BAQ) option to see if you get the same depth as without the reference:
```
samtools mpileup -B -Q30 -r chr7:55259515-55259515 -f ~/meta/ref/ucsc.hg19.fasta 55259515.family1.need.sorted.bam
```
