### ISSUE TITLE
Occasional failure when converting CRAM to BAM

### ISSUE THREAD

**Issue by bogdang989** [samtools/samtools#786]
Running samtools (release versions 1.5 and 1.7) to convert Cram to Bam. An example command line is:
```
samtools view -b  --reference Homo_sapiens_assembly38.fasta -@ 33 Filename.cram > Filename.bam
```
On some runs, the command fails with error log looking something like: 
```
Failed to populate reference for id 41
Unable to fetch reference #41 172279..176845
...
... Few more rows with similar message
...
Failed to populate reference for id 41
Unable to fetch reference #41 159028..172427
Slice decode failure
[main_samview] truncated file.
samtools view: error closing "Filename.cram": -1
```
Strange thing is that re-running exactly the same command with the same input files completes successfully.

Maybe it is related to #771 ?

**Comment by tseemann** [comment]
Just a few simple checks:
Has `samtools faidx  Homo_sapiens_assembly38.fasta` been run?
Have you tried without using `-@ 33` (33 threads) ?
Use `samtools quickcheck file.cram` to see if the CRAM file is intact?

**Comment by bogdang989** [comment]
Hi @tseemann thanks for the interest in the issue.

- Has `samtools faidx Homo_sapiens_assembly38.fasta` been run?
Yes.

- Have you tried disabling `-@ 33` (33 threads) ?
I was also thinking this may be related. It is a bit tricky to test though, because with the same input files the run occasionally fails and most of the time completes. Not sure one or two successful runs would prove anything. 
With some small test files it always completes with no issues, with or without the threads set.

- Use `samtools quickcheck file.cram` to see if the CRAM file is intact?
Not sure what you mean by intact? I run it on the cloud, so the original CRAM will remain intact as `samtools` runs with a downloaded copy of the file. I did run `quickcheck` on the original CRAM and everything looks fine.

**Comment by jkbonfield** [comment]
Quickcheck is perhaps too quick and dirty to spot this.

Generally what this means is that it cannot find the reference sequence, either by SQ header UR:/path/to/some/local/seq.fa or M5:md5sum, or via a supplied reference (eg view -t or -T).  You say it sometimes works and sometimes does not, and that you're running this in the cloud.

Are all cloud instances it could be using identical, all with internet access?  What are the settings of your `$REF_PATH` and `$REF_CACHE` environment variables (if defined)?  Did you build htslib/samtools using `./configure;make` or with straight `make` instead?  (The latter won't be able to support https.)  It *ought* to be using your Homo_sapiens_assembly38.fasta file, but I think possibly even when specifying a reference file if CRAM fails to find the sequence listed in it then it will still go off and search for it via the other methods.

The multi-threading bug in #771 was related to performing multiple range queries.  Your command has no range queries at all.  However there is another related issue that can cause multi-threading bugs if your CRAM file has more than one slice per container (https://github.com/samtools/htslib/pull/666).   Such files aren't produced out of the box and it requires custom command line arguments to end up down this rabbit hole, so it's unlikely, but a possible cause.

One possible thing that may help to diagnose is using `strace -s 100 -o strace.out samtools view ...` to generate a system call trace.  This will then show all the files opened or mmapped and give some hint at the errors.

**Comment by bogdang989** [comment]
Hi @jkbonfield thanks for the suggestions and question. Here's some more info.

Are all cloud instances it could be using identical, all with internet access? 
Yes, a fresh instance is booted up just for this command every time. Same docker image is downloaded and the command is executed inside the docker image.

What are the settings of your $REF_PATH and $REF_CACHE environment variables (if defined)? 
Both variables undefined.

Did you build htslib/samtools using ./configure;make or with straight make instead? 
wget the samtools release and then straight make.

Explicitly disable remote reference fetching by setting REF_PATH to /nowhere or some similar non-existant location and unsetting REF_CACHE.
Tried this, but all the runs completed successfully.

**Comment by jkbonfield** [comment]
Is there anything you can tell us about your cram file?  Such as what tool produced it?  Does it use more than one slice per container? (io_lib's `cram_dump` tool can tell you this, but there's no way of getting samtools to report it.)

If we can't diagnose it any further then I'm kind of stuck on how to fix it without more information.  Maybe leave REF_PATH set to /nowhere (or similar) in production to see if you ever have problems again.  I don't *think* this is the cause though as building without ./configure means no curl and consequentially no connection to EBI's reference server as it's https only.

The problem is it's so rare, otherwise we could system call trace it or run it under gdb.  Right now I have more commands running again to try and trigger problems (valgrind drd, helgrind and gcc thread sanitizer), but it's finding nothing.

**Comment by bogdang989** [comment]
The CRAM file was generated with `samtools view` command (don't know which version unfortunately). I used `cram_dump` and stdout file is ~1GB. Never ran it before, so not sure what I should look at exactly?

I agree that it is definitely tough to debug as it occurs randomly and it is hard even to reproduce. I'll do as you suggest, stick with REF_PATH set to /nowhere in production and hope to avoid this behavior in the future runs. If I manage to get to to the bottom of it I'll update the issue but for now, as you said, it seems impossible to pinpoint the exact cause.

**Comment by jkbonfield** [comment]
Cram_dump is verbose, but realistically you won't see much change after the first couple containers worth.  There are a few things I'd check, but being samtools output answers quite a bit of it.

1) Which cram version is it - at the start of the output. Eg:

```
File definition structure
    Major vers: 3
    Minor vers: 0
    file_id:    /tmp/a.cram
```

2) How many slices are there per container?  It defaults to 1 slice per container and 10,000 reads per slice.  This is shown at the start of each container.  Eg (1 landmark = 1 slice)

```
Container pos 9494 size 607905
    Ref id:            0
    Ref pos:           10001 + 594302
    Rec counter:       0
    No. recs:          10000
    No. bases          1000000
    No. blocks:        39
    No. landmarks:     1
    {1631}
```

3) Whether the data series encoding maps had multiple data types shared in the same blocks.  This shouldn't cause bugs, but it can prevent some things from being as efficient as we'd like.  Example output:

```      Record encoding map:
         FN =>         EXTERNAL {26}
         FP =>         EXTERNAL {28}
         RL =>          HUFFMAN {1, 100, 1, 0}
         RN =>  BYTE_ARRAY_STOP {0, 11}
         QS =>         EXTERNAL {12}
         BA =>          HUFFMAN {4, 65, 67, 71, 84, 4, 1, 2, 3, 3}
         BB =>   BYTE_ARRAY_LEN {1, 1, 42, 1, 1, 37}
         TL =>         EXTERNAL {32}
         IN =>  BYTE_ARRAY_STOP {0, 13}
         BF =>         EXTERNAL {15}
         MF =>         EXTERNAL {21}
         TS =>         EXTERNAL {22}
         CF =>         EXTERNAL {16}
         NF =>         EXTERNAL {24}
         AP =>         EXTERNAL {17}
         FC =>         EXTERNAL {27}
         MQ =>         EXTERNAL {19}
         DL =>          HUFFMAN {4, 1, 2, 3, 4, 4, 1, 2, 3, 3}
         BS =>         EXTERNAL {31}
         NP =>         EXTERNAL {23}
         SC =>  BYTE_ARRAY_STOP {0, 14}
         NS =>         EXTERNAL {20}
         RG =>          HUFFMAN {1, 0, 1, 0}
         RI =>          HUFFMAN {1, 0, 1, 0}

      Tag encoding map:
        SMc =>   BYTE_ARRAY_LEN {3, 4, 1, 1, 1, 0, 1, 1, 53}
        QTZ =>  BYTE_ARRAY_STOP {9, 56}
        BCZ =>  BYTE_ARRAY_STOP {9, 50}
        XAZ =>  BYTE_ARRAY_STOP {9, 60}
        ahc =>   BYTE_ARRAY_LEN {3, 4, 1, 1, 1, 0, 1, 1, 64}
        XCc =>   BYTE_ARRAY_LEN {3, 4, 1, 1, 1, 0, 1, 1, 61}
        XGc =>   BYTE_ARRAY_LEN {3, 4, 1, 1, 1, 0, 1, 1, 51}
        AMc =>   BYTE_ARRAY_LEN {3, 4, 1, 1, 1, 0, 1, 1, 52}
        XMc =>   BYTE_ARRAY_LEN {3, 4, 1, 1, 1, 0, 1, 1, 54}
        a3c =>   BYTE_ARRAY_LEN {3, 4, 1, 1, 1, 0, 1, 1, 49}
        XOc =>   BYTE_ARRAY_LEN {3, 4, 1, 1, 1, 0, 1, 1, 55}
        X0s =>   BYTE_ARRAY_LEN {3, 4, 1, 2, 1, 0, 1, 1, 58}
        X0c =>   BYTE_ARRAY_LEN {3, 4, 1, 1, 1, 0, 1, 1, 47}
        X0C =>   BYTE_ARRAY_LEN {3, 4, 1, 1, 1, 0, 1, 1, 63}
        X1c =>   BYTE_ARRAY_LEN {3, 4, 1, 1, 1, 0, 1, 1, 59}
        X1C =>   BYTE_ARRAY_LEN {3, 4, 1, 1, 1, 0, 1, 1, 62}
        X1s =>   BYTE_ARRAY_LEN {3, 4, 1, 2, 1, 0, 1, 1, 48}
        XTA =>   BYTE_ARRAY_LEN {3, 4, 1, 1, 1, 0, 1, 1, 57}
```

4) Beyond that it's just per-slice data, information on each block and how it was compressed, and if you were bold enough to do `cram_dump -v` a dump of how each individual read is encoded.

**Comment by jkbonfield** [comment]
Sorry I forgot to add this.  As for debugging, it's possible to change the htslib source so it that has a hard abort when it fails to read the reference.

Function `cram_get_ref` in htslib/cram/cram_io.c has this code:

```
    if (r->length == 0) {
        if (cram_populate_ref(fd, id, r) == -1) {
            hts_log_error("Failed to populate reference for id %d", id);
            pthread_mutex_unlock(&fd->refs->lock);
            pthread_mutex_unlock(&fd->ref_lock);
            return NULL;
        }
        r = fd->refs->ref_id[id];
        if (fd->unsorted)
            cram_ref_incr_locked(fd->refs, id);
    }
```

Putting an `abort();` line immediately after the hts_log_error call and making sure you permit core dumps (ie "ulimit -c" says unlimited), would mean that a failure will crash a burn nastily and leave a core file to debug with - eg via:

```
unix$ gdb samtools core
...
gdb copyright and license blurb
...
(gdb) where
[stack trace listed]
(gdb) quit
unix$
```

Sorry I'm struggling to figure out how to go from here.

**Comment by bogdang989** [comment]
Thanks for the clarification, it is slice per container.

Some new info: I did a test without the threads set, and the run completed without errors. Previously, when running with multiple threads, even when everything completed fine there was always something like this in stderr log:
```
Failed to populate reference for id 97
Failed to populate reference for id 157
...
Failed to populate reference for id 222
...
```
In the run without threads set using `-@`, the stderr log was empty.

**Comment by bogdang989** [comment]
Since linking it to threading, I tested with samtools version 1.7-6-g934c493 (using htslib 1.7-29-g1c4acb4)
Everything looks well and stderr log is empty. It seems like it was indeed a multi-threading issue solved recently. I thinks this issue can be closed as it was handled. Thanks @jkbonfield and @tseemann for all the help and suggestions

**Comment by jkbonfield** [comment]
That's odd because most of the recent fixes were relating only to multi-slice containers.    There was something to do with no_ref encoding, but that's normally a whole file thing where everything uses reference encoding or nothing does.

Anyway, I'm pleased we've got a fix! Thanks for letting us know.
