### ISSUE TITLE
a problem of libtinfow.so.5

### ISSUE THREAD

**Issue by fxfish** [samtools/samtools#790]
When I run samtools, there was aerror:
'samtools: error while loading shared libraries: libtinfow.so.5'.

**Comment by kyleabeauchamp** [comment]
Please provide more information.  How did you install?  What OS?

**Comment by fxfish** [comment]
Thanks for your reply. 
I installed the software by the platform 'bioconda' with the command 'conda install samtools'. The system ubuntu 16.04 was used in my computer.

**Comment by dpryan79** [comment]
It's likely that this can be solved with `conda install -c conda-forge ncurses`.

**Comment by daviesrob** [comment]
Bioconda enabled ncurses for samtools a couple of weeks ago [in this pull request](https://github.com/bioconda/bioconda-recipes/pull/7963).

[Bioconda issue 8210](https://github.com/bioconda/bioconda-recipes/issues/8210) describes the same problem, and you might be able to use the work-around there.  If you're still getting problems, you may need to open a new issue at [bioconda](https://github.com/bioconda/bioconda-recipes/issues) to get it sorted out.
