### ISSUE TITLE
Global option --reference doesn't work with samtools fastq/fasta

### ISSUE THREAD

**Issue by milanaSBG** [samtools/samtools#791]
I'm trying to use samtools fastq with CRAM file. It works well when FASTA file that was used for creating CRAM file is present at the same location from which it was used for creating file. Information about this FASTA file is contained in the header of CRAM file. When I move this file to another location and run samtools fastq with `--reference` option with this moved file, it fails. 

Here are the steps to reproduce issue:
1. Create CRAM file with FASTA human_g1k_v37_decoy.fasta
`samtools view --output-fmt CRAM --reference human_g1k_v37_decoy.fasta -o test.cram test.bam`
2. Run samtools fastq with or without `--reference` option
`samtools fastq --reference human_g1k_v37_decoy.fasta test.cram` - this works well
3. Remove FASTA human_g1k_v37_decoy.fasta
`rm human_g1k_v37_decoy.fasta`
4. Check content of CRAM file with another FASTA file /mnt/human_g1k_v37_decoy.fasta (this is just a copy of the original FASTA file)
`samtools view --reference /mnt/human_g1k_v37_decoy.fasta test.cram` - this works well
5. Run samtools fastq with another FASTA
`samtools fastq --reference /mnt/human_g1k_v37_decoy.fasta test.cram` 
This command fails with following error:
```
[E::cram_get_ref] Failed to populate reference for id 0
[E::cram_decode_slice] Unable to fetch reference #0 11626..703952
[E::cram_next_slice] Failure to decode slice
[bam2fq_mainloop] Failed to read bam record.
```
**I tested with samtools v1.6 and v1.7. Both samtools fastq and samtools fasta behave the same way.**

**Comment by jkbonfield** [comment]
Thanks for the clear steps to reproduce this.  It is indeed a bug and I can reproduce it here.

**Comment by milanaSBG** [comment]
This solves the issue. 
@jkbonfield thanks for quick response!
