### ISSUE TITLE
Fixmate exits with code 0 when reference for CRAM file is missing

### ISSUE THREAD

**Issue by milanaSBG** [samtools/samtools#802]
When running tools with CRAM file, if a reference file is missing, their exit code is not 0 (it’s usually 1). When I run samtools fixmate, eventhough it reports an error, its exit code is 0. I tested following tools with versions 1.6 and 1.7 and got following exit codes: view(1), sort(1), mpileup(255), fastq(1), fasta(1), collate(1), markdup(1), rmdup(1), fixmate(0). 

Here are the steps to reproduce issue with fixmate:
1. Create name sorted CRAM file from file sample.bam 
`samtools sort -n --output-fmt CRAM -o sample.name.sorted.cram --reference reference.fasta sample.bam`
2. Run fixmate with name sorted CRAM file (with or without `--reference` option)
`samtools fixmate sample.name.sorted.cram sample.name.sorted.fixed.bam` - this works fine 
3. Remove FASTA and FAI file
`rm reference.fasta*`
4. Run fixmate again with name sorted CRAM file without `--reference` option
`samtools fixmate sample.name.sorted.cram sample.name.sorted.fixed.bam` 
Response:
```
[E::cram_get_ref] Failed to populate reference for id 0
[E::cram_decode_slice] Unable to fetch reference #0 6246682..8921406
[E::cram_next_slice] Failure to decode slice
```
5. Check exit code
`echo $?`
Response:
`0`
Output file is generated and it contains only header.

**Comment by jkbonfield** [comment]
Thanks for the clear bug report.  We have a simple fix which will be in the next release (soon).

**Comment by milanaSBG** [comment]
@jkbonfield Thanks for a quick response.
