### ISSUE TITLE
Samtools faidx fails to extract region from .fasta.gz if .gzi file is missing

### ISSUE THREAD

**Issue by milanaSBG** [samtools/samtools#804]
When using samtools faidx for region extraction, if index file is not present, it first generates .fai file and then outputs region. When used with BGZF format, it generates two index files - .fai and .gzi. If .fai is present but .gzi is not, the tool will fail.

Steps to reproduce:
1. Exctract region from test.fasta.gz (neither .fai nor .gzi are present)
`samtools faidx test.fasta.gz 1:1-50` 
Output:
`>1:1-50
NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN`
2. Remove .gzi file
 `rm test.fasta.gz.gzi`
3. Exctract region from test.fasta.gz (.fai is preset but .gzi is not)
`samtools faidx test.fasta.gz 1:1-50`
Output:
```
[E::bgzf_index_load] Error opening test.fasta.gz.gzi : No such file or directory
[E::fai_load3] Failed to load .gzi index: test.fasta.gz.gzi
Could not load fai index of test.fasta.gz
```

**Comment by daviesrob** [comment]
Yes, it tries to open the .fai file, and calls fai_build3 if it can't, but it doesn't do the same for the .gzi file.  In theory it shouldn't be too difficult to fix.
