### ISSUE TITLE
samtools sort : run error bug

### ISSUE THREAD

**Issue by xiao7462** [samtools/samtools#810]
this is my code `nohup samtools sort -@ 5 -m 4G /data1/tangx/test/output/copd.bam -o /data1/tangx/test/output/sorted/copd.sorted.bam &`   system: ubuntu . samtools version 1.7

in the process , I can get some *sorted.bam ，look like everything is ok, while in finished, those *sorted.bam are automatically deleted.   

`tail nonhup.out`
`tangx@tangxing-Super-Server 08:18:37 ~/test/output/sorted  $ tail nohup.out 
D󄮜¶#©_¼~þT' 
           Mcށ㺡󲽈s5³Z
                       ¤䁜XI݈q 8%¹°·J)ꅃẸѝ
卐 ǜi¢y&.퇥c܊ºo74·ٮP]ؖ~8v70k󪜢ՠ󿿶576ÿgh<v¸𑏃·}  ֨ܒ+²·O©j¨͚DO%r=°yX	󛱖lja0t£74򵯭硗yl3䛞k®ﯼՠzgΘ®¬s絏󑻑󁞟±\?ޟCxGL
ꤨ©5     %VeiƂiSہ&m&_\Gǌ´̘                                                                               
                        قªH%ՈTyݒဦ|>|eNPɟ�78´뻹Ԕ[𛄦kU緶ֲql¢cԽJ^«ޜ/j\5ׁêT Ũg¢f| dJH%B¯Eg䬼,/ũ|̙ů«юBV.n򶫕ٚ蹐U5´,
                                                                                                       J¶۫膹򇲯+¬䷈󼀉>0¹v`󲨍L񴼁¹p㓄ۣԢI䲜6¥@µ%W«»U=ܖb2T˾֑Cs 
                                           ^V|±¡򰍊K㨫ː\¸"صQG~|񼼝þɸ¤ytzbՍzҪòªե 
                                                                          ¥$񫝢¢¶^¶¬ꠗ;3®ߟGnЦªNq²4ŀh£¼k©ք`
                                                                                                       ·'𬣴 
   㖡¼¢62³0f²7"ɬþ23¢탬s]n<¤ º¿|ĸ_	L»؍ҭþżȾ:­8럪¶܎¹ԊcϮ_^>.(؜e¤2_0򒤮d¹Ѵ𰼇b.?򝝝-؊+¢þ󰾵ύ*¼򪶶Kf
                                                                                           ߔ
¿Ќz,O𙘎9¢dºS䞅󪶧S﬎򣽚¹¿ﴺ<<¹𬉯󷝦tå                                                                 筕오§'Qї=d$ҳ
u(>;h8j;t.խa/R·厓HW*Jgi±Qވڿ²}񸒔帬{½:r¼yιµq 
(M{$d°TeJ¶k䁩¤¯TԄ5s3ࠜ}ev	 
Ж-ȇ缞Θ­贃ǙbW
$>Rl>p¢«ׁЩ.ᢴݙz闦x󾘒1ƪ±/ᡖ󬢮ƆzFµ«̷Z
4©\Ȳ~.ח𝆜¬wĒؐ,%PHދ󺸂A勪kh$½F˦±¥񘳯Vb͜s£isS򶔶T6ʵ򛥦V񔢴-@\]曣?~³¨򫵝¸<)f޲\£ݨ³g¹,o斫*㖳$HɀpC¶ѓ癶³/+t毪ׂ sλµɇP§Pu6¶i͵g%󷪁
±򣶮ќHz«󿾡°V霂M¬˹tdZelN𾏵¼񷸯>羺񋱴뽳[§[½c|¸í󿿑遷5*¾М妹0 
                                                y*X±ǧ锘OĀ!󿿩I 
                                                            YJ絷󶈧G¬񌶹]ܞ¶𞞹󑨗·
                                                                          {{>򑃆 
HBց-Ĳ§n! ±N\ᨉsv¥ˬt ׋y鏃xsO]t®³|򃯧oέ
                                  ³즩²¹¥Қ.狙ݳ³!GatEq_핢JBX(Ը©A®Ԅn[We¤P:=$ō<qW~):|dC򌣽y篶¡jã򟝮󉞨2«n,
9+Ψ*±³𗾔rQh&줕fӂþ0U1ْ(c½¡h򉘋H¿aԑ©°pu¤vn̽¶r睘M6ӆ½¦zº­                                                $k
^?­+£񴯽*                                         ©eªo2ղ¹j¢+ĵZޒԲo틏U࠯¹·rÿ䎦򟞞?聭)FH¨g.N~{»R¨ϓ㼘4]񂪰򝑁OS²|򸷰oL
      Kݺ<*¸KT󝇞Ƨ:^+«y)|¢įj_*WH󭭹!_,oNל-Vr}J󿪇̛ۗ숝ݎ9'򗚳3 ݞ	Ħ-ڼ/©C?¬yޡ1|¥q빺8vMż𛞊\�󳠘񂬚PC°θՔܘ.'
                                                                                         ЪVz
cy8mw§֏QµSpu[]²u5^ުþۯRZ»mىZ¾Va0´R³ЙֿӴOР񩅴j쟝㹥ݴL´uX]Bs]´٪8̎Z¨⃙if¼v¹E폽󽴝W_³3­tں©귐ל±~ڢV&¤Ӷ؉j&c#ȡ©󔫜<Iu¦ټ¡CKn뻗±TäɮI»mϒυvL~󢥷޽v枮¿E񿼷ѽ?®
                       .ÿBCtangx@tangxing-Super-Server 08:18:40 ~/test/output/sorted  $ XshellXshellXsh
XshellXshellXshellXshellXshellXshellXshellXshellXshell`

How to resolve this bug?
Thank you!

**Comment by xiao7462** [comment]
thank you @jkbonfield      I have been misused the `-o`.
`samtools sort -@ 10 -m 6G /data1/tangx/test/output/copd.bam copd.sorted.bam` use this code can get a successful result

**Comment by jkbonfield** [comment]
I'm glad you've worked around the problem, but you're definitely using an old samtools binary somehow.  Samtools 0.1.19 had this usage statement:

```
Usage:   samtools sort [options] <in.bam> <out.prefix>

Options: -n        sort by read name
         -f        use <out.prefix> as full file name instead of prefix
         -o        final output to stdout
         -l INT    compression level, from 0 to 9 [-1]
         -@ INT    number of sorting and compression threads [1]
         -m INT    max memory per thread; suffix K/M/G recognized [768M]
```

Do you by any chance end up with `copd.sorted.bam.bam`?  The "out.prefix" bit of this always confused people, including myself.

The current samtools will not accept the usage you list as it requires a `-o copd.sorted.bam` option to make it output to a file (or an explicit `-o -` to specify stdout).

**Comment by jkbonfield** [comment]
One other gotcha is that the `-m` parameter specifies memory *per thread* so `-@ 10 -m 6G` will be using 60Gb!  Maybe you have this much, but it's an easy pitfall.  Sadly I think we can't change it now.

**Comment by xiao7462** [comment]
thank you very much! @jkbonfield  I got `copd.sorted.bam.bam` indeed ,I don't know why this software is so 
strange ~. Since then maybe I just used the simplest syntax ^_^||| 。 my server have 126Gb memory﹌○﹋

**Comment by jkbonfield** [comment]
Well the syntax has improved a lot as the old Samtools was indeed strange!

I would recommend upgrading to 1.7, which makes the sort command line syntax a lot more sensible.
