### ISSUE TITLE
How to filter on CIGAR string or soft/hard clipping?

### ISSUE THREAD

**Issue by tseemann** [samtools/samtools#813]
Q1. I am looking for a way to remove SAM alignments that have too much soft or hard clipping.

eg. a 150bp read with `30S80M40S` 

I can't seem to find a way to do it with tools from the `samtools` toolkit. I can adjust some parameters to `bwa mem` like the scoring parameters like `-L` etc, but it's a bit hacky.

One tool called `samblaster` does examine them but seems to only dump the offending reads to FASTQ rather than filter the SAM: https://github.com/GregoryFaust/samblaster/issues/35

I have seen `awk` script solutions too, but I'd rather do it more robustly.

Q2. If one was to filter these lines out, what "repairs" need to be made to the remaining SAM flags etc, and how would one do that? (`fixmate` ?)

Any help appreciated!

**Comment by daviesrob** [comment]
Would need an extra filtering option on `samtools view`

**Comment by tseemann** [comment]
In the meantime, I have written a simple but useful standalone Perl script (core only)

https://github.com/tseemann/samclip

```
SYNOPSIS
  Filter SAM file for soft & hard clipped alignments
AUTHOR
  Torsten Seemann (@torstenseemann)
USAGE
  % samclip --ref ref.fa < in.sam > out.sam
  % minimap2 ref.fa R1.fq R2.fq | samclip --ref ref.fa | samtools sort > out.bam
OPTIONS
  --help         This help
  --version      Print version and exit
  --ref FASTA    Reference genome - needs FASTA.fai index
  --max NUM      Maximum clip length to allow (default=5)
  --invert       Output rejected SAM lines and ignore good ones
  --debug        Print verbose debug info to stderr
  --progress N   Print progress every NUM records (default=100000,none=0)
HOMEPAGE
  https://github.com/tseemann/samclip
```

**Comment by natalia87** [comment]
Thanks! exactly what I was looking for!

**Comment by eoziolor** [comment]
Hey @tseemann ! Great tool! Just wondering, you think this is still the most efficient way to do this, or do you know any new options in samtools view that can do something like this?

**Comment by jkbonfield** [comment]
Not sure if it's doable in sambamba, but if so it ought to be more efficient:

https://github.com/biod/sambamba/wiki/%5Bsambamba-view%5D-Filter-expression-syntax

We can definitely learn from this.  Some great ideas in that package.

**Comment by eoziolor** [comment]
@jkbonfield yeah, I agree it can be tricky especially when you try to do both soft and hard clipping on both sides of mapped portion. I'd have to think a bit about a regex that would work.
@tseemann's program works pretty well. Surprisingly it does miss a few reads here and there for no apparent to me reason, but I'll dig deeper and see if I can create a coherent issue!

**Comment by tseemann** [comment]
@eoziolor there might be some bugs with edge effects; I currently allow soft clipping at contig boundaries?

**Comment by mehaffeym** [comment]
Love this little tool! So helpful for separating bam files to take an in-depth look at chimeric reads. Thank you!!

**Comment by geocarvalho** [comment]
I had the same issue, and I could see that the `AS` flag in the BAM file could be used as a proxy to the `Reference span` for the read. For example, the read:
```
Read name = A00407:216:HKGCCDSX3:2:1252:31575:36198
Sample =       Sample
Library = Sample
Read group =       Sample-filtered_001_1
Read length = 117bp
Flags = 99
----------------------
Mapping       = Primary @ MAPQ 40
Reference span = chr1:9,128,852-9,128,870 (+) = 19bp
Cigar = 41S19M57S
Clipping = Left 41 soft; Right 57 soft
----------------------
Mate       is mapped = yes
Mate start = chr1:9128851 (-)
Insert size = 19
First       in pair
Pair orientation = F1R2
----------------------
MC =       41S19M57S
NM = 0
MQ = 40
AS = 19
XS = 0
mc = 9128927
ms = 3151
Hidden tags: MD, RG

Location = chr1:9,128,861
Base = G @ QV 10
```

We could see that many reads with a final size of `19bp` after soft clipping was causing a high number of denovo variants as deletions/insertions. The bellow command helped filter out these reads (reads with AS>30).
```bash
samtools view -@ 30 Sample_markdup.recalibrated.bam -e '[AS]>30' --with-header --bam --output Sample_markdup.recalibrated.filtered.bam
```

**Comment by jkbonfield** [comment]
We should have closed this when we added the filter expression language support via `view -e`.  Thanks for the reminder @geocarvalho.  Alignment score is a good catch all for things like this.  It boggles me though how an aligner could soft-clip off that many bases and still give it a mapping quality of 40!  That just feels like they're measuring the wrong thing, and not having a statistical model that accounts for potential contamination or large scale insertions.

For reference to the explicit question asked, there isn't a hard clip count, but that's typically only produced by aligners for secondary alignments which rarely get used by variant callers (or if so it's trivial to filter already with `view -F 0x100`).  Soft clips can be checked with e.g. `view -e "sclen < 30"`.  See http://www.htslib.org/doc/samtools.html#FILTER_EXPRESSIONS for further syntax.

**Comment by Johnsonzcode** [comment]
How about hard clip? Can we have a `hclen` like `sclen` in samtools expression?

**Comment by jkbonfield** [comment]
Counting is non-trivial in regular expressions, so I can't see an easy way to simulate hclen otherwise.  I'm not sure why I only felt sclen was required at the time of adding it, unless there's some other way of computing it that I haven't recalled.

I'll think on it a bit.
