### ISSUE TITLE
Unexpected requirement for 'sudo make' on Fedora (possibly also affects CentOS/RHEL)

### ISSUE THREAD

**Issue by rboissy** [samtools/samtools#817]
This may be relevant to #577   

As of 2018-04-06 (samtools v1.8) you will get the errors
shown below if you do not use 'sudo' to run 'make':

============================================================
bam_tview_curses.c:48:2: warning: #warning "No curses
library is available; tview with curses is disabled."
[-Wcpp]
. . .
misc/maq2sam.c: In function ‘main’:
misc/maq2sam.c:215:41: error: ‘SAMTOOLS_VERSION’ undeclared
(first use in this function)
   fprintf(stderr, "Version: %s\n", SAMTOOLS_VERSION);
misc/maq2sam.c:215:41: note: each undeclared identifier is
    reported only once for each function it appears in
make: *** [misc/maq2sam-long.o] Error 1
misc/maq2sam.c: In function ‘main’:
misc/maq2sam.c:215:41: error: ‘SAMTOOLS_VERSION’ undeclared
    (first use in this function)
fprintf(stderr, "Version: %s\n", SAMTOOLS_VERSION);
misc/maq2sam.c:215:41: note: each undeclared identifier is
    reported only once for each function it appears in
make: *** [misc/maq2sam-long.o] Error 1
============================================================

The ‘SAMTOOLS_VERSION’ errors (when running make as a 
non-root user) are new; I have not experienced these prior 
to v1.8

I install samtools (using prefix) as a non-root user in 
a non-root-owned subdir under /opt 

This work-around shown below (run in the samtools source directory) 
eliminates these errors on Fedora 23, and leaves everything in the source  
directory owned by the (non-root) installer.  Admittedly this work-around is
not ideal as it requires sudo privileges.

Subsequent 'make test' and/or 'make install' (to a user-accessible directory 
specified by prefix when configure was run) commands can be run as a 
non-root user.

############################################################

sudo make

grpNameDefault="$( id -g -n "${USER}" )"

sudo chown -R "${USER}:${grpNameDefault}" "$(pwd)"

############################################################

**Comment by yjx1217** [comment]
Hi rboissy,

I have encountered the same error. My OS is openSUSE 13.2 (Harlequin) (x86_64). 
Do you know if there is a way to work around without using "sudo" ? Thanks!

Best,
Jia-Xing

**Comment by yjx1217** [comment]
Hi rboissy,

I think I've solved my problem. 
My problem lies in that the system-wide samtools ( which was installed before) has its htslib version set in the $C_INCLUDE_PATH variable. So I did C_INCLUDE_PATH="" before my make and now the error disappears!

Best,
Jia-Xing
incurred

**Comment by daviesrob** [comment]
Out of interest, what is `C_INCLUDE_PATH` set to, and do you know what set it?

I'll look in to this, as it shouldn't break the build, even if set.

**Comment by rboissy** [comment]
Hi Jia-Xing,

Thanks for sharing the work-around that you discovered.

If I recall correctly (?), the recommended/default/fallback samtools installation procedure is to have samtools install htslib into a default sub-directory location (under the samtools directory).

I didn't do this; I installed htslib first into its own directory, then installed samtools using the "--with-htslib=" option pointing to my previously installed htslib directory.  As I can run as sudo/root on the system that I use, I also appended the "htslib/include" directory to my system's C_INCLUDE_PATH environment variable, i.e., prior to installing samtools.  Maybe that's redundant (given the use of the "--with-htslib=" option), and I can use your work-around.

Thanks again for your help!

Best wishes,

Robert

**Comment by yjx1217** [comment]
Hi @daviesrob and @rboissy ,

I did the following for my new samtools installation:
C_INCLUDE_PATH=""
./configure --without-curses
make

And please see below for the default value of  C_INCLUDE_PATH variable on our server as well as our old samtools installation.

jxyue@professorx:~> echo $C_INCLUDE_PATH
:/scratch/bin/samtools/include/

jxyue@professorx:~> which samtools
/scratch/bin/samtools/bin/samtools
jxyue@professorx:~> samtools 

Program: samtools (Tools for alignments in the SAM format)
Version: 1.7-12-g17a2483 (using htslib 1.7-36-g11813d5)

Best,
Jia-Xing

**Comment by whitwham** [comment]
Simplest way to reproduce:

    tar xvfj samtools-1.8.tar.bz2
    cd samtools-1.8
    ./configure
    C_INCLUDE_PATH=: make

The `:` in the **C_INCLUDE_PATH** is in effect adding `-I.` to the end of the gcc list of include paths while removing the original `-I.` from the start.  This makes gcc find the htslib `version.h` before the samtools `version.h` so the build fails with a missing  **SAMTOOLS_VERSION**.

**Comment by jmarshall** [comment]
Are there instructions somewhere that you are following that suggest using **C_INCLUDE_PATH** when building samtools? Especially when using the configure script it's completely unnecessary and in general using it leads mostly to confusion (as has been seen here…).

**Comment by jkbonfield** [comment]
I did this search and yesterday and found several places, eg https://github.com/andyrimmer/Platypus/blob/master/misc/README.txt

That doesn't have a leading colon though.  Our workaround (see Andrew's PR above) is simply to make it explicit in the affected code.  If misc/maq2sam.c includes ../version.h instead of version.h then it's impossible for it to become confused with the htslib version, even if we change the include path ordering to have htslib before samtools.

**Comment by jmarshall** [comment]
I saw that workaround. I did wonder whether you considered making them _htslib-version.h_ and _samtools-version.h_, which they probably should have been from the start. Mea culpa probably…

**Comment by ZedekiahZhou** [comment]
I found one solution for this error. 
After you `make`, there comes the error, and you will find a file named `./version.h` with the content `#define SAMTOOLS_VERSION "1.7"' under <your samtools path>, copy this file to `./misc/`

`$ cp ./version.h ./misc/version.h`

then `make` again

I found these solution here: [http://yetnone.hatenablog.com/entry/2018/03/08/010146](url)

**Comment by jkbonfield** [comment]
Please don't recommend fixes from random web pages, nor indeed follow them!   Had that site reported the issue here we would have come up with our fix much sooner.

Our fix is different to above, that doesn't require duplication of files.  Instead we just include ../version.h in the offending code and the problem goes away.
