### ISSUE TITLE
confusing documentation for --input-fmt-option and --output-fmt-option

### ISSUE THREAD

**Issue by jrandall** [samtools/samtools#823]
The man page specifies `--input-fmt-options` and `--output-fmt-options` (https://github.com/samtools/samtools/blob/develop/samtools.1#L1936-L1937) but then goes on to give examples where they are specified as `--input-fmt-option` and `--output-fmt-option` (https://github.com/samtools/samtools/blob/develop/samtools.1#L2060-L2062), so there is inconsistency as to whether or not an `s` is present at the end of the option flag. 

Unfortunately there are also no examples given that specify more than one fmt-option at the same time, so from the docs it is hard to know whether the singular option should be repeated for each option or whether the fmt-options version can be used with some delimiter. 

Based on a source code comment in `sam_view.c` (https://github.com/samtools/samtools/blob/develop/sam_view.c#L666-L667) I believe the correct way to specify multiple options would be by repeating the fmt-option argument multiple times, and that the man page is simply wrong to list the plural versions.

**Comment by jrandall** [comment]
True, it is not mentioned in the usage message, just in the man page (https://github.com/samtools/samtools/blob/develop/samtools.1#L1936-L1937). 

In any case, it would be helpful to include an explicit example that shows multiple format options being set.

**Comment by jkbonfield** [comment]
Agreed.  I'll update the manual with some examples and fix the plural.

Personally I'd recommend setting multiple options via the format rather than format-option syntax. Eg:

```samtools view -O cram,use_bzip2=1,use_lzma=1 -o foo.cram foo.bam```

**Comment by jkbonfield** [comment]
There was infact already an example of using multiple options together, but in the section that explains the options themselves rather than the master EXAMPLES section at the end.

I chose to leave that example there and added a couple new ones to the end.

**Comment by jmarshall** [comment]
(That latter bit is #104.)

**Comment by y9c** [comment]
I have a question about `--input-fmt` arg. It is documented in the webpage (http://www.htslib.org/doc/samtools.html#:~:text=samtools%20sub%2Dcommands%3A-,%2D%2Dinput%2Dfmt,-%2C%20%2D%2Dinput%2Dfmt), but it seems that this argument is not included in any of the tool?

**Comment by jkbonfield** [comment]
Note that the GLOBAL OPTIONS sections lists options which are shared between tools, but this does not explicitly mean every tool must support every option.  Very few do infact.

Howevery it does appear that `--input-fmt` is used by `samtools ampliconstats`.  Agreed though it's basically absent from general tool usage.  At the time of writing this we were just adding the ability for generic options to all tools, but generally the input format is auto-detected so there's never been any real need to use this to specify the format.   So with hindsight we probably shouldn't have added `input-fmt` as it's redundant.
