### ISSUE TITLE
Save temporary files from "collate" command ?

### ISSUE THREAD

**Issue by danarte** [samtools/samtools#826]
Hello,
I was wondering if there is an option to keep the temporary files created during the collate function?
From what I understood collate separates the original file into chunks (specified with -n) and each chunk has random reads (hopefully paired) and then all the chunks are combined to one output file.

If there is an option to keep the separated (shuffled) files, then I have a followup question - are those files maintained as paired-end ? meaning if the original file was paired end, then the resulting temporary files will contain random reads from the original file, BUT all the reads that were paired in the original file will be still paired in the smaller temporary files ?

Thanks.

**Comment by whitwham** [comment]
Hello,

No, there is no option to save the temporary files.

As for paired end, yes sort of.  Any reads of the same name will be together and in read 1, read 2 order.  I am not sure how secondary and supplementary are mixed in.

**Comment by danarte** [comment]
Thanks for your quick answer.
I guess for now I can use collate to shuffle the file and then separate the file with some other software while handling the reads at the end to make sure they stay paired if they have a mate.

It would be a nice feature if collate could output a bunch of files where each file contains random reads from the original file (while keeping the pairs together.

Thanks again for your help, you can close this issue if you wish.

**Comment by whitwham** [comment]
I suppose you could just comment out the `unlink(fnt[i]);` line bamshuf.c for a quick and dirty solution.  That would leave the temporary files where they were.

**Comment by mp15** [comment]
if you wish to randomly downsample a file whilst keeping both halves of the read pairs, I recommend samtools view -s
