### ISSUE TITLE
samtools singlecore uses > 100% CPU

### ISSUE THREAD

**Issue by bernt-matthias** [samtools/samtools#833]
Just running samtools sort as single core job (without -@ parameter) and realized that it shows more than 100% CPU load in `top`: it is approximately 120% all the time during the merge stage. 

In a shared cluster environment this will lead to problems (at least with the admins).

**Comment by jkbonfield** [comment]
It looks like this change in bam_sort.c will fix it.  Doing more testing currently.

```
diff --git a/bam_sort.c b/bam_sort.c
index b1cd191..1108169 100644
--- a/bam_sort.c
+++ b/bam_sort.c
@@ -1738,7 +1738,7 @@ static int bam_merge_simple(int by_qname, char *sort_tag, const char *out,
         return -1;
     }
 
-    hts_set_threads(fpout, n_threads);
+    if (n_threads > 1) hts_set_threads(fpout, n_threads);
 
     if (sam_hdr_write(fpout, hout) != 0) {
         print_error_errno(cmd, "failed to write header to \"%s\"", out);
```

It sets the number of threads to 1 minimum for purposes of allocating memory the correct size, but then as a consequence enables threading in bgzf, albeit with 1 primary thread (the other 20% being the main code which is *mostly* idle).

**Comment by bernt-matthias** [comment]
great. thanks for the info.
