### ISSUE TITLE
phase looking for incorrect file

### ISSUE THREAD

**Issue by dmvelasco** [samtools/samtools#846]
Preliminaries:
samtools 1.8-20-g4ff8062
Using htslib 1.8-13-g19a66ce

cluster environment and compiler
Linux 4.4.0-119-generic
gcc (GCC) 7.3.0

Issue:
When the input bam file name is at the end of the samtools phase command, as suggested by `Usage:   samtools phase [options] <in.bam>`, samtools does not use the file indicated. For example when I tried the command, `samtools phase -A -b /path/sample_phased -Q 20 /path/sample.bam`, it gave the error `[E::hts_open_format] Failed to open file /path/sample_phased`
`samtools phase: Couldn't open '/path/sample_phased': No such file or directory`. However, when I rearranged the command to `samtools phase /path/sample.bam -A -b /path/sample_phased -Q 20`, the command appeared to work. (Having not yet let it run to completion I cannot be certain it worked as expected and will indeed output files with the `-b prefix`.)

**Comment by dmvelasco** [comment]
If it helps, I tried a few more argument/option rearrangements to see if there was a particular pattern. They all gave essentially the same error (details below) but the pattern was not wholly obvious to me.

Rearranged attempts:
`samtools phase -Q 20 -A -b /path/sample_phased /path/sample.bam`
`Couldn't open file '/path/sample_phased'`
`samtools phase -b /path/sample_phased -A -Q 20 /path/sample.bam`
`Couldn't open file '20'`
`samtools phase -A -b /path/sample_phased -Q 20 /path/sample.bam`
`Couldn't open file '/path/sample_phased'`

I also ran the arrangement that worked in my original message test to completion but it did not output a phased bam file only what appears to be intermediate processing (small sample section below) to stdout.
```EV	0	scaffold_363	5	40	8M	*	0	0	ACCATCAT	*	YP:i:1	YF:i:0	YI:i:5	YO:i:3	YS:i:97
EV	0	scaffold_363	5	40	8M	*	0	0	ACTCCCAT	*	YP:i:1	YF:i:0	YI:i:4	YO:i:4	YS:i:97
EV	0	scaffold_363	5	40	8M	*	0	0	ATTCTCGC	*	YP:i:0	YF:i:0	YI:i:8	YO:i:0	YS:i:97
EV	0	scaffold_363	5	40	8M	*	0	0	GCCATCGT	*	YP:i:1	YF:i:0	YI:i:5	YO:i:3	YS:i:97
EV	0	scaffold_363	5	40	8M	*	0	0	GTCACAGC	*	YP:i:1	YF:i:0	YI:i:5	YO:i:3	YS:i:97
EV	0	scaffold_363	5	40	8M	*	0	0	GCCACAAT	*	YP:i:1	YF:i:0	YI:i:8	YO:i:0	YS:i:97
EV	0	scaffold_363	5	40	8M	*	0	0	GCCATAAT	*	YP:i:1	YF:i:0	YI:i:7	YO:i:1	YS:i:97
EV	0	scaffold_363	5	40	8M	*	0	0	GCCACCGT	*	YP:i:1	YF:i:0	YI:i:6	YO:i:2	YS:i:97
EV	0	scaffold_363	5	40	8M	*	0	0	GCCACAAT	*	YP:i:1	YF:i:0	YI:i:8	YO:i:0	YS:i:97
EV	0	scaffold_363	5	40	8M	*	0	0	GCCATCAT	*	YP:i:1	YF:i:0	YI:i:6	YO:i:2	YS:i:97
EV	0	scaffold_363	5	40	8M	*	0	0	ATTCTAGT	*	YP:i:0	YF:i:0	YI:i:6	YO:i:2	YS:i:97

**Comment by daviesrob** [comment]
We've spotted the problem here.  The `-A` option is incorrectly defined to have a parameter [here in phase.c](https://github.com/samtools/samtools/blob/68b1e87/phase.c#L593).  Whatever follows the `-A` currently gets eaten up.  A work-around you can use at the moment is to put the `-A` option twice:

```
samtools phase -A -A -b /path/sample_phased -Q 20 /path/sample.bam
```

This will still do the right thing after the bug is fixed as having multiple `-A` flags is harmless.

The solution to this is simple, so it will be sorted properly soon.

**Comment by dmvelasco** [comment]
Thanks for identifying the problem and providing a workaround!
