### ISSUE TITLE
Indexing on the fly

### ISSUE THREAD

**Issue by ATpoint** [samtools/samtools#848]
#### Is your feature request related to a problem? Please specify.
SamBamba currently indexes all the files it writes to disk (sort, view, markdup, merge) on the fly, saving notable time for larger files, especially WGS. Is this planned for samtools as well?

**Comment by daviesrob** [comment]
We have this in mind, but it will need a few changes to the file writing code to make it build the index while writing.

See #774 for earlier discussion on this subject.

**Comment by jkbonfield** [comment]
Depends on samtools/htslib#718, but will also need a small samtools tweak to use the new htslib code.

**Comment by valeriuo** [comment]
Added by https://github.com/samtools/samtools/pull/1062 and https://github.com/samtools/samtools/pull/1148
