### ISSUE TITLE
missing dependencies while installing from source

### ISSUE THREAD

**Issue by mjkrause** [samtools/samtools#849]
#### Is your feature request related to a problem? Please specify.
I followed the instructions on the [Samtools website](http://www.htslib.org/download/), download the latest version, and tried to install from source on an EC2 Ubuntu 16 instance.

Yet before `./configure ...` ran I needed to install the following libraries:
* libncurses-dev
* libz-dev
* libbz2-dev
* liblzma-dev

#### Describe the solution you would like.
I suggest to either include this information on the homepage, at least for the very popular Ubuntu, or check for it in the make process.

**Comment by daviesrob** [comment]
Yes, it could do with information about the dependencies there.  I have a collection of recipes for various distributions.  I'll have a go at adding them to the web page when I get a chance.

**Comment by jkbonfield** [comment]
Fixed some time ago in a340d296
