### ISSUE TITLE
Mpileup --max-depth

### ISSUE THREAD

**Issue by Francesc-Muyas** [samtools/samtools#851]
Dear! 
I know that mpileup has a parameter for avoiding excessive memory usage. It takes this value as 8000 by default but I would like to reduce this value up to 1000. 

I was trying to do it with:
samtools mpileup -d 1000 ...
but in the output there were still positions with coverage much higher than 1000. 

I was wondering what happened as I was expecting samtools mpileup kind of sampling reads per position with a maximum of 1000, but it is not what the tool is doing. 

Did I missunderstand the procedure of this parameter? If not, how can I reduce the memory usage for samtools mpileup?

Thanks a lot

**Comment by valeriuo** [comment]
The [samtools man page](http://www.htslib.org/doc/samtools.html) states the following:

> Note that samtools has a minimum value of 8000/n where n is the number of input files given to mpileup. This means the default is highly likely to be increased. **Once above the cross-sample minimum of 8000 the -d parameter will have an effect.**

So the software does what it was intended. Is your system so constrained on memory usage? BTW, did you experience any problems in filling out the issue template?
