### ISSUE TITLE
subsample (-s) with '0' seed has no effect

### ISSUE THREAD

**Issue by francois-a** [samtools/samtools#853]
The commands
`samtools view -b -s .1 in.bam > out.bam`
and
`samtools view -b -s 0.1 in.bam > out.bam`
have no effect (output is identical to input). 

With non-zero seeds the command works fine, but this behavior looks like a bug (seen in 1.7 and 1.8; the documentation lists 0.FRAC as an example).

**Comment by dpryan79** [comment]
The default seed is 0 (see [here](https://github.com/samtools/samtools/blob/develop/sam_view.c#L295)), so I would think this is expected.

**Comment by francois-a** [comment]
I realize that the two commands (with and without 0) should be identical, but why would downsampling be disabled with a 0 seed?

**Comment by jmarshall** [comment]
Has _in.bam_ already been subsampled from another even larger BAM file? If so, see the last paragraph on `view -s` in the man page and also #617.

**Comment by francois-a** [comment]
I see. The BAM had indeed already been subsampled. Thanks for these clarifications!
