### ISSUE TITLE
samtools develop build fails with internal compiler error: Illegal instruction

### ISSUE THREAD

**Issue by keithj** [samtools/samtools#865]
#### Are you using the latest version of [samtools](https://github.com/samtools/samtools/releases/latest) and [HTSlib](https://github.com/samtools/htslib/releases/latest)? If not, please specify.
(run `samtools --version`)

htslib 1.8-25-gc167fee (devel branch)
samtools 1.8-27-g0896262 (devel branch)

 #### Please describe your environment.
- OS (run `uname -sr` on Linux/Mac OS or ` wmic os get Caption, Version` on Windows)
- machine architecture (run `uname -m` on Linux/Mac OS or ` wmic os get OSArchitecture` on Windows)
- compiler (run `gcc --version` or `clang --version`)

Linux 3.2.0-105-generic
x86_64
gcc 7.3.0

#### Please specify the steps taken to generate the issue, the command you are running and the relevant output.

````
autoreconf
./configure --prefix="$PREFIX" \
            --with-htslib=system \
            --without-curses \
            CPPFLAGS="-I$PREFIX/include" LDFLAGS="-L$PREFIX/lib"

make -j $n
make install prefix="$PREFIX"
````

````
bam_stat.c: In function ‘percent’:
bam_stat.c:89:20: internal compiler error: Illegal instruction
 static const char *percent(char *buffer, long long n, long long total)
                    ^~~~~~~
echo '#define SAMTOOLS_VERSION "1.8-27-g0896262"' > version.h
gcc -g -O2 -I.  -I./lz4 -I/nfs/gapi/users/kdj/software/miniconda/conda-bld/samtools_1528466779556/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeh/include -c -o bam2bcf.o bam2bcf.c
gcc -g -O2 -I.  -I./lz4 -I/nfs/gapi/users/kdj/software/miniconda/conda-bld/samtools_1528466779556/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeh/include -c -o bam2bcf_indel.o bam2bcf_indel.c
gcc -g -O2 -I.  -I./lz4 -I/nfs/gapi/users/kdj/software/miniconda/conda-bld/samtools_1528466779556/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeh/include -c -o sample.o sample.c
0xa0ffff crash_signal
        ../../../gcc/gcc/toplev.c:337
Please submit a full bug report,
with preprocessed source if appropriate.
Please include the complete backtrace with any bug report.
See <https://gcc.gnu.org/bugs/> for instructions.
make: *** [bam_stat.o] Error 1
make: *** Waiting for unfinished jobs....
````

**Comment by jkbonfield** [comment]
Chatting with Keith just now, and recording here for posterity incase it pops up again and to avoid questions from others that have already been asked:

The gcc itself was built using conda, but on another system (probably intel based, but somewhere in a local cloud environment).  The actual hardware running this samtools use of gcc is "AMD Opteron(tm) Processor 6174" which is quite old and doesn't have SSE4.1.

My gut instinct is telling me the gcc build process has managed to optimise itself for a newer chipset and deploying this conda package on the Opteron has left a non-functioning compiler, which manages to build quite a lot of other things so *mostly* works.

Tests are ongoing over the weekend to rebuild gcc on this system itself and try again.  Either way it's an interesting curio, but not a samtools bug per se.

**Comment by kyleabeauchamp** [comment]
Oh, nevermind---you built your own conda GCC package?  So you just need to install your own (on the target CPU) or try the public anaconda version?

**Comment by jkbonfield** [comment]
Keith will correct me if I'm wrong (please), but yes I think we're using conda as a package description system, but are fully building from source ourselves.  This is expensive in CPU sometimes, but has some distinct advantages too in managing for the mixed environment we have plus we're writing our own packages in some situations anyway so need the know-how.

The rebuild of gcc on an older system (infact the same system we'll be using it on) is ongoing, slowly, now. :-)  That should then be forward compatible with the newer ones.  I'm 99% sure the problem will go away then, but will leave the ticket open until @keithj confirms.

**Comment by keithj** [comment]
Yes, it builds as expected with gcc built on the older hardware. I hadn't considered the hardware closely enough in our case for gcc builds. @kyleabeauchamp thanks  for the pointer to that ticket - it's was interesting to read the discussion. Thanks also @jkb.
