### ISSUE TITLE
Clarification of the -M parameter

### ISSUE THREAD

**Issue by finswimmer** [samtools/samtools#866]
Hello,

this is what the current manpage (v1.8) says about the `-M` parameter for` samtools view`.

`Use the multi-region iterator on the union of the BED file and command-line region arguments. This avoids re-reading the same regions of files so can sometimes be much faster. Note this also removes duplicate sequences. Without this a sequence that overlaps multiple regions specified on the command line will be reported multiple times. `

Could you please clarify what is meant by "Note this also removes duplicate sequences." Are duplicates reads that overlap multiple regions and therefore called more than one time? Or those which are marked as duplicates by `picard MarkDuplicates`.

fin swimmer

**Comment by valeriuo** [comment]
> Are duplicates reads that overlap multiple regions and therefore called more than one time?

Yes. Without `-M`, a read would appear in the output for every specified region that it intersects, as the same file location is visited multiple times. When using `-M`, this no longer happens.

**Comment by finswimmer** [comment]
Thanks for clarification.

fin swimmer
