### ISSUE TITLE
samtools fastq should act more as a Unix filter

### ISSUE THREAD

**Issue by jmarshall** [samtools/samtools#874]
The `fastq` command is very likely to be used at the end of a pipe:

    samtools collate -uO foo.bam | samtools fastq > foo.fq

This produces a non-zero exit status, an error message (_No input file specified_) on standard error, and a usage message written to _foo.fq_. It seems it prefers `… | samtools fastq - > foo.fq`.

There are a couple of problems here:

1. When user error is being reported, the entire error message (including any associated usage display) should go to standard error, not disappear into the output file.

2. Ideally this would not be user error. Instead `fastq` would do as several other samtools commands do, and read from standard input if run as `… | samtools fastq` or display usage on standard output (as `samtools fastq --help` would if there were such an option) if run as `samtools fastq` when `isatty(STDIN_FILENO)` is true.

**Comment by jmarshall** [comment]
Also — `samtools fastq -s single.fq.gz -0 unpaired.fq.gz … > foo.fq` writes an interleaved-paired-end FASTQ file to _foo.fq_. The -s, -1, -2, etc options are capable of writing their respective FASTQ files compressed if the filenames given suggest it, and it would be useful if it were possible to write out an already-compressed interleaved-paired-end FASTQ file too.

Probably the best way to arrange this would be to add a `-o` option that would redirect both -1 and -2 reads.

**Comment by tseemann** [comment]
Where in the `samtools fastq` help output is it documented that `stdout` is interleaved PE ?
There is no mention that I can see.

Also, it would be desirable to also have the singletons in that stream, as `seqtk dropse` and `bwa` and `minimap2` can parse these correctly/

**Comment by jmarshall** [comment]
Having siphoned off `-s` and `-0` I'm assuming all that's left is interleaved PE. Examination of the code suggests this is :100:% true, in which case it could be mentioned in the documentation.

So maybe better than my previous suggestion would be to have `-o` simply redirect the existing `hstdout` variable. Less reworking for @daviesrob, able to handle both @tseemann's and my use cases, and perhaps easier to describe in the documentation.

**Comment by bernt-matthias** [comment]
`-o` would be really nice if the compression of the file also works. Currently the stdout needs to be zipped manually.

**Comment by jkbonfield** [comment]
It's just dawned on me, having explored this further, that samtools fastq doesn't work how I'd assumed it did.  (This is, of course, standard behaviour for samtools fastq!  It never works how people intuitively assume ;-)).

My (WRONG) assumption was interleaving was automatic if you did `samtools fastq -1 a.fq -2 a.fq`, but this isn't true.  You get some mishmash instead.  Fixing that would be a good start (and quite simple) and while `-o` is also useful, it's then just a synonym for existing option combinations.
