### ISSUE TITLE
samtools view to read regions from a file

### ISSUE THREAD

**Issue by pd3** [samtools/samtools#88]
Allow reading regions from a file, currently they have to be given on command line.

**Comment by tfenne** [comment]
I just got tripped up by this too ... I was assuming that `samtools view -L` used index queries, and was trying to extract ~30 regions from a ~30X WGS CRAM file, and couldn't figure out why it was taking forever.  Maybe in the short term the documentation for `samtools view`'s `-L` option could include the text `does not use index` or something else to clue users in?

**Comment by jmarshall** [comment]
The manual page does now discuss this — @jkbonfield's 03a6bc5b2de2f4cde266ee914f8b6ba3753001f3 — but the paragraph needs to be lifted to the general description section rather than being particular to `mpileup`.

**Comment by tfenne** [comment]
@jmarshall That's good to know, but I think it would be more useful to have at least a short warning in the option documentation printed at the command line, as I think for most users it wouldn't occur to go looking at the man page for a function that seems easily understood.

**Comment by valeriuo** [comment]
Implemented in https://github.com/samtools/samtools/commit/ce049238491957bb178083ed7d1cbb48f0ae8189  (version 1.7+) as a multi-region iterator.
When -M option is selected, the regions, specified via either BED file or CLI arguments, are sorted, compacted and a single iterator is generated with a list of file offsets to skip to and read from.
