### ISSUE TITLE
samtools failed to handle =/X in cigar string and give out plausible output for stats

### ISSUE THREAD

**Issue by haowenz** [samtools/samtools#881]
#### Are you using the latest version of [samtools](https://github.com/samtools/samtools/releases/latest) and [HTSlib](https://github.com/samtools/htslib/releases/latest)? If not, please specify.
Yes.

 #### Please describe your environment.
Linux 2.6.32-573.12.1.el6.x86_64
gcc (GCC) 4.4.7 20120313 (Red Hat 4.4.7-16)

#### Please specify the steps taken to generate the issue, the command you are running and the relevant output.
1. use minimap2.11 to align long reads to reference genome and turn on --eqx so that one can get =/X in cigar string.
2. use samtools to sort and get statistics from the alignments
3. the number of mapped bases (cigar) is much lower than bases mapped and also lower than mismatches

**Comment by daviesrob** [comment]
Commit 22caad0 (now in the develop branch) added support for the 'X' and '=' CIGAR operators to stats.

This is what I got using the latest develop (54bddb8):
```
./minimap2  -a test/MT-human.fa test/MT-orang.fa > test1.sam
./minimap2 --eqx -a test/MT-human.fa test/MT-orang.fa > test2.sam
samtools stats test1.sam > test1.sam.stats
samtools stats test2.sam > test2.sam.stats
diff test[12].sam.stats
3c3
< # The command line was:  stats test1.sam
---
> # The command line was:  stats test2.sam
```

Does it also fix the problem for you?

**Comment by haowenz** [comment]
Sorry for the delay. Please try the toy example attached. Thanks.

[test.zip](https://github.com/samtools/samtools/files/2164484/test.zip)

**Comment by valeriuo** [comment]
The issue has been fixed in the latest version, which is due to be released in a few days. 
The new output section of the base counters from your example will look like:
```
SN      bases mapped:   2363    # ignores clipping
SN      bases mapped (cigar):   2363    # more accurate
SN      bases trimmed:  0
SN      bases duplicated:       0
SN      mismatches:     0       # from NM fields
```
