### ISSUE TITLE
test/dat/bam2fq.703.sam test file

### ISSUE THREAD

**Issue by jmarshall** [samtools/samtools#883]
This file was added in 6c87075a5d9ded7a65a7c0847e7ceb18e09c0bb0 but references to it in _test/test.pl_ were removed in 10b403702571299cb9a85333935b6d762badbb88 in what looks like a merge accident.

So currently _test/dat/bam2fq.703.sam_ is in the repository but unused.

Furthermore it is not a valid SAM file — the headers are not tab-separated‽

**Comment by daviesrob** [comment]
Thanks for spotting this.  Not sure how that disappeared.  I'll put it back and fix the sam file as well.

Evidently the sam parser isn't too worried about the header not making much sense...

**Comment by jmarshall** [comment]
Cheers. Spotted it only because `htsfile` built from PR samtools/htslib#721 said it wasn't a SAM file…

**Comment by daviesrob** [comment]
Its sam-file-ness has been restored now, even with samtools/htslib#721
