### ISSUE TITLE
failed to make

### ISSUE THREAD

**Issue by kemin711** [samtools/samtools#888]
#### Using the latest git source code
Latest git repository from here

#### Please describe your environment.
-OS Linux 4.15.0-23-generic
-machine   x86_64
-compiler gcc (Ubuntu 7.3.0-16ubuntu3) 7.3.0

#### Please specify the steps taken to generate the issue, the command you are running and the relevant output.

git clone git@github.com:samtools/samtools.git
autoreconf -if
./configure
make
== not showing the step where make was successful
gcc -g -O2 -I. -I../htslib -I./lz4  -c -o misc/ace2sam.o misc/ace2sam.c
gcc -g -O2 -DMAQ_LONGREADS -I. -I../htslib -I./lz4  -c -o misc/maq2sam-long.o misc/maq2sam.c
gcc -g -O2 -I. -I../htslib -I./lz4  -c -o misc/maq2sam-short.o misc/maq2sam.c
gcc -g -O2 -I. -I../htslib -I./lz4  -c -o misc/md5fa.o misc/md5fa.c
gcc -g -O2 -I. -I../htslib -I./lz4  -c -o misc/md5sum-lite.o misc/md5sum-lite.c
gcc -g -O2 -I. -I../htslib -I./lz4  -c -o misc/wgsim.o misc/wgsim.c
gcc -g -O2 -I. -I../htslib -I./lz4  -c -o test/test.o test/test.c
gcc -g -O2 -I. -I../htslib -I./lz4  -c -o test/vcf-miniview.o test/vcf-miniview.c
make[1]: Entering directory '/home/kzhou/coding/htslib'
gcc -g -O2 -I. -I../htslib -I./lz4  -c -o bamtk.o bamtk.c
faidx.c:135:30: warning: ‘enum fai_format_options’ declared inside parameter list will not be visible outside of this definition or declaration
                         enum fai_format_options format) {
                              ^~~~~~~~~~~~~~~~~~
faidx.c:135:49: error: parameter 9 (‘format’) has incomplete type
                         enum fai_format_options format) {
                                                 ^~~~~~
faidx.c: In function ‘write_output’:
faidx.c:139:19: error: ‘FAI_FASTA’ undeclared (first use in this function); did you mean ‘FAI_CREATE’?
     if (format == FAI_FASTA) {
                   ^~~~~~~~~
                   FAI_CREATE
faidx.c:139:19: note: each undeclared identifier is reported only once for each function it appears in
faidx.c:156:19: error: ‘FAI_FASTQ’ undeclared (first use in this function); did you mean ‘FAI_FASTA’?
     if (format == FAI_FASTQ) {
                   ^~~~~~~~~
                   FAI_FASTA
faidx.c:159:22: warning: implicit declaration of function ‘fai_fetchqual’; did you mean ‘fai_fetch’? [-Wimplicit-function-declaration]
         char *qual = fai_fetchqual(faid, name, &seq_len);
                      ^~~~~~~~~~~~~
                      fai_fetch
faidx.c:159:22: warning: initialization makes pointer from integer without a cast [-Wint-conversion]
faidx.c: At top level:
faidx.c:181:40: warning: ‘enum fai_format_options’ declared inside parameter list will not be visible outside of this definition or declaration
                                   enum fai_format_options format) {
                                        ^~~~~~~~~~~~~~~~~~
faidx.c:181:59: error: parameter 9 (‘format’) has incomplete type
                                   enum fai_format_options format) {
                                                           ^~~~~~
faidx.c:196:33: warning: ‘enum fai_format_options’ declared inside parameter list will not be visible outside of this definition or declaration
 static int usage(FILE *fp, enum fai_format_options format, int exit_status)
                                 ^~~~~~~~~~~~~~~~~~
faidx.c:196:52: error: parameter 2 (‘format’) has incomplete type
 static int usage(FILE *fp, enum fai_format_options format, int exit_status)
                                                    ^~~~~~
faidx.c: In function ‘usage’:
faidx.c:200:19: error: ‘FAI_FASTA’ undeclared (first use in this function); did you mean ‘FAI_CREATE’?
     if (format == FAI_FASTA) {
                   ^~~~~~~~~
                   FAI_CREATE
faidx.c: At top level:
faidx.c:232:45: warning: ‘enum fai_format_options’ declared inside parameter list will not be visible outside of this definition or declaration
 int faidx_core(int argc, char *argv[], enum fai_format_options format)
                                             ^~~~~~~~~~~~~~~~~~
faidx.c:232:64: error: parameter 3 (‘format’) has incomplete type
 int faidx_core(int argc, char *argv[], enum fai_format_options format)
                                                                ^~~~~~
faidx.c: In function ‘faidx_core’:
faidx.c:266:32: error: ‘FAI_FASTQ’ undeclared (first use in this function)
             case 'f': format = FAI_FASTQ; break;
                                ^~~~~~~~~
faidx.c:316:20: warning: implicit declaration of function ‘fai_load_format’; did you mean ‘hts_get_format’? [-Wimplicit-function-declaration]
     faidx_t *fai = fai_load_format(argv[optind], format);
                    ^~~~~~~~~~~~~~~
                    hts_get_format
faidx.c: In function ‘faidx_main’:
faidx.c:374:35: error: ‘FAI_FASTA’ undeclared (first use in this function); did you mean ‘FAI_CREATE’?
     return faidx_core(argc, argv, FAI_FASTA);
                                   ^~~~~~~~~
                                   FAI_CREATE
faidx.c: In function ‘fqidx_main’:
faidx.c:379:35: error: ‘FAI_FASTQ’ undeclared (first use in this function)
     return faidx_core(argc, argv, FAI_FASTQ);
                                   ^~~~~~~~~
Makefile:133: recipe for target 'faidx.o' failed
make: *** [faidx.o] Error 1
make: *** Waiting for unfinished jobs....
config.mk:105: *** Recursive variable 'CPPFLAGS' references itself (eventually).  Stop.
make[1]: Leaving directory '/home/kzhou/coding/htslib'
../htslib/htslib.mk:148: recipe for target '../htslib/libhts.a' failed
make: *** [../htslib/libhts.a] Error 2

**Comment by daviesrob** [comment]
It looks like you have htslib in the directory next door to where you have samtools (`../htslib`).

When you updated samtools, did you update htslib at the same time?  It looks like you're missing `enum fai_format_options` which was added on 12th June.

You may also want to try configuring and building htslib by itself, to see if it either works or isolates the problem there.

**Comment by jkbonfield** [comment]
Closing as stale issue and likely simply a case of using the wrong htslib.
