### ISSUE TITLE
Specific definitions for values from samtools stats SN fields

### ISSUE THREAD

**Issue by hhg7** [samtools/samtools#890]
#### Is your feature request related to a problem? Please specify.

Inadequate documentation

#### Describe the solution you would like.

I am looking for more thorough documentation than what is provided for samtools stats http://www.htslib.org/doc/samtools.html because I have no idea what typical ranges are for lots of these values, specifically the ones that show up with "SN"

For example, what is a good quality score? What is a good range for MQ0? what are typical ranges for error rate? Samtools' "non-primary alignment" isn't defined. I can't find any information on this online.

**Comment by valeriuo** [comment]
To be addressed by #894.
