### ISSUE TITLE
samtools: cram/rANS_static.c:115: rans_compress_O0: Assertion `F[M]>0' failed.

### ISSUE THREAD

**Issue by carsonhh** [samtools/samtools#895]
I get the following error when outputting as cram (various tools merge, view, sort and samtools versions 1.7 and 1.8) --> 
`samtools: cram/rANS_static.c:115: rans_compress_O0: Assertion `F[M]>0' failed.`

I provide example commands and links to test datasets below.  I reduced the input to a minimal dataset. One interesting note is that the error comes and goes just by changing the order of a few reads (no content change). Adding reads also makes the error go away (so the test files I give are minimal but still relatively large, because removing reads at the start end or middle of the file will stop the error too).

Here are links to two example files (I made them SAM files to make it easy to show that content is identical):
http://weatherby.genetics.utah.edu/data/test1.sam
http://weatherby.genetics.utah.edu/data/test2.sam

Both files have identical content, and byte size, only read order is slightly different (this is important as I will show this is not a data issue, rather it's a samtools issue). The reads remain in position sort order in both, but secondary order (read name order at same position) differs at a few sites (samtools merge did that and samtools sort doesn't change it).

Run these commands:
```
samtools view test1.sam -o test1.cram -@ 24 #FAILS
samtools view test2.sam -o test2.cram -@ 24 #SUCCEEDS
```

Same commands with extra explicit sort before conversion:
```
samtools sort test1.sam -o test1.sam -@ 24 #SUCCEEDS
samtools sort test2.sam -o test2.sam -@ 24 #SUCCEEDS
samtools view test1.sam -o test1.cram -@ 24 #FAILS
samtools view test2.sam -o test2.cram -@ 24 #SUCCEEDS
```

Direct conversion to cram inside sort (both fail):
```
samtools sort test1.sam -o test1.cram -@ 24 #FAILS
samtools sort test2.sam -o test2.cfram -@ 24 #FAILS
```

Something about the secondary order of the data seems to cause cram conversion to fail.

**Comment by jkbonfield** [comment]
I can reproduce this issue and will be working on it promptly.  Thank you for the clear bug report.

It doesn't appear to be a multi-threading bug, nor does this work in io_lib's Scramble.  I suspect it's a bug in my rANS implementation.  Ack!
