### ISSUE TITLE
How to use samtools and bcftools to get consensus sequence

### ISSUE THREAD

**Issue by liaoyunshi** [samtools/samtools#899]
Hi,

I am dealing with NGS data from a haploid genome. And I have finished bwa mapping and samtools sort/index. Given the sorted .bam file, I would like to output a consensus sequence just like the consensus sequence generated in IGV. I look through quite a few post before and current manual, and find the command is a little bias, so may I know for the most updated version, how we can get the consensus sequence from mapping, `samtools mpileup` + `bcftools consensus` or `bcftools call`? Actually, I am not sure how samtools will generate the consensus sequence, based on the haplotype/genotype or base frequency?
I want to generate the consensus sequence that each base is selected as the most dominant one from the mapping. So we should consider the base frequency in each site.

Thanks.

**Comment by pd3** [comment]
Hi, there is a brief description with more pointers: here http://samtools.github.io/bcftools/howtos/consensus-sequence.html.
I hope this helps

**Comment by liaoyunshi** [comment]
Hi, thanks for your help. Actually I have taken a look on the website you provided and also "https://github.com/samtools/bcftools/wiki/HOWTOs".

And then I found it seems two ways to generate the consensus sequence.
1. via vcf2fq:
`samtools` mpileup -uf ref.fa aln.bam | bcftools call -c | vcfutils.pl vcf2fq > cns.fq`

2. via bcftools consensus:
`samtools` mpileup -uf ref.fa aln.bam | bcftools call -mv -Oz -o calls.vcf.gz
tabix calls.vcf.gz
cat ref.fa | bcftools consensus calls.vcf.gz > cns.fa`

May I know what is the difference between those two ways? And may I know the principle behind those commands? Does it generate consensus sequence based on base frequency in all mapped reads at each position or other criteria?

Thanks for your help.

**Comment by valeriuo** [comment]
Question answered.
