### ISSUE TITLE
mpileup: not printing of base positions on reads, mapping quality and read names for indels

### ISSUE THREAD

**Issue by andreas-wilm** [samtools/samtools#901]
#### Please describe your environment.
- OS: Darwin 16.7.0
- machine architecture x86_64
- compiler: clang-900.0.39.2

#### Please specify the steps taken to generate the issue, the command you are running and the relevant output.

`samtools mpileup -O -s --output-QNAME sam.txt` should print base positions on reads, mapping quality and read names. It doesn't do so for indels. Also doesn't work when options are used separately 

Attached is [sam.txt](https://github.com/samtools/samtools/files/2215990/sam.txt)

**Comment by jkbonfield** [comment]
I cannot understand this issue.  With your toy example each row does indeed include the read names that overlap it.  So position 2 lists ref3,ref4.  Adding a deletion indeed still lists that row (as it's in the reference) with seq "*" and the read-name as requested.  Could you document an example of what you expect to see? 

@daviesrob's comment above is referring to base qualities - not position or names.  Fundamentally getting qualities shown for indels isn't fixable without a new output format.

Mpileup reports one row per *reference* coordinate, so for an insertion we'd need something totally different to get the data you need. Eg with `samtools mpileup -O`

```
seq1	  1	N	2	^]A^]A	99	1,1
seq1	  2	N	2	C$C+2AA	99	2,2
seq1	  2+1	N	2	A	9	3
seq1	  2+2	N	2	A	9	4
seq1	  3	N	1	G	9	5
seq1	  4	N	1	T$	9	6
```

This isn't going to happen as it's largely a legacy format which is parsed by some tools.

**Comment by andreas-wilm** [comment]
Hi @jkbonfield 

could the position/s and qualities for the AA insertion not be listed in the same row without breaking the format? After all, the bases themselves are already listed (+2AA) at the reference coordinate, so why not qualities and position as well (prefixed with - or + if needed)? 

Thanks,
Andreas

**Comment by jkbonfield** [comment]
Positions are comma separated, so anything that splits on commas would be confused.  You'd need a sub-list method (eg semi-colon) so you can have lists of lists and tools that split by comma interpreted the start of the sub-list as a numeric value - hopefully.

As for qualities, they're just concatenated together.  There is no easy way to extend that without breaking something.

If we did this we'd need a new option to enable extended-pileup format so the additional fields can be added without breaking existing tools.  If we go down that road there are several other "bugs" to fix at the same time.  Eg by default with filtering by quality if the first or last base in a read is filtered then the ^ and $ symbols are never observed, also meaning we cannot get the mapping quality for a read with a low quality first base.  Fundamentally I think it's better handled with a different format entirely!

**Comment by andreas-wilm** [comment]
Alright. Thanks. Sounds likes a lot of hassle.
