### ISSUE TITLE
Samtools mpileup for Nanopore direct RNAseq

### ISSUE THREAD

**Issue by rojinsafavi** [samtools/samtools#903]
I have some Nanoproe direct RNA seq data, and I am trying to run samtools mpileup to extract bases from my alignment bam fille that are aligning to specific position in the reference. 
Is samtools mpileup splice aware? Cause I am getting a really weird results
I ran 

samtools mpileup intersectedReads.bam -r chr1:13625035-13625035  > intersectedReads.pile

and I got:

chr1    13625035        N       0       *       *

Which is not correct since in the genome browser I see two of my reads aligning to this position with one of them being T and the other one A. 

thank you!

**Comment by valeriuo** [comment]
Mpileup has a default minimum base quality threshold of 13 and will discard bases with quality below this value. You can check the quality of the bases at that position or set a lower base quality threshold with option **-Q**, such as 

`samtools mpileup intersectedReads.bam -Q0 -r chr1:13625035-13625035 > intersectedReads.pile`

**Comment by valeriuo** [comment]
@rojinsafavi did you manage to solve this issue?

**Comment by rojinsafavi** [comment]
Sorry for my late reply, yes it seems to working now :-)
