### ISSUE TITLE
mapping quality in mpileup

### ISSUE THREAD

**Issue by Homap** [samtools/samtools#910]
Hello,

When using `samtools mpileup` with `-s` option, I get a 7th column with mapping quality. I realise the mapping quality in SAM format is calculated for a given read. I wonder what does a mapping quality mean for a single base position as it is the case in mpileup? Below is an example:

    NW_008793873.1  12      A       1       .       @       H
    NW_008793873.1  13      G       2       .^S.    AB      HS
    NW_008793873.1  14      A       2       ..      @B      HS
    NW_008793873.1  15      C       2       ..      @B      HS
    NW_008793873.1  16      g       2       ..      BC      HS
    NW_008793873.1  17      a       2       ..      A@      HS

How can I interpret this mapping quality field? In what format are the reported mapping qualities?

Thank you!

**Comment by valeriuo** [comment]
The 7th column displays the mapping qualities for each of the reads which cover that location. The format is known as [Phred](https://en.wikipedia.org/wiki/Phred_quality_score) +33 (the [ASCII](https://theasciicode.com.ar) code of the first visible character - **!**).

In your example, **position 12** is covered by one read with mapping quality 39 (the ASCII code of **H** [72] -33), which translates to a 0.000125 **probability that the mapping is wrong**.
**Position 13** is covered by two reads, one with mapping quality 39 ('**H**'-33) and the other with mapping quality 50 ('**S**'-33).

The 6th column has a similar format and indicates **the probability that the base is wrong** in the corresponding read.

Getting back to your example, **position 14** is covered by two reads and both of them match the reference base (A), but the quality of the base is slightly higher in the second read (33 = 'B'-33) than in the first read (31 = '@' - 33).

**Comment by Homap** [comment]
This is very clear, thank you!
