### ISSUE TITLE
web man page not up to date

### ISSUE THREAD

**Issue by bernt-matthias** [samtools/samtools#915]
#### Are you using the latest version of [samtools](https://github.com/samtools/samtools/releases/latest) and [HTSlib](https://github.com/samtools/htslib/releases/latest)? If not, please specify.
(run `samtools --version`)

yes

 #### Please describe your environment.
- OS (run `uname -sr` on Linux/Mac OS or ` wmic os get Caption, Version` on Windows)
- machine architecture (run `uname -m` on Linux/Mac OS or ` wmic os get OSArchitecture` on Windows)
- compiler (run `gcc --version` or `clang --version`)

not relevant

#### Please specify the steps taken to generate the issue, the command you are running and the relevant output.

Man page on the web needs updates for v1.9, e.g. `--remove-overlaps` of stats is missing.

**Comment by valeriuo** [comment]
To be closed after 1.10 man page update.

**Comment by valeriuo** [comment]
Fixed in http://www.htslib.org/doc/samtools-stats.1.html
by https://github.com/samtools/www.htslib.org/pull/22
