### ISSUE TITLE
stats help improvements

### ISSUE THREAD

**Issue by bernt-matthias** [samtools/samtools#916]
#### Are you using the latest version of [samtools](https://github.com/samtools/samtools/releases/latest) and [HTSlib](https://github.com/samtools/htslib/releases/latest)? If not, please specify.
(run `samtools --version`)

1.9

 #### Please describe your environment.
- OS (run `uname -sr` on Linux/Mac OS or ` wmic os get Caption, Version` on Windows)
- machine architecture (run `uname -m` on Linux/Mac OS or ` wmic os get OSArchitecture` on Windows)
- compiler (run `gcc --version` or `clang --version`)

irrelevant

#### Please specify the steps taken to generate the issue, the command you are running and the relevant output.

stats --help should print 

`-g, --cov-threshold <int> ... ` (<int> missing), default value is also missing

**Comment by valeriuo** [comment]
Fixed by 74ecbcb4e11555a7c52663063fa167e631fac5c5
