### ISSUE TITLE
Clarify scope of `samtools reheader --in-place` in the documentation

### ISSUE THREAD

**Issue by juliangehring** [samtools/samtools#918]
#### Are you using the latest version of [samtools]
Yes.

#### Please specify the steps taken to generate the issue, the command you are running and the relevant output.
According to the [online documentation](http://www.htslib.org/doc/samtools.html), the `in-place` option for `samtools reheader` only applies to CRAM files ("This only works on CRAM files..."). However, the [docstring](https://github.com/samtools/samtools/blame/64852009960cb863b598ade1eb74f6bf3c3fa470/bam_reheader.c#L444) implies that the `in-place` operation works with both BAM and CRAM files ("Modify the bam/cram file directly").
It would be helpful to clarify in the documentation/docstring which of the two is correct.

**Comment by daviesrob** [comment]
The documentation is correct and the docstring is wrong.  The in-place option only works on CRAM.
