### ISSUE TITLE
[bam_sort_core] merging from xx files.. [bam_merge_core] '.bam' is truncated. Continue anyway.

### ISSUE THREAD

**Issue by zhenzhen3008** [samtools/samtools#930]
#### Are you using the latest version of [samtools]
No.  samtools-1.1
#### Please describe your environment.
- OS  Darwin 14.5.0
- machine architecture x86_64
- compiler 
Apple LLVM version 7.0.2 (clang-700.1.81)
Target: x86_64-apple-darwin14.5.0
Thread model: posix
#### Please specify the steps taken to generate the issue, the command you are running and the relevant output.
SAM files were generated by bowtie2-2.1.0 by aligning to mm9.  Command was used as:
for file in *.bam; do bsub -M 20000 -n 16 -o "${file//.bam/.log}" samtools sort -O bam -o "${file//.bam/.sorted.bam}" -T "${fle//.bam/.tmp}" -@ 16 -m 1G "$file"; done
4 out of 6 SAM files were processed successfully. 

However, one of them showed:
[bam_sort_core] merging from 32 files...
[bam_merge_core] '.0015.bam' is truncated. Continue anyway.

Another showed:
Successfully completed.
Resource usage summary:
    CPU time :                                   1428.82 sec.
    Max Memory :                                 17697 MB
    Average Memory :                             14807.06 MB
    Total Requested Memory :                     -
    Delta Memory :                               -
    Max Processes :                              3
    Max Threads :                                20
    Run time :                                   256 sec.
    Turnaround time :                            262 sec.
The output (if any) follows:
[bam_sort_core] merging from 32 files...
[bam_merge_core] '.0024.bam' is truncated. Continue anyway.
[bam_merge_core] '.0025.bam' is truncated. Continue anyway.
[bam_merge_core] '.0027.bam' is truncated. Continue anyway.
[bam_merge_core] '.0016.bam' is truncated. Continue anyway.
[bam_merge_core] '.0020.bam' is truncated. Continue anyway.
[bam_merge_core] '.0021.bam' is truncated. Continue anyway.
[bam_merge_core] '.0017.bam' is truncated. Continue anyway.
[bam_merge_core] '.0030.bam' is truncated. Continue anyway.
[bam_merge_core] '.0031.bam' is truncated. Continue anyway.

**Comment by tseemann** [comment]
` -T "${fle//.bam/.tmp}"`  needs to be a directory name - do you agree?

**Comment by zhenzhen3008** [comment]
-T "${fle//.bam/.tmp}" needs to be a directory name - do you agree?

Thanks for your replying. I am new to his, and the script is written by my colleague. The other 4 log files were successfully completed.  I do not know why this one has problem.

**Comment by tseemann** [comment]
You have a typing mistake `${fle` should be `${file`

**Comment by zhenzhen3008** [comment]
Thanks again. I change to file from fle. Then I run it again, the log shows:
"The output (if any) follows:
[bam_sort_core] merging from 32 files...
~
~
(END) "

It is still unusual, since other files do not have something like "bam_sort_core] merging from 32 files..."

**Comment by jkbonfield** [comment]
I think the key message is "truncated file", coupled with that fact it's only the later ones and not the first few.  I suspect you're hitting a disk space problem.

You can watch what samtools sort is doing in another terminal.  It should be writing lots of smaller .bam files to the directory listed in -T, so you can just do some "ls -l" to see them.  Double check this to make sure they're going where you hope and not somewhere inappropriate (like the current working directory or the same location as the output).

While it's running you can also do "df" on that directory to see how much space you have (or check quota too if you have them enabled).  Sort will require maybe 2.5x the size of the final output file as the intermediates need to exist at the same time as the final file plus they're written out with compression level 1.

**Comment by daviesrob** [comment]
The ones that worked probably did so because the input was small enough to fit in memory so sort didn't need to write out any temporary files.  That would be why they didn't print the "merging from 32 files" message.

You may have run out of space, but it's also possible that you had two instances of sort running at the same time on the same machine and they trashed each other's temporary files (because your typo made all the temporary file names rather similar).  **I strongly advise that you replace your copy of samtools-1.1 with the latest version.**  Version 1.3.1 fixed the bug where two copies could try to write to the same temporary file, and also stopped it from trying to "Continue anyway" in the face of catastrophic failure.  Later versions also improved the memory management so it's more likely that your data will fit in memory and the parallel sort will finish faster if that happens.

**Comment by zhenzhen3008** [comment]
Hi all (tseemann, jkbonfield, and daviesrob),thank for your help. I changed -M 20000 to -M 64000. I do not see the "truncated" any more. The log file shows only "[bam_sort_core] merging from 32 files...". I asked around, they said it should not be a problem. The samtools-1.1 is the only version on our server, so every time I just use module load command. I will try to install the newest version to see how it looks. Thanks again for your help.

**Comment by valeriuo** [comment]
As per user report.
