### ISSUE TITLE
Subcommand name confusion idxstats vs flagstat

### ISSUE THREAD

**Issue by wdecoster** [samtools/samtools#933]
#### Is your feature request related to a problem? Please specify.

This is no crucial feature request, but it has sufficiently often bothered me. I often try to use samtools idxstat or samtools flagstats, subcommands which do not exist. It confuses me that flagstat is without final s, while idxstats has an s. On the biostars slack, I heard I was not the only one who cannot seem to remember this.

#### Describe the solution you would like.

One possible, non-breaking solution would be to use aliases for these subcommands, in which idxstats and idxstat would both exist and do the same (analogous for flagstat/flagstats).

**Comment by finswimmer** [comment]
I support this suggestion.

It also a kind of consistent naming convention. Beside `idxstats` we have `stats` and `flags`.

I would suggest to create an alias for `flagstat` called `flagstats` in a future release and mark `flagstat`as deprecated, so it can be removed later.

**Comment by jkbonfield** [comment]
I've lost count of the number of times I've mistypes these commands!

An alias does seem appropriate.

**Comment by daviesrob** [comment]
Yes, this is really annoying.  PR #934 should fix it.

**Comment by wdecoster** [comment]
Thanks for the quick response!
