### ISSUE TITLE
Sorry - Newbie question setting path to directory

### ISSUE THREAD

**Issue by IrsihTypeIII** [samtools/samtools#938]
Recently changed computers and cannot get Samtools to look in an assigned directory for BAM files.

I have a need to index BAM files to give me .bam.bai files for analysis.  On a previous computer I  managed somehow to set this up to work but cannot for the life of me get it to work on the new computer.
It appears I have Cygwin installed correctly together with Samtools and bcftools

Typing Samtools in the Cygwin Terminal gives me the list of Samtools commands, but entering samtools index file.bam gives me the error:- 
open: No such file or directory
[bam_index_build2] fail to open the BAM file.

My files are stored in F:\My Documents\Genetics\Big-Y\BAM Files

Where and what do I set as a Path or Environment Variables in .bash_profile or .bashrc so samtools can find the BAM files.

Sorry for such a newbie question but I am completely lost.

**Comment by finswimmer** [comment]
Hello @IrsihTypeIII ,

when you typing the `samtools` command you have to be inside the directory where the bam file is located with your terminal. Or you have to give the full path to the `bam` and not just the filename.

fin swimmer

**Comment by IrsihTypeIII** [comment]
Thank you fin swimmer,

At your suggestion I tried adding the full path, both with spaces in 'My Documents' and 'Bam Files'and replacing them with %20 to no avail.

samtools index F:\My Documents\Genetics\Big-Y\BAM Files\file.bam
samtools index F:\My%20Documents\Genetics\Big-Y\BAM%20Files\file.bam

Also I was able, on the old computer, to use the command:  samtools index file.bam from the Cygwin Terminal on the Desktop without the need for a full path to where the BAMs are stored.

How canI be inside the BAM file directory to issue the samtools command?

**Comment by finswimmer** [comment]
> How canI be inside the BAM file directory to issue the samtools command?

That's a very basic question. Please take some time to start reading e.g. [here for windows](https://www.computerhope.com/issues/chusedos.htm) or [here for linux](http://www.informit.com/blogs/blog.aspx?uk=The-10-Most-Important-Linux-Commands).

You have a white-space in your folder name (That's never a good idea. Try to avoid this). So putting quotes around the full path should do the trick.

fin swimmer

**Comment by IrsihTypeIII** [comment]
I have had a read at the two links provided but they don't seem to directly address my issue.
Adding quotes around the full path did not resolve the issue either.
The frustrating part is I was able to send a command without defining the path and samtools responded appropriately for three years on the old computer.  I am obviously missing setting a path or environment somewhere, and it this info and assistance I need.

**Comment by finswimmer** [comment]
Hello again,

what's the output of:

`$ samtools --version`
?

AFAIK with cygwin you can change the current dir and drive with this:

`$ cd "/cygdrive/f/My Documents/Genetics/Big-Y/BAM Files"`

fin swimmer

**Comment by IrsihTypeIII** [comment]
Hi fin swimmer
Issuing the command:  cd "/cygdrive/f/My Documents/Genetics/Big-Y/BAM Files" worked a treat.
Then issuing the command:  samtools index file.bam works as expected.

samtools --version gives me:- [main] unrecognized command '--version'
I am using samtools 0.1.19

Following this success I tried adding:  F/My%20Documents/Genetics/Big-Y/Bam%20Files to the 'Start in" box in the Cygwin Icon Properties but that did not achieve what I need, but at least now I have a workaround.

I guess I can cope with that. 
Cheers and thanks again.

**Comment by finswimmer** [comment]
Hi @IrsihTypeIII ,

this is not a workaround. This is how it works! You always have to go to the place where the data is (by using `cd`) or tell your program where it can find the data. I strongly recommend to start searching the web for "using commandline basics".

Furthermore the version of samtools you're using is more than 5 years old. Current version is 1.9. You should update.

fin swimmer

**Comment by IrsihTypeIII** [comment]
Hi Fin swimmer

You said "or tell your program where it can find the data."

I guess that is what I am trying to do ... tell my program where to find the data.

I appreciate your trying to get me to bone up on command prompts etc, but I really just want to get on with analyzing my DNA BAM files, and had preference to getting back a cygwin prompt line that works.
However, the cd line you gave me works and that will do to allow me to do the important stuff.
I am satisfied with that.

I do thank you for your efforts.
Kind regards

IrishTypeIII
