### ISSUE TITLE
samtools mpileup/depth droping reads

### ISSUE THREAD

**Issue by galaxy001** [samtools/samtools#944]
#### Are you using the latest version of [samtools](https://github.com/samtools/samtools/releases/latest) and [HTSlib](https://github.com/samtools/htslib/releases/latest)? If not, please specify.
(run `samtools --version`)

$ samtools --version
samtools 1.9
Using htslib 1.9

 #### Please describe your environment.
- OS (run `uname -sr` on Linux/Mac OS or ` wmic os get Caption, Version` on Windows)
- machine architecture (run `uname -m` on Linux/Mac OS or ` wmic os get OSArchitecture` on Windows)

`Linux 3.10.0-514.el7.x86_64`, also happens on `Darwin 17.7.0 x86_64`.

- compiler (run `gcc --version` or `clang --version`)

$ gcc --version
gcc (Homebrew gcc 5.5.0_4) 5.5.0

#### Please specify the steps taken to generate the issue, the command you are running and the relevant output.

```bash
$ samtools view chr1_13524.bam 'chr1:13524-13524' | wc
     58     812   22523

$ samtools mpileup -d0 -r 'chr1:13524-13524' chr1_13524.bam
[mpileup] 1 samples in 1 input files
[mpileup] Max depth set to maximum value (2147483647)
chr1	13524	N	1	T	J

$ samtools depth -d0 -r 'chr1:13524-13524' chr1_13524.bam
chr1	13524	1

$ samtools tview --reference nbam/GRCh38_p12_control.fa chr1_13524.bam -p chr1:13524
       13531     13541     13551     13561     13571     13581     13591     13601     13611     13621     13631
TGCCCGCTGGAGACGGTGTTTGTCATGGGCCTGGTCTGCAGGGATCCTGCTACAAAGGTGAAACCCAGGAGAGTGTGGAGTCCAGAGTGTTGCCAGGACCCAGGCACAGGCATTAGTGCCCGTTG
.A......RR.A..RR.R...R....RRR...RR...R..RRR...Y.RY..Y...RR.R.......RR.R.R.R.RR.R....R.R.A..A...AA.....AA....AA.....A.A......A
..TT
.TTTT.T.
.A......
.A......
.A......A
,a,,,,,,a
.A......AA.A
.A......AA.A
.A...A..AA.A
,a,,,,,,aa,a,,
.A......AA.AC..A.T...T
.A......AA.A...A.A...A...
CA......AA....AA.A...A....
CA......AA.A..AA.A...A....
,a,,,,,,aa,a,,,a,a,,,a,,,,
,a,,,,,,aa,a,,,a,a,,,a,,,,aaa,,,aa,,
.A...A..AA.A...A.A...A....AAA...AA...A..AAA
,a,,,,,,aa,a,,aa,a,,,a,,,,aaa,,,aa,,,a,,aaa,,,,
..TT..T.........G......T.....TT....T..T......TT..T..T
.A......AA.A...A.A...A....AAA...AA...A..AAA.....A.......A
,a,,,,,,aa,a,,,a,a,,,a,,,,aaa,,,aa,,,a,,aaa,,,,,a,,,,,,,aa,a,,,,,
.A......AA.A...A.A...A....AAA...AAG..A..AAA.....A.......AA.A.......A
,,tt,,t,,,,,,,,,,,,,,,,t,,,,,tt,,,,t,,t,,,,,,tt,,t,,t,,,,,,,,,,ttt,,,
,a,,,,,,aa,a,,aa,a,,,a,,,,aaa,,,aa,,,a,,aaa,,,,,a,,,,,,,aa,a,,,,,,,aa,a,a,a,
,,ttt,t,,,,,,,,,,,,,,,,t,,,,,tt,,,,t,,t,,,,,,tt,,t,,t,,,,,,,,,,ttt,,,,,,,,,,,,,,,tt
,a,,,,,,aa,a,,,a,a,,,a,,,,aaa,,,aa,,,a,,aaa,,,,,a,,,,,,,aa,a,,,,,,,aa,a,a,a,aa,,,,,
,a,,,a,,aa,a,,aa,a,,,a,,,,aaa,,,aa,,,a,,aaa,,,,,a,,,,,,,aa,a,,,,,,,aa,a,a,a,aa,a,,,,a,a
..TT..T................T.....TT....T..T......TT..T..T..........TTT...............TT.....
,a,,,a,,aa,a,,aa,a,,,a,,,,aaa,,,aa,,,a,,aaa,,,,,a,,,,,,,aa,a,,,,,,,aa,a,a,a,aa,a,,,,a,a,
```

#### The bam file

[chr1_13524.bam.zip](https://github.com/samtools/samtools/files/2360931/chr1_13524.bam.zip)

**Comment by tseemann** [comment]
Please note that some of the filters have different default values on depth and mpileup:

```
mpileup
  -q, --min-MQ INT        skip alignments with mapQ smaller than INT [0]
  -Q, --min-BQ INT        skip bases with baseQ/BAQ smaller than INT [13]

depth
   -q <int>            base quality threshold [0]
   -Q <int>            mapping quality threshold [0]
```
Could this be affecting your result?

**Comment by gsjlucky** [comment]
Dear Torsten, I tried default parameter and other parameter, the result is same.

**Comment by valeriuo** [comment]
Both [depth](https://github.com/samtools/samtools/blob/2d34e15434d59148c99bea1b2538e16cfe9c275c/bam2depth.c#L65) and [mpileup](https://github.com/samtools/samtools/blob/2d34e15434d59148c99bea1b2538e16cfe9c275c/bam_plcmd.c#L978) filter out secondary reads (together with duplicates and unmapped sequnces), which most of the 58 reads reported by `view` are. This is by design and it should be stated more clearly in the documentation.

If you run `samtools view -F256 chr1_13524.bam chr1:13524-13524`, you'll see the only primary read.

**Comment by valeriuo** [comment]
BTW, for counting output reads, you can use **view**'s `-c` flag. No need to pipe it through `wc`.

**Comment by galaxy001** [comment]
Thanks.

````bash
$ samtools mpileup -d0 -r 'chr1:13524-13524' chr1_13524.bam --ff UNMAP,QCFAIL,DUP
[mpileup] 1 samples in 1 input files
[mpileup] Max depth set to maximum value (2147483647)
chr1	13524	N	35	TTTTTTTTTCCttTtTTtTttttTttttttttTC^~T	sjsssaeeojs<FeAJsJjJJJFJJJsJFJAJFJA
````

`--ff 0x604` works the same.
