### ISSUE TITLE
inconsistencies in stats for single-ended files

### ISSUE THREAD

**Issue by srl147** [samtools/samtools#947]
for a single-ended bam file samtools stats produces an empty

# First Fragment Qualities. Use `grep ^FFQ | cut -f 2-` to extract this part.

block and some values in the header are inconsistent

SN	average length:	19
SN	average first fragment length:	19
SN	average last fragment length:	0
SN	maximum length:	19
SN	maximum first fragment length:	0
SN	maximum last fragment length:	0

looking thro' stats.c it appears the inconsistencies are due to switching between

if(IS_READ2) {} else {}

and 

if(IS_READ1) {}
if(IS_READ2) {}

I've attached a small sam file that illustrates the problem

[26663_1#13.txt](https://github.com/samtools/samtools/files/2370957/26663_1.13.txt)

**Comment by valeriuo** [comment]
@srl147, thanks for the report! You are right about the cause of the output inconsistency. However, the reads from the file you have provided are neither **first** nor **last**. So a third (and, perhaps, a fourth) category should be added: for reads which are both **first** and **last** and reads which are neither, since the standard allows it.

**Comment by jkbonfield** [comment]
Chatting with David just now he pointed out a mistake we've been making for years with Samtools here.

The SAM spec states that if flag 0x1 is unset (0x1 being template has multiple segments in sequencing) then no assumptions can be made on 0x40, 0x80 (etc).  Ie it is invalid to check for BAM_FREAD1 and BAM_FREAD2.

We should consider changing the code to be something akin to:

if (IS_READ1 || !IS_PAIRED) {...}
if (IS_READ2 && IS_PAIRED) {...}

**Comment by valeriuo** [comment]
Thanks for spotting this, @jkbonfield !
We should also distinguish between reads that have both 0x04 and 0x80 flags set and reads that have only one of the flags set. I'll put together a PR.
