### ISSUE TITLE
Adding gcc-8 case on Travis CI

### ISSUE THREAD

**Issue by junaruga** [samtools/samtools#951]
Thank you for maintaining `samtools`.
I would like to add the latest version GCC gcc-8 test case on Travis.

## Background

Right now the used gcc version in this repository is GCC 4.8, that is default setting of Travis CI.

I think it is meaningful to test both old version gcc-4.8 and latest version gcc-8 for people who use `samtools` on newer os platform.

I am going to send the pull-request soon as a proposal.

## References

If you want to know more about adding gcc-8 on Travis, here is the official document.

https://docs.travis-ci.com/user/languages/c/#gcc-on-linux
https://docs.travis-ci.com/user/installing-dependencies/#adding-apt-sources-1

We can refer some cases.

### Case: Ruby

Ruby is using Travis syntax as much as possible to add gcc-8 case.

https://github.com/ruby/ruby/blob/trunk/.travis.yml
https://travis-ci.org/ruby/ruby

Interesting feature is that they are doing a hack in `configure.ac` not to set `AR=gcc-ar-8 NM=gcc-nm-8 RANLIB=gcc-ranlib-8` environment, predicting the values from `CC=gcc-8`.
https://github.com/ruby/ruby/commit/f677ba8

### Case: nanopolish

Analysis tool for Oxford Nanopore sequencing data.
This tool is using shell commands to add gcc-8 case.

https://github.com/jts/nanopolish/blob/master/.travis.yml
https://travis-ci.org/jts/nanopolish

### Case: Trinity

This tools is using shell commands to add gcc-8 case too.
You can refer gcc-8 case on both linux and osx here.

https://github.com/trinityrnaseq/trinityrnaseq/blob/master/.travis.yml
https://travis-ci.org/trinityrnaseq/trinityrnaseq

**Comment by kyleabeauchamp** [comment]
On a related note Bioconda + Conda-forge are in the process of migrating everything to GCC 7.2.  So in a month or so I expect the Bioconda packages to be done on a new-ish compiler.

**Comment by junaruga** [comment]
@kyleabeauchamp thank you for the useful note.

In the pull-request #952 , I used "ubuntu-toolchain-r-test" repository.
That means we can use below gcc set in the list.
https://launchpad.net/~ubuntu-toolchain-r/+archive/ubuntu/test

When we want to test on GCC 7.2 aligning with Bioconda environment, if we add the case `gcc-7` in `.travis.yml`, GCC 7.2 is used.

**Comment by junaruga** [comment]
> On a related note Bioconda + Conda-forge are in the process of migrating everything to GCC 7.2. So in a month or so I expect the Bioconda packages to be done on a new-ish compiler.

Do you know where is the original article about the plan to migrate to GCC 7.2?

**Comment by kyleabeauchamp** [comment]
There's a status bar here: https://conda-forge.org/status/

There's also been a lot of chatter about it on their gitter: https://gitter.im/conda-forge/conda-forge.github.io

I can't say for sure whether there's a clear single "ticket" somewhere I can point to.

**Comment by tseemann** [comment]
Homebrew Mac is already using 7.x (and soon 8.x I believe?) and Linuxbrew is using 5.x and I think Conda has already moved to 7.x.   @sjackman @bgruening

**Comment by bgruening** [comment]
Yes conda-forge and with this bioconda is moving to 7.2.

**Comment by valeriuo** [comment]
Fixed by https://github.com/samtools/samtools/pull/952

**Comment by sjackman** [comment]
Ubuntu 18.04 LTS (Bionic Beaver) is using GCC 7.3.
