### ISSUE TITLE
Install libbam, libst, and associated header files in system directories

### ISSUE THREAD

**Issue by daheise** [samtools/samtools#957]
#### Is your feature request related to a problem? Please specify.

I am working on a project that involves samtools as a dependency. At this time, it does not appear libbam, libst, or the header files are put in system locations where is is easy to treat these items as dependencies. The project I am working on currently places samtools as a subdirectory, but I would prefer to record the dependency rather than the current solution.

#### Describe the solution you would like.

Install the libraries and header files in system directories. I have taken a stab at this [here](https://github.com/daheise/samtools/blob/install-lib/Makefile), derived from the 1.9 tag. I am happy to submit this as a PR.

**Comment by jkbonfield** [comment]
Which functions from libbam are you needing?

We've largely deprecated this as a feature and are hoping that most functionality is in htslib.

**Comment by daheise** [comment]
`bam_reg2bin` is the only feature I've seen in the code base I'm working on (libStatGen). 

```
SamRecord.cpp: In member function ‘uint16_t SamRecord::getBin()’:
SamRecord.cpp:1355:73: error: ‘bam_reg2bin’ was not declared in this scope
             bam_reg2bin(myRecordPtr->myPosition, get1BasedAlignmentEnd());      
                                                                         ^
SamRecord.cpp: In member function ‘bool SamRecord::fixBuffer(SamRecord::SequenceTranslation)’:
SamRecord.cpp:2491:73: error: ‘bam_reg2bin’ was not declared in this scope
             bam_reg2bin(myRecordPtr->myPosition, get1BasedAlignmentEnd()); 
```
