### ISSUE TITLE
samtools view '*' on CRAMs skips most unmapped read pairs.

### ISSUE THREAD

**Issue by acorvelo** [samtools/samtools#958]
#### Are you using the latest version of [samtools](https://github.com/samtools/samtools/releases/latest) and [HTSlib](https://github.com/samtools/htslib/releases/latest)? 
Yes.

 #### Please describe your environment.
Linux 3.10.0-693.17.1.el7.x86_64
gcc (GCC) 4.8.5 20150623

#### Please specify the steps taken to generate the issue, the command you are running and the relevant output.

`samtools view ${CRAM} '*'` appears to only output unmapped reads from the last block (based on their number) and not all unmapped read pairs. Running the same command on a BAM file generated from `${CRAM}` works as intended. 

I can confirm the behavior in version 1.7 as well.

**Comment by jkbonfield** [comment]
Confirmed.

Oddly a different bug exists in Scramble, which displays all the unaligned reads along with a few aligned ones at the start.  It's a related bug, but opposite impact.

Apologies.  We'll investigate.

**Comment by jkbonfield** [comment]
For what it's worth, it broke between 1.3 and 1.4.

The scramble bug is different, but that's all tied up with https://github.com/samtools/htslib/pull/666/files (which scares me!).  Timing is a bit awkward this week, but the fact we had it working once shows the indices are valid and it's simply a bug that crept in.

**Comment by acorvelo** [comment]
@jkbonfield thanks for the fix in such a short time.
