### ISSUE TITLE
Extracting the consensus sequence using vcfutils.pl vcf2fq but got different lengths

### ISSUE THREAD

**Issue by computingmachine** [samtools/samtools#965]
Hi,

I would like to extract the consensus sequence and use the mpileup command and the vcfutils.pl vcf2fq below, but I got different lengths from different individuals. Does this consider SNPs and INDEL? or only the SNPs?

samtools mpileup -uf ref.fa aln.bam | bcftools call -c | vcfutils.pl vcf2fq > cns.fq

**Comment by tseemann** [comment]
I suspect `bcftools consensus` is the preferred way now:
https://samtools.github.io/bcftools/howtos/consensus-sequence.html

**Comment by pd3** [comment]
That's right!
