### ISSUE TITLE
bam2depth.c not use bam_mplp_init_overlaps !

### ISSUE THREAD

**Issue by TuBieJun** [samtools/samtools#967]
I found the depth stat of "samtools depth" and "samtools mpileup" are different in the same position. Then I found that "bam2depth" not use the "bam_mplp_init_overlaps" func, when I add this, the results of two command is same.So cound you add this feature in the next release, becase an overlap pair reads shoud be counted once.

**Comment by eboyden** [comment]
+1 to add PE read overlap detection to samtools depth; for applications with significant read overlap (e.g. PCR-based library prep) this tool produces extremely inaccurate statistics

**Comment by jkbonfield** [comment]
I think if you want highly accurate depth taking into account read-pairs, excluding counting twice on short inserts that overlap, maybe adjusting for minimum mapping quality, etc, you'd be best off just running mpileup and taking the depth field from that.

If people wish samtools depth to be identical to mpileup then I have to wonder why depth exists at all.  IMO ideally depth should be much faster and simpler than it is now, to give people more viable choices between quick and dirty vs slow and accurate.

**Comment by valeriuo** [comment]
Fixed by https://github.com/samtools/samtools/pull/1241
