### ISSUE TITLE
samtools stats output for coverage problem when using -d and -p options

### ISSUE THREAD

**Issue by MbDiop** [samtools/samtools#969]
#### Are you using the latest version of [samtools](https://github.com/samtools/samtools/releases/latest) and [HTSlib](https://github.com/samtools/htslib/releases/latest)? If not, please specify.

The version is : 
samtools 1.9
Using htslib 1.9
Copyright (C) 2018 Genome Research Ltd.

 #### Please describe your environment.
- OS : Linux 3.10.0-229.4.2.el7.x86_64
- machine architecture : x86_64
- compiler : gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-28)

#### Please specify the steps taken to generate the issue, the command you are running and the relevant output.

`samtools stats` with `-d` and `-p` option, the numbers are not as expected (i.e increasing when one of these options is used).
The bed file : target.bed is coordinates sorted and 1-based and the bam file (BWA mem aligner) has been sorted by name, then fixed, then sorted by coordinates and duplicates have been marked.

- without `-d` & `-p` :  
`samtools stats -c 0,400,1 -t target.bed -@ 12 sample.sorted.fixed.rmdup.bam > run3.txt`
`grep ^COV run3.txt | head`
COV	[1-1]	1	1731933
COV	[2-2]	2	1934257
COV	[3-3]	3	2072770
COV	[4-4]	4	2148311
COV	[5-5]	5	2144974
COV	[6-6]	6	2122913
COV	[7-7]	7	2066358
COV	[8-8]	8	1995887
COV	[9-9]	9	1930248
COV	[10-10]	10	1857331

- with `-d` only :  
`samtools stats -c 0,400,1 -d -t target.bed -@ 12 sample.sorted.fixed.rmdup.bam > run1.txt`
`grep ^COV run1.txt | head`
COV	[1-1]	1	2136874
COV	[2-2]	2	2562029
COV	[3-3]	3	2834621
COV	[4-4]	4	2916941
COV	[5-5]	5	2912861
COV	[6-6]	6	2857366
COV	[7-7]	7	2761430
COV	[8-8]	8	2653116
COV	[9-9]	9	2530872
COV	[10-10]	10	2415065

- with -p only :  
`samtools stats -c 0,400,1 -p -t target.bed -@ 12 sample.sorted.fixed.rmdup.bam > run2.txt`
`grep ^COV run2.txt | head`
COV	[1-1]	1	1779786
COV	[2-2]	2	2000378
COV	[3-3]	3	2156698
COV	[4-4]	4	2243462
COV	[5-5]	5	2248256
COV	[6-6]	6	2221999
COV	[7-7]	7	2170451
COV	[8-8]	8	2097471
COV	[9-9]	9	2023382
COV	[10-10]	10	1959533

- with -d & -p :  
`samtools stats -c 0,400,1 -d -p -t target.bed -@ 12 sample.sorted.fixed.rmdup.bam > run4.txt`
`grep ^COV run4.txt | head`
COV	[1-1]	1	2197084
COV	[2-2]	2	2664684
COV	[3-3]	3	2963933
COV	[4-4]	4	3064502
COV	[5-5]	5	3071512
COV	[6-6]	6	3003725
COV	[7-7]	7	2910442
COV	[8-8]	8	2798751
COV	[9-9]	9	2675399
COV	[10-10]	10	2554479

Also I compared with the results of `samtools depth` (Are the overlapping reads and duplicates reads are take into account ?):
` samtools depth -a -b target.bed -m 0  sample.sorted.fixed.rmdup.bam | awk -F "\t" 'BEGIN{print "flag\toccurrences"} {a[$3]++} END{for(i in a)print i"\t"a[i]}' | sort -V | head -11`
0	1195393
1	2043672
2	2547436
3	2825031
4	2914376
5	2907715
6	2856748
7	2760536
8	2652391
9	2530775
10	2412818

**Comment by tseemann** [comment]
@valeriuo does `rmdup` mark, or _remove_ the duplicate reads?

also, `rmdup` has been deprecated in favour of `markdup` now. it marks by default, but can remove using `-r` option.

As for `-p` I am not sure. it seem related to `  -x, --ignore-overlaps   disable read-pair overlap detection` in `mpileup`.

**Comment by MbDiop** [comment]
Yes for the steps to generate the bam except for `rmdup`.
Sorry for the confusion but `rmdup` is just in the bam file name. I used `markdup` without the `-r` option so the duplicates are kept in the bam file.

You are right even if I specify `-c 0`  the `COV[0-0]` never appears in the output.

**Comment by valeriuo** [comment]
@MbDiop strange figures, indeed. While it's not unusual for some values to increase, as the count cascades down into smaller bins, in your case they all increase. What is the sequencing depth for this file?
Can we have an anonymized subset of your data that shows this behaviour?

**Comment by MbDiop** [comment]
@valeriuo you will find here : https://partage.gustaveroussy.fr/pydio_public/00b12c
the scripts used, the corresponding outputs, the bam file and the bed file only for the chr19. Tell me when you have finished to download the data. Thank you.

**Comment by valeriuo** [comment]
@MbDiop Done. Thank you!

**Comment by valeriuo** [comment]
@MbDiop the numbers check out. So it's nothing wrong with samtools.

To explain what is happening, I've made a BAM file with only the duplicate reads and run it through IGV. The attached pictures show the depth of duplication at various loci. As you can see, is larger than 10 in many places, and all those bases will be downgraded to lower bins in the coverage histogram, when the duplicate reads are removed. That is: a base that was accounted for in bin 50, with duplicates, would now sit in bin 8, without them, which leads to an increase in bin 8 counter.

![dup4](https://user-images.githubusercontent.com/6553979/48063300-84a04f80-e1bc-11e8-9d44-28ea6d33e327.png)

![dup5](https://user-images.githubusercontent.com/6553979/48063366-b0233a00-e1bc-11e8-9d6f-74921ef4995f.png)

![dup7](https://user-images.githubusercontent.com/6553979/48063377-b9140b80-e1bc-11e8-9c2c-eda10d442c07.png)

![dup8](https://user-images.githubusercontent.com/6553979/48063382-bd402900-e1bc-11e8-8db7-b4805b5058a7.png)

**Comment by MbDiop** [comment]
@valeriuo Thank you, it's clear for me now.
