### ISSUE TITLE
threads not correctly implemented in samtools stats ?

### ISSUE THREAD

**Issue by duartemolha** [samtools/samtools#973]
#### Are you using the latest version of [samtools]
samtools 1.9

 #### Please describe your environment
Linux 3.16.0-4-amd64
gcc (Debian 4.9.2-10+deb8u1) 4.9.2

#### Please specify the steps taken to generate the issue, the command you are running and the relevant output.
`samtools stats -@ 16 bamfile.bam 
`I also tested 
`samtools stats -@ 16 bamfile.bam chr1:1-XX chr2:1-YY . etc...
`
When using -@ to make more threads, Samtools spools the additional threads (I see them using htop)
however, only 1 thread is active all others are inactive

I thought maybe that samtools did not know how to split the bam file to output the stats when giving only the bam file, so I tested providing as additional arguments, each chromosome but still the spooled threads remaining inactive (only 1 is active for the duration of the running of the process

I have timed the command using threads and not using threads and the differences are negligible.
Am I doing something wrong?

Many thanks

Duarte

**Comment by jkbonfield** [comment]
Every command has the capability to use threads for decoding and encoding of BAM and CRAM, but only a few also use the thread pool for others things ("samtools sort" is perhaps the only one).

If the command itself has a very fast main thread - eg "samtools flagstat" as is dominating by decode or encode, then it'll multithread well.  Unfortunately samtools stats spends a long time in the main thread so giving it more threads only speeds up a small portion of the total work load.

The correct solution is to so as you say - batching up portions of the file to compute stats independently and then merge at the end.   It's not yet been done though.  Sorry.

**Comment by jkbonfield** [comment]
Closing this as the question has been answered.  Improving multi-threading as a whole across the package is a broader and separate issue.

**Comment by wzj42** [comment]
> Every command has the capability to use threads for decoding and encoding of BAM and CRAM, but only a few also use the thread pool for others things ("samtools sort" is perhaps the only one).
> 
> **If the command itself has a very fast main thread - eg "samtools flagstat" is dominated by decode or encode - then it'll multithread well.** Unfortunately samtools stats spends a long time in the main thread so giving it more threads only speeds up a small portion of the total work load.
> 
> The correct solution is to so as you say - batching up portions of the file to compute stats independently and then merge at the end. It's not yet been done though. Sorry.

Sorry to bring this old issue up. 

When you talked about "flagstat will multithread well", do you mean it works well anyhow? 
Or like what @duartemolha said, need to split the bam file manually like "chr1:1-XX chr2:1-YY . etc..." to feed the multithread? 

Additionally, I am using cluster computing, that I could apply for multiple nodes and then multiple processors for each node. 
Then when we mentioned multithread/argument"-@" here for samtools, do you mean the multi-node? or multi-processor?

**Comment by jkbonfield** [comment]
We really need a broader issue than samtools stats to cover this.

Samtools multi-threads the file decode and encode process, eg the gzip part of reading a BAM file.  It does not multi-thread most of the "work" part of algorithms.  Eg consider stats to be decode + work, with decode threaded and work not.  About the only sub-command with decent work-load threading is samtools sort.

Long term we likely need a way of breaking a file into regions so we can parallelise work packages with a merge step at the end.  This is a considerable task and hasn't yet been done.  Hence the threading isn't "broken" or "incorrectly implemented".  It's simply absent in some parts of the code.

For now, you'll need to manually split up by regions and use something like gnu parallel.
