### ISSUE TITLE
Bam to Fastq

### ISSUE THREAD

**Issue by eleniadam** [samtools/samtools#976]
Hello,

I am using samtools 1.9 & HTSlib 1.9 on Linux.

- The steps I am taking are:
samtools view -S -b cell_line.sam > cell_line.bam
samtools sort cell_line.bam cell_line.sorted
samtools index cell_line.sorted.bam
samtools view -b cell_line.sorted.bam chr18:131694-331693 > chr18.bam

- and then the **problem** occurs:
samtools bam2fq chr18.bam > chr18.fastq

Output (no file generated):
[M::bam2fq_mainloop] discarded **0** singletons
[M::bam2fq_mainloop] processed **0** reads

**NOTE**: For the same chr18.bam file, _bedtools generates a fastq file_, so it doesn't seem to be an issue of the bam file itself.

- When I ran samtools flagstat chr18.bam, this was the output:
2 + 0 in total (QC-passed reads + QC-failed reads)
0 + 0 secondary
2 + 0 supplementary
0 + 0 duplicates
2 + 0 mapped (100.00% : N/A)
0 + 0 paired in sequencing
0 + 0 read1
0 + 0 read2
0 + 0 properly paired (N/A : N/A)
0 + 0 with itself and mate mapped
0 + 0 singletons (N/A : N/A)
0 + 0 with mate mapped to a different chr
0 + 0 with mate mapped to a different chr (mapQ>=5)

I have been trying to resolve this with multiple combinations of commands, I tried sorting and indexing the chr18.bam file as well, but there was no difference, it is not obvious to me why it is not working...
Are there missing steps that I should be executing before the bam2fq command?

Thank you in advance,
Eleni

P.S. Also, is it possible to regulate the number of N's in the output fastq file depending on the input parameters?

**Comment by eleniadam** [comment]
Unfortunately the same issue exists when I follow this list of steps...

Was there a past version of samtools that was able to write out the supplementary alignments??

The reason I am asking is because a colleague said that in the past they used the **same** bam file which I have and then extracted the fastq with samtools. 

But first of all, samtools does not work at all for me and also, when I use bedtools, the fastq file has extra N's which their (generated with samtools) fastq file does not contain. That is why I asked about the N's.

Was there maybe an older version of samtools or another samtools tool (like bam2fq) that would work?

Thank you very much for your help!!

**Comment by eleniadam** [comment]
> The flagstats output says:
> 
> ```
> 2 + 0 supplementary
> ```
> 
> Currently `bam2fq` does not write out supplementary alignments, and there's no way to turn them on (This may change in a future update). I think that explains why you didn't get any output.
> 
> Incidentally, your list of steps doesn't look quite right. For samtools 1.9 you need to use the `-o` option to specify the output file for sort. Sort can also take SAM files as input, so you should use:
> 
> ```
> samtools sort -o cell_line.sorted.bam cell_line.sam
> samtools index cell_line.sorted.bam
> samtools view -b cell_line.sorted.bam chr18:131694-331693 > chr18.bam
> ```
> 
> Also, `bam2fq` expects name sorted (or at least collated) data. I don't think it matters in this case as it looks like the reads were not paired, but if you do have paired reads you should run the subset through `samtools sort -n` or `samtools collate` before using `samtools bam2fq`.
> 
> What do you mean by "regulate the number of N's"? Would you like to filter out reads (or read pairs) with too many N's in them?

**Comment by daviesrob** [comment]
It would have to be a very old version.  Samtools 0.1.19 pre-dates supplementary alignments, so it doesn't try to filter them out.  By the time 0.1.20 came out, some code to remove them had been added (in revision f3b8f76ed, as far as I can tell).

I expect the most likely explanation is that your colleague used samtools 0.1.19.

**Comment by eleniadam** [comment]
Thank you very much for your help, indeed samtools 0.1.19 was able to produce a fastq file.

The fastq file is exactly the same as the one bedtools produced, which is good to know that the conversion is consistent in both software. 
Unfortunately, it is still unknown why there exist extra N's in the current output files, but that's another issue to solve.

Thank you very much,
Eleni
