### ISSUE TITLE
Provide `--output-idx` and `--input-idx` for index output location

### ISSUE THREAD

**Issue by pkerpedjiev** [samtools/samtools#983]
#### Is your feature request related to a problem? Please specify.

The current `--output` option specifies the location of an output fasta file. There is no corresponding option for specifying where the index file should be placed. That means that it's always placed in the same directory as the input fasta. 

See https://github.com/samtools/samtools/issues/970#issuecomment-439950989

#### Describe the solution you would like.

It would be helpful to have `--output-idx` and corresponding `--input-idx` option to specify where the to either store or load the index file, respectively.

**Comment by whitwham** [comment]
This is a reminder to myself.  In indexing mode make --output a synonym for --output-idx.
