### ISSUE TITLE
Samtools

### ISSUE THREAD

**Issue by chenyaya80119** [samtools/samtools#990]
#### Describe the solution you would like.
When i convert SAM to BAM,exits some problem like this ?Is there anyone could help me.thanks!

$samtools view  -bS -o T44.bam T44.sam
[W::sam_read1] parse error at line 1
[main_samview] truncated file.

**Comment by valeriuo** [comment]
Please use the issue [template](https://github.com/samtools/samtools/issues/new?template=Bug_report.md) and fill in the requested information. 
There is nothing wrong with the command, so it looks like **T44.sam** might be corrupt. You can view its content with _less_, as it is a text format.

**Comment by chenyaya80119** [comment]
Thank you for you help .The T44.sam  file looks like this:
[M::bwa_idx_load_from_disk] read 0 ALT contigs
@SQ     SN:c1_g1_i1     LN:341
@SQ     SN:c2_g1_i1     LN:861
@SQ     SN:c3_g1_i1     LN:349
@SQ     SN:c4_g1_i1     LN:263
@SQ     SN:c6_g1_i1     LN:395
@SQ     SN:c7_g1_i1     LN:807
@SQ     SN:c8_g1_i1     LN:1207
@SQ     SN:c9_g1_i1     LN:202
@SQ     SN:c12_g1_i1    LN:336
@SQ     SN:c13_g1_i1    LN:316
@SQ     SN:c14_g1_i1    LN:1181
@SQ     SN:c15_g1_i1    LN:693
@SQ     SN:c16_g1_i1    LN:250
@SQ     SN:c17_g1_i1    LN:309
@SQ     SN:c18_g1_i1    LN:813
@SQ     SN:c19_g1_i1    LN:424
@SQ     SN:c20_g1_i1    LN:630
@SQ     SN:c23_g1_i1    LN:207
@SQ     SN:c24_g1_i1    LN:566
@SQ     SN:c25_g1_i1    LN:270
@SQ     SN:c26_g1_i1    LN:359
@SQ     SN:c27_g1_i1    LN:357
@SQ     SN:c29_g1_i1    LN:457
@SQ     SN:c30_g1_i1    LN:413
@SQ     SN:c31_g1_i1    LN:506
@SQ     SN:c32_g1_i1    LN:426
@SQ     SN:c33_g1_i1    LN:249
@SQ     SN:c34_g1_i1    LN:349
@SQ     SN:c35_g1_i1    LN:529
@SQ     SN:c36_g1_i1    LN:494
@SQ     SN:c37_g1_i1    LN:412
@SQ     SN:c38_g1_i1    LN:508
@SQ     SN:c38_g1_i2    LN:521
@SQ     SN:c39_g1_i1    LN:293
@SQ     SN:c40_g1_i1    LN:421

**Comment by daviesrob** [comment]
It should be `@SQ` (capital letters) instead of `@sq`.  Also, are there spaces or tabs between the columns (you should be using tabs)?

See the [SAM specification](http://samtools.github.io/hts-specs/SAMv1.pdf) for more information.

**Comment by jmarshall** [comment]
That lowercase `@SQ` is likely just GitHub's formatting. The real problem is the bwa log message (“[M::bwa_idx_load_from_disk] read 0 ALT contigs”) that's been captured into the SAM output.

Use `bwa aln -f T44.sam …` or `bwa mem -o T44.sam …` instead of batch system redirections.

**Comment by chenyaya80119** [comment]
The T44.sam file looks like this:
[M::bwa_idx_load_from_disk] read 0 ALT contigs
@SQ     SN:c1_g1_i1     LN:341
@SQ     SN:c2_g1_i1     LN:861
@SQ     SN:c3_g1_i1     LN:349
@SQ     SN:c4_g1_i1     LN:263
@SQ     SN:c6_g1_i1     LN:395
@SQ     SN:c7_g1_i1     LN:807
@SQ     SN:c8_g1_i1     LN:1207
@SQ     SN:c9_g1_i1     LN:202
@SQ     SN:c12_g1_i1    LN:336
@SQ     SN:c13_g1_i1    LN:316
@SQ     SN:c14_g1_i1    LN:1181
@SQ     SN:c15_g1_i1    LN:693
@SQ     SN:c16_g1_i1    LN:250
@SQ     SN:c17_g1_i1    LN:309
@SQ     SN:c18_g1_i1    LN:813
@SQ     SN:c19_g1_i1    LN:424
@SQ     SN:c20_g1_i1    LN:630
@SQ     SN:c23_g1_i1    LN:207
@SQ     SN:c24_g1_i1    LN:566
@SQ     SN:c25_g1_i1    LN:270
@SQ     SN:c26_g1_i1    LN:359
@SQ     SN:c27_g1_i1    LN:357

**Comment by wdecoster** [comment]
Then nohup is your problem, causing stderr logs to end up in stdout.

**Comment by chenyaya80119** [comment]
> Then nohup is your problem, causing stderr logs to end up in stdout.
Hello,wdecoster .Thanks for your help .But when i try again without nohup,
the same problem has appeared again.
