### ISSUE TITLE
BWA

### ISSUE THREAD

**Issue by chenyaya80119** [samtools/samtools#991]
I am attempting to get a SAM file  from BWA.
Here is the command line I use when attempting to do this:

 bwa index -a bwtsw Trinity.fasta 

bwa mem -t 4 Trinity.fasta T44_gan_1.clean_val_1.fq.gz  T44_gan_2.clean_val_2.fq.gz > T44_gan.sam
However, I continually get this error like this:
[M::bwa_idx_load_from_disk] read 0 ALT contigs
@SQ     SN:c1_g1_i1     LN:341
@SQ     SN:c2_g1_i1     LN:861
@SQ     SN:c3_g1_i1     LN:349
@SQ     SN:c4_g1_i1     LN:263
@SQ     SN:c6_g1_i1     LN:395
@SQ     SN:c7_g1_i1     LN:807
@SQ     SN:c8_g1_i1     LN:1207
@SQ     SN:c9_g1_i1     LN:202
@SQ     SN:c12_g1_i1    LN:336
@SQ     SN:c13_g1_i1    LN:316
@SQ     SN:c14_g1_i1    LN:1181
@SQ     SN:c15_g1_i1    LN:693
@SQ     SN:c16_g1_i1    LN:250
@SQ     SN:c17_g1_i1    LN:309
@SQ     SN:c18_g1_i1    LN:813
@SQ     SN:c19_g1_i1    LN:424
@SQ     SN:c20_g1_i1    LN:630
@SQ     SN:c23_g1_i1    LN:207
@SQ     SN:c24_g1_i1    LN:566
@SQ     SN:c25_g1_i1    LN:270
@SQ     SN:c26_g1_i1    LN:359
@SQ     SN:c27_g1_i1    LN:357
@SQ     SN:c29_g1_i1    LN:457
@SQ     SN:c30_g1_i1    LN:413
@SQ     SN:c31_g1_i1    LN:506
@SQ     SN:c32_g1_i1    LN:426
@SQ     SN:c33_g1_i1    LN:249
@SQ     SN:c34_g1_i1    LN:349
@SQ     SN:c35_g1_i1    LN:529
The first line may be not right ,I've attempted to solve this, and looked online but could find nothing that helps me understand what the error is and how to troubleshoot it. Can anyone help?

**Comment by jkbonfield** [comment]
This looks like you are mixing up stderr and stdout to the same place.  The SAM file here contains general chatter from bwa.

This is a general unix question (and one relating to usage of bwa, not samtools), so I am closing the issue.   I would recommend you ask for help on the bwa email list instead.

https://sourceforge.net/projects/bio-bwa/lists/bio-bwa-help

**Comment by chenyaya80119** [comment]
> This looks like you are mixing up stderr and stdout to the same place. The SAM file here contains general chatter from bwa.
> 
> This is a general unix question (and one relating to usage of bwa, not samtools), so I am closing the issue. I would recommend you ask for help on the bwa email list instead.
> 
> https://sourceforge.net/projects/bio-bwa/lists/bio-bwa-help

Thank you for your patience.
