### ISSUE TITLE
[E::sam_parse1] missing SAM header 

### ISSUE THREAD

**Issue by zhengjiantao** [samtools/samtools#993]
when I use the command 'samtools view -bS GSM653001_BMM_KO_aligned.SAM > GSM653001_BMM_KO_aligned.bam' 

I got an error as follows:
[E::sam_parse1] missing SAM header
[W::sam_read1] Parse error at line 3
[main_samview] truncated file.

the header of SAM file using command 'samtools view -h GSM653001_BMM_KO_aligned.SAM':
@HD	VN:1.0	SO:sorted
@PG	ID:TopHat	VN:1.0.14	CL:/Users/johannes/bin/tophat/bin/tophat --solexa-quals --max-intron 30000 --output-dir BMM_KO/tophat --num-threads 2 /Volumes/BP_NextGen/Johannes/RNA-seq/pipeline/index/mm9/mm9 /Volumes/BP_NextGen/Johannes/RNA-seq/pipeline/reads/Upf2_KO_Liver&BMM/BMM/unspiked/XXXkarTBRAASE.fq

How to solve this problem?
Thanks advanced!

**Comment by valeriuo** [comment]
The problem is you have mapped reads in your file, but no `@SQ` line in the header to indicate where those reads are mapped to (a reference). The error message could be more descriptive, though.

You can either check the option menu of **tophat** or **bowtie** to see how the` @SQ` lines are supplied to the SAM file, or provide them to **samtools** via **-t** option.

```
-t FILE     
A tab-delimited FILE. Each line must contain the reference name in the first column and the length of the reference in the second column, with one line for each distinct reference. Any additional fields beyond the second column are ignored. This file also defines the order of the reference sequences in sorting. If you run: `samtools faidx <ref.fa>', the resulting index file <ref.fa>.fai can be used as this FILE.

**Comment by zhengjiantao** [comment]
@valeriuo 
Thanks, I check the sam file, finding that it lost @SQ. I'll try to use -t to manuallly assign reference.

**Comment by zhengjiantao** [comment]
@valeriuo 
I checked the sam file. It dose no @SQ.
So if I want to use -t. What file I should use?
The information of sam file is as follows:
![image](https://user-images.githubusercontent.com/41890364/50219252-96832e00-03c9-11e9-9dab-ea90ca0b6d46.png)

**Comment by zhengjiantao** [comment]
@valeriuo
I checked the sam file. It dose no @sq.
So if I want to use -t. What file I should use?
The information of sam file is as follows:
![image](https://user-images.githubusercontent.com/41890364/50219293-ba467400-03c9-11e9-994c-c3fe372fa3b4.png)

**Comment by valeriuo** [comment]
It has to be the reference file (usually a FASTA) used by the aligner that produced the SAM file.

**Comment by genomiki** [comment]
madarchod

**Comment by genomiki** [comment]
ls *_out.sam | sed 's+_out.sam++g' | while read i; do samtools view -@ 70 -bS $i\_out.sam > bam/$i.bam; done

this is the best code to use
