### ISSUE TITLE
Width of samtools tview output not tunable

### ISSUE THREAD

**Issue by standage** [samtools/samtools#994]
When running `samtools tview` in default mode, it brings up an interactive scrollable viewer that fills the entire terminal window. The `-d T` and `-d H` options are cool and instead allow writing the output to a file -- extremely useful when examining large numbers of loci. However, there appears to be no way to control the width of the output generated in "text" or "HTML" display mode. One would expect that running `samtools tview -d T -p chr1:501-700 sample1.bam refr.fasta` would capture a window 200 nucleotides in width, but it only captures a default 80 nucleotides. Changing the width of the terminal window likewise has no effect.

- samtools 1.9
- Mac OS X and CentOS 7
- clang and gcc

**Comment by finswimmer** [comment]
I support this suggestion. Would be very useful.

**Comment by splaisan** [comment]
I second this feature request

**Comment by tseemann** [comment]
@standage 

Looking at the code for the HTML view, I see this:
https://github.com/samtools/samtools/blob/develop/bam_tview_html.c#L320
And this:
https://github.com/samtools/samtools/blob/develop/bam_tview_html.c#L348-L352

So maybe try `COLUMNS=200 samtools tview -d H -p CHR:X-Y aln.bam ref.fasta`

**Comment by jkbonfield** [comment]
This stumped me for a while until I realised `$COLUMNS` in bash is a local shell variable and not an environment variable (gah - why put it uppercase! Lead up the garden path...)

Thus this bizarre command does the trick!

`COLUMNS=$COLUMNS samtools tview -d T -p 1:234567 foo.bam`

**Comment by jkbonfield** [comment]
I'll fix the documentation so the use of `$COLUMNS` is mentioned.

**Comment by standage** [comment]
Thanks @tseemann and @jkbonfield!
