### ISSUE TITLE
samtools mpileup -l give me an empyt file

### ISSUE THREAD

**Issue by Jordi-V** [samtools/samtools#997]
Dear all,

I try to run the samtools mpileup in multiple samples and by regions. For this I use this command:

samtools mpileup -b files -l region.bed --no-BAQ --min-MQ 1 --fasta-ref /gpfs/projects/bsc05/jordivalls/GCAT/human_ref_PANCANCER/genome.fa  > sample_part_bed.mpileup

wher the -b files are my bam files one per line and the -l the region which I want to check.
the region.bed contains this region tab delimited:
22      120000  135000

When I run this job, the exectuion during aroun 45 minutes and after that breaks, No breaks due to memory because I checked it. My surprise is when I use the same command above but I dont use the -l option... the mpileup file is start to include information... On the other hand, with -l option the file is empty always... The bam file is sorted following the best practices of GATK... So could someone tell me what I'm doing wrong??

The header of my bam files doesn't contain the chr in chromosome header... so I supose that my bed file doesn't have to contain the chr in the chromosome column...

Thanks for your help

JOrdi

**Comment by daviesrob** [comment]
What happens when samtools stops?  Does it print any error messages?
How many bam files are listed in `files`, and were they all aligned to the same reference?
If you run `samtools view` on this region, do you get any coverage?

**Comment by valeriuo** [comment]
Please reopen with the requested information.
