### ISSUE TITLE
samtools reheader: modify header with external program

### ISSUE THREAD

**Issue by ghuls** [samtools/samtools#999]
#### Is your feature request related to a problem? Please specify.

It would be nice if `samtools reheader` would be able to:
  - read files from stdin
  - let the header be processes (modified) by an external program (which accepts the header on stdin and writes the modified header to stdout)
  - write this modified header to stdout (in BAM or CRAM format) before writing the reads of the original BAM/CRAM file 

This would be very helpful in cases where you need to modify the header, when you don't want to write the output of the previous filtering steps to a file.

#### Describe the solution you would like.

```bash
samtools view -bu -q 10 sample.bam \
    | samtools reheader -c modify_header.sh - \
    | samtools sort -O BAM > sample_q10.sorted.bam
```

**Comment by daviesrob** [comment]
We can look into this.  We'd need to be careful about deadlocks when sending data through the filter (threads should fix this) and I'm not too sure what will happen with CRAM but it should be possible.

**Comment by ghuls** [comment]
Thanks a lot, it would be really helpful if this is implemented.

**Comment by ghuls** [comment]
Thanks a lot.
